nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/ChangeMasterPasswordCommandDAS.java
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/LocalStrings.properties

Fixes #141 GLASSFISH-21017
Domain keystore becomes corrupt if change-master-password is used with a password shorter than 6 characters

Fix for GLASSFISH-21017

---

nucleus/security/ssl-impl/src/main/java/com/sun/enterprise/security/ssl/manager/UnifiedX509KeyManager.java

Fixes #85 GLASSFISH-21249 UnifiedX509KeyManager calls incorrect method on wrapped Key Manager.
getServerAliases calls getClientAliases on the wrapped key manager.

Fix UnifiedX509KeyManager GLASSFISH-21249

---

appserver/pom.xml

Upgrading Mojarra to 2.2.9 builds the Jenkins build but not local builds. Revert until we can figure that out.

Revert Mojarra

---

appserver/batch/glassfish-batch-connector/pom.xml
appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/MySqlPersistenceManager.java
appserver/batch/glassfish-batch-connector/src/main/java/org/glassfish/batch/spi/impl/BatchRuntimeHelper.java
appserver/pom.xml
nucleus/pom.xml

Integrate the released JBatch upgrade, now it is on Maven Central and remove dependency on Payara patched JBatch.
Also fixes a bug in the MySQL Persistence where checking the schema exists failed.

Integrate JBatch 1.0.1-b4

---

appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/impl/PayaraCacheKeyInvocationContext.java

Replace use of HashSet with LinkedList as order of parameters used in the key could be different due to lack of order of iteration in a HashSet

Fix bug whereby Cache Key could be different for the same parameters

---

appserver/distributions/glassfish/pom.xml
appserver/distributions/minnow/pom.xml
appserver/distributions/web/pom.xml
appserver/extras/embedded/all/pom.xml
appserver/extras/embedded/nucleus/pom.xml
appserver/extras/embedded/pom.xml
appserver/extras/embedded/web/pom.xml
appserver/installer/pom.xml
appserver/javaee-api/javax.javaee-api/pom.xml
appserver/javaee-api/javax.javaee-endorsed-api/pom.xml
appserver/javaee-api/javax.javaee-web-api/pom.xml
appserver/javaee-api/pom.xml

The maven-release plugin missed some poms, I've manually updated them

Update version numbers for poms missed by maven-release-plugin

---

nucleus/distributions/payara-minimal/pom.xml
nucleus/distributions/pom.xml

Add cluster commands back into payara-minimal. This means create-instance and start-instance commands can be used to create additional standalone instances of payara-minimal. 
This is very useful for creating hazelcast "storage" nodes for a full Payara installation.

Adds cluster back into payara-minimal

---

appserver/web/web-ha/src/main/java/org/glassfish/web/ha/session/management/ReplicationWebEventPersistentManager.java

In a standalone instance with Availability enabled in the server config and on the deployment and with Hazelcast selected as a persistent session store a null pointer is thrown.
Preventing the null pointer allows standalone instances to share session state within Hazelcast and to act as a "cluster". Now standalone instances can share session state within hazelcast and therefore have persistent sessions similar to a "cluster".

Prevent null pointer exception when GMS is not enabled.

---

appserver/extras/embedded/web/pom.xml

Added the hazelcast package to the payara-web-embedded distribution.
Tested by checking if the hazelcast jar is packaged in the jar, which it is.
Also tested by adding the embedded jar to NetBeans and seeing if the Hazelcast packages were available, which they are.

Add hazelcast dependency to payara-web-embedded pom

---

nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java

- caused random problems with restarts
- related to problems in ear applications
- related Hazelcast code will be changed in it's later versions(!)(after 3.4)

Payara #154 - Removed the Classloader hack for older Hazelcast versions

---

appserver/transaction/jts/src/main/java/com/sun/enterprise/transaction/jts/JavaEETransactionManagerJTSDelegate.java

Early creation of TX Manager is creating OSGI circular dependency problems. Reverting TX Manager change.

Revert early creation of TX Manager due to OSGI circular dependencies

---

appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/CachePutInterceptor.java
appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/CacheResultInterceptor.java
appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/JSR107Producer.java
appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/impl/PayaraCacheResolverFactory.java
appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/impl/PayaraGeneratedCacheKey.java
appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/impl/PayaraTCCLObjectInputStream.java
appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/impl/PayaraValueHolder.java

Fix #230 by Holding value objects serialized into a Payara Holder class for CDI. This ensures CDI works as expected on war defined classes.

Serialize jcache cdi Fixes #230

---

nucleus/pom.xml

For the record the diff from glassfish-corba-orb 4.0.1 is;
```
diff -r 5541165fd78e orbmain/src/main/java/com/sun/corba/ee/impl/encoding/CDRInputStream_1_0.java
--- a/orbmain/src/main/java/com/sun/corba/ee/impl/encoding/CDRInputStream_1_0.java	Fri Mar 20 09:34:40 2015 -0400
+++ b/orbmain/src/main/java/com/sun/corba/ee/impl/encoding/CDRInputStream_1_0.java	Sat Apr 18 08:28:48 2015 +0100
@@ -144,7 +144,6 @@
private static final OMGSystemException omgWrapper = OMGSystemException.self;
private static final String K_READ_METHOD = "read";
private static final int MAX_BLOCK_LENGTH = 0x7fffff00;
-    protected static final String EMPTY_STRING = "";
protected BufferManagerRead bufferManagerRead;
protected ByteBuffer byteBuffer;
@@ -497,7 +496,7 @@
// zero to mean empty string.
//
if (len == 0) {
- …
```

Fix #251 by patching glassfish-corba

---

appserver/packager/pom.xml
appserver/pom.xml

Removes the verifier packages from the build, since they are not used in the final packages

Remove verifier from build

---

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/accesslog/DefaultAccessLogFormatterImpl.java

Was working on glassfish 3.1.2.2, fails on glassfish 4.1.

Add support for access-logging of session attributes

---

nucleus/payara-modules/payara-micro/src/main/resources/payara-boot.properties

added default system property java.net.preferIPv4Stack=true. This can still be overridden by setting to false on the command line.

Fixes #341

---

appserver/packager/glassfish-ha/pom.xml
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/MasterPasswordFileManager.java
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/ChangeMasterPasswordCommandDAS.java
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/LocalServerCommand.java
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/pe/PEFileLayout.java
nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/ChangeNodeMasterPasswordCommand.java
nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/CreateLocalInstanceCommand.java
nucleus/common/common-util/src/main/java/com/sun/appserv/management/client/prefs/MemoryHashLoginInfoStore.java
nucleus/common/common-util/src/main/java/org/glassfish/security/common/FileProtectionUtility.java
nucleus/common/common-util/src/main/java/org/glassfish/server/ServerEnvironmentImpl.java

Addresses issues #333, #334, and #335 
Factors out functionality for setting 0600 file mode on a specific file to a common utility class which uses NIO2 Files api with PosixFilePermission to set the mode.  Various classes have been updated to use this utility class rather than using ProcessBuilder.  Proper detection of PosixFileAttributeSupport has been implemented in the utility class to make it safe for platforms such as Windows using filesystems that do not support posix file permissions.
These changes do NOT replace all places in the source code where ProcessBuilder+chmod are used... only the places where explicitly setting 0600 with chmod were used.

master-password & gfclient pass file permissions via NIO2 file attribute api rather than chmod-via-ProcessBuilder

---

nucleus/payara-modules/payara-micro/src/main/java/fish/payara/micro/PayaraMicro.java
nucleus/payara-modules/payara-micro/src/main/java/fish/payara/micro/PortBinder.java

Adds auto bind functionality to the `--port` and `--sslPort` options.
Similar to how Hazelcast works, if the HTTP or HTTPS port is busy and auto bind is enabled, it will now try to find an empty port on the next x ports.

Automatically increment busy payara micro http and https ports

---

appserver/admingui/payara-console-extras/src/main/resources/hazelcast/hazelcastConfigurationCluster.jsf
appserver/admingui/payara-console-extras/src/main/resources/hazelcast/hazelcastConfigurationServer.jsf
appserver/admingui/payara-console-extras/src/main/resources/hazelcast/hazelcastConfigurationStandalone.jsf
nucleus/cluster/admin/src/main/resources/META-INF/config-files

Also fix length of hazelcast configuration path in admin console so that custom hazelcast configuration files can be placed into the instance configuration directory and replicated to the instance

PAYARA-270 enable hazelcast-configuration synchronisation

---

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java

During deployment an @Startup EJB can submit a Batch Job or ManagedExecutorService task. However the Executor Service was checking the domain.xml to see if the referenced application was enabled although its state had not been written to the domain.xml.
This race condition caused the task/job submission to fail. This pull request fixes this.

PAYARA-220 fixes #204  still submits executor task during deployment.

---

nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/embeddable/DeployerImpl.java
nucleus/payara-modules/payara-micro/src/main/java/fish/payara/micro/PayaraMicroRuntime.java

When deploying from an Input Stream in the new PayaraRuntime api a temp context root was created. This is now by default the application name and can be configured.
Also added an undeploy api

Fix bug whereby could not set context root 

---

appserver/web/admin/src/main/java/org/glassfish/web/admin/cli/CreateProtocol.java

Fixes #371 create-protocol CLI command correctly creates ssl subtag if security is enabled. Also disables SSLv3 automatically in the new protocol.

PAYARA-331 fixes #371 

---

nucleus/payara-modules/payara-micro/src/main/java/fish/payara/micro/PayaraMicro.java

- In order for `PayaraMicro` class to load `payara-bootstrap.properties` in Gradle task execution context, chage the way to load it.
- Project : payara-modules/payara-micro
- Class : `fish.payara.micro.PayaraMicro`
- Line : 1008
- Before : `ClassLoader.getSystemResourceAsStream(String)`
- After : `getClass().getClassLoader().getResourceAsStream(String)`
- Reason : In Gradle task execution context, `ClassLoader.getSystemResourceAsStream("payara-bootstrap.properties")` returns `null` so that payara-micro server cannot get started.

Changed the way to load payara-bootstrap.properties.

---

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EjbThreadPoolExecutor.java
appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/startup/EjbApplication.java
appserver/jms/jms-core/src/main/java/com/sun/enterprise/connectors/jms/system/ActiveJmsResourceAdapter.java
appserver/orb/orb-connector/src/main/java/org/glassfish/enterprise/iiop/api/GlassFishORBHelper.java
appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/GlassFishORBManager.java
appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/TimeoutManager.java
appserver/web/war-util/src/main/java/com/sun/enterprise/glassfish/web/WarHandler.java
appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
appserver/web/weld-integration/src/main/java/org/glassfish/weld/BeanDeploymentArchiveImpl.java
nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/InvocationManager.java
nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/InvocationManagerImpl.java
nucleus/common/internal-api/src/main/java/org/glassfish/internal/data/ApplicationInfo.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ExecutorServiceFactory.java
nucleus/deployment/admin/pom.xml
nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/DeployCommand.java
nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/PostStateCommand.java
nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/UndeployCommand.java
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/util/CleanupPostBoot.java

A load of work to fix a number of classloader leaks and filehandles kept open to make Payara Server more robust on redeployment of applications. Should help #434 #445

Payara 457 classloader work

---

appserver/admin/runtime/mgmt-infra/pom.xml
appserver/extras/embedded-shell/pom.xml
appserver/orb/orb-connector/pom.xml
appserver/resources/resources-connector/pom.xml
appserver/security/security-dol/pom.xml
appserver/tests/paas/multiple-spe-test/mydb-plugin/pom.xml
appserver/transaction/jta-xa/pom.xml
nucleus/pom.xml

upgraded hk2.version and hk2.plugin.version to 2.4.0.b32
also used hk2-core instead of -core dependency since -core looked obsolete.

PAYARA-388 - Server log displays webappClassLoader severe warnings on shutdown

---

appserver/jms/gf-jms-injection/src/main/java/org/glassfish/jms/injection/JMSCDIExtension.java
appserver/web/web-sse/src/main/java/org/glassfish/sse/impl/ServerSentEventCdiExtension.java

We have 2 extensions on board within our codebase, ServerSentEventCdiExtension and JMSCDIExtension. With Weld 2.x these warning occur when we handle generic types in ProcessAnnotatedType.
They need to be narrowed down by using the @WithAnnotations annotation, as advised in the warning message. I first did some tricks with <weld:exclude> but didn't turned out good so moved 
over by modifying the extensions' code.

used @WithAnnotations to narrow down the generic type used.

---

appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/PostgresJDBCConstants.java
appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/PostgresPersistenceManager.java

Resolve a problem using PostgreSQL as JBatch job repository.
Postgres Multi Version Concurrency means Foreign Key referencing is not blocked by outstanding update locking.
Retry marking a job as started until the row is available and updated as a work-around.
Fixes #195

Payara 222

---

appserver/web/weld-integration/pom.xml
appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionalInterceptorRequired.java
appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionalInterceptorRequiresNew.java
appserver/web/weld-integration/src/test/java/org/glassfish/cdi/transaction/TransactionScopedBeanTest.java

Fixes #505 
Even though a transaction is created correctly by the interceptor. Resources e.g. DataSources are not enlisted into the global transaction so do not behave as expected.

PAYARA-510 fixes 505 ensures resources are enlisted into the transaction

---

nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/DisableCommand.java

Disable command was not executing correctly on a cluster during undeployment due to not matching the cluster target name with the server name. This is a regression introduced by fixing #433 and had the effect of JNDI names not being removed even though the application was correctly unloaded.

PAYARA-511 fixes #492

---

appserver/packager/metro/pom.xml
appserver/pom.xml
appserver/security/webservices.security/pom.xml
appserver/webservices/jsr109-impl/pom.xml
appserver/webservices/metro-glue/pom.xml
appserver/webservices/soap-tcp/pom.xml

in order to get this pull request merged and its build done successfully, first the pull request linked at: https://github.com/payara/Payara_PatchedProjects/pull/7 needs to be merged to the payara:master. This is needed because the modified webservices-osgi.jar defined with payara classifier can only be retrieved from our github based maven repository this way.

PAYARA-446-Multiple cookies cannot be added using Headers.putAll()

---

appserver/ejb/ejb-timer-service-app/src/main/webapp/WEB-INF/classes/META-INF/orm.xml
appserver/ejb/ejb-timer-service-app/src/main/webapp/WEB-INF/classes/META-INF/persistence.xml
appserver/persistence/jpa-container/src/main/java/org/glassfish/persistence/jpa/PersistenceUnitLoader.java

Only actual headers and target-server property. It did not resolved the exception in server.log, but it is correct at least. SunAS9 replaced with Glassfish.

Payara issue 512 - actual descriptors and replacing SunAS9 with Glassfish

---

appserver/jdbc/jdbc-runtime/src/main/java/org/glassfish/jdbc/deployer/DataSourceDefinitionDeployer.java

DataSourceDeployer was not returning null for non-existent properties.

Removed cause of spurious warning RAR8705

---

appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java
appserver/web/web-core/src/main/java/org/apache/catalina/ContainerEvent.java
appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/AuthenticatorBase.java
appserver/web/web-glue/src/main/java/com/sun/web/server/WebContainerListener.java

invocation context not set up correctly when calling an Authentication Module.
Added new Container events for authentication and post-authentication

PAYARA-548 fixes #299

---

appserver/persistence/jpa-container/src/main/java/org/glassfish/persistence/jpa/PersistenceUnitLoader.java

Use final application classloader to bootstrap the Persistence Unit as it loads driver classes
This fixes #510

PAYARA-547 fix #510

---

appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/IIOPSSLSocketFactory.java

Fixes #572
Adds in the functionality to enable SO_KEEPALIVE by setting a system property on the client (e.g. `java -Dfish.payara.SOKeepAlive=true -jar client.jar`).

PAYARA-408 Allow enabling of SO_KEEPALIVE

---

appserver/web/web-core/src/main/java/org/apache/catalina/connector/Request.java

sets handler initialised variable to false when the Request is recycled.

PAYARA-551 Fixes #536

---

appserver/admingui/jdbc/src/main/resources/advancePool.inc
appserver/admingui/jdbc/src/main/resources/jdbcConnectionPoolAdvance.jsf
appserver/admingui/jdbc/src/main/resources/org/glassfish/jdbc/admingui/Strings.properties
appserver/jdbc/jdbc-config/src/main/java/org/glassfish/jdbc/config/JdbcConnectionPool.java
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/common/DataSourceSpec.java
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/monitoring/JdbcRAConstants.java
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/JdbcObjectsFactory.java
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/ManagedConnectionFactoryImpl.java
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/util/SQLTraceCache.java
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/util/SQLTraceDelegator.java
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/fish/payara/jdbc/SQLQuery.java
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/fish/payara/jdbc/SlowSQLLogger.java
appserver/jdbc/jdbc-ra/jdbc-ra-distribution/build.xml
appserver/jdbc/jdbc-ra/jdbc30/src/main/java/com/sun/gjc/spi/jdbc30/ProfiledConnectionWrapper30.java
appserver/jdbc/jdbc-ra/jdbc40/src/main/java/com/sun/gjc/spi/jdbc40/ProfiledConnectionWrapper40.java
appserver/jdbc/jdbc-runtime/src/main/java/org/glassfish/jdbc/deployer/DataSourceDefinitionDeployer.java
appserver/jdbc/jdbc-runtime/src/main/java/org/glassfish/jdbc/deployer/JdbcConnectionPoolDeployer.java
nucleus/common/glassfish-api/src/main/java/org/glassfish/api/jdbc/SQLTraceRecord.java

Execution time of the JDBC method is now recorded in the SQL Trace.
Also SQLTraceCache now also displays number of executions in the console.#
Now enable custom connection pool properties for application defined datasource using DataSourceDefinition
Removed synchronized block from SQLTraceCache and replaced with Concurrent collection
Created SlowSQLLogger to report SQL queries that exceed a threshold time.
Plumbed the SQL tracing and Slow SQL Logging into the admin console and incorporated the two in-built SQL tracers directly

PAYARA-554 modified and improved SQL Tracing

---

appserver/pom.xml

Updates EclipseLink to a patched 2.6.2.
Fixes #512 
Depends upon https://github.com/payara/Payara_PatchedProjects/pull/13

PAYARA-519 Update EclipseLink to patched 2.6.2

---

nucleus/pom.xml

Option to include -Dfish.payara.CORBA.SkipGmbalInit=true to runtime environment to bypass Gmbal MBean initialisation. Fixes #539

PAYARA-556 Update to use CORBA version 4.0.1-p3

---

appserver/tests/quicklook/ejb/remoteview/src/test/RemoteViewTestNG.java
appserver/tests/quicklook/testng/testng_gd.xml

Change ejb_remoteview quicktest to access the IIOP Listener on port 5037 instead of defaulting to port 3700 and re-enable tests

PAYARA-417 

---

nucleus/common/common-util/src/main/java/com/sun/enterprise/security/store/AsadminTruststore.java
nucleus/common/common-util/src/main/java/com/sun/enterprise/util/CULoggerInfo.java

The original fix prevented the asadmin truststore being created if it doesn't exist, stopping you from saving certificates. This remedies that by making sure to create it first.
Also adds some logging for if a certificate can't be added.

Edit PAYARA-496 fix

---

appserver/packager/metro/pom.xml
appserver/pom.xml
appserver/security/webservices.security/pom.xml
appserver/webservices/jsr109-impl/pom.xml
appserver/webservices/metro-glue/pom.xml
appserver/webservices/soap-tcp/pom.xml

rollbacked pax-logging and patched webservices-osgi by moving the org.apache.xml.security package from xmlsec to webservices-osgi for overriding commons-logging dependency with java util logging.

rollbacked pax-logging and patched the webservices-osgi again

---

nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/AdminLoggerInfo.java
nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/HttpConnectorAddress.java

Fixes #657 
Allows you to set a system property that determines what version of TLS a client should use for HTTPS connections, allowing you to secure the sec-admin-listener to a greater level than TLSv1.
Currently only supports setting one protocol at a time.
Also adds some logging for clarity.

PAYARA-542 Cannot enable secure ciphers for admin listener

---

appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/GlassFishORBManager.java

and don't switch to parent in that case.
Bit of a hack that needs fixing by the Janitor Service in the future to clear up threads context classloader as the ORB spawns a bunch of threads.

Fixes #673 PAYARA-642 do explicit check for OSGi classloader 

---

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/Application.java
appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/descriptor/EjbBundleDescriptorImpl.java

- facilitating rolling upgrade
This is another issue I have encountered with rolling updates.
When serializing / deserializing local EJB references within a web session, the unique IDs have to be the same (right now they are sorted by EJB name) .
This pull request is a solution for this problem.  Instead of sorted EJB index, a UUID chunk is used for unique ID of EJBs
Related ticket #455

Unique IDs are kept based on the name of the EJB -

---

nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/embeddable/CommandExecutorImpl.java

…dded glassfish
When CLIUtil.readPasswordFileOptions is invoked with boolean parameter of true, then Map
`passwords` contains keys prefixed with `AS_ADMIN_`. This is never the parameter name and
therefore the password parameters didn't get filled.
I couldn't locate the origin of bug, because the code is same in Glassfish 3.1.2, I suppose it
either used some side channel, or command model transformation.

GLASSFISH-20818: Pass passwords from passwordfile to commands (PAYARA-658)

---

nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java

`com.sun.aas.instanceName` is the only glassfish system property that will not resolve when passed as JVM argument, which is strange omission.
In my use case I redirect all logging to logback, and logback gets initialized earlier than the system property is set during appserver startup. Passing it in JVM arguments guarantees it is available right from the process start.

Resolve com.sun.aas.instanceName in JVM arguments (PAYARA-660)

---

appserver/admingui/payara-console-extras/src/main/resources/fish/payara/admingui/extras/Strings.properties
appserver/admingui/payara-console-extras/src/main/resources/hazelcast/hazelcastConfigurationCluster.jsf
appserver/admingui/payara-console-extras/src/main/resources/hazelcast/hazelcastConfigurationServer.jsf
appserver/admingui/payara-console-extras/src/main/resources/hazelcast/hazelcastConfigurationStandalone.jsf
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastRuntimeConfiguration.java
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/MulticastConfiguration.java
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/admin/GetHazelcastConfiguration.java
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/admin/ListHazelcastMembers.java
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/admin/SetHazelcastConfiguration.java
nucleus/payara-modules/payara-micro/src/main/java/fish/payara/micro/PayaraMicro.java

Lite members are full cluster members but do not store any JCache or web session data. This provides more flexibility for cluster configurations.
Also corrects instance names in list-cluster-members to be the instance name and the name set in payara micro using --name

PAYARA 626 added support for Hazelcast Lite Members 

---

nucleus/payara-modules/payara-micro/src/main/java/fish/payara/micro/GAVConvertor.java
nucleus/payara-modules/payara-micro/src/main/java/fish/payara/micro/PayaraMicro.java

Allows you to deploy artefacts stored in Maven repositories by providing GAV (group, artefact, version) coordinates as comma separated Strings (e.g. `fish.payara.examples,test,1.1`), and repository URLs.
Defaults to looking for provided artefacts in Maven central if no additional repositories are provided.
Also removes an unused constructor and tidies up some comments.

PAYARA-249 Payara Micro Maven Deployer

---

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java

`EarLibClassloader` of an EAR app deployed on non-DAS instance was initialized but not destroyed on DAS upon deployment.
That lead to JarFile handles to its lib directory being held, and the DAS was unable to clear its application directory.
Calling unload unconditionally gurantees ApplicationInfo.clean to be called, which in turns calls preDestroy() / done() on all application
class loaders.

PAYARA-671 Always perform clean up on application on DAS upon undeployment.

---

nucleus/payara-modules/payara-micro/src/main/java/fish/payara/micro/PayaraMicro.java
nucleus/payara-modules/payara-micro/src/main/java/fish/payara/micro/PortBinder.java

Adds in warnings for when autobinding or setting ports is overriding a domain.xml.
Also cleans up the code formatting to be of one consistent style, and removes walkthrough comments.

PAYARA-263 Autobinding port precedence warnings

---

appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/EntityManagerWrapper.java

Fix for [GLASSFISH-21486](https://java.net/jira/browse/GLASSFISH-21486) - extended persistence context violates all contracts of JPA 2.1 by making fetched entities detached.

PAYARA-657 GLASSFISH-21486: EntityManager should not be detached in extended Persistence context 

---

appserver/connectors/connectors-inbound-runtime/src/main/java/com/sun/enterprise/connectors/inbound/InboundRecoveryHandler.java

…Fixes #679
OSGi applications do not have (EE) Application metadata, leading to NPE at line 267

Fix failing transaction recovery when OSGi applications are present. (Payara-659)

---

appserver/batch/glassfish-batch-connector/pom.xml
appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/LazyBootPersistenceManager.java

PAYARA-692 hazelcast dependency should be removed from JBatch until the JBatch persistence store for Hazelcast is available

Remove dependency on Hazelcast 

---

nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/HttpConnectorAddress.java

TLSv1 is now pretty old and has security flaws, so updating to use TLSv1.2 if possible.
By default TLS rollback is enabled, so there should be no change to default behaviour (my own testing has not revealed any).

PAYARA-662 Set TLSv1.2 as default for the asadmin client

---

appserver/deployment/javaee-core/src/main/java/org/glassfish/javaee/core/deployment/GetContextRootCommand.java
appserver/deployment/javaee-core/src/main/java/org/glassfish/javaee/core/deployment/ListSubComponentsCommand.java

Bugfix: always strip off the app's version suffix (apps with rolling updates) when looking up the app's modules.
This is probably a dirty hack to solve issue #702, and partly also #461 (note: only the GUI issue, when components were listed), because:
1.  it leaves the GUI in a kind of unpolished state: it will still show the app's main moduleName with the version suffix, even though it does not seem right (before this hack the  the REST resource did not accept module names with version suffix).
2. it does not enforce the correct naming of the module in various calls, rather makes the REST resource more forgiving
3. certain REST resources may return URLs with incorrect moduleName (with the suffix)
However! 
1. It works and is just a 6 line change. Simplicity matters.
2. The potential of …

Fix component list for versioned apps

---

appserver/admin/gf_template/src/main/resources/config/default-web.xml
appserver/admin/payara_template/src/main/resources/config/default-web.xml
appserver/appclient/client/acc-standalone/fixup.xml
appserver/extras/embedded/build.xml
appserver/extras/embedded/payara-micro/build.xml
appserver/packager/glassfish-appclient/pom.xml
appserver/packager/glassfish-appclient/src/main/assembly/glassfish-appclient.xml
appserver/pom.xml
appserver/tests/quicklook/weld/osgiweld/README
appserver/tests/quicklook/weld/osgiweld/src/java/osgiweld/OsgiWeldServlet.java

weld-osgi-bundle.jar text references replaced with weld-osgi-bundle-glassfish4.jar.
Also staged the weld-environment-common.jar to lib/appclient folder by first putting it into modules folder like weld-se-core and that propagating it to lib/appclient during the build process.
These actions fix the quicklook tests that were failing and the MDBTests to be specific.

Payara 738 references to weld osgi bundle.jar should be fixed

---

nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncherInfo.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/RestartServer.java

Service wrapper runs instances / domains with `--watchdog true`. This causes server to be relaunched once it exits with predefined exit code. See `StartDomainCommand.executeCommand` and `StartLocalInstanceCommand.executeCommand`.
On the other hand, RestartServer will also relaunch the server by starting separate process just before the process exits. See `RestartServer.doReincarnation()`.
RestartServer doesn't take` --watchdog` argument into account in its `doExecute` method, and therefore two server instances are started, from each of the code paths.

Prevent duplicate server respawn when run under supervision. Fixes #732.

---

nucleus/flashlight/framework/pom.xml
nucleus/pom.xml

Lower required JDK version, as IBM JDK on AIX does not have an update number. Also remove aix profile from flashlight, as properties file doesn't exist

PAYARA-753 

---

appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/recovery/ConnectorsRecoveryResourceHandler.java

This improves previous fixes of [GLASSFISH-21175](https://java.net/jira/browse/GLASSFISH-21175).
I was unsatisfied with timeout approach that prolonged server starts or cause startup of application to fail. To fix this in Glassfish 3.1.2 I made `ApplicationLoaderService` spawn a new thread after all connector modules were started. With that, its `postConstruct` would finish before transaction recovery started.
Glassfish 4 has an explicit application ordering built in, so it already guarantees that all connector modules are started when applications start, and need a transaction. Therefore this wait point in `ConnectorResourceRecoveryHandler` is not relevant anymore.

Do not wait for all applications to be loaded when doing TX recovery

---

nucleus/payara-modules/payara-micro/src/main/java/fish/payara/micro/GAVConvertor.java

Add break clause to loop to stop it overwriting the correct artefactURL with an incorrect one if there are still more repositories to search

PAYARA-800 Payara Micro Maven Deployer gives a FileNotFoundException

---

appserver/security/core-ee/src/main/java/com/sun/enterprise/security/jmac/callback/BaseContainerCallbackHandler.java
appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java
appserver/web/web-core/src/main/java/org/apache/catalina/connector/RequestFacade.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/common/AbstractSecurityContext.java

Fixes #751 enable access to both the custom principal and the WebPrincipal in the Security Context when doing JASPIC

Payara 775

---

appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java
appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldTerminationListenerProxy.java

added WeldTerminationListenerProxy to check if BeanManager is available since all WARs in an EAR are always assumed to be CDI
removes NPE that was caused by this
Fixes PAYARA-638 and Issue #662

Fixes PAYARA-638 - NPE on logout in EAR files

---

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/LoggingHandlers.java
nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java
nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/DeleteLogLevel.java

The admin console cannot deal with log level properties that have colons in them (e.g. _test:test_), as the colon is the delimiter for when dealing with multiple log levels. This fix allows you to add and delete log level properties that have delimiters in them.
Note, you will still have to escape the colon on the command line (e.g. `set-log-levels "test\:test"`), and it will be stored with the escape character in the _logging.properties_ file. It will be displayed without the escape character in the admin console, and in the response from the `list-log-levels` command.

Payara 724 Admin Console cannot handle escape characters

---

nucleus/packager/nucleus-hk2/pom.xml

Dependency is listed twice in the same POM. Should remove the warning message at the beginning of builds.

Remove duplicate dependency

---

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/GrizzlyProxy.java
nucleus/core/kernel/src/main/java/org/glassfish/kernel/KernelLoggerInfo.java

A very often error that prevents server startup is that a port cannot be bound because it is already occupied. Payara server just logs a stacktrace and shuts down.
This update adds error logging of address and port, which could not be bound.

Added error logging when unable to bind to port.

---

nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/store/ClusteredStore.java

get on the cluster store did not check whether the store was enabled resulting in a NPE

PAYARA-900 Fixed NPE in Cluster Store if HZ is not enabled

---

appserver/concurrent/concurrent-impl/pom.xml
appserver/concurrent/concurrent-impl/src/main/java/fish/payara/concurrent/monitoring/ConcurrentMonitoringUtils.java
appserver/concurrent/concurrent-impl/src/main/java/fish/payara/concurrent/monitoring/ManagedExecutorServiceStatsProvider.java
appserver/concurrent/concurrent-impl/src/main/java/fish/payara/concurrent/monitoring/ManagedScheduledExecutorServiceStatsProvider.java
appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/admin/ManagedExecutorServiceManager.java
appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ConcurrentRuntime.java
appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ManagedExecutorServiceDeployer.java
appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ManagedScheduledExecutorServiceDeployer.java
appserver/pom.xml
nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/MonitoringService.java
nucleus/admin/monitor/src/main/java/org/glassfish/admin/monitor/StatsProviderRegistry.java
nucleus/flashlight/framework/src/main/java/org/glassfish/flashlight/cli/MonitoringConfig.java

Adds monitoring for `ManagedExecutorService` and `ManagedScheduledExecutorServices`. Currently has the limitation of only registering the pools for monitoring once an application tries to use them.
The monitoring is registered to the "_Threal Pool_" module, so monitoring of this will need to be enabled to see the statistics.
Also contains some minor clean up of unused imports, and somewhat of a fix for container-monitoring (as opposed to module-monitoring). Registering and editing monitoring requires transaction semantics, and container-monitoring was lacking this (see changes made to `MonitoringService.java`). Container-monitoring is still in a sorry state though, as I believe this was either intended to be deprecated, or the two monitoring types were intended to be merged together, but …

PAYARA-592 Monitoring for Concurrent Resources

---

appserver/pom.xml

Fixes PAYARA-869 by closing a stream when it is no longer used in the JBatch container.
Relies on https://github.com/payara/Payara_PatchedProjects/pull/33

PAYARA-869 Update JBatch container version

---

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/RestartServer.java

It was bit more involved than I originally thought, but one cannot make a running daemon thread a non-daemon thread. Starting an another one was the only way to keep it close to the actual restart code.

Issue #967: Payara-945 Perform System.exit in non-daemon thread during server restart.

---

appserver/deployment/javaee-full/src/main/java/org/glassfish/javaee/full/deployment/EarHandler.java
appserver/web/gf-weld-connector/src/main/java/org/glassfish/weld/connector/WeldUtils.java

deployment doesn't override implicit CDI scanning settings in glassfish-application.xml

CDI scanning enhancements fixes PAYARA-824

---

appserver/core/javaee-kernel/src/main/java/org/glassfish/kernel/javaee/MEJBNamingObjectProxy.java
appserver/core/javaee-kernel/src/main/java/org/glassfish/kernel/javaee/MEJBService.java
appserver/ejb/ejb-container/src/main/resources/com/sun/logging/enterprise/system/core/LogStrings.properties

added log strings file to EJB container to quiet the "resource bundle not found" messages
Also fixed logging in JavaEE kernel (MEJBService and it's proxy) to quiet similar warning messages

Fixes PAYARA-813 and PAYARA-690 spurious "resource not found" messages

---

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ManagedExecutorServiceDeployer.java
appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ManagedScheduledExecutorServiceDeployer.java
nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/config/AMXConfigLoader.java

Changes the log level to FINE to silence this log message, as it isn't useful information pertaining to normal running procedure.
Also adds in the unregister methods for the ManagedExecutorService monitoring.

PAYARA-956 ManagedExecutorService MBean attempts to register multiple times

---

nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/domain/DomainPortValidator.java

re-add JMS port property to domainProperties because its a "substitutable property"

Correct JMS Port property - fixes PAYARA-892

---

appserver/distributions/pom.xml
appserver/extras/pom.xml

Edits the default build procedure, and adds additional build options.
Doing a standard build (`mvn clean install`) will build:
* payara
* payara-ml
* payara-web
* payara-web-ml
* payara-minimal
Running a build with the _QuickBuild_ profile (`mvn clean install -PQuickBuild`) will just build:
* payara
* payara-minimal
Running a build with the _BuildExtras_ profile will add the Embedded and Micro distributions to the build. For example, `mvn clean install -PQuickBuild,BuildExtras` will build:
* payara
* payara-minimal
* payara-micro
* payara-embedded-all
* payara-embedded-web
Finally, running a build with the _BuildMicro_ profile will add Payara Micro to the build. For example, `mvn clean install -PBuildMicro` will build:
* payara
* payara-ml
* payara-web
* payara-web-ml
* payara-minimal
* …

Add build profiles

---

appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/api/AppSpecificConnectorClassLoaderUtil.java

There is a small possibility that the application actually is deployed but not yet started. This is fixed in another PR. 
On the other hand, this entire functionality is very glassfish-specific, so a workaround for such case -- waiting with deploy command after restart -- is suitable.

Ignore not deployed connectors when looking for JNDI resource. Fixes #871.

---

appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/EjbWebServiceServlet.java

PAYARA-1104 fixes #1117 Encode redirect to https correctly on webservice

---

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/monitor/GrizzlyMonitoring.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/monitor/stats/ThreadPoolStatsProvider.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/monitor/stats/ThreadPoolStatsProviderGlobal.java

This pull request makes the global thread pool statistics much more complete, with it now counting the total maximum and minimum threads in all of the thread pools of a config.
It also edits the way the monitoring works so that it is more accurate by querying the JVM for the actual current number of threads, rather than relying upon events to alter internally stored values (which may have been missed or reset depending on when the monitor listener was registered).
Also renames the global thread pool stats from _thread-pool_ to _global-thread-pool-stats_ to make it more clear.

PAYARA-1056 global thread pool statistics incorrect

---

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/LifecycleCallbackDescriptor.java
appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/EjbServicesImpl.java

For method and timeout CDI interceptors in EJB, choose only the method having argument of InvocationContext type, not only based on the name, as there may be multiple methods with the same name in a single interceptor class.
A fix for #1078

PAYARA-1067 Check of InvocationContext argument for AroundInvoke and AroundTimeout.

---

appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/JSR107Producer.java

Fixes #1124
Disclaimer: I don't really understand CDI lifecycle. I assume the producer method is called for each injection point. 
[Example usage](https://github.com/jerrinot/microprofile-conference/commit/53a08594d6ce36896becc4e7d6a0a07aee57dd71) (depends also on https://github.com/payara/Payara/pull/1125)

Use name from CacheDefaults when injecting JCache (PAYARA-1106)

---

appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/JSR107Producer.java

This allows to use JCache beans to be applied into injection sites with
type parameters.
For example this works now:
```java
@Inject
private Cache<LongKey, Schedule> scheduleCache;
```

JCache beans created by JSR107Producer use generics (PAYARA-1107)

---

appserver/jdbc/jdbc-ra/jdbc-core/pom.xml
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/ManagedConnectionImpl.java
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/util/SQLTraceDelegator.java
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/fish/payara/jdbc/RequestTracingListener.java

Adds in request tracing for JDBC context events.
Request tracing can be enabled/disabled without requiring the connection pool to be recreated.
JDBC wrapping is required for the request tracing events to appear in the log (enabled by default).

PAYARA-178 Request tracing for JDBC context events.

---

appserver/admin/gf_template/src/main/resources/config/domain.xml
appserver/admin/payara_template/src/main/resources/config/domain.xml
appserver/extras/payara-micro/payara-micro-core/src/main/resources/payara-boot.properties
nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/SSLConfigurator.java
nucleus/grizzly/config/src/test/java/org/glassfish/grizzly/config/GrizzlyConfigTest.java
nucleus/pom.xml

DO NOT MERGE UNTIL AFTER THE 163.1 customer release as Grizzly changes the default buffer type used internally between 2.3.26 and 2.3.27

PAYARA-1033 upgrade to Grizzly 2.3.27

---

nucleus/admin/config-api/src/main/java/org/glassfish/config/support/TranslatedConfigView.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/CreateSystemProperties.java

Disable alias substitution when checking whether config value truly changed
Fixes a rare instance when the alias is changed into non-alias and the change is ignored

PAYARA-934 Alias substitution configuration issue

---

nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/RequestTrace.java
nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/RequestTracingService.java
nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/domain/RequestEvent.java

PAYARA-1113 - Request Tracing does not process thresholds below millisecond

PAYARA-1113 - Request Tracing does not process thresholds below millisecond

---

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/WebBundleDescriptor.java
appserver/deployment/dtds/src/main/resources/glassfish/lib/dtds/glassfish-web-app_3_0-1.dtd
appserver/web/war-util/src/main/java/org/glassfish/web/loader/ServletContainerInitializerUtil.java
appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModule.java
appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/descriptor/WebBundleDescriptorImpl.java
appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/node/runtime/gf/WebBundleRuntimeNode.java

added <container-initializer-enabled> element to glassfish-web.xml to control initializer invocation

PAYARA-867 servlet initializer invocation parameter

---

appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/CacheResultInterceptor.java

Reasoning:
JCache spec and Payara implementation allows caching of exceptions.
In theory everything extending Throwable can be cached -> casting to
Exception is  not safe as it can throw ClassCastException

Don't cast cached Throwable to Exception as it's too narrow. (PAYARA-1126)

---

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/PayaraMicro.java
appserver/extras/payara-micro/payara-micro-core/src/main/resources/microdomain-nocluster.xml
appserver/extras/payara-micro/payara-micro-core/src/main/resources/microdomain.xml

Adds in command line options to enable and configure request tracing in Payara Micro.
Also turns on the Notification service by default.
The new options are:
* `--enableRequestTracing` - Just a flag; you **don't** need to add _true_ or _false_ afterwards. 
* `--requestTracingThresholdUnit` - Accepts a String value determining the time unit, defaulting to seconds if no value is given. The accepted strings are (case insensitive): _NANOSECONDS_, _MICROSECONDS_, _MILLISECONDS_, _SECONDS_, _MINUTES_, _HOURS_, and _DAYS_.
* `--requestTracingThresholdValue` - Accepts a _long_ to determine the threshold value before a request is traced, defaulting to 30 if no value is entered.
As an example of usage:
`java -jar payaramicro.jar --enableRequestTracing --requestTracingThresholdUnit NANOSECONDS …

PAYARA-931 Payara Micro Request Tracing

---

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/PayaraMicro.java

In Payara Micro make ROOT.war deploy to the / context root as it does after packaging as an Uber Jar

PAYARA-1134 make ROOT.war deploy to / context root 

---

appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContextValve.java

Related to fix done in #1024 
I'm restricting this fix to **just** the issue we've currently got of redirecting to index.jsf by matching the URI String so as to keep the initial fix intact. I can't think of a way that this could be abused, but if someone comes up with anything let me know.

PAYARA-989 Fix Windows Admin Console Redirect

---

nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/VirtualServer.java

remove smart quotes in authRealm description

---

appserver/security/core-ee/src/main/java/com/sun/enterprise/security/acl/RoleMapper.java

default role mapping on security service if enabled takes precedence

PAYARA-1244 

---

appserver/web/weld-integration/src/main/java/org/glassfish/weld/BeanDeploymentArchiveImpl.java

fix WELD-000163: Non-unique bean deployment identifier detected for Weld 2.4+

PAYARA-1223 fix WELD-000163 non-unique bean deployment

---

nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/GFFileHandler.java

now reading properties before rotating the logs, so com.sun.enterprise.server.logging.GFFileHandler.maxHistoryFiles is properly read

PAYARA-1105 reading logging properties before rotating logs

---

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/Application.java

using Unix slash for path separator, works both unix and windows
fixes #1158

PAYARA-999 fixes regex errors on windows

---

appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/service/ConnectorConnectionPoolAdminServiceImpl.java
appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/util/ApplicationValidator.java
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/common/DataSourceSpec.java

- Application-scoped DB connection resources work correctly with redeployment
- No severer errors that don't mean anything (duplicate jndi-name)
Fixes #907

PAYARA-1290 various application-scoped deployment fixes

---

nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/SetLogAttributes.java

Also adds in an extra message for when setting the file rotation time to an invalid value.

PAYARA-1150 Provide greater clarity in error log for when setting an invalid value for the log file rotation size limit

---

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/SetCommand.java

As discussed in the issue,  the patch is correct unless there exists a situation, where instance would give different result to ` getAliasedParent(domain, pattern)` than the DAS.

Replicate original set command key instead of processed one. Fixes #1280

---

appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/ConnectorXAResource.java
appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/PoolManagerImpl.java
appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/rm/LazyEnlistableResourceManagerImpl.java
appserver/connectors/connectors-runtime/src/main/resources/com/sun/enterprise/LogStrings.properties

Committed by @retoo
* Payara-769: Make resetAssociation() more robust by avoiding begin()ing tx in error handling/finally
Otherwise we will crash right again in our finally/resetAssociation block which will
cause the connection pool entry to have avery inconsistent state from which the
server does not recover.
* Payara-769: When errors occur during TXStart we should evict the connection from the pool
* Payara copyright
* Payara Copyright
* Payara Copyright

PAYARA-769 Make resetAssociation() more robust (#1148)

---

appserver/admin/gf_template/src/main/resources/config/domain.xml
appserver/admin/payara_template/src/main/resources/config/domain.xml

This fix is implemented by adding the default configuration tags for this service to the default domain.xml files, so will not take affect for those migrating from previous versions (if they have not already made a configuration change to the _monitoring-service-configuration_ service)

PAYARA-1282 jmx monitoring service is not dynamic until first restart

---

appserver/web/web-core/src/main/java/org/apache/catalina/session/ManagerBase.java
appserver/web/web-core/src/main/java/org/apache/catalina/session/PersistentManagerBase.java
appserver/web/web-core/src/main/java/org/apache/catalina/session/StandardManager.java
appserver/web/web-core/src/main/java/org/apache/catalina/session/StandardSession.java
appserver/web/web-ha/src/main/java/org/glassfish/web/ha/session/management/ModifiedAttributeHASession.java
appserver/web/web-ha/src/main/java/org/glassfish/web/ha/session/management/ReplicationAttributeStore.java

more resilience of session serialization in presence of errors, such as:
- ignore non-serializable fields with a warning, even if they are inside a serializable object

PAYARA-1324 session replication resilience and improvements

---

appserver/connectors/connectors-internal-api/src/main/java/org/glassfish/api/jdbc/validation/DefaultConnectionValidation.java
appserver/connectors/connectors-internal-api/src/main/java/org/glassfish/api/jdbc/validation/DerbyConnectionValidation.java
appserver/connectors/connectors-internal-api/src/main/java/org/glassfish/api/jdbc/validation/JDBC40ConnectionValidation.java
appserver/connectors/connectors-internal-api/src/main/java/org/glassfish/api/jdbc/validation/OracleConnectionValidation.java
appserver/connectors/connectors-internal-api/src/main/java/org/glassfish/api/jdbc/validation/PostgresConnectionValidation.java
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/ManagedConnectionFactoryImpl.java
nucleus/common/glassfish-api/src/main/java/org/glassfish/api/jdbc/ConnectionValidation.java

This PR changes the GlassFish API slightly; the `isConnectionValid(Connection con)` method of the `ConnectionValidation` class is now `isConnectionValid(Connection con, int statementTimeout)`.
The timeout only applies to the `table` and the applicable `custom-validation` connection validation types.

 PAYARA-1078 Make JDBC connection validation use the configured statement timeout

---

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/monitor/GrizzlyMonitoring.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/monitor/ThreadPoolMonitor.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/monitor/probes/ThreadPoolProbeProvider.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/monitor/stats/ThreadPoolStatsProvider.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/monitor/stats/ThreadPoolStatsProviderGlobal.java

Re-implements original busy thread count impl, and reworks the global and individual thread counts for current, core, and max threads to be more accurate.
Also cleans up the probe provider methods a little.

Payara 1056 global thread pool statistics redux

---

appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/AbstractJSR107Interceptor.java
appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/CachePutInterceptor.java
appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/CacheRemoveAllInterceptor.java
appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/CacheRemoveInterceptor.java
appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/CacheResultInterceptor.java
appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/JSR107Producer.java

interceptors and producer checks whether Hazelcast is enabled before doing anything.
PAYARA-1346 Also fixed by the same change
Fixes #1303 
Fixes #1305

PAYARA-1345

---

nucleus/admin/config-api/src/main/java/org/glassfish/config/support/TranslatedConfigView.java

This PR provides the capability to add ${ENV=envvariable} into the domain.xml to enable environment variable substitution. This also works for some deployments including application deployed datasources.

PAYARA-1386 allow environment variable substitution in the domain.xml

---

appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/common/DataSourceSpec.java

This fixes an error where no password credential exception is thrown after reconfiguring the JDBC connection pool.

PAYARA-1281 Add ignored properties when working out equality

---

nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HealthCheckServiceThresholdConfigurer.java

sets default values for thresholds

PAYARA-1413-Healthcheck-threshold-configuration-fails-if-all-the-values-are-not-provided

---

appserver/admingui/payara-console-extras/src/main/resources/fish/payara/admingui/extras/Strings.properties

I'm not sure, but I think that the Notification service shouldn't be in technical preview since 164, or at least since 171. In that case, there should be no warning message in admin console.
If it is still in technical preview, **don't merge this PR yet**.

PAYARA-1423 notification svc preview

---

appserver/admingui/payara-console-extras/src/main/resources/fish/payara/admingui/extras/Strings.properties

Request tracing is officially production-ready since 164, therefore there should be no warning anymore.

PAYARA-1423 Removed the warning of Request Tracing in preview from admin console

---

nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HealthCheckConfigurer.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HealthCheckServiceConfigureCheckerWithThresholdsCommand.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HealthCheckServiceThresholdConfigurer.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HoggingThreadsConfigurer.java

I believe null checks already exist for healthcheck-configure-service-thresholds, certainly if done dynamically.

PAYARA-1437 removed defaults for healthcheck service commands

---

nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HealthCheckServiceConfigureCheckerWithThresholdsCommand.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HealthCheckServiceConfigurer.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HoggingThreadsConfigurer.java

The name parameter is a reserved word, and so can't be used from the admin console or rest interface.

PAYARA-1383 Deprecate name parameter and fix pages

---

appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/Outbound.java
appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/ClusteredCDIEventBusImpl.java

Changed instanceName from type String to array.
A single instance name can still be defined in the same way (due to how arrays work in annotations):
```
@Inject
@Outbound(instanceName = "Instance-1")
Event<String> event;
```
However, instead of using comma to separate more instances, multiple instance names are specified as an array:
```
@Inject
@Outbound(instanceName = {"inst1", "inst2"})
Event<String> event;
```
Internaly, three commas (instead of a single comma) are used as a separator in the flattened string value, so that it doesn't clash if comma is used also inside an instance name.

Payara 1434 cdi bus outbount instance names as array

---

appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardWrapper.java

made NotFoundErrorSupressionFilter static to remove dangling references to class loader

PAYARA-1462 class loader leakage

---

appserver/payara-appserver-modules/jmx-monitoring-service/src/main/java/fish/payara/jmx/monitoring/admin/SetMonitoringConfiguration.java

PAYARA-1284 JMX monitoring set-monitoring-configuration no longer requires --enabled to keep its current state

PAYARA-1284 JMX monitoring set-monitoring-configuration fix

---

appserver/extras/payara-micro/payara-micro-core/src/main/resources/commandoptions.properties

verified that setting -Djava.io.tmpdir does still change the unpack directory and that this is the default behaviour. Added this fact to the description.

PAYARA-1471-clarify-default-unpack-behaviour

---

nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/KeystoreManager.java

The self-signed certificate that is generated by default in Payara no longer says it's generated by Oracle

PAYARA-539 change self signed

---

appserver/grizzly/glassfish-spdy/src/main/java/org/glassfish/grizzly/extras/spdy/SpdyAddOnProvider.java
nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/GenericGrizzlyListener.java
nucleus/pom.xml

This change updates the grizzly dependency to the 2.3.29. This enables
handling of content-encodings for incoming requests by the server.
The ability to compress responses has already been part of glassfish,
but response handling did not include the ability to handle gzip/lzma
compressed requests.
This was requested in #1038 [2] and also requested for glassfish [0].
Grizzly 2.3.28 gained decompression support[1], but introduced a
regression. In this version the incoming datastream was decompressed,
but the Content-Encoding header was left in place. This in turn lead
to servlet filters/applications to asume the stream was still
compressed and triggered a second decompression step [3].
With grizzly 2.3.29 defaults were changed to match 2.3.27 (making
request decompression opt-in) and add …

Update grizzly to 2.3.29 and handle gzip/lzma content-encoding of requests PAYARA-1288 PAYARA-1441

---

appserver/admingui/xmpp-notifier-console-plugin/src/main/resources/fish/payara/admingui/notifier/xmpp/Strings.properties
appserver/admingui/xmpp-notifier-console-plugin/src/main/resources/xmpp/xmppNotifierConfiguration.jsf
appserver/payara-appserver-modules/notification-xmpp-core/src/main/java/fish/payara/notification/xmpp/GetXmppNotifierConfiguration.java
appserver/payara-appserver-modules/notification-xmpp-core/src/main/java/fish/payara/notification/xmpp/XmppNotificationConfigurer.java
appserver/payara-appserver-modules/notification-xmpp-core/src/main/java/fish/payara/notification/xmpp/XmppNotificationRunnable.java
appserver/payara-appserver-modules/notification-xmpp-core/src/main/java/fish/payara/notification/xmpp/XmppNotifierConfiguration.java
appserver/payara-appserver-modules/notification-xmpp-core/src/main/java/fish/payara/notification/xmpp/XmppNotifierConfigurationExecutionOptions.java
appserver/payara-appserver-modules/notification-xmpp-core/src/main/java/fish/payara/notification/xmpp/XmppNotifierConfigurationExecutionOptionsFactory.java

Changed XMPP configuration variable named roomName to roomId and text from Name to ID.

Changed XMPP configuration variable

---

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
nucleus/deployment/admin/src/main/java/fish/payara/deployment/admin/DeployRemoteArchiveCommand.java
nucleus/deployment/common/osgi.bundle
nucleus/deployment/common/src/main/java/fish/payara/deployment/util/GAVConvertor.java
nucleus/payara-modules/phonehome-bootstrap/src/main/java/fish/payara/nucleus/phonehome/PhoneHomeTask.java

Introduces a new asadmin command, `deploy-remote-archive`, that allows you to deploy an artefact from a URL, or by providing comma separated GAV (GroupId, ArtefactId, VersionNumber) coordinates and Maven repositories to check and download from (similar to how the feature works in Payara Micro).
The new command takes the same parameters as the standard deploy command, with the addition of a new parameter: `--additionalRepositories`.
This parameter accepts a comma separated list of URLs that Payara will search for Maven artefacts in (Payara will only check in Maven Central by default).
Command usage for deploying directly from a URL (as in, without GAV conversion): `asadmin deploy-remote-archive url`
For example:
`asadmin deploy-remote-archive …

PAYARA-1395 Allow full server to deploy applications from a maven repository and URLs

---

appserver/admingui/payara-console-extras/src/main/java/fish/payara/admingui/extras/rest/PayaraRestApiHandlers.java
appserver/admingui/payara-console-extras/src/main/resources/hazelcast/microInstancesTable.inc

The tickboxes in the Hazelcast micro instances table will now be properly deselected on failure.

PAYARA-1404 Deselect tickboxes on failure

---

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/PEAccessLogValve.java
nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/AccessLog.java
nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/ConfigBeansUtilities.java

PAYARA-1509 condition for access logger may be read in from domain.xml

---

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/APIClassLoaderServiceImpl.java

log a warning when OSGi exception results from an API load, instead of swallowing the error

PAYARA-1402 OSGi classloading failure improvements

---

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/boot/runtime/MicroGlassFish.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java

Allows Embedded Payara Micro to actually shut down, as the refactor brought in from 171 broke this.

PAYARA-1542 Embedded Micro doesn't shut down

---

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/DynamicConfigListener.java

Restart required now shows when the admin thread pool configuration is changed.

PAYARA-1085 Changing admin-thread-pool config flags restart required

---

appserver/admin/gf_template_web/pom.xml
appserver/admin/gf_template_web/src/main/assembly/appserver-domain-web.xml
appserver/admin/gf_template_web/src/main/resources/config/default-web.xml
appserver/admin/gf_template_web/src/main/resources/config/domain.xml
appserver/admin/gf_template_web/src/main/resources/config/glassfish-acc.xml
appserver/admin/gf_template_web/src/main/resources/config/wss-server-config-1.0.xml
appserver/admin/gf_template_web/src/main/resources/config/wss-server-config-2.0.xml
appserver/admin/gf_template_web/src/main/resources/stringsubs.xml
appserver/admin/gf_template_web/src/main/resources/template-info.xml
appserver/admin/payara_template_web/pom.xml
appserver/admin/payara_template_web/src/main/assembly/payara-domain-web.xml
appserver/admin/payara_template_web/src/main/resources/config/default-web.xml
appserver/admin/payara_template_web/src/main/resources/config/domain.xml
appserver/admin/payara_template_web/src/main/resources/config/glassfish-acc.xml
appserver/admin/payara_template_web/src/main/resources/config/wss-server-config-1.0.xml
appserver/admin/payara_template_web/src/main/resources/config/wss-server-config-2.0.xml
appserver/admin/payara_template_web/src/main/resources/stringsubs.xml
appserver/admin/payara_template_web/src/main/resources/template-info.xml
appserver/admin/pom.xml
appserver/distributions/payara-ml/src/main/assembly/payara-ml.xml
appserver/distributions/payara-web-ml/src/main/assembly/payara-web-ml.xml
appserver/distributions/payara-web/src/main/assembly/payara-web.xml
appserver/distributions/payara/src/main/assembly/payara.xml
appserver/extras/embedded/build.xml
appserver/extras/payara-micro/payara-micro-distribution/build.xml
appserver/extras/payara-micro/payara-micro-microprofile-distribution/build.xml
appserver/packager/glassfish-nucleus/pom.xml

Caused by JMS declaration lines in domain.xml.
- Added new modules to generate modified domain templates for Web Profile
- New domain templates have had the JMS lines removed.
- New domain templates are packaged into glassfish-nucleus packager as gf_template_web and payara_template_web.
- Payara Web and Web-ML replace the default domain templates with the correct one.
- All other distributions now discard any new domain templates to keep the originals.

Payara 1524 Payara Web throws JMS error

---

appserver/admingui/cluster/src/main/resources/org/glassfish/cluster/admingui/Strings.properties

The instances aren't really "standalone" any more.

PAYARA-1142 Rename Standalone Instances to Instances

---

appserver/admingui/war/src/main/webapp/WEB-INF/sun-web.xml
appserver/admingui/war/src/main/webapp/resources/yui/yahoo-dom-event.js
appserver/pom.xml

Requires https://github.com/payara/Payara_PatchedProjects/pull/56 to be merged first

PAYARA-1128 buttons now have unified look-and-feel - suntheme

---

appserver/admingui/email-notifier-console-plugin/src/main/java/fish/payara/admingui/notifier/email/EmailNotifierPlugin.java
nucleus/pom.xml

Made a new profile to disable doclint on JDK 1.8 and above, which was causing errors when running the javadoc goal.

Javadoc Plugin Fix

---

appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/InstanceResolverImpl.java

Resolver guarded with proper double-check lock. Field instance only changes when resolver is
initialized, therefore I believe it doesn't need any further synchronization.

Thread-safe initialization of InstanceResolverImpl. Fixes #1511. PAYARA-1577

---

appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/ClusteredCDIEventBusImpl.java
appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/context/JavaEEContextUtilImpl.java
nucleus/common/internal-api/src/main/java/org/glassfish/internal/api/JavaEEContextUtil.java
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/contextproxy/CacheProxy.java
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/contextproxy/CompleteConfigurationProxy.java
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/contextproxy/EntryProcessorProxy.java

- Make it work with EjbInvocation as well as ServletInvocation
- Refactor to make names prettier
- ClusteredCDIEventBus uses JavaEEContextUtil

PAYARA-1566 refactor / improve invocation context utility

---

appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/annotation/impl/WarScanner.java

This fixes issue #1456 among others.

PAYARA-1537 Fixed locating resource in class loader

---

appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardPipeline.java

Issue : Response information is not correctly logged in the HTTP Access log when the web container deals with Asynchronous servlet requests.
Fix : Logging invocation is now done at the completion notification of Asynchronous Context using AsyncListener.
Issue  Ref : https://github.com/payara/Payara/issues/1401

PAYARA-1585 Async servlet access is not correctly logged

---

appserver/jdbc/jdbc-runtime/src/main/java/org/glassfish/jdbc/deployer/DataSourceDefinitionDeployer.java

DataSourceDefinitionDeployer now also takes data sources that are defined in application.xml into account when doing the special early deployment for JPA.

PAYARA-1625 fixed data-source from application.xml in JPA

---

appserver/payara-appserver-modules/notification-datadog-core/src/main/java/fish/payara/notification/datadog/DatadogNotifierService.java
appserver/payara-appserver-modules/notification-email-core/src/main/java/fish/payara/notification/email/EmailNotifierService.java
appserver/payara-appserver-modules/notification-hipchat-core/src/main/java/fish/payara/notification/hipchat/HipchatNotifierService.java
appserver/payara-appserver-modules/notification-jms-core/src/main/java/fish/payara/notification/jms/JmsNotifierService.java
appserver/payara-appserver-modules/notification-newrelic-core/src/main/java/fish/payara/notification/newrelic/NewRelicNotifierService.java
appserver/payara-appserver-modules/notification-slack-core/src/main/java/fish/payara/notification/slack/SlackNotifierService.java
appserver/payara-appserver-modules/notification-snmp-core/src/main/java/fish/payara/notification/snmp/SnmpNotifierService.java
appserver/payara-appserver-modules/notification-xmpp-core/src/main/java/fish/payara/notification/xmpp/XmppNotifierService.java
nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/service/BaseNotifierService.java
nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/service/QueueBasedNotifierService.java
nucleus/payara-modules/notification-eventbus-core/src/main/java/fish/payara/notification/eventbus/core/EventbusNotifierService.java

Only a single thread will now exist for each notifer.

PAYARA-1696 stop previous thread when notifier is configured

---

nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java
nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncherLogger.java
nucleus/admin/launcher/src/main/java/fish/payara/admin/launcher/PayaraDefaultJvmOptions.java
nucleus/admin/launcher/src/main/java/fish/payara/admin/launcher/PayaraJvmOptionDefaults.java

If the JVM option _org.glassfish.grizzly.DEFAULT_MEMORY_MANAGER_ is not present in the server/instance config, we will override the Grizzly default and use the _HeapMemoryManager_.
To override this behaviour (so to use a different memory manager), you must specify this JVM option in the server/instance config with your desired setting.
This is to help with people upgrading from an older version of Payara where this JVM option has not been added to the default domain.xml.
When this override happens, a message is logged at a level of FINE.
When this override happens, the JVM option is **NOT** added to the domain.xml.

PAYARA-1681 Add default JVM options check

---

nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HistoricHealthCheckEventRetriever.java

Don't mark command as failed when not enabled

PAYARA-1694 Healthcheck still prints out error in log

---

appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/deployer/JMSConnectionFactoryDefinitionDeployer.java

This attribute was already being collected in the original code with
even a check if it was set of not, but then eventually the last part was
not implemented.

PAYARA-1715 Implemented processing of transactional attribute

---

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/ApplicationHandlers.java
appserver/admingui/common/src/main/resources/applications/deployTable.inc
appserver/admingui/common/src/main/resources/applications/edit.inc
appserver/admingui/core-l10n/src/main/resources/org/glassfish/admingui/core/Strings_es.properties
appserver/admingui/core-l10n/src/main/resources/org/glassfish/admingui/core/Strings_pt_BR.properties
appserver/admingui/core/src/main/resources/org/glassfish/admingui/core/Strings.properties
nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/Application.java
nucleus/common/glassfish-api/osgi.bundle
nucleus/common/glassfish-api/src/main/java/fish/payara/api/admin/config/ApplicationDeploymentTime.java
nucleus/common/glassfish-api/src/main/java/org/glassfish/api/admin/config/ApplicationDeploymentTime.java
nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/DeployCommand.java
nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/DeploymentCommandUtils.java
nucleus/deployment/admin/src/test/java/org/glassfish/deployment/admin/ListComponentsCommandTest.java
nucleus/deployment/common/src/test/java/org/glassfish/deployment/versioning/VersioningUtilsTest.java

Double data type gets funny in hk2, so I've put a double validator instead

Payara 1322 application deployment time

---

appserver/jdbc/admin/src/main/java/org/glassfish/jdbc/admin/cli/CreateJdbcConnectionPool.java
appserver/jdbc/admin/src/main/java/org/glassfish/jdbc/admin/cli/JDBCConnectionPoolManager.java
appserver/jdbc/jdbc-config/src/main/java/org/glassfish/jdbc/config/JdbcConnectionPool.java
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/monitoring/JdbcStatsProvider.java
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/monitoring/SQLTraceProbeProvider.java
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/ManagedConnectionFactoryImpl.java
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/util/FrequentSQLTraceCache.java
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/util/SQLTrace.java
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/util/SQLTraceCache.java
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/util/SQLTraceDelegator.java
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/fish/payara/jdbc/SilentSqlTraceListener.java
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/fish/payara/jdbc/stats/SlowSqlTrace.java
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/fish/payara/jdbc/stats/SlowSqlTraceCache.java
appserver/jdbc/jdbc-runtime/src/main/java/org/glassfish/jdbc/deployer/DataSourceDefinitionDeployer.java

Adds the capability to monitor the slowest SQL traces executed against a connection pool.
To enable this, turn on monitoring of the JDBC Connection pools in a config, for example:
`asadmin set server.monitoring-service.module-monitoring-levels.jdbc-connection-pool=HIGH`
It is configured in the same way as the frequent SQL tracing, using the _number-of-top-queries-to-report_ and _time-to-keep-queries-in-minutes_ properties:
```
asadmin set server.resources.jdbc-connection-pool.<POOL_NAME>.property.number-of-top-queries-to-report=15                    
asadmin set server.resources.jdbc-connection-pool.<POOL_NAME>.property.time-to-keep-queries-in-minutes=10  
```
The monitoring figures can be viewed via the admin console (under Resources > _Resource_ > JDBC Connection Pool Statistics), or …

PAYARA-1133 Slow SQL logger should keep the top and slowest SQL traces

---

appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/archivist/WebArchivist.java
appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/descriptor/WebBundleDescriptorImpl.java

application is still considered distributable when archives don't have web-fragment.xml are present.
fixes #1689

PAYARA-1765 Distributable web.xml handling broken for WEB-INF/lib archive

---

nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/GlassFishMain.java

Previous parsing method was replacing equals characters with spaces which causes problems with passing properties to commands.
e.g. command = "create-jdbc-connection-pool --datasourceclassname com.mysql.jdbc.jdbc2.optional.MysqlDataSource --restype javax.sql.DataSource --property user=root:password=password:serverName=localhost:portNumber=3306:databaseName=test test-connection-pool --user admin --passwordFile /opt/pwdfile"

PAYARA 1739 Pre and Post boot command parsing problem

---

appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/ClusteredCDIEventBusImpl.java
appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/context/ContextImpl.java
appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/context/JavaEEContextUtilImpl.java
appserver/web/weld-integration/src/main/java/org/glassfish/weld/BeanDeploymentArchiveImpl.java
appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java
nucleus/common/internal-api/src/main/java/org/glassfish/internal/api/JavaEEContextUtil.java
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/PayaraHazelcastSerializer.java
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/contextproxy/CacheManagerProxy.java
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/contextproxy/CacheProxy.java
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/contextproxy/CompleteConfigurationProxy.java
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/contextproxy/EntryProcessorProxy.java
nucleus/pom.xml

- Refactor JavaEEContextUtil APIs to greatly simplify and modernize it's usage
- Use try-with-resources for automatic context cleanup
- No more postInvoke, use automatic cleanup instead
- Bug fixes for JCache (add createCaache() support)
- fixed versioned BDA IDs for compatibility between versioned and non-versioned applications, especially the case with Payara Micro

PAYARA-1072 PAYARA-1740 Refactor context util and bug fixes

---

appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/deployer/AdministeredObjectDefinitionDeployer.java
appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/deployer/ConnectionFactoryDefinitionDeployer.java
appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/deployer/JMSConnectionFactoryDefinitionDeployer.java
appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/deployer/JMSDestinationDefinitionDeployer.java
appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/deployer/MailSessionDeployer.java
appserver/jdbc/jdbc-runtime/src/main/java/org/glassfish/jdbc/deployer/JdbcConnectionPoolDeployer.java
appserver/resources/javamail/javamail-runtime/src/main/java/org/glassfish/resources/javamail/deployer/MailResourceDeployer.java
appserver/resources/resources-connector/src/main/java/org/glassfish/resources/admin/cli/ResourcesXMLParser.java

ensure environment variable, password alias and system property replacement is possible when using glassfish-resources.xml

PAYARA-1792 Environment variable replacement does not work in glassfish-resources.xml

---

appserver/admingui/common/src/main/resources/security/securityAttrs.inc
nucleus/admin/template/src/main/resources/config/server.policy
nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/ldap/LDAPRealm.java
nucleus/security/core/src/main/resources/config/server.policy

Payara 1339

---

nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/GlassFishMain.java

Previous fix also removed the end of commands with hashtags in them as comments. 
E.g. 
`set configs.config.server-config.http-service.virtual-server.test.default-web-module=ear-test#ear-test-web-1.0-SNAPSHOT.war`
Now only removes comments if they have whitespace before them.

Payara 1739 Pre and post boot command files a little too thorough

---

appserver/admingui/war/src/main/webapp/WEB-INF/web.xml

explicit SEPARATOR_CHAR context parameter, in case default-web.xml overwrites it
fixes #1724

PAYARA-1816 explicit javax.faces.SEPARATOR_CHAR = : to admin console

---

appserver/admingui/healthcheck-service-console-plugin/src/main/resources/fish/payara/admingui/healthcheck/Strings.properties

To align with the documentation and blogs.
Documentation should also be fixed from Health Check to HealthCheck.

Changed Healthcheck to HealthCheck in Admin Console PAYARA-1859

---

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/xml/RuntimeTagNames.java
appserver/deployment/dtds/src/main/resources/glassfish/lib/dtds/glassfish-ejb-jar_3_1-1.dtd
appserver/ejb/ejb-container/pom.xml
appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/node/runtime/DefaultWebServiceLoginConfigNode.java
appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/node/runtime/EjbBundleRuntimeNode.java

added default EJB web service login configuration

PAYARA-1183 default web service realm configuration

---

nucleus/common/mbeanserver/src/main/java/org/glassfish/admin/mbeanserver/ConnectorStarter.java
nucleus/common/mbeanserver/src/main/java/org/glassfish/admin/mbeanserver/RMIConnectorStarter.java

JMX Connector allowing connections from remote hosts on all network interfaces by specifying  "0.0.0.0" or "*" .

PAYARA-1723 JMX Connector bind on all network interfaces

---

appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionalInterceptorBase.java

Whilst the scenario causing to this println is not supposed to happen, it's currently happening a very large number of times a second on one of my servers, and being unable to turn off the message to get at more pertinent logging is making it hard to fix.

Use logging instead of System.out.println PAYARA-1878

---

appserver/packager/JMX-Monitoring/pom.xml
appserver/packager/glassfish-jmx/pom.xml

The plugin is for the admingui, and should not be built with Micro

PAYARA-1949 moved the jmx-monitoring-plugin package

---

nucleus/pom.xml

The plugin will no longer run as part of the site lifecycle by default, it already has its own profile.

PAYARA-1898 Disabled findbugs plugin

---

appserver/pom.xml

PAYARA-2054 This resolves the needless necessity of having a 2.3 faces-config.xml
file.
See https://github.com/payara/Payara_PatchedProjects/pull/81

PAYARA-2054 Updated Mojarra with patched version

---

appserver/connectors/connectors-connector/src/main/java/com/sun/enterprise/connectors/connector/module/RarDetector.java
nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/GenericAnnotationDetector.java

All archives are now checked for annotations, regardless of type

PAYARA-1840 RAR detector now checks for all JCA annotations

---

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/FileSystemItemValidator.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/FileValidator.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java

Fixes #1953
Precedence in highest precedence first order is
1) Command line option
2) Property loaded via --systemproperties command line option
3) Property set in the uber jar MICRO-INF/deploy/payaramicro.properties
4) Property set in the uber jar MICRO-INF/payara-boot.properties
5) Property set on the command line via -D

PAYARA-2063 fixed precedence on loading user defined configuration properties

---

appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardHostValve.java
appserver/web/web-core/src/main/java/org/apache/catalina/util/URLPattern.java

Tested with example application and custom application, behaviour remains the same, just without the error page. If a file is provided and configured within Wicket, but cannot be found, then Wicket will throw the error - if a file is correct but incorrectly configured then Payara's behaviour remains the same.
Thanks for @arjantijms and @MattGill98 for the help!
Fixes #1886

PAYARA-2111 Fixed warning in logs from mismatched error page

---

appserver/payara-appserver-modules/jmx-monitoring-service/src/main/java/fish/payara/jmx/monitoring/admin/SetMonitoringConfiguration.java

JMX Monitoring values which have spaces as part of their name, path, or type can now be entered by escaping the space:
`name=PS\ Scavenge`

PAYARA-2240 JMX monitoring values with spaces now recognised

---

appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/domain.xml

Disables JMX Log Monitoring by default in Payara Micro

PAYARA-2247 disable jmx log monitoring service by default.

---

nucleus/payara-modules/asadmin-recorder/src/main/java/fish/payara/asadmin/recorder/AsadminRecorderService.java

The asadmin recorder output file location will now always be substituted, regardless of thread-local configuration

PAYARA-2281 System Property Substitution Fails For Asadmin Recorder

---

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/annotation/impl/ModuleScanner.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java

This fixes and improves #2150. It uses `Executors.newCachedThreadPool(..)` instead of a fixed thread pool with the number of available processors as size instead.

Improvement for high number of JAR scanning threads.

---

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/RestUtil.java
appserver/admingui/jmx-monitoring-plugin/src/main/resources/fish/payara/admingui/jmxmonitoring/Strings.properties
appserver/admingui/jmx-monitoring-plugin/src/main/resources/jmxmonitoring/jmxmonitoring.jsf
appserver/admingui/jmx-monitoring-plugin/src/main/resources/jmxmonitoring/monitoredAttributeTable.inc
appserver/payara-appserver-modules/jmx-monitoring-service/src/main/java/fish/payara/jmx/monitoring/LocalStrings.properties
appserver/payara-appserver-modules/jmx-monitoring-service/src/main/java/fish/payara/jmx/monitoring/MonitoringService.java
appserver/payara-appserver-modules/jmx-monitoring-service/src/main/java/fish/payara/jmx/monitoring/admin/GetMonitoringConfiguration.java
appserver/payara-appserver-modules/jmx-monitoring-service/src/main/java/fish/payara/jmx/monitoring/admin/SetMonitoringConfiguration.java
appserver/payara-appserver-modules/jmx-monitoring-service/src/main/java/fish/payara/jmx/monitoring/configuration/MonitoredAttribute.java
appserver/payara-appserver-modules/jmx-monitoring-service/src/main/java/fish/payara/jmx/monitoring/configuration/MonitoringServiceConfiguration.java
nucleus/admin/rest/rest-service/src/main/java/fish/payara/admin/rest/resources/MonitoredAttributeBagResource.java
nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/generator/ASMClassWriter.java
nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/generator/ResourcesGeneratorBase.java

- Updated command set-monitoring-configuration from the format `--addproperty name=x value=x` to `--addattribute attributeName=x objectName=x`. Old command syntax is maintained for backwards compatibility.
- Multiple properties are added by providing multiple --addproperty commands.
- Better validation and output messages added to set-monitoring-configuration command.
- New MonitoredAttribute bean created, and REST endpoint to access it: `monitoring-service-configuration/monitored-attribute.json`. Functions vastly similar to the old `property.json` page, but with the new format.
- Admin console updated to reflect new changes.
- Updated admin console REST util to allow data in the body of a PUT request.

PAYARA-2285 Jmx Monitoring Same Attribute Different Beans Merge

---

appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java

Disable CDI when WAR bean archive is set to BeanDiscoveryMode.NONE so CDI extensions such as Soteria etc. won't fail
Fixes #2112

PAYARA-2309 fix broken deployment when BeanDiscoveryMode is NONE

---

nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/ListDomainsCommand.java
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/LocalStrings.properties
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/StopDomainCommand.java
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/Strings.java

PAYARA-2113 Made stop-domain a little more descriptive

---

appserver/packager/external/jcip/pom.xml
appserver/packager/legal/src/main/resources/glassfish/legal/PAYARA-3RD-PARTY-LICENSE.txt
appserver/pom.xml

PAYARA-2341 creates a JCIP jar with the OSGi headers in MANIFEST.MF, but does not yet add this as a dependency to Payara.

PAYARA-2341 repackage JCIP annotations with OSGi headers

---

nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/MemberAddressPicker.java

Fix selection of IP addresses on Windows Server

PAYARA-2352 Fix Windows Data Grid Discovery

---

appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/FormAuthenticator.java

Fix FormAuthenticator corrupting post parameters.

---

appserver/jms/gf-jms-injection/src/main/java/org/glassfish/jms/injection/InjectableJMSContext.java

make skip resource registration is on by default
There are no bad sideffects due to this change

PAYARA-2377 JMS 2.0 context race condition workaround on by default

---

appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/cdi/extension/MetricCDIExtension.java
appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/cdi/interceptor/AbstractInterceptor.java
appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/cdi/interceptor/MetricsInterceptor.java
appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/rest/MetricsResource.java

MP-Metrics log warning fix :
Warning: The following warnings have been detected: WARNING: Parameter bean of type javax.enterprise.inject.spi.Bean from protected javax.enterprise.inject.spi.Bean fish.payara.microprofile.metrics.cdi.interceptor.MetricsInterceptor.bean is not resolvable to a concrete type.
Severe: No valid EE environment for injection of fish.payara.microprofile.metrics.cdi.producer.MetricRegistryProducer

PAYARA-2432 MP-Metrics log warning fix

---

nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigProviderResolverImpl.java

Addition of metrics api broke config api due to order of initialisation. 
This corrects that in 4.x

PAYARA-2395 Fix Microprofile Config API for 4.181 release

---

appserver/extras/arquillian-containers/payara-common/pom.xml
appserver/extras/arquillian-containers/payara-common/src/main/java/fish/payara/arquillian/container/payara/PayaraVersion.java
appserver/extras/arquillian-containers/payara-common/src/test/java/fish/payara/arquillian/container/payara/PayaraVersionTest.java
appserver/extras/arquillian-containers/payara-micro/pom.xml
appserver/extras/arquillian-containers/payara-micro/src/main/java/fish/payara/arquillian/container/payara/managed/PayaraMicroContainerConfiguration.java
appserver/extras/arquillian-containers/payara-micro/src/main/java/fish/payara/arquillian/container/payara/managed/PayaraMicroDeployableContainer.java

- The Arquillian container now accepts either old or new instance descriptor format.
- Added hierarchy to container configuration variables. They will now take values from system properties if possible, then environment variables, then the default value.
- New configurable options are: 
| Option | Description | System Property | Environment Variable | Default |
| --- | --- | --- | --- | --- |
| `microJar` | Provides the location of the Payara Micro Jar | `payara.microJar` | `MICRO_JAR` | `null` |
| `clusterEnabled` | Enables clustering on the Micro instance. | `payara.clusterEnabled` | `MICRO_CLUSTER_ENABLED` | `false` |
| `consoleOutput` | Enables/disables console output on the Micro instance. | `payara.consoleOutput` | `MICRO_CONSOLE_OUTPUT` | `true` |
| `debug` | Enables debugging on …

PAYARA-2500 Update Micro Arquillian Container For New Instance Descriptor Format

---

appserver/extras/payara-micro/payara-micro-distribution/pom.xml
appserver/packager/microprofile-package/pom.xml

PAYARA-2516 JWT was failing in Micro since all dependencies were missing. Fixed by including the whole packager output, as should have been the case in the first place. Removed JDK 8 profile as well and applied formatting.

PAYARA-2516 Fixed JWT failure by correcting packager pom

---

appserver/admingui/cluster/src/main/resources/dg/dgGeneral.jsf
appserver/admingui/cluster/src/main/resources/dg/listEjbTimersDG.jsf
appserver/admingui/cluster/src/main/resources/dg/migrateEjbTimersDG.jsf
appserver/admingui/ejb/src/main/resources/configuration/ejbContainerTimerService.jsf
appserver/admingui/ejb/src/main/resources/ejbTimerButtonsDG.jsf
appserver/admingui/ejb/src/main/resources/org/glassfish/ejb/admingui/Strings.properties
appserver/ejb/ejb-connector/src/main/java/org/glassfish/ejb/config/EjbTimerService.java
appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/admin/cli/ListTimers.java
appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/admin/cli/MigrateTimers.java
appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/startup/EjbDeployer.java
appserver/ejb/ejb-container/src/main/resources/org/glassfish/ejb/admin/cli/LocalStrings.properties
appserver/ejb/ejb-full-container/src/main/java/org/glassfish/ejb/persistent/timer/DatabaseEJBTimerService.java
appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/domain.xml
appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/IiopFolbGmsClient.java
appserver/packager/glassfish-ejb/pom.xml
appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/DataGridEJBTimerService.java
appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastTimerStore.java
nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ListInstancesCommand.java
nucleus/common/internal-api/src/main/java/org/glassfish/internal/api/Target.java
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/cluster/ClusterListener.java
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/cluster/MemberEvent.java
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/cluster/PayaraCluster.java

PAYARA-1079 Add DataGrid Timer Store

---

appserver/payara-appserver-modules/microprofile/config/src/main/java/fish/payara/microprofile/config/cdi/ConfigProducer.java

Fix to Microprofile Config api to ensure the optional is injected as empty if no value is specified for the property
```java
@Inject
@ConfigProperty(name="test")
Optional<String> value;
```

PAYARA-2511 Ensure Optional property is returned as empty and not as unconfigured value

---

appserver/ejb/ejb-connector/src/main/java/org/glassfish/ejb/config/EjbContainer.java
appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/StatelessSessionContainer.java
appserver/payara-appserver-modules/zendesk-support/src/main/java/fish/payara/appserver/zendesk/admin/SetZendeskSupportConfigurationCommand.java
appserver/payara-appserver-modules/zendesk-support/src/main/java/fish/payara/appserver/zendesk/config/ZendeskSupportConfiguration.java
nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/AMXStartupService.java
nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/config/AMXConfigLoader.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/admin/GetConfigOrdinal.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/admin/SetConfigOrdinal.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/ApplicationConfigSource.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/ClusterConfigSource.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/ConfigConfigSource.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/DomainConfigSource.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/JNDIConfigSource.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/ModuleConfigSource.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/SecretsDirConfigSource.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/ServerConfigSource.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/MicroprofileConfigConfiguration.java

- Changed HK2 Config properties to String data type.
- Added appropriate conversions.
- Converted error messages with no localisation to an appropriate string.

PAYARA-2283 Illegal Type Error In Logs

---

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PortBinder.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/GrizzlyProxy.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/GrizzlyService.java
nucleus/core/kernel/src/main/java/fish/payara/kernel/services/impl/MicroNetworkListener.java
nucleus/core/kernel/src/main/java/org/glassfish/kernel/KernelLoggerInfo.java

- Payara Micro now reserves the ports it's configured once it's found them, so that two Micro instances starting up simultaneously don't choose the same port. Allows many Micro instances to startup at the same time.
- Merged `Started Grizzly Framework` messages into one.

PAYARA-2515 Micro Arquillian Tests Fail In Parallel

---

nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/DomainDiscoveryService.java

PAYARA-2523 Handle some simple mistakes when specifying domain cluster mode in micro
localhost or 127.0.0.1 specified most likely IP address chosen
4848 specified as port a warning is printed that the default is 4900

PAYARA-2523 Handle some simple mistakes when specifying domain cluster mode

---

appserver/extras/arquillian-containers/payara-micro/src/main/java/fish/payara/arquillian/container/payara/managed/PayaraMicroContainerConfiguration.java
appserver/extras/arquillian-containers/payara-micro/src/main/java/fish/payara/arquillian/container/payara/managed/PayaraMicroDeployableContainer.java

This should&trade; also work on windows.

PAYARA-2555 Micro Arquillian Container Doesn't Allow Spaces In Arguments

---

appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/SecServerRequestInterceptor.java

make call counter ThreadLocal instead of InteritedThreadLocal, was causing trouble with thread pools and authentication

PAYARA-2561 CORBA authentication leakage

---

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/EJBUtils.java

added LinkageError to the catch statement so the error actually gets caught

PAYARA-2564 multi-threaded InitialContext() fix

---

nucleus/admin/config-api/src/main/java/org/glassfish/config/support/TargetBasedResolver.java
nucleus/admin/rest/rest-service/src/main/java/fish/payara/admin/rest/resources/MonitoredAttributeBagResource.java
nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/CollectionLeafResource.java
nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/LeafResource.java
nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/PropertiesBagResource.java
nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateListOfResource.java
nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateRestResource.java
nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/custom/SystemPropertiesCliResource.java
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/DomainXmlVerifier.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/DeleteSystemProperty.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/V2DottedNameSupport.java
nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/dom/NetworkListener.java
nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/dom/ThreadPool.java

synchronized all getter access to the Dom class due to Dom not being thread-safe, as per PAYARA-2541

PAYARA-2541 synch HK2 Dom class race condition

---

appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/util/InjectionManagerImpl.java
appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/descriptor/WebBundleDescriptorImpl.java
appserver/web/weld-integration/src/main/java/org/glassfish/weld/DeploymentImpl.java
appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java

- Fixed InjectionManager to defer looking up JNDI until it knows it's the correct class
- CDI injection services are added with the proper BDA/Bundle combindations
Fixes regressions introduced with PAYARA-1200 and couple of upstream bugs
fixes #2081

PAYARA-2229 fixed CDI extension injection regression with EAR files

---

appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/PayaraMicro.java
appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/PayaraMicroBoot.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/RUNTIME_OPTION.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/UberJarCreator.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/ssl/GlassfishServerSocketFactory.java
nucleus/security/ssl-impl/src/main/java/com/sun/enterprise/security/ssl/impl/SecuritySupportImpl.java

to specify the certificate alias to use in the keystore
Also adds some extra logging is SSL is misconfigured
Also correctly packages up alternate keystores into the Uber Jar if specified via system properties

PAYARA-2615 Add support for Payara Micro command line option --sslCert

---

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/util/ResourceValidator.java

Continuation of https://github.com/payara/Payara/pull/2520.

PAYARA-2583 Continue Classloader Leak Fix

---

nucleus/admin/config-api/src/main/java/org/glassfish/config/support/ServerReaderFilter.java

added fish.payara.configFileEncoding JVM option / System property to set config file encoding (i.e. domain.xml)

PAYARA-2633 set domain.xml file encoding - Payara 4

---

nucleus/admin/config-api/src/main/java/org/glassfish/config/support/ServerReaderFilter.java

added fish.payara.configFileEncoding JVM option / System property to set config file encoding (i.e. domain.xml)

PAYARA-2633 set domain.xml file encoding

---

nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/AdminMain.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/CLICommand.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/CLIConstants.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/CLIContainer.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/CLIProcessExecutor.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/CLIUtil.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/ClassPathBuilder.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/DirectoryClassLoader.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/Environment.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/ExportCommand.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/HelpCommand.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/ListCommandsCommand.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/LoginCommand.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/More.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/MultimodeCommand.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/Parser.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/ProgramOptions.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/StringEditDistance.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/Strings.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/UnsetCommand.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/VersionCommand.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/embeddable/CommandExecutorImpl.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/embeddable/DeployerImpl.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/remote/ClientCookieStore.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/remote/DASUtils.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/remote/RemoteCLICommand.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/remote/RemoteCommand.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/schemadoc/ClassDef.java

Resolves warnings and code smells from sonarcloud, excluding duplications and cognitively complexity

PAYARA-2708 Cleanup code in nucleus/admin/cli

---

nucleus/security/core/src/main/java/com/sun/enterprise/security/ssl/GlassfishSSLImpl.java
nucleus/security/core/src/test/java/com/sun/enterprise/security/ssl/GlassfishSSLImplTest.java

Based on the analysis in https://github.com/payara/Payara/issues/2613 i'd like to present a one-liner fix. This fix has the added benefit of reloading the relevant keystore(s) whenever a listener is enabled. 
Thus this change makes the procedure outlined in https://github.com/payara/Payara/issues/1047, specifically,
```
asadmin set server.network-config.network-listeners.network-listener.http-listener-2.enabled=false
asadmin set server.network-config.network-listeners.network-listener.http-listener-2.enabled=true
```
to activate the new keypair from letsencrypt (and alias) working.
I have tested this with secure-admin enabled admin port (4848), as well as two separate listeners on different ports and using different keystores/aliases. All was working.
According to my research, the only …

Bugfix: listener not using the correct keystore

---

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/util/ResourceValidator.java
appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/ContextImpl.java
appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/JavaEEContextUtilImpl.java
nucleus/common/internal-api/src/main/java/org/glassfish/internal/api/JavaEEContextUtil.java

unset capturedInvocation (reset to null) if JNDI environment is not present,
signifying invalid invocation.  fixes #2581

PAYARA-2691 fix ResourceValidator Class Loaders

---

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/util/ResourceValidator.java
appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/ContextImpl.java
appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/JavaEEContextUtilImpl.java
nucleus/common/internal-api/src/main/java/org/glassfish/internal/api/JavaEEContextUtil.java

unset capturedInvocation (reset to null) if JNDI environment is not present,
signifying invalid invocation.

PAYARA-2691 resource validation context cl p4

---

appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/CircuitBreakerInterceptor.java

A small error in the exception message when a circuit is open (MicroProfile Fault tolerance)
throw new CircuitBreakerOpenException("CircuitBreaker for method " 
+ invocationContext.getMethod().getName() + **" is** in state OPEN.");
Space added before the 'is'.

Added a space in the exception message of CircuitBreakerOpenException

---

appserver/pom.xml

ASM Plugin bundled with EclipseLink 2.6.5 requires JDK8.

PAYARA-2592 Back Updated EclipseLink out of JDK7 Build

---

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java

moved code that uses handle.getInvocation() into the if() block that _does_ a null check for the former
fixes #2794

PAYARA-2779 fix NPE regression in concurrent

---

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java

moved code that uses handle.getInvocation() into the if() block that does a null check for the former

PAYARA-2779 fix NPE regression in concurrent for Payara 4

---

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ApplicationProcessor.java

Limited schema creation to classes in the application classlist.
Still passes TCK.

PAYARA-2830 StackOverflowError in OpenAPI

---

appserver/web/weld-integration/src/main/java/org/glassfish/weld/BeanDeploymentArchiveImpl.java
nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/JarFileUtils.java
nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/UndeployCommand.java
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/util/CleanupPostBoot.java

PAYARA-2848 catch ConcurrentModificationException

---

appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/InjectionServicesImpl.java
appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/NonModuleInjectionServices.java

Remove spurious SEVERE message on deployment

PAYARA-2855

---

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ApplicationProcessor.java

Add check for classes with fields with a type of themselves to prevent infinite recursion

PAYARA-2846 StackOverflowException in OpenAPI

---

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java
appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/ClusteredCDIEventBusImpl.java

Unexpected null values when CDI event triggered from server context and not from app context

PAYARA-2824 Fixes in CDI event notif.

---

appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/GlassFishORBManager.java
appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/POARemoteReferenceFactory.java
appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/SecurityMechanismSelector.java

added system property fish.payara.orb.disable-ssl-check to make remote EJB calls accessible in development

PAYARA-2835 local SSL remote EJB call fallback property

---

appserver/security/core-ee/src/main/java/com/sun/enterprise/security/provider/JDKPolicyFileWrapper.java

This fix stops the NullPointerExceptions, and I don't see any obvious problem with the contextID being null in the first place. Needs a review to make sure this is the case.

PAYARA-2874 Enabling Security Manager Causes Log Errors

---

appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/DB2PersistenceManager.java
appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/JBatchJDBCPersistenceManager.java
appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/MySqlPersistenceManager.java
appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/OraclePersistenceManager.java
appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/PostgresPersistenceManager.java
appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/SQLServerPersistenceManager.java
appserver/common/glassfish-naming/src/main/java/com/sun/enterprise/naming/util/NamingUtilsImpl.java
appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/PayaraMicroLauncher.java
appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/loader/ExplodedURLClassloader.java
appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/loader/Launcher.java
appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/loader/jar/JarFile.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/RuntimeDirectory.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/UberJarCreator.java
appserver/persistence/cmp/enhancer/src/main/java/com/sun/jdo/api/persistence/enhancer/Main.java
appserver/persistence/cmp/generator-database/src/main/java/com/sun/jdo/spi/persistence/generator/database/DatabaseOutputStream.java
appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/DelegatedRecoveryManager.java
appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/RecoveryManager.java
appserver/web/web-core/src/main/java/org/apache/catalina/session/StandardSession.java
nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/provider/ProgressStatusEventJsonProvider.java
nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/provider/ProgressStatusJsonProvider.java
nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/readers/JsonHashMapProvider.java
nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/readers/JsonParameterMapProvider.java
nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/readers/RestModelListReader.java
nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/readers/RestModelReader.java
nucleus/admin/util/src/main/java/com/sun/enterprise/admin/remote/reader/ProgressStatusEventJsonProprietaryReader.java
nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ValidateDcom.java
nucleus/common/common-util/src/main/java/com/sun/enterprise/util/net/NetUtils.java
nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/Syslog.java

Fixes some of the resource handling issues found by SonarQube in #2674

#2674 fixing several resource handling misses

---

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/api/OpenAPIBuildException.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/OpenApiService.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ApplicationProcessor.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/rest/app/service/OpenApiResource.java

- Deferred OpenAPI scanning until the `/openapi` endpoint is visited.
- Allowed document creation for apps deployed while the OpenAPI service is disabled, since it's now created on endpoint visiting.
- Added a null check to prevent potential `@Produces` errors.

PAYARA-2889 Defer OpenAPI Scanning Until Endpoint Visit

---

nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/InjectedPayaraConfig.java

PAYARA-2880 Implemented getPropertyNames in microprofile config

---

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/InstanceHandler.java
nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/CollectionLeafResource.java

- Fixed error handling in InstanceHandler to not obscure error.
- Removed HashMap from result output.
- Configured the dynamic JVM options to be built before a restart.

PAYARA-2910 RuntimeException in Admin Console JVM Options

---

nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/PayaraConfig.java

When the ConfigProperty is used with Injection the PayaraConfig is always called with a default value (org.eclipse.microprofile.config.configproperty.unconfigureddvalue).
The logic to notice that no property is found requires the StringConverter to throw the DeploymentException. The cast to String and return before Converters are determined prevents this.
Removed this line of code.
Fixes issue #2986.

Fix for #2986 Missing String ConfigProperty should cause DeploymentException

---

appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/JaxrsContainerRequestTracingFilter.java

Fixes an IllegalStateException that can occur when a JAX-RS method of an app with no CDI beans is called with request tracing enabled.

PAYARA-2923 Fix OpenTracing IllegalStateException

---

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/GenerateBashAutoCompletionCommand.java

This creates a file that when run adds glassfish/bin to the path and creates autocompletion of asadmin commands

PAYARA-1714 Added command to generate bash autocomplete

---

appserver/packager/glassfish-common-web/src/main/resources/bin/letsencrypt.py

Requires certbot with the webroot plugin.
The idea is to deploy an empty war (as a directory, using in-place deployment) and provide that directory's path to certbot's webroot plugin to pass the challenge.
Script is written in python, because certbot itself requires python. As certbot works only under linux, so does this script.
Proper functionality (reloading the keystore and restarting the listener) requires https://github.com/payara/Payara/commit/b3bd6b073dca50de17b5161d37b59b12827f3573 and https://github.com/payara/Payara/commit/83fb3c15e445575384d7f9966e4a9209d9571639
fixes #1047

PAYARA-1061 LetsEncrypt integration script

---

appserver/web/web-core/src/main/java/org/apache/catalina/session/FileStore.java
appserver/web/web-core/src/main/java/org/apache/catalina/session/PersistentManagerBase.java

from sessions being stored in memory with file persistence

PAYARA-2931 Resolved memory leak

---

appserver/web/web-core/src/main/java/org/apache/catalina/session/FileStore.java
appserver/web/web-core/src/main/java/org/apache/catalina/session/PersistentManagerBase.java

PAYARA-2931 Resolved memory leak
https://github.com/payara/Payara/pull/3048

PAYARA-2931 Resolved Memory Leak - Payara4

---

appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/cdi/CdiExtension.java
appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/SignedJWTIdentityStore.java
appserver/pom.xml

Depends on : 
https://github.com/payara/Payara_PatchedProjects/pull/180
https://github.com/payara/MicroProfile-TCK-Runners/pull/13
https://github.com/payara/patched-src-microprofile-jwt-auth/tree/jwt-auth-1.1.payara-p1

PAYARA-2853 Microprofile JWT Auth v1.1 impl

---

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/BaseContainer.java

Depends on :
https://github.com/payara/patched-src-jersey/pull/3

PAYARA-3119 NullPointerException when starting Jersey/EJB Containers in Order

---

.gitignore

Eclipse and VScode use this file for annotation processing. It should be removed from the codebase.

PAYARA-3154 Add .factorypath to .gitignore.

---

nucleus/common/common-util/src/main/java/com/sun/enterprise/security/store/AsadminSecurityUtil.java

Make Payara `$HOME/.gfclient` directory configurable, to change it set the `AS_GFCLIENT` variable in `asenv.bat/asenv.sh`.
This is fundamental when the user who launch Payara does not have an home directory with write right granted
(this can happen for security reasons/company policies).
[asenv_examples.zip](https://github.com/payara/Payara/files/2378330/asenv_examples.zip)

Configurable .gfclient directory

---

nucleus/core/logging/src/main/java/fish/payara/enterprise/server/logging/JSONLogFormatter.java

Log throwable exception into THROWABLE_KEY instead of LOG_MESSAGE_KEY to keep consistent structure log message.

PAYARA-2952 - Log Json Formatter - LogMessage type

---

appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/cdi/TracedInterceptor.java

This resolves a warning when persisting session scoped beans

PAYARA-3110 Made TracedInterceptor serializable

---

appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/MetricsService.java

PAYARA-2938 : Warn when multiple references to OperatingSystem/SystemCpuLoad (Payara 4.x)

---

nucleus/security/core/src/main/java/com/sun/enterprise/security/ssl/GlassfishSSLSupport.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/ssl/J2EEKeyManager.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/ssl/SSLUtils.java
nucleus/security/ssl-impl/src/main/java/com/sun/enterprise/security/ssl/impl/MasterPasswordImpl.java
nucleus/security/ssl-impl/src/main/java/com/sun/enterprise/security/ssl/impl/SecuritySupportImpl.java
nucleus/security/ssl-impl/src/main/java/com/sun/enterprise/server/pluggable/SecuritySupport.java

PAYARA-3184 made the SecuritySupport contract (responsible of certificate loading for SSL) resettable.

Payara 3184 security support reset

---

appserver/extras/payara-micro/payara-micro-distribution/pom.xml
nucleus/packager/nucleus-hk2/pom.xml

With this PR Payara Micro works on JDK11 with the command
java --add-opens java.base/jdk.internal.loader=ALL-UNNAMED -jar payara-micro.jar

PAYARA-3129 add dependencies for classes removed in JDK11

---

appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/JaxrsContainerRequestTracingExceptionMapper.java
nucleus/pom.xml

Also updates Jersey so that priority ordering actually works
See:
* 2.27.payara-p13 - source change (original): payara/patched-src-jersey@ad9e68a
* 2.27.payara-p13 - jar deployment:   https://github.com/payara/Payara_PatchedProjects/pull/195/commits/7f9002a4912e31ab7350c46455f48b21cf9b2e6c

PAYARA-3125 Set OpenTracing Exception Mapper to the lowest priority

---

appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/util/JavaEEIOUtilsImpl.java
appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/spi/util/GlassFishInputStreamHandler.java
appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/spi/util/GlassFishOutputStreamHandler.java
appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/spi/util/JavaEEIOUtils.java

https://sonarcloud.io/project/issues?id=org.glassfish.main%3Aglassfish-main-aggregator&moduleUuids=AWJyK9gD1B6WA4TgV2m-&resolved=false&types=BUG

PAYARA-3221 Fixing sonar bugs in module container common.

---

nucleus/pom.xml

PAYARA-3196 Upgrade grizzly-npn to 1.8.1 for JDK 8u191

---

nucleus/pom.xml

This upgrade mandates the use of JDK8u191 or higher, which isn't widely available yet.

Temp revert Grizzly-NPN Upgrade

---

appserver/web/weld-integration/src/main/java/org/glassfish/weld/BeanDeploymentArchiveImpl.java

implement getKnownClasses and getLoadedClasses for BeanDeploymentArchive as a small optimisation as we know the results

PAYARA-3215 Small Weld deployment optimisation

---

Jenkinsfile

Leaves a JDK7 build and quicklook test just to some quick checks for compile errors.

Temporarily disable most JDK7 tests

---

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/EJBUtils.java

When remote EJBs Proxy/Wrapper classes are initially accessed/generated simultanously from multiple threads after start or restart of an app this LinkageError occurs when the second thread tries to store the generated class in the app classloader.
Fixes #3087 
Fixes #2763

Fixes linkage error concurrently loading remote EJBs

---

nucleus/deployment/autodeploy/pom.xml
nucleus/deployment/autodeploy/src/main/java/org/glassfish/deployment/autodeploy/AutoDeployService.java

As part of the thread reduction moved the AutoDeployer timer task onto the common Payara Scheduled Executor Service

PAYARA-3250 move AutoDeployer thread onto the Scheduled Payara Executor Service

---

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/EJBUtils.java
appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/BaseContainer.java

Refactoring the previously added synchronization code to prevent LinkageError also when generating EJBHome and Webservice SEI classes.
Extends the fix for #3087 and #2763 to EJBHome and Webservice SEI class generation.

PAYARA-3265 Fixing linkage errors with generated classes (Part 2)

---

nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfig.java
nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java
nucleus/common/common-util/src/main/java/com/sun/enterprise/util/PropertyPlaceholderHelper.java
nucleus/common/common-util/src/test/java/com/sun/enterprise/util/PropertyPlaceholderHelperTest.java
nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogFacade.java
nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java
nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/ListLogAttributes.java

Now it's possible to use references to environment variables in logging.properties.
${ENV=XXX}, where XXX is environment variable

PAYARA-3266 Using environment variable in logging.properties

---

nucleus/payara-modules/healthcheck-core/pom.xml
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HealthCheckService.java
nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/PayaraExecutorService.java

Reduce thread usage by using the common Executor Service

PAYARA-3252 refactor the healthcheck service to use the Payara Executor Service

---

nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/PayaraExecutorService.java
nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/PayaraExecutorServiceConfiguration.java

- increasing default queue size to 500 which makes pool exhaustion less likely
- adding RejectedExecutionHandler `ThreadPoolExecutor.CallerRunsPolicy` to prevent task rejection when pool is exhausted with the effect that the task is run in the callers thread immediatley
Fixes #3495

PayaraExecutorService - Increasing default queue size and adding RejectedExecutionHandler CallerRunsPolicy

---

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/visitor/OpenApiWalker.java

PAYARA-3258 Disabled Path Based Annotations For Interfaces

---

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java

Addressing https://payara.atlassian.net/browse/PAYARA-3310.
After some discussion it was decided to only allow both or none argument. If only one argument would be passed it cannot be decided if _namespace_ or _service-name_ was meant. To avoid confusion we do not allow single option.
When passing options via `SetHazelcastConfiguration` both parameters are already optional so that any combination can be set. The namespace in `HazelcastRuntimeConfiguration` uses a default of `"default"` so one needs to explicitly set this to empty to not set any of the two.

Make Service Name and Namespace Options for Kubernetes Cluster mode Optional PAYARA-3310

---

nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/SetHealthCheckServiceNotifierConfiguration.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/notifier/CDIEventbusHealthCheckNotifierConfigurer.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/notifier/DatadogHealthCheckNotifierConfigurer.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/notifier/EmailHealthCheckNotifierConfigurer.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/notifier/EventbusHealthCheckNotifierConfigurer.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/notifier/HipchatHealthCheckNotifierConfigurer.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/notifier/JmsHealthCheckNotifierConfigurer.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/notifier/LogHealthCheckNotifierConfigurer.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/notifier/NewRelicHealthCheckNotifierConfigurer.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/notifier/SlackHealthCheckNotifierConfigurer.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/notifier/SnmpHealthCheckNotifierConfigurer.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/notifier/XmppHealthCheckNotifierConfigurer.java

This PR is only one part of the effort of PAYARA-1896 split for easier review.
Goal was to combine the various asadmin commands to set individual health check notifier configurations into one command. To not break existing commands these were deprecated and a new command `set-healthcheck-service-notifier-configuration` was added.
The working principle of the new service is largely based on the `BaseHealthCheckNotifierConfigurer` that was the base class for the various specific commands.
The new command has an additional parameter to specify the type of notifier the setting should apply to. The list of possible values is based on the enum `NotifierType`. The code is entirely written so newly added types of notifiers do not require changes to this service/command.
Like the …

PAYARA-1896 Unified asadmin command to set health check notifier configuration

---

appserver/payara-appserver-modules/microprofile/healthcheck/src/main/java/fish/payara/microprofile/healthcheck/HealthCheckService.java

PAYARA-3438: Improve usability MP Health endpoint as readinessProbe

---

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/boot/runtime/MicroGlassFish.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/RUNTIME_OPTION.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/GlassFishImpl.java

Initially the plan was to use `domain.xml` based configuration for the grace period setting. I looked into it but it turned out to be overly complicated due to module dependencies and access limitations. So I went for the simpler option using `System` property `fish.payara.shutdowngrace` instead. The period is given is milliseconds. E.g. `-Dfish.payara.shutdowngrace=1000` for 1 second grace period.
After a first look into where to add the waiting it seamed most appropriate on the outermost level, like the `PayaraMicroImpl#shutdown` and equivalent methods. After deeper investigation on possible paths during shutdown I found that the common abstraction to server, micro and embedded that is called independent on how the shutdown was initiated should be the `GlassFish` abstraction. While …

PAYARA-3344 Added System Property for Shutdown Grace Period

---

nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/adapter/RestAdapter.java
nucleus/pom.xml

Fixes retrieving the monitoring data of remote instances from the DAS.
When using the module / bundle classloader, it fails to find any of the Jersey services (despite them being present). This change takes inspiration from [here](https://github.com/payara/Payara/blob/master/nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/adapter/RestAdapter.java#L299) to switch the classloader to the common one, which *can* find the Jersey services,

PAYARA-3028 Fix remote monitoring of instances from the admin console

---

appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/FormAuthenticator.java

The ticket requested configuration either based on a system property or as part of a specific configuration.
I decided to use the system property as this communicates clearly that this is a general "global" on/off switch that applies to all instances and applications. To me this is the most sensible way to implement this feature as it prevents unintentionally permitting any HTTP method for some instances or apps due to using wrong configuration scope.
If customers want to apply the system property cluster wide there is already a mechanism build into the admin GUI that allows to do so: `server => Properties => System Properties (Add Property)`. This also allows to set or change the property after startup. 
For the property name I decided for `fish.payara.permittedFormBasedAuthHttpMethods` …

PAYARA-3318 Restrict permitted HTTP method for FORM based auth

---

appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/AppClientContainer.java
appserver/common/glassfish-naming/src/test/java/com/sun/enterprise/naming/impl/AppTest.java
appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java
appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/InvocationContext.java
appserver/ejb/ejb-container/src/main/java/com/sun/ejb/EjbInvocation.java
appserver/ejb/ejb-full-container/src/main/java/org/glassfish/ejb/mdb/MessageBeanContainer.java
appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebComponentInvocation.java
appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java
nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/ComponentInvocation.java

PAYARA-3451 Managed Scheduled Executor Service doesn't execute tasks from versioned applications

---

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java

Adding an option (see #3702) I noticed some duplication in the argument parsing of payara micro.
This PR does some smaller code level improvements.
Mainly the reoccurring `try`-`catch` block to parse arguments to `TimeUnit`, `int` or `long` was extracted to a common helper method.
IDE warned me that the property parsing method unnecessarily would use wrapper types. While the methods all returned wrappers the fields the values were assigned to were all primitive. So I switched those to primitive.

PAYARA-3490 Code level improvements for payara micro argument and property parsing 

---

appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/domain.xml

With the current settings, Micro will only create 2 threads and queue 20000 tasks before expanding the pool size any further. With these settings, Micro will create up to 200 threads _as required_ before queuing tasks.

PAYARA-3507 Set executor core pool size to 0 and queue to max on Micro

---

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/DeploymentFileValidator.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/RUNTIME_OPTION.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/UberJarCreator.java
appserver/extras/payara-micro/payara-micro-core/src/main/resources/commandoptions.properties

This PR allows to set the context path in two ways:
1. use `--contextroot`
```bash
java -jar payara-micro.jar --deploy myapp.war --contextroot mycontext
```
2. use `--deploy` with `:root` after the file name
```bash
java -jar payara-micro.jar --deploy myapp.war:mycontext
```
Both examples configure a effective root context of `/mycontext/`
When both are specified the root given with `--deploy` takes precedence. That means `--contextroot` works as a default or fallback for all applications where no root context was specified explicitly.
```bash
java -jar payara-micro.jar --deploy app1.war:foo --deploy app2.war --contextroot bar
```
This will deploy `app1` in `/foo/` and `app2` in `/bar/`.
Note: `--deploy app.war:/` is the same as `--deploy app.war` and even `--deploy app.war:` which all …

PAYARA-1165 allow setting of context root on Payara Micro deployments

---

appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/CircuitBreakerInterceptor.java

For some reason the CircuitBreaker interceptor was checking for overrides of the failOn parameter on the Retry annotation - presumably a copy-pasta bug as I can't immediately see why it should do this.

PAYARA-3512 Check for failOn override on correct annotation

---

appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/ConnectionPool.java
appserver/connectors/connectors-runtime/src/main/resources/com/sun/enterprise/resource/pool/LocalStrings.properties

This instead of throwing a NPE a short while later

PAYARA-3508 Throw informative error in ConnectionPool.getResouce if Interrupted

---

nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/MultimodeCommand.java

In order to prevent unwanted JLine logging in the asadmin multiline mode, a new system property can be used in the respective `asadmin` to disable it:
```
set JAVA=java
:run
%JAVA% -fish.payara.admin.command.jline.log.disable=true -jar "%~dp0..\glassfish\lib\client\appserver-cli.jar" %*
```

Implemented PAYARA-3505 Disable Option for JLine Logging in Asadmin Multimode

---

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/OpenApiService.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/admin/GetOpenApiConfigurationCommand.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/admin/OpenApiServiceConfiguration.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/admin/SetOpenApiConfigurationCommand.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/rest/app/OpenApiApplication.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/rest/app/provider/CorsHeadersFilter.java

This adds CORS headers support to the Microprofile OpenAPI module of Payara as suggested in #3787. There now is an additional configuration command to enable CORS headers. The default is 'false' to be backwards compatible. The CORS headers are added using a JAX-RS container response filter, whenever OpenAPI + CORS headers are enabled.

PAYARA-3537 Added CORS headers support to Microprofile OpenAPI module

---

appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/PayaraMicro.java
appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/PayaraMicroBoot.java
appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/PayaraMicroLauncher.java
appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/loader/Launcher.java
appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/loader/MainMethodRunner.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java

Using the programmatic API of `PayaraMicro` to bootstrap a micro instance has shown to have classloading isses when deploying a simple war with a JSP page. This is not the case when starting the server via the `PayaraMicroLauncher`. The problem encountered illustrated that two code paths to do the same thing is problematic. This lead to the idea to transition to one common code path of `PayaraMicroLauncher` (as this is the working one).  This should not mean that the programmatic bootrapping **API** (as provided by `PayaraMicro`)  should be abandoned, just that this API can be nothing more then a builder API to assemble the `String[]` arguments passed to the launcher. From there is is a common code path.
This "prove-of-concept" PR only changes enough to allow using the …

QA-192 POC to launch micro via cmd line args runner programmatically

---

appserver/admin/gf_template/pom.xml
appserver/admin/gf_template_web/pom.xml
appserver/admin/production_domain_template/pom.xml
appserver/admin/production_domain_template_web/pom.xml

There were implicit dependencies between domain templates and
nucleus-domain.
They made dependency:unpack plugin to fail, as the artifact could not be found in local repo

PAYARA-3172: Improve support for building in parallel

---

appserver/extras/embedded/all/pom.xml
appserver/extras/embedded/web/pom.xml

All of the dependencies of embedded modules must be optional, so they
don't pull other artifacts to the user's classpath.

PAYARA-3576: Don't leak dependencies of embedded

---

appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/PayaraMicroLauncher.java
appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/loader/Launcher.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java

Unfortunately git has tracked the changes in formatting that ended up coming into existence, the only physical changes I've made to the code are I the deployAll() method from line 1530 onwards

[PAYARA-3662] fixing glassfish-web.xml contextroot overwrite

---

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/SetCommand.java

When multiple instances share a configuration many of the `asadmin set instance-name.....` commands actually end up changing the shared config, which is applied to these instaces after they restart.
This PR puts up a warning when such configuration change is being made.
First three commits refactor SetCommand, fourth introduces the warning and the fifth fixes the detection logic.

PAYARA-3444: Warn when shared config is changed when referring to server node

---

appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/IiopFolbGmsClient.java

When deploying an app containing EJB Singletons to a standalone (non-clustered, no-deployment-group, no-instances) server the EJB-Container fails to start with a NullPointerException. This has been introduced to Payara 5.191 class IiopFolbGmsClient with commit `44b99bda4fae6ddcf7219b4c7c7abb75eb2de3be`.
Does anyone know about a workaround? We are trying to migrate to Payara 5.191.
```
UTIL6009:Unexpected Exception in createORB.
java.lang.NullPointerException
at org.glassfish.enterprise.iiop.impl.IiopFolbGmsClient.isTraditionalClusterActive(IiopFolbGmsClient.java:204)
at org.glassfish.enterprise.iiop.impl.IiopFolbGmsClient.isGMSAvailable(IiopFolbGmsClient.java:191)
at org.glassfish.enterprise.iiop.impl.GlassFishORBManager.setFOLBProperties(GlassFishORBManager.java:440)
at …
```

PAYARA-3702 Fixing NPE with standalone server deploying an application containing EJB singletons

---

appserver/admingui/ejb/src/main/resources/configuration/ejbContainerTimerService.jsf
appserver/admingui/ejb/src/main/resources/org/glassfish/ejb/admingui/Strings.properties
appserver/ejb/ejb-connector/src/main/java/org/glassfish/ejb/config/EjbTimerService.java
appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBTimerService.java
appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/startup/EjbDeployer.java

`asadmin deploy` no longer fails when application with timers are deployed to a deployment group.
EJB Timer Service offers option of persistence type None, where all timers are treated like non-persistent (as in Web Profile / EJB Lite).

Payara-3419: Support deploying timers to deployment group and non-persistent timer service

---

appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/FaultToleranceService.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/FaultToleranceServiceConfiguration.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/cdi/FaultToleranceCDIExtension.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/cdi/FaultToleranceCdiUtils.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/AsynchronousInterceptor.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/BulkheadInterceptor.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/CircuitBreakerInterceptor.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/RetryInterceptor.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/TimeoutInterceptor.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/fallback/FallbackPolicy.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/validators/BulkheadValidator.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/validators/CircuitBreakerValidator.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/validators/FallbackValidator.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/validators/RetryValidator.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/validators/TimeoutValidator.java

Before I start on 2.0 update I did a quick look through the module addressing warnings.
* Mostly this adds generic types where they where missing,
* removes now unnecessary casts
* removes unnecessary `else` clauses
* makes helper methods `static` where possible
There were a few cases where adding generic type information revealed type inconsistencies. I fixed and marked those with a comment.
Make sure to look at the diff with "ignoring whitespace changes" checked. This makes `else` block changes much less hard to review.

PAYARA-3468 MP FT Generic types

---

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ClassloaderResourceLocatorAdapter.java

when CommonModelRegistry is unavailable. Fixes e. g. CDI deployment in Payara Micro, where the definition of annotations are relevant.
The bug workaround mentioned refers to eclipse-ee4j/glassfish-hk2#446

PAYARA-3660: Supply Common Classloader as locator

---

nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/CLICommand.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/MultimodeCommand.java

This request is made to complement the changes made by #3757. In particular, the following 2 cases were not considered:
* Running any `asadmin` command outside of multimode
* Running multimode without any domains running.
The gist of the changes was to move the `checkToDisableJLineLogging` method to the `CLICommand` class first and then allow an static initializer to disable the JLine logging before any interaction with a JLine reader is made.

PAYARA-3708 Implemented fixes for JLine Logging

---

nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/LoginCommand.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/remote/RemoteCLICommand.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/remote/RemoteCommand.java
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/ChangeAdminPasswordCommand.java
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/CreateDomainCommand.java
nucleus/admin/util/pom.xml
nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/AsadminTrustManager.java
nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/LocalInstanceCommand.java
nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/SetupLocalDcom.java
nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/SetupSshKey.java
nucleus/common/common-util/pom.xml
nucleus/common/common-util/src/main/java/com/sun/enterprise/security/store/AsadminSecurityUtil.java

Much more aggressive use of JLine to hopefully catch any remaining issues around asadmin prompts exiting after a single input character.
Fixes #3833

PAYARA-3676 PAYARA-3665 Fix More Asadmin Prompt Issues

---

api/payara-api/src/main/java/fish/payara/security/openid/api/OpenIdState.java

Picked up from sonarcloud.io finding: https://sonarcloud.io/project/issues?id=org.glassfish.main%3Aglassfish-main-aggregator&open=AWVeB8Tq33vkQKHpI6h-&resolved=false&types=BUG
If allowing a String with the same value as the contained state property to qualify as an equal object is IMHO questionable. Should I correct it?

PAYARA-3738 OpenIdState: properly implement equals and hashcode method

---

appserver/packager/microprofile-package/pom.xml
appserver/payara-appserver-modules/jaxrs-client-tracing/pom.xml
appserver/payara-appserver-modules/jaxrs-client-tracing/src/main/java/fish/payara/requesttracing/jaxrs/client/JaxrsClientRequestTracingFilter.java
appserver/payara-appserver-modules/jaxrs-client-tracing/src/main/java/fish/payara/requesttracing/jaxrs/client/decorators/JaxrsClientBuilderDecorator.java
appserver/payara-appserver-modules/jaxrs-client-tracing/src/main/java/fish/payara/requesttracing/jaxrs/client/mprest/TracedMethodFilter.java
appserver/payara-appserver-modules/jaxrs-client-tracing/src/main/java/fish/payara/requesttracing/jaxrs/client/mprest/TracingClientListener.java
appserver/payara-appserver-modules/jaxrs-client-tracing/src/main/resources/META-INF/services/org.eclipse.microprofile.rest.client.spi.RestClientListener
appserver/pom.xml
nucleus/pom.xml

Two features were added to jaxrs-client-tracing, which is the glue code between opentracing and jersey rest client:
* Rest Client TCK tests that providers are eagerly initialized (before first request). For that, the client decorator needs to support such feature
* Tracing exclusions 
Creating a new module for these looked like a overkill, this way both the initialization and implementation of the features are within single module.
Merging and Jenkins test depend  on payara/Payara_PatchedProjects#243

Payara-3482, PAYARA-3742: MP Rest Client 1.2.1 and Jersey 2.29

---

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/OpenApiService.java

Documentation of REST API on the /openapi url had switched ports in http and https addresses. This commit fixes it.

PAYARA-3780 fix http and https ports in generated openapi

---

appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/jws/CombinedXPath.java
appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/jws/XPathToDeveloperProvidedContentRefs.java

See sonar bug https://sonarcloud.io/project/issues?id=org.glassfish.main%3Aglassfish-main-aggregator&open=AWJyK-mw1B6WA4TgV5lG&resolved=false&severities=MAJOR&types=BUG

avoid using non-threadsafe XPath as static property

---

appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/SecurityDeployer.java
appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/SecurityUtil.java
appserver/security/core-ee/src/main/java/com/sun/enterprise/security/web/integration/WebPrincipal.java
appserver/security/core-ee/src/main/java/com/sun/enterprise/security/web/integration/WebSecurityManagerFactory.java
appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java
appserver/security/webintegration/src/main/java/com/sun/web/security/realmadapter/JaspicRealm.java
appserver/web/web-core/src/main/java/org/apache/catalina/realm/RealmBase.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/BaseCertificateLoginModule.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/BasePasswordLoginModule.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/BaseRealm.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/PolicyLoader.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/SecurityContext.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/SecurityRoleMapperFactoryGen.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/WebAndEjbToJaasBridge.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/Realm.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/RealmsManager.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/certificate/CertificateRealm.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/common/AbstractSecurityContext.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/common/ClientSecurityContext.java

Addressed various Sonar reported warnings and use clearer variable names
and method structures at various places.

PAYARA-3785 Security code cleaning sweep 6

---

appserver/ejb/ejb-http-remoting/client/pom.xml
appserver/ejb/ejb-http-remoting/endpoint/src/main/java/fish/payara/ejb/invoke/InvokeEJBServlet.java

While testing #3925 I looked into several kinds of errors. Some where user errors due to limitations I wasn't aware of. This PR contains the improvements I made to understand the errors I dealt with.
* Added logging
* Error responses are less likely to mislead as different error causes are distinguished
* Separated concerns on method level into: unpack JSON, process request, create response + helpers
* For the interface we now don't simply use the first interface returned by `getClass().getInterfaces()` but make use of the EJB bean name in case it does contain the interface name
* For application name we do use the name given in the EJB bean name if it contains the application name (portable names) - otherwise we do fallback on the existing strategy to try each application and use the …

PAYARA-3729 EJB HTTP Endpoint improvments

---

appserver/ejb/ejb-http-remoting/client/pom.xml

Adds the missing runtime dependencies to the client and used the maven flatten plugin that will make the distributed artefact appear as if it is the top most  stand-alone module which makes it cleaner to use the client.
Tested this with both our jersey patched version `2.27.payara-p15`  and `2.28`. 
I attached a maven project with test application to the jira issue. This can be used to deploy (make a jar without the `Client` class) and verify (run `Client` class) the EJB over HTTP.

PAYARA-3729 Added missing runtime dependencies

---

appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/CLIBootstrap.java
appserver/appclient/client/acc/src/test/java/org/glassfish/appclient/client/CLIBootstrapTest.java
nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/PayaraExecutorService.java

Payara-3696 Don't init executor service when in ACC
Hint for reviewers; review per individual commit. The first commit is adding a [debug option](https://github.com/payara/Payara/pull/3936/commits/393e1934f041004faba4fd5e2942c0987981f5b2#diff-d1d42039c38aeeee99906d790f64d73aR904) to the ACC start, since it's otherwise quite difficult to debug the agent code for the ACC.
The second commit fixes the exception during startup of the ACC by not initialising the executor service on the client-side.

payara-3696-acc-executor-service

---

appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/FaultToleranceConfig.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/cdi/FaultToleranceExtension.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/policy/AsynchronousPolicy.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/service/BindableFaultToleranceConfig.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/service/FaultToleranceUtils.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/test/java/fish/payara/microprofile/faulttolerance/service/ConfigAlternativeAsynchronousAnnotationsTest.java

@arjantijms pointed out that projects might want to use other `@Asynchronous` annotations. As this is specific a fixed list of supported annotations seemed less feasible. Also some customers might not want to have such a feature enabled by default. Therefore I think the best solution is to allow to configure alternative annotation classes that should have the same effect as FT's `@Asynchronous`.
With this PR user can do so by defining the classes for the added key `MP_Fault_Tolerance_Alternative_Asynchronous_Annotations` as a comma separated list beside other FT configurations.
Implementation wise a bit of duplication cannot be avoided since the marking has to recognise the alternative annotations as well as the `FaultTolceranceConfig` which is not available at that stage.
I added tests …

PAYARA-3468 Added a config property to set alternative @Asynchronous annotations

---

appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/ResourceState.java
appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/ConnectionPool.java

When a connectionpool is closed it now logs an error rather than throwing an exception.
A multiexception is printed, showing both the current stack trace and the trace of where
the resource was previously closed.

PAYARA-3487 Race condition in ConnectionPool

---

.gitignore
appserver/ejb/ejb-http-remoting/client/pom.xml
appserver/ejb/ejb-http-remoting/client/src/main/java/fish/payara/ejb/http/client/EjbHttpProxyHandler.java
appserver/ejb/ejb-http-remoting/endpoint/src/main/java/fish/payara/ejb/invoke/InvokeEJBServlet.java
appserver/pom.xml

This builds upon #3931 (and the diff will get simpler once that one is merged) and payara/patched-src-yasson#3 in order to handle all of the test cases present in payara/payara-samples#9. Needs payara/Payara_PatchedProjects#244 to build properly.
512fbc7  handles class names especially for primitive types and null
7148154 adds dependency of client to same version of Yasson as in server, because all public Yasson versions at this time have issues with handling primitive types (and null)
177d55b maintains proper generic type of method parameters, so that JSON-B can properly deserialize parameters of types `List<Pojo>`, instead of creating `List<Map<String,Object>>` instead.

PAYARA-3755: Improve JSON-B support in ejb-http-client

---

nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/CollectionLeafResource.java
nucleus/admin/rest/rest-service/src/test/java/fish/payara/admin/rest/resources/CollectionLeafResourceTest.java

The problem was caused by '-XX:NewRatio=2' as previously it was assumed -X command-line options didn't require a value like in -D command-line options.

PAYARA-3805 Cannot edit, add, or delete JVM options from Admin Console

---

appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/loader/ExecutableArchiveLauncher.java

**Description**
The issue seems to be that we use the nested jar file without ever creating the `FileSystem` for it as one should according to https://docs.oracle.com/javase/7/docs/technotes/guides/io/fsp/zipfilesystemprovider.html and similar problems reported on SO. 
**Reviewer notes**
I can't say why this would work prior to Java 11. I am also unsure where best to create the `FileSystems.newFileSystem`. In the launcher where I put it it ensures that we do it just for the payara jar  and the method effectively isn't called multiple times but it does feel quite right place.
**Testing performed**
I first ran the reproducer 
```bash
java -jar payara-micro.jar --deploy <some.war> --nested
```
getting the error, added the fix and rebuild the jar and ran the reproducer again without getting …

PAYARA-3798 Create zip file system when processing nested archives

---

appserver/payara-appserver-modules/jaxrs-client-tracing/src/main/java/fish/payara/requesttracing/jaxrs/client/decorators/JaxrsClientBuilderDecorator.java

Test case in payara-samples#11
Root cause was, that open tracing decorator is present as ServiceLoader-visible service and intercepts creation of JAX-RS client, even if request tracing service (or any other service, as Payara is not running) is not available.

PAYARA-3521: Only trace JAX-RS Client requests when tracing services are present

---

appserver/payara-appserver-modules/jaxrs-client-tracing/src/main/java/fish/payara/requesttracing/jaxrs/client/decorators/JaxrsClientBuilderDecorator.java

Calling `getService` would start the service, even if the runtime is not ready yet

PAYARA-3521: Check for request tracing services without side effects

---

appserver/admingui/common/src/main/resources/security/realms/manageUsers.jsf
nucleus/security/core/src/main/java/com/sun/enterprise/security/cli/CreateFileUser.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/cli/DeleteFileUser.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/cli/UpdateFileUser.java

This is effectively reverting 0ef96b5168b4692a8e8a3816f5ba885ab0c1c31c

PAYARA-3703 Update-file-users command now works when there are instances with different configs

---

nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java

After HK2 upgrade, the `@Named` annotation prevents the config object to be
added into config automatically.
To test, backup a Payara4 domain, and restore it into Payara5. Before it failed because of this injection not being satisfied, now it will only compain about missing Grizzly ALPN classes (but will start).

PAYARA-3736: Let HazelcastConfigSpecificConfiguration register itself

---

nucleus/deployment/autodeploy/src/main/java/org/glassfish/deployment/autodeploy/AutoDeployDirectoryScanner.java

Fixes #2258
The autodeploy state folder tends to disappear in windows after running Payara Micro
for longer period of time.

PAYARA-3868: Check whether directory did not disappear in the meantime

---

nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/schemadoc/DocClassVisitor.java
nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/modularity/ConfigModularityUtils.java
nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/generator/ASMClassWriter.java
nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/utils/Util.java
nucleus/cluster/ssh/src/main/java/org/glassfish/cluster/ssh/sftp/SFTPClient.java
nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/core/AMXValidator.java
nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/core/Util.java
nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/config/AMXConfigImpl.java
nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/mbean/ToolsImpl.java
nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/ClassUtil.java
nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/jmx/JMXUtil.java
nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/jmx/MBeanInterfaceGenerator.java
nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/jmx/stringifier/MBeanConstructorInfoStringifier.java
nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/PropertiesDecoder.java
nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/glassfish/ASenvPropertyReader.java
nucleus/common/common-util/src/main/java/org/glassfish/admin/payload/PayloadImpl.java
nucleus/common/internal-api/src/main/java/org/glassfish/internal/embedded/ScatteredArchive.java
nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/GlassFishMain.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/AdminAdapter.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/DynamicInterceptor.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/JobManagerService.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/ListCommandsCommand.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/MonitoringReporter.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/V2DottedNameSupport.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/ContainerMapper.java
nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java
nucleus/deployment/autodeploy/src/main/java/org/glassfish/deployment/autodeploy/AutoDeployDirectoryScanner.java
nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/DeploymentUtils.java
nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/Descriptor.java
nucleus/flashlight/framework/src/main/java/org/glassfish/flashlight/impl/core/ProviderImplGenerator.java

This pull request contains fixes only for module _nucleus_.
Replacing `String.lastIndexOf("/")` with `String.lastIndexOf('/')` which can be more performant.
This fixes SonarQube violations of the rule: [String function use should be optimized for single characters](https://rules.sonarsource.com/java/RSPEC-3027)

SonarQube - Optimizing String.lastIndexOf() for single char in nucleus

---

nucleus/common/glassfish-api/src/main/java/org/glassfish/api/admin/AdminCommandLock.java

Complexity of locks deserves a PR focused on the `AdminCommandLock` entirely. 
~~There are two cases of not releasing the lock on all paths that were corrected. I annotate them in context.~~
@pdudits provided a PR-PR that removes the full suspension feature as it is unused whereby the inconsistent lock handling fixed originally no longer exists.

Cleanup sonar issues 7 - Locks not released

---

appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/micro/services/PayaraInstanceImpl.java

Added a synchronized double check in PayaraInstanceImpl to avoid race condition - tested through sheer brute forcing of Thread.sleep() and spamming of functionality and problem no longer appears to be present

[PAYARA-3860] - Added synchronization block double check to avoid race condition

---

appserver/appclient/client/acc-standalone/src/main/java/org/glassfish/appclient/client/acc/agent/ACCAgentClassLoader.java
appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/ACCClassLoader.java
appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/AppClientDeployerHelper.java
appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/StandaloneAppClientDeployerHelper.java
appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/BundleDescriptor.java
appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/micro/services/PayaraClusteredCDIEventImpl.java
appserver/security/core-ee/src/main/java/com/sun/enterprise/security/acl/RoleMapper.java
nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/SecureAdmin.java
nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/composite/CompositeUtil.java
nucleus/common/common-util/src/main/java/org/glassfish/admin/payload/PayloadFilesManager.java
nucleus/common/internal-api/src/main/java/org/glassfish/internal/deployment/GenericSniffer.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/CommonClassLoaderServiceImpl.java
nucleus/deployment/common/src/main/java/org/glassfish/deployment/versioning/VersioningService.java
nucleus/deployment/common/src/main/java/org/glassfish/deployment/versioning/VersioningUtils.java
nucleus/hk2/hk2-config/src/main/java/org/jvnet/hk2/config/ConfigModel.java
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/DomainDiscoveryService.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/JNDIConfigSource.java

This PR solves some cases of the SonarQube rule: ["Collections.EMPTY_LIST", "EMPTY_MAP", and "EMPTY_SET" should not be used](https://rules.sonarsource.com/java/RSPEC-1596).
I only replaced cases where a method returns with a typed Collection return type.

SonarQube - Replacing raw Collections EMPTY_... fields with generic methods empty…()

---

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ConcurrentRuntime.java
appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/util/RAWriterAdapter.java
appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/BundleDescriptor.java
appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/EjbIORConfigurationDescriptor.java
appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/BaseContainer.java
appserver/ejb/ejb-full-container/src/main/java/org/glassfish/ejb/persistent/timer/PersistentEJBTimerService.java
appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/ManagedConnectionFactoryImpl.java
appserver/persistence/cmp/generator-database/src/main/java/com/sun/jdo/spi/persistence/generator/database/MappingPolicy.java
appserver/persistence/cmp/support-sqlstore/src/main/java/com/sun/jdo/spi/persistence/support/sqlstore/ejb/DeploymentHelper.java
appserver/persistence/cmp/utility/src/main/java/com/sun/jdo/spi/persistence/utility/logging/LoggerFactoryJDK14.java
appserver/security/jacc.provider.inmemory/src/main/java/com/sun/enterprise/security/jacc/provider/SimplePolicyProvider.java
appserver/web/war-util/src/main/java/com/sun/enterprise/glassfish/web/WarHandler.java
appserver/web/web-core/src/main/java/org/apache/catalina/connector/Connector.java
nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/core/proxy/ProxyFactory.java
nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/mbean/RuntimeRootImpl.java
nucleus/resources/src/main/java/org/glassfish/resourcebase/resources/admin/cli/ResourceUtil.java

parseWrapper() avoids creating a boxed primitive, and this is more performant when just the primitive is desired.
This fixes SonarQube violations of the rule: [Parsing should be used to convert "Strings" to primitives](https://rules.sonarsource.com/java/RSPEC-2130)

SonarQube - Using Wrapper.parseWrapper() when converting String to primitive

---

appserver/persistence/cmp/ejb-mapping/src/main/java/com/sun/jdo/api/persistence/mapping/ejb/MappingFile.java
appserver/persistence/cmp/ejb-mapping/src/main/java/com/sun/jdo/api/persistence/mapping/ejb/MappingGenerator.java
appserver/persistence/cmp/enhancer/src/main/java/com/sun/jdo/api/persistence/enhancer/classfile/CodeEnv.java
appserver/persistence/cmp/enhancer/src/main/java/com/sun/jdo/api/persistence/enhancer/classfile/ConstantPool.java
appserver/persistence/cmp/enhancer/src/main/java/com/sun/jdo/api/persistence/enhancer/impl/MethodAnnotater.java
appserver/persistence/cmp/enhancer/src/main/java/com/sun/jdo/api/persistence/enhancer/util/Support.java
appserver/persistence/cmp/generator-database/src/main/java/com/sun/jdo/spi/persistence/generator/database/MappingPolicy.java
appserver/persistence/cmp/model/src/main/java/com/sun/jdo/api/persistence/model/jdo/impl/PersistenceClassElementImpl.java
appserver/persistence/cmp/model/src/main/java/com/sun/jdo/api/persistence/model/jdo/impl/PersistenceFieldElementImpl.java
appserver/persistence/cmp/model/src/main/java/com/sun/jdo/api/persistence/model/jdo/impl/RelationshipElementImpl.java
appserver/persistence/cmp/model/src/main/java/com/sun/jdo/api/persistence/model/mapping/impl/MappingClassElementImpl.java
appserver/persistence/cmp/model/src/main/java/com/sun/jdo/api/persistence/model/mapping/impl/MappingFieldElementImpl.java
appserver/persistence/cmp/support-ejb/src/main/java/com/sun/jdo/spi/persistence/support/ejb/ejbc/CMPProcessor.java
appserver/persistence/cmp/support-ejb/src/main/java/com/sun/jdo/spi/persistence/support/ejb/ejbqlc/ErrorMsg.java
appserver/persistence/cmp/support-sqlstore/src/main/java/com/sun/jdo/spi/persistence/support/sqlstore/SQLStateManager.java
appserver/persistence/cmp/support-sqlstore/src/main/java/com/sun/jdo/spi/persistence/support/sqlstore/SQLStoreManager.java
appserver/persistence/cmp/support-sqlstore/src/main/java/com/sun/jdo/spi/persistence/support/sqlstore/database/oracle/OracleSpecialDBOperation.java
appserver/persistence/cmp/support-sqlstore/src/main/java/com/sun/jdo/spi/persistence/support/sqlstore/impl/TransactionImpl.java
appserver/persistence/cmp/support-sqlstore/src/main/java/com/sun/jdo/spi/persistence/support/sqlstore/model/FieldDesc.java
appserver/persistence/cmp/support-sqlstore/src/main/java/com/sun/jdo/spi/persistence/support/sqlstore/model/LocalFieldDesc.java
appserver/persistence/cmp/support-sqlstore/src/main/java/com/sun/jdo/spi/persistence/support/sqlstore/query/jqlc/ErrorMsg.java
appserver/persistence/cmp/support-sqlstore/src/main/java/com/sun/jdo/spi/persistence/support/sqlstore/sql/ResultDesc.java
appserver/persistence/cmp/support-sqlstore/src/main/java/com/sun/jdo/spi/persistence/support/sqlstore/sql/generator/DBStatement.java
appserver/persistence/cmp/support-sqlstore/src/main/java/com/sun/jdo/spi/persistence/support/sqlstore/utility/StringScanner.java
appserver/persistence/cmp/utility/src/main/java/com/sun/jdo/spi/persistence/utility/SemaphoreImpl.java

This PR fixes multiple SonarQube violations of the rule: [Constructors should not be used to instantiate "String", "BigInteger", "BigDecimal" and primitive-wrapper classes](https://rules.sonarsource.com/java/RSPEC-2129)
The rule says: 
> Constructors for String, BigInteger, BigDecimal and the objects used to wrap primitives should never be used. Doing so is less clear and uses more memory than simply using the desired value in the case of strings, and using valueOf for everything else.

SonarQube - Instantiating wrappers - from 'new Wrapper(arg)' to 'Wrapper.valueOf(arg)'

---

appserver/ejb/ejb-http-remoting/client/pom.xml
appserver/pom.xml
nucleus/pom.xml

* groupId now matches release artifact
* developers are included
* outdated misleading scm section removed
Also relates to PAYARA-3646
Javadoc and sources are generated when built using maven's `release-profile`

PAYARA-3864: Make flattened pom match released pom

---

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java

PAYARA-3928 Fix NPE when notification via CDI eventbus comes in

---

appserver/security/core-ee/src/main/java/com/sun/enterprise/security/web/integration/WebPrincipal.java
appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/SecServerRequestInterceptor.java
appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java
nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/stringifier/X509CertificateStringifier.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/JaspicToJaasBridge.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/WebAndEjbToJaasBridge.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/login/ClientCertificateLoginModule.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/certificate/CertificateRealm.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/certificate/OIDs.java
nucleus/security/core/src/main/java/com/sun/enterprise/security/ssl/JarSigner.java

Should also stop requiring OIDs for most known fields (e.g. EMAILADDRESS)

PAYARA-3789 Unify DN Representation

---

nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigProviderResolverImpl.java

PAYARA-3950 Process all properties files

---

nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java
nucleus/common/common-util/src/main/java/com/sun/enterprise/util/JDK.java

Fix GFLauncher to use the correct JDK when determining the JVM options.
Using the javaExe already set for launching the domain, run it first with the -version parameter, and use the version parsed from its output (if available and matching) when setting the JVM options instead of the JVM currently running.
In case of non-fatal errors, the functionality falls back on the current JVM version (like before). On fatal errors a GFLauncherException will be thrown.
Fixes #4025

PAYARA-3911 Fix domain.xml java-home is not honored in version-specific jvm-options (#4025)

---

appserver/admin/gf_template/src/main/resources/config/domain.xml
appserver/admin/gf_template_web/src/main/resources/config/domain.xml
appserver/admin/production_domain_template/src/main/resources/config/domain.xml
appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml
appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/CLIBootstrap.java
appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/jws/ExtensionFileManager.java
appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/jws/JWSAdapterManager.java
appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/jws/JavaWebStartInfo.java
appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/util/DriverLoader.java
appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/io/DeploymentDescriptorFile.java
appserver/extras/embedded/all/src/main/resources/config/domain.xml
appserver/extras/embedded/web/src/main/resources/config/domain.xml
appserver/security/jacc.provider.file/src/main/java/com/sun/enterprise/security/provider/PolicyParser.java
appserver/web/web-core/src/main/java/org/apache/catalina/util/ExtensionValidator.java
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/V2ToV3ConfigUpgrade.java
nucleus/admin/template/src/main/resources/config/domain.xml
nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/AddLibraryCommand.java
nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/InstalledLibrariesResolver.java
nucleus/deployment/common/src/main/java/org/glassfish/loader/util/ASClassLoaderUtil.java

Reopened #4051 
> Was removed when we merged in the JDK 11 branch.
> 
> There are checks in place which should prevent it being used when running Payara Server with JDK11, as these properties are "hard" deprecated (JDK11 refuses to run if they're present).
> 
> This is essentially a revert of #3317 with a couple of modifications

PAYARA-3931 Bring back ext and endorsed dir for JDK 8

---

appserver/packager/external/javadb/pom.xml
nucleus/admin/template/src/main/resources/config/server.policy
nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/ASURLClassLoader.java
nucleus/security/core/src/main/resources/config/server.policy

The TCK barks about an exception, and about security permissions not being set. This should have been done when integrating the updated JavaDB/Derby as per its release notes: https://db.apache.org/derby/releases/release-10.12.1.1.html (Note for DERBY-6648)

SPEC-104 Address security permission exception preventing TCK running

---

appserver/deployment/dtds/src/main/resources/glassfish/lib/dtds/glassfish-ejb-jar_3_1-1.dtd

As reported in #4073, element `description` is declared more than one time in DTD file.
none
First element declaration is here:
https://github.com/payara/Payara/blob/d9d9bb5e4349c0fe63ffd2999c671855c0b23cf4/appserver/deployment/dtds/src/main/resources/glassfish/lib/dtds/glassfish-ejb-jar_3_1-1.dtd#L667-L672
After this change test referenced in #4073 complains only about `Element type "property" must not be declared more than once` .
[Travis CI](https://travis-ci.org/pzrep/Payara/jobs/553747506)

PAYARA-3980 Remove duplicated element 'description'

---

appserver/jdbc/jdbc-config/src/main/java/org/glassfish/jdbc/config/JdbcConnectionPool.java
appserver/jdbc/jdbc-config/src/main/java/org/glassfish/jdbc/config/validators/JdbcConnectionPoolValidator.java
appserver/jdbc/jdbc-runtime/src/main/java/org/glassfish/jdbc/deployer/DataSourceDefinitionDeployer.java

It is desired that variable types can be used in place of set values in JDBC connection pool settings (i.e. set maxPoolSize = ${MAX_POOL_SIZE_PROPERTY}) - this was previously not possible due to the validation process of JDBC connection pool properties (results in a NumberFormatException trying to parse an incorrect format string to an Integer) - the changes in this PR get around that

[PAYARA-3909] - Can't Use Any of the Variable Types in JDBC Connection Pool Settings

---

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBTimerServiceWrapper.java

Non-persistent timers are incorrectly wrapped and thus will generate NoSuchObjectLocalException
exceptions when invoking methods such as Timer.getInfo() on returned timers.
Fixes #3884

Ensure that the TimerWrapper references correct EJBTimerService

---

nucleus/pom.xml

- fixes PAYARA-3922:
- support for Stateless(name = "xxx")
- support for implicit Local interface

PAYARA-3922 Updated jersey.version to 2.29.payara-p4

---

api/payara-api/src/main/java/fish/payara/security/annotations/AzureAuthenticationDefinition.java
api/payara-api/src/main/java/fish/payara/security/annotations/GoogleAuthenticationDefinition.java
api/payara-api/src/main/java/fish/payara/security/annotations/OpenIdAuthenticationDefinition.java
api/payara-api/src/main/java/fish/payara/security/openid/api/OpenIdConstant.java
api/payara-api/src/main/java/fish/payara/security/openid/api/Scope.java
appserver/payara-appserver-modules/security-openid/pom.xml
appserver/payara-appserver-modules/security-openid/src/main/java/fish/payara/security/openid/OpenIdAuthenticationMechanism.java
appserver/payara-appserver-modules/security-openid/src/main/java/fish/payara/security/openid/OpenIdCredential.java
appserver/payara-appserver-modules/security-openid/src/main/java/fish/payara/security/openid/OpenIdIdentityStore.java
appserver/payara-appserver-modules/security-openid/src/main/java/fish/payara/security/openid/azure/AzureOpenIdAuthenticationMechanism.java
appserver/payara-appserver-modules/security-openid/src/main/java/fish/payara/security/openid/azure/AzureOpenIdExtension.java
appserver/payara-appserver-modules/security-openid/src/main/java/fish/payara/security/openid/controller/ConfigurationController.java
appserver/payara-appserver-modules/security-openid/src/main/java/fish/payara/security/openid/controller/RefreshedIdTokenClaimsSetVerifier.java
appserver/payara-appserver-modules/security-openid/src/main/java/fish/payara/security/openid/controller/TokenController.java
appserver/payara-appserver-modules/security-openid/src/main/java/fish/payara/security/openid/domain/AccessTokenImpl.java
appserver/payara-appserver-modules/security-openid/src/main/java/fish/payara/security/openid/domain/OpenIdConfiguration.java
appserver/payara-appserver-modules/security-openid/src/main/java/fish/payara/security/openid/google/GoogleOpenIdAuthenticationMechanism.java
appserver/payara-appserver-modules/security-openid/src/main/java/fish/payara/security/openid/google/GoogleOpenIdExtension.java

Added (optional) validity-check for Access Tokens and automated refresh of Access and Refresh tokens to OpenID connect authentication mechanism.
If auto-refresh is enabled but the Refresh Token is invalid (expired or user has logged out from OpenID connect provider), (s)he is logged out from the application (app-server) as well and redirected to the OpenID Connect provider. This allows the user to login again.

PAYARA-3825 Validity check and auto-refresh for OpenID connect tokens.

---

appserver/pom.xml

This allows MP Metrics 2.0 to work

PAYARA-4013 Increase Microprofile Fault Tolerance version to 2.0.1

---

appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/policy/FaultTolerancePolicy.java

Circuit Breaker should be considered success if exception thrown is not
marked as failOn

PAYARA-4026 Fault Tolerance 2.0.1 fix for failing TCK

---

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBTimerServiceWrapper.java

In some previous refactorings the invocation of the second constructor
disappeared, replacing with runtime instance check.
Fixes all 35 failures in `ejb/ee/timer`, and thus entire `ejb` suite

SPEC-259: Correctly identify if timer service relates to managed entity

---

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBTimerService.java
appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/StatefulSessionContainer.java
appserver/extras/embedded/shell/glassfish-embedded-static-shell/pom.xml
appserver/packager/requesttracing/pom.xml
appserver/payara-appserver-modules/jaxrs-client-tracing/pom.xml
appserver/payara-appserver-modules/rest-monitoring/rest-monitoring-service/src/main/java/fish/payara/appserver/monitoring/rest/service/adapter/RestMonitoringAdapter.java
nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/GenericAnnotationDetector.java
nucleus/payara-modules/opentracing-adapter/pom.xml
nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/PayaraExecutorService.java

TCK uses `glassfish-embedded-static-shell` to launch an embedded container, that is isolated from installed domain but inherits domain's settings. This module needed broader dependencies, which uncovered issues in request tracing related modules.
The startup of embedded container is quite special. First, it doesn't start with HTTP ports, which `RestMonitoringService` doesn't expect and needed to handle. Second the server starts up twice -- once to get security configuration to copy, and second time to run with this new configuration. `PayaraExecutorService` had to be adapted to cope with double startup.
Also added fix for cases where an EJB injects a `TimerService` but doesn't use it. Before we wouldn't initialize any service and injection would fail.
Also present in this bunch is fix for …

SPEC-245: Support embedded  EJBContainer

---

appserver/payara-appserver-modules/healthcheck-checker/src/main/java/fish/payara/healthcheck/mphealth/MicroProfileHealthChecker.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/service/FaultToleranceServiceImpl.java
appserver/payara-appserver-modules/microprofile/healthcheck/src/main/java/fish/payara/microprofile/healthcheck/HealthCheckService.java
appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/MetricsService.java
nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/AMXStartupService.java
nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/MonitoringDataUtil.java
nucleus/common/internal-api/osgi.bundle
nucleus/common/internal-api/src/main/java/fish/payara/monitoring/collect/MonitoringDataCollector.java
nucleus/common/internal-api/src/main/java/fish/payara/monitoring/collect/MonitoringDataSource.java
nucleus/common/internal-api/src/main/java/org/glassfish/internal/data/ApplicationRegistry.java
nucleus/common/internal-api/src/main/java/org/glassfish/internal/data/ContainerRegistry.java
nucleus/common/internal-api/src/main/java/org/glassfish/internal/data/ModuleInfo.java
nucleus/flashlight/framework/src/main/java/org/glassfish/flashlight/impl/provider/FlashlightProbeProviderFactory.java
nucleus/flashlight/framework/src/main/java/org/glassfish/flashlight/provider/FlashlightProbe.java
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/eventbus/EventBus.java
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/store/ClusteredStore.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HealthCheckService.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/BaseHealthCheck.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/BaseThresholdHealthCheck.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/CpuUsageHealthCheck.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/GarbageCollectorHealthCheck.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/HeapMemoryUsageHealthCheck.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/HoggingThreadsHealthCheck.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/MachineMemoryUsageHealthCheck.java
nucleus/payara-modules/healthcheck-cpool/src/main/java/fish/payara/nucleus/healthcheck/cpool/ConnectionPoolHealthCheck.java
nucleus/payara-modules/healthcheck-stuck/src/main/java/fish/payara/nucleus/healthcheck/stuck/StuckThreadsHealthCheck.java
nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/RequestTraceSpanStore.java
nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/RequestTracingService.java
nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/store/IterableThreadLocal.java

Introduces a new API to collect monitoring data consisting of two interface:
* `MonitoringDataSource` a `@Contract` implemented by `@Service` classes that have references to monitoring data in some form
* `MonitoringDataCollector` is passed to the sources so they can add any number of data points.
Data points are added in in a collection context that is implicit for the `MonitoringDataCollector` and can be extended using its `tag` method to create a new extended collection context.
The majority of actual code are the implementations of the `MonitoringDataSource`s where the different services add their information to the collection. 
More details can be found in the design document https://payara.atlassian.net/wiki/spaces/PAYAR/pages/870055939/Payara+Monitoring+Console+Design

PAYARA-3850 Data collection API and sources

---

nucleus/admin/server-mgmt/pom.xml
nucleus/admin/server-mgmt/src/main/java/fish/payara/admin/servermgmt/cli/PrintCertificateCommand.java
nucleus/admin/server-mgmt/src/test/java/fish/payara/admin/servermgmt/cli/PrintCertificateCommandTest.java
nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/SecureAdminClientManager.java
nucleus/pom.xml

- prints informations about a certificate saved in a file
- supported file types: der, pem, p12, jks, jceks
- if using additional provider, it's jar must be in payara5/glassfish/lib/asadmin/ directory (f.e. BC)

PAYARA 3792 asadmin print certificate

---

Jenkinsfile
Jenkinsfile-MicroProfile
Jenkinsfile-Nightly

Title.
We're not actively updating the jenkins branch frequently enough to justify it.

CI-38 Use master branch rather than jenkins

---

appserver/common/glassfish-naming/src/main/java/com/sun/enterprise/naming/impl/SerialContext.java
appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/deployment/annotation/handlers/ConnectionFactoryDefinitionHandler.java
appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/service/ConnectorConnectionPoolAdminServiceImpl.java
appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/deployer/AdministeredObjectDefinitionDeployer.java
appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/deployer/ConnectionFactoryDefinitionDeployer.java
appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/deployer/JMSConnectionFactoryDefinitionDeployer.java
appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/deployer/JMSDestinationDefinitionDeployer.java
appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/deployer/MailSessionDeployer.java
appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/EjbReferenceDescriptor.java
appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/node/DeploymentDescriptorNode.java
appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/node/PersistenceUnitNode.java
appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/node/SaxParserHandler.java
appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/annotation/handlers/AbstractEjbHandler.java
appserver/ejb/ejb-full-container/src/main/java/org/glassfish/ejb/mdb/deployment/annotation/handlers/MessageDrivenHandler.java
appserver/jdbc/jdbc-runtime/src/main/java/org/glassfish/jdbc/deployer/JdbcConnectionPoolDeployer.java
appserver/payara-appserver-modules/healthcheck-checker/src/main/java/fish/payara/healthcheck/mphealth/MicroProfileHealthChecker.java
appserver/payara-appserver-modules/security-oauth2/src/main/java/fish/payara/security/oauth2/OAuth2AuthenticationMechanism.java
appserver/payara-appserver-modules/security-openid/src/main/java/fish/payara/security/openid/OpenIdUtil.java
appserver/payara-appserver-modules/yubikey-authentication/src/main/java/fish/payara/security/identitystores/ConfigRetriever.java
appserver/resources/javamail/javamail-runtime/src/main/java/org/glassfish/resources/javamail/deployer/MailResourceDeployer.java
appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/annotation/handlers/WebServletHandler.java
nucleus/admin/config-api/src/main/java/org/glassfish/config/support/TranslatedConfigView.java
nucleus/core/bootstrap/src/main/java/fish/payara/boot/runtime/BootCommands.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/listener/CombinedJavaConfigSystemPropertyListener.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/SystemTasksImpl.java
nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/GFFileHandler.java
nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/SyslogHandler.java
nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/logviewer/backend/LogFilter.java
nucleus/core/logging/src/main/java/fish/payara/enterprise/server/logging/PayaraNotificationFileHandler.java
nucleus/deployment/common/src/main/java/fish/payara/deployment/util/GAVConvertor.java

Performing variable expansion in descriptors is not spec compliant, therefore it needs to be switched off for TCK tests. The system property is called `fish.payara.substitution.disable` and needs to be set to true in order to disable the feature.
Some of the expansions need to be done regardless of the setting, therefore the original method was split into two.

SPEC-282: Introduce JVM option to turn off variable support outside config

---

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/NonPersistentEJBTimerService.java
appserver/ejb/ejb-full-container/src/main/java/org/glassfish/ejb/persistent/timer/PersistentEJBTimerService.java
appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastTimerStore.java

Spec mandates throwing an exception on accessing nonpersistent
expired timers when accessed over public API.
Since NonPersistentEJBTimerService is base class for persistent
implementations, which pass their non-persistent functionality to it,
it needs internal method for verifying it would handle that timer.
This fixed ejb32/lite/timer tests, while not breaking ejb30/timer/tests at same time.

SPEC-267: Fail operations on expired nonpersistent timers

---

appserver/extras/embedded/shell/fixup.xml
appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/JCDIAroundConstructCallback.java
appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/JCDIServiceImpl.java

SPEC-321: Create instance at the and of AroundConstruct chain
Producing the instance eagerly triggered interceptor chain too early with incomplete context, and instance was created after interceptors completed, not when end of chain was reached (i. e. in the middle of interceptors processing).
Also clean up unused imports and methods.
And trying to fix embedded shell, which sometimes build with incorrect MANIFEST.MF, causing tests with embedded EjbContainer to fail.

 SPEC-321: Create instance at the and of AroundConstruct chain

---

nucleus/admin/server-mgmt/src/test/java/fish/payara/admin/servermgmt/cli/PrintCertificateCommandTest.java

Test was failing because on Windows it has a `/r` on the end

PAYARA-3792 Fix failing test on Windows

---

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/AbstractSingletonContainer.java

Due to serialisation of the objects put into the Hazelcast map, they need to be explicitly updated.

PAYARA-4028 PostConstruct values lost in Clustered Singleton EJBs

---

nucleus/pom.xml
pom.xml

- new parent relation introduced problems with it's configuration poisoning
all it's grandchildren - profiles source and javadoc did not work.
This is now fixed.
- source and javadoc profiles now produce same artifacts as before
- it is possible to combine profiles and build phases
- removed duplicated and redundant configuration parts.
- modules moved from profiles to the main pom.
- aggregator also changed the id

PAYARA-4043 Removed Jvnet parent

---

nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/CLICommand.java
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/MasterPasswordFileManager.java
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/LocalServerCommand.java
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/LocalStrings.properties
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/pe/PEFileLayout.java
nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/ChangeNodeMasterPasswordCommand.java
nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/CreateLocalInstanceCommand.java
nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/LocalInstanceCommand.java
nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/LocalStrings.properties

For anyone reviewing, a brief explanation of the behaviour change. The following functionality causes a problem:
1. Create a node
2. Create an instance on that node
3. Change master password for domain
4. Attempt to start instance (node still has the old master password saved, which doesn't unlock the keystore as the keystore has been synchronised from the DAS to the instance, so must be unlocked using the DAS master password)
5. Attempt to change master password for node (can't as the `change-master-password` command for the node will check the password against the keystore of each instance, which has now been updated with the DAS keystore)
This PR attempts to remedy this by causing the `change-master-password` command, when run against a node, to only change the saved password for the …

PAYARA-4031 Master Password Synchronisation Inconsistencies Across Nodes

---

nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/PayaraExecutorService.java

While there was a previous attempt to do this in place, it failed if the shutdown of the thread pool took any amount of time. And thus calling `stop()` and then `start()` in rapid succession would fail. This change attempts to eliminate this scenario

PAYARA-4065 Ensure that the threadpools are correctly initialized even when Embedded server is restarted

---

appserver/extras/payara-micro/payara-micro-distribution/build.xml

`jvm-options` in `domain.xml` is not used by Payara Micro and not applicable as Payara Micro is not executing in a separate JVM. 
```
<jvm-options>[9|]--add-opens=java.base/jdk.internal.loader=ALL-UNNAMED</jvm-options>
<jvm-options>[9|]--add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED</jvm-options>
<jvm-options>[9|]--add-exports=java.base/jdk.internal.ref=ALL-UNNAMED</jvm-options>
<jvm-options>[9|]--add-opens=java.base/java.lang=ALL-UNNAMED</jvm-options>
<jvm-options>[9|]--add-opens=java.base/java.nio=ALL-UNNAMED</jvm-options>
<jvm-options>[9|]--add-opens=java.base/sun.nio.ch=ALL-UNNAMED</jvm-options>
<jvm-options>[9|]--add-opens=java.management/sun.management=ALL-UNNAMED</jvm-options>
<jvm-options>[9|]--add-opens=java.base/sun.net.www.protocol.jrt=ALL-UNNAMED</jvm-options …
```

PAYARA-3884 Payara Micro adds JDK 11 warning when exploded application deployed

---

appserver/extras/payara-micro/payara-micro-distribution/pom.xml
appserver/payara-appserver-modules/cdi-auth-roles/pom.xml
appserver/payara-appserver-modules/cdi-auth-roles/src/main/java/fish/payara/appserver/cdi/auth/roles/CallerAccessExceptionAutoDiscoverable.java
appserver/payara-appserver-modules/cdi-auth-roles/src/main/java/fish/payara/appserver/cdi/auth/roles/CallerAccessExceptionMapper.java
appserver/payara-appserver-modules/cdi-auth-roles/src/main/java/fish/payara/appserver/cdi/auth/roles/RolesPermittedInterceptor.java
appserver/payara-appserver-modules/cdi-auth-roles/src/main/java/fish/payara/appserver/cdi/auth/roles/extension/RolesCDIExtension.java
appserver/payara-appserver-modules/cdi-auth-roles/src/main/resources/META-INF/services/org.glassfish.jersey.internal.spi.ForcedAutoDiscoverable

Implemented Parameterized dynamically resolved role names feature by using existing annotation @RolesPermitted: e.g 
```
@RolesPermitted("#{'CustomerCare_'.concat(customer.name)}")
public void updateCustomer(@Named("customer") Customer customer){
}
```
In the above example, `Named` annotation is used to define the parameter name in dynamic role expression. 
Multiple parameters can be used in el expression:  e.g 
```
@RolesPermitted("#{self.findRole(customer, product)}")
public void updateCustomer(@Named("customer") Customer customer, @Named("product") Product product){
}
```
If the parameter name not defined using `Named` annotation and method parameter count is 1 then default `param` name is used, e.g 
```
@RolesPermitted("#{'CustomerCare_'.concat(param.name)}")
public void …
```

PAYARA-3885 Implement Parameterized dynamically resolved role names

---

appserver/appclient/client/acc/pom.xml

This will make `javax.json.bind-api` to appear in the `Class-Path` manifest of `acc-standalone` (also known as `gf-client.jar`), and therefore makes classes available to application client runtime.
Makes Jakarta EE 8 signature tests pass for these packages.

PAYARA-4067: Put JSON-B api on AppClient classpath

---

appserver/ejb/ejb-full-container/src/main/java/org/glassfish/ejb/mdb/deployment/annotation/handlers/MessageDrivenHandler.java

Added support for singleton-bean-pool and bean-pool MDB deployment descriptor elements as ActivationConfigProperty values in MDB annotations

PAYARA-3964 Allow configuration of MDB bean pool size with ActivationConfigProperty

---

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java

Made Payara services transient in ContextSetupProvider
Tests fixed:
concurrency/spec/ContextService/contextPropagate_servlet/Client.java#testClassloaderInServlet
concurrency/spec/ContextService/contextPropagate_servlet/Client.java#testJNDIContextInServlet

PAYARA-4062 Fix failing test cases in concurrency TCK

---

nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/DeployCommand.java

When deployment fails, prepare returns null and action report contains details of the failure. Line 542 caused NullPointerException in such case, silently erasing that diagnostic information.

PAYARA-4079: Fix NPE in DeployCommand

---

appserver/deployment/dtds/src/main/resources/glassfish/lib/dtds/glassfish-ejb-jar_3_1-1.dtd

Closes #4073
With two ways of providing property, as elements and as attributes
the REQUIRED constraints for attributes have to be relaxed,
and name/value elements have to be optional as well.

PAYARA-4081 Merge 'property' elements

---

nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/CollectionLeafResource.java

JDK$Version caused JsonException when trying to serialize it

PAYARA-4092: Put Strings into optionMap

---

nucleus/core/bootstrap/src/main/java/fish/payara/boot/runtime/BootCommands.java
nucleus/core/bootstrap/src/test/java/fish/payara/boot/runtime/BootCommandsTest.java

For commands used in pre- or post-boot file allow the operand to be a single
char

PAYARA-4087 Allow the use of a single char as the operand for Micro

---

appserver/pom.xml
nucleus/pom.xml

The repositories do not contain anything relevant outside one unreleased version of fighterfish osgi-cdi, which already has more recent version on central.
Also for local patched_projects it's just better to place that as a mirror in settings.xml, no need to pollute pom.xml with that.

PAYARA-3819: Remove java.net repositories

---

appserver/monitoring-console/core/src/main/java/fish/payara/monitoring/store/InMemoryMonitoringDataRepository.java

PR fixes error reported in #4186 .

PAYARA-4104 Fixes NPE in monitoring console startup in case hazelcast is disabled

---

appserver/docker/src/main/java/fish/payara/docker/node/admin/ListNodesDockerCommand.java

Title.
Previously when you run the command you'd just get an error, due to the number of columns in the formatter not matching the number of actual parameters.

PAYARA-4115 Fix invalid number of columns message when running list-nodes-docker

---

Jenkinsfile
appserver/admingui/cluster/pom.xml
appserver/payara-appserver-modules/microprofile/config/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigProviderResolver
appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/ClusteredCDIEventBusImpl.java
appserver/web/weld-integration/src/main/java/org/glassfish/weld/DeploymentImpl.java
appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java
appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/ResourceInjectionServicesImpl.java
appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/SecurityServicesImpl.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigProviderResolverImpl.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigProviderResolverSync.java

This enable security context propagation to asynchronous event observers.
This is build on top of PAYARA-4078 to make CDI TCK pass.

PAYARA-4077: Implement Weld SecurityContext

---

appserver/admin/cli/pom.xml
appserver/appclient/client/acc/pom.xml
appserver/deployment/dol/pom.xml
appserver/extras/javaee/manifest-jar/pom.xml
appserver/packager/glassfish-common-web/pom.xml
appserver/payara-appserver-modules/microprofile/config/pom.xml
appserver/pom.xml
appserver/tests/payara-samples/samples/pom.xml
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/AdminMain.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/DirectoryClassLoader.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/remote/RemoteCLICommand.java
nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/remote/RemoteCommand.java
nucleus/distributions/payara-minimal/pom.xml
nucleus/hk2/config-generator/pom.xml
nucleus/packager/nucleus/pom.xml
nucleus/packager/nucleus/src/main/assembly/nucleus.xml
nucleus/pom.xml

- fixes classloader issue on JDK11 that prevented the JDK to run anything including local asadmin commands
- fixed also several other issues, see commits

PAYARA-4120 Upgraded javax.annotation to jakarta.annotation

---

appserver/payara-appserver-modules/cdi-auth-roles/src/main/java/fish/payara/appserver/cdi/auth/roles/RolesPermittedInterceptor.java

... from RolesPermittedInterceptor
Comparable to issue #4147

PAYARA-4141 fixes throwing NotAuthorizedException using the wrong constructor

---

nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/generator/ResourcesGeneratorBase.java

The generation is recursive and therefore we need to mark class as generated as soon as generation starts

PAYARA-4131: Fix race conditions in resource class generation

---

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/util/ResourceValidator.java

that are likely resolved by other definition

PAYARA-4140: Ignore unresolvable JNDI references

---

appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/admin/SetMetricsConfigurationCommand.java

Reopening due to small change that removed Dynamic config, thanks to @jGauravGupta for spotting it!

PAYARA-3501 Configuration changes in MP health and metrics in Admin console don't warn about restart needed

---

appserver/monitoring-console/webapp/pom.xml
appserver/monitoring-console/webapp/src/main/webapp/index.html
appserver/monitoring-console/webapp/src/main/webapp/mc-line-chart.js
appserver/monitoring-console/webapp/src/main/webapp/mc-main.js
appserver/monitoring-console/webapp/src/main/webapp/mc-model.js
appserver/monitoring-console/webapp/src/main/webapp/mc-view.js
appserver/monitoring-console/webapp/src/main/webapp/monitoring-console.css
appserver/monitoring-console/webapp/src/main/webapp/monitoring-console.js

Pure JS/HTML/CSS update for MC webapp that does:
* fixed grid layout algorithm
* made settings dynamic or responsive so they reflect the actual chart selected and its current values - for this the settings are now purely generated by JS
* organised and cleaned the JS code (main separation into model view and chart specific code all under the global object `MonitoringConsole`)
Remember that `monitoring-console.js` is merged from the other JS files and does not need to be reviewed.

PAYARA-4097 Fixed Grid Layout, Dynamic Settings 

---

appserver/ejb/ejb-http-remoting/client/pom.xml

Added to the pom for ejb-http-client to generate source and javadoc jars required for release automation as requested in PAYARA-4102

[PAYARA-4102] - Added source & javadoc generation

---

.github/PULL_REQUEST_TEMPLATE.md

Checkboxes for executed tests suites in PR description produce progress bars in PR overview and give false signal of PR being incomplete:
Instead of that the submitter should edit the list of test suites. Removed the checkboxes and modified instructions.
- Making test PR against my own repo
https://help.github.com/en/articles/about-task-lists

Remove checkboxes from PR template

---

appserver/appclient/client/acc/pom.xml

When using appclient feature both API and implementation of JSOB need to be on available on application client classpath. Adding the dependency into acc magically changes classpath of `gf-client.jar` -- the entry point to application client.
- Jakarta EE TCKs - jsonb in appclient suite.
Zulu JDK 1.8_222 on Ubuntu 18.04

PAYARA-4067: Add JSONB implementation into appclient runtime

---

appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/OpenTracingApplicationEventListener.java
nucleus/payara-modules/opentracing-adapter/src/main/java/fish/payara/opentracing/OpenTracingService.java

- invocationManager is null for default admin context
- there is no guarantee to have all needed services accessible
- application name can be null for context of server modules
Fixes TCK/CDI
- [x ] Quicklook

PAYARA-4164 Robust null-safe code

---

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/CommandRunnerImpl.java

Error occurs with some asadmin commands, i.e. _list-app-refs when targeting a deployment group, leading to messages like:
Target local-group is not a supported type. Command _list-app-refs supports these types of targets only: Default server, Stand alone instance, Cluster, Config, 
create-instance --node=localhost-domain1 local-instance
create-deployment-group local-group
add-instance-to-deployment-group --instance=local-instance --deploymentGroup=local-group
start-deployment-group local-group
Then ran test app (See Jira)(which uses cargo plugin) with `mvn integration-test`
- Quicklook
- Payara Private Tests
- Jakarta TCKs
- Mojarra
Zulu JDK 1.8_222 on Ubuntu 18.04 …

PAYARA-4144 Add support for deployment groups in commands that don't list targets

---

appserver/web/web-core/src/main/java/org/apache/catalina/connector/RequestFacade.java
appserver/web/web-core/src/main/java/org/apache/catalina/core/ApplicationDispatcher.java

Revert fix made for [PAYARA-917](https://github.com/payara/Payara/pull/1081) as it currently breaks the Servlet TCK.
Requires the following PR into the EE7 samples repo to be merged to pass Jenkins tests - as the fix was originally put it to fix a couple of tests in `jaspic/dispatching-jsf-cdi` around something that doesn't seem to be mentioned in any specs: https://github.com/payara/patched-src-javaee7-samples/pull/44
What should be the outcome of calling `getServletPath()` on a HttpServletRequest injected into a Bean, which is injected into a Servlet which has been forwarded to? The original servlet (before the forward), or the forwarded-to servlet (as is what you'd get if calling the method on the HttpServletRequest parameter of the forwarded to Servlet's `doGet` method)

PAYARA-4056 HttpServletRequest.getServletPath() not returning original path

---

appserver/common/glassfish-naming/src/main/java/com/sun/enterprise/naming/impl/GlassfishNamingManagerImpl.java
appserver/deployment/client/src/main/java/org/glassfish/deployapi/ProgressObjectImpl.java
appserver/deployment/client/src/main/java/org/glassfish/deployapi/SunDeploymentFactory.java
appserver/deployment/client/src/main/java/org/glassfish/deployapi/SunDeploymentManager.java
appserver/deployment/client/src/main/java/org/glassfish/deployapi/TargetImpl.java
appserver/deployment/client/src/main/java/org/glassfish/deployapi/TargetModuleIDImpl.java
appserver/deployment/client/src/main/java/org/glassfish/deployment/client/AbstractDeploymentFacility.java
appserver/deployment/client/src/main/java/org/glassfish/deployment/client/CommandXMLResultParser.java
appserver/deployment/client/src/main/java/org/glassfish/deployment/client/DFDeploymentProperties.java
appserver/deployment/client/src/main/java/org/glassfish/deployment/client/DFDeploymentStatus.java
appserver/deployment/client/src/main/java/org/glassfish/deployment/client/DeploymentFacility.java
appserver/deployment/client/src/main/java/org/glassfish/deployment/client/RemoteDeploymentFacility.java
appserver/deployment/client/src/main/java/org/glassfish/deployment/client/TargetOwner.java
appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/BaseContainer.java
appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/security/application/EJBSecurityManager.java
appserver/payara-appserver-modules/jmx-monitoring-service/src/main/java/fish/payara/jmx/monitoring/admin/notifier/DatadogMonitoringNotifierConfigurer.java
appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/OpenTracingRequestEventListener.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java
nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/DeploymentProperties.java

This is only additional PR to #4247 adding some cleanups I and my Eclipse made while working on issues with deployment-client and TCK. I didn't want to mix it with original PR.
Main differences:
1. deploy first deploys the module to the domain, then creates references (originally deployed to first target it received and created reference automatically; then developers added magic to avoid clashes on redeployments)
2. undeploy first removes all references, then undeploys the module (originally removed all references except last and for that called undeploy; existed error scenarios causing failures in undeploy phase)
3. ApplicationLifecycle.getArchiveHandler - fixed NPE
Look into individual commits for more details.
- Quicklook
- Jakarta TCKs (j2eetools)

PAYARA-4195 Cleanup related to deployment-client

---

nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/converters/AutomaticConverter.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/converters/CharacterConverter.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/converters/CommonSenseConverter.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigProviderResolverImpl.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/PayaraConfig.java

Obtaining an array over `Config.getOptionalValue(String, Class)` previously threw an exception
```
Caused by: java.lang.IllegalArgumentException: Unable to convert value to type java.lang.String[]
at fish.payara.nucleus.microprofile.config.spi.PayaraConfig.getConverter(PayaraConfig.java:243)
at fish.payara.nucleus.microprofile.config.spi.PayaraConfig.getOptionalValue(PayaraConfig.java:99)
```
First commit of the PR fixes this.
This use of API was not covered by TCK test, therefore tests have been added upstream in https://github.com/eclipse/microprofile-config/pull/452.
Running against these tests showed, that we miss converters for `char` and `Character` types, which is added by the second commit.
Last commit cleans up logic around selecting fitting converter for a …

PAYARA-4202 PAYARA-4206 Support for optional arrays and char type in config

---

appserver/extras/embedded/all/pom.xml
appserver/extras/embedded/build.xml
appserver/extras/embedded/web/pom.xml

Changing the artifacts also changed parameter passed to ant file, that build embedded distribution. That ant file was changing against three fixed bundle names. Those now match again, and refer to Payara rather than Glassfish.
```
mvn "-Dpayara.version=5.194-SNAPSHOT" -Ppayara-server-embedded "-Dpayara.arquillian.container.version=1.1" "-Dmaven.surefire.debug" "-Djersey.version=2.29.payara-p5" test            
[INFO] Results:                                                                               
[INFO]                                                                                        
[INFO] Tests run: 28, Failures: 0, Errors: 0, Skipped: 0  
```
Zulu 8, Windows 10, Maven 3.6.1

CI-93 PAYARA-3822: Update bundlename magic string for building embedded artifacts

---

nucleus/common/glassfish-api/src/main/java/org/glassfish/api/deployment/archive/ArchiveHandler.java
nucleus/common/internal-api/src/main/java/org/glassfish/internal/deployment/GenericHandler.java
nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/DeployCommand.java

This is a bug fix to an issue with application name of the deployed EAR adding unique numbers. This issue was caused by 1application.xml1 file being added by default, which causes the use of temporary application name when it can't find it.
None
* Deployed an EAR without an `application.xml` file and unique numbers were not added to the application name.
* Local build test
No required
To reproduce this issue just deploy an EAR without an `application.xml` file.

PAYARA-4124 Application name of deployed EAR shows unique numbers

---

appserver/extras/payara-micro/payara-micro-boot/pom.xml
appserver/extras/payara-micro/payara-micro-boot/src/main/resources-filtered/META-INF/maven/fish.payara.micro/payara-micro-boot/pom.properties

This is a bug fix / feature. A feature to workaround bug in Arquillian container.
arquillian-micro-managed container looks specifically for `pom.properties` of artifact `payara-micro-boot` in old groupId, and fails with unhelpful error message when it doesn't find one:
```
[ERROR] org.javaee7.cdi.vetoed.GreetingTest  Time elapsed: 74.975 s  <<< ERROR!
java.lang.NullPointerException: entry
```
- Java EE7 Samples in profile `payara-micro-managed`
Zulu 8, Maven 3.6.1, Windows 10

PAYARA-4150: Retain compatibility with Payara Micro ARQ container

---

appserver/admin/gf_template/src/main/resources/config/domain.xml
appserver/admin/gf_template_web/src/main/resources/config/domain.xml
appserver/admin/production_domain_template/src/main/resources/config/domain.xml
appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml
appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/UtilHandlers.java
appserver/admingui/common/src/main/resources/shared/sslAttrs.inc
appserver/admingui/core/src/main/resources/org/glassfish/admingui/core/Strings.properties
appserver/extras/embedded/all/src/main/resources/config/domain.xml
appserver/extras/embedded/web/src/main/resources/config/domain.xml
nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java
nucleus/admin/template/src/main/resources/config/domain.xml
nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/HttpConnectorAddress.java
nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/xml/MiniXmlParser.java
nucleus/common/common-util/src/main/java/com/sun/enterprise/util/JDK.java

This is a feature to add TLS 1.3 support when using Zulu JDK 1.8_222 and higher. This possible due to OpenJSEE project, OpenJSEE is a JSEE provider created by Azul to support TLS 1.3 on Java SE 8. You can enable TLS 1.3 support with the Java option `--XX:+UseOpenJSSE`. See [TLS 1.3 Support in Zulu
8 with OpenJSSE](https://docs.azul.com/openjsse/index.htm) for more information.
- Implemented vendor specific JVM options, since TLS 1.3 is only supported in Zulu JDK. E.g. `[Azul-1.8.0u222|1.8.0u500]-XX:+UseOpenJSSE` this option will on included if the JDK vendor is Azul.
- The checkbox to enable TLS 1.3 should not be visible if you are using Zulu JDK lower 1.8_222 or JDK 8 provided by other vendors.
- You will need to add the following Java Options to the asadmin script for TLS 1.3 to work on …

PAYARA-3997 Add TLS 1.3 support when using Zulu JDK 8

---

appserver/monitoring-console/core/src/main/java/fish/payara/monitoring/store/InMemoryMonitoringDataRepository.java
appserver/monitoring-console/core/src/test/java/fish/payara/monitoring/collect/DataSinkCollectorTest.java
appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/MetricsService.java

As tag values can be any valid UTF-8 character, and spaces are used frequently
i.e. in the name of the garbage collector PS Marksweep
Picked a control character to split tags as that is least likely to be split on
New unit test added (see PR)
Testing also performed by starting up a DAS and instance, no errors occur in logs
Zulu JDK 1.8_222 on Ubuntu 18.04 with Maven 3.6.0

PAYARA-4196 Replace spaces in tag values with an underscore

---

appserver/pom.xml
nucleus/pom.xml

Upgrading to latest Jersey release brings in support for Microprofile Rest Client 1.3 as well as various bugfixes.
https://github.com/payara/Payara_PatchedProjects/pull/281 Binary release
https://github.com/payara/Payara_PatchedProjects/pull/282 Binary release fix
- Payara Microprofile TCKs Runner (Rest Client 1.3)
Windows 10, Zulu 1.8_212, Maven 3.6.1

PAYARA-3828: Upgrade Jersey and MP Rest client version

---

appserver/payara-appserver-modules/microprofile/healthcheck/src/main/java/fish/payara/microprofile/healthcheck/HealthCheckService.java
appserver/payara-appserver-modules/microprofile/healthcheck/src/main/java/fish/payara/microprofile/healthcheck/HealthCheckType.java
appserver/payara-appserver-modules/microprofile/healthcheck/src/main/java/fish/payara/microprofile/healthcheck/servlet/HealthCheckServlet.java
appserver/payara-appserver-modules/microprofile/healthcheck/src/main/java/fish/payara/microprofile/healthcheck/servlet/HealthCheckServletContainerInitializer.java
appserver/pom.xml

MicroProfile Healthcheck 2.0 and 2.1 implementation:
- Message body of Health check response was modified, `outcome` and `state` replaced by `status` [Breaking Change]
- Introduction of Health checks for `@Liveness` and `@Readiness` on `/health/ready` and `/health/live` endpoints
- To enable the backward compatibility (`outcome` and `state` not replaced by `status` in JSON payload) of `/health` endpoint set the value of `mp.health.enable-backward-compatibility` MP config property to true.
- `/health` is deprecated and return combines Health checks data of `@Liveness` , `@Readiness` and `@Health`.
https://github.com/payara/MicroProfile-TCK-Runners/pull/59
Microprofile HealthCheck TCK v2.1
- Payara Microprofile TCKs Runner - HealthCheck TCK v1.0 where …

PAYARA-3829 MicroProfile Healthcheck 2.1 implementation

---

appserver/web/admin/src/main/java/org/glassfish/web/admin/monitor/RequestProbeProvider.java
nucleus/admin/monitor/src/main/java/org/glassfish/admin/monitor/StatsProviderRegistry.java
nucleus/flashlight/framework/src/main/java/org/glassfish/flashlight/impl/client/FlashlightProbeClientMediator.java
nucleus/flashlight/framework/src/main/java/org/glassfish/flashlight/impl/client/ProbeClientMethodHandleImpl.java
nucleus/flashlight/framework/src/main/java/org/glassfish/flashlight/impl/client/ProbeProviderClassFileTransformer.java
nucleus/flashlight/framework/src/main/java/org/glassfish/flashlight/provider/ProbeRegistry.java

When un-deploying and re-deploying an application the web and HTTP statistics would no longer update.
The reason for updates no longer reaching the statistics counters was that the connection done via class instrumentation was cut when un-deploying an app. This occurred because un-deploying an application does disable statistics providers specifically responsible for the application which wrongly triggered a removal of the class instrumentation for the probe provider class connecting the events to the statistics counters. So instead of just disconnecting the application specific statistics all statistics based on a particular class were disabled. Since the overall statistics for HTTP and web use the same class as the application specific ones this also disabled the overall statistics. …

PAYARA-4121 Fixed Updating of Flashlight Class Instrumentation

---

appserver/admin/gf_template/src/main/resources/config/domain.xml
appserver/admin/gf_template/src/main/resources/stringsubs.xml
appserver/admin/gf_template_web/src/main/resources/config/domain.xml
appserver/admin/gf_template_web/src/main/resources/stringsubs.xml
appserver/admin/production_domain_template/src/main/resources/config/domain.xml
appserver/admin/production_domain_template/src/main/resources/stringsubs.xml
appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml
appserver/admin/production_domain_template_web/src/main/resources/stringsubs.xml
appserver/admingui/reference-manual/src/main/help/en/help/reference/create-domain.html
nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/util/PortConstants.java
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/DomainConfig.java
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/CreateDomainCommand.java
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/domain/DomainBuilder.java
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/domain/DomainPortValidator.java
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/domain/SubstitutableTokens.java
nucleus/admin/server-mgmt/src/main/manpages/com/sun/enterprise/admin/servermgmt/cli/create-domain.1
nucleus/admin/template/src/main/resources/stringsubs.xml

This is a feature to allow `create-domain` command to configure the Hazelcast Configuration. This makes it possible to configure the Hazelcast Configuration before starting the domain.
**Following new command options have been added to the `create-domain` command:**
* **`--hazelcastdasport`** The port to run Hazelcast on for the DAS. If this port is busy, the port specified will be incremented until a valid port is found. The `--hazelcastdasport` option cannot be used with the --portbase option. The default value is 4900. The `--hazelcastdasport` option overrides the `hazelcast.das.port` property of the `--domainproperties` option.
* **`--hazelcaststartport`** The port the other Payara Server instances use to run Hazelcast on. If this port is busy, the port specified will be incremented …

PAYARA-4158 Allow create-domain command to configure the Hazelcast Configuration 

---

nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigProviderResolverImpl.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigProviderResolverSync.java

`ConfigProviderResolverImpl` might provide instance to MP Config SPI at wrong moment, where its instance gets yet overwritten by instance of `ConfigProviderResolveSync` instance. This race condition manifests itself as `StackOverflowError` then, because Sync relied on Impl to set the instance.
This solution only masks a larger issue where various server internals cooperate with MP Config API to obtain configuration, however config impl is a service, that only works after proper initialization.
It would be best to use HK2 injection instead, but majority of the points of use are not HK2 services.
- Java EE7 Samples in `payara-micro-managed` profile, that manifested this behavior the most in nightly
Windows 10, Java 1.8.0_221, Maven 3.6.2

PAYARA-4130: Workaround hidden config service dependencies

---

nucleus/pom.xml

ASM 7.2 supports JDKs up to JDK 14
Build+start
Zulu JDK 1.8_222 on Ubuntu 19.04 with Maven 3.6.0
Zulu JDK 11.0.5 on Ubuntu 19.04 with Maven 3.6.0

PAYARA-4243 Upgrade ASM to version 7.2

---

appserver/admin/gf_template/src/main/resources/config/domain.xml
appserver/admin/gf_template_web/src/main/resources/config/domain.xml
appserver/admin/production_domain_template/src/main/resources/config/domain.xml
appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml
appserver/extras/payara-micro/payara-micro-distribution/build.xml

Adds add
Start Payara Server, Payara Micro and Payara Web with the `--illegal-access=warn` command line option and check for any messages about illegal reflective access.
Zulu JDK 11.0.5 on Ubuntu 19.04 with Maven 3.6.0

PAYARA-3803 Add more add-opens for JDK11 modules

---

appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/jmx/MBeanGuageImpl.java

Fixes #4230 
CPU Load was being displayed as 0 as gauge was used a long which would round off the actual cpu usage which occurs in the range [0,1]
Started domain and admin console. Went to localhost:4848/metrics and checked system_cpu_load gauge, with this PR is is non-zero.
Zulu JDK 1.8_222 on Ubuntu 19.04 with Maven 3.6.0

PAYARA-4147 MP Metrics now use double for MBean metrics instead of long

---

nucleus/security/ssl-impl/src/main/java/com/sun/enterprise/security/ssl/impl/SecuritySupportImpl.java

This is a feature request. 
Currently expired certificates are logged with SEVERE Level which confuses users. Server starts fine and users currently see this expired certificates logging as cause of some other problem .
Verified the changed log message in server.log

PAYARA-4248 Log Expired certificates from cacerts.jks with level warning

---

nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/GlassFishImpl.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/AppServerStartup.java
nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/PayaraExecutorService.java

Since cca summer 2017 server would hang when startup failure occurred, thread dump would show one or two threads hanging in 
```
java.lang.Thread.State: TIMED_WAITING
at java.lang.Thread.sleep(Thread.java:-1)
at com.sun.enterprise.v3.admin.StopServer.doExecute(StopServer.java:74)
at com.sun.enterprise.v3.admin.StopDomainCommand.execute(StopDomainCommand.java:96)
at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:558)
at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:554)
at java.security.AccessController.doPrivileged(AccessController.java:-1)
at javax.security.auth.Subject.doAs(Subject.java:360)
at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:553)
at …
```

PAYARA-4116: Properly shutdown server on startup failure

---

appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/admin/cli/ListTimers.java

- Quicklook
Ubuntu LTS 18.04, Java 1.8.0_222
This is a fix for an error 500 that occurs when selecting to list timers on instances within a deployment group on the DAS. This error is the result of a null array being returned when no EJB timers are present so I've simply filled the array with 0s.
Whilst working on this, I've discovered another potential issue which will require looking into, however it needs further research and will likely be resolved in a separate issue/PR

[PAYARA-4160] - Error 500 when listing EJB Timer Count on DAS

---

appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/MetricsService.java
appserver/payara-appserver-modules/microprofile/metrics/src/test/java/fish/payara/microprofile/metrics/MetricsServiceTest.java

When undeploying an application that has capital letters in its name i.e. SNAPSHOT then it fails to be deregistered when it is removed.
New unit test added, see PR
Deployed the test application for PAYARA-4174, went to localhost:8080/metrics then undeployed the application and went to localhost:8080/metrics again. Before PR error thrown, afterwards no error.
"Zulu JDK 1.8_232 on Ubuntu 19.10 with Maven 3.6.0"

PAYARA-4256 MP Metrics are now always unregiestred after application undeployment

---

appserver/web/weld-integration/src/main/java/org/glassfish/weld/ACLSingletonProvider.java
appserver/web/weld-integration/src/main/java/org/glassfish/weld/util/Util.java

This is a bug fix .
The /metrics endpoint is loaded as default-web-module which is a different context to the
user's application. In Web profile previously TCCLSingleton is used to hold the classloader,
which does not allow cross-application sharing. In Full profile, and now Web, ACLSingleton
is used which while is has separate classloader for each application does allow
cross-application communication and sharing of metrics.
Used reproducer in Jira, throws an error in Payara Micro and Payara Web before this PR when going to /metrics and not afterwards.
- Payara Private Tests
Zulu JDK 1.8_232 on Ubuntu 19.10 with Maven 3.6.0"-->

PAYARA-4174 MP Metrics in web profile do not throw an exception on custom metrics

---

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/MonitoringHandlers.java
appserver/admingui/common/src/main/resources/monitor/monitoringPage.jsf
appserver/admingui/common/src/main/resources/org/glassfish/common/admingui/Strings.properties
nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/Domain.java
nucleus/admin/config-api/src/main/java/org/glassfish/config/support/CommandTarget.java
nucleus/admin/monitor/src/main/java/fish/payara/admin/monitor/cli/Constants.java
nucleus/admin/monitor/src/main/java/fish/payara/admin/monitor/cli/GetMonitoringServiceConfiguration.java
nucleus/admin/monitor/src/main/java/fish/payara/admin/monitor/cli/SetMonitoringLevel.java
nucleus/admin/monitor/src/main/java/fish/payara/admin/monitor/cli/SetMonitoringServiceConfiguration.java
nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/CreateLocalInstanceCommand.java
nucleus/common/amx-core/src/main/java/fish/payara/admin/amx/AMXBootService.java
nucleus/common/amx-core/src/main/java/fish/payara/admin/amx/cli/SetAmxEnabled.java

This is a bug fix to an issue where monitoring data of an Instance was not visible if it was in a Deployment Group.
Although the issue was identified because of the monitoring issue, the underlying issue was caused by a command not being replicated to the instances in a deployment group. 
Created a deployment group with an instance, enabled the monitoring service and checked if the monitoring data is available. 
No required

PAYARA-4171 Monitoring data of an Instance is not visible if it is in a Deployment Group

---

appserver/distributions/payara/pom.xml
appserver/monitoring-console/core/pom.xml
appserver/monitoring-console/core/src/main/java/fish/payara/monitoring/admin/SetMonitoringConsoleConfigurationCommand.java
appserver/packager/monitoring-console/pom.xml

Package MC webapp in Payara distribution so it can be deployed through some sort of API.
Using maven `unpack` unpacks the webapp war to `glassfish/lib/install/applications` (same folder as admingui). A new asadmin-command uses auto-deploy and undeploy to deploy the unpacked app from that folder when MC is enabled or disabled.
Note that this is a minimal solution that intends to be extended with a GUI in the admingui that uses the provided commands to enable/disable MC.
Build and install the server. Enter asadmin command line:
```
asadmin> start-domain
asadmin> set-monitoring-console-configuration --enabled=true
```
MC should now run on `localhost:8080/monitoring-console/`
```
asadmin> set-monitoring-console-configuration --enabled=false
```
MC should no longer run on localhost.

PAYARA-4245 Packaging MC with Payara (Server)

---

appserver/monitoring-console/core/src/main/java/fish/payara/monitoring/store/InMemoryMonitoringDataRepository.java

The goal of this change is to prevent potential log spamming caused by the collection of metrics every second in case exception is thrown by a source. This is achieved in two ways:
* only log failing sources once (until they not fail any more)
* only collect metrics when monitoring service is enabled
As discussed shortly during standup the solution to enable/disable via the existing setting was chosen to keep things simple both for the user and development.
The periodical collection task is submitted to the scheduler when monitoring is enabled initially or when a change event for the property changes is state to enabled. The task is cancelled should the state change to disabled.
With deployed MC the configuration _Monitoring_ => _Monitoring Service: Enabled_ is checked. The change can be …

PAYARA-4250 Prevent log spamming

---

nucleus/common/common-util/src/main/java/com/sun/appserv/server/util/Version.java

Invoking `asadmin version` or reaching version endpoint returned only major version, when product was in snapshot:
`Version = Payara Server  5 #badassfish (build ${build.number})`
After the change it also reports
`Version = Payara Server  5.194 #badassfish (build ${build.number})`
The change was done during exploring posibilities of server management from inside Arquillian tests, with one of the goals of recognizing server version without additional property.
Version parsing in `Version` failed on snapshot versions, causing only major number to be reported, which is quite useless.
`asadmin version` and on build result
`curl -H 'Requested-By: me' -H "Accept: application/json" http://localhost:4848/management/domain/version`
```
{"message":"Payara Server  5.194 …
```

Return minor version for snapshot versions of servers

---

appserver/packager/monitoring-console/pom.xml

This is a bug fix/build fix. 
Adds the dependency on MC webapp so module build order is changed so that the webapp module is available when the packager `unpack` during `generate sources` phase finds the artefact.
Deleted the snapshot(s) from the local repository at `fish/payara/server/monitoring-console/monitoring-console-webapp` and run a clean install. With a successful build check that 
* the webapp module was build before the package (order in list of build modules) (can also use `mvn dependency:tree` to check)
* the webapp war is **not** in the `glassfish/modules` folder of the `payara` distribution 
* the webapp was unpacked to `glassfish/lib/install/applications/__monitoringconsole`
None specific.

PAYARA-4263 Added missing dependency on MC webapp

---

appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/jdkcheck
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/jdkcheck.bat
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/schemagen
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/schemagen.bat
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wscompile
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wscompile.bat
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsdeploy
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsdeploy.bat
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsgen
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsgen.bat
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsimport
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsimport.bat
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/xjc
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/xjc.bat

This allows running of the JAX-WS commands i.e. `wsimport`, `wscompile` on both JDKs 8 and 11, since the endorsed has been removed in JDK9+ and required classes were removed from Java SE in JDK11.
Ran all changed commands on JDKs 8 and 11 on Windows and Linux
Zulu JDK 1.8_222 on Ubuntu 19.04
Zulu JDK 11.0.5 on Ubuntu 19.04
IBM JDK 1.8_221 on Ubuntu 19.04
Zulu JDK 1.8_181 on Windows 10
Zulu JDK 11.0.3 on Windows 10

PAYARA-4218 Add JDK11 support to JAX-WS commands

---

appserver/admin/cli/pom.xml

Earlier commit fixed instability of asadmin CLI classpath by having it generated by Maven Archiver. However `jline-jna` and `jna` are not Payara modules, rather runtime dependencies.
Thankfully, manual entry can be combined with automated classpath, and the new path looks like
```
Class-Path: jna.jar jline-terminal-jna.jar ../../modules/admin-cli.jar
../../modules/hk2.jar ../../modules/hk2-utils.jar ../../modules/jaka
rta.annotation-api.jar ../../modules/jakarta.inject.jar ../../modules
/hk2-api.jar ../../modules/aopalliance-repackaged.jar ../../modules/h
k2-core.jar ../../modules/hk2-locator.jar ../../modules/javassist.jar
../../modules/hk2-runlevel.jar ../../modules/class-model.jar ../../m
odules/asm.jar ../../modules/asm-analysis.jar ../../modules/asm-commo
ns.jar …
```

PAYARA-4188: Put jline-jna back on asadmin cli classpath

---

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBContainerTransactionManager.java

- print warning about timeout also in a case when there is more serious error if the tx timeouted too,
- when some bean tried to use timeouted transacion, a non-checked exception
was thrown and it shadowed the original cause of rollback - the warning
wasn't printed then. Now it is.
TBD (there will be done)
See future push in #4263  with integrated test case.
Manual using the JIRA example.
None of following yet:
- Quicklook
- Payara Private Tests
- Jakarta TCKs
- Mojarra
The solution was designed after refactoring done in another PR, because present logging is not much useful and is rather confusing. But refactoring might introduce new errors and will need to pass at least TCK/EJB and …

PAYARA-4197 Always print rollback+timeout warning

---

appserver/connectors/work-management/src/main/java/com/sun/enterprise/connectors/work/WorkCoordinator.java
appserver/ejb/ejb-container/src/main/java/com/sun/ejb/EjbInvocation.java
appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/AbstractSessionContextImpl.java
appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/AbstractSingletonContainer.java
appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/BaseContainer.java
appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBContainerTransactionManager.java
appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBLocalHomeInvocationHandler.java
appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EjbThreadPoolExecutor.java
appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/SessionContextImpl.java
appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/SingletonContextImpl.java
appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/StatefulSessionContainer.java
appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/StatelessSessionContainer.java
appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/WebServiceInvocationHandler.java
appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/embedded/EJBContainerImpl.java
appserver/ejb/ejb-full-container/src/main/java/org/glassfish/ejb/mdb/MessageBeanContainer.java
appserver/ejb/ejb-internal-api/src/main/java/org/glassfish/ejb/api/EJBInvocation.java
appserver/persistence/entitybean-container/src/main/java/org/glassfish/persistence/ejb/entitybean/container/EntityContainer.java
appserver/transaction/jta/src/main/java/com/sun/enterprise/transaction/JavaEETransactionImpl.java
appserver/transaction/jta/src/main/java/com/sun/enterprise/transaction/JavaEETransactionManagerSimplified.java
appserver/transaction/jta/src/main/java/com/sun/enterprise/transaction/TransactionManagerHelper.java
appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionalInterceptorBase.java

- sorted imports, removed unused
- code formatting
- preferred shorter block first
- preferred positive if without negation
- preferred fast return
- collisions of these rules resolved appropriately
- removed 10 years old TODOs
- using generics where it is clear
- trivial optimizations
- declaring variables
- preferred final instead of changing the default value
- removed redundant keywords (public method in interface, ie)
- removed redundant class typing
- using addSuppressed/cause rather than masking exceptions
- improved logging
- log entry to important method at least as finest
- removed some duplicit logs
This is an enhancement for better readibility and also to provide better informations in logs.
EJB timeout warnings are now printed immediately when the transaction is set to the …

PAYARA-4197 Minor but large cleanup in ejb-container and related things

---

appserver/web/web-core/src/main/java/org/apache/catalina/connector/MappingImpl.java
appserver/web/web-core/src/main/java/org/apache/catalina/core/ApplicationDispatcher.java
appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java

Cherrypick of a single commit fixing the PAYARA-4056 issue in master (for master under PAYARA-4255)
- Jakarta TCKs
```
real    54m12,844s
user    27m49,124s
sys     2m8,883s
Waiting for the domain to stop ..
Command stop-domain executed successfully.
Not passed: 0/846 /home/dmatej/work/repo/git/jakartaeetck-runner/cts_home/jakartaeetck-report/servlet_api/text/summary.txt
Writing stage file for servlet/api  into stage_servlet_api
```

PAYARA-4255 Fix servletcontext and mapping errors

---

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/RestUtil.java
appserver/admingui/common/src/main/resources/configuration/sysInstanceValues.jsf
nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/custom/SystemPropertiesCliResource.java

Overriding system properties in `{Instance Name}-config -> System Properties -> Instance Values` failed stating "An error has occured"
*On a new Instance running/stopped e.g Elegant-Archerfish*
- Go to `Instances -> Elegant-Archerfish -> Properties -> System Properties` changing an `Override value` should change `Current Value`
- Go to `Configurations -> Elegant-Archerfish-config -> System Properties -> Instance Values` changing the `Override Value` should save successfully.
**Note: `Default Value` will remain the same unless changed in the configuration**
Check the override value has been applied by going back to `Instances -> Elegant-Archerfish -> Properties -> System Properties` you should see the new override value. The instance may need to be restarted.
Build tests …

PAYARA-4219 Problem when trying to override System Properties of an instance

---

nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/DirWatcher.java
nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/WatchProcessor.java
nucleus/common/common-util/src/test/java/com/sun/enterprise/loader/DirWatcherTest.java

Log messages `Watch service attempted to get checker for untracked item...` that appeared during deployment in recent build hinted, that the lifecycle around directory watchers (deployment optimizations from #4279) was not correct:
Same path can be registered multiple times. Therefore we cannot remove a watcher while there is still a classloader interested in the directory -- this is what caused the message to be logged.
We now keep track of subscription count and remove only if there are no subscribers left.
On some occasions, multiple levels of parent directories might be non-existing, therefore we need to register parent watchers until we find an existing directory.
#4279 - Original implementation
Executing the test suite and watching for references to `watch`.
- …

PAYARA-4265: Fix cleanup issues in DirWatcher

---

appserver/tests/payara-samples/pom.xml
appserver/tests/payara-samples/samples/pom.xml

Updates the arquillian containers used in Payara Samples tests.
Maintaining support for Payara 4 and Payara 5 within the same arquillian container version was proving too difficult, so we've split them out.
Relies upon the release of the following PRs: https://github.com/payara/ecosystem-arquillian-connectors/pull/30 https://github.com/payara/ecosystem-arquillian-connectors/pull/29
If you wish to test, check out those two PRs and build them.

TEST-388 Update Arquillian Containers

---

Jenkinsfile

Fixed build. rm returns non-zero error code if there is nothing to delete.
Example:
```
dmatej@dmatej-G5-5587:/repo/git/Payara$ rm *.zip && echo "this works"
rm: cannot remove '*.zip': No such file or directory
dmatej@dmatej-G5-5587:/repo/git/Payara$ rm -f *.zip && echo "this works"
this works
```

CI-108 Fixed error when there is no file to remove (Jenkinsfile)

---

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EjbContainerUtilImpl.java
appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/startup/EjbDeployer.java

This is a bugfix / feature (bit of both). 
Method annotated with `@Schedule` weren't executed when application was deployed to a deployment group. It was quite correct thing to do, because Deployment Groups are loose groupings of instances that do not necessarily share configuration, inclusive Timer Service configuration.
It is task of DAS to register timers defined by annotations and xml descriptor, and in general it couldn't know which timer service defined in domain to use.
However, from now on we will assume, that user is doing the right thing and his instances' timer service configurations are compatible. E. g. point to same external database, or use DataGrid timer service. At this point, `server-config` needs to have same timer service configuration as well (separate issue).
DAS …

PAYARA-4215: Enable persistent timers in Deployment Group targets

---

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ApplicationProcessor.java

eclipse/microprofile-open-api#386
Used test app, ensured correct schema was generated
Zulu JDK 1.8_232 on Ubuntu 19.10 with Maven 3.6.0
Before fix for a test enum of:
```
@Schema(enumeration = {"KIND1", "KIND2"}, type = SchemaType.STRING)
public enum Kind {
KIND1,KIND2
}
```
was displayed as
Kind:
type: string
allOf:
- $ref: '#/components/schemas/Enum'
enum:
- KIND1
- KIND2```
Now is:
```    Kind:
enum:
- KIND1
- KIND2

PAYARA-4186 Generate correct schema for enums

---

nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/admin/LocalStrings.properties
nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/admin/SetRequestTracingConfiguration.java

PR in response to @Pandrex247 comment https://github.com/payara/Payara/pull/4332#issuecomment-555974202 that adds a warning message to the action report in case any of the store properties is changed. 
I do not change state status to `WARNING` since that would report the action as failed when it wasn't:
Command set-requesttracing-configuration failed.
Start the server, use asadmin console:
```
asadmin> set-requesttracing-configuration --traceStoreSize=20 --enabled=true
Command set-requesttracing-configuration executed successfully.
asadmin> set-requesttracing-configuration --traceStoreSize=19 --enabled=true
Please note that from 5.194 onwards the store size refers to the size of a single store shared by all cluster members. Any configuration change regarding the store should be applied to …
```

PAYARA-4261 Warning when changing request tracing store properties via asadmin

---

appserver/admin/gf_template/src/main/resources/config/domain.xml

#4277 Description
Both -client and -server are defined in default-config of domain.1 domain.xml.  This PR removes the -server option line so that options are the same in server-config and default-config.

PAYARA-4277 : Uniform jvm-option in server-config and default-config

---

pom.xml

- all dependencies are from 3.2, not 3.0
https://download.eclipse.org/microprofile/microprofile-3.2/microprofile-spec-3.2.html#microprofile3.2

PAYARA-4280 Fixed MicroProfile version from 3.0 to 3.2

---

appserver/tests/payara-samples/pom.xml
appserver/tests/payara-samples/samples/ejb-http-remoting/api/pom.xml
appserver/tests/payara-samples/samples/ejb-http-remoting/server-app/pom.xml

This is a test-build fix
In a different PR a regex was run to replace javax with the new jakarta coordinates. However some of the versions didnt exist with jakarta. I have corrected these.
Apache Maven 3.6.0
Java version: 1.8.0_232, vendor: Azul Systems, Inc., 
OS name: "linux", version: "5.0.0-36-generic", arch: "amd64", family: "unix"

CI-33 Fix missed Jakarta versioning

---

nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/GFFileHandler.java

Note: To be refactored to be much more effective under PAYARA-4276, this is a minimal fix
The buffer accepts all messages even before the logging handlers are configured, but - if the capacity is reached, the threads are blocked until some thread would start process records from buffer - this will never be done, so this is a bit risky - this issue does not fix it, only increases the capacity.
Under PAYARA-4276 I will refactor and optimize the logging, I already gained 10-50% throughput in yet uncommited changes (depends on system configuration and state).
See VerboseLoggingITest in https://github.com/payara/Payara/pull/4263
Kubuntu 19.10, OpenJDK11

PAYARA-4161 Fixed full logging - increased buffer capacity

---

appserver/monitoring-console/webapp/JS_DOCS.md
appserver/monitoring-console/webapp/pom.xml
appserver/monitoring-console/webapp/src/main/webapp/css/monitoring-console.css
appserver/monitoring-console/webapp/src/main/webapp/index.html
appserver/monitoring-console/webapp/src/main/webapp/js/mc-bar-chart.js
appserver/monitoring-console/webapp/src/main/webapp/js/mc-common-chart.js
appserver/monitoring-console/webapp/src/main/webapp/js/mc-line-chart.js
appserver/monitoring-console/webapp/src/main/webapp/js/mc-model.js
appserver/monitoring-console/webapp/src/main/webapp/js/mc-trace-chart.js
appserver/monitoring-console/webapp/src/main/webapp/js/mc-view-colors.js
appserver/monitoring-console/webapp/src/main/webapp/js/mc-view-components.js
appserver/monitoring-console/webapp/src/main/webapp/js/mc-view.js
appserver/monitoring-console/webapp/src/main/webapp/js/monitoring-console.js

Makes graph colours configurable by
* adding color input type to `Settings` component that can be used for single or multiple values
* adds configuration for waterline, alerting and critical colours per widget
* adds new settings group _Colors_ which allows to modify the list of colours used for data lines in graphs as well as the defaults for waterline, alerting and critical colours. 
PR also makes settings more flexible by allowing to mark a group as `collapsed` which will not show the settings of the section initially. This was added to hide the colour settings so they don't move the widget settings out of normal screen.
Besides making colours configurable for the user this PR also makes sure that all graphs and pages are consistent in their use of colour for a particular source. With …

Monitoring Console Colour Configuration and Colour Schemes

---

appserver/jdbc/jdbc-config/src/main/java/org/glassfish/jdbc/config/validators/JdbcConnectionPoolValidator.java

https://github.com/payara/Payara/issues/4197
It's my first pull request to payara. Sorry if if did some mistake in some convenion.

CUSTCOM-27: Fix that steady-pool-size can be 0

---

appserver/packager/monitoring-console/pom.xml

This isn't a bug fix / feature. 
Currently maven build starts with
```
[WARNING] Some problems were encountered while building the effective model for fish.payara.server.internal.packager:monitoring-console:distribution-fragment:5.194-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-dependency-plugin @ line 83, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
```
None
1. Full build `mvn clean install` on travis.
2. Reviewed order of goals executed for …

Merge executions of the same plugin

---

appserver/payara-appserver-modules/rest-monitoring/rest-monitoring-war/pom.xml
appserver/payara-appserver-modules/rest-monitoring/rest-monitoring-war/src/main/java/fish/payara/monitoring/rest/app/handler/MBeanAttributeReadHandler.java
appserver/payara-appserver-modules/rest-monitoring/rest-monitoring-war/src/test/java/fish/payara/monitoring/rest/app/handler/MBeanAttributeReadHandlerTest.java

CUSTOM-54: NullPointerException when JMX attribute is null within the rest-monitoring endpoint
When JMX attributes are null, it results in NPE when accessed from the rest-monitoring endpoint.
The fix  checks if the attribute value is null and return JsonValue.NULL in that case instead of the 'generic' method who tries to convert the instance to a JsonValue.
Manual testing
- /asadmin start-domain 
- deploy simple jms example (https://github.com/payara/Payara-Examples/tree/master/javaee/simple-jms-example)
- ./asadmin set-monitoring-level --level=HIGH --module=jmsService --target=server-config
- ./asadmin set-amx-enabled --dynamic=true --enabled=true --target=server-config 
- ./asadmin set-monitoring-service-configuration --mbeanEnabled=true --monitoringEnabled=true …

CUSTOM-54: NullPointerException when JMX attribute is null

---

appserver/security/realm-stores/src/main/java/fish/payara/security/realm/cdi/RealmExtension.java
appserver/tests/payara-samples/pom.xml
appserver/tests/payara-samples/samples/realm-identity-stores/pom.xml
appserver/tests/payara-samples/samples/realm-identity-stores/src/main/java/fish/payara/samples/realm/identity/store/MultipleRealmIdentityStoreAppConfig.java
appserver/tests/payara-samples/samples/realm-identity-stores/src/test/java/fish/payara/samples/realm/identity/store/MultipleRealmIdentityStoreDefinitionTest.java
appserver/tests/payara-samples/samples/realm-identity-stores/src/test/resources/addUsersPayara.txt
appserver/tests/payara-samples/test-utils/src/main/java/fish/payara/samples/ServerOperations.java

This is a bug fix for registration of multiple realm Identity Stores.
`appserver/tests/payara-samples/samples/realm-identity-stores/src/test/java/fish/payara/samples/realm/identity/store/MultipleRealmIdentityStoreDefinitionTest.java`

PAYARA-2598 / CUSTCOM-71 Fix for multiple Realm Identity Stores registration

---

pom.xml

This is a bug fix. In some scenarios, an SSL connection is terminated before data is fully sent. In this case, the SSLBaseFilter will currently keep passing the incomplete data down the chain. An infinite loop was caused by the data handling filters deciding there's not enough data, and restarting the chain. This change makes sure that the SSLBaseFilter doesn't try to repeatedly process incomplete data on a terminated SSL connection.
https://github.com/payara/Payara_PatchedProjects/pull/285 for the artifact
https://github.com/payara/patched-src-grizzly/pull/20 for the source
- Grizzly unit tests

CUSTCOM-83 Update Grizzly Dependencies to 2.4.3.payara-p10

---

appserver/extras/embedded/all/pom.xml
appserver/extras/embedded/web/pom.xml
appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/domain.xml
appserver/extras/payara-micro/payara-micro-distribution/pom.xml
appserver/featuresets/minnow/pom.xml
appserver/packager/appserver-core/pom.xml
appserver/packager/appserver-core/src/main/assembly/appserver-core.xml
appserver/packager/appserver-core/src/main/resources/bin/asadmin
appserver/packager/appserver-core/src/main/resources/bin/asadmin.bat
appserver/packager/appserver-core/src/main/resources/bin/letsencrypt.py
appserver/packager/appserver-core/src/main/resources/glassfish/bin/asadmin
appserver/packager/appserver-core/src/main/resources/glassfish/bin/asadmin.bat
appserver/packager/appserver-core/src/main/resources/pkg_proto.py
appserver/packager/glassfish-common-web/pom.xml
appserver/packager/pom.xml

Jars no longer included: glassfish-embedded-shell,
glassfish-embedded-static-shell, jline-terminal-jna, jna, deployment-client, appserver-cli,domain backup and schema2beans.
Manual restart of server and micro.
Also comparison of jars included in 5.194 and in this PR.
- Java EE 8 Samples
- Microprofile Metrics
- Microprofile Health

CLOUD-12 Removed cruft from Payara Micro

---

appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/micro/services/asadmin/SendAsadminCommand.java

This is an alternative to #4398
As the other commands which accept multiple operands have it as non-optional then I think a better approach is to only check in the command that does it this way, rather than doing a check every single time (which is less efficient).

CUSTCOM-109 SendAsadminCommand now does a check for if supplied instances is null

---

nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java
nucleus/admin/launcher/src/test/java/com/sun/enterprise/admin/launcher/GFLauncherExtractPortTest.java
nucleus/admin/launcher/src/test/java/com/sun/enterprise/admin/launcher/GFLauncherExtractSuspendTest.java
nucleus/admin/launcher/src/test/java/com/sun/enterprise/admin/launcher/GFLauncherJdwpCheckerTest.java

This is a bug fix. (#4386)
Current `GFLauncher` recognizes only old-style JDWP option (`-Xrunjdwp`), but by default from template new one (`-agentlib:jdwp`) is used. With the effect of port not parsed from option (defaulted to -1), https://github.com/payara/Payara/blob/c2905122f21f49ed1455612bdc3aded5b1d1f2ce/nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/StartServerHelper.java#L268 is not fulfilled, and expected message is not logged.
After full build following performed:
```shell
unzip  appserver/distributions/payara/target/payara.zip
./payara5/glassfish/bin/asadmin start-domain --debug=true
```
which resulted in
```
Waiting for domain1 to start ............
Successfully started the domain : domain1
domain  Location: …
```

CUSTCOM-81 Display port number on start-domain with --debug=true option

---

appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastTimerStore.java

This is refactoring (only private implementation details changed).
Follow-up to @jbee's https://github.com/payara/Payara/pull/4311#pullrequestreview-323530383.
Full build (`mvn clean install` on Travis).
Only the ones included in step above.
Ubuntu 16.04.6 LTS
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10)
Maven 3.6.1

CUSTCOM-146 Parametrize *Cache maps

---

appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java

Customer reports occasionally a NullPointerException in `org.glassfish.web.loader.WebappClassLoader` when starting up his Payara Micro (5.193.1) Application.
> Caused by: java.lang.NullPointerException
> at org.glassfish.web.loader.WebappClassLoader.findResourceInternalFromJars(WebappClassLoader.java:2908)
> at org.glassfish.web.loader.WebappClassLoader.findResourceInternal(WebappClassLoader.java:2761)
> at org.glassfish.web.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2651)
There is a synchronized access on a non final property causing multithreading issues in the addJar() and findResourceInternalFromJars()
- Manual smoke testing with a few customer reperoducers to verify normal classloader behaviour
Oracle 8u181, mvn 3.5.4
N/A …

CUSTCOM-76: Fix Thread synchronization in WebappClassloader

---

appserver/web/web-glue/pom.xml
appserver/web/web-glue/src/main/java/com/sun/enterprise/web/deploy/FilterDefDecorator.java
appserver/web/web-glue/src/test/java/com/sun/enterprise/web/deploy/FilterDefDecoratorTest.java

This is a bug fix, for issue originally reported against javaee/glassfish (22406).
New UT `FilterDefDecoratorTest.nullAsyncSupportedFlagShallNotCauseException`.
A. `mvn clean install` 
1. for first commit to make sure UT fails
2. for second commit to make sure it fixes `FilterDefDecorator` and doesn't break the build in other parts.
B. With distribution built in step A2 - *Steps to reproduce* from [22406](https://github.com/eclipse-ee4j/glassfish/issues/22406#issuecomment-504749628), but with step 7 producing expected welcome page.
Only included in full build with command above.
A. Ubuntu 16.04.6 LTS, OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10), maven 3.6.3
B. GNU/Linux, OpenJDK Runtime Environment (build 1.8.0_232-b09), maven 3.6.3

CUSTCOM-144 Avoid NPEx on unboxing null Boolean (javaee/glassfish 22406)

---

appserver/payara-appserver-modules/hazelcast-ejb-timer/pom.xml
appserver/payara-appserver-modules/notification-hipchat-core/pom.xml
appserver/payara-appserver-modules/payara-micro-cdi/pom.xml
appserver/payara-appserver-modules/rest-monitoring/rest-monitoring-war/pom.xml
appserver/web/web-glue/pom.xml
nucleus/core/logging/pom.xml
nucleus/payara-modules/notification-core/pom.xml
nucleus/payara-modules/requesttracing-core/pom.xml
nucleus/pom.xml

This is not a bug fix.
Managed dependency in parent project helps to keep children DRY.
Executed full build: `mvn clean install` that completed successfully.
Linux, openjdk version "1.8.0_232", maven 3.6.3

CUSTCOM-147: Manage mockito

---

appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/service/ResourceAdapterAdminServiceImpl.java
nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/config/AMXConfigLoader.java
nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/jmx/NotificationEmitterSupport.java
nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingOutputStream.java
nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/osgi/OSGiFrameworkLauncher.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/JobCleanUpService.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/GFDomainXml.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ScheduledExecutorServiceFactory.java

During Thread dump analysis, it was not always easy to identify what threads are due to their name (Thread-[n] or pool-[x]-thread-[y])
After this update, threads name are mostly set. Some threads are still un named and could be done in
osgi-javaee-base org.glassfish.osgijavaeebase.ExtenderManager.GlassFishServerTracker#addingService
org.glassfish.osgijavaeebase.JavaEEExtender.HybridBundleTrackerCustomizer#addingBundle
and Apache Felix
This is a improvement
Should be easier to identify threads in Thread Dump.
Manual testing to identify the list of threads through JConsole.
- Quicklook
Mac OS

Thread Naming for easier Thread Dump analysis - CUSTCOM-145

---

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/commands/DeleteJvmOptions.java

When you try to delete a JVM option which has defined a min and/or max version, the option cannot be found (and thus not deleted).
This PR fixes the delete logic of the JVM Options.
No Unit Test created due to proxy requirements of JavaConfig within `org.jvnet.hk2.config.ConfigSupport#apply(org.jvnet.hk2.config.SingleConfigCode<T>, T)` 
./asadmin start-domain
./asadmin create-jvm-options '[1.8.123|1.8.231]-DtestOption'
./asadmin delete-jvm-options '[1.8.123|1.8.231]-DtestOption'
- Quicklook
Maven 3.5.4
JDK 1.8u181

CUSTOM-142 Delete JVM options with min max versions.

---

appserver/tests/payara-samples/samples/pom.xml

See commit message for details.
I've added the optional flag to make none of the connectors include themselves transiently.

CUSTCOM-150 Leaking Managed Connector Dependency

---

nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/StartDomainCommand.java
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/StartServerHelper.java
nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/StartLocalInstanceCommand.java

This is refactoring.
Field
https://github.com/payara/Payara/blob/c2905122f21f49ed1455612bdc3aded5b1d1f2ce/nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/StartServerHelper.java#L91
is not used, so I propose to remove it.
It's also [reported by sonar](https://sonarcloud.io/project/issues?id=fish.payara.server%3Apayara-aggregator&issues=AW0h5g1lbW38OQeaThxd&open=AW0h5g1lbW38OQeaThxd) I see.
`mvn clean install` to make sure whole project is still compilable.
Linux
OpenJDK Runtime Environment (build 1.8.0_232-b09)
maven 3.6.3

Remove unused field debug from StartServerHelper

---

nucleus/common/internal-api/src/main/java/org/glassfish/internal/deployment/GenericHandler.java

This is an improvement to use application name provided by a user if a deployment descriptor does not define the name. 
Tested both the `deploy` and `redeploy` command to make sure the improvement works as intended. 
Zulu JDK 1.8_222 on Elementary OS 0.4.1 Loki with Maven 3.5.4>
TODO

APPSERV-18 Use application name provided by a user when a deployment descriptor does not define the name

---

appserver/tests/payara-samples/samples/pom.xml
appserver/tests/payara-samples/samples/rest-management/pom.xml
appserver/tests/payara-samples/samples/rest-management/src/test/java/fish/payara/samples/rest/management/HttpResponsesTest.java
appserver/tests/payara-samples/samples/rest-management/src/test/java/fish/payara/samples/rest/management/RestManagementTest.java
appserver/tests/payara-samples/test-utils/src/main/java/fish/payara/samples/PayaraTestShrinkWrap.java
appserver/tests/payara-samples/test-utils/src/main/java/fish/payara/samples/ServerOperations.java
nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/readers/FormReader.java

This is a bug fix. Starting a fresh domain in 5.194 and running the following curl command:
~~~
curl -X DELETE -v -H "Content-Type: application/x-www-form-urlencoded" -H "X-Requested-By:Payara" http://localhost:4848/management/domain/servers/server/server/application-ref/non-existing-app-ref
~~~
will cause a HTTP 415 to return, where it should be a 404. Note that in 5.193 this worked.
Second commit. I've made the testing module fairly generic, as I see it as something that could be useful in the future.
The new test against 5.193 and the SNAPSHOT on micro, managed and remote profiles.
- Payara Samples (only single test)
- Java EE7 Samples (only JAX-RS tests against remote)
- Java EE8 Samples (only JAX-RS tests against remote)
Read the commit messages ;)
I've deliberately ignored the …

CUSTCOM-13 A REST management DELETE command returns 415 code instead of 404

---

appserver/web/war-util/src/test/java/org/glassfish/web/loader/WebappClassLoaderTest.java

Synchronisation issues in the WebappClassLoader have already been fixed,
but not tested properly. This commit adds a test for the synchronisation
issues that caused CUSTCOM-76.
Ran the unit test with `-Dsurefire.rerunFailingTestsCount=500` before and after the changes in https://github.com/payara/Payara/pull/4378.

CUSTCOM-76 WebappClassLoader Synchronisation Test

---

appserver/payara-appserver-modules/jaxrs-client-tracing/src/main/java/fish/payara/requesttracing/jaxrs/client/JaxrsClientRequestTracingFilter.java
appserver/payara-appserver-modules/jaxrs-client-tracing/src/main/java/fish/payara/requesttracing/jaxrs/client/PayaraTracingServices.java
appserver/payara-appserver-modules/jaxrs-client-tracing/src/main/java/fish/payara/requesttracing/jaxrs/client/SpanPropagator.java
appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/cdi/TracedInterceptor.java
appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/JerseyOpenTracingAutoDiscoverable.java
appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/OpenTracingApplicationEventListener.java
appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/client/AsyncContextPropagator.java
appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/client/JaxrsClientBuilderDecorator.java
appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/client/JaxrsClientRegistrarProvider.java
appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/client/JaxrsInvocationBuilderDecorator.java
appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/client/JaxrsWebTargetDecorator.java
appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/client/RestClientTracingListener.java
appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/client/TracedMethodFilter.java

```
mvn clean install -TC4 -PQuickBuild,fastest
mvn clean install -PBuildExtras,QuickBuild,fastest -pl :payara-embedded-all
mvn clean install -Ppayara-samples -pl :embedded-vs-jersey
```
- Quicklook Y
- Payara Samples Y
- Java EE7 Samples N
- Java EE8 Samples N
- Payara Private Tests N
- Payara Microprofile TCKs Runner N
- Jakarta TCKs - jaxrs
- Mojarra N
- Cargo Tracker N

CUSTCOM-70 Fixed jersey-client issues with embedded distros of Payara

---

appserver/admin/gf_template/src/main/resources/config/domain.xml
appserver/admin/gf_template_web/src/main/resources/config/domain.xml
appserver/admin/production_domain_template/src/main/resources/config/domain.xml
appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml
appserver/extras/payara-micro/payara-micro-distribution/build.xml

Manual - run with JDK11
`asadmin start-domain --verbose`
- and you should not see warning:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.enterprise.server.logging.LogManagerService (file:/app/appservers/payara5/glassfish/modules/logging.jar) to field java.util.logging.LogManager.props
WARNING: Please consider reporting this to the maintainers of com.sun.enterprise.server.logging.LogManagerService
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

CUSTCOM-165 Prevented warning about illegal access to LogManager's field

---

appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastTimerStore.java

Full build with `mvn clean install`.
GNU/Linux, OpenJDK Runtime Environment (build 1.8.0_232-b09), Maven 3.6.3
1. [Use isEmpty() to check whether the collection is empty or not.](https://sonarcloud.io/project/issues?id=fish.payara.server%3Apayara-aggregator&issues=AW0h5iNJbW38OQeaTjl3&open=AW0h5iNJbW38OQeaTjl3)
2. [Either remove or fill this block of code.](https://sonarcloud.io/project/issues?id=fish.payara.server%3Apayara-aggregator&issues=AW0h5iNJbW38OQeaTjmE&open=AW0h5iNJbW38OQeaTjmE)
3. [Remove this unused "hZTimer" local variable.](https://sonarcloud.io/project/issues?id=fish.payara.server%3Apayara-aggregator&issues=AW0h5iNJbW38OQeaTjmI&open=AW0h5iNJbW38OQeaTjmI)
4. [Use isEmpty() to check whether the collection is empty or …

CUSTCOM-167 Remove unused loop and unnecessary collection size checks

---

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/JobCleanUpService.java

Start Payara Micro.
Before: NPE
Afterwards: None
Zulu JDK 1.8_232 on Ubuntu 19.10 with Maven 3.6.2

APPSERV-40 Fix NPE when starting Payara Micro in JobCleanUpService

---

nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/BlockingQueueHandler.java
nucleus/payara-modules/notification-core/src/test/java/fish/payara/nucleus/notification/BlockingQueueHandlerTest.java

Current https://github.com/payara/Payara/blob/ff7bf071c20e021ef1614e65f765c6ec18bf4468/nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/BlockingQueueHandler.java#L194-L197 throws `ClassCastException`. (It is shown in the first commit.)
```
mvn clean test -pl nucleus/payara-modules/notification-core -Dtest=BlockingQueueHandlerTest
```
and full build (`mvn clean install`)
GNU/Linux, OpenJDK Runtime Environment (build 1.8.0_232-b09), maven 3.6.3

CUSTCOM-171 Prevent ClassCastException

---

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBContainerTransactionManager.java

CUSTCOM-174 Avoid NPE by EJBException.addSuppressed() by ContainerTransactionManager.
EJBException.addSuppressed() will throw a NPE when called with a null parameter. The code within 
ContainerTransactionManager doesn't check for this condition and user encountered this problem due to changes done in 5.194 release (https://github.com/payara/Payara/pull/4325)
No unit test created due to some final methods which cannot be mocked.
- Quicklook

CUSTCOM-174 Avoid NPE by EJBException.addSuppressed() 

---

appserver/admingui/healthcheck-service-console-plugin/src/main/resources/healthcheck/checkers/stuckThreadsConfiguration.jsf
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/GetHealthCheckConfiguration.java
nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/SetHealthCheckServiceConfiguration.java
nucleus/payara-modules/healthcheck-stuck/src/main/java/fish/payara/nucleus/healthcheck/stuck/StuckThreadsHealthCheck.java
nucleus/payara-modules/healthcheck-stuck/src/main/java/fish/payara/nucleus/healthcheck/stuck/admin/StuckThreadsConfigurer.java

Configuring a stuck thread threshold in microsecond or nanosecond range would mean that in order to detect such a "stuck" thread the check detecting it must run faster than the threshold and must run in an interval not much longer than the threshold. Both neither make sense nor are they doable with reasonable effort and resources. Even is such a configuration could be implemented it would not be of much use as threads running for that short of a duration **or longer** are the absolute norm so this would basically trigger all the time. 
TLDR; stuck threads thresholds only make sense in a range that is subjectively "slow" to both humans and machines. 
The change is tackled by assuming that:
* in the future configuration will not allow to set a threshold in nano or microseconds
* we still …

APPSERV-43 Removes micro- and nanoseconds from stuck threads configuration

---

appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/IIOPSSLSocketFactory.java

This is a [possible] bug fix
```
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.String;
```
`mvn clean install`
GNU/Linux, OpenJDK Runtime Environment (build 1.8.0_232-b09), Maven 3.6.3

CUSTCOM-181 Remove unused method

---

appserver/monitoring-console/core/src/main/java/fish/payara/monitoring/admin/SetMonitoringConsoleConfigurationCommand.java
appserver/monitoring-console/core/src/main/java/fish/payara/monitoring/alert/Alert.java
appserver/monitoring-console/core/src/main/java/fish/payara/monitoring/alert/AlertService.java
appserver/monitoring-console/core/src/main/java/fish/payara/monitoring/alert/Circumstance.java
appserver/monitoring-console/core/src/main/java/fish/payara/monitoring/alert/Condition.java
appserver/monitoring-console/core/src/main/java/fish/payara/monitoring/alert/Watch.java
appserver/monitoring-console/core/src/main/java/fish/payara/monitoring/configuration/MonitoringConsoleConfiguration.java
appserver/monitoring-console/core/src/main/java/fish/payara/monitoring/model/Metric.java
appserver/monitoring-console/core/src/main/java/fish/payara/monitoring/store/InMemoryAlarmService.java
appserver/monitoring-console/core/src/test/java/fish/payara/monitoring/alert/ConditionTest.java
appserver/monitoring-console/core/src/test/java/fish/payara/monitoring/alert/WatchSerializationTest.java
appserver/monitoring-console/webapp/JS_DOCS.md
appserver/monitoring-console/webapp/pom.xml
appserver/monitoring-console/webapp/src/main/java/fish/payara/monitoring/web/ApiResponses.java
appserver/monitoring-console/webapp/src/main/java/fish/payara/monitoring/web/MonitoringConsoleResource.java
appserver/monitoring-console/webapp/src/main/webapp/css/monitoring-console.css
appserver/monitoring-console/webapp/src/main/webapp/index.html
appserver/monitoring-console/webapp/src/main/webapp/js/mc-bar-chart.js
appserver/monitoring-console/webapp/src/main/webapp/js/mc-controller.js
appserver/monitoring-console/webapp/src/main/webapp/js/mc-data.js
appserver/monitoring-console/webapp/src/main/webapp/js/mc-line-chart.js
appserver/monitoring-console/webapp/src/main/webapp/js/mc-main.js
appserver/monitoring-console/webapp/src/main/webapp/js/mc-model.js
appserver/monitoring-console/webapp/src/main/webapp/js/mc-trace-chart.js
appserver/monitoring-console/webapp/src/main/webapp/js/mc-view-colors.js
appserver/monitoring-console/webapp/src/main/webapp/js/mc-view-components.js
appserver/monitoring-console/webapp/src/main/webapp/js/mc-view-units.js
appserver/monitoring-console/webapp/src/main/webapp/js/mc-view.js
nucleus/hk2/hk2-config/src/main/java/org/jvnet/hk2/config/WriteableView.java

Adds custom watches to client. In contrast to watches collected from `MonitoringWatchSource`s a custom watch is a user defined `Watch` instance. The monitoring client is used to compose such a watch. This can be done in the new page _Watches_ that also lists all watches and allows to edit, delete or disable and enable them.
A disabled watch is simply not actively evaluating data, it is ignored but it will show in the graphs as a outline box instead of a filled one. All watches can be disabled and enabled. This is stored in the added configuration so that the disabled state can be recreated on server startup.
Only custom watches can be delete. Collected (or programmatic) watches cannot be deleted as they originate from the server's code.
Custom watches can be edited. Programmatic watches …

APPSERV-47 Adds Custom Watches to Monitoring Console

---

nucleus/cluster/admin/src/main/java/fish/payara/admin/cluster/AddInstanceToDeploymentGroupCommand.java

When you create and add a new instance to a deployment group with an application deployed to it, an error is thrown and the application is not deployed
**Steps to reproduce:**
- Start a clean domain
- Create a deployment group with no instances
- Deploy an application to the deployment group
- Create a new instance and add it to the deployment group
- Start the instance and look at the logs
Followed the above reproducer to make sure the fix worked as intended.
Build Test

APPSERV-30 Exception when Adding an Instance to a Deployment Group with an Application Deployed

---

appserver/admingui/cluster/src/main/resources/standalone/standaloneInstanceGeneral.jsf
appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/CommonHandlers.java

Converted the node uptime display format from milliseconds to a human readable format.
There was already a handler for this purpose that could be used. Since a node can also be stopped and then has no uptime, the handler needed a null check.
fixes #4169 
Created a new instance and opened its standaloneInstanceGeneral.jsf page.
Checked the result when the instance is running & stopped.
Zulu JDK 1.8_232
Windows 10
Maven 3.6.1

fixes issue #4169 - Display node uptime in a human readable format

---

appserver/payara-appserver-modules/microprofile/healthcheck/src/main/java/fish/payara/microprofile/healthcheck/HealthCheckService.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigProviderResolverImpl.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigProviderResolverSync.java

- instane() is synchronized
- setInstance is NOT synchronized, so it ignores any locks
- preferring @Inject over ConfigProvider in HealthCheckService
- using @ContractsProvided to allow both @Inject target types
- more logging, but only when configured
- tested in extremely slowed TestContainers docker container
Removed the timeout and countdouwn latch, because 
- it is more simple to diagnose deadlock without timeout
- deadlock should never happen - if it happened, something is broken again => timeout is not a way to get out of it
- this PR fixed the cause of timeout
- this PR still allows inverted (incorrect) order of initialization.
Not pushed reproducer in PAYARA-4176 branch (not production quality, but stacktraces in logs visible)

CUSTCOM-135 Fixed race condition on ConfigProviderResolver initialization

---

nucleus/admin/config-api/src/main/java/org/glassfish/config/support/TranslatedConfigView.java
nucleus/common/glassfish-api/src/main/java/org/glassfish/api/StartupRunLevel.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigProviderResolverImpl.java

Many services have implicit dependency on Microprofile config. We therefore need
to assure that it is already available as services enter startup run level.
Expansion of domain.xml attributes should also refer to our implementation rather
than to MP Config API, as that might lock up in certain scenarios, like single-threaded
startup.
During development of other feature, it became apparent that during load of applications on Payara Micro the startup is single threaded. Therefore no amount of wait would resolve implicit dependency to Microprofile config provider, it simply needs to be started earlier.
Another potential danger point was evalutation of `${MPCONFIG=key}`  while our provider didn't yet start.
Prepared Payara Micro with an deployed application, then restarted …

CUSTCOM-135: Move config initialization before Startup run level

---

pom.xml

- Fixes #4424 
- https://github.com/payara/Payara_PatchedProjects/pull/292 - required to be merged before runing Jenkins; do checkout before runing local Payara build and enable profile using this repo. OR build PR of mojarra.
- https://github.com/payara/patched-src-mojarra/pull/7
- https://github.com/payara/patched-src-mojarra/releases
- Jakarta TCKs
- jsf - one test failed, but fails also for master without changes, 5.193.1 and 5.194.2, all on my computer; manually (deploy war and visit URL) it passed.
- Mojarra - passed
- JDK8, Kubuntu 19.10, Intel i7
Before asking Jenkins to test this you have to approve and merge the Patched Projects PR

CUSTCOM-154 Using Mojarra 2.3.14.payara-p1

---

appserver/payara-appserver-modules/jaxrs-client-tracing/src/main/java/fish/payara/requesttracing/jaxrs/client/PayaraTracingServices.java
appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/JerseyOpenTracingAutoDiscoverable.java
appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/client/JaxrsClientBuilderDecorator.java
appserver/tests/payara-samples/classpath/embedded-vs-jersey/src/test/java/fish/payara/samples/classpath/embeddedvsjersey/JerseyClasspathTest.java

When Payara Embedded is used as a library rather than starting the embedded server, an exception will be thrown when using the JAX-RS client caused by the request tracing service not having initialised.
The previous CUSTCOM-70 fix allowed a JAX-RS client request to be built, but executing the request would still throw the same exception. This change allows the request to be executed as well.
This PR is an extension to https://github.com/payara/Payara/pull/4443, which didn't address the initial problem. The test has been amended to match.
Payara Sample test amendment.

CUSTCOM-70 Additional Fix to JAXRS Client With Embedded Dependency

---

appserver/extras/docker-images/src/main/resources/payaraserver-node/entrypoint.sh

This is a feature to allow Temp/Unmanaged Docker Node instance to Join a Deployment Group on Creation. When creating temporary docker node instances using either the Docker Rest API or Docker CLI, the only way to have an instance join a deployment group upon creation is for you to use a custom Docker image.
With this PR you can specify a Docker Env variable, `PAYARA_DEPLOYMENT_GROUP` which would then be read and used upon instance creation.
Created a Docker image using the newly updated `entrypoint.sh`. Using the Docker image created a container with the `PAYARA_DEPLOYMENT_GROUP` Docker Env variable. 
TODO

APPSERV-27 Allow Temp/Unmanaged Docker Node instance to Join a Deployment Group on Creation

---

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/RUNTIME_OPTION.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/LauncherCreator.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/RootDirLauncher.java

`--warmup` initializes payara micro and immediately shuts down. To be used for preconfiguring fixed root directory in a script or for class data sharing warmup.
`--outputlauncher`  writes out `launch-micro.jar` into defined root directory. This launcher can be used to launch micro from that directory, skipping any directory preparation and dynamic classloading of runtime jars. This makes startup faster and runtime classpath is class data sharing-friendly.
Needs way of test end-to-end behavior on the command line, with precise selection of JDKs. Therefore only manual testing was performed:
Smoke test
```
java -jar payara-micro.jar --rootdir micro-root --outputlauncher
java -jar micro-root/launch-micro.jar --warmup
cd micro-root
. .env
java -cp $MICRO_CLASSPATH …
```

CLOUD-41: Payara Micro warmup mode and optimization-friendly classpath

---

appserver/persistence/cmp/ejb-mapping/pom.xml
appserver/persistence/cmp/enhancer/pom.xml
appserver/persistence/cmp/generator-database/pom.xml
appserver/persistence/cmp/support-ejb/pom.xml

[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …

[SECURITY] Use HTTPS to resolve dependencies in Maven Build

---

appserver/extras/payara-micro/payara-micro-distribution/build.xml
appserver/extras/payara-micro/payara-micro-distribution/pom.xml
appserver/pom.xml

Changes the product name to _Payara Server Enterprise_ or _Payara Micro Enterprise_ for Payara Server & Micro respectively when building using a new _enterprise_ profile.
None
Narp
Build the server and micro with and without the new _enterprise_ profile.
Without the product name present in glassfish-version.properties should be Payara Server / Payara Micro, and Payara Server Enterprise / Payara Micro Enterprise when the profile is provided.
Negative
See above.
N/A
Windows, Java 8
N/A
None.

APPSERV-35 Add 'Enterprise' to product.name

---

appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastTimerStore.java

I took the liberty to interpret _Easy to Contribute_ this way.
Fixes #4356.
Included in `mvn clean build` only.
GNU/Linux, OpenJDK Runtime Environment (build 1.8.0_232-b09), Maven 3.6.3

CUSTCOM-200 Get PKs for every timer found in timers

---

nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/readers/JsonParameterMapProvider.java

The REST management interface couldn't be invoked via a JSON request, since the parameters would be read into the map as a JSONStringImpl, which still contains the wrapping quotation marks. This means that all of the parameters would be wrong. This commit uses the toString method
of the values read rather than hard casting to make sure the correct values are parsed.

CUSTCOM-199 Fix REST management JSON requests

---

appserver/payara-appserver-modules/security-openid/src/main/java/fish/payara/security/openid/OpenIdAuthenticationMechanism.java

This is a bug fix / feature. 
1. If a page contains multiple protected resources and authentication (via OpenID Connect) is activated, multiple redirects to the OpenID Connect provider are performed (one for each protected resource). This is especially the case when auto refresh of the token is activated, the token expires and a new access token must be requested. To prevent multiple redirects, I have synchronized the authentication/refresh logic on the user's session.
2. If auto refresh is enabled for the access token, the principal was registered in the session again after  refreshing the token. This caused the currently active session to be invalidated (destroys all session scoped beans and session attributes).
Deployed developed app on instance with fix installed and …

CUSTCOM-168 OpenID Connect: Fixed simultaneous redirects and invalidation of session

---

nucleus/common/glassfish-api/src/main/java/fish/payara/api/admin/config/NameGenerator.java

The "Wide-eyed" adjective for the auto name generation has a trailing space, leading it to create names like "Wide-eyed -Ladyfish", which breaks stuff.
None

APPSERV-87 Remove trailing space

---

nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/domain/CustomTokenClient.java

Fixes situation when you call create-domain while other instance uses same ports, you disable port checking, but it fails because 7676 is still checked.
Use cases: 
* upgrading Payara and creating new domain by some script while previous version is still running.
* running build of Payara while there is any running instance using default ports
1. asadmin start-domain domain1
2. asadmin create-domain --checkports false ouiehwefwf
Result of checkports=true behaves same in both versions (will generate other ports automatically).
Result from 5.194.2
```
Enter admin user name [Enter to accept default "admin" / no password]>
Using default port 4848 for Admin.
Using default port 8080 for HTTP Instance.
Using default port 7676 for JMS.
Using default port 3700 for IIOP.
Using default port 8181 for …
```

CUSTCOM-195 Fixed throwing exceptions with disabled port check

---

appserver/admingui/common/src/main/resources/configuration/sysInstanceValues.jsf
appserver/admingui/common/src/main/resources/configuration/systemPropertiesButtons.jsf
appserver/tests/payara-samples/samples/rest-management/src/test/java/fish/payara/samples/rest/management/HttpResponsesTest.java
appserver/tests/payara-samples/samples/rest-management/src/test/java/fish/payara/samples/rest/management/SystemPropertyTest.java
appserver/tests/payara-samples/samples/rest-management/src/test/java/fish/payara/samples/rest/management/extension/TemporaryInstance.java
appserver/tests/payara-samples/samples/rest-management/src/test/java/fish/payara/samples/rest/management/extension/TemporaryInstanceExtension.java
appserver/tests/payara-samples/samples/rest-management/src/test/java/fish/payara/samples/rest/management/extension/TemporaryInstanceProvider.java
appserver/tests/payara-samples/samples/rest-management/src/test/java/fish/payara/samples/rest/management/util/RestManagementClientBuilder.java
appserver/tests/payara-samples/samples/rest-management/src/test/java/fish/payara/samples/rest/management/util/RestManagementRequestBuilder.java
appserver/tests/payara-samples/samples/rest-management/src/test/java/fish/payara/samples/rest/management/util/RestManagementWebTarget.java
appserver/tests/payara-samples/samples/rest-management/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
appserver/tests/payara-samples/test-utils/src/main/java/fish/payara/samples/NotMicroCompatible.java
appserver/tests/payara-samples/test-utils/src/main/java/fish/payara/samples/SincePayara.java
nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/custom/SystemPropertiesCliResource.java

This change allows instance property overrides to be created without deleting all the other instance properties by using the REST endpoint correctly. It also allows empty property fields to be submitted to remove the property.
Firstly the PUT and POST methods were the wrong way around, so they've been swapped. Secondly, the POST method didn't allow empty fields, which meant that instance property overrides couldn't be removed. To stop this, empty properties are now treated as properties to be removed.
Setting up domain with:
~~~
asadmin copy-config default-config test-config
asadmin create-instance --node localhost-domain1 --config test-config instance1
asadmin create-system-properties --target instance1 ASADMIN_LISTENER_PORT=12345
asadmin create-system-properties …

CUSTCOM-75 Fix Payara System Property REST API

---

appserver/tests/payara-samples/samples/asadmin/src/test/java/fish/payara/samples/asadmin/AutoNameInstancesTest.java

See title - setting a static variable from BeforeClass didn't seem to persist to the actual container, so set a system property instead.
Ran test using remote profile against domain1 & production, and ran against server-managed container.

APPSERV-86 Allow AutoNameInstancesTest to work with non-default domains.

---

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/RestApiHandlers.java
appserver/tests/payara-samples/samples/asadmin/src/test/java/fish/payara/samples/asadmin/AsadminTest.java
appserver/tests/payara-samples/samples/asadmin/src/test/java/fish/payara/samples/asadmin/SetHazelcastConfigurationTest.java
nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/admin/SetHazelcastConfiguration.java

Prints a warning on the command line and in the admin console when enabling data grid encryption when a key can't be found.
From a clean domain, simply run `set-hazelcast-configuration --encryptdatagrid true` and you should get a warning.
You should get a similar warning when attempting to do the same from the admin console: Domain > Data Grid.
New asadmin test added to existing `SetHazelcastConfigurationTest` in payara-samples.
Checks that a warning is given when enabling datagrid encryption without generating a key.
Touching such a fundamental method in the admin console (`updateEntity`) worries me a bit, as this can easily ripple outwards in unforeseen ways. I've poked around the admin console and haven't managed to make it throw a wobbly but I can't poke everything.

APPSERV-54 Print a Warning if No Encryption Key Present

---

appserver/tests/payara-samples/test-utils/src/main/java/fish/payara/samples/ServerOperations.java
nucleus/admin/server-mgmt/src/main/java/fish/payara/admin/servermgmt/cli/GenerateEncryptionKey.java

The `generate-encryption-key` command will only create the key for the default domain due to the _domain_name_ parameter being commented out on its super class.
A workaround to this is to either make sure there’s only one domain in your domain dir (the default domain is always the solitary domain in the specified domain dir - it doesn't need to be called _domain1_), or to simply copy the generated file from the default domain to where you need it.
This also fixes the SfsbEncryptionTest so that it isn't always running against the default domain.
Ran the SfsbEncryptionTest using server-managed and server-remote profiles, against domain1 and production domains.

APPSERV-88 CUSTCOM-213 generate-encryption-key Command Always Creates Key for Default Domain

---

nucleus/admin/config-api/pom.xml
nucleus/pom.xml

This is an improvement.
During our attempts to update this component to 1.0.2, it started throwing errors due to unsupported operations.
Upon further investigation I'm not convinced we need this dependency any more - it's only test scoped and the test works fine without it.
See related PR from Susan: https://github.com/payara/Payara/pull/4507
Build Payara Server and don't skip tests - the relevant module is config-api.

APPSERV-70 Remove unnecessary test dependency

---

nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/SecureAdminBootstrapHelper.java
nucleus/core/logging/pom.xml
nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/logviewer/backend/LogFilterForInstance.java
nucleus/packager/external/trilead-ssh2/pom.xml
nucleus/pom.xml

Fixes problems with default keys on Ubuntu.
Depends on following PR or usage of special profile in settings.xml as an alternative:
https://github.com/payara/Payara_PatchedProjects/pull/295
The alternative profile:
```
<profile>
<id>ext</id>
<repositories>
<repository>
<id>jenkins</id>
<url>https://repo.jenkins-ci.org/releases/</url>
<snapshots><enabled>false</enabled></snapshots>
<releases><enabled>true</enabled></releases>
</repository>
</repositories>
</profile>
```
See https://github.com/payara/Payara/pull/4548
- these pull requests don't depend on each other, BUT with both integrated is possible to change configuration in UI between password and keyfile authentication using ECDSA private key.

CUSTCOM-211 Upgraded Trilead library and included ECDSA support

---

nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java

The message stating that encryption is enabled is printed regardless of whether or not it is actually enabled.

CUSTCOM-223 Move log message into if block

---

appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/MySqlPersistenceManager.java
appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/PostgresPersistenceManager.java

Reverted unintended removal of setSchemaOnConnection for JBatch on MySQL and Postgres.
Tested reproducer for reported issue.

CUSTCOM-219: Fix setSchemaOnConnection for JBatch on MySQL and Postgres

---

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java

This removed the command that will restart Hazelcast, as it is already started during boot.
Alternative to #4576 
Start Payara Micro, check the Hazelcast has only been started once.
Tested with reproducer from #4457
Zulu JDK 1.8_232 on Ubuntu 19.10 with Maven 3.6.2

CLOUD-13 Remove command that restarts Hazelcast, so it is only started once

---

appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/FaultToleranceConfig.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/FaultToleranceMethodContext.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/FaultToleranceService.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/cdi/FaultToleranceInterceptor.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/policy/BulkheadPolicy.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/policy/CircuitBreakerPolicy.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/policy/FallbackPolicy.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/policy/FaultTolerancePolicy.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/policy/Policy.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/policy/RetryPolicy.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/service/BindableFaultToleranceConfig.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/service/FaultToleranceMethodContextImpl.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/service/FaultToleranceServiceImpl.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/service/FaultToleranceUtils.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/test/java/fish/payara/microprofile/faulttolerance/policy/AbstractBulkheadTest.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/test/java/fish/payara/microprofile/faulttolerance/policy/BulkheadBasicTest.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/test/java/fish/payara/microprofile/faulttolerance/service/FaultToleranceMethodContextStub.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/test/java/fish/payara/microprofile/faulttolerance/service/FaultToleranceServiceStub.java
pom.xml

A good summary on the spec changes can be found https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.1/microprofile-fault-tolerance-spec.html#release_notes_21
Changes for Payara FT:
* adds of new exception handling properties to `@Fallback` (`applyOn` and `skipOn`) and `@CircuitBreaker` (`skipOn`)
* adds: CDI `@RequestScope` context is now activated for worker threads working `@Asynchronous` computation
* adds: `@Bulkhead` and `@Asynchronous` annotated methods returning `CompletionStage` now semantically exit the bulkhead when they complete (not when the annotated method returns a value).
* fixes: exception handling corrected to handle both `Exception` and `Error` (missed `Error` before which wasn't spec compliant before but went unnoticed until 2.1 that clarified …

APPSERV-57 Updates to MicroProfile Fault Tolerance 2.1

---

appserver/appclient/client/appclient-scripts/src/main/resources/glassfish/bin/.gitattributes
appserver/extras/docker-images/src/main/resources/payaraserver-node/.gitattributes
appserver/packager/appserver-core/src/main/resources/bin/.gitattributes
appserver/packager/appserver-core/src/main/resources/glassfish/bin/.gitattributes
appserver/packager/glassfish-common-web/src/main/resources/bin/.gitattributes
appserver/packager/glassfish-common-web/src/main/resources/glassfish/bin/.gitattributes
appserver/persistence/cmp/cmp-scripts/src/main/resources/glassfish/bin/.gitattributes
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/.gitattributes
nucleus/packager/nucleus/src/main/resources/bin/.gitattributes
nucleus/packager/nucleus/src/main/resources/config/.gitattributes

This should ensure that unix shell scripts work even when distribution was built on Windows with automatic CRLF conversion. This was causing trouble when testing #4402 on Windows. Clean checkout after adding `.gitattributes` solved issues with bash scripts failing in containers.
`git clone --single-branch --branch qaci-158 Payara payara-test`
Verify that shell files in affected source directories have unix line endings, whereas windows one retain CRLF line endings.
Built docker images from #4402 
Windows 10, Maven 3.6.3

QACI-158: Enforce UNIX line endings for shell scripts

---

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/commands/DeleteJvmOptions.java

This is a bug fix to fix an issue where the `delete-jvm-options` command required the specify Java version prefix to execute successfully. 
None
Build test
Manually tested the `delete-jvm-options` command with and without the Java version prefix with the following commands: 
-  `./asadmin delete-jvm-options '[Azul-1.8.0u222|1.8.0u500]-XX\:+UseOpenJSSE'` 
-  `./asadmin delete-jvm-options '-XX\:+UseOpenJSSE'` 
Not required

CUSTCOM-194 The delete-jvm-options command shouldn't require to specify the Java version prefix

---

pom.xml

This is a feature.
Updates MicroProfile Health to 2.2.
No other changes required for this update, it updates it to require CDI 2.0 which we already provide.
[MP TCK Runner PR](https://github.com/payara/MicroProfile-TCK-Runners/pull/105)
Build Tests.
MP Health, all permutations.
Windows 10, JDK 8u242.
https://github.com/payara/Payara-Server-Documentation/pull/727

APPSERV-60 Update MP Health to 2.2

---

appserver/jdbc/jdbc-config/src/test/java/org/glassfish/main/jdbc/config/validators/JdbcConnectionPoolValidatorTest.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/converters/AutomaticConverter.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/converters/ShortConverter.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigProviderResolverImpl.java
pom.xml

This is a feature.
Minor update - changes the order of implicit converters, and added a built-in converter for shorts.
[MP TCK Runner](https://github.com/payara/MicroProfile-TCK-Runners/pull/104)
Ran through full MP TCK (server-managed).
Ran through MP Config TCK (server-remote, server-managed, micro-managed, and embedded)
Payara Build tests.
Windows, Zulu JDK 8u242
https://github.com/payara/Payara-Server-Documentation/pull/725

APPSERV-58 Update to MP Config 1.4

---

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/Application.java

This fix allows using a custom realm defined in web.xml in a WAR application for authenticating SOAP requests using the WS policy mechanism. 
Without the fix, the default realm is always used even if a custom realm is defined in the WAR file.
This fixes a customer issue.
Manual testing on Payara Server 5.191.7 (Java 8) and 5.201 (Java 11), on Ubuntu Linux.

CUSTCOM-247 Propagates realm name from WAR module to its application wrapper 

---

appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/FaultToleranceServiceConfiguration.java
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/service/FaultToleranceServiceImpl.java

To avoid TCK runs failing due to pool rejecting execution the default is increased to 2000. The TCK at some point uses 1000 threads in a single test. Local tests with a max of 2000 has shown to avoid this issue.

Increase FaultTolerance async max pool size from 1000 to 2000

---

appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/PayaraMicro.java
appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/AdminCommandRunner.java
appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/PayaraMicroBoot.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/CommandResultAdapter.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/CommandResultWrapper.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
appserver/extras/payara-micro/payara-micro-distribution/pom.xml
appserver/payara-appserver-modules/microprofile/fault-tolerance/src/test/java/fish/payara/microprofile/faulttolerance/policy/AbstractBulkheadTest.java
appserver/tests/payara-samples/samples-programmatic/src/test/java/fish/payara/samples/programatic/PayaraMicroCommandsTest.java

Adds methods `setPreBootHandler` and `setPostBootHandler` that offer functionality similar to `--prebootcommandfile` and `--postbootcommandfile` of Payara Micro jar.
The methods accept Consumer of `CommandRunner`, allowing the user to also inspect the output of the commands, and direct their flow.
Two secondary things are addressed with this PR:
* 38a8641 adds flatten plugin to Payara Micro distribution. The installed POM does not contain any dependencies anymore, making it equal with release POM.
* 2abfc10 adds more diagnostic information to failure of Bulkhead tests, as I've experienced some during development.
Alternative to #4600 
`PayaraMicroCommandsTest` tests and demonstrated the API.
OpenJ9 1.8.0_242 on Windows 10, Maven 3.6.3
Javadoc comments …

CLOUD-59: Programmatic API for preboot and postboot commands in Micro

---

nucleus/packager/nucleus-grizzly/pom.xml

This is a bug fix to fix an issue on ZuluJDK 8.44, where accessing HTTPS throws NoSuchMethodError exception.  
To test this issue edit the Grizzly NPN version of the following JVM options: `-Xbootclasspath/p:${com.sun.aas.installRoot}/lib/grizzly-npn-bootstrap-1.8.1.jar` to `1.9.payara-p1` and run https://github.com/summerwind/h2spec with h2spec -t -k -p 8181 on Zulu 8.44. After a request has been made check the log file to see if the NoSuchMethodError exception has been thrown. 
https://github.com/payara/Payara_PatchedProjects/pull/297
https://github.com/payara/patched-src-grizzly-npn/pull/2
- Build test
- Quicklook
TODO

CUSTCOM-205 On ZuluJDK 8.44, accessing HTTPS throws NoSuchMethodError exception 

---

appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/startup/EjbApplication.java
appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/JavaEESecurityLifecycle.java
appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/SecurityDeployer.java
appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebContainer.java

- JVM global security objects and JVM options must be configured before
first usage
- it is hard to control the right point in the startup sequence, previous
version relied on some side effects (admin gui initiated it, but on
domain nodes it is not deployed).
Depends on PAYARA-4176, see testing how to use it for testing.
```
cd /repo/git
git clone git@github.com:dmatej/arquillian-junit5-extension.git
cd arquillian-junit5-extension
mvn clean install
cd ..
git clone git@github.com:payara/Payara.git payara-cc133
cd payara-cc133
git remote add dmatej git@github.com:dmatej/Payara.git
git fetch --all
```
This should fail:
```
git checkout origin/master
mvn clean install -PQuickBuild,fastest
git checkout dmatej/PAYARA-4176-TestContainers-prototype
mvn clean install -Ptest-containers  -pl …
```

CUSTCOM-133 Fixed jaspic on domain nodes

---

appserver/web/web-core/src/main/java/org/apache/catalina/session/StandardSession.java
appserver/web/web-ha/src/main/java/org/glassfish/web/ha/session/management/BaseHASession.java

This is a bug fix of deadlock described in #4281 
I could not create simple reproducer because race conditions are hard to reproduce. 
EDIT dmatej: the possible deadlock is well visible from sources.
Reviewer should proove that the cycle between classes existed in previous version and now is fixed correctly.
@dmatej

CUSTCOM-260 Fixed possible deadlock in StandardSession

---

appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/service/FaultToleranceServiceImpl.java

New threadpools for Fault tolerance doesn't shut down cleanly while having a permanent cleanup task scheduled.
There is probably more that should be done (i. e. utilizing `PayaraExecutorService` instead), but it fixes the largest trouble at this moment.
`java -jar payara-micro.jar --warmup` didn't terminate before the fix, it does now.
AdoptOpenJDK 14+36 (by mistake) on Windows 10.
Zulu 11.0.6 in Docker

APPSERV-142: Shutdown fault tolerance thread pools on server shutdown

---

api/payara-bom/pom.xml

Payara BOM contains a referene to a non existent Maven dependency.
Fixes #4618.
mvn validate

CUSTCOM-261: Remove jakarta.transaction.cdi:jakarta.transaction.cdi-api from Payara BOM as it is wrong.

---

nucleus/core/logging/pom.xml
nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/GFFileHandler.java
nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogFormatHelper.java
nucleus/core/logging/src/test/java/com/sun/enterprise/server/logging/LogFormatTest.java

If Payara Server is restarted with the JSON log formatter then the logs would always rotate.
New test file added in this commit.
Tested by restarting the server and checking that no new additional log files are created.
Zulu JDK 1.8_212 on Ubuntu 18.04 with Maven 3.6.0

CUSTCOM-265 Restarting the domain with the Payara log formatter causes the log to rotate

---

appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/MetricsService.java
appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java
nucleus/common/glassfish-api/pom.xml
nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/ComponentInvocation.java
nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/ComponentInvocationHandler.java
nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/InvocationManagerImpl.java
nucleus/common/glassfish-api/src/test/java/org/glassfish/api/invocation/InvocationManagerImplTest.java

Running FT TCK strongly suggested that a race condition in or around the `InvocationManger` leads to inconsistent context when trying to derive the _current_ application like shown below:
```java
ComponentInvocation current = invocationManager.getCurrentInvocation();
if (current == null) {
return invocationManager.peekAppEnvironment().getName();
}
String appName = current.getAppName();
if (appName == null) {
appName = current.getModuleName();
}
if (appName == null) {
appName = current.getComponentId();
}
return appName;
```
The issue observed was that different application names were returned in a non deterministic manner for the actual same application processing tests.
The most likely cause is related to the frames that push and pop the stack which is peeked by `getCurrentInvocation()`. …

APPSERV-114 Addresses possible sources of Race Conditions in InvocationManager

---

appserver/payara-appserver-modules/microprofile/config/src/main/java/fish/payara/microprofile/config/cdi/ConfigPropertyProducer.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/PayaraConfig.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/test/java/fish/payara/nucleus/microprofile/config/spi/PayaraConfigTest.java

Fixes behaviour for undefined properties of `PayaraConfig` for arrays, lists and sets.
If an undefined property is resolved the `Config` implementation should always throw an `NoSuchElementException`. This behaviour was changed unintentional and incorrectly by #4614 .
Added unit tests for undefined property lookup.
Running MP TCKs https://github.com/payara/MicroProfile-TCK-Runners :
```bash
export my_int_property=45
export MY_BOOLEAN_PROPERTY=true
export my_string_property=haha
export MY_STRING_PROPERTY=woohoo
export MP_CONFIG_CACHE_DURATION=0
export MP_METRICS_TAGS=tier=integration
{payara-bin-dir}/asadmin start-domain
cd {tck--runner-base-dir}/tck-runner/
mvn clean install "-Ppayara-server-remote" "-Dpayara.version=5.202"
```
This is used to run MP Config, MP Metrics, MP Rest Client and …

APPSERV-141 Fixes undefined behaviour of PayaraConfig 

---

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/boot/runtime/JarManifestHk2Factory.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/boot/runtime/JarManifestModuleRegistry.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/boot/runtime/MicroGlassFishRuntime.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java

SingleModuleHK2Registry assumes that all runtime jars are enumerated by
context class loader, which is only true when Payara Micro's special
classloader is involved. When launched with RootDir launcher, classpath
only contains launcher jar, and the module list need to be read from
its manifest.
Testing was done by trying to start a JSF application in rootdir mode:
```
java -jar $micro --rootDir root --deploy jsf-app.war --nocluster --warmup
java -jar $micro --rootDir root --outputlauncher
java -jar root/launch-micro.jar --nocluster --warmup
```
Application would not start up in third case, it didn't before, because `FacesContext.getCurrentContext()` would fail.
Tested multiple JVMs on Windows, as this relates to root classloader:
* Zulu11.37+17-CA
* Zulu 8.46.0.19-CA-win64
* AdoptOpenJDK …

CUSTCOM-266: Fix HK2 Config when Payara Micro is launched via Root Dir Launcher

---

appserver/tests/payara-samples/samples/jaxws-security/src/test/java/fish/payara/samples/jaxws/security/ejb/EJBEndpointTest.java

This is just a fix of my previous PR #4638 where I mistakenly switch 2 assertions in 2 unstable tests.

CUSTCOM-247: Fix of switched assertions in tests

---

pom.xml

Updates MicroProfile Rest Client to 1.4.
Minor update, not many changes required - the main one is that the ClientHeadersFactory is now CDI scoped.
The actual changes are in Jersey, see Dependant PRs
https://github.com/payara/patched-src-jersey/pull/59
https://github.com/payara/patched-src-microprofile-rest-client/pull/3
https://github.com/payara/Payara_PatchedProjects/pull/298
New tests added to Rest Client TCK to check App and Request scope.
MicroProfile Rest Client TCK.
Windows 10, JDK8.
Pending...

APPSERV-61 Update MP Rest Client to 1.4

---

appserver/extras/docker-images/basic/pom.xml
appserver/extras/docker-images/basic/src/main/docker/Dockerfile
appserver/extras/docker-images/basic/src/main/docker/assembly.xml
appserver/extras/docker-images/micro/src/main/docker/Dockerfile
appserver/extras/docker-images/micro/src/main/docker/assembly.xml
appserver/extras/docker-images/micro/src/main/docker/bin/.gitattributes
appserver/extras/docker-images/micro/src/main/docker/bin/entrypoint.sh
appserver/extras/docker-images/pom.xml
appserver/extras/docker-images/server-full/pom.xml
appserver/extras/docker-images/server-full/src/main/docker/Dockerfile
appserver/extras/docker-images/server-full/src/main/docker/assembly.xml
appserver/extras/docker-images/server-node/pom.xml
appserver/extras/docker-images/server-node/src/main/docker/Dockerfile
appserver/extras/docker-images/server-web/pom.xml
appserver/extras/docker-images/server-web/src/main/docker/Dockerfile
appserver/extras/docker-images/server-web/src/main/docker/assembly.xml
appserver/extras/docker-images/tests/pom.xml
appserver/extras/docker-images/tests/src/test/java/fish/payara/distributions/docker/PayaraContainer.java
appserver/extras/docker-images/tests/src/test/java/fish/payara/distributions/docker/PayaraMicroTest.java
appserver/extras/docker-images/tests/src/test/java/fish/payara/distributions/docker/PayaraServerNodeTest.java
appserver/extras/docker-images/tests/src/test/java/fish/payara/distributions/docker/war/TestServlet.java

* Fixes incompatibility with debian/ubuntu based JDK11 images
* Fixes warning about unsupported JVM option
* Adds features - JVM memory settings for Micro and Server-Full and JVM_ARGS for Micro
* All Dockerfiles use same commands for same things
* URL for gpg can be changed with -D parameter
`mvn clean install -PBuildExtras,BuildDockerImages -pl :docker-images -amd`
`mvn clean install -PBuildExtras,BuildDockerImages -pl :docker-images -amd -Ddocker.payara.tag=5.202-SNAPSHOT-JDK11 -Ddocker.java.repository=adoptopenjdk/openjdk11 -Ddocker.java.tag=jdk-11.0.6_10-debian-slim`
1. Build some Payara4 versions including all required distribution packages
2. This will generate docker images
3. PayaraServerNodeTest will fail, because there is a difference in syntax, but other images should pass …

CUSTCOM-130 Better compatibility of docker images

---

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebComponentInvocation.java
nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/InvocationManagerImpl.java

Strictly it would be correct to assume that the `ComponentInocation` passed to `preInvoke` should be the same as the one passed to `postInvoke`. This however is difficult to do in some cases (see #4646). Relaxing expectations `equal` is also problematic as `WebComponentInocation#equal` would need to change. To avoid introducing new issues `WebComponentInocation`s will be excluded from the logging. This needs to be done matching the class name as string as the module making the check cannot become dependent on the module defining that class. I figured that checking the simple class name is sufficient here.
I also improved the formatting of the log message and added the strack trace as it is important to find where the inconsistent call is coming from.
After revisiting this and with the …

APPSERV-157 preInvoke/postInvoke ComponentInvocation logging

---

pom.xml

Requires payara/Payara_PatchedProjects#303
Zulu JDK 1.8_212 on Ubuntu 18.04 with Maven 3.6.0
Eclipselink tagged at https://github.com/payara/patched-src-eclipselink/tree/eclipselink-2.7.6.payara-p1

APPSERV-109 Upgrade Eclipselink to 2.7.6.payara-p1

---

appserver/admin/gf_template/src/main/resources/config/domain.xml
appserver/admin/gf_template_web/src/main/resources/config/domain.xml
appserver/admin/production_domain_template/src/main/resources/config/domain.xml
appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml

These versions also contain the ALPN functionality included in Java 9,
so should be treated as such by the domain options.
Fixes https://github.com/payara/Payara/issues/4625
JDK 1.8u154 SSL connection.

Remove Grizzly ALPN from 1.8.0u251 and above

---

nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/JavaConfig.java
nucleus/admin/launcher/src/test/java/com/sun/enterprise/admin/launcher/JavaConfigTest.java

This is a bug fix. Github ticket: https://github.com/payara/Payara/issues/4619
Since Java 9 JDWP agent listens only local network interface by default so remote connections would be rejected. In this PR, If server mode is enabled then address port is prefixed with `*:` to enable remote connection. Unfortunately, the `*:` syntax is not backward compatible to Java 8 hence debug address requires an update on runtime.
https://github.com/payara/Payara/blob/8dc6dd06b74eccfd92c10fdb4e91a0f0a40cc12f/nucleus/admin/launcher/src/test/java/com/sun/enterprise/admin/launcher/JavaConfigTest.java#L56-L78
Tested manually with IntelliJ IDEA 2020.1 patched with [`glassfishIntegration.jar`](https://youtrack.jetbrains.com/api/files/74-834117?sign=MTU4NzYwMDAwMDAwMHwxMS01MjcxODV8NzQtODM0MTE3fENxVk9wVllnSzV6MGxK …

CUSTCOM-264 Client mode debugging (server=no) doesn't work with JDK>=9

---

appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/MetricsService.java
appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/impl/MetricRegistrationListener.java
appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/impl/MetricRegistryImpl.java
pom.xml

Goal was to make the MicroProfile Metadata of MP metrics available as "related data" for the MC series resulting from each MP metric.
The solution uses the existing concept of MC annotations which are key-value pairs associated with a series at a certain point in time of that series. As annotations are limited to a certain capacity and then replace the oldest the concept of annotation needed to be extended so that annotation could be made that would be permanent. Meaning other non-permanent annotations are disposed to make room for newer annotations before any permanent annotation is replaced. This is done by https://github.com/payara/monitoring-console/pull/9 and used in this PR by the `MetricsService` to add the annotation data.
Needs https://github.com/payara/monitoring-console/pull/9 …

APPSERV-148 Adds MP Metadata as permanent MC annotation

---

appserver/payara-appserver-modules/microprofile/metrics/pom.xml
appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/rest/MetricsResource.java
appserver/payara-appserver-modules/microprofile/metrics/src/test/java/fish/payara/microprofile/metrics/rest/AcceptContentTypeTest.java

Metrics endpoint's parsing of accept header was incomplete, and failed on media type requests with multiple parameters, like
` application/vnd.google.protobuf;proto=io.prometheus.client.MetricFamily;encoding=delimited;q=0.7,text/plain;version=0.0.4;charset=utf-8;q=0.3`
`AcceptContentTypeTest` tests known corner scenarios
`AcceptContentTypeTest` and curl with mentioned accept header
OpenJDK 64-Bit Server VM (Zulu 8.46.0.19-CA-win64) (build 25.252-b14, mixed mode)
Apache Maven 3.6.3
Windows 10

CUSTOM-271: Support multiple media type parameters

---

appserver/admin/gf_template/src/main/resources/config/domain.xml
appserver/admin/gf_template_web/src/main/resources/config/domain.xml
appserver/admin/production_domain_template/src/main/resources/config/domain.xml
appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml

When trying to set the values of one or more system properties for a non-DAS instance (or through its configuration) in the admin console, an error is thrown.
- Build test
**Steps to reproduce:**
1. Start the default Payara Server domain.
2. Launch the admin console. Proceed to create a new configuration called instance-config that copies the default configuration.
3. Head to the System Properties option of this new configuration, add a new property called fish.payara.properties.sample and set its value to example. Hit the Save button, which will cause the error to appear.

CUSTCOM-262 HZ_LISTENER_PORT property error when setting system properties via the admin console

---

appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/SecurityServicesImpl.java

When a CDI event is fired in async mode with Weld-specific option to enable parallel execution of events, not all events are triggered as expected if one of them throws an exception.
- Build test
- Jakarta TCK

CUSTCOM-237 In Weld, parallel execution mode for async observers doesn't trigger all observers

---

Jenkinsfile
api/payara-api/pom.xml
api/payara-bom/pom.xml
appserver/distributions/payara-ml/pom.xml
appserver/distributions/payara-web-ml/pom.xml
appserver/distributions/payara-web/pom.xml
appserver/distributions/payara/pom.xml
appserver/ejb/ejb-http-remoting/client/pom.xml
appserver/extras/embedded/all/pom.xml
appserver/extras/embedded/web/pom.xml
appserver/extras/payara-micro/payara-micro-distribution/pom.xml

My understanding is the following modules should be deployed. They currently do not. This change is to deploy these, and only these with maven deploy:
- fish/payara/api/payara-api
- fish/payara/api/payara-bom
- fish/payara/distributions/payara-ml/
- fish/payara/distributions/payara-web-ml
- fish/payara/distributions/payara-web
- fish/payara/distributions/payara
- fish/payara/extras/ejb-http-client
- fish/payara/extras/payara-embedded-all
- fish/payara/extras/payara-embedded-web
- fish/payara/extras/payara-micro
- fish/payara/extras/payara-source
Credentials and permissions to deploy to nexus are required, as is specifying the deployment repo. That is part of A change to internal CI pipeline
Needs to be done on all streams
none
none
ran mvn clean deploy locally, and via Internal Jenkins …

QACI-172 Utilise mvn deploy

---

appserver/admingui/common/src/main/help/en/help/ref-editjdbcrealm.html
appserver/admingui/reference-manual/src/main/help/en/help/reference/create-auth-realm.html

Based off https://stackoverflow.com/questions/48247919/how-to-configure-payara-jdbcrealm-jdbcdigestrealm-to-store-passwords-in-httpd-st

SERV-25 Document JDBCRealm encoding property

---

appserver/monitoring-console/core/src/main/java/fish/payara/monitoring/admin/SetMonitoringConsoleConfigurationCommand.java
appserver/monitoring-console/core/src/main/java/fish/payara/monitoring/configuration/MonitoringConsoleConfiguration.java
appserver/monitoring-console/core/src/main/java/fish/payara/monitoring/runtime/MonitoringConsoleRuntimeImpl.java
pom.xml

This PR adds the page names (IDs) and values to the server side monitoring console configurations which is used by https://github.com/payara/monitoring-console/pull/11 to provide a fully integrated server side page configuration for MC. Requires https://github.com/payara/monitoring-console/pull/11 and https://github.com/payara/monitoring-console/pull/15 to be merged first and release 1.2 of MC implementation made.
Assuming MC changes are released (or build locally) build this PR and install it.
* start server
* enable monitoring console
* open monitoring console webapp in the browser
* clear browsers local storage for the page
* refresh the page, check the role selection popup is shown
* select _User_ role
* check that the page synchronisation popup is shown
* with no previous pages …

APPSERV-124 Monitoring-Console: Adds server side page configuration

---

appserver/tests/payara-samples/pom.xml
appserver/tests/payara-samples/samples-programmatic/pom.xml

Quick fix to stop micro tests on running on remote profile
Tested and passed locally
Ran maven clean install;
```mvn -V -B -fae help:active-profiles clean install -f appserver/tests/payara-samples -Dpayara.version=5.2020.2-SNAPSHOT -Dpayara_domain=test-domain -Dglassfish.home=/home/alanroth/Workspace/Payara/appserver/distributions/payara/target/stage/payara5 -Ppayara-server-remote```
Openjdk 11.0.7
Ubuntu 64 bit
Maven 3.6.3
This isn't designed to be a permanent solution, origionally planned on having a annotation like 'NotMicroCompatible' but for remote, 'NotRemoteCompatible'

QACI-242 Payara Samples Tests Are Attempting to Run Micro Tests for Remote Profile

---

appserver/payara-appserver-modules/security-oauth2/src/main/java/fish/payara/security/oauth2/OAuth2StateHolder.java

Fixes https://github.com/payara/ecosystem-security-connectors/issues/33, injected OAuth2AccessToken is always empty
I applied the patch locally build the module and tested it. 
Please, see the github issue.

ECOSYS-161 OAuth2AccessToken empty instance injected

---

api/payara-api/src/main/java/fish/payara/security/openid/api/OpenIdContext.java
appserver/payara-appserver-modules/security-openid/src/main/java/fish/payara/security/openid/OpenIdAuthenticationMechanism.java
appserver/payara-appserver-modules/security-openid/src/main/java/fish/payara/security/openid/OpenIdIdentityStore.java
appserver/payara-appserver-modules/security-openid/src/main/java/fish/payara/security/openid/domain/OpenIdContextImpl.java
appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/test/InvalidRedirectURITest.java
appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/test/OpenIdDefaultTest.java
appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/test/OpenIdTestUtil.java
appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/test/UseCookiesTest.java
appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/test/WithoutNonceTest.java

This is a fix to set the caller's name & groups after the authentication in `OpenIdContext` and error message logged if redirect URL not matched with request URL.
Manually Tested, Payara-Samples

ECOSYS-157 OpenID Connect Caller's name and groups are null

---

Jenkinsfile

EE8 failed due to log already existing. Quicklook removed all .zips in its setup which is now commented out.

QACI-262 - Remove exisiting EE8 .zip log before archiving new log

---

nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/LocalServerCommand.java
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/StopDomainCommand.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/AppServerStartup.java

This a feature to improve the stop-domain process. Now check is performed to see if the hostname passed by the `--host` parameter represents the current machine. 
Ran the following command to test:
```
./asadmin start-domain
./asadmin --host $MY_HOSTNAME --port 4848 stop-domain
```
Not required

CUSTCOM-14 Improvements in stop-domain process

---

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/SetCommand.java
nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/DisableCommand.java

This fixes an issue where disabling applications via their deployment group target didn't work.
- Created an instance
- Created a deployment group, added he instances to it and started it
-  Deployed a web application targeting the deployment group
- Disabled the application using the following commands:
1. `asadmin set deployment-groups.deployment-group.<dg-name>.application-ref.<appname>.enabled=false`
2. `asadmin disable --target <dg-name> <appname>`

FISH-13 Disabling applications via their deployment group targets not working

---

nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/AbstractStatefulRealm.java

This is a bug fix to fix were creating a JDBC Realm failed with a NullPointerException. This was caused by the default value of the Digest Algorithm being null.
Ran the following asadmin command:
```
./asadmin create-auth-realm --classname=com.sun.enterprise.security.auth.realm.jdbc.JDBCRealm --property=jaas-context=jdbcRealm:datasource-jndi=jdbc/youtube:user-table=t_user:user-name-column=username:password-column=password:group-table=t_usergroup:group-table-user-name-column=username:group-name-column=groupnames: --target=server-config test
```

FISH-197 Creating a JDBC Realm fails with a NullPointerException

---

appserver/extras/certificate-management/src/main/java/fish/payara/certificate/management/CertificateManagementKeytoolCommands.java
appserver/extras/certificate-management/src/main/java/fish/payara/certificate/management/admin/AbstractCertManagementCommand.java
appserver/extras/certificate-management/src/main/java/fish/payara/certificate/management/admin/GenerateSelfSignedCertificateCommand.java
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/KeystoreManager.java

Also fixes `generate-self-signed-certificate` from adding the certificate to the trust store as a PrivateKeyEntry rather than as a trustCertEntry.
Also fixes bug with replacing a self-signed certificate with its signed certificates equivalent.
Please note that the pem is certificate only. Adding just a private key on its own isn't intended behaviour with the Java keystore, you have to make a bundle first.
No new automated tests.
* Generate-self-signed cert: `asadmin generate-self-signed-certificate --dn "CN=biggles.tiddles.fish" tiddles`
* View key and trust store, should be _PrivateKeyEntry_ and _trustedCertEntry_ respectively: 
* `keytool -list -keystore .\appserver\distributions\payara\target\stage\payara5\glassfish\domains\domain1\config\cacerts.jks -storepass …

FISH-188 FISH-200 FISH-216 Fix adding pems to key/trust stores

---

appserver/extras/certificate-management/src/main/java/fish/payara/certificate/management/admin/AbstractCertManagementCommand.java
appserver/extras/certificate-management/src/main/manpages/fish/payara/certificate/management/admin/generate-csr.1
appserver/extras/certificate-management/src/main/manpages/fish/payara/certificate/management/admin/generate-self-signed-certificate.1

This is an improvement.
Previously you had to give the domain name as `--domain_name` when using the cert management commands (e.g. `generate-self-signed-certificate`). This simply allows you to also use `domainname`.
* Ran `generate-self-signed-certificate` using _domainname_ parameter
* Ran `generate-csr` using _domain\_name_ parameter
Windows 10, Zulu JDK 8u252
Pending...

FISH-187 Allow domainname in cert management commands

---

appserver/extras/docker-images/server-full/src/main/docker/Dockerfile
appserver/extras/docker-images/server-web/src/main/docker/Dockerfile

Fixed typo made in fddc468b4c85b08ff6b957e3517be6617fffb12c
Fixes issue #4688 
`mvn clean install -amd -PBuildExtras,BuildDockerImages -pl :docker-images`

FISH-236 Fixed typo - name of the passwordfile in dockerfiles

---

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/RUNTIME_OPTION.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
appserver/extras/payara-micro/payara-micro-core/src/main/resources/commandoptions.properties
nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/PayaraFileWatcher.java

When running Payara Micro with `--enableDynamicLogging` the logging properties file will be copied into the exploded directory and read again.
To reproduce, use the following log properties file:
~~~
#Payara Micro Logging Properties File
handlers=java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.formatter=com.sun.enterprise.server.logging.ODLLogFormatter
com.sun.enterprise.server.logging.ODLLogFormatter.ansiColor=true
java.util.logging.ConsoleHandler.level=FINE
.level=INFO
#All log level details
PayaraMicro.level=INFO
~~~
Run Payara Micro with --logproperties and notice that changing the file doesn't print anything.
Run Payara Micro also with --enableDynamicLogging and change the global log level to FINE. Notice that an INFO log appears saying log levels have been updated. …

FISH-205 Implement Dynamic Micro Logging Properties

---

appserver/extras/certificate-management/src/main/manpages/fish/payara/certificate/management/admin/add-to-keystore.1
appserver/extras/certificate-management/src/main/manpages/fish/payara/certificate/management/admin/add-to-truststore.1
appserver/extras/certificate-management/src/main/manpages/fish/payara/certificate/management/admin/remove-expired-certificates.1
appserver/extras/certificate-management/src/main/manpages/fish/payara/certificate/management/admin/remove-from-keystore.1
appserver/extras/certificate-management/src/main/manpages/fish/payara/certificate/management/admin/remove-from-truststore.1

Original PR by Jonathan.
This is a feature.
Manually tested with --help option for the commands
Java EE7 Samples
This PR adds documentation in the form of man pages

FISH-190 Added man pages for certificate management commands

---

pom.xml

There was an issue with the Monitoring console 1.2 release where it was missing some changes it should have had that prevented it from working.

FISH-243 Use monitoring console 1.2.1

---

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/tags/TagImpl.java
appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/test/app/application/TagExampleTest.java

Signed-off-by: Gaurav Gupta <gaurav.gupta@payara.fish>
This is a fix to exclude duplicate tags from OpenAPI metadata.
Unit test
Unit tests
MP OPEN API TCK Runner
Windows 10, JDK 11.0

FISH-42 OpenAPI document has duplicate Tag items

---

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/api/visitor/ApiContext.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ApplicationProcessor.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/visitor/OpenApiContext.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/visitor/OpenApiWalker.java
appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/test/app/application/ExternalSchemaExampleTest.java

Signed-off-by: Gaurav Gupta <gaurav.gupta@payara.fish>
This is a bug fix that dynamically picks and scans `@Schema` class, if not found in the list of selected classes for OpenAPI metadata processing but exists in the classpath.
Unit  test
https://github.com/payara/Payara/blob/1bcbbd250b8204ac0ffc9cfdcc387b27dc9a3197/appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/test/app/application/ExternalSchemaExampleTest.java#L68
Unit tests
MP OPEN API TCK Runner
Windows 10, JDK 11.0

FISH-56 OpenAPI document doesn't use @Schema when class is in jar dependency of the project

---

appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java

Is this a feature that adds support for [multi-release JAR ](https://openjdk.java.net/jeps/238)files in WAR file
The reproducer is available on the [JIRA issue](https://payara.atlassian.net/browse/FISH-148)

FISH-148 Support multi-release JAR files in WAR file

---

appserver/payara-appserver-modules/microprofile/config/src/main/java/fish/payara/microprofile/config/cdi/ConfigProducer.java
appserver/payara-appserver-modules/microprofile/config/src/main/java/fish/payara/microprofile/config/cdi/ConfigPropertyProducer.java
appserver/security/realm-stores/src/main/java/fish/payara/security/realm/config/CertificateRealmIdentityStoreConfiguration.java
appserver/security/realm-stores/src/main/java/fish/payara/security/realm/config/FileRealmIdentityStoreConfiguration.java
appserver/security/realm-stores/src/main/java/fish/payara/security/realm/config/PamRealmIdentityStoreConfiguration.java
appserver/security/realm-stores/src/main/java/fish/payara/security/realm/config/SolarisRealmIdentityStoreConfiguration.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/converters/ArrayConverter.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/converters/AutomaticConverter.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigProviderResolverImpl.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigValueResolver.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigValueResolverImpl.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/InjectedPayaraConfig.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/PayaraConfig.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/test/java/fish/payara/nucleus/microprofile/config/spi/ConfigTestUtils.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/test/java/fish/payara/nucleus/microprofile/config/spi/ConfigValueResolverTest.java
nucleus/payara-modules/nucleus-microprofile/config-service/src/test/java/fish/payara/nucleus/microprofile/config/spi/PayaraConfigTest.java

The programmatic MP `Config` API currently lacks certain capabilities that are granted when accessing configuration properties using CDI and the `@ConfigProperty` annotation. Like injecting `List`s, `Set`s for properties with a value with potentially multiple elements. Or to provide a default value in its raw `String` form as provided by a `ConfigSource`. 
As a consequence there was the need to use non standardised APIs when doing this programmatically. Essentially the `Config` needed to be cast to `PayaraConfig` to access extra methods available that would allow these operations. 
The reason these were needed was also to implement the CDI support. This mismatch between the `Config` API and the standard capabilities granted by the `@ConfigProperty` annotation isn't news to the standard …

MicroProfile Config Value Resolver API POC

---

Jenkinsfile
appserver/tests/quicklook/gfproject/h2.properties

Delete the test|sa.mv.db file during setup, as it keeps getting corrupted

QACI-262 Quicklook is broken on Public Jenkins

---

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/OpenApiService.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/config/OpenApiConfiguration.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ApplicationProcessor.java

Signed-off-by: Gaurav Gupta <gaurav.gupta@payara.fish>
This is a feature to include classes for OpenAPI Metadata scanning from the packaged jar within a  war.
Unit tests, Manual testing, MP OpenAPI TCK Runner
Windows 10, JDK 11.0
TODO

FISH-128 OpenAPI does not include APIs from jars within a war 

---

nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/LocalStrings.properties
nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/domain/DomainPortValidator.java

Now missing default value will be indicated when using custom template for domain creation.
- Copy `/glassfish/common/templates/appserver-domain.jar` form previous Payara release into `<payara-5.2020.2>/glassfish/common/templates/appserver-domain.jar`
- Run command: `./asadmin create-domain --nopassword test`

FISH-219 Indicate missing default value when using custom template for domain creation

---

appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/MetricUnitsUtils.java
appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/MetricsService.java
appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/writer/OpenMetricsExporter.java
appserver/payara-appserver-modules/microprofile/metrics/src/test/java/fish/payara/microprofile/metrics/MetricUnitsUtilsTest.java

Payara changes for https://github.com/payara/monitoring-console/pull/18, details can be found there.
In this PR the main goal is to provide two additional attributes in the permanent annotation:
* `BaseUnit`: The unit considered base unit for MP Metrics
* `ScaleToBaseUnit`: Factor to convert the metric unit to its base unit as used by MP Metrics
In order to share the code responsible for unit scale factor is extracted to a utility class.

FISH-7 Adds more MP Metrics Metadata as MC Annotation for Query Pages (Virtual Pages)

---

appserver/payara-appserver-modules/microprofile/metrics/pom.xml
appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/cdi/extension/MetricCDIExtension.java
appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/cdi/interceptor/ConcurrentGaugeInterceptor.java
appserver/payara-appserver-modules/microprofile/metrics/src/test/java/fish/payara/microprofile/metrics/cdi/interceptor/ConcurrentGaugeInterceptorTest.java
appserver/web/web-glue/src/main/java/com/sun/web/server/J2EEInstanceListener.java
nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/InvocationManagerImpl.java
nucleus/pom.xml

In certain build environment we were hitting following exception:
```
java.lang.RuntimeException: Exception during processing of event of type AFTER_FILTER_EVENT for web module StandardEngine[glassfish-web].StandardHost[server].StandardContext/1bbf5b4d-c5b2-4d17-90f9-0c21032d50fe
at com.sun.web.server.J2EEInstanceListener.handleAfterEvent(J2EEInstanceListener.java:321)
at com.sun.web.server.J2EEInstanceListener.instanceEvent(J2EEInstanceListener.java:113)
at org.apache.catalina.util.InstanceSupport.fireInstanceEvent(InstanceSupport.java:317)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:260)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
at …
```

FISH-260 QACI-296: Add diagnostics for missing top-level invocation on stack

---

appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/PayaraMicroLauncher.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java

RootDirLauncher invokes PayaraMicroImpl directly, and that made instance inaccessible via PayaraMicro API. The change will explicitly set the static instance holder in PayaraMicroLauncher.
The solution is not particulary nice, the entire bootstrap API could use some refactoring, a task for that has been put on backlog
Deploying https://github.com/pdudits/data-replication-talk/tree/master/consumer-app into prepared rootdir and waiting for scheduled task to launch (every 15 second) would have one of these outcomes:
```
Caused by: javax.ejb.CreateException: Initialization failed for Singleton UserDataPoller
at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:542)
at com.sun.ejb.containers.AbstractSingletonContainer.access$000(AbstractSinglet …
```

CUSTCOM-293: Explicitly register launched PayaraMicro instance to bootstrap API

---

nucleus/packager/nucleus-grizzly/pom.xml
nucleus/pom.xml
pom.xml

This is an improvement enabling HTTP/2 when native ALPN APIs are found (8u252+).
Note that Zulu versions with the -XX:+OpenJSSE flag don't support HTTP/2.
Grizzly changes: https://github.com/payara/patched-src-grizzly/pull/23
h2spec
OpenJDK 11, Zulu JDK 8u252 and Zulu JDK 8u232.

FISH-31 Upgrade Grizzly to 2.4.4.payara-p3

---

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/OpenApiService.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/OpenAPIImpl.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/media/SchemaImpl.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/security/SecuritySchemeImpl.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/util/ModelUtils.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ApplicationProcessor.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/visitor/OpenApiContext.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/visitor/OpenApiWalker.java

Signed-off-by: Gaurav Gupta <gaurav.gupta@payara.fish>
This is a feature that includes refactoring of OpenAPI implementation by scanning OpenAPI metadata per class and support of the merging of multiple OpenAPI documents created via the deployment of more than one application.
Unit test
MP OpenAPI TCK Runner
Manually tested with 2 WARs
Windows 10, JDK 11.0
Merging document from multiple application works well for list attributes but attribute like 'info' is overridden by the document of last deployed application.

FISH-162 OpenAPI Class Data Processing

---

appserver/tests/payara-samples/samples/rest-management/src/test/java/fish/payara/samples/rest/management/ServerLogTest.java

The warnings that failed ServerLogTest should be solved with FISH-31, which has been now merged.
Testing with this PR

QACI-249 Revert "Exclude ServerLogTest"

---

pom.xml

Fixes https://github.com/payara/Payara/issues/4060 
Tested with reproducer mentioned on the above issue.

FISH-45 Unable to resolve jackson-dataformat-xml due to wrong OSGI version range

---

appserver/extras/docker-images/pom.xml

Now that HTTP/2 support has been extended to 8u252, the Dockerfiles can
be updated to use this Java version.

FISH-278 Update Docker Java Versions to 8u252

---

appserver/tests/payara-samples/samples/clustered-singleton/clustered-singleton-ejb/pom.xml
appserver/tests/payara-samples/samples/jaxws-security/pom.xml

JDK11 seemed to throw random classpath related exceptions in a couple of
projects. These dependencies seem to fix the problems.
Maintenance PR of https://github.com/payara/Payara/pull/4792

FISH-240 Fix Classpath Exceptions in Samples

---

appserver/extras/certificate-management/certificate-management-admin/pom.xml
appserver/extras/certificate-management/certificate-management-cli/pom.xml
appserver/extras/certificate-management/certificate-management-common/pom.xml
appserver/extras/certificate-management/certificate-management-console-plugin/pom.xml

Cert Management was missed from the version increment, leading to failures when building with the `-PBuildExtras` profile.

Fix Cert Management Versions

---

appserver/extras/docker-images/pom.xml

The JDK11 Docker images are currently built in a separate Maven lifecycle with a manual system property override. This change causes the Docker Maven plugin to generate a '-jdk11' version of each Docker image in the same lifecycle.

FISH-289 Create JDK11 Docker images

---

appserver/payara-appserver-modules/microprofile/healthcheck/src/main/java/fish/payara/microprofile/healthcheck/HealthCheckService.java

To support the RAG indicator added by https://github.com/payara/monitoring-console/pull/20 each health check is made into a metric series. In addition aggregation series are created for:
* all checks of an app liveness
* all checks of an app readiness
* all checks of an app health
* all checks of an app (overall - that is liveness,  readiness or health)
* all checks of any app liveness
* all checks of any app readiness
* all checks of any app health
* all checks of any app (overall - that is liveness,  readiness or health)
The results of the health checks can carry additional key-value data which in case of a `DOWN` state are added as MC annotation.
Lastly each of the created series is also watched by a watch that is collected for it.
When checks are run they always run in their …

FISH-257 Adds RAG Status metrics and watches for MP Health Checks

---

appserver/admin/gf_template/src/main/resources/config/domain.xml
appserver/admin/gf_template_web/src/main/resources/config/domain.xml
appserver/admin/production_domain_template/src/main/resources/config/domain.xml
appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml
appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/UtilHandlers.java
appserver/admingui/common/src/main/resources/shared/sslAttrs.inc
appserver/extras/docker-images/pom.xml
appserver/extras/embedded/all/src/main/resources/config/domain.xml
appserver/extras/embedded/web/src/main/resources/config/domain.xml
nucleus/admin/template/src/main/resources/config/domain.xml
nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/HttpConnectorAddress.java
nucleus/common/common-util/src/main/java/com/sun/enterprise/util/JDK.java

The -XX:+OpenJSSE flag is disabled for Zulu versions above 8u262 (as they now have native TLS 1.3 support).
TLS 1.3 option is now visible for 8u262+ as well.
Docker Zulu versions have been updated to avoid problems with TLS 1.3.

FISH-314 Enable TLS 1.3 on JDK 8u262

---

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java

Is this a bug fix to where you could not set `payaramicro.logPropertiesFile` and `payaramicro.enableAccessLogFormat` system property
Fixes: https://github.com/payara/Payara/issues/4428
Run the command below:
- java -Dpayaramicro.logPropertiesFile=logging.properties -jar payara-micro.jar

FISH-35 Payara Micro system property payaramicro.logPropertiesFile and payaramicro.enableAccessLog do not work

---

appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wscompile
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wscompile.bat

The wscompile script hadn't been adapted to use the new jakarta jar.
I've also removed a classpath entry which doesn't seem to exist? (aixporting).
Ran wscompile script and **didn't** get a lovely CNF exception.
Windows 10, JDK 8u262 & JDK 11.0.8

FISH-90 Fix incorrect classpath in wscompile script

---

nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/domain/execoptions/RequestTracingExecutionOptions.java

During the startup of the server with request tracing enabled, it was possible for an NPE to be thrown due to a check of `shouldStartTrace`. This simply enforces that the execution options have default values for everything rather than relying on the `bootstrapRequestTracing` method.
Not really feasible due to race condition nature and lack of reproducer.
I cannae see how this could break anything though (famous last words) - what could go wrong?

FISH-89 Address possible NPE during request tracing startup

---

nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/store/RequestTraceStoreFactory.java

Adds a check to the RequestTraceStoreFactory for whether the ClusteredStore service is actually active.
`java -jar payara-micro.jar --enableRequestTracing --warmup --rootdir startup`
You should see no errors about ClusteredStore being started at _RunLevel_ 9 rather than 10.
Windows 10, Zulu JDK 8u262

FISH-82 Command Line option --warmup results in an Exception when Payara Micro instance stops when Request Tracing is activated

---

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/RUNTIME_OPTION.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/RequestTracingValidator.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/RuntimeOptions.java
appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
appserver/extras/payara-micro/payara-micro-core/src/main/resources/commandlogstrings.properties
appserver/extras/payara-micro/payara-micro-core/src/test/java/fish/payara/micro/cmd/options/RequestTracingValidatorTest.java

The `--enableRequestTracing` command line option for Payara Micro originally accepted configuration values so that you didn't have to specify the `--requesttracingthresholdunit` and `--requesttracingthresholdvalue` options separately. At some point extra validation was added to the command line arguments, which broke this.
I've added a new runtime option type of "optional followup value", since the configuration options are, well, optional. 
I've also moved some of the validation into a proper valdiator.
New unit (kind of) test added to Payara Micro Boot module to check that options can be set (doesn't validate the option itself - just that you **can** add configuration values)
```
java -jar payara-micro.jar --enableRequestTracing --noCluster
java -jar payara-micro.jar …
```

FISH-59 Payara Micro --enableRequestTracing argument not accepting values 

---

appserver/tests/payara-samples/samples/jakartaee-namespace-transformer/pom.xml

Title.
New module added to samples has an incorrect parent pom version and causes failures in CI.

Fix Incorrect Parent Pom Version

---

api/payara-api/src/main/java/fish/payara/notification/requesttracing/RequestTraceSpan.java

Currently if you try to use the _toString_ method on an active span (as in a span that hasn't actually finished yet) you get a NPE due to it not having an end time. This fixes this by simply not attempting to print this detail.
It also calculates a trace duration.
Tested using Rudy's app.
You can also see this by evaluating an active span during debugging.

FISH-388 Fix NPE when printing out active span

---

pom.xml

This reverts commit 2a0b89bc068ceb6ce93330ee0f822f5afadabdb8.
The reverted commit breaks a websocket TCK test. QACI-406 will endeavour to fix this test without rolling back functionality.

Revert "FISH-31 Upgrade Grizzly to 2.4.4.payara-p3"

---

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/DataSourceDefinitionDescriptor.java
appserver/jdbc/jdbc-runtime/src/main/java/org/glassfish/jdbcruntime/deployment/annotation/handlers/DataSourceDefinitionHandler.java
appserver/jdbc/jdbc-runtime/src/test/java/org/glassfish/jdbcruntime/deployment/annotation/handlers/DataSourceDefinitionTest.java

If URL has been set it should override the serverName, causing that to be set to null
to prevent that being using when the DataSource is initialised
Fixes #4385
New test added in PR, DataSource Definition Tests
* Written test
* Debugging Payara and checking the value of serverName is set to null and unused
* Docker test in original issue
Zulu JDK 1.8_262 on Ubuntu 20.04 with Maven 3.6.3

FISH-37 URL in DataSourceDefinition overrides serverName

---

appserver/resources/javamail/javamail-connector/src/main/java/org/glassfish/resources/javamail/admin/cli/CreateJavaMailResource.java
appserver/tests/payara-samples/samples/asadmin/pom.xml
appserver/tests/payara-samples/samples/asadmin/src/test/java/fish/payara/samples/asadmin/CreateJavaMailResourceTest.java

Bug fix.
When using the "New JavaMail session" screen on the Web administration console, the user is allowed to choose a Deployment Group. When saving however, the follow error appears on the screen:
```
Resource <name> has Invalid target to create resource-ref on <dg-name>.
```
This was caused by the create-javamail-resource command itself not allowing a target type of deployment group.
None.
New asadmin test added, which creates a deployment group and a javamail resource, before attempting to assign a resource ref between them.
Essentially the steps taken in the added test.
Windows, Zulu JDK 8u265
N/A
Brownie point for whomever spots the mythological reference without using Google/Wikipedia 🐿

FISH-55 Creating Java Mail Session targetted to Deployment Group fails

---

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java
nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/DisableCommand.java
nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/EnableCommand.java

When using the Maven cargo plugin to deploy an application on a deployment group, it is listed as not being enabled, when going to the endpoint of an instance in the deployment group show it is.
Detail information on the reproducer is available on [FISH-87](https://payara.atlassian.net/browse/FISH-87).

FISH-407 List of enabled application targets is not always correct

---

appserver/ejb/ejb-container/pom.xml
appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/BaseContainer.java
appserver/tests/payara-samples/samples/remote-ejb-tracing/remote-ejb-tracing-client/src/test/java/fish/payara/samples/remote/ejb/tracing/RemoteEjbClientIT.java
appserver/transaction/jta/pom.xml
appserver/transaction/jta/src/main/java/com/sun/enterprise/transaction/JavaEETransactionManagerSimplified.java
nucleus/payara-modules/opentracing-adapter/src/main/java/fish/payara/opentracing/OpenTracingService.java

Improvement.
Adds the transaction ID as a baggage item to the active span.
To accomodate this, the old-style request tracing was changed to be in the OpenTracing style.
The old style of attaching the log details to the currently active thread local trace is still present however for cases where we can't determine the tracer or active span.
New test added to existing `remote-ejb-tracing` sample, checking that a transaction ID has been added as a baggage item.
Pending...

FISH-389 Add Transaction ID as Span Baggage Item

---

appserver/payara-appserver-modules/payara-rest-endpoints/src/main/java/fish/payara/appserver/rest/endpoints/RestEndpointModel.java

Bugfix. list-rest-endpoints command doesn't list REST endpoints tagged with @PATCH.
Ran the reproducer for the issue.

FISH-393: asadmin command list-rest-endpoints doesn't list PATCH methods.

---

appserver/ejb/ejb-opentracing/src/main/java/fish/payara/ejb/opentracing/OpenTracingIiopServerInterceptor.java
appserver/tests/payara-samples/samples/remote-ejb-tracing/remote-ejb-tracing-client/pom.xml

Bug fix.
OpenTracingIiopServerInterceptor starts a trace even if request tracing is disabled - this is inconsistent with the behaviour of opentracing and request tracing everywhere else.
Ran the remote-ejb-tracing sample. Before it didn't enable request tracing and would still pass against a clean domain - with the changes in this PR it should fail against a clean domain so I've added extra setup and teardown steps to the test.

FISH-392 Fix Trace getting started when Request Tracing is Disabled

---

appserver/admin/gf_template/src/main/resources/config/domain.xml
appserver/admin/production_domain_template/src/main/resources/config/domain.xml
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/schemagen
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/schemagen.bat
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsdeploy
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsdeploy.bat
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsgen
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsgen.bat
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsimport
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsimport.bat
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/xjc
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/xjc.bat

Bug fix.
Fixes the incorrect file in the webservices scripts, and adds the Jakarta JWS API Jar to the import script too as it seems to need it.
The tester servlet doesn't use these scripts however, and instead uses the Java APIs directly. To fix this, I've had to add classpath entries as a system property as it appears to not use the already loaded classes and instead gets the classpath specified during bootstrap (by default `${installRoot}/glassfish/modules/glassfish.jar` which is just the bootstrap jar).
Related to https://github.com/payara/Payara/pull/4837
Fixes https://github.com/payara/Payara/issues/4350
Using https://github.com/rlfnb/JaxWSPoC, deploying, and hitting endpoint: http://localhost:8080/StupidWebService/StupidWebService?Tester
Should successfully import and not spew out a …

FISH-25 Fix SOAP Web Service Tester not working correctly on JDK 11

---

appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/schemagen
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/schemagen.bat
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wscompile
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wscompile.bat
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsdeploy
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsdeploy.bat
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsgen
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsgen.bat
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsimport
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsimport.bat
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/xjc
appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/xjc.bat

The JDK no longer includes any Java EE packages, this PR adds them to the classpath when using the web services utilies.
Tested by running commands on JDK11 and checking for NoClassDefFoundErrors
Zulu JDK 11.41 on Ubuntu 20.04 with Maven 3.6.3
OpenJDK 11.0.8 on Ubuntu 20.04

FISH-93 Add Jakarta EE jars to classpath for JDK11

---

nucleus/common/common-util/src/main/java/org/glassfish/admin/payload/PayloadFilesManager.java
nucleus/common/common-util/src/main/java/org/glassfish/admin/payload/ZipPayloadImpl.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/AdminAdapter.java

Using curl command `curl --location --request POST 'http://127.0.0.1:4848/__asadmin/deploy?name=mavenproject22&contextroot=/mavenproject22&upload=false&type=war&target=server&force=true' \
--header 'Content-Type: application/zip' \
--data-binary '~/hello-world.war'` and checking for success.
Using curl command `curl --location --request POST 'http://127.0.0.1:4848/__asadmin/deploy?name=mavenproject22&contextroot=/mavenproject22&upload=true&type=war&target=server&force=true' \
--header 'Content-Type: application/zip' \
--data-binary @hello-world.war` and checking for success.
Also deployed using asadmin command and via admin console to check that nothing else has broken.
Behaviour now matches documentation, upload=false …

FISH-198 Fix for IllegalArgument when deploying using curl to endpoint with upload flag

---

nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java

When `_JAVA_OPTIONS` environment variable is set it makes executions of `java ...` print out out the options before the usual output.
This breaks the `java -version` check done during launcher bootstrap since it expects it to be on the first line. This fix simply makes it check all lines.
None
Nil
Keiner - messing with env variables is iffy in a _build_ test
Set environment variable
Start server with debug enabled
Stepped through to check if skips incorrect java options line and reads the correct "version" line: https://github.com/payara/Payara-Enterprise/compare/payara-server-4.1.2.191.maintenance...Pandrex247:FISH-396?expand=1#diff-7fd7ed9c30a3768cece34b929651acb8R919
Checked that full list of java options are present.
OpenSUSE Leap 15.2, 8u252
OpenSUSE Leap 15.2, …

FISH-396 _JAVA_OPTIONS prevents Payara Server determining Java version for JVM options

---

appserver/payara-appserver-modules/microprofile/openapi/pom.xml
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/ExtensibleImpl.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/OpenAPIImpl.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/media/SchemaImpl.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/responses/APIResponseImpl.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/responses/APIResponsesImpl.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ApplicationProcessor.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/BaseProcessor.java
appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/visitor/OpenApiWalker.java
appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/test/app/OpenApiApplicationTest.java
appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/test/app/application/ExternalSchemaWithProducesTest.java
appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/test/app/application/schema/TeacherDTO.java

Fixes #4802
New test included in PR
* Tested using reproducers on Jira tickets
* Microprofile OpenAPI TCK
Zulu JDK 1.8_262 on Ubuntu 20.04 with Maven 3.6.3
Previously schemas may not have been referenced by APIResponse if the schema class was scanned later than the REST class, so this PR means the the APIWalker will go through the classes a second time to add in any references that didn't get linked the first time.

FISH-99 FISH-298 Schemas are always picked up and used in OpenAPI

---

appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/jmx/MBeanMetadataConfig.java

through usage of CopyOnWriteArrayLists. fixes #4855.
Signed-off-by: Sven Diedrichsen <sdiedrichsen@yahoo.de>
This PR replaces the usage of ArrayLists with CopyOnWriteArrayLists within MBeanMetadataConfig

FISH-446 #4855 metrics endpoint preventing ConcurrentModificationException

---

appserver/tests/payara-samples/pom.xml
appserver/tests/payara-samples/samples/jaxws-tracing/pom.xml
appserver/tests/payara-samples/samples/jaxws-tracing/src/main/java/fish/payara/samples/jaxws/endpoint/TraceMonitor.java
appserver/tests/payara-samples/samples/jaxws-tracing/src/main/java/fish/payara/samples/jaxws/endpoint/ejb/JAXWSEndPointImplementation.java
appserver/tests/payara-samples/samples/jaxws-tracing/src/main/java/fish/payara/samples/jaxws/endpoint/servlet/JAXWSEndPointImplementation.java
appserver/tests/payara-samples/samples/jaxws-tracing/src/test/java/fish/payara/samples/jaxws/test/JAXWSEndpointTest.java
appserver/tests/payara-samples/samples/jaxws-tracing/src/test/java/fish/payara/samples/jaxws/test/ejb/EJBEndpointTest.java
appserver/tests/payara-samples/samples/jaxws-tracing/src/test/java/fish/payara/samples/jaxws/test/servlet/ServletEndpointTest.java
appserver/tests/payara-samples/test-utils/src/main/java/fish/payara/samples/PayaraTestShrinkWrap.java

The module depended on JDK support for JAX-WS. There were also other issues:
- missing separation between test and war packages
- Unstable wasn't inside the war package which caused errors on JDK8 on server side (JDK11 has fix for this)
- **the test still fails now, but the result is same on JDK8 and JDK11**
With both JDK11 and JDK8:
```
rm -rf ./target; mvn clean install -pl :payara-samples,:jaxws-tracing -Ppayara-samples,payara-server-managed,unstable -fae
```
With JDK8 only:
```
rm -rf ./target; mvn clean install -pl :payara-samples -Ppayara-samples,payara-server-managed -fae -amd
rm -rf ./target; mvn clean install -pl :payara-samples,:jaxws-tracing -Ppayara-samples,payara-server-managed,unstable -fae -amd
asadmin start-domain; mvn clean install -pl :payara-samples,:jaxws-tracing …
```

QACI-451 Compile jaxws-tracing on jdk11

---

nucleus/admin/monitor/src/main/java/org/glassfish/admin/monitor/StatsProviderManagerDelegateImpl.java

Under certain conditions, a Warning with Stacktrace can be thrown when Services are still registering and the MonitoringRuntimeData is accessed.  This replaces the stacktrace with a proper warning message so that the module for which the enable/disable occurs is known.
Basic testing with Monitoring Service active.
Second commit contains a cleanup of the code so align with code conventions.

FISH-441: Write Warning message instead of Exception when MonitoringRuntimeData not found.

---

appserver/connectors/descriptors/src/main/resources/glassfish/lib/dtds/payara-resources_1_6.dtd
appserver/jdbc/admin/src/main/java/org/glassfish/jdbc/admin/cli/CreateJdbcConnectionPool.java
appserver/jdbc/admin/src/main/java/org/glassfish/jdbc/admin/cli/JDBCConnectionPoolManager.java
appserver/jdbc/admin/src/main/manpages/org/glassfish/jdbc/admin/cli/create-jdbc-connection-pool.1
appserver/jdbc/jdbc-runtime/src/main/java/org/glassfish/jdbc/deployer/JdbcConnectionPoolDeployer.java
appserver/resources/resources-connector/src/main/java/org/glassfish/resources/admin/cli/ResourceConstants.java
appserver/resources/resources-connector/src/main/java/org/glassfish/resources/admin/cli/ResourcesXMLParser.java

This is a feature. It adds the options for log-jdbc-calls to the asadmin command `create-jdbc-connection-pool` and as an attribute to the `jdbc-connection-pool` element in `resources.xml`.
Tested with the resources.xml file
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources PUBLIC "-//Payara.fish//DTD Payara Server 4 Resource Definitions//EN" "file:///home/jcoustick/NetBeansProjects/Payara/appserver/connectors/descriptors/src/main/resources/glassfish/lib/dtds/payara-resources_1_6.dtd">
<resources>
<jdbc-connection-pool name="TestPool"
res-type="javax.sql.DataSource"
datasource-classname="org.h2.jdbcx.JdbcDataSource" log-jdbc-calls="true">
<property name="user" value="sa"/>
<property name="password" value=""/>
<property name="url" value="jdbc:h2:mem:hibernateExample"/> …
```

FISH-154 Support log-jdbc-calls in asadmin and xml

---

appserver/tests/payara-samples/samples/logging/pom.xml
appserver/tests/payara-samples/samples/logging/src/main/java/fish/payara/samples/logging/LogRecordMapParameterServlet.java
appserver/tests/payara-samples/samples/logging/src/test/java/fish/payara/samples/logging/JsonLogFormatIT.java
appserver/tests/payara-samples/samples/pom.xml
nucleus/core/logging/src/main/java/fish/payara/enterprise/server/logging/JSONLogFormatter.java

Feature.
Parameters added to a log record as a map will now be logged out.
Also adds some default maven-failsafe -plugin settings because I'm tired of copy-pasting them.
None.
New sample added.
Ran sample test.
Also tested manually by deploying servlet in sample, changing log formatting to JSON, and hitting servlet.
Windows 10, JDK 8u265
Pending...
None.

FISH-141 Support Additional Fields with LogRecord when using JsonLogFormatter

---

appserver/admin/gf_template/src/main/resources/config/domain.xml
appserver/admin/gf_template_web/src/main/resources/config/domain.xml
appserver/admin/production_domain_template/src/main/resources/config/domain.xml
appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml
appserver/extras/embedded/all/src/main/resources/config/domain.xml
appserver/extras/embedded/web/src/main/resources/config/domain.xml
appserver/tests/payara-samples/samples/rest-management/src/test/java/fish/payara/samples/rest/management/ServerLogTest.java
nucleus/admin/template/src/main/resources/config/domain.xml
nucleus/grizzly/config/pom.xml
nucleus/packager/nucleus-grizzly/pom.xml
nucleus/pom.xml
pom.xml

Fixes QACI-406 - two TCK tests failed.
Current result:
```
real    103m6,578s
user    30m29,330s
sys     2m5,713s
Waiting for the domain to stop ..
Command stop-domain executed successfully.
Not passed: 0/745 /home/dmatej/work/repo/git/jakartaeetck-runner/cts_home/jakartaeetck-report/websocket/text/summary.txt
Writing stage file for websocket  into stage_websocket
```
* New Grizzly version: https://github.com/payara/patched-src-grizzly/pull/24
* New Grizzly binaries: https://github.com/payara/Payara_PatchedProjects/pull/327
* Related, but not blocking new NPN (we don't need it here): https://github.com/payara/patched-src-grizzly-npn/pull/4
* None
* TCK tests for websockets - two were failing, now all websockets TCK tests passed
* Complete Grizzly build, one test is still failing, in older …

QACI-406 fixed tck websockets

---

appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/domain.xml

The notifier update missed an old eventbus notifier tag in the micro domain.xml, which has now been updated to the new syntax.
This caused an error in the Payara Micro logs:
~~~
[2020-09-23T11:32:49.808+0000] [] [SEVERE] [] [] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1600860769808] [levelValue: 1000] [[
Ignoring unrecognized element eventbus-notifier at Line number = 105
Column number = 36
System Id = null
Public Id = null
Location Uri= null
CharacterOffset = 7338
]]
~~~

FISH-315 Fix Micro Domain.xml Error

---

nucleus/common/internal-api/src/main/java/fish/payara/internal/notification/NotifierUtils.java
nucleus/common/internal-api/src/test/java/fish/payara/internal/notification/CamelCaseConversionTest.java

Added testing for the camel casing function to make sure that notifier properties are calculated correctly the majority of the time. This is to ensure that notifier implementations don't see any unexpected results.
This PR wasn't necessary, but in implementing new notifiers I was getting anxiety at the sight of this method

FISH-315 Camel Case Testing

---

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/util/ResourceValidator.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/SystemTasksImpl.java

Manual tests, see Jira for reproducer

FISH-477 Deployment group properties are now resolved

---

pom.xml

This is a bug fix. This fixes the issue around JPA left join on embeddable types.
Patched Project PR: payara/Payara_PatchedProjects#336
Ran the reproducer in the Jira, before request fails and exception thrown, afterwards it works fine.
Zulu JDK 1.8_262 on Ubuntu 20.04 with Maven 3.6.3
Eclipselink code changes in https://github.com/payara/patched-src-eclipselink/commit/98f2160602ad3f6909eb4d650414f22225826765
This PR includes upgrade Eclipselink from 2.7.6 to 2.7.7

FISH-405 Use upgrade & patched eclipselink version

---

nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/HoggingThreadsHealthCheck.java
nucleus/payara-modules/healthcheck-stuck/src/main/java/fish/payara/nucleus/healthcheck/stuck/StuckThreadsHealthCheck.java

This is a tiny improvement that makes sure all of the Payara Health Checks define a Green state.
Start server, enable Payara health checks, open MC and navigate to RAG/Traffic Light Status page.
Check that both hogging and stuck threads are shown as green instead of white.

FISH-356 All Payara Health Checks Define Green State

---

api/payara-api/pom.xml
api/payara-bom/pom.xml
api/pom.xml
appserver/distributions/payara-ml/pom.xml
appserver/distributions/payara-web-ml/pom.xml
appserver/distributions/payara-web/pom.xml
appserver/distributions/payara/pom.xml
appserver/distributions/pom.xml
appserver/ejb/ejb-http-remoting/client/pom.xml
appserver/extras/embedded/all/pom.xml
appserver/extras/embedded/pom.xml
appserver/extras/embedded/web/pom.xml
appserver/extras/javaee/pom.xml
appserver/extras/payara-micro/payara-micro-distribution/pom.xml
appserver/extras/pom.xml
nucleus/distributions/pom.xml
nucleus/pom.xml
pom.xml

The new profile "deployinternals" can be used with the deploy goal to deploy to the new Nexus based payara-artifacts repository. Any JARs deployed to Maven central are excluded from this goal to prevent duplication. The exception is the Payara-API and Payara-BOM, as these may be dependencies of other artifacts.
Artifacts have been installed to https://nexus.payara.fish/repository/payara-artifacts/ with command:
~~~
mvn clean deploy -Pdeploy-internals
~~~
Run the deploy goal to a local directory:
~~~
mvn deploy -DaltDeploymentRepository=null::default::file:///home/matt/documents/local-repo/ -Dmaven.test.skip
~~~
Check the contents are as expected.
Run the same command but with the new profile:
~~~
mvn deploy -Pdeploy-internals -DaltDeploymentRepository=null::default::file:///home/matt/docum …

FISH-326 Add Profile to Deploy Internal JARs

---

appserver/payara-appserver-modules/jmx-monitoring-service/src/main/java/fish/payara/jmx/monitoring/JMXMonitoringService.java

Bug Fix related to a report during deployment that this method was not according to specifications.
Smoke test
Activated JMX Monitoring service and verified entries appears in the server.log
Zulu 8.48.0.51-CA-macosx (build 1.8.0_262-b19) on Mac 10.14.6 with Maven 3.5.4

FISH-509: Remove NamingException from PostConstruct method

---

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/InstanceHandler.java
nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/CollectionLeafResource.java
nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/xml/MiniXmlParser.java
nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/commands/ListJvmOptions.java

This applies both in the admin console and asadmin command.
Also allows for saving of JVM options with vendor info.
Run the `list-jvm-options` asadmin command and see that the vendor is listed
Go the the jvm options and add and edit a jvm option that has a vendor as part of the minimum JDK version.
Zulu JDK 1.8_262 on Ubuntu 20.04 with Maven 3.6.3

FISH-474 display vendor if specified in jvm-options

---

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBTimerService.java
appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/annotation/handlers/ScheduleHandler.java
appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastTimerStore.java

This is a bug fix. Fixes #4572 .
Use the example application provided with Jira. Start three Payara Micro instance with the app deployed. The timer should start on one of them. Then kill that instance. The timer should restart on one and only one other instance.
Zulu JDK 1.8_212 on Ubuntu 18.04 with Maven 3.6.3
The use of ILock is deprecated and removed in Hazelcast 4. #4762 contains the Hazelcast upgrade and that PR will need to be updated to take account of this one.

FISH-40 EJB timers with @Clustered will execute on one and only one instance

---

pom.xml

Title.
Use EclipseLink 2.7.7 without the fix for FISH-405

FISH-405 FISH-604 Revert for now

---

appserver/admingui/microprofile-console-plugin/src/main/resources/fish/payara/admingui/microprofile/Strings.properties
appserver/admingui/microprofile-console-plugin/src/main/resources/microprofile/microprofileConfigAPITabs.inc
appserver/admingui/microprofile-console-plugin/src/main/resources/microprofile/specs/configAPI/azureConfigSourceConfiguration.jsf
appserver/admingui/microprofile-console-plugin/src/main/resources/microprofile/specs/configAPI/gcpConfigSourceConfiguration.jsf
appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/azure/AzureSecretsConfigSource.java
appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/azure/AzureSecretsConfigSourceConfiguration.java
appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/azure/admin/GetAzureSecretsConfigSourceConfigurationCommand.java
appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/azure/admin/SetAzureSecretsConfigSourceConfigurationCommand.java
appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/azure/model/Attributes.java
appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/azure/model/Secret.java
appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/azure/model/SecretHolder.java
appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/azure/model/SecretsResponse.java
appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/gcp/GetGCPSecretsConfigSourceConfigurationCommand.java
appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/gcp/SetGCPSecretsConfigSourceConfigurationCommand.java

This is a feature, that allows you to fetch secrets from Azure Key Vault to be used as a config source for Payara.
TODO
Currently Azure supports two options for authentication to get an access code: password-based authentication and certidifcate-based authentication. I have decided to use the latter as it is the recommended way and it also means the user doesn't have to provide their password.

FISH-339  Create Azure Secrets Cloud Config Source

---

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebContainer.java
nucleus/common/internal-api/src/main/java/org/glassfish/internal/deployment/Deployment.java
nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/DisableCommand.java
nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/UndeployCommand.java

Improvement.
It was possible to get errors if an application endpoint was accessed during disable/undeployment. This improvement should help to alleviate these by marking the context for an application as unavailable (returning an 503 error when accessed) during the disable process while it is being unloaded and cleared away.
There is possibly a race condition present here due to processing the new _Disable_Start_ event asynchronously, but from all investigations and testing it's not possible for anything bad to happen. If the web container disables the context first, that's the goal we're aiming for and everything is bon. If the app engine and its modules are torn down before the context can be disabled (this _should_ be slower), then it either does nothing or simply logs a message at …

FISH-152 Mark Applications as Unavailable as soon as they are Disabled

---

nucleus/security/services/src/main/java/org/glassfish/security/services/common/SecurityAccessValidator.java

Reverts a long-ago workaround for something that was fixed in hk2 since.
Using the reproducer app in the Jira, deploy to Payara then curl endpoint, and check logs for any JACC warnings.
Start request-tracing in the admin console and click around to check nothing broken in the notification service.
Zulu JDK 1.8_262 on Ubuntu 18.04 with Maven 3.6.3
HK2 issue that this code was commented out for is eclipse-ee4j/glassfish-hk2#167 which was fixed by  eclipse-ee4j/glassfish-hk2@1ac109a9fd2281bb583db2eb6f14ceeafe6bae97
This is the community PR for payara/Payara-Enterprise#226

FISH-429 Lookup calling class when properly when doing a security check

---

Jenkinsfile

We now have a feature in the build to renew expired certs when the product is being built which makes this stage redundant and will only cause issues with PR testing - thus I am reverting it

Revert Unstable on Expired Certs

---

pom.xml

Fixes CVE-2020-10693
Signed-off-by: Andrew Pielage <andrew.pielage@payara.fish>

FISH-731 Update Hibernate validator to 6.1.5

---

appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/jmx/MBeanMetadata.java
appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/jmx/XmlTag.java

When MP metric registration from metrics.xml fails, the log should give a meaningful message of what went wrong.
Ran the reproducer.
Zulu 8.48.0.51-CA-macosx (build 1.8.0_262-b19) on Mac 10.14.6 with Maven 3.5.4

FISH-732: Define toString() of MBeanMetaData and XmlTag to have meaningful messages in server.log

---

appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/CSIV2TaggedComponentInfo.java
appserver/tests/payara-samples/samples/pom.xml
appserver/tests/payara-samples/samples/rolesallowed-unprotected-methods/pom.xml
appserver/tests/payara-samples/samples/rolesallowed-unprotected-methods/rolesallowed-unprotected-methods-client/pom.xml
appserver/tests/payara-samples/samples/rolesallowed-unprotected-methods/rolesallowed-unprotected-methods-client/src/test/java/fish/payara/samples/rolesallowed/unprotected/methods/RemoteEjbClientIT.java
appserver/tests/payara-samples/samples/rolesallowed-unprotected-methods/rolesallowed-unprotected-methods-common/pom.xml
appserver/tests/payara-samples/samples/rolesallowed-unprotected-methods/rolesallowed-unprotected-methods-common/src/main/java/fish/payara/samples/rolesallowed/unprotected/methods/HelloServiceLocal.java
appserver/tests/payara-samples/samples/rolesallowed-unprotected-methods/rolesallowed-unprotected-methods-common/src/main/java/fish/payara/samples/rolesallowed/unprotected/methods/HelloServiceRemote.java
appserver/tests/payara-samples/samples/rolesallowed-unprotected-methods/rolesallowed-unprotected-methods-common/src/main/java/fish/payara/samples/rolesallowed/unprotected/methods/ProtectedHelloServiceLocal.java
appserver/tests/payara-samples/samples/rolesallowed-unprotected-methods/rolesallowed-unprotected-methods-common/src/main/java/fish/payara/samples/rolesallowed/unprotected/methods/ProtectedHelloServiceRemote.java
appserver/tests/payara-samples/samples/rolesallowed-unprotected-methods/rolesallowed-unprotected-methods-server/pom.xml
appserver/tests/payara-samples/samples/rolesallowed-unprotected-methods/rolesallowed-unprotected-methods-server/src/main/java/fish/payara/samples/rolesallowed/unprotected/methods/HelloServiceBean.java
appserver/tests/payara-samples/samples/rolesallowed-unprotected-methods/rolesallowed-unprotected-methods-server/src/main/java/fish/payara/samples/rolesallowed/unprotected/methods/HelloServlet.java
appserver/tests/payara-samples/samples/rolesallowed-unprotected-methods/rolesallowed-unprotected-methods-server/src/main/java/fish/payara/samples/rolesallowed/unprotected/methods/ProtectedHelloServiceBean.java
appserver/tests/payara-samples/samples/rolesallowed-unprotected-methods/rolesallowed-unprotected-methods-server/src/test/java/fish/payara/samples/rolesallowed/unprotected/methods/HelloServletIT.java

Without authorisation being passed, an EJB client would fail to perform a lookup on an EJB if it had a @RolesAllowed annotation if no IOR descriptor and no authentication were provided - it would default to requiring authentication to perform a lookup if any checked method permissions were detected. If the EJB had methods annotated with PermitAll however, this would prevent you from accessing these methods without providing authentication since you could not perform the initial context lookup.
This should ideally be run through the JakartaEE TCK before being merged, due to the security implication of me cracking the door open slightly. 
None
None
Added some new tests and ran some small bits of the Jakarta TCK and Java EE7 Samples.
Added a new sample to payara-samples, which only runs if …

FISH-206 @RolesAllowed annotation in method prevents unauthenticated calls to other methods in remote EJB

---

appserver/admingui/microprofile-console-plugin/src/main/resources/microprofile/specs/configAPI/azureConfigSourceConfiguration.jsf
appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/azure/admin/GetAzureSecretsConfigSourceConfigurationCommand.java

This PR fixes an issue where you could not use the admin console to configure Azure config source configuration.

FISH-747 Azure config source configuration on Admin console fails

---

Jenkinsfile

This is a testing update
With the update to MP4.0 having the TCKs exist on a separate branch, testing for community needs to be updated to make use of this new branch so that tests pass
Depends on the merging of #4989 and PRs to the TCK 4.0 branch

[QACI-571] - Use microprofile-4.0 branch for testing

---

nucleus/deployment/common/src/main/java/org/glassfish/loader/util/ASClassLoaderUtil.java

Add explicit support for the "jardir" schema used by fileinstall for unpacked directories by translating it to to the "file" schema.  This allows unpacked WAB (and probably EJB bundles) installed via Felix FileInstall to be deployed successfully (barring other bugs)
Fixes: https://github.com/payara/Payara/issues/4415
This works because the path portion of the jardir: URL is the directory path.  The "jardir:" provides some additional features that don't appear to be needed during Java EE module deployment and it isn't supported for the NIO FileSystem API, which Payara uses during deployment.
None added
Tested this with the application under which we discovered this bug
None
OS: RedHat Linux 7
JDK: OpenJDK 8.0.201
Maven: 3.6.2
N/A
N/A

  FISH-761 Deployment of unpacked WAB fails when using Felix fileinstall

---

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/BaseContainer.java
nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/ASURLClassLoader.java

added ASURLClassLoader.mustLoadFrom() to indicate that DirWatcher should be disregarded due to race conditions
There is an inherent race condition between OS delivering filesystem changes to DirWatcher,
when classes are loaded right after the class files are created.
Ignore DirWatcher when classes are necessary for app to work
Fixes QuickLook stability
MacOS exposes this really well because it's a polling version of DirWatcher instead of pushing events

QACI-464 FISH-775 CmpRosterTest fails due to DirWatcher race dondition w/filesystem

---

appserver/appclient/client/acc/pom.xml

The jar file handling the Request Tracing for Remote EJB jar is not referenced from the Manifest file of gf_client.jar file.
So when using gf_client.jar, the class OpenTracingIiopInterceptorFactory.class is missing and thus Request Tracing will not work. (no issue with embedded_all.jar)
tested resulting gf_client.jazr
Zulu 8.48.0.51-CA-macosx (build 1.8.0_262-b19) on Mac 10.14.6 with Maven 3.5.4

FISH-767: reference ejb-opentracing.jar in manifest.mf of gf_client.jar.

---

appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/OpenTracingRequestEventListener.java

OpenAPI 1.3 spec conformance
Manual testing

FISH-777 Exclude OpenAPI rest endpoint from tracing

---

appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java
appserver/web/web-glue/src/main/java/com/sun/enterprise/security/web/GlassFishSingleSignOn.java

3 Servlet failures were caused by an 'unauthorized' error. This PR makes the following changes:
- Partially revert FISH-766. The community contribution is still present, but the changed functionality introduced by https://github.com/payara/Payara/pull/4479/commits/b298f292cd383ea3aab7ad244f0d4ce649a6a4e9#r456932973 is broken, so has been removed.
- Totally revert https://github.com/payara/Payara/pull/4610. The issue will need reopening and readdressing, but in a way that still passes the TCK. Unfortunately, this community contribution will not be present in the release notes as it's been reverted.

FISH-867 Fix Servlet TCK Failures (Revert of FISH-779 and FISH-766)
