appserver/distributions/payara-web/pom.xml, appserver/distributions/payara-web/src/main/assembly/payara-web.xml, appserver/distributions/payara-web/src/main/assembly/web.xml, appserver/distributions/payara-web/src/test/java/org/glassfish/distributions/test/EmbeddedTest.java, appserver/distributions/payara-web/src/test/java/org/glassfish/distributions/test/UnitTest.java, appserver/distributions/payara-web/src/test/java/org/glassfish/distributions/test/ejb/SampleEjb.java, appserver/distributions/payara-web/src/test/java/org/glassfish/distributions/test/web/WebHello.java, appserver/distributions/payara-web/web-distributions.xml, appserver/distributions/pom.xml, appserver/featuresets/payara-web/pom.xml
Created payara-web distribution, and disabled minnow, glassfish-web, and glassfish-full distributions
=> Add payara-web distribution

appserver/pom.xml, appserver/tests/quicklook/wsit/JaxwsFromWsdl/build.properties, appserver/tests/quicklook/wsit/jaxbosgi/build.xml, appserver/tests/quicklook/wsit/jaxbosgi/src/java/jaxb1/impl/runtime/DefaultJAXBContextImpl.java, appserver/tests/quicklook/wsit/jaxbosgi/src/java/jaxb1/impl/runtime/GrammarInfoFacade.java, appserver/tests/quicklook/wsit/jaxbosgi/src/java/jaxb1/impl/runtime/GrammarInfoImpl.java, appserver/tests/quicklook/wsit/jaxbosgi/src/java/jaxb1/impl/runtime/Messages.java, appserver/tests/quicklook/wsit/jaxbosgi/src/java/jaxb1/impl/runtime/Messages.properties, appserver/tests/quicklook/wsit/jaxbosgi/src/java/jaxb1/impl/runtime/Util.java, appserver/web/web-ha/src/main/java/org/glassfish/web/ha/authenticator/HASingleSignOn.java, appserver/web/web-ha/src/main/java/org/glassfish/web/ha/authenticator/HASingleSignOnEntry.java, common.sh, nucleus/admin/config-api/src/test/java/com/sun/enterprise/configapi/tests/DirectCreationTest.java, nucleus/admin/config-api/src/test/java/com/sun/enterprise/configapi/tests/TransactionCallBackTest.java, nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/config/AMXConfigImpl.java, nucleus/grizzly/config/src/test/java/org/glassfish/grizzly/config/GrizzlyConfigTest.java, nucleus/packager/nucleus-hk2/pom.xml, nucleus/pom.xml
Cherry-Pick of commits from GlassFish upstream.
=> GlassFish Upstream Cherry-Pick 13/01/2015 - 15/01/2015

appserver/pom.xml
Upgrade Mojarra to the latest minor bug-fix release.
=> Upgrade Mojarra

appserver/pom.xml
=> Update mojarra version

nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/admin/SetHazelcastConfiguration.java
Removed the -p shortcut as it clashes with the shortcut for --port
Removed the -mp shortcut as it doesn't get recognised as a valid option
=> Removed broken and clashing shortcuts

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/SimpleEjbResourceHandlerImpl.java
Now checks whether the transaction state is suitable for registering for synchonisation events.
This prevents a spurious WARN message appearing when an attempt is made to register during completion of the transaction.
=> Remove spurious transaction warning in some circumstances

appserver/payara-admingui/payara-console-extras/src/main/resources/hazelcast/hazelcastConfigurationCluster.jsf, appserver/payara-admingui/payara-console-extras/src/main/resources/hazelcast/hazelcastConfigurationServer.jsf, appserver/payara-admingui/payara-console-extras/src/main/resources/hazelcast/hazelcastConfigurationStandalone.jsf, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/admin/SetHazelcastConfiguration.java
=> validate the parameters before storing

appserver/batch/glassfish-batch-commands/src/main/java/org/glassfish/batch/SetBatchRuntimeConfiguration.java
Removed short names for suffix and prefix parameters until we decide what they are.
Fixes #176
=> Fixed #176

appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/EjbServicesImpl.java
=> FIX GLASSFISH-21125

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBContainerTransactionManager.java, appserver/packager/jersey/pom.xml, appserver/packager/resources/pkg_conf.py, appserver/pom.xml, appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/EventSemaphore.java, appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/RecoveryManager.java, nucleus/pom.xml
Cherrypick of glassfish upstream.
=> GlassFish upstream cherry pick 29-01-2015

appserver/extras/embedded/all/pom.xml, appserver/extras/embedded/nucleus/pom.xml, appserver/extras/embedded/web/pom.xml
Changed artifact IDs to differentiate from glassfish embedded artifacts
=> Changed embedded artifact IDs from glassfish to payara

appserver/pom.xml, nucleus/pom.xml
=> Revert Metro 2.3.1 to fix 218 

nucleus/pom.xml
=> Upgrade Hazelcast to 3.4.2

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBContainerTransactionManager.java, appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/RecoveryManager.java, appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/TransactionFactoryImpl.java
Fix #244 and revert to conform with default JTS timeout on GlassFish 4.1 by adding in a system property to the Recovery Manager for the timeout.
=> Fix #244 ( PAYARA-138 )

appserver/pom.xml
=> Upgrade Weld

nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java
=> Incorporate patch for GLASSFISH-21343

nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateCommandDeleteResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateCommandGetResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateCommandPostResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateExecCommand.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateListOfResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateRestResource.java
Fixes error and keeps original weighting.
Only removes weighting from @Produces annotations with only 1 media type, which seems to be what causes error.
=> Issue #269

nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/CollectionLeafResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/LeafResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/MonitoringResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/PropertiesBagResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/SessionsResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateCommandDeleteResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateCommandGetResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateCommandPostResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateExecCommand.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateListOfResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateRestResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/custom/FindHttpProtocolResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/custom/JmxServiceUrlsResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/custom/ManagementProxyResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/custom/SetDomainConfigResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/custom/SystemPropertiesCliResource.java
=> Fix Issue 275

nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/CollectionLeafResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/LeafResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/MonitoringResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/PropertiesBagResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/SessionsResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateCommandDeleteResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateCommandGetResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateCommandPostResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateExecCommand.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateListOfResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateRestResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/custom/FindHttpProtocolResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/custom/JmxServiceUrlsResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/custom/ManagementProxyResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/custom/SetDomainConfigResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/custom/SystemPropertiesCliResource.java
Cherry-pick fix for issue #275 into Payara 4.1.152
=> Patch Issue 275

nucleus/payara-modules/payara-micro/src/main/java/fish/payara/micro/PayaraMicro.java
Fixes #292 parameter bug on parsing alternateDomain.xml on Payara Micro
=> Fixes #292

appserver/security/core-ee/src/main/java/com/sun/enterprise/security/web/integration/WebPrincipal.java, appserver/web/web-core/src/main/java/org/apache/catalina/connector/RequestFacade.java
Proposed Fix for #290 needs security testing
=> Fixes #290 by ensuring the Facade uses the custom principal if available

appserver/packager/glassfish-ha/pom.xml, nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/LocalServerCommand.java, nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/pe/PEFileLayout.java, nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/ChangeNodeMasterPasswordCommand.java, nucleus/common/common-util/src/main/java/org/glassfish/server/ServerEnvironmentImpl.java
This pull request combines two earlier pull requests containing fixes for issues #330, #319, and #316 
Previous pull requests with some code review comments: #317, #320
=> Combined pull request for various issues

appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/CachePutInterceptor.java, appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/CacheRemoveAllInterceptor.java, appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/CacheResultInterceptor.java, nucleus/pom.xml
Removed requirement for PayaraValueHolder to get around Serialization
fixes #339
=> Upgraded Hazelcast to 3.5

appserver/batch/glassfish-batch-commands/pom.xml
Fixes #175 
Edited the POM to pull down the edited help pages artefact from our Payara_PatchedProjects repo.
=> Edited pom file to use our own help pages

nucleus/common/common-util/src/main/java/com/sun/enterprise/util/io/DomainDirs.java
Now if there are multiple domains and no domain is specified Payara will boot domain1 if it exists.
=> PAYARA-261 Fixes #349 

nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/SetLogAttributes.java
This updates the set-log-attributes command to add an additional command argument --validate=false to switch off validation of the attributes against an allowed set of keys.
This allows arbitrary key-values to be set in the logging.properties file
Fixes #321 
For example
```Shell
asadmin> set-log-attributes foo=bar
remote failure: Invalid logging attribute name or value foo=bar.
Command set-log-attributes failed
asadmin> set-log-attributes --validate=false foo=bar
foo logging attribute value set to bar.
The logging attributes are saved successfully for server.
Command set-log-attributes executed successfully.
```
=> PAYARA-260 Enable arbitrary keys in logging.properties

appserver/pom.xml
Tested with Primefaces showcase application
=> PAYARA-268 Upgraded Mojarra to the latest point release. 

appserver/admin/gf_template/src/main/resources/config/domain.xml, appserver/admin/payara_template/src/main/resources/config/domain.xml
Add hazelcast configuration section to default domain.xml
=> Fixes #373

appserver/packager/hazelcast-l10n/pom.xml
=> Add ${temp.dir} property to pom.xml

appserver/web/web-core/src/main/java/org/apache/catalina/connector/Request.java, appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardPipeline.java
Reworked changes for GLASSFISH-21007 which fixes #327 as well.
=> Fixes #327 and GLASSFISH-21007

appserver/tests/quicklook/bean-validator/simple-bv-servlet/build.xml, appserver/tests/quicklook/build.xml, appserver/tests/quicklook/gfproject/build-impl.xml, appserver/tests/quicklook/testng/testng_gd.xml, appserver/tests/quicklook/weld/extensions/build.xml, appserver/tests/quicklook/wsit/jaxbosgi/build.xml, appserver/tests/quicklook/wsit/jsr109tester/build.xml
New configuration in quicklook files (as tests were not building properly - some lines of code had to be commented out). This is also to incorporate into Jenkins build
=> new quicklook configuration

nucleus/pom.xml
Fixes #350 Upgrades Grizzly to 2.3.22
=> PAYARA-322 fixes #350 upgrades Grizzly to 2.3.22

nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/GenericGrizzlyListener.java, nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/dom/Http2.java, nucleus/grizzly/nucleus-grizzly-all/pom.xml, nucleus/payara-modules/payara-micro/src/main/java/fish/payara/micro/PayaraMicro.java
Also removes error in Grizzly boot due to incomplete HTTP2 support
=> PAYARA-416 Fixes #395

nucleus/payara-modules/payara-micro/src/main/java/fish/payara/micro/PayaraMicro.java
Move deployAll to after Runtime creation  so that injection of @PayaraMicroRuntime works
=> Fixes PAYARA-415

appserver/admin/gf_template/src/main/resources/config/domain.xml, appserver/admin/payara_template/src/main/resources/config/domain.xml, nucleus/payara-modules/payara-micro/src/main/resources/payara-boot.properties
as it doesn't work in a cluster or with passivated sessions
Fixes #300
=> Disabled Weld Bean Identifier Index optimisation 

nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/admin/ClearCache.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/admin/ListCacheKeys.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/admin/ListCaches.java
Adds some simple asadmin commands to list caches and clear a cache.
=> Payara 447 Add some simple asadmin commands

nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/DisableCommand.java
Modifies disable command to check the target is equal to the server executing the command. Also fixes #270
=> PAYARA-452 Fixes #433 versioned application can not be enabled on cluster instance

nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/SecureAdminPrincipal.java, nucleus/admin/config-api/src/main/java/org/glassfish/config/support/GenericCreateCommand.java
=> PAYARA-322 enable-secure-admin-principal adds principal multiple times

appserver/tests/quicklook/admincli/src/test/admincli/ExistStatusTests.java, appserver/tests/quicklook/admincli/testng.xml, appserver/tests/quicklook/adminconsole/src/test/admin/BaseAdminConsoleTest.java, appserver/tests/quicklook/amx/src/test/amx/AMXProxyTests.java, appserver/tests/quicklook/amx/src/test/amx/AMXTestBase.java, appserver/tests/quicklook/amx/testng.xml, appserver/tests/quicklook/build.properties, appserver/tests/quicklook/build.xml, appserver/tests/quicklook/ejb/mdb/src/test/mdb/MDBTests.java, appserver/tests/quicklook/gfproject/utils.xml, appserver/tests/quicklook/gfproject/v2-config.properties, appserver/tests/quicklook/gfproject/v3-config.properties, appserver/tests/quicklook/gfproject/v3-targets.xml, appserver/tests/quicklook/rest/src/test/admin/RestTests.java, appserver/tests/quicklook/rest/testng.xml, appserver/tests/quicklook/testng/testng_debug.xml, appserver/tests/quicklook/testng/testng_gd.xml, appserver/tests/quicklook/testng/testng_gd_security.xml, appserver/tests/quicklook/testng/testng_wd.xml, appserver/tests/quicklook/wsit/JaxwsFromWsdl/build.properties, appserver/tests/quicklook/wsit/jsr109tester/build.properties
Fixes #405 
Many of the tests are failing on my own and on Jenkins, I have disabled these for now, but they should be looked at and fixed later.
=> Update Quicklook files for Jenkins

appserver/admin/payara_template/src/main/resources/config/domain.xml, appserver/batch/glassfish-batch-connector/src/main/java/org/glassfish/batch/spi/impl/BatchRuntimeConfiguration.java
=> PAYARA-387 Make the default DerbyPool use Derby Embedded

appserver/admingui/jms-plugin/src/main/resources/jmsService.jsf, appserver/jms/admin/src/main/java/org/glassfish/jms/admin/cli/JMSPing.java, appserver/jms/gf-jms-connector/src/main/java/com/sun/enterprise/connectors/jms/config/JmsService.java, appserver/jms/jms-core/src/main/java/com/sun/enterprise/connectors/jms/system/ActiveJmsResourceAdapter.java, appserver/jms/jms-core/src/main/java/com/sun/enterprise/connectors/jms/system/JmsProviderLifecycle.java
This disables the OpenMQ Broker preventing bootstrap and fails fast the jmsra.rar from attempting to create connections to the broker
To fully disable the default connection factory and connection pools should also be deleted.
=> PAYARA-427 Allow DISABLED as a JMS Broker type. 

appserver/ejb/ejb-full-container/src/main/java/org/glassfish/ejb/mdb/deployment/annotation/handlers/MessageDrivenHandler.java
Add support for resourceAdapter activation config property. Fixes #440
=> Fixes #440

pom.xml
=> PAYARA-462 Fun edits

nucleus/common/common-util/src/main/java/org/glassfish/server/ServerEnvironmentImpl.java
=> PAYARA-459 Correct ${com.sun.aas.hostName}

nucleus/pom.xml
Pull in latest Jersey which incorporates our pull request to fix #377
=> PAYARA-393 upgrade Jersey to 2.22 fixes #377

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EjbContainerUtilImpl.java
=> PAYARA-405 fixes #415

nucleus/pom.xml
Ignore classNotFoundException when attempting to load class of type, if a loaded class is already held
Fixes #465
=> PAYARA-448: Update CORBA version to 4.0.1-p2

appserver/admingui/common/src/main/resources/commonTaskDoc.inc, appserver/admingui/core/src/main/resources/org/glassfish/admingui/core/Strings.properties
addition of wiki to docs in console
=> Payara 473

nucleus/common/common-util/pom.xml, nucleus/common/common-util/src/main/java/com/sun/common/util/logging/GFLogRecord.java, nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingOutputStream.java, nucleus/core/logging/pom.xml, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/GFFileHandler.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/ODLLogFormatter.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/UniformLogFormatter.java
=> PAYARA-406 Wrong thread name in server.log

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/VirtualServer.java, nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/xml/MiniXmlParser.java
=> PAYARA-376 Instance server log written to despite change of log file name

appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionalInterceptorBase.java, appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionalInterceptorMandatory.java, appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionalInterceptorNever.java, appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionalInterceptorNotSupported.java, appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionalInterceptorRequired.java, appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionalInterceptorRequiresNew.java, appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionalInterceptorSupports.java
INFO level log moved to FINE level.
=> PAYARA-477

appserver/packager/metro/pom.xml, appserver/pom.xml, appserver/security/webservices.security/pom.xml, appserver/webservices/jsr109-impl/pom.xml, appserver/webservices/metro-glue/pom.xml, appserver/webservices/soap-tcp/pom.xml, nucleus/pom.xml
=> PAYARA-492 Fix WSIT enabled WS services

appserver/pom.xml
Redo update to patched metro version.
=> PAYARA-446 Update metro version to patched version

appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/GlassFishORBManager.java
Remote JNDI lookups from standalone client results in ClassNotFoundException
Fixes #535
=> Fix problem with JNDI lookups from standalone client

nucleus/payara-modules/payara-micro/src/main/java/fish/payara/micro/PayaraMicro.java
=> Remove obsolete mechanism for configuring Hazelcast Multicast port

appserver/pom.xml, appserver/tests/quicklook/amx/src/test/amx/AMXProxyTests.java, appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java, nucleus/pom.xml
Merge in the changes from the GlassFish upstream.
=> GlassFish Upstream

appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/LazyBootPersistenceManager.java, appserver/batch/glassfish-batch-connector/src/main/java/org/glassfish/batch/spi/impl/BatchRuntimeHelper.java, nucleus/payara-modules/payara-micro/src/main/resources/microdomain-nocluster.xml, nucleus/payara-modules/payara-micro/src/main/resources/microdomain.xml
Tweaks to the config files and creation of a new JBatch lazy persistence manager which cuts Payara Micro boot times by 2 thirds
=> Speed up Payara Micro Boot Times PAYARA-527

appserver/connectors/connectors-runtime/osgi.bundle, nucleus/common/common-util/src/main/java/com/sun/logging/LogDomains.java
This is a first part resolving the issue (manually tested).
=> Payara issue 502.1

appserver/pom.xml
=> PAYARA-371: Update mq.version from 5.1.1-b02 to 5.1.1-b02.payara-p1

nucleus/payara-modules/payara-micro/src/main/java/fish/payara/micro/PayaraMicro.java
now .ear and .jar will also be deployed
Fixes #576
=> PAYARA-549 Removed check that file for deployment ends in .war 

nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/GFFileHandler.java
Fixes #500 
The original fix in #501 only worked for logs printed out to the console.
=> PAYARA-406

appserver/common/amx-javaee/src/main/java/org/glassfish/admin/amx/impl/j2ee/J2EEServerImpl.java
=> PAYARA-557 Add call to Version to get correct version string for the JMX attributes

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EjbContainerUtilImpl.java, nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingOutputStream.java, nucleus/common/common-util/src/main/java/org/glassfish/common/util/admin/ManagedFile.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/GFFileHandler.java
=> PAYARA-458 Enforce names on many raw threads

appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/LazyBootPersistenceManager.java, appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/SQLServerJDBCConstants.java, appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/SQLServerPersistenceManager.java
=> PAYARA-359 Add SQL Server support to JBatch

nucleus/payara-modules/payara-micro/src/main/java/fish/payara/micro/PayaraMicro.java, nucleus/payara-modules/payara-micro/src/main/java/fish/payara/micro/PayaraMicroRuntime.java
=> For Payara #588

nucleus/common/mbeanserver/src/main/java/org/glassfish/admin/mbeanserver/ssl/SSLClientConfigurator.java
Changed SunX509 to KeyManagerFactory.getDefaultAlgorithm()
=> PAYARA-568 fixes #596 #pr 

nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HealthCheckHoggingThreadsExecutionOptions.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HealthCheckTask.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/GetHealthCheckConfiguration.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HealthCheckServiceThresholdConfigurer.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/configuration/HoggingThreadsChecker.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/entity/ThreadTimes.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/BaseHealthCheck.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/BaseThresholdHealthCheck.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/CpuUsageHealthCheck.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/GarbageCollectorHealthCheck.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/HeapMemoryUsageHealthCheck.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/HoggingThreadsHealthCheck.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/MachineMemoryUsageHealthCheck.java
Since I needed HoggingThreadsChecker class with the admin command implementation, I created this branch out of the branch PAYARA-166-Thread-CPU-Usage-Hogging-Threads. 
Commits with id: b9e0f8d and 903ef4f can be omitted before merging the PR if PAYARA-166 PR gets merged before. You can cherry-pick 9789ed7 and 49eba0e afterwards.
=> Payara 586 create asadmin commands for the healthcheck service that display the current configuration

appserver/pom.xml
Fixes #426.
Relies upon https://github.com/payara/Payara_PatchedProjects/pull/12.
=> PAYARA-446 edit webservices version to use updated patch

nucleus/security/core/src/main/java/com/sun/enterprise/security/admin/cli/SecureAdminCommand.java
=> PAYARA-518

appserver/packager/appserver-base/src/main/docs/README.txt
=> PAYARA-600 Rewrite top-level README.txt for Payara

appserver/admingui/war/src/main/webapp/WEB-INF/sun-web.xml, appserver/pom.xml
Depends on https://github.com/payara/Payara_PatchedProjects/pull/19
Fixes exploit.
=> Update woodstock version

appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionalInterceptorBase.java, appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionalInterceptorRequiresNew.java
Fix rollback on exception for Transactional Annotation fixes #667
=> PAYARA-640 fixes #667

nucleus/osgi-platforms/felix/src/main/resources/config/osgi.properties
Removed reference to non-existent core.jar and other clan up to stop warnings
=> PAYARA-599 Remove Boot time OSGI warnings

nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/UndeployCommand.java
JarFileFactory keeps jar files open and it is difficult to ensure they are closed. Prior to cleaning up on undeployment force closure of all cached JarFiles to ensure the files are closed if they need deleting.
This may help with #680  #456 #445
=> PAYARA-665 force JarFileFactory to close all cached Jar Files 

appserver/batch/glassfish-batch-connector/pom.xml, appserver/packager/glassfish-jcdi/pom.xml, appserver/pom.xml, appserver/tests/hk2/cdi/jersey/war/pom.xml, appserver/web/web-sse/pom.xml, appserver/web/weld-integration-fragment/pom.xml, appserver/web/weld-integration/pom.xml
this one also contains the 3 commits from branch PAYARA-577-Get-Weld-2.3.x-working-on-Payara since weld 2.3.2 needs to be included first.
=> Payara 604 upgrade version of guava

nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java
=> Revert "Resolve com.sun.aas.instanceName in JVM arguments (PAYARA-660)"

nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java
=> Revert "Revert "Resolve com.sun.aas.instanceName in JVM arguments (PAYARA-660)""

nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/MulticastConfiguration.java, nucleus/payara-modules/payara-micro/src/main/java/fish/payara/micro/PayaraMicro.java, nucleus/payara-modules/payara-micro/src/main/java/fish/payara/micro/PayaraMicroRuntime.java
A command line option for payara micro to output an uber jar which includes all command line deployments and options so that when run again all deployments and command line options are preserved and packaged into the jar.
=> Payara 679 Uber Jar command line option

appserver/admingui/cluster/src/main/resources/cluster/clusterGeneral.jsf, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/RestartClusterCommand.java
Added an asadmin command to restart a cluster and added an admin console button. No l10n on the strings, though.
=> PAYARA-676 Restart cluster asadmin command

appserver/admingui/payara-console-extras/src/main/resources/fish/payara/admingui/extras/Strings.properties, appserver/admingui/payara-console-extras/src/main/resources/hazelcast/hazelcastConfigurationCluster.jsf, appserver/admingui/payara-console-extras/src/main/resources/hazelcast/hazelcastConfigurationServer.jsf, appserver/admingui/payara-console-extras/src/main/resources/hazelcast/hazelcastConfigurationStandalone.jsf, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastRuntimeConfiguration.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/MulticastConfiguration.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/admin/GetHazelcastConfiguration.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/admin/SetHazelcastConfiguration.java, nucleus/payara-modules/payara-micro/src/main/java/fish/payara/micro/PayaraMicro.java
Hazelcast Cluster Group Functionality enables users to set the cluster group name and cluster group password. these have to be identical for nodes to cluster.
=> Payara 687 Implement Hazelcast Cluster Group

appserver/admin/gf_template/src/main/resources/config/domain.xml, nucleus/admin/template/src/main/resources/config/domain.xml, nucleus/common/common-util/src/test/resources/clusters1.xml, nucleus/common/common-util/src/test/resources/manysysprops.xml
Use the `--nointeractive` mode rather than the current `--noshutdown -c noop=true`
=> changed gosh command in XML files

nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HealthCheckService.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HealthCheckConfigurer.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HealthCheckServiceConfigurer.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/BaseHealthCheck.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/ConnectionPoolHealthCheck.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/CpuUsageHealthCheck.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/GarbageCollectorHealthCheck.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/HeapMemoryUsageHealthCheck.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/HoggingThreadsHealthCheck.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/MachineMemoryUsageHealthCheck.java
=> setting values for the checker services dynamically is now working correctly

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/SystemTasksImpl.java, nucleus/payara-modules/payara-micro/src/main/java/fish/payara/micro/PayaraMicro.java, nucleus/payara-modules/payara-micro/src/main/resources/microdomain-nocluster.xml, nucleus/payara-modules/payara-micro/src/main/resources/microdomain.xml
=> PAYARA-693 fixes #729 do not override an existing system property

nucleus/common/glassfish-api/src/main/java/org/glassfish/api/jdbc/SQLTraceRecord.java
Link to  Glassfish JIRA https://java.net/jira/browse/GLASSFISH-21536
=> PAYARA-727 Fixed GLASSFISH-21536 possible NPE in SQLTraceRecord

nucleus/packager/nucleus/src/main/resources/config/asenv.bat, nucleus/packager/nucleus/src/main/resources/config/asenv.conf
changed warning note to explicitly approve the setting of user variables in asenv.conf or .bat
=> changed warning note in asenv.conf/asenv.bat

appserver/deployment/javaee-full/src/main/java/org/glassfish/javaee/full/deployment/EarLibClassLoader.java
Fixed a small issue with META-INF/services processing that may make the fix incompatible with previous versions in the default configuration under rare circumstances
=> Fixes for PAYARA-677

appserver/webservices/connector/src/main/java/org/glassfish/webservices/connector/annotation/handlers/HandlerChainHandler.java, appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/WebServiceEjbEndpointRegistry.java
…Jax-WS and EJB WS handling
Fixes PAYARA-382 and Issue #384
=> PAYARA-382 fix Jax-WS warnings and errors

appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/service/ConnectorConnectionPoolAdminServiceImpl.java
Fixed property substitution in some parts of redeployment code
=> Fixes PAYARA-682 and Issue #703

appserver/pom.xml
Generate correct Informix SQL when parsing Concat Operator
This pull request is dependent on https://github.com/payara/Payara_PatchedProjects/pull/30
Fixes #815
=> PAYARA-742 Use EclipseLink 2.6.2.payara-p2. 

appserver/web/war-util/src/main/java/org/glassfish/web/loader/ServletContainerInitializerUtil.java, appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModule.java, appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/JAXWSContainer.java
- Remove ClassLoading warnings when using multiple WARs in EAR
- Remove Jax-WS Module support warning
=> Fixes for Payara-355 and Isssue #374

appserver/packager/external/ant/pom.xml
really affected it keeps our security scan clean.
=> PAYARA-710 Upgraded ant version to resolve CVE-2012-2098 although not

nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/services/Constants.java, nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/services/LocalStrings.properties, nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/services/WindowsService.java
Now reads "Payara" instead of "GlassFish"
=> Changed the name suffix for the Windows service. (PAYARA-776)

appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/LazyBootPersistenceManager.java, appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/NullPersistenceManager.java
=> PAYARA-794 add extra diagnostic logs for when JBatch is configured with

nucleus/payara-modules/payara-micro/src/main/java/fish/payara/micro/PayaraMicro.java, nucleus/payara-modules/payara-micro/src/main/resources/payara-boot.properties
Ensure login.conf and server.policy are set in the system properties at boot.
Fixes #804
=> PAYARA-803 fixes #804 

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/LoggingHandlers.java, nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/DeleteLogLevel.java
=> PAYARA-724 Copyright and remove unused import

nucleus/pom.xml
=> Revert "PAYARA-713 Update hawtjndi version"

nucleus/pom.xml
Reverts payara/Payara#840
Needed to be tested.
=> Revert "Revert "PAYARA-713 Update hawtjndi version""

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebContainer.java
Plugged into DeploymentFailure event to de-register stale application references from the JNDI naming manager, was causing bad objects to be cached there
=> Fixes PAYARA-580 and Issue #315

appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
Fixes PAYARA-664 and Issue #693
=> PAYARA-664 - added a lock for jarFiles variable

appserver/packager/glassfish-web/pom.xml, appserver/pom.xml, appserver/security/pom.xml, nucleus/pom.xml
Incorporates the Soteria and javax.security-api JARs into Payara Server.
Given the lack of an easily accessible JAR for both, I shall upload my own builds to the Payara patched projects repository.
=> PAYARA-751 Incorporate Soteria

appserver/pom.xml
Default JoinFetch annotation to INNER and BatchFetch annotation to JOIN
This pull request is dependent on payara/Payara_PatchedProjects#32
Fixes #868
=>  PAYARA-821 Use EclipseLink 2.6.2.payara-p3. 

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/InterceptorDescriptor.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/interceptors/InterceptorManager.java, appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/impl/PayaraCacheKeyInvocationContext.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/EjbServicesImpl.java
=> PAYARA-826 ensure the interceptor class is reused if already loaded 

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/ResourceReferenceDescriptor.java
incorrectly-named data sources fail fast instead of defaulting
=> Fixes PAYARA-823 and Issue #843 

appserver/ejb/ejb-connector/src/main/java/org/glassfish/ejb/config/EjbTimerService.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBTimerService.java, appserver/extras/embedded/payara-micro/pom.xml, appserver/payara-appserver-modules/hazelcast-ejb-timer/pom.xml, appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HZTimer.java, appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastEJBTimerService.java, appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastTimerStore.java, appserver/payara-appserver-modules/pom.xml, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java, nucleus/payara-modules/payara-micro-service/src/main/java/fish/payara/micro/services/PayaraMicroInstance.java, nucleus/payara-modules/payara-micro/src/main/resources/microdomain.xml
A Hazelcast based EJB Timer store initially for Payara Micro only, although the module should work on full Payara Server Fixes #265
=> PAYARA-186 micro hazelcast ejbtimer

nucleus/packager/nucleus-cluster/pom.xml
j-interop-repackaged.jar inclusion in modules/ was commented out
=> Fix PAYARA-808

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/ApplicationHandlers.java, appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/AppUtil.java, appserver/admingui/common/src/main/resources/applications/appEdit.layout, appserver/admingui/common/src/main/resources/applications/targetListing.jsf, appserver/admingui/common/src/main/resources/applications/webDDEdit.jsf
Edit check for application resources to also search for resources in application modules.
=> PAYARA-683 Application scoped resources not showing for EAR modules in Admin Console

index.html
This is for github pages branch. Preview the added link here: https://ondrejm.github.io/Payara/
=> Added link to documentation git repo

nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/ConnectionPoolHealthCheck.java
Replaced ConnectorsUtil with ResourceUtil
=> PAYARA-854-Payara-Minimal-is-broken-due-to-missing-OSGi-requirements

appserver/security/core-ee/src/main/java/com/sun/enterprise/security/web/integration/WebSecurityManager.java
Code is now fetching correct (current) SecurityContext instead creating a new, invalid one
=> Fixes PAYARA-810

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBTimerService.java
This adds tracing of EJB timers by adding a start and end trace to the timer task
=> PAYARA-926 trace EJB timers

nucleus/pom.xml
=> PAYARA-930 upgrade mimepull to expected version for jersey

appserver/web/web-core/src/main/java/org/apache/catalina/fileupload/MultipartStream.java
Takes the fix from http://svn.apache.org/viewvc?view=revision&revision=1743742 and puts it into our code.
=> PAYARA-901 Incorporate fix for CVE-2016-3092

appserver/extras/embedded/build.xml, appserver/extras/payara-micro/payara-micro-distribution/build.xml
Fixes incorrect JBoss logging classed in payara micro and payara embedded
=> Payara 893

index.html
Preview of the changes available at https://ondrejm.github.io/Payara/
Fixes #942.
=> Added links to JCache API

index.html
According to discussion in PR #945
=> Renamed links

appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/JavaModuleNamingProxy.java, appserver/ejb/ejb-container/pom.xml, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/BaseContainer.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/InjectionServicesImpl.java
fixed a bug when injection value was checked against first available EJB, not the correct one
=> Fixes PAYARA-947 and github issue #668

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/BundleDescriptor.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/node/runtime/application/gf/ApplicationRuntimeNode.java, appserver/deployment/dtds/src/main/resources/glassfish/lib/dtds/glassfish-application_6_0-1.dtd, appserver/deployment/dtds/src/main/resources/glassfish/lib/dtds/glassfish-ejb-jar_3_1-1.dtd, appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/node/runtime/EjbBundleRuntimeNode.java, appserver/security/core-ee/pom.xml, appserver/security/core-ee/src/main/java/com/sun/enterprise/security/acl/RoleMapper.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModule.java
added property default-role-mapping in glassfish-web.xml
Fixes #906 and PAYARA-936
=> Add support for default pincipal->group mapping #906 and PAYARA-936

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/annotation/introspection/ConstantPoolInfo.java
=> PAYARA-1010 update ConstantPool info to match JDK7+

appserver/extras/embedded/web/pom.xml
Fixes #1054 
A 163.0.1 patch should be uploaded to Maven Central _Soon<sup>TM</sup>_.
=> Add request tracing package

appserver/web/weld-integration/src/main/java/org/glassfish/weld/DeploymentImpl.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/RootBeanDeploymentArchive.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java
Fixes PAYARA-955
added rolling update support for versioned application
=>  PAYARA-955 rolling upgrades for versioned apps

appserver/payara-appserver-modules/jmx-monitoring-service/src/main/java/fish/payara/jmx/monitoring/admin/EnableMonitoringServiceOnInstance.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/PEAccessLogValve.java, nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/AccessLog.java, nucleus/payara-modules/asadmin-recorder/src/main/java/fish/payara/asadmin/recorder/AsadminRecorderConfiguration.java, nucleus/payara-modules/asadmin-recorder/src/main/java/fish/payara/asadmin/recorder/AsadminRecorderService.java, nucleus/payara-modules/asadmin-recorder/src/main/java/fish/payara/asadmin/recorder/admin/AsadminRecorderEnabled.java, nucleus/payara-modules/asadmin-recorder/src/main/java/fish/payara/asadmin/recorder/admin/DisableAsadminRecorder.java, nucleus/payara-modules/asadmin-recorder/src/main/java/fish/payara/asadmin/recorder/admin/EnableAsadminRecorder.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HealthCheckService.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HealthCheckConfigurer.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HealthCheckServiceConfigurer.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HealthCheckServiceThresholdConfigurer.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/configuration/Checker.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/configuration/HealthCheckServiceConfiguration.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/configuration/HoggingThreadsChecker.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/BaseHealthCheck.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/BaseThresholdHealthCheck.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/ConnectionPoolHealthCheck.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/HoggingThreadsHealthCheck.java, nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/NotificationService.java, nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/configuration/NotificationServiceConfiguration.java, nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/configuration/Notifier.java, nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/configuration/NotifierConfiguration.java, nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/domain/execoptions/NotifierConfigurationExecutionOptionsFactory.java, nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/RequestTracingService.java, nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/admin/GetRequestTracingConfiguration.java, nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/admin/RequestTracingNotifierConfigurer.java, nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/configuration/RequestTracingServiceConfiguration.java, nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/domain/execoptions/NotifierExecutionOptionsFactory.java
Converts method types to Strings, and add in parsing conversions where necessary.
Also includes some cleanup of unused imports, and some extra input validation.
=> PAYARA-935 Fix "Illegal non-string type" for request tracing, notification, healthcheck, and asadmin recorder services

nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/admin/GetNotificationConfiguration.java
=> PAYARA-1034 Fix NPE

appserver/concurrent/concurrent-impl/pom.xml, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java
Adds in a request tracing event to the concurrent context setup.
Traces ThreadName, Class Name, Module Name, Component ID, and App Name.
=> PAYARA-182 Add request tracing for ManagedExecutorService and ManagedScheduledExecutorService

appserver/ejb/ejb-full-container/pom.xml, appserver/ejb/ejb-full-container/src/main/java/org/glassfish/ejb/mdb/MessageBeanListenerImpl.java, nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/RequestEventStore.java, nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/RequestTrace.java, nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/RequestTracingService.java, nucleus/payara-modules/requesttracing-core/src/test/java/fish/payara/nucleus/requesttracing/RequestEventStoreTest.java
Also add additional apis for request tracing to view and set the conversation ID
=> PAYARA-179 implement request tracing for inbound JMS messages on an MDB

nucleus/pom.xml
=> PAYARA-993 Upgrade Grizzly

nucleus/core/logging/pom.xml, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/ExcludeFieldsSupport.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogEventImpl.java, nucleus/core/logging/src/main/java/fish/payara/enterprise/server/logging/JSONLogFormatter.java
Initial version for a JSON Log Formatter.
Stick with the JSONObjectBuilder or no?
=> PAYARA-733 Add capability to output logs in JSON format

appserver/transaction/jta/pom.xml, appserver/transaction/jta/src/main/java/com/sun/enterprise/transaction/JavaEETransactionManagerSimplified.java
Adds in request tracing for the start and end of transactions (JTA).
=> PAYARA-756 Request tracing for JTA

appserver/batch/glassfish-batch-connector/pom.xml, appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/JBatchJDBCPersistenceManager.java
Creates a request tracing event whenever a job execution is created.
=> PAYARA-181 Add in request tracing for JBatch

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/LoggingHandlers.java, appserver/admingui/common/src/main/resources/configuration/loggerGeneral.jsf, appserver/admingui/common/src/main/resources/org/glassfish/common/admingui/Strings.properties, nucleus/admin/launcher/src/test/resources/domains/domain1/config/logging.properties, nucleus/admin/launcher/src/test/resources/domains/domain2/config/logging.properties, nucleus/admin/launcher/src/test/resources/domains/domain3/config/logging.properties, nucleus/admin/launcher/src/test/resources/domains/domainNoLog/config/logging.properties, nucleus/admin/template/src/main/resources/config/logging.properties, nucleus/core/logging/pom.xml, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/GFFileHandler.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogFormatHelper.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/SetLogAttributes.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/logviewer/backend/LogFile.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/parser/LogParserFactory.java
and update log viewer to handle compressed logs
=> Payara-923 Add log compression on rotation option

appserver/extras/payara-micro/payara-micro-distribution/pom.xml, nucleus/packager/nucleus-jersey/pom.xml
=> PAYARA-1081 add Jackson JAXB Annotations Module

nucleus/packager/nucleus/src/main/resources/lib/install/templates/Domain-service-winsw.xml.template, nucleus/packager/nucleus/src/main/resources/lib/install/templates/linux-service.template
+ corrected a comment in the Linux Service template
=> PAYARA-954 changed the description of the Windows service 

appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/CacheResultInterceptor.java
=> Remove unused variable

appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardWrapper.java
suppress Apache Jasper logging severe when a JSP file is not found, w…hich is a common occurence in production web sites
Also may apply, or at least make #585 less confusing
=> PAYARA-1008 remove nuisance PWC6117 errors

nucleus/core/logging/pom.xml
=> Fix manpage version

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/StatelessSessionContainer.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/util/pool/AbstractPool.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/util/pool/BlockingPool.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/util/pool/NonBlockingPool.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/util/pool/Pool.java
- removed duplication of code from AbstractPool
- added BlockingPool for limiting resource consumption of @Stateless beans
- refactored and upgraded code base for Java 7 syntax
Fixes #646
=> PAYARA-1065 re-introduce blocking stateless bean pool

appserver/pom.xml
Upgrade Weld version to 2.4.1.Final
=> PAYARA-1204

nucleus/payara-modules/requesttracing-core/src/test/java/fish/payara/nucleus/requesttracing/RequestEventStoreTest.java
threshold from 100 to 95 to handle vm time variations
=> PAYARA-1207 Reduce RequestEvent test testFlushMultipleThreads 

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/BundleDescriptor.java, appserver/packager/glassfish-web/pom.xml, appserver/payara-appserver-modules/jaspic-servlet-utils/pom.xml, appserver/payara-appserver-modules/jaspic-servlet-utils/src/main/java/fish/payara/security/jaspic/JASPICWebListenerHelper.java, appserver/payara-appserver-modules/jaspic-servlet-utils/src/main/java/fish/payara/security/jaspic/SimpleSAMAuthConfigProvider.java, appserver/payara-appserver-modules/jaspic-servlet-utils/src/main/java/fish/payara/security/jaspic/SimpleSAMAuthContext.java, appserver/payara-appserver-modules/jaspic-servlet-utils/src/main/java/fish/payara/security/jaspic/SimpleSAMConfig.java, appserver/payara-appserver-modules/pom.xml, appserver/security/core-ee/src/main/java/com/sun/enterprise/security/acl/RoleMapper.java
Add utility classes to enable simple registration of a custom Server Auth Module
=> PAYARA-822 JASPIC utilities

nucleus/common/mbeanserver/src/main/java/org/glassfish/admin/mbeanserver/JMXMPConnectorStarter.java
restrict acceptable JMX credential types to reflect  CVE-2016-3427
=> PAYARA-1214 restrict acceptable JMX credential types

pom.xml
Change of maven project name form GF to Payara
=> Change of maven project name form GF to Payara

nucleus/pom.xml
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22jline%22%20AND%20a%3A%22jline%22
=> PAYARA-1260 upgraded jline to 2.14.2 which is the latest stable version

appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/archivist/WebArchivist.java, appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/descriptor/WebBundleDescriptorImpl.java, appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/descriptor/WebComponentDescriptorStub.java, appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/node/WebCommonNode.java
correct behavior when overriding servlet-mapping from web-fragments in web.xml
fixes issue #936
=> PAYARA-1007 fixes overrides in web.xml

appserver/admingui/web/src/main/resources/configuration/accessLog.jsf
fixed bug where it was impossible to turn off access logging to console via admin interface
=> PAYARA-1259 fixed access logging admin console interface

appserver/ha/ha-hazelcast-store/src/main/java/fish/payara/ha/hazelcast/store/HazelcastBackingStore.java, appserver/ha/ha-hazelcast-store/src/main/java/fish/payara/ha/hazelcast/store/HazelcastBackingStoreFactory.java, appserver/web/web-core/src/main/java/org/apache/catalina/session/PersistentManagerBase.java, appserver/web/web-ha/src/main/java/org/glassfish/web/ha/session/management/BaseHASession.java, appserver/web/web-ha/src/main/java/org/glassfish/web/ha/session/management/HANonStorableSession.java, appserver/web/web-ha/src/main/java/org/glassfish/web/ha/session/management/ReplicationStore.java, appserver/web/web-ha/src/main/java/org/glassfish/web/ha/session/management/ReplicationWebEventPersistentManager.java
Fixed issues with Hz session store
=> PAYARA-995 distributable Hz session store fixes

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/BasePersistenceStrategyBuilder.java, appserver/web/web-ha/src/main/java/org/glassfish/web/ha/session/management/ReplicationManagerBase.java
setting relaxCacheVersionSemantics true by default
=> PAYARA-1276 relaxCacheVersionSemantics set to true by default

appserver/web/web-ha/src/main/java/org/glassfish/web/ha/authenticator/HASSOFactory.java
getting PersistenceType from server configuration
Fixes issue #242
=> PAYARA-1060 SSO persistence type

appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/BaseSeleniumTestClass.java, appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/deployment/annotation/handlers/AdministeredObjectDefinitionsHandler.java, appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/deployment/annotation/handlers/ConnectionFactoryDefinitionsHandler.java, appserver/grizzly/glassfish-grizzly-extra-all/src/main/java/org/glassfish/grizzly/extras/addons/AjpAddOnProvider.java, appserver/jdbc/jdbc-runtime/src/main/java/org/glassfish/jdbcruntime/deployment/annotation/handlers/DataSourceDefinitionsHandler.java, appserver/jms/jms-core/src/main/java/com/sun/enterprise/connectors/jms/deployment/annotation/handlers/JMSConnectionFactoryDefinitionsHandler.java, appserver/jms/jms-core/src/main/java/com/sun/enterprise/connectors/jms/deployment/annotation/handlers/JMSDestinationDefinitionsHandler.java, appserver/resources/javamail/javamail-runtime/src/main/java/org/glassfish/resources/javamail/annotation/handler/MailSessionDefinitionsHandler.java, appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java, appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/SingleSignOn.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/security/web/GlassFishSingleSignOn.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/EmbeddedWebContainer.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/PEAccessLogValve.java, appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/annotation/handlers/WebFilterHandler.java, appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/annotation/handlers/WebServletHandler.java, appserver/web/web-glue/src/main/resources/org/glassfish/web/deployment/annotation/handlers/LocalStrings.properties, appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/LogUtils.java, nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/util/ConfigApiLoggerInfo.java, nucleus/admin/config-api/src/main/java/org/glassfish/config/support/LogStrings.properties, nucleus/core/kernel/src/main/java/org/glassfish/kernel/KernelLoggerInfo.java
fixed single quote escapes
fixes issue #1122
=> PAYARA-1115 log messages single quote escaped

appserver/web/web-glue/src/main/java/org/glassfish/web/jsp/JSPCompiler.java
=> Payara 1264 Jsp precompiling during deployment ignores settings in glassfish web xml

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/io/DeploymentDescriptorFile.java, appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/SecuritySniffer.java, nucleus/common/internal-api/src/main/java/org/glassfish/internal/deployment/GenericSniffer.java
Fixes #1070 deployment errors when internet is off
Also, FIxed error: WEB9100: No WebSecurityManager found for context WebAppl…ication1/WebApplication1
as described here: https://java.net/jira/browse/GLASSFISH-21365
=> PAYARA-1277 deployment issues when internet is off or web.xml is missing in the cluster

appserver/deployment/javaee-core/src/main/java/org/glassfish/javaee/core/deployment/DolProvider.java
reset RoleMapper when application is redeployed
fixes #1115
=> PAYARA-1082 autodeploy security issues

appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/GlobalTID.java
disregard branch qualifier in hashCode as pointed out by GLASSFISH-21532
=> PAYARA-737 fix GlobalTID.hashCode()

nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/PropertiesBagResource.java
fixes other property processing, besides system properties
i.e. "additional properties" and JDBC properties
=> PAYARA-934 fix other additional properties behavior besides system properties

appserver/admingui/payara-console-extras/src/main/java/fish/payara/admingui/extras/rest/PayaraRestApiHandlers.java, appserver/admingui/payara-console-extras/src/main/resources/hazelcast/microInstancesTable.inc, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/PayaraMicro.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/util/NameGenerator.java, appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/micro/services/PayaraInstance.java, appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/micro/services/asadmin/ListHazelcastClusterMembersCommand.java, appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/micro/services/asadmin/SendAsadminCommand.java, appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/micro/services/data/InstanceDescriptor.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/events/HazelcastEvents.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/MulticastConfiguration.java
Allows you to send asadmin commands to Micro instances from the DAS, using either an asadmin command or the admin console.
=> PAYARA-1157 Send asadmin commands to Micro instances from the DAS + Admin console Integration

nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java
fixed problems with classloading and serialization for Hazlecast due to OSGi restrictions
=> PAYARA-1146 Hazelcast serialization

nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/HistoricRequestEventStore.java
added null check for hazelcast map
=> PAYARA-1122-Store-a-number-of-historical-traces-in-memory-for-future-reporting

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/PayaraMicro.java
=> PAYARA-1321 Change Payara Micro deployment message.

appserver/payara-appserver-modules/notification-jms-core/src/main/java/fish/payara/notification/jms/JmsNotifierService.java
removed commented-out code snippets
=> PAYARA-700-Create-JMS-Notifier

nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HealthCheckService.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HistoricHealthCheckEvent.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HistoricHealthCheckEventStore.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HistoricHealthCheckEventRetriever.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/configuration/HealthCheckServiceConfiguration.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/BaseHealthCheck.java, nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/domain/BoundedTreeSet.java
=> PAYARA-1125 - Healthcheck service should store a number of historical measurements

appserver/pom.xml
Relies upon https://github.com/payara/Payara_PatchedProjects/pull/44
=> PAYARA-1230 Update EclipseLink to 2.6.4.payara-p1

appserver/web/admin/src/main/java/org/glassfish/web/admin/monitor/HttpServiceStatsProvider.java, nucleus/core/kernel/osgi.bundle
Fix for negative values return from following command :
````./asadmin get -m server.http-service.<virtual-server>.request.countopenconnections-count````
=> PAYARA-1176 Negative values for countopenconnections

appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/ConnectorXAResource.java, appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/PoolManagerImpl.java, appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/rm/LazyEnlistableResourceManagerImpl.java, appserver/connectors/connectors-runtime/src/main/resources/com/sun/enterprise/LogStrings.properties
=> Revert "PAYARA-769 Make resetAssociation() more robust" - belongs in master

appserver/payara-appserver-modules/notification-email-core/src/main/java/fish/payara/notification/email/EmailNotificationConfigurer.java, appserver/payara-appserver-modules/notification-email-core/src/main/java/fish/payara/notification/email/EmailNotifierService.java, appserver/payara-appserver-modules/notification-eventbus-core/src/main/java/fish/payara/notification/eventbus/EventbusNotificationConfigurer.java, appserver/payara-appserver-modules/notification-eventbus-core/src/main/java/fish/payara/notification/eventbus/EventbusNotifierService.java, appserver/payara-appserver-modules/notification-hipchat-core/src/main/java/fish/payara/notification/hipchat/HipchatNotificationConfigurer.java, appserver/payara-appserver-modules/notification-hipchat-core/src/main/java/fish/payara/notification/hipchat/HipchatNotifierService.java, appserver/payara-appserver-modules/notification-jms-core/src/main/java/fish/payara/notification/jms/JmsNotificationConfigurer.java, appserver/payara-appserver-modules/notification-jms-core/src/main/java/fish/payara/notification/jms/JmsNotifierService.java, appserver/payara-appserver-modules/notification-slack-core/src/main/java/fish/payara/notification/slack/SlackNotificationConfigurer.java, appserver/payara-appserver-modules/notification-slack-core/src/main/java/fish/payara/notification/slack/SlackNotifierService.java, appserver/payara-appserver-modules/notification-snmp-core/src/main/java/fish/payara/notification/snmp/SnmpNotificationConfigurer.java, appserver/payara-appserver-modules/notification-snmp-core/src/main/java/fish/payara/notification/snmp/SnmpNotifierService.java, appserver/payara-appserver-modules/notification-xmpp-core/src/main/java/fish/payara/notification/xmpp/XmppNotificationConfigurer.java, appserver/payara-appserver-modules/notification-xmpp-core/src/main/java/fish/payara/notification/xmpp/XmppNotifierService.java, nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/NotificationService.java, nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/admin/BaseNotificationConfigurer.java, nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/admin/GetNotificationConfiguration.java, nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/admin/NotificationConfigurer.java, nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/admin/NotificationNotifierConfigurer.java, nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/admin/SetNotificationConfiguration.java, nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/domain/NotificationExecutionOptions.java, nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/log/LogNotificationConfigurer.java, nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/log/LogNotifierService.java, nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/service/BaseNotifierService.java, nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/service/QueueBasedNotifierService.java, nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/admin/GetRequestTracingConfiguration.java, nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/admin/HistoricRequestEventRetriever.java, nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/admin/RequestTracingConfigurer.java, nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/admin/RequestTracingNotifierConfigurer.java, nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/admin/SetRequestTracingConfiguration.java
also contains asadmin commands for email, eventbus, hipchat, log, jms and xmpp notifiers
=> PAYARA-1265-Create-asadmin-command-for-Slack-notifier

appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/RegisteredSyncs.java, appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/TopCoordinator.java
added java.util.concurrent locks in order to resolve deadlock when callbacks are called from within synchornized methods
=> PAYARA-1114 distributed deadlock in JTA

appserver/transaction/jts/src/test/java/com/sun/enterprise/transaction/jts/AppTest.java
TestSuite for Pull Request https://github.com/payara/Payara/pull/1146 distributed deadlock in JTA
=> PAYARA-1114 distributed deadlock in JTA - TestSuite (PR-1146)

nucleus/pom.xml
aligning with asm version bundled with HK2
=> PAYARA-1336-Upgrade-asm-commons-to-5.0.3

appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastTimerStore.java
=> Fix ConcurrentModificationException in HazelcastTimerStore

appserver/admingui/eventbus-notifier-console-plugin/src/main/resources/eventbus/eventbusNotifierConfiguration.jsf, appserver/admingui/hipchat-notifier-console-plugin/src/main/resources/hipchat/hipchatNotifierConfiguration.jsf, appserver/admingui/payara-console-extras/src/main/resources/fish/payara/admingui/extras/Strings.properties, appserver/admingui/payara-console-extras/src/main/resources/notification/notification.jsf, appserver/admingui/slack-notifier-console-plugin/src/main/resources/slack/slackNotifierConfiguration.jsf, nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/log/GetLogNotifierConfiguration.java
Also adds in a 'dynamic' checkbox for the HipChat, Slack, and Eventbus notifiers.
=> PAYARA-1327 Admin console integration for log notifier

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/boot/runtime/MicroGlassFishRuntime.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/RuntimeDirectory.java
=> Payara 1372

appserver/web/web-ha/src/main/java/org/glassfish/web/ha/session/management/ReplicationStore.java
fixed NPE when backing store is not initialized
=> PAYARA-1380 NPE session replication fix

appserver/payara-appserver-modules/notification-hipchat-core/src/main/java/fish/payara/notification/hipchat/HipchatNotifierService.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HealthCheckService.java, nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/NotificationService.java, nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/RequestTracingService.java
-Services-that-implement-ConfigListener-should-return-null-on-the-configurations-that-they-are-interested
=> PAYARA-1379

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModule.java
Null Pointer check on Web Bundle Descriptor
=> PAYARA-1396 fixes #1310

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java
Prevent NullPointerException which is hiding a legitimate error fixes #1193
=> PAYARA-1234 

appserver/jms/jms-core/src/main/java/com/sun/enterprise/connectors/jms/system/ActiveJmsResourceAdapter.java
Now using ORB/EJB host for default JMS connection address
=> PAYARA-1185 Application Client JMS connectivity

nucleus/payara-modules/asadmin-recorder/src/main/java/fish/payara/asadmin/recorder/AsadminRecorderService.java
Have the asadmin recorder service create its domain.xml entry on startup to help negate errors upon migration.
=> PAYARA-1430 Asadmin recorder migration improvement

appserver/admingui/email-notifier-console-plugin/src/main/resources/email/emailNotifierConfiguration.jsf, appserver/admingui/eventbus-notifier-console-plugin/src/main/resources/eventbus/eventbusNotifierConfiguration.jsf, appserver/admingui/hipchat-notifier-console-plugin/src/main/resources/hipchat/hipchatNotifierConfiguration.jsf, appserver/admingui/jms-notifier-console-plugin/src/main/resources/jms/jmsNotifierConfiguration.jsf, appserver/admingui/slack-notifier-console-plugin/src/main/resources/slack/slackNotifierConfiguration.jsf, appserver/admingui/snmp-notifier-console-plugin/src/main/resources/snmp/SNMPNotifierConfiguration.jsf, appserver/admingui/xmpp-notifier-console-plugin/src/main/resources/xmpp/xmppNotifierConfiguration.jsf, appserver/payara-appserver-modules/notification-email-core/src/main/java/fish/payara/notification/email/EmailNotificationConfigurer.java
Email to validates against one or more non-whitespace characters, followed by an _@_, followed by one or more non-whitespace characters (`\S+@\S+`).
=> PAYARA-1439 Admin console and email to validation

appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/ClusteredCDIEventBusImpl.java, appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/micro/services/PayaraInstance.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/cluster/PayaraCluster.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/eventbus/EventBus.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/exec/ClusterExecutionService.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/store/ClusteredStore.java
refactor boot of Hazelcast after it was moved to server-ready
=> PAYARA-1447 

nucleus/admin/config-api/src/main/java/org/glassfish/config/support/TranslatedConfigView.java
support mixed system property and environment property multiple times in value
=> PAYARA-1422 

nucleus/pom.xml
=> PAYARA-1449 updated hazelcast version

appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/loader/data/RandomAccessDataFile.java
=> Issue1414 - Override InputStream.available() in DataInputStream

nucleus/common/common-util/src/main/java/org/glassfish/common/util/OSGiObjectInputOutputStreamFactoryImpl.java
=> Fix the assertion to correctly check prefix for an array type PAYARA-1502

nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/GenericAdminAuthenticator.java, nucleus/common/mbeanserver/src/main/java/org/glassfish/admin/mbeanserver/ConnectorStarter.java
Fix empty JMX principal when MBean is accessed after authentication
=> PAYARA-1251 Fix empty principal after authentication in JMX

appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
This should fix this issue
Fixes #1035
=> synchornized loadClass() method, taken from upstream

nucleus/pom.xml
Depends on https://github.com/payara/Payara_PatchedProjects/pull/51
=> PAYARA-798 PAYARA-902 Update corba to use patched version

appserver/ejb/ejb-full-container/src/main/java/org/glassfish/ejb/mdb/MessageBeanContainer.java
=> PAYARA-1199 Remove dependency on IIOP from MDB container. Fixes #164

appserver/web/weld-integration/src/main/java/org/glassfish/weld/BeanDeploymentArchiveImpl.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/DeploymentImpl.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java
fixed WELD-000163: Non-unique bean deployment identifier detected err…or for versioned applications as well
=> PAYARA-1223 Weld deployment issues for versioned applications

appserver/payara-appserver-modules/jmx-monitoring-service/src/main/java/fish/payara/jmx/monitoring/MonitoringService.java
fixed bug when starting and stopping JMX monitor on a cluster, some cleanup
=> PAYARA-992 fixed dynamic cluster config for JMX logging

appserver/common/container-common/src/main/java/org/glassfish/javaee/services/CommonResourceProxy.java, appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/service/ConnectorAdminServiceUtils.java
fixed extraneous re-creation of app-locally-refined global resources (e.g. JMS factories, JDBC pools etc)
=> PAYARA-1290 fixed sideffects

appserver/common/glassfish-naming/src/main/java/com/sun/enterprise/naming/impl/SerialContext.java, appserver/common/glassfish-naming/src/main/java/com/sun/enterprise/naming/impl/SerialContextProviderImpl.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/EjbReferenceDescriptor.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/node/DeploymentDescriptorNode.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/node/SaxParserHandler.java, appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/annotation/handlers/AbstractEjbHandler.java, appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/annotation/handlers/WebServletHandler.java
Please don't merge until it's flagged ready.
=> PAYARA-1255 enhanced system property substitution

appserver/admingui/payara-console-extras/src/main/resources/hazelcast/hazelcast.jsf
Hazelcast configuration showed incorrect configuration name
=> Changed config name in admin console for hazelcast configuration

appserver/web/weld-integration/src/main/java/org/glassfish/weld/DeploymentImpl.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java
Fix for PAYARA-1200
Github Issue : https://github.com/payara/Payara/issues/900
=> PAYARA-1200 Injection doesn't work for beans created by CDI extensions

appserver/admingui/common/src/main/resources/applications/applications.jsf
The page was referencing an absolute path instead of a relative path.
=> Fixed application reload links

appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/deployment/annotation/handlers/ConnectionFactoryDefinitionHandler.java
do environment variable scanning for ConnectionFactoryDefinitions set via annotations
=> PAYARA-1255 

appserver/admingui/snmp-notifier-console-plugin/src/main/resources/snmp/SNMPNotifierConfiguration.jsf
added fix for handling dynamic configuration in the UI
=> PAYARA-1489-SNMP-Notifier-not-working-correctly

appserver/admingui/common/src/main/resources/applications/applications.jsf, appserver/admingui/common/src/main/resources/applications/deployTable.inc
Caused by https://github.com/payara/Payara/pull/1522
=> Fixed deploy button so that reload button still works

nucleus/admin/template/src/main/resources/config/server.policy
Prevents access exceptions when connecting via JMX with security manager enabled.
=> Added extra permissions to default server.policy file

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/SecurityHandler.java, appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/UtilHandlers.java
Fix for https://github.com/payara/Payara/issues/1398
=> PAYARA-1571 Cannot create LDAP Realm properly

appserver/extras/payara-micro/payara-micro-distribution/pom.xml, appserver/packager/glassfish-common-full/pom.xml, appserver/packager/glassfish-common/pom.xml
Adds concurrent apis to Web Profile. Clustered CDI Event bus now works on web profile.
=> Payara 1445

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
sslPort is not being  set when using packaged system properties.
Fixes #1562
=> PAYARA-1621 sslPort is not being set

api/payara-api/pom.xml, api/payara-api/src/main/java/fish/payara/cdi/jsr107/impl/NamedCache.java, api/payara-api/src/main/java/fish/payara/micro/cdi/ClusteredCDIEventBus.java, api/payara-api/src/main/java/fish/payara/micro/cdi/Inbound.java, api/payara-api/src/main/java/fish/payara/micro/cdi/Outbound.java, api/payara-api/src/main/java/fish/payara/notification/eventbus/EventbusMessage.java, api/payara-api/src/main/java/fish/payara/nucleus/requesttracing/api/Traced.java, api/pom.xml, appserver/payara-appserver-modules/payara-jsr107/pom.xml, appserver/payara-appserver-modules/payara-micro-cdi/pom.xml, appserver/payara-appserver-modules/requesttracing-api/pom.xml, appserver/payara-appserver-modules/zendesk-support/pom.xml, nucleus/packager/payara-api-package/pom.xml, nucleus/payara-modules/notification-core/pom.xml, nucleus/payara-modules/notification-eventbus-core/pom.xml, nucleus/pom.xml, pom.xml
Moves the Payara API back into the Payara Project at the top level.
=> Move API back into Payara Project

appserver/web/weld-integration/src/main/java/org/glassfish/weld/BeanDeploymentArchiveImpl.java
Issue Ref :  https://github.com/payara/Payara/issues/1532
=> PAYARA-1584 @Priority Interceptor from external JAR not picked up

appserver/admingui/payara-console-extras/src/main/java/fish/payara/admingui/extras/rest/PayaraRestApiHandlers.java, appserver/admingui/payara-console-extras/src/main/resources/payaraRestEndpoints/payaraRestEndpoints.jsf, appserver/payara-appserver-modules/payara-rest-endpoints/src/main/java/fish/payara/appserver/rest/endpoints/RestEndpointModel.java, appserver/payara-appserver-modules/payara-rest-endpoints/src/main/java/fish/payara/appserver/rest/endpoints/config/admin/ListRestEndpointsCommand.java, appserver/payara-appserver-modules/payara-rest-endpoints/src/test/java/fish/payara/appserver/rest/endpoints/RestEndpointTest.java
- Fleshed out the tests to fully test REST endpoint options
- Fixed a bug where only one endpoint would display if there were multiple request methods
- Fixed the REST endpoint displayed values
=> Payara 1638 incorrect rest endpoints displayed

appserver/admingui/payara-console-extras/src/main/java/fish/payara/admingui/extras/rest/PayaraRestApiHandlers.java, appserver/payara-appserver-modules/payara-rest-endpoints/src/main/java/fish/payara/appserver/rest/endpoints/config/admin/ListRestEndpointsCommand.java
Changed list rest endpoints command to still return success for empty component so that link appears in admin console, and fixed null pointer exception bug when deploying an application with no web components.
=> PAYARA-1638 Rest Endpoint Null Pointer Exception Fix

api/pom.xml
=> Changed relative path to nucleus pom

appserver/payara-appserver-modules/notification-xmpp-core/src/main/java/fish/payara/notification/xmpp/GetXmppNotifierConfiguration.java
To complement https://github.com/payara/Payara-Server-Documentation/pull/202
=> PAYARA-1486 Changed room name column to room id for xmpp notifier

appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/util/GlassFishObjectInputStream.java
using Class.forName() for arrays, as ClassLoader.loadClass() does not…work for arrays
=> PAYARA-1693 Persistent Timer Info Bug when Using a custom class

appserver/common/glassfish-naming/src/main/java/com/sun/enterprise/naming/impl/SerialInitContextFactory.java
=> PAYARA-1685 fix issues when caching IIOP endpoints in remote EJBs

appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/WebServiceEjbEndpointRegistry.java
initialize Web service endpoints only after it's EJB dependencies have been loaded
fixes #1377
=> PAYARA-1613 SOAPHandlers not working correctly with Dependency Injection on EJBs

appserver/payara-appserver-modules/payara-rest-endpoints/src/main/java/fish/payara/appserver/rest/endpoints/config/admin/ListRestEndpointsCommand.java
=> Fixes #1632

pom.xml
Fix for #1666 breaking on JDK8
=> Removed jdk8 profile

appserver/payara-appserver-modules/payara-rest-endpoints/src/main/java/fish/payara/appserver/rest/endpoints/config/admin/ListRestEndpointsCommand.java
I was facing a similar exception reported in this issue https://github.com/payara/Payara/issues/1632
=> NullPointerException bugfix related to #1632

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/DynamicConfigListener.java
Also edits the similar message for Thread Pools to be clearer, and makes it so that the HTTP listener is only recreated if something has actually changed.
=> PAYARA-1770 Throw an unprocessed change when editing a HTTP listener with monitoring enabled

appserver/admingui/corba/src/main/resources/iiopListenerAttrs.inc, appserver/admingui/corba/src/main/resources/iiopListenerEdit.jsf, appserver/admingui/corba/src/main/resources/iiopListenerNew.jsf, appserver/admingui/corba/src/main/resources/org/glassfish/corba/admingui/Strings.properties, appserver/orb/orb-enabler/src/main/java/org/glassfish/orb/admin/config/IiopListener.java
added ORB listener lazy initialization check boxes to admin console
=> PAYARA-1729 CORBA lazy initialization admin console controls

appserver/admingui/common/src/main/resources/configuration/loggerLevels.jsf
Fixes issue introduced by upstream fix for GLASSFISH-21560
Fixes #1680
=> PAYARA-1759 enable the admin console to support ALL logger level.

appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/SecurityIIOPInterceptorFactory.java
CORBA lazy initialization loads security classes via Common class loader, preventing not found classes
=> PAYARA-1730 lazy-init IIOP security class loader issues

nucleus/pom.xml
=> PAYARA-1753 upgrade to CORBA -p7

appserver/extras/arquillian-containers/pom.xml
Temporarily disable the arquillian container tests due to a clash with Jenkins.
=> PAYARA-1805 Temporarily disable the arquillian container tests

appserver/pom.xml
~~Wait for https://github.com/payara/Payara_PatchedProjects/pull/63 to be merged before merging~~
=> PAYARA-1708 Updated version to match Payara Patched Mojarra version

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/JmsResourceHandler.java
Update of #1728 with copyright
=> PAYARA-1802 jms description

appserver/admingui/common/src/main/resources/security/securityAttrs.inc, nucleus/admin/template/src/main/resources/config/server.policy, nucleus/security/core/src/main/resources/config/server.policy
Down-port security fixes from upstream GlassFish 5
=> Payara 1790

appserver/jms/admin/src/main/java/org/glassfish/jms/admin/cli/CreateJMSDestination.java, appserver/jms/admin/src/main/java/org/glassfish/jms/admin/cli/JMSDestination.java
=> PAYARA-820 JMS destinations cannot have a / in their name

appserver/admingui/payara-console-extras/src/main/resources/fish/payara/admingui/extras/Strings.properties, appserver/admingui/payara-console-extras/src/main/resources/requestTracing/requestTracing.jsf, nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/admin/ListHistoricRequestTraces.java
=> PAYARA-1868 fix for list-historic-requesttracing

nucleus/packager/nucleus-cluster/pom.xml
=> PAYARA-1873 re-add j-interop

appserver/extras/payara-micro/payara-micro-distribution/pom.xml, appserver/extras/payara-micro/payara-micro-microprofile-distribution/pom.xml, appserver/featuresets/payara-web/pom.xml, appserver/packager/pom.xml, appserver/payara-appserver-modules/pom.xml, nucleus/payara-modules/pom.xml
Add MicroProfile modules/dependencies to build profile that activate on JDK8.
=> PAYARA-1875

nucleus/pom.xml
update CORBA patch level to -p8
fixes #1677
=> PAYARA-1884 PAYARA-1861 CORBA fixes

nucleus/common/glassfish-api/src/main/java/fish/payara/api/admin/config/ApplicationDeploymentTime.java
No longer throws an exception if domain upgraded from previous version
=> PAYARA-1322 has a default value for deployment time if none set

appserver/security/webintegration/src/main/java/com/sun/web/security/RequestFacadeWrapper.java, appserver/web/web-core/src/main/java/org/apache/catalina/connector/RequestFacade.java
=> PAYARA-1944 fix wrongly named method

appserver/extras/embedded/all/pom.xml, appserver/extras/embedded/web/pom.xml
=> PAYARA-1952 Add healthcheck package to embedded releases

appserver/payara-appserver-modules/microprofile/config/src/main/java/fish/payara/microprofile/config/spi/ConfigProviderResolverImpl.java
Fixes a NPE coming from microprofile while deploying a versioned application. Doesn't hit on all versioned applications.
=> PAYARA-1950 fix NPE in CDI 

.github/ISSUE_TEMPLATE.md, README.md, appserver/admin/gf_template/src/main/resources/config/domain.xml, appserver/admin/gf_template_web/src/main/resources/config/domain.xml, appserver/connectors/connectors-internal-api/src/test/resources/PasswordAliasTest.xml, appserver/tests/embedded/README, nucleus/admin/config-api/src/test/resources/ClusterDomain.xml, nucleus/admin/config-api/src/test/resources/parser/c1i1.xml, nucleus/admin/config-api/src/test/resources/parser/c1i1c1i2.xml, nucleus/admin/config-api/src/test/resources/parser/i1.xml, nucleus/admin/config-api/src/test/resources/parser/i1i2.xml, nucleus/admin/config-api/src/test/resources/parser/noconfigfori1.xml, nucleus/admin/config-api/src/test/resources/parser/stock.xml, nucleus/admin/template/src/main/resources/config/domain.xml, nucleus/common/common-util/src/test/resources/big.xml, nucleus/common/common-util/src/test/resources/clusters1.xml, nucleus/common/common-util/src/test/resources/manysysprops.xml, nucleus/common/common-util/src/test/resources/monitoringFalse.xml, nucleus/common/common-util/src/test/resources/monitoringNone.xml, nucleus/common/common-util/src/test/resources/monitoringTrue.xml, nucleus/common/common-util/src/test/resources/olddomain.xml, nucleus/common/common-util/src/test/resources/v2domain.xml
=> Payara 1963 max perm size

README.md
=> PAYARA-1945 Updated Payara 5 readme

appserver/pom.xml
PAYARA-1942 Updated Java EE Security versions to enable sample to work
=> PAYARA-1942 Update Java EE Security to API b11 and early impl b14

appserver/web/web-naming/pom.xml, appserver/web/web-naming/src/main/java/org/apache/naming/resources/DirContextURLStreamHandlerService.java, nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/osgi/BundleProvisioner.java, nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/osgi/EmbeddedOSGiGlassFishRuntimeBuilder.java, nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/osgi/OSGiFrameworkLauncher.java, nucleus/osgi-platforms/felix/src/main/resources/config/osgi.properties, nucleus/pom.xml
PAYARA-1917
Adjusted several components as needed for the latest Felix.
Additionally updated Hibernate Validation to 6.0.2.Final
=> PAYARA-1917 Updated Felix to latest version

appserver/packager/external/libpam4j/pom.xml, appserver/pom.xml, appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java, appserver/tests/embedded/maven-plugin/pom.xml, appserver/tests/embedded/servlet_runs_admin_cmds/pom.xml, appserver/tests/paas/mq-shared-service-test/mq-app/web/pom.xml, nucleus/pom.xml
PAYARA-1761 This sets the versions of multiple components to their final EE 8 version
=> PAYARA-1761 Payara 5 minor updates of a selection of components

nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java
fixed a few places where existing serializer configuration would be wiped out,
refactored serialization code a bit
fixes #1872
=> PAYARA-1962 fixed bugs in serializer configuration augmentation

nucleus/payara-modules/healthcheck-cpool/osgi.bundle
fix OSGI manifest for connection pool checker to import hk2 configuration Property
=> PAYARA-2010 fixes connection pool health checker does not work on 173

appserver/packager/glassfish-jcdi/pom.xml, appserver/pom.xml
PAYARA-2028 Using a patched version since the original misses an OSGi export
=> PAYARA-2028 Updated Weld to 3.0.1

.gitignore, appserver/tests/amx/pom.xml, appserver/tests/pom.xml, appserver/tests/quicklook/admin/src/test/admin/BaseAsadminTest.java, appserver/tests/quicklook/adminconsole/pom.xml, appserver/tests/quicklook/adminweb/basic/build.xml, appserver/tests/quicklook/amx/pom.xml, appserver/tests/quicklook/bean-validator/integration-test-servlet/metadata/web.xml, appserver/tests/quicklook/bean-validator/integration-test-servlet/src/java/integration_test_servlet/BVIntegrationTestServlet.java, appserver/tests/quicklook/bean-validator/simple-bv-servlet/build.xml, appserver/tests/quicklook/bean-validator/simple-bv-servlet/src/test/test/bv/servlet/simple/SimpleBVServletTestNG.java, appserver/tests/quicklook/build.xml, appserver/tests/quicklook/gfproject/build-impl.xml, appserver/tests/quicklook/persistence/jpainjectemf/metadata/persistence.xml, appserver/tests/quicklook/persistence/jpainjectemf/src/java/JpaServlet.java, appserver/tests/quicklook/persistence/jpainjectemf/src/java/JpaTest.java, appserver/tests/quicklook/persistence/jpainjectemf/src/test/JpaInjectEMFTestNG.java, appserver/tests/quicklook/pom.xml, appserver/tests/quicklook/weld/extensions/build.xml, appserver/tests/quicklook/weld/extensions/src/java/extensions/ExtensionBean.java, appserver/tests/quicklook/weld/extensions/src/java/extensions/ExtensionBeanServlet.java, appserver/tests/quicklook/wsit/jaxbosgi/build.xml, nucleus/packager/nucleus-osgi/pom.xml, nucleus/tests/pom.xml, nucleus/tests/quicklook/pom.xml
PAYARA-1999 Fixed breakages in tests:
* Update to Java 8
* Addressed warnings
* Added missing jar
* Updated for changed non null message
=> PAYARA-1999 Updated quicklook tests

appserver/pom.xml
=> upgrade commons-fileupload (#1776)

nucleus/pom.xml
updated corba patch level to -p9
=> PAYARA-2015 PAYARA-1960 upgrade CORBA to -p9

appserver/ejb/ejb-connector/src/main/java/org/glassfish/ejb/config/EjbTimerService.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBTimerService.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java, appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HZTimer.java, appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastEJBTimerService.java, appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastTimerStore.java
=> PAYARA-1966 Fix non-persistent timers with --nocluster

appserver/web/web-core/src/main/java/org/apache/catalina/ContainerEvent.java, appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java, appserver/web/web-glue/src/main/java/com/sun/web/server/WebContainerListener.java
PAYARA-1761 Fixes "WEBSOCKET - CDI RELATED TESTS FAIL IN CTS"
See: https://github.com/javaee/glassfish/pull/22210
=> PAYARA-1761 add events for pre/post container initializer calls

appserver/javaee-api/javax.javaee-api/pom.xml, appserver/javaee-api/javax.javaee-web-api/pom.xml, appserver/javaee-api/pom.xml
=> PAYARA-1761 Move jaspic and java ee security to web profile

appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/EjbServicesImpl.java
PAYARA-1761 Fixes TCK MessageDrivenBeanInterceptorInvocationTest failure
See: https://github.com/javaee/glassfish/issues/22150
=> PAYARA-1761 Add AROUND_CONSTRUCT to interceptor chain

appserver/admin/payara_template/src/main/resources/config/domain.xml
I don't think deleting one line can be copyrighted so I skip the legal bits for now, sorry. Feel free to drop my contribution and delete that line yourself.
=> removed duplicated "-Djava.ext.dirs"

appserver/extras/arquillian-containers/payara-common/pom.xml, appserver/extras/arquillian-containers/payara-embedded/pom.xml, appserver/extras/arquillian-containers/payara-managed/pom.xml, appserver/extras/arquillian-containers/payara-remote/pom.xml, appserver/extras/arquillian-containers/pom.xml
PAYARA-2048 Updated versions in pom, added new dependencies that are needed now and tested
=> PAYARA-2048 Updated Arquillian Connector for Jersey 2.26

appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/logging.properties, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/AnsiColor.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/AnsiColorFormatter.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/GFFileHandler.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/ODLLogFormatter.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/UniformLogFormatter.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/SetLogAttributes.java, nucleus/core/logging/src/main/java/fish/payara/enterprise/server/logging/JSONLogFormatter.java
=> PAYARA-1891 First cut of some Ansi Color on the log formatters

appserver/pom.xml
Updated install folder to exclude minor version number
=> Payara 1985 Change Payara 5 Installation Folder

appserver/admingui/payara-console-extras/src/main/java/fish/payara/admingui/extras/rest/PayaraRestApiHandlers.java, appserver/deployment/javaee-core/src/main/java/org/glassfish/javaee/core/deployment/ListSubComponentsCommand.java
Changed JAX-RS Resource 'type' column in admin console to 'JAX-RS'.
=> PAYARA-1906 JAX-RS Resources Incorrectly Listed in Admin Console

nucleus/common/common-util/src/main/java/com/sun/appserv/server/util/VersionInfoImpl.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/VersionInfo.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/ODLLogFormatter.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/UniformLogFormatter.java, nucleus/core/logging/src/main/java/fish/payara/enterprise/server/logging/JSONLogFormatter.java
- Added Payara version number to logs.
- Added JavaDoc comments for Version methods.
=> Payara 1986 Add Payara Quarter Number  To Logs

appserver/web/web-naming/src/main/java/org/apache/naming/resources/FileDirContext.java, appserver/web/web-naming/src/main/java/org/apache/naming/resources/WebDirContext.java
Tested on my local environment, reproducer is detailed in JIRA, but would appreciate more eyes.
=> PAYARA-2151 Ported Apache's fix for CVE-2017-12615

appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/ManagedConnectionImpl.java
fixes NPE where Domain and it's configuration is not available in the environment,
i.e. embedded or standalone client
=> PAYARA-2126 fix NPE in JDBC-RA in non-server (ACC/embedded) environments

appserver/extras/arquillian-containers/payara-common/pom.xml, appserver/extras/arquillian-containers/payara-embedded/pom.xml, appserver/extras/arquillian-containers/payara-managed/pom.xml, appserver/extras/arquillian-containers/payara-remote/pom.xml, appserver/extras/arquillian-containers/pom.xml
Adds the necessary stuff for a maven release.
=> Edit Arquillian container poms for release

appserver/orb/orb-connector/src/main/java/org/glassfish/enterprise/iiop/api/GlassFishORBHelper.java
Nullpointer with a message; log the initialization of the factory.
=> PAYARA-1967 Nullpointer with a message; log the initialization of the factory

nucleus/admin/config-api/src/test/java/com/sun/enterprise/configapi/tests/HttpListenerTest.java, nucleus/admin/config-api/src/test/java/com/sun/enterprise/configapi/tests/UnprocessedEventsTest.java
PAYARA-2175 - test is now independent of order in which separate classes happen to be executed
=> PAYARA-2175 Hardened test by resetting state after test

appserver/packager/glassfish-web/pom.xml, appserver/pom.xml
PAYARA-1923 Added Soteria 1.0, tested against all Soteria tests with the "provided" profile (which assumes the server has the implementation lib)
=> PAYARA-1923 Adding Soteria 1.0 to Payara 4

appserver/web/gf-weld-connector/src/main/java/org/glassfish/weld/connector/WeldSniffer.java, nucleus/diagnostics/context/pom.xml, nucleus/diagnostics/context/src/test/java/org/glassfish/diagnostics/context/impl/AContextImplContextPropagationIntegrationTest.java, nucleus/diagnostics/context/src/test/java/org/glassfish/diagnostics/context/impl/BContextImplIntegrationTest.java, nucleus/diagnostics/context/src/test/java/org/glassfish/diagnostics/context/impl/ContextImplUnitTest.java, nucleus/diagnostics/context/src/test/java/org/glassfish/diagnostics/context/impl/ContextManagerImplUnitTest.java, nucleus/pom.xml
PAYARA-2176 Added ordering directive for surefire and renamed classed to fit
=> PAYARA-2176 Fixed ordering issue between tests

appserver/admin/payara_template/src/main/resources/config/domain.xml, appserver/admin/payara_template_web/src/main/resources/config/domain.xml
New PR from https://github.com/payara/Payara/pull/1976
=> PAYARA-1225 enhance payaradomain template

appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/domain.xml, appserver/extras/payara-micro/payara-micro-distribution/pom.xml
Also updated domain.xml so monitoring will work
=> PAYARA-2179 added jmx monitoring to Payara Micro

nucleus/pom.xml
=> PAYARA-2184 PAYARA-1960 upgrade to CORBA -p10

nucleus/pom.xml
=> Revert "PAYARA-2216 Deploy From Admin Console Fails"

nucleus/pom.xml
=> Revert "Revert "PAYARA-2216 Deploy From Admin Console Fails""

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/ApplicationHandlers.java, appserver/admingui/common/src/main/resources/applications/manageVirtualServers.jsf, appserver/admingui/common/src/main/resources/resourceNode/resourceEditTargets.jsf, nucleus/admin/util/src/main/java/org/glassfish/admin/cli/resources/LocalStrings.properties, nucleus/admin/util/src/main/java/org/glassfish/admin/cli/resources/UpdateResourceRef.java, nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/UpdateApplicationRefCommand.java
- Added update-application-ref command.
- Added update-resource-ref command.
- Updated admin console to use new commands.
=> PAYARA-1797 Virtual Server Config Cluster Propagation

appserver/admingui/common/src/main/resources/applications/manageVirtualServers.jsf, appserver/admingui/common/src/main/resources/resourceNode/resourceEditTargets.jsf, nucleus/admin/util/src/main/java/org/glassfish/admin/cli/resources/LocalStrings.properties, nucleus/admin/util/src/main/java/org/glassfish/admin/cli/resources/UpdateResourceRef.java, nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/UpdateApplicationRefCommand.java
Added relevant copyright headers for commit e9d7011b40ed5e04aef2d2fd6ad62b81374f3af8.
https://github.com/payara/Payara/pull/2086
=> PAYARA-1797 Added Copyright Headers for Cluster Config Propagation

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java, appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastTimerStore.java
=> Revert "PAYARA-2095 Fix EJB timers broken in Payara 5 alpha1"

appserver/admin/gf_template/src/main/resources/config/default-web.xml, appserver/admin/gf_template_web/src/main/resources/config/default-web.xml, appserver/admin/payara_template/src/main/resources/config/default-web.xml, appserver/admin/payara_template_web/src/main/resources/config/default-web.xml, appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/util/InjectionManagerImpl.java, appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/spi/util/InjectionManager.java, appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/default-web.xml, appserver/web/jsf-connector/src/main/java/org/glassfish/faces/integration/GlassFishInjectionProvider.java, appserver/web/jsf-connector/src/main/java/org/glassfish/faces/integration/GlassFishTldProvider.java, appserver/web/web-embed/api/src/main/resources/org/glassfish/web/embed/default-web.xml, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/ApplicationEnvironment.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/ComponentInvocation.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/ComponentInvocationHandler.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/InvocationException.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/InvocationManager.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/InvocationManagerImpl.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/RegisteredComponentInvocationHandler.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/ResourceHandler.java
This reverts commit 17587dde0cf44f93e4d56011dabf4e48eea44e35.
=> Revert PAYARA-1926

appserver/admin/gf_template/src/main/resources/config/default-web.xml, appserver/admin/gf_template_web/src/main/resources/config/default-web.xml, appserver/admin/payara_template/src/main/resources/config/default-web.xml, appserver/admin/payara_template_web/src/main/resources/config/default-web.xml, appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/util/InjectionManagerImpl.java, appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/spi/util/InjectionManager.java, appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/default-web.xml, appserver/web/jsf-connector/src/main/java/org/glassfish/faces/integration/GlassFishInjectionProvider.java, appserver/web/jsf-connector/src/main/java/org/glassfish/faces/integration/GlassFishTldProvider.java, appserver/web/web-embed/api/src/main/resources/org/glassfish/web/embed/default-web.xml, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/ApplicationEnvironment.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/ComponentInvocation.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/ComponentInvocationHandler.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/InvocationException.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/InvocationManager.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/InvocationManagerImpl.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/RegisteredComponentInvocationHandler.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/ResourceHandler.java
=> Revert "Revert PAYARA-1926"

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java, appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastTimerStore.java
=> Revert "Revert "PAYARA-2095 Fix EJB timers broken in Payara 5 alpha1""

appserver/packager/glassfish-web/pom.xml
PAYARA-2187 excludes Soteria when running on JDK7
=> PAYARA-2187 Added JDK8 profile for Soteria in Payara 4.

appserver/pom.xml
upgrade OpenMQ to -p2 version
Merge only after the PatchedProjects PR has been merged
=> PAYARA-2182 OpenMQ

nucleus/pom.xml
PAYARA-2253 update Hibernate Validation
=> PAYARA-2253 update validation to 6.0.3

nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java
=> PAYARA-2266 Fixed collect files command for Payara Micro

nucleus/pom.xml
=> PAYARA-2269 Fix ALPN issues with SSL

appserver/extras/payara-micro/payara-micro-distribution/pom.xml, appserver/packager/microprofile-package/pom.xml, appserver/payara-appserver-modules/microprofile/config/src/main/java/fish/payara/microprofile/config/converters/ChronoUnitConverter.java, appserver/payara-appserver-modules/microprofile/config/src/main/java/fish/payara/microprofile/config/spi/ConfigProviderResolverImpl.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/pom.xml, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/FaultToleranceCDIExtension.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/FaultToleranceService.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/FaultToleranceServiceConfiguration.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/admin/GetFaultToleranceConfigurationCommand.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/admin/SetFaultToleranceConfigurationCommand.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/cdi/FaultToleranceCDIExtension.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/cdi/FaultToleranceCdiUtils.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/AsynchronousInterceptor.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/BulkheadInterceptor.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/CircuitBreakerInterceptor.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/FallbackPolicy.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/RetryInterceptor.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/TimeoutInterceptor.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/fallback/FallbackPolicy.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/state/CircuitBreakerState.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/validators/AsynchronousValidator.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/validators/BulkheadValidator.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/validators/CircuitBreakerValidator.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/validators/FallbackValidator.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/validators/RetryValidator.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/validators/TimeoutValidator.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension, appserver/pom.xml
Initial stab at implementing MicroProfile Fault Tolerance 1.0
=> PAYARA-1912 MicroProfile Fault Tolerance 1.0

appserver/pom.xml
=> PAYARA-2262 Update Payara 5 to use Mojarra 2.4 m01 p3

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/Container.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/BaseContainer.java, appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/startup/EjbApplication.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/deployment/ApplicationContainer.java, nucleus/common/internal-api/src/main/java/org/glassfish/internal/data/ApplicationInfo.java, nucleus/common/internal-api/src/main/java/org/glassfish/internal/data/EngineRef.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java
Container initialization is deferred until init phase
=> PAYARA-2243 and PAYARA-2095 EJB Timer initialization in Payara Micro 5

appserver/transaction/jta/src/main/java/com/sun/enterprise/transaction/JavaEETransactionManagerSimplified.java
using working list to prevent concurrent modification exceptions in JTA
=> PAYARA-2303 ConcurrentModificationException in JTA

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java, appserver/payara-appserver-modules/payara-micro-cdi/pom.xml, appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/ClusteredCDIEventBusImpl.java, appserver/web/weld-integration/pom.xml, appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/InjectionServicesImpl.java, nucleus/common/internal-api/src/main/java/org/glassfish/internal/data/ApplicationInfo.java, nucleus/common/internal-api/src/main/java/org/glassfish/internal/deployment/Deployment.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java
Fixed numerous issues that prevented CDI event bus from working
=> PAYARA-2150 CDI Event Bus fixes for Payara 5

appserver/extras/embedded/all/pom.xml, appserver/extras/embedded/web/pom.xml, appserver/extras/payara-micro/payara-micro-distribution/pom.xml, appserver/featuresets/payara-web/pom.xml, appserver/packager/payara-executor-service/pom.xml, appserver/packager/payara-executor-service/src/main/assembly/payara-executor-service.xml, appserver/packager/payara-executor-service/src/main/resources/pkg_proto.py, appserver/packager/pom.xml, nucleus/packager/payara-executor-service-package/pom.xml, nucleus/packager/pom.xml, nucleus/payara-modules/payara-executor-service/pom.xml, nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/PayaraExecutorService.java, nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/PayaraExecutorServiceConfiguration.java, nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/admin/GetPayaraExecutorServiceConfigurationCommand.java, nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/admin/SetPayaraExecutorServiceConfigurationCommand.java
Adds in a basic executor service for use by internal services.
=> PAYARA-2289 Payara Executor Service

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/DynamicReloader.java
=> PAYARA-2311 Null check for app location for dynamic reloader

appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/data/ModuleDescriptor.java, appserver/payara-appserver-modules/payara-micro-service/pom.xml, appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/micro/services/data/InstanceDescriptorImpl.java, appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/micro/services/data/ModuleDescriptorImpl.java
=> PAYARA-2300 Added logging of servlet mappings for each module at boot

appserver/common/glassfish-naming/src/main/java/com/sun/enterprise/naming/impl/SerialInitContextFactory.java, appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/IiopFolbGmsClient.java, appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/NamingClusterInfoImpl.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/naming/NamingClusterInfo.java
introduced property fish.payara.iiop.clusterupdate to enable/disable 
populating CORBA clusters from GMS
=> PAYARA-2278 disable CORBA updates from GMS

appserver/payara-appserver-modules/payara-rest-endpoints/src/main/java/fish/payara/appserver/rest/endpoints/config/admin/ListRestEndpointsCommand.java
Diff is a little weird due to added loop. application.wadl is [autogenerated by jersey](https://jersey.github.io/documentation/latest/wadl.html#d0e13102) so should always be located here.
=> PAYARA-2232 Added link to application.wadl

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/RUNTIME_OPTION.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/RuntimeOptions.java
deploy applications that are missing --deploy flag to improve user experience on Payara Micro with this PR
```java -jar payara-micro.jar test.war ``` will just work
=> PAYARA-2304 Support raw deployments on Payara Micro

appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/data/ModuleDescriptor.java, appserver/payara-appserver-modules/payara-micro-service/pom.xml, appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/micro/services/data/InstanceDescriptorImpl.java, appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/micro/services/data/ModuleDescriptorImpl.java
Fixed issue whereby InstanceDescriptorImpl was no longer Serializable
=> PAYARA-2334 Fix InstanceDescriptor Serialization

appserver/pom.xml
PAYARA-2340 Also fixed some compile warnings
=> PAYARA-2340 Patched Soteria making some utilities public

appserver/transaction/jta/src/main/java/com/sun/enterprise/transaction/JavaEETransactionManagerSimplified.java
fixed ConcurrentModificationException in enlistComponentResources() as well
=> PAYARA-2354 JTA CME fix #2

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModule.java
PAYARA-2355 Add declared roles to web bundle descriptor.  …
That way policy config can pick them up later.
=> Payara-2355 declare roles

appserver/admingui/payara-console-extras/src/main/resources/hazelcast/hazelcast.jsf, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/admin/GetHazelcastConfiguration.java
Fixes bug in this cycle which stopped saving the Data Grid configuration
=> PAYARA-2357 Fix bug saving Data Grid configuration

nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java
=> PAYARA-2358 Ensure restart of datagrid when dynamic is true

nucleus/admin/util/src/main/java/com/sun/enterprise/admin/remote/RemoteRestAdminCommand.java
Add more robust parsing of booleans to ensure command parameters are correctly parsed. This fixes issue whereby applications won't undeploy on remote instances
=> PAYARA-2363

nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/GenericAnnotationDetector.java
Fixes Embedded all issues with not deploying EJB jars that contained other files e.g. xml files
Fixes #2188
=> PAYARA-2333 Fix deployment of EJB jars on embedded when config files are present

appserver/extras/arquillian-containers/payara-common/src/main/java/fish/payara/arquillian/container/payara/file/LogReader.java, appserver/extras/arquillian-containers/payara-common/src/main/java/fish/payara/arquillian/container/payara/file/StringConsumer.java, appserver/extras/arquillian-containers/payara-micro/src/main/java/fish/payara/arquillian/container/payara/managed/PayaraMicroDeployableContainer.java
- Container now stops in undeploy phase, to prevent multiple running instances.
- Tests now wait completely for startup by following log output.
- No longer confuses output from different tests.
=> PAYARA 2386 Fix Payara Micro Arquillian Container

appserver/pom.xml
=> PAYARA-2390 Updated Mojarra with websocket fix

nucleus/payara-modules/nucleus-microprofile/config-service/src/test/java/fish/payara/nucleus/microprofile/config/source/SecretsDirConfigSourceTest.java
manually updating the last modification time
=> PAYARA-2356-increase-delay-on-secret-dir-test (#2229)

appserver/packager/microprofile-package/pom.xml, appserver/payara-appserver-modules/microprofile/jwt-auth/pom.xml, appserver/pom.xml
PAYARA-2367 Using patched jwt api that removed cdi2 constraint.
MP JWT impl and api jars packaged again.
=> PAYARA-2367 Using patched jwt api that removed cdi2 constraint.

nucleus/admin/template/src/main/resources/config/logging.properties
This is for Payara Server in verbose mode
=> PAYARA-2383 Enabled ANSI coloured logs by default

nucleus/pom.xml
Fixes #2327 
Builds OK locally.
=> PAYARA-2443 - update Jackson

appserver/transaction/jta/src/main/java/com/sun/enterprise/transaction/JavaEETransactionManagerSimplified.java
The bug is actually in JMSContext, the fixes would have hidden this bug further,
so reverting these fixes
=> Revert PAYARA-2354 and PAYARA-2303

appserver/pom.xml
PAYARA-2451 Updated Mojarra to patch 6
=> PAYARA-2451 Update Mojarra to p6 to get rid of left over system.out

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBContextImpl.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/StatelessSessionContainer.java
added reset of resources for SLSBs that are going back in the pool
fixes #1278
=> PAYARA-1354 fixed resource leakage with SLSB back in the pool

nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/util/CleanupPostBoot.java
Changed to help clean up boot log to only contain useful information for developers/operators.
=> PAYARA-2467 Changed log level to Config

nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigProviderResolverImpl.java
Microprofile Config api is broken in Beta 2.
=> PAYARA-2395 Config api is broken in 5 beta 2

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
=> PAYARA-2475 Change sort back to JDK7 version

appserver/web/web-core/src/main/java/org/apache/catalina/connector/Request.java
PAYARA-2212 if AsyncContext is used from within another "http thread" than the one that created it, execute the complete method internals in another thread to shield it (distinguish it) from the thread that calls complete on it.
=> PAYARA-2212 Fix Weld warning for asynccontext used in other http thread

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBContextImpl.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/StatelessSessionContainer.java, appserver/extras/embedded/all/pom.xml, appserver/extras/embedded/web/pom.xml, appserver/extras/payara-micro/payara-micro-distribution/pom.xml, appserver/jms/gf-jms-injection/src/main/java/org/glassfish/jms/injection/InjectableJMSContext.java, appserver/payara-appserver-modules/microprofile/config/src/main/java/fish/payara/microprofile/config/cdi/ConfigPropertyProducer.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/PayaraConfig.java
Using alternative merge strategy then cherry-picking
=> PAYARA-2494 merge master into Payara 5

nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/RequestTrace.java, nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/RequestTraceStoreCleanupTask.java, nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/admin/ListRequestTraces.java, nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/domain/RequestTraceSpan.java
Also made requesttracing use Java 8 time API, which makes things a bit simpler
=> PAYARA-2502 Requesttraces now use correct endtime

appserver/pom.xml
PAYARA-2468 
* https://github.com/payara/Payara_PatchedProjects/commit/d81048933a56f5dc4eeea7bbd0c6c4ae0c936582
* https://github.com/payara/patched-src-mojarra/commit/1561aad5a4b0b232b198688ead241c502b9c181f
=> PAYARA-2468 Updated Mojarra to P7 to prevent junk logging

appserver/extras/arquillian-containers/payara-micro/src/main/java/fish/payara/arquillian/container/payara/managed/PayaraMicroContainerConfiguration.java, appserver/extras/arquillian-containers/payara-micro/src/main/java/fish/payara/arquillian/container/payara/managed/PayaraMicroDeployableContainer.java
Also added environment variable for already present `outputToConsole` option.
=> PAYARA-2406 Add Clustering Switch To Micro Arquillian Container

appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/domain.xml
Prevents the DAS trying to join a Payara Micro multicast cluster when using domain cluster mode.
=> PAYARA-2429 Changed default start port

appserver/pom.xml, nucleus/pom.xml
* https://github.com/payara/Payara_PatchedProjects/commit/c4cf2aa5eca412ee87cfa03ffa2e32b62e96e910
* https://github.com/payara/patched-src-security-soteria/commit/7067b4b7534a19de97bb92ef8eb0860064309fd7
* https://github.com/payara/patched-src-security-soteria/commit/21cef88df1b745d672bd68bdd9f6376c98b7c8c7
=> PAYARA-2364 PAYARA-2412 Updated to Soteria P2 fixing exception and log

appserver/pom.xml
* https://github.com/payara/Payara_PatchedProjects/commit/0ed4986c34087a42e189a26043a9c5667b63e184
=> PAYARA-2517 Updated JBatch to P3 with Weld logging fix

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/ODLLogFormatter.java, nucleus/core/logging/src/main/java/fish/payara/enterprise/server/logging/JSONLogFormatter.java
=> PAYARA-2512 Ensure formatter added to handler correctly on reading log config

appserver/packager/jersey/pom.xml
* https://github.com/payara/Payara_PatchedProjects/commit/83bc1ec086fd353e19cd30ed89d308d5812ad1b5
* https://github.com/payara/patched-src-jersey/commit/2b8b16ba5383e989c9febb3c9d29563a946b6e1a
=> PAYARA-2518 Update 3 individual jars to Jersey 2.26 p1

nucleus/pom.xml
=> Upgrade to patched grizzly ALPN for JDK8u161 and above

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/ApplicationHandlers.java, appserver/admingui/payara-console-extras/src/main/java/fish/payara/admingui/extras/rest/PayaraRestApiHandlers.java, appserver/admingui/payara-console-extras/src/main/resources/payaraRestEndpoints/payaraRestEndpoints.jsf, appserver/extras/payara-micro/payara-micro-core/pom.xml, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java, appserver/payara-appserver-modules/payara-rest-endpoints/src/main/java/fish/payara/appserver/rest/endpoints/config/admin/ListRestEndpointsCommand.java
- Refactored ListRestEndpointsCommand to use intermediary helper method.
- Used this helper method in PayaraMicroImpl to disable the output if there are no endpoints.
- Fixed related rest endpoint bugs.
- Made rest endpoint links clickable in the admin console.
=> PAYARA-2365 Remove Redundant Rest Endpoint Info

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/util/ResourceValidator.java
ensure component invocation is set up before doing resource lookups
Ensure global JNDI lookups are done rather than just checked against the application
fixes #2430
=> PAYARA-2531 Fixes #2430

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/Application.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/WebBundleDescriptor.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/xml/RuntimeTagNames.java, appserver/deployment/dtds/src/main/resources/glassfish/lib/dtds/glassfish-web-app_3_0-1.dtd, appserver/payara-appserver-modules/microprofile/jwt-auth/pom.xml, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jaxrs/RolesAllowedAutoDiscoverable.java, appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/descriptor/WebBundleDescriptorImpl.java, appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/node/runtime/gf/WebBundleRuntimeNode.java
=> PAYARA-2326 Added switch in glassfish-web to switch JAX-RS @RolesAllowed

appserver/admingui/payara-console-extras/src/main/java/fish/payara/admingui/extras/PayaraUtilHandlers.java
* Added null check to prettyDateFormat.
* Properly handled the exceptions.
* Added copyright header.
Merge from #2424
=> PAYARA-2440 Refactor Pretty Date Format (Payara 5 merge)

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/StatefulSessionContainer.java, nucleus/common/internal-api/osgi.bundle
Never worked in HA to begin with, so fails on micro as wel
=> PAYARA-2542 @Stateful HA fixes

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java
When versioned applications are deployed, this message is printed in error
=> PAYARA-2542 don't print concurrent deploy msg

appserver/web/weld-integration/src/main/java/org/glassfish/weld/DeploymentImpl.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java
otherwise Weld clustering deserialization fails
=> PAYARA-2542 Weld BDA context is the same in Server as in Micro

appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/PayaraMicro.java
This option is required to compile JSPs but otherwise is not required.
=> PAYARA-2492 added options to unpack jars when Payara Micro is used programmatically

nucleus/pom.xml, pom.xml
Also propertises the versions rather than hard coding them.
=> PAYARA-2329 Javadoc fix

appserver/admingui/payara-support/src/main/resources/zendesk/assets/skins/payara_theme/styles.css, appserver/admingui/payara-support/src/main/resources/zendesk/index.html
- JavaScript tweak to loading for support styles
- Added overrides for some pesky CSS not being applied in Firefox
=> PAYARA-2347

appserver/admin/gf_template/src/main/resources/config/domain.xml, appserver/admin/gf_template_web/src/main/resources/config/domain.xml, appserver/admin/payara_template/src/main/resources/config/domain.xml, appserver/admin/payara_template_web/src/main/resources/config/domain.xml, appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/domain.xml, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/MetricsService.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/admin/GetMetricsConfigurationCommand.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/admin/MetricsServiceConfiguration.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/admin/SetMetricsConfigurationCommand.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/cdi/interceptor/AbstractInterceptor.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/cdi/interceptor/MetricsInterceptor.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/rest/MetricsResource.java
Update of https://github.com/payara/Payara/pull/2433
=> PAYARA-2477 (Master) Update

appserver/payara-appserver-modules/payara-jsr107/osgi.bundle, appserver/payara-appserver-modules/payara-jsr107/pom.xml, appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/implementation/PayaraValueHolder.java, appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/ClusteredCDIEventBusImpl.java, appserver/web/gf-web-connector/osgi.bundle, appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/JavaEEContextUtilImpl.java, nucleus/common/internal-api/src/main/java/org/glassfish/internal/api/JavaEEContextUtil.java
stop printing erroneous exceptions when apps are not subscribed to events
=> PAYARA-2189 filter class not found by applications in CDI events

nucleus/osgi-platforms/felix/src/main/resources/config/osgi.properties
PAYARA-2466 Finally squash the unnecessary Felix warnings
=> PAYARA-2466 Finally squash the unnecessary Felix warnings

nucleus/core/logging/pom.xml, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/AnsiColor.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/AnsiColorFormatter.java, nucleus/packager/nucleus/pom.xml, nucleus/pom.xml
This reverts commit d7311adaab08ff3b162d5d02290285e4dfb54a8e.
=> Revert "PAYARA-2265 enable ansi colours on all OSs"

appserver/pom.xml
* https://github.com/payara/Payara_PatchedProjects/commit/d240348f6b35b57a67a911f25f7fa5d6df0ff7e4
* https://github.com/payara/patched-src-security-soteria/commit/995ac794a57bcd0e64ab05f3d0efbc2c8d145e71
=> PAYARA-2566 Update to Soteria P3

appserver/web/web-glue/pom.xml, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebContainer.java
When app is deployed to more than one virtial server, create a separate class loader for each
Fixes #1133 in Payara 4
=> PAYARA-2613 fix JSF warnings that fill up log files w/virtual servers - Payara 4

appserver/web/web-glue/pom.xml, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebContainer.java
When app is deployed to more than one virtual server, create a separate class loader for each
fixes #1133
=> PAYARA-2613 fix JSF warnings that fill up log files w/virtual servers

appserver/extras/payara-micro/payara-micro-distribution/build.xml
=> PAYARA-2579 Added keyfile to Payara Micro distribution

appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/util/InjectionManagerImpl.java, appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/descriptor/WebBundleDescriptorImpl.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/DeploymentImpl.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java
- Fixed InjectionManager to defer looking up JNDI until it knows it's the correct class
- CDI injection services are added with the proper BDA/Bundle combindations
Fixes regressions introduced with PAYARA-1200 and couple of upstream bugs
fixes #2081
=> PAYARA-2229 fixed CDI extension injection regression with EAR files for Payara 5

appserver/extras/embedded/all/pom.xml, appserver/extras/embedded/web/pom.xml
MAINTENANCE PR of: https://github.com/payara/Payara/pull/2489
=> PAYARA-2558 Embedded Contains Non Optional Dependencies

nucleus/core/kernel/src/main/java/org/glassfish/kernel/FileMonitoringImpl.java
PAYARA-2630 when Payara is started via the java command, instead of via asadmin, it throws a bunch of exceptions and hangs. This fixes this.
=> PAYARA-2630 Fix exception during boot when Payara started via java

appserver/pom.xml
PAYARA-2566 Fixed EL processing of LDAP URL attribute
=> PAYARA-2566 Update to Soteria P3 (#2519)

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/util/ResourceValidator.java
* PAYARA-2582 change application to be a local variable to prevent classloader leak when validating resources
* payara-2582 Fixed messed up infinite loop
=> PAYARA-2582 … (#2520)

nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/JvmOptions.java
=> PAYARA-2425 Added Environment substitution for JVM options

appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java
This creates an EEModuleDescriptor which avoids triggering
ApplicationScoped events twice
=> PAYARA-2310 back port of changes done in PAYARA-1305

nucleus/admin/config-api/src/main/java/org/glassfish/config/support/TargetBasedResolver.java, nucleus/admin/rest/rest-service/src/main/java/fish/payara/admin/rest/resources/MonitoredAttributeBagResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/CollectionLeafResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/LeafResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/PropertiesBagResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateListOfResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateRestResource.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/custom/SystemPropertiesCliResource.java, nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/DomainXmlVerifier.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/DeleteSystemProperty.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/V2DottedNameSupport.java, nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/dom/NetworkListener.java, nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/dom/ThreadPool.java
Down-port grizzly race condiftion fix
=> PAYARA-2657 grizzly race condition for Payara 4

nucleus/admin/template/src/main/resources/config/logging.properties, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/SetLogAttributes.java, nucleus/core/logging/src/main/java/fish/payara/enterprise/server/logging/JSONLogFormatter.java
=> PAYARA-2612 removed underscore from field names in JSON Formatter

appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java
This logs InvocationException first and then DeploymentException with information about the original error. It may be worth fixing the InvocationException too because it has no real value for the user.
The log message for the InvocationException should be probably externalized similar to WELD_BOOTSTRAP_SHUTDOWN_EXCEPTION but I don't know how to do it correctly.
=> PAYARA-2666 - show DepoymentException in logs in case of deployment error

api/payara-api/src/main/java/fish/payara/cluster/Clustered.java, api/payara-api/src/main/java/fish/payara/cluster/DistributedLockType.java, appserver/common/container-common/pom.xml, appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/util/ClusteredSingletonLookupImplBase.java, appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/spi/ClusteredSingletonLookup.java, appserver/ejb/ejb-container/pom.xml, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/AbstractSingletonContainer.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/BMCSingletonContainer.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/BaseContainer.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/CMCSingletonContainer.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/ClusteredSingletonLookupImpl.java, appserver/payara-appserver-modules/payara-micro-cdi/pom.xml, appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/PayaraMicroCDIExtension.java, appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/cluster/ClusterScopeContext.java, appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/cluster/ClusterScopedInterceptor.java, appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/cluster/ClusteredAnnotatedType.java, appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/cluster/ClusteredAnnotationProcessor.java, appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/cluster/ClusteredSingletonLookupImpl.java, appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/cluster/annotations/ClusterScoped.java, appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/cluster/annotations/ClusterScopedIntercepted.java, appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/JavaEEContextUtilImpl.java, appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/JCDIServiceImpl.java, nucleus/common/internal-api/src/main/java/org/glassfish/internal/data/ApplicationInfo.java, nucleus/common/internal-api/src/main/java/org/glassfish/internal/deployment/Deployment.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java
Back-port Clustered Singleton CDI support and fixes to Payara 4
=> PAYARA-2557 clustered singleton Payara 4

nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/admin/GetConfigOrdinal.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/admin/SetConfigOrdinal.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/PasswordAliasConfigSource.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigProviderResolverImpl.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/MicroprofileConfigConfiguration.java
Add a microprofile config source to inject password aliases stored in the Password alias store
=> PAYARA-2682 Add Password Alias Store Config Source

appserver/admingui/common/src/main/resources/js/adminjsf.js, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebDeployer.java
default context root value for deployment is now taken internally,
the default GUI valus is now blank
Issue #2619
=> PAYARA-2697 default context root admin console improvement

nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/UpdateApplicationRefCommand.java
Fixes https://github.com/payara/Payara/issues/1697.
=> PAYARA-2674 UpdateApplicationRef Command Doesn't Replicate

nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/UpdateApplicationRefCommand.java
Maintenance PR of: https://github.com/payara/Payara/pull/2685
=> PAYARA-2674 Update Application Ref Command Doesn't Replicate MAINTENANCE

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
There is a minor typo in --minHttpThreads in Payara Micro
=> PAYARA-2735 correct typo. Fixes #2714

nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/AdminMain.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/CLICommand.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/CLIConstants.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/CLIContainer.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/CLIProcessExecutor.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/CLIUtil.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/ClassPathBuilder.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/DirectoryClassLoader.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/Environment.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/ExportCommand.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/HelpCommand.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/ListCommandsCommand.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/LoginCommand.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/More.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/MultimodeCommand.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/Parser.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/ProgramOptions.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/StringEditDistance.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/Strings.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/UnsetCommand.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/VersionCommand.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/embeddable/CommandExecutorImpl.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/embeddable/DeployerImpl.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/remote/ClientCookieStore.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/remote/DASUtils.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/remote/RemoteCLICommand.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/remote/RemoteCommand.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/schemadoc/ClassDef.java
Resolves warnings and code smells from sonarcloud, excluding duplications and cognitively complexity
=> PAYARA-2708 Cleanup code in nucleus/admin/cli

nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/MemberAddressPicker.java
=> PAYARA-2734 --interfaces does not work in Payara Micro

nucleus/security/services/pom.xml
This allows Payara 4 to build with JDK 1.8.0_171
=> PAYARA-2746 Resolved classloading issue preventing Payara 4 building

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
=> PAYARA-2735 correct typo maintenance PR

appserver/payara-appserver-modules/microprofile/config/src/main/java/fish/payara/microprofile/config/cdi/CDIExtension.java, appserver/payara-appserver-modules/microprofile/config/src/main/java/fish/payara/microprofile/config/cdi/ConfigProducer.java, appserver/payara-appserver-modules/microprofile/config/src/main/java/fish/payara/microprofile/config/cdi/ConfigPropertyProducer.java, appserver/pom.xml, nucleus/payara-modules/nucleus-microprofile/config-service/pom.xml, nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/converters/BooleanConverter.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/converters/ClassConverter.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/converters/CommonSenseConverter.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/converters/StringConverter.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigProviderResolverImpl.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/PayaraConfig.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/PayaraConfigBuilder.java, nucleus/pom.xml
Microprofile Config 1.2.1 for Payara 4
=> PAYARA-2545 Payara-v4 branch

nucleus/pom.xml
Fix for https://github.com/payara/Payara/issues/2646
=> Code coverage analysis using Jacoco

appserver/extras/arquillian-containers/payara-client-ee8/pom.xml, appserver/extras/arquillian-containers/pom.xml, nucleus/pom.xml
Jersey 2.27 Patch branch : https://github.com/payara/patched-src-jersey/commits/2.27_mp_rest
=> PAYARA-2712 - Jersey Patch v2.27.payara-p3 (ParamConverterProvider support in Jersey Client)

nucleus/flashlight/framework/src/main/java/org/glassfish/flashlight/impl/client/ReflectiveClientInvoker.java
This partially fixes PAYARA-2730 by allowing disabling the annoying log message
=> Changed printing to stdout to logging with the JDK logger.

appserver/extras/arquillian-containers/payara-client-ee7/pom.xml, appserver/extras/arquillian-containers/payara-client-ee8/pom.xml, appserver/extras/arquillian-containers/pom.xml, nucleus/pom.xml
Jersey branch : https://github.com/payara/patched-src-jersey/commits/2.27_mp_rest
=> PAYARA-2762 -Jersey Rest Client - Remove redundant MessageBodyReader/MessageBodyWriter filtering based on custom flag

appserver/extras/arquillian-containers/pom.xml, appserver/packager/microprofile-package/pom.xml, appserver/pom.xml, nucleus/pom.xml
- Microprofile TCK Runner : https://github.com/payara/MicroProfile-TCK-Runners/pull/7
- Jersey branch for Rest Client : https://github.com/payara/patched-src-jersey/commits/2.25.1_mp_rest
- Patched Rest Client API/TCK : https://github.com/payara/patched-src-microprofile-rest-client/tree/1.0.1-patch
=> PAYARA-2726 - MicroProfile REST client v1.0.1 (Payara 4.x)

nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/JvmOptions.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/commands/CreateJvmOptions.java
* PAYARA-2425 Fix for using multiple envrionment variable in a line
* PAYARA-2425 Add - to start of option if not already present
* PAYARA-2425 Fix for create-jvm-options using an envrionment variable
* PAYARA-2425 added comment
=> PAYARA-2425 Fix for using multiple envrionment variable in a line

appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/MetricsService.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/jmx/MBeanExpression.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/jmx/MBeanMetadataHelper.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/rest/MetricsResource.java
* PAYARA-2707 Dynamic registraion of MBean as MP metric
This allows for placeholder replacement in MP custom metrics
* PAYARA-2707 added import
* Update MetricsService.java
Breaking tie
* Update MetricsService.java
=> PAYARA-2707 Dynamic registration of MBean as MP metric (#2717)

api/payara-api/pom.xml, api/payara-api/src/main/java/fish/payara/security/annotations/OAuth2AuthenticationDefinition.java, appserver/payara-appserver-modules/security-oauth2/pom.xml, appserver/payara-appserver-modules/security-oauth2/src/main/java/fish/payara/security/oauth2/OAuth2AuthenticationMechanism.java, appserver/payara-appserver-modules/security-oauth2/src/main/java/fish/payara/security/oauth2/OAuth2MechanismHandler.java, appserver/payara-appserver-modules/security-oauth2/src/main/java/fish/payara/security/oauth2/OAuth2Producer.java, appserver/payara-appserver-modules/security-oauth2/src/main/java/fish/payara/security/oauth2/OAuth2StateHolder.java
* PAYARA-2718 Added Microprofile Config support to OAuth definition annotation
* PAYARA-2718 added method to reduce duplication
* PAYARA-2718 Added EL# support
* Moved annotation to different package
* PAYARA-2718 Made keys well-known
* PAYARA-2718 return MP value if present directly
=> PAYARA-2718 Added Microprofile Config support to OAuth definition annotation

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/util/ModelUtils.java
This is non-essential, but is there still time for it to be merged?
=> PAYARA-2768 Fixed OpenAPI Leading Slash Issue

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/util/ModelUtils.java
MAINTENANCE for: https://github.com/payara/Payara/pull/2791.
=> PAYARA-2768 OpenAPI Incorrect Paths 4 Maintenance

appserver/common/amx-javaee/src/main/java/org/glassfish/admin/amx/impl/j2ee/loader/AMXJ2EEStartupService.java, appserver/web/admin/src/main/java/fish/payara/grizzly/config/admin/cli/SetNetworkListenerConfiguration.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/DynamicConfigListener.java
* PAYARA-2781 Exception thrown in logs when shutting down Payara
=> PAYARA-2781 Exception thrown in logs when shutting down Payara

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/AsmSerializableBeanGenerator.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/cdi/interceptor/MetricsInterceptor.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/JCDIServiceImpl.java
**Root cause :**
- Bean<?> injection not supported in JCDIService
- @Inject and @Intercepted annotation not added to constructor of EJB serializable interceptor created by ASM class writer
=> PAYARA-2775 MP Metrics support for @Stateless JAX-RS resource

appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/domain.xml
PAYARA-2827 Add empty java config to prevent null pointer
=> PAYARA-2827 - Payara4

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ApplicationProcessor.java
PAYARA-2830 StackOverflowError in OpenAPI
=> PAYARA-2830 - Payara4

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java, appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/ClusteredCDIEventBusImpl.java
PAYARA-2824 Fixes in CDI event notif.
=> PAYARA-2824 - Payara4

appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/writer/PrometheusExporter.java
https://github.com/payara/Payara/pull/2839
=> PAYARA-2849 - Payara4

appserver/web/admin/src/main/java/fish/payara/grizzly/config/admin/cli/SetNetworkListenerConfiguration.java
for the set-network-listener command
=> PAYARA-2788 Changing port now works for an non-admin http listener - Payara4

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/PEAccessLogValve.java
PAYARA-2822 Access logs are not beeing purged
=> PAYARA-2822 - Payara4

appserver/security/core-ee/src/main/java/com/sun/enterprise/security/provider/JDKPolicyFileWrapper.java
Maintenance PR of: https://github.com/payara/Payara/pull/2883.
=> PAYARA-2874 Enabling Security Manager Causes Log Errors PAYARA4

appserver/admingui/web/src/main/resources/configuration/accessLog.jsf, appserver/admingui/web/src/main/resources/org/glassfish/web/admingui/Strings.properties, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/PEAccessLogValve.java, nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/AccessLog.java
PAYARA-2828 Add rotation on file fize options on Access logging
=> PAYARA-2828 - Add rotation on file fize options on Access logging Payara4

appserver/admingui/common/src/main/resources/configuration/loggerGeneral.jsf, appserver/admingui/common/src/main/resources/org/glassfish/common/admingui/Strings.properties, nucleus/admin/template/src/main/resources/config/logging.properties, nucleus/common/common-util/src/main/java/com/sun/common/util/logging/Constants.java, nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java, nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingPropertyNames.java, nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingXMLNames.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/GFFileHandler.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/SetLogAttributes.java
PAYARA-2843 Add Logging format options to Payara Notification Logger
=> PAYARA-2843 - Add Logging format options to Payara Notification Logger Payara4

nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java
Maintetance PR of: https://github.com/payara/Payara/pull/2873
=>  PAYARA-2870 Log Formatter Isn't Used for ConsoleHandler 4 MAINTENANCE

appserver/admingui/payara-console-extras/src/main/resources/fish/payara/admingui/extras/Strings.properties
=> PAYARA-2722-Notifiers-can-be-made-less-noisy - Payara4

appserver/pom.xml
=> PAYARA-2881 Upgrade EclipseLink to 2.7.2-p1

appserver/admingui/war/src/main/webapp/WEB-INF/sun-web.xml, appserver/pom.xml
Added links to new theme version.
=> PAYARA-2694

appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/DB2PersistenceManager.java, appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/JBatchJDBCPersistenceManager.java, appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/MySqlPersistenceManager.java, appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/OraclePersistenceManager.java, appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/PostgresPersistenceManager.java, appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/SQLServerPersistenceManager.java, appserver/common/glassfish-naming/src/main/java/com/sun/enterprise/naming/util/NamingUtilsImpl.java, appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/PayaraMicroLauncher.java, appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/loader/ExplodedURLClassloader.java, appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/loader/Launcher.java, appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/loader/jar/JarFile.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/RuntimeDirectory.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/UberJarCreator.java, appserver/persistence/cmp/enhancer/src/main/java/com/sun/jdo/api/persistence/enhancer/Main.java, appserver/persistence/cmp/generator-database/src/main/java/com/sun/jdo/spi/persistence/generator/database/DatabaseOutputStream.java, appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/DelegatedRecoveryManager.java, appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/RecoveryManager.java, appserver/web/web-core/src/main/java/org/apache/catalina/session/StandardSession.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/provider/ProgressStatusEventJsonProvider.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/provider/ProgressStatusJsonProvider.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/readers/JsonHashMapProvider.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/readers/JsonParameterMapProvider.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/readers/RestModelListReader.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/readers/RestModelReader.java, nucleus/admin/util/src/main/java/com/sun/enterprise/admin/remote/reader/ProgressStatusEventJsonProprietaryReader.java, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ValidateDcom.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/util/net/NetUtils.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/Syslog.java
Revert "#2674 fixing several resource handling misses (#2896)"
This reverts commit eaeea9984a6ade82deaf7ebe97731c3981bfd8fd.
=> PAYARA-2895 Resolve extensive classloading issues

nucleus/pom.xml
Relies on https://github.com/payara/Payara_PatchedProjects/pull/172.
Incorporates PAYARA-2617 and PAYARA-2892.
=> PAYARA-2892 Updated Grizzly version to 2.4.3.payara-p4.

appserver/connectors/admin/src/main/java/org/glassfish/connectors/admin/cli/FlushConnectionPool.java
(#2917)
* flush-connection-pool is now executed on all instances.
* Added cluster_instance to target types.
=> PAYARA-2732 flush-connection-pool fails in a clustered environment - Payara4

appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java
Backported PAYARA-2666 to Payara 4.
=> PAYARA-2666 Show DeploymentException in Logs

appserver/admingui/payara-console-extras/src/main/java/fish/payara/admingui/extras/rest/PayaraRestApiHandlers.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HealthCheckRebooter.java
Signed-off-by: Mert Caliskan <mert.caliskan@payara.fish>
=> PAYARA-2821 health check checks send multiple notifications when a new notifier is added (Payara 4)

appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/JaxrsContainerRequestTracingFilter.java
https://github.com/payara/Payara/pull/2973
=>  PAYARA-2921 OpenTracing Swallows StackTraces PAYARA4

Jenkinsfile
The intention with this is to have local Jenkins run a job to analyse the PR and decorate the GitHub PR. This file is the Jenkins pipeline (a description of what the job should do).
=> QA-4 Set up sonar PR analysis

appserver/extras/arquillian-containers/payara-common/src/main/java/fish/payara/arquillian/container/payara/clientutils/PayaraClientService.java
AC-3 resolved intermitted NPE when building Payara
=> AC-3 Resolved intermitted NPE when building Payara - Payara4

appserver/extras/arquillian-containers/payara-micro/src/main/java/fish/payara/arquillian/container/payara/managed/PayaraMicroDeployableContainer.java
Now selects the Java version used to run the Arquillian container. Addresses https://github.com/payara/Payara/issues/3007.
=> PAYARA-2953 Payara Micro Arquillian Container Doesn't Use Java Home

nucleus/pom.xml
Fix CDI warnings caused by Jersey:
* https://github.com/payara/Payara_PatchedProjects/commit/cd1d213a9fdcd4d7352b5792887f5ca58a82a9e7
* https://github.com/payara/patched-src-jersey/commit/e1a6aa670b58364fb15af25f049a6d783af3adfa
=> PAYARA-2956 - Update Jersey to 2.27.payara-p8

appserver/admingui/war/src/main/webapp/WEB-INF/sun-web.xml, appserver/pom.xml
=> PARAYA-2925 Background for admin console in IE is wrong colour

appserver/security/jaspic-provider-framework/src/main/java/com/sun/jaspic/config/servlet/HttpMessageInfo.java, appserver/security/webintegration/src/main/java/com/sun/web/security/HttpRequestWrapper.java, appserver/security/webintegration/src/main/java/com/sun/web/security/HttpResponseWrapper.java, appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java, appserver/security/webintegration/src/main/java/com/sun/web/security/realmadapter/AuthenticatorProxy.java, appserver/security/webintegration/src/main/java/com/sun/web/security/realmadapter/JaspicRealm.java, appserver/web/web-core/src/main/java/org/apache/catalina/connector/InputBuffer.java, appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardPipeline.java
=> PAYARA-2970 - JASPIC code split off from realm adapter

appserver/pom.xml
=> PAYARA-3002 Upgrade eclipselink to 2.7.3

nucleus/payara-modules/asadmin-recorder/src/main/java/fish/payara/asadmin/recorder/AsadminRecorderConfiguration.java
…es-in-default-Asadmin-recorder-config
Signed-off-by: Mert Caliskan <mert.caliskan@payara.fish>
=> PAYARA-2966 filter healthcheck list services and notifier list services in default asadmin recorder config (Payara4)

nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/NativeRemoteCommandsBase.java
=> PAYARA-3029 fix ssh node creation on non-standard port - Payara4

nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/NativeRemoteCommandsBase.java
=> PAYARA-3029 fix ssh node creation on non-standard port

appserver/web/web-core/src/main/java/org/apache/catalina/session/CookiePersistentManager.java
=> PAYARA-2926 Cookie session persistence type does not throw exception after maxSessions reached (Payara4)

appserver/admingui/full/src/main/resources/META-INF/admingui/console-config.xml, appserver/admingui/healthcheck-service-console-plugin/src/main/resources/META-INF/admingui/console-config.xml, appserver/admingui/payara-console-extras/src/main/resources/META-INF/admingui/console-config.xml
=> PAYARA-2921 Configurations tree view doesn't list in alphabetically order - Payara4

nucleus/pom.xml
Relies on https://github.com/payara/Payara_PatchedProjects/pull/181.
Incorporates https://github.com/payara/patched-src-grizzly/pull/9.
=> PAYARA-2941 Updated Grizzly to 2.4.3.payara-p5.

appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/auth/login/ProgrammaticLogin.java, appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java, appserver/security/webintegration/src/main/java/com/sun/web/security/realmadapter/JaspicRealm.java, nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/login/ClientCertificateLoginModule.java, nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/login/ClientPasswordLoginModule.java, nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/login/LoginCallbackHandler.java, nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/login/LoginContextDriver.java, nucleus/security/core/src/main/java/com/sun/enterprise/security/common/ClientSecurityContext.java
=> Addressing several warnings

appserver/admingui/web/src/main/java/org/glassfish/web/admingui/handlers/WebHandlers.java, appserver/admingui/web/src/main/resources/configuration/httpListeners.jsf, appserver/admingui/web/src/main/resources/grizzly/networkListeners.jsf, appserver/admingui/web/src/main/resources/serverPageNode.jsf
https://github.com/payara/Payara/pull/3060
=> PAYARA-3027 py.resolveDynamicPort - Payara4

appserver/payara-appserver-modules/microprofile/fault-tolerance/pom.xml, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/FaultToleranceService.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/cdi/FaultToleranceCdiUtils.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/AsynchronousInterceptor.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/BulkheadInterceptor.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/CircuitBreakerInterceptor.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/RetryInterceptor.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/TimeoutInterceptor.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/fallback/FallbackPolicy.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/state/CircuitBreakerState.java, appserver/pom.xml, nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigProviderResolverImpl.java
PAYARA-2721 MicroProfile Fault Tolerance 1.1.1
=> PAYARA-2721-MicroProfile-Fault-Tolerance-1.1 - Payara4

appserver/extras/arquillian-containers/payara-client-ee8/pom.xml, appserver/extras/arquillian-containers/pom.xml, nucleus/pom.xml
Depends on : 
https://github.com/payara/patched-src-jersey/commit/2c04b8fa495bbabf01e9ec591fcb902e442876a4
https://github.com/payara/patched-src-jersey/tree/jersey-2.27.payara-p11
https://github.com/payara/Payara_PatchedProjects/pull/185
=> PAYARA-3038 Jersey JAXB Unmarshalling Error

appserver/payara-appserver-modules/microprofile/metrics/pom.xml, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/MetricsService.java
Made it only initialise when enabled and also initialisation to happen on its own thread
=> PAYARA-2539 Speed up intialisation of metrics boot

appserver/admingui/common/src/main/resources/logViewer/logEntryDetail.jsf
Fixes https://github.com/payara/Payara/issues/3117
=> PAYARA-3079 Log File Viewer Doesn't Show Complete Message

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
Signed-off-by: Steve Millidge <steve.millidge@payara.fish>
=> PAYARA-3069 fix dumb NPE in uber jar packaging

appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/ManagedConnectionImpl.java, appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/util/SQLTraceDelegator.java
PAYARA-3059 don't deregister slow sql logger on every call and make l…
=> PAYARA-3059 Don't deregister slow sql logger on every call and make listeners collection a concurrent hashmap - Payara4

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/util/ModelUtils.java
PAYARA-2837 OpenAPI Incorrect Collection Merging
=> PAYARA-2837 OpenAPI Incorrect Collection Merging - Payara4

nucleus/admin/monitor/src/main/java/org/glassfish/admin/monitor/MonitoringBootstrap.java, nucleus/admin/monitor/src/main/java/org/glassfish/admin/monitor/StatsProviderManagerDelegateImpl.java, nucleus/admin/monitor/src/main/java/org/glassfish/admin/monitor/StatsProviderRegistry.java, nucleus/admin/monitor/src/main/java/org/glassfish/admin/monitor/jvm/JVMClassLoadingStatsProvider.java, nucleus/admin/monitor/src/main/java/org/glassfish/admin/monitor/jvm/JVMCompilationStatsProvider.java, nucleus/admin/monitor/src/main/java/org/glassfish/admin/monitor/jvm/JVMGCStatsProvider.java, nucleus/admin/monitor/src/main/java/org/glassfish/admin/monitor/jvm/JVMMemoryStatsProvider.java, nucleus/admin/monitor/src/main/java/org/glassfish/admin/monitor/jvm/JVMOSStatsProvider.java, nucleus/admin/monitor/src/main/java/org/glassfish/admin/monitor/jvm/JVMRuntimeStatsProvider.java, nucleus/admin/monitor/src/main/java/org/glassfish/admin/monitor/jvm/JVMStatsProviderBootstrap.java, nucleus/admin/monitor/src/main/java/org/glassfish/admin/monitor/jvm/JVMThreadInfoStatsProvider.java, nucleus/admin/monitor/src/main/java/org/glassfish/admin/monitor/jvm/JVMThreadSystemStatsProvider.java, nucleus/admin/monitor/src/main/java/org/glassfish/admin/monitor/jvm/ServerRuntimeStatsProvider.java, nucleus/admin/monitor/src/main/java/org/glassfish/admin/monitor/jvm/statistics/JVMStatsImpl.java, nucleus/admin/monitor/src/main/java/org/glassfish/flashlight/datatree/impl/AbstractTreeNode.java, nucleus/admin/monitor/src/main/java/org/glassfish/flashlight/statistics/impl/AverageImpl.java, nucleus/admin/monitor/src/main/java/org/glassfish/flashlight/statistics/impl/CounterImpl.java, nucleus/admin/monitor/src/main/java/org/glassfish/flashlight/statistics/impl/TimeStatsAbstractImpl.java
=> PAYARA-3096 cleanup nucleus/admin/monitor (Payara4)

appserver/admin/jdk11_template/pom.xml, appserver/admin/jdk11_template/src/main/assembly/jdk11-domain.xml, appserver/admin/jdk11_template/src/main/resources/config/default-web.xml, appserver/admin/jdk11_template/src/main/resources/config/domain.xml, appserver/admin/jdk11_template/src/main/resources/config/glassfish-acc.xml, appserver/admin/jdk11_template/src/main/resources/config/wss-server-config-1.0.xml, appserver/admin/jdk11_template/src/main/resources/config/wss-server-config-2.0.xml, appserver/admin/jdk11_template/src/main/resources/stringsubs.xml, appserver/admin/jdk11_template/src/main/resources/template-info.xml, appserver/admin/jdk11_template_web/pom.xml, appserver/admin/jdk11_template_web/src/main/assembly/jdk11-domain-web.xml, appserver/admin/jdk11_template_web/src/main/resources/config/default-web.xml, appserver/admin/jdk11_template_web/src/main/resources/config/domain.xml, appserver/admin/jdk11_template_web/src/main/resources/config/glassfish-acc.xml, appserver/admin/jdk11_template_web/src/main/resources/config/wss-server-config-1.0.xml, appserver/admin/jdk11_template_web/src/main/resources/config/wss-server-config-2.0.xml, appserver/admin/jdk11_template_web/src/main/resources/stringsubs.xml, appserver/admin/jdk11_template_web/src/main/resources/template-info.xml, appserver/distributions/payara-ml/pom.xml, appserver/distributions/payara-web-ml/pom.xml, appserver/distributions/payara-web/pom.xml, appserver/distributions/payara/pom.xml, appserver/distributions/pom.xml, appserver/packager/glassfish-nucleus/pom.xml
This does not include any JDK9+ specific options
=> PAYARA-3053 Created JDK11 domain template

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/RuntimeDirectory.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/UberJarCreator.java
https://sonarcloud.io/project/issues?id=org.glassfish.main%3Aglassfish-main-aggregator&moduleUuids=AWJyK9hl1B6WA4TgV3i2&resolved=false&severities=BLOCKER&types=BUG
=> Fixing sonar blocker bugs in module Micro Core

nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/provider/ProgressStatusEventJsonProvider.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/provider/ProgressStatusJsonProvider.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/readers/JsonHashMapProvider.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/readers/JsonParameterMapProvider.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/readers/RestModelListReader.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/readers/RestModelReader.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateCommandPostResource.java
https://sonarcloud.io/project/issues?id=org.glassfish.main%3Aglassfish-main-aggregator&moduleUuids=AWJyK9jI1B6WA4TgV4YT&resolved=false&severities=BLOCKER&types=BUG
=> Fixing sonar blocker bugs in module GF Admin Rest Service

appserver/persistence/cmp/generator-database/src/main/java/com/sun/jdo/spi/persistence/generator/database/DatabaseOutputStream.java, appserver/persistence/cmp/generator-database/src/main/java/com/sun/jdo/spi/persistence/generator/database/MappingPolicy.java
https://sonarcloud.io/project/issues?id=org.glassfish.main%3Aglassfish-main-aggregator&moduleUuids=AWJyK9gJ1B6WA4TgV2qO&resolved=false&types=BUG
=> Fixing bugs of blocker and major for module db generator 4 cmp

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ApplicationProcessor.java
=> PAYARA-3116 OpenAPI Fails When Jersey Features are Registered - Payara4

nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/JarUtil.java, nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/Rejar.java, nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/StaticGlassFishRuntime.java, nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/osgi/BundleProvisioner.java, nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/osgi/MinimalBundleProvisioner.java
https://sonarcloud.io/project/issues?id=org.glassfish.main%3Aglassfish-main-aggregator&moduleUuids=AWJyK9jc1B6WA4TgV4lM&resolved=false&types=BUG
=> Fixing sonar bugs of module Appserver core bootstrapping classes PAYARA-3181

appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/FaultToleranceObject.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/FaultToleranceService.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/BulkheadInterceptor.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/CircuitBreakerInterceptor.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/state/CircuitBreakerState.java
PAYARA-3075 Tie Bulkheads and CircuitBreakers to Bean instances
=> PAYARA-3075 Rework Fault Tolerance so that Bulkhead and CircuitBreaker are tied to instances instead of applications - Payara4

nucleus/security/core/src/main/java/com/sun/enterprise/security/cli/CreateFileUser.java, nucleus/security/core/src/main/java/com/sun/enterprise/security/cli/DeleteFileUser.java
Signed-off-by: Steve Millidge <steve.millidge@payara.fish>
=> PAYARA-3166 Prevent showing of spurious error on command replication

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/EJBUtils.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/base/io/EJBObjectOutputStreamHandler.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/BaseContainer.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/interceptors/CallbackInvocationContext.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/interceptors/InterceptorUtil.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/util/pool/BlockingPool.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/util/pool/NonBlockingPool.java, appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/descriptor/ContainerTransaction.java
https://sonarcloud.io/project/issues?id=org.glassfish.main%3Aglassfish-main-aggregator&moduleUuids=AWJyK9fq1B6WA4TgV2XN&resolved=false&types=BUG
=> Fixing bugs of blocker and major for module GF core EJB container impl

nucleus/pom.xml
Depends on : https://github.com/payara/Payara_PatchedProjects/pull/194
=> PAYARA-3137 Jersey patch version 2.27.payara-p12

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ConcurrentRuntime.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java, appserver/pom.xml
Depends on : https://github.com/payara/Payara_PatchedProjects/pull/193
=> PAYARA-3122 Managed Scheduled Executor Service still executes tasks after undeployment (Payara 4.x)

appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/loader/ExplodedURLClassloader.java, appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/loader/jar/JarFile.java
https://sonarcloud.io/project/issues?id=org.glassfish.main%3Aglassfish-main-aggregator&moduleUuids=AWJyK9hj1B6WA4TgV3iB&resolved=false&rules=squid%3AS2095&severities=BLOCKER%2CCRITICAL%2CMAJOR&types=BUG
=> Fixing blocker bugs in Payara micro boot module

nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/GroupMapper.java, nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/ldap/LDAPRealm.java
=> #3301 fixing Web Console 403 LDAPRealm.getGroupNames Exception

nucleus/deployment/common/src/main/java/com/sun/enterprise/deploy/shared/FileArchive.java, nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/ModuleExploder.java
https://sonarcloud.io/project/issues?id=org.glassfish.main%3Aglassfish-main-aggregator&moduleUuids=AWJyK9jW1B6WA4TgV4hV&resolved=false&severities=BLOCKER%2CCRITICAL%2CMAJOR&types=BUG
=> PAYARA-3192 - Fixing blocker bugs in Deployment related classes module

nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/Syslog.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/logviewer/backend/LogFile.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/logviewer/backend/LogFilterForInstance.java
https://sonarcloud.io/project/issues?id=org.glassfish.main%3Aglassfish-main-aggregator&moduleUuids=AWJyK9ja1B6WA4TgV4kC&resolved=false&rules=squid%3AS2095&types=BUG
=> PAYARA-3193 - Fixing blocker bugs in module nucleus logging

appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/SignedJWTIdentityStore.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jwt/JwtTokenParser.java
https://sonarcloud.io/project/issues?id=org.glassfish.main%3Aglassfish-main-aggregator&moduleUuids=AWJyK9hu1B6WA4TgV3of&resolved=false&rules=squid%3AS2095&severities=BLOCKER%2CCRITICAL%2CMAJOR&types=BUG
=> Fixing blocker bugs in microprofile jwt module

appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/cdi/TracedInterceptor.java
=> PAYARA-3110 Made TracedInterceptor serializable (payara4)

appserver/web/web-glue/src/main/java/com/sun/appserv/web/cache/DefaultCacheHelper.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/PEAccessLogValve.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebContainer.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/accesslog/DefaultAccessLogFormatterImpl.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/connector/coyote/PECoyoteConnector.java, appserver/web/web-glue/src/main/java/org/glassfish/web/jsp/JSPCompiler.java
https://sonarcloud.io/project/issues?id=org.glassfish.main%3Aglassfish-main-aggregator&moduleUuids=AWJyK9gm1B6WA4TgV28B&resolved=false&types=BUG
=> PAYARA-3197 - Fixing sonar bugs blocker and major in web glue module

appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/WebServiceContextImpl.java, appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/WebServicesDeployer.java, appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/monitoring/WebServiceTesterServlet.java
https://sonarcloud.io/project/issues?id=org.glassfish.main%3Aglassfish-main-aggregator&moduleUuids=AWJyK9g91B6WA4TgV3Kw&resolved=false&types=BUG
=> PAYARA-3211 Fixing sonar blocker bugs in JSR-109 impl module

Jenkinsfile-MicroProfile, Jenkinsfile-Nightly
In addition to https://github.com/payara/Payara/pull/3347
=> INFRA-167 Change test branches from master to jenkins

Jenkinsfile-MicroProfile
In addition to https://github.com/payara/Payara/pull/3348
=> INFRA-167 Make Jenkins use a different test branch

appserver/extras/embedded/all/pom.xml, appserver/extras/embedded/web/pom.xml, appserver/payara-appserver-modules/healthcheck-checker/pom.xml
Add Micro service to embedded and remove unnecessary dependencies
=> PAYARA-3239 ClassNotFoundException in Payara Embedded

appserver/admingui/war/src/main/webapp/WEB-INF/sun-web.xml, appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/colorAndMedia_ja.css, appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/colorAndMedia_ko.css, appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/colorAndMedia_zh_CN.css, appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/colorAndMedia_zh_TW.css, appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/layout_ja.css, appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/layout_ko.css, appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/layout_zh_CN.css, appserver/admingui/webui-jsf-suntheme-plugin-l10n/src/main/resources/com/sun/webui/jsf/suntheme/css/layout_zh_TW.css, appserver/pom.xml
=> PAYARA-3231 It appears that with Firefox 63, that the Payara admin web screens no longer work correctly

appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/MetricsService.java
Prevents NPE on Payara Micro due to unmarshal exception on boot.
=> PAYARA-3199 Add null check for bootstrap of metrics

Jenkinsfile-Nightly
Upload Nightly Build after running quicklook, rather than after running through all of them.
=> INFRA-174 Upload Nightly Builds Earlier

appserver/pom.xml
Depends on: https://github.com/payara/Payara_PatchedProjects/pull/201.
=> Updated Weld Version to 3.0.5.Final.payara-p1

appserver/payara-appserver-modules/jmx-monitoring-service/src/main/java/fish/payara/jmx/monitoring/JMXMonitoringService.java
As part of the thread usage reduction task refactor the JMX Monitoring Service to use the Payara Scheduled Executor Service
=> PAYARA-3253 Refactor JMX Monitoring Service to use the Payara Executor Service

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/DynamicReloadService.java
Part of the thread usage reduction task. Moved scheduled dynamicreloader to the general Payara Executor Service.
=> PAYARA-3249 Move Timer Task in DynamicReloader to Payara Executor Service

appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java, nucleus/security/core/src/main/java/com/sun/enterprise/security/ssl/GlassfishSSLImpl.java, nucleus/security/core/src/test/java/com/sun/enterprise/security/ssl/GlassfishSSLImplTest.java
PAYARA-3171 cherry-picked https://github.com/payara/Payara/commit/9ea2b82aca2e5c4f481894bf45035e3c1c8dd39d
And added extra check for if principal is X500Name again.
=> PAYARA-3171 custom keystore

nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/CreateNodeConfigCommand.java, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ServerSynchronizer.java
Maintenance PR of: https://github.com/payara/Payara/pull/3439.
=> Reverted System Specific Path Variables - Payara4

appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionScopedCDIUtil.java
=> PAYARA-3120 added EE contexts for CDI @TransactionScoped extension invocations

appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionScopedCDIUtil.java
Reverts payara/Payara#3446 due to failing internal test. See JIRA for more info.
=> Revert "PAYARA-3120 added EE contexts for CDI @TransactionScoped extension invocations"

nucleus/pom.xml
* https://github.com/payara/Payara_PatchedProjects/pull/203
* https://github.com/payara/patched-src-felix/pull/1
=> PAYARA-455 fileinstall will no longer eagerly create directory

nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/CreateNodeConfigCommand.java
As per comments raised in https://github.com/payara/Payara/pull/3439
=> Change slash to File.separator

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/visitor/OpenApiWalker.java
Maintenance PR of: https://github.com/payara/Payara/pull/3505
=> PAYARA-3258 Disabled Path Based Annotations For Interfaces - Payara4

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/visitor/OpenApiWalker.java
=> Revert "PAYARA-3258 Disabled Path Based Annotations For Interfaces"

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/visitor/OpenApiWalker.java
=> Revert "PAYARA-3258 Disabled Path Based Annotations For Interfaces - Payara4"

nucleus/pom.xml
Requires https://github.com/payara/Payara_PatchedProjects/pull/206
=> PAYARA-3257 Jersey 2.25.1.payara-p6

nucleus/pom.xml
Requires https://github.com/payara/Payara_PatchedProjects/pull/205
=> PAYARA-3257 Jersey 2.27.payara-p14

appserver/admingui/war/src/main/webapp/WEB-INF/sun-web.xml, appserver/pom.xml
Depends on https://github.com/payara/Payara_PatchedProjects/pull/207.
=> PAYARA-3308 Upgrade PrototypeJS version used in the Admin Console

nucleus/pom.xml
Depends on: https://github.com/payara/Payara_PatchedProjects/pull/213.
Needs fairly rigorous testing.
=> PAYARA-3031 HTTP/2 Trailer Issue

nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/CollectionLeafResource.java
=> PAYARA-3376-Some-JVM-parameters-are-not-correctly-stored-through-the-Web-Admin-Console-Payara4

appserver/admingui/common/pom.xml, appserver/connectors/work-management/pom.xml, appserver/extras/javaee/manifest-jar/pom.xml, appserver/extras/payara-micro/payara-micro-microprofile-distribution/pom.xml, appserver/javaee-api/javax.javaee-web-api/pom.xml, appserver/packager/glassfish-common-web/pom.xml, appserver/pom.xml, appserver/security/core-ee/pom.xml, appserver/security/jaspic-provider-framework/pom.xml, appserver/security/security-all/pom.xml, appserver/security/webintegration/pom.xml
=> PAYARA-3428 Integrate Jakarta version of JASPIC API

nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/CLICommand.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/LoginCommand.java
Payara4 version of https://github.com/payara/Payara/pull/3528
=> PAYARA-3357 Fix Interactive Asadmin Prompt Errors - Payara4

appserver/common/container-common/pom.xml, appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/util/ClusteredSingletonLookupImplBase.java, appserver/ejb/ejb-container/pom.xml, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/ClusteredSingletonLookupImpl.java, appserver/payara-appserver-modules/payara-micro-cdi/pom.xml, appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/cluster/ClusterScopedInterceptor.java, appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/cluster/ClusteredAnnotatedType.java, appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/cluster/ClusteredAnnotationProcessor.java, appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/cluster/ClusteredSingletonLookupImpl.java, appserver/tests/quicklook/ejb/remoteview/pom.xml, appserver/tests/quicklook/ejb/remoteview/src/test/RemoteViewTestNG.java, appserver/web/gf-web-connector/pom.xml, appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/ContextImpl.java, appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/JavaEEContextUtilImpl.java, nucleus/common/internal-api/src/main/java/org/glassfish/internal/api/JavaEEContextUtil.java, nucleus/payara-modules/hazelcast-bootstrap/pom.xml, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/contextproxy/CacheManagerProxy.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/contextproxy/CacheProxy.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/contextproxy/CachingProviderProxy.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/contextproxy/CompleteConfigurationProxy.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/contextproxy/EntryProcessorProxy.java, nucleus/pom.xml
This PR removes the dependency from the project and includes the changes do in PRs #3642 #3641 #3640 #3639 #3638.
=> Removed usage of lombok

appserver/admingui/war/src/main/webapp/WEB-INF/sun-web.xml, appserver/pom.xml
Maintenance PR of https://github.com/payara/Payara/pull/3519.
=> PAYARA-3308 Upgrade PrototypeJS PAYARA4

Jenkinsfile, nucleus/common/common-util/src/main/java/com/sun/appserv/util/cache/BaseCache.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/ASURLClassLoader.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/SystemProps.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/xml/MiniXmlParser.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/util/ExceptionUtil.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/util/LocalStringManagerImpl.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/util/ObjectAnalyzer.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/util/StringUtils.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/util/SystemPropertyConstants.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/util/i18n/StringManager.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/util/i18n/StringManagerBase.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/util/io/FileUtils.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/util/uuid/UuidUtilPadded.java, nucleus/common/common-util/src/main/java/org/glassfish/common/util/StringHelper.java, nucleus/common/common-util/src/main/java/org/glassfish/common/util/timer/TimerSchedule.java
=> Jenkins dev

appserver/web/admin/src/main/java/org/glassfish/web/admin/cli/ListProtocolFilters.java
=> PAYARA-3449-list-protocol-filters-command-fails-with-NPE

appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/JaxrsContainerRequestTracingExceptionMapper.java
Maintenance PR of: https://github.com/payara/Payara/pull/3451
=> PAYARA-3262 dont create a new response in the jaxrs container exception mapper - Payara4

nucleus/pom.xml
Depends on https://github.com/payara/Payara_PatchedProjects/pull/218
=> PAYARA-2890 HTTP/2 Server Push Issues

appserver/batch/hazelcast-jbatch-store/pom.xml, appserver/ha/ha-hazelcast-store/pom.xml, appserver/pom.xml, nucleus/packager/hazelcast-package/pom.xml, nucleus/payara-modules/hazelcast-bootstrap/pom.xml, nucleus/payara-modules/jsr107-repackaged/pom.xml, nucleus/payara-modules/notification-core/pom.xml, nucleus/pom.xml
Based on PR review changes of #3699
=> PAYARA-3422 Clean up payara pom

appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/payara-boot.properties
Fixes #3734. Also added a comment to avoid this issue in the future
=> Add a newline at the end

nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java
Fixes bug introduced with https://github.com/payara/Payara/pull/3629/files where instance wouldn't log anything.
=> PAYARA-3160 Minimum Log File Size Error Ignored - Payara4 Part 2

appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/IIOPSSLSocketFactory.java
Fixes some silly mistakes introduced in the fix for PAYARA-546: https://github.com/payara/Payara/pull/3534
=> PAYARA-3478 Fix Port Usage and Logic in PAYARA-546

appserver/tests/quicklook/testng/testng_gd.xml
The test seems to be failing sporadically based on a build issue.
Jira to fix it: QA-185
=> PAYARA-3502 Temp disable test - Payara4

appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/FormAuthenticator.java
=> PAYARA-3318 Restrict permitted HTTP method for FORM based auth (Payara p4.x)

nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HealthCheckConfigurer.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HealthCheckServiceConfigureCheckerWithThresholdsCommand.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HealthCheckServiceConfigurer.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HealthCheckServiceThresholdConfigurer.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HoggingThreadsConfigurer.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/ListHealthCheckServices.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/SetHealthCheckConfiguration.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/SetHealthCheckServiceConfiguration.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/SetHealthCheckServiceNotifierConfiguration.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/notifier/CDIEventbusHealthCheckNotifierConfigurer.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/notifier/DatadogHealthCheckNotifierConfigurer.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/notifier/EmailHealthCheckNotifierConfigurer.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/notifier/EventbusHealthCheckNotifierConfigurer.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/notifier/HipchatHealthCheckNotifierConfigurer.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/notifier/JmsHealthCheckNotifierConfigurer.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/notifier/LogHealthCheckNotifierConfigurer.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/notifier/NewRelicHealthCheckNotifierConfigurer.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/notifier/SlackHealthCheckNotifierConfigurer.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/notifier/SnmpHealthCheckNotifierConfigurer.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/notifier/XmppHealthCheckNotifierConfigurer.java, nucleus/payara-modules/healthcheck-stuck/src/main/java/fish/payara/nucleus/healthcheck/stuck/admin/StuckThreadsConfigurer.java
=> PAYARA-1896 Unified asadmin command to set health check configuration (Payara 4.x)

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/boot/runtime/MicroGlassFish.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/RUNTIME_OPTION.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java, nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/GlassFishImpl.java
=> PAYARA-3344 Added System Property for Shutdown Grace Period (Payara 4.x)

appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/CircuitBreakerInterceptor.java
Maintenance of: https://github.com/payara/Payara/pull/3768/files
Looks like a commit might have been missed at some point given the difference.
=> PAYARA-3512 Check for failOn override on correct annotation - Payara4

appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/CircuitBreakerInterceptor.java
Should fix https://groups.google.com/forum/#!topic/payara-forum/dA9T4rGP91Q
=> PAYARA-3511 Don't try to cast a String to a ChronoUnit

appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/interceptors/CircuitBreakerInterceptor.java
Maintenance of: https://github.com/payara/Payara/pull/3765
=> PAYARA-3511 Don't try to cast a String to a ChronoUnit - Payara4

appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/IIOPSSLSocketFactory.java
Maintenance of: https://github.com/payara/Payara/pull/3727
=> PAYARA-3478 Fix Port Usage and Logic in PAYARA-546 - Payara4

nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/certificate/CertificateRealm.java
Weirdly, this is a maintenance PR of https://github.com/payara/Payara/pull/3766.
Wasn't applicable to the other files.
=> PAYARA-3373 Certificate Realms With Custom JCE Provider Still Raise Exceptions

nucleus/deployment/common/pom.xml, nucleus/deployment/common/src/main/java/org/glassfish/loader/util/ASClassLoaderUtil.java
=> PAYARA-3499 Optimisation of ASClassLoaderUtil - Payara4

appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/domain.xml
Maintenance of https://github.com/payara/Payara/pull/3759
=> PAYARA-3507 Micro Executor Pool Size - Payara4

appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/ConnectionPool.java, appserver/connectors/connectors-runtime/src/main/resources/com/sun/enterprise/resource/pool/LocalStrings.properties
…nterrupted
This instead of throwing a NPE a short while later
=> PAYARA-3508 Throw informative error in ConnectionPool.getResouce if Interrupted - Payara4

appserver/pom.xml
Relies on https://github.com/payara/Payara_PatchedProjects/pull/225
Effective change: https://github.com/payara/patched-src-mojarra/commit/1f482efaa6e8f797d4b881744a08394a3e5d606a
=> PAYARA-3520 Update Mojarra to 2.3.9.payara-p2

appserver/payara-appserver-modules/microprofile/healthcheck/src/main/java/fish/payara/microprofile/healthcheck/HealthCheckService.java
=> PAYARA-3438: Improve usability MP Health endpoint as readinessProbe - Payara4
