appserver/payara-appserver-modules/jaxrs-client-tracing/src/main/java/fish/payara/requesttracing/jaxrs/client/JaxrsClientRequestTracingFilter.java, appserver/payara-appserver-modules/jaxrs-client-tracing/src/main/java/fish/payara/requesttracing/jaxrs/client/decorators/JaxrsClientBuilderDecorator.java, appserver/payara-appserver-modules/jaxrs-client-tracing/src/main/java/fish/payara/requesttracing/jaxrs/client/decorators/JaxrsClientDecorator.java, appserver/payara-appserver-modules/jaxrs-client-tracing/src/main/java/fish/payara/requesttracing/jaxrs/client/decorators/JaxrsInvocationBuilderDecorator.java, appserver/payara-appserver-modules/jaxrs-client-tracing/src/main/java/fish/payara/requesttracing/jaxrs/client/decorators/JaxrsWebTargetDecorator.java, appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/cdi/TracedInterceptor.java, appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/JaxrsContainerRequestTracingFilter.java, nucleus/packager/external/opentracing-repackaged/pom.xml, nucleus/payara-modules/opentracing-adapter/src/main/java/fish/payara/opentracing/OpenTracingService.java, nucleus/pom.xml
Maintenance of https://github.com/payara/Payara/pull/3750
=> PAYARA-3261 OpenTracing 1.3 - Payara4

nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/MultimodeCommand.java
Maintenance of https://github.com/payara/Payara/pull/3757
=> PAYARA-3505 Disable Option for JLine Logging in Asadmin Multimode - Payara4

appserver/pom.xml
Depends on https://github.com/payara/Payara_PatchedProjects/pull/226 and https://github.com/payara/Payara_PatchedProjects/pull/227
=> PAYARA-3387 Updated Metro to 2.4.3.payara-p1

pom.xml
Missed at top level in https://github.com/payara/Payara/pull/3566
=> PAYARA-3402 Missed javadoc version property

Jenkinsfile
Adds sonar analysis to the (PR) Jenkinsfile. Webhooks already configured, so once this has been merged to master all subsequent PRs should be decorated with sonar reports
=> QA-3 Sonar PR analysis

Jenkinsfile
=> Revert "QA-3 Sonar PR analysis"

appserver/packager/glassfish-ejb/pom.xml, nucleus/admin/template/pom.xml
Changed the package names missing from original refactor
=> Fixed missing pom refactor [PAYARA-3563]

appserver/tests/quicklook/testng/testng_gd.xml
This reverts commit 37f39f6b4b594991736d770d98050432a663dbe3.
=> Revert "QA-171 Ignoring test until fixed"

appserver/pom.xml
Bug identified as eclipselink bug, waits for payara/Payara_PatchedProjects#236
=> PAYARA-3493: Upgrade eclipselink to 2.7.4.payara-p2

pom.xml
Alternative implementation to #3826
=> PAYARA-3540: Use no-fork javadoc invocation and package the jar manually

appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/GlassFishORBManager.java, nucleus/pom.xml
Depends on :
https://github.com/payara/patched-src-glassfish-corba/pull/9
https://github.com/payara/patched-src-glassfish-corba/pull/10
https://github.com/payara/Payara_PatchedProjects/pull/238
=> PAYARA-3484 JDK11 Java EE 7 Sample: ejb - remote - Roles Allowed testcase fix

appserver/security/jacc.provider.file/src/main/java/com/sun/enterprise/security/provider/JDKPolicyFileWrapper.java
PAYARA-3722 Sonar cleanups, but also fixes PAYARA-3722
=> PAYARA-3722 - Sonar cleanups in JDKPolicyFileWrapper

Jenkinsfile, Jenkinsfile-Nightly, appserver/admin/gf_template/src/main/resources/config/domain.xml, appserver/admin/gf_template_web/src/main/resources/config/domain.xml, appserver/admin/production_domain_template/src/main/resources/config/domain.xml, appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml, appserver/admingui/reference-manual/src/main/help/en/help/reference/list-jvm-options.html, appserver/batch/glassfish-batch-connector/pom.xml, appserver/common/glassfish-ee-api/src/main/java/com/sun/appserv/ClassLoaderUtil.java, appserver/connectors/connectors-runtime/pom.xml, appserver/core/api-exporter-fragment/pom.xml, appserver/installer/src/cpp/share/launcher/java.c, appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/IIOPSSLSocketFactory.java, appserver/persistence/cmp/enhancer/src/main/java/com/sun/jdo/api/persistence/enhancer/EnhancerClassLoader.java, appserver/persistence/cmp/enhancer/src/main/java/com/sun/jdo/api/persistence/enhancer/URLClassPath.java, appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/GSSUtils.java, appserver/tests/quicklook/pom.xml, appserver/web/weld-integration-fragment/pom.xml, appserver/web/weld-integration-test-fragment/pom.xml, appserver/web/weld-integration/osgi.bundle, nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/JavaConfig.java, nucleus/core/bootstrap/pom.xml, nucleus/core/extra-jre-packages/pom.xml, nucleus/core/kernel/src/main/manpages/com/sun/enterprise/v3/admin/commands/list-jvm-options.1, nucleus/packager/nucleus-grizzly/pom.xml, nucleus/packager/nucleus/src/main/resources/lib/package-appclient.xml
Depends on https://github.com/javaee-samples/javaee7-samples/pull/449/
=> PAYARA-3577 Build Payara Server & Payara Micro using JDK8 and get them to pass the Test Suite

api/payara-api/src/main/java/fish/payara/security/openid/api/OpenIdState.java, appserver/payara-appserver-modules/security-openid/src/main/java/fish/payara/security/openid/OpenIdAuthenticationMechanism.java, appserver/payara-appserver-modules/security-openid/src/main/java/fish/payara/security/openid/controller/StateController.java
See sonar finding https://sonarcloud.io/project/issues?id=org.glassfish.main%3Aglassfish-main-aggregator&open=AWoN7ILp9zLXaOU8UM1S&resolved=false&sinceLeakPeriod=true&types=BUG
=> PAYARA-3784 Fixed OpenIdState equals method

nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/StartServerHelper.java, nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/services/AppserverServiceType.java, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/StartInstanceCommand.java, nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/StartLocalInstanceCommand.java
PAYARA-3688 Timeout option also propagates from start-instance
=> PAYARA-3688 Added timeout option to start-local-instance

appserver/packager/microprofile-package/pom.xml, nucleus/pom.xml
Artifact name for MP client changed
Tested Microprofile TCKs.
Depends on payara/Payara_PatchedProjects#247
=> PAYARA-3482: Upgrade Jersey version

appserver/ejb/ejb-http-remoting/client/pom.xml, appserver/ejb/ejb-http-remoting/client/src/main/java/fish/payara/ejb/http/client/EjbHttpProxyFactory.java
Also removed dependency to jersey internals
=> Generate clean OSGi manifest for ejb-http-client

appserver/persistence/gf-jpa-connector/src/main/java/org/glassfish/persistence/jpaconnector/JPASniffer.java, appserver/resources/resources-connector/src/main/java/org/glassfish/resources/util/ResourceUtil.java, appserver/web/gf-weld-connector/src/main/java/org/glassfish/weld/connector/WeldSniffer.java, appserver/web/gf-weld-connector/src/main/java/org/glassfish/weld/connector/WeldUtils.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/BeanDeploymentArchiveImpl.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/DeploymentImpl.java, nucleus/common/internal-api/src/main/java/org/glassfish/internal/deployment/GenericSniffer.java
Fixes #3939 
As the error sounds like a race condition which are hard to track by nature I have focused on  preventing the NPE from happening. This may lead to some follow up problems which were hidden by the NPE but I don't expect them to happen at a higher rate than the NPE. Additionally this might lead to a better understanding of the root cause.
I have found several other spots where there already were NULL checks in place. Probably for similar reasons.
=> PAYARA-3820 - Fixing sporadic NPE when archive has no JPA beans

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
Fixes https://github.com/payara/Payara/issues/3800
=> PAYARA-3541 Error deploying exploded WAR

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/RestUtil.java
Original changes were too generalised and caused issues with checkbox values being saved - created a special case for the saving of system properties to amend this
=> [PAYARA-3812] - Fixed issue with checkboxes causing errors due to changes

appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/cdi/TracedInterceptor.java, appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/MonitoringPipe.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/InvocationManager.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/InvocationManagerImpl.java
This fix stores the current webservice method invocation into the
invocation context.
=> PAYARA-3827 Fixed JAX-WS tracing bug by checking for webservice method

appserver/featuresets/payara/pom.xml, appserver/packager/opentracing-jaxws-package/pom.xml, appserver/packager/opentracing-jaxws-package/src/main/assembly/opentracing-jaxws-package.xml, appserver/packager/opentracing-jaxws-package/src/main/resources/pkg_proto.py, appserver/packager/pom.xml, appserver/payara-appserver-modules/microprofile/opentracing-jaxws/pom.xml, appserver/payara-appserver-modules/microprofile/opentracing-jaxws/src/main/java/fish/payara/opentracing/jaxws/JaxwsContainerRequestTracingFilter.java, appserver/payara-appserver-modules/microprofile/opentracing-jaxws/src/main/java/fish/payara/opentracing/jaxws/OpenTracingJaxwsCdiUtils.java, appserver/payara-appserver-modules/microprofile/opentracing/pom.xml, appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/cdi/OpenTracingCdiUtils.java, appserver/payara-appserver-modules/microprofile/pom.xml
Gets around web dist not having required JAX-WS dependencies
=> PAYARA-3385 Move JAX-WS tracing into its own module

README.md
=> PAYARA-3817 - Updated readme to indicate JDK 11 preview support and MP 2.2

appserver/packager/microprofile-package/pom.xml
Updates REST Client to version from payara/Payara_PatchedProjects#248
The test case is present in pdudits/data-replication-talk (`ReplicationIT` in `consumer-app`).
Another testcase was added to [upstream](https://github.com/payara/patched-src-jersey/pull/20/files#diff-2e366f66b6244208226da5cbdbc5ba63)
=> PAYARA-3859: Update Microprofile Rest Client

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/gadget/GadgetHandlers.java, appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/CommonHandlers.java, appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/TagSupport.java, appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/GuiUtil.java, appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/JSONUtil.java, appserver/admingui/core/src/main/java/org/glassfish/admingui/util/SunOptionUtil.java, appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/NestedAppClientDeployerHelper.java, appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/jws/JWSAdapterManager.java, appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/jws/RestrictedContentAdapter.java, appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/jws/XPathToDeveloperProvidedContentRefs.java, appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/JBatchJDBCPersistenceManager.java, appserver/batch/glassfish-batch-connector/src/main/java/org/glassfish/batch/spi/impl/BatchRuntimeHelper.java, appserver/common/amx-javaee/src/main/java/org/glassfish/admin/amx/impl/j2ee/RegistrationSupport.java, appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/EntityManagerWrapper.java
Moved to Major sonar issues (bugs). This PR is almost exclusivity preventing NPEs from happening at locations identified by sonar. I annotated more complicated places.
=> Cleanup sonar issues 3 - potential NPEs

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/ApplicationHandlers.java, appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/WebAppHandlers.java, appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/AppUtil.java, appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/DeployUtil.java, appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/GuiUtil.java, appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/RestResponse.java, appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/RestUtil.java, appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/TargetUtil.java, appserver/admingui/payara-console-extras/src/main/java/fish/payara/admingui/extras/rest/PayaraRestApiHandlers.java
Started extracted constants as indicated by sonar and got side tracked filling in generics in classes full of raw types. 
Reviewers should look out for generics added to something that would be considered public API and therefore should not change. As everything is part of the `admingui` to my knowledge it should be fine and not be problematic for 3rd party users.
=> Cleanup sonar issues 8 - Extracting constants and Adding generics

appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/PayaraMicroLauncher.java, appserver/ha/ha-file-store/src/main/java/org/glassfish/ha/store/adapter/file/FileBackingStore.java, appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/DMManagedConnectionFactory.java, appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/ManagedConnectionFactoryImpl.java, appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/JaxrsContainerRequestTracingFilter.java, appserver/payara-appserver-modules/payara-jsr107/src/main/java/fish/payara/cdi/jsr107/implementation/PayaraCacheKeyInvocationContext.java, appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/micro/services/data/InstanceDescriptorImpl.java, appserver/persistence/cmp/ejb-mapping/src/main/java/com/sun/jdo/api/persistence/mapping/ejb/CaptureSchema.java, appserver/persistence/cmp/ejb-mapping/src/main/java/com/sun/jdo/api/persistence/mapping/ejb/MappingFile.java, appserver/persistence/cmp/ejb-mapping/src/main/java/com/sun/jdo/api/persistence/mapping/ejb/SunCmpMappingsUtils.java, appserver/persistence/cmp/enhancer/src/main/java/com/sun/jdo/api/persistence/enhancer/PersistenceLauncher.java
Major sonar issues (bugs). Focussed on potential NPEs. Sometimes I also cleaned other problems found at the same location. As before I annotate the changes that are less trivial and require bit of context.
=> Cleanup sonar issues 6 - potential NPEs

nucleus/pom.xml
Signed-off-by: smillidge <steve.millidge@payara.fish>
=> PAYARA-3881 Upgraded Jackson to 2.9.9

appserver/admingui/cluster/src/main/resources/shared/handlers.inc
=> PAYARA-3895 Fix check for if name is in use by deployment group

appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/impl/WeightedSnapshot.java, appserver/web/web-ha/src/main/java/org/glassfish/web/ha/authenticator/HASingleSignOnEntry.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/composite/CompositeUtil.java, nucleus/flashlight/framework/src/main/java/org/glassfish/flashlight/provider/FlashlightProbe.java
Cleanup of blocker and critical sonar issues (bugs) hand picked from our sonar issues trying to fix more severe first. As the issues do not have a common theme except their severity I annotated the changes with some context or thoughts.
=> Cleanup sonar issues 1 - Resources + Misc

nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/generator/TextResourcesGenerator.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/GenerateBashAutoCompletionCommand.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/ContainerMapper.java, nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/InstanceDeployCommand.java, nucleus/flashlight/framework/src/main/java/org/glassfish/flashlight/impl/provider/FlashlightProbeProviderFactory.java, nucleus/osgi-platforms/osgi-cli-interactive/src/main/java/org/glassfish/osgi/cli/interactive/LocalOSGiShellCommand.java
Cleanup of blocker and critical sonar issues (bugs) hand picked from our sonar issues trying to fix more severe first. As the issues do not have a common theme except their severity I annotated the changes with some context or thoughts.
=> Cleanup sonar issues 2 - Resources + Misc

appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/spi/util/JavaEEObjectStreamFactory.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java, appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/api/ConnectorsUtil.java, appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/util/DriverLoader.java, appserver/core/javaee-kernel/src/main/java/org/glassfish/kernel/javaee/WebContainerStarter.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/EnvironmentProperty.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/node/DeploymentDescriptorNode.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/node/ResourcePropertyNode.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/util/ComponentValidator.java
Major sonar issues (bugs). Focussed on potential NPEs. Sometimes I also cleaned other problems found at the same location. As before I annotate the changes that are less trivial and require bit of context.
=> Cleanup sonar issues 4 - potential NPEs

nucleus/pom.xml
Fixes #3994, needs payara/Payara_PatchedProjects#250 to be merged first.
=> PAYARA-3908: Upgrade Jersey to version with a fix

appserver/admingui/cluster/src/main/resources/node/nodeNew.jsf, appserver/docker/src/main/java/fish/payara/docker/DockerConstants.java, appserver/docker/src/main/java/fish/payara/docker/node/admin/CreateNodeDockerCommand.java
Also fix autofill on admin console
=> PAYARA-3875 Correct default docker image name

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java
Follow on from comments made on PR after merge: https://github.com/payara/Payara/pull/4043
=> PAYARA-3928 Alternative solution

nucleus/distributions/payara-minimal/pom.xml
=> PAYARA-3775 Disabled failing domain creation in payara-minimal module

nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/mbean/LoggingImpl.java, nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/store/LocalRequestTraceStore.java
Quickly fixed two occurrences of errors that IDE reports as such which gets kind of annoying.
=> Fixed random errors identified by IDE

appserver/pom.xml
Depends on : 
https://github.com/payara/patched-src-yasson/pull/4
https://github.com/payara/Payara_PatchedProjects/pull/261
=> PAYARA-3992 Updated Yasson Version to 1.0.4.payara-p2

nucleus/core/logging/src/main/java/fish/payara/enterprise/server/logging/JSONLogFormatter.java
=>  JSONLogFormatter causes NPE with logged exception without message

appserver/deployment/javaee-core/src/main/java/org/glassfish/javaee/core/deployment/DolProvider.java, nucleus/common/internal-api/src/main/java/org/glassfish/internal/data/ApplicationInfo.java, nucleus/common/internal-api/src/main/java/org/glassfish/internal/data/ModuleInfo.java, nucleus/common/internal-api/src/main/java/org/glassfish/internal/deployment/DeploymentTracing.java, nucleus/common/internal-api/src/main/java/org/glassfish/internal/deployment/GenericHandler.java, nucleus/common/internal-api/src/main/java/org/glassfish/internal/deployment/analysis/DeploymentSpan.java, nucleus/common/internal-api/src/main/java/org/glassfish/internal/deployment/analysis/StructuredDeploymentTracing.java, nucleus/common/internal-api/src/main/java/org/glassfish/internal/deployment/analysis/TraceContext.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java, nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/DeployCommand.java
Use consistent container names, document what I think the individual actions represent and compute nesting levels of individual spans. Current trace output looks like this: (without the headers)
```
Start			Finish			Nest  Container	Context				Action  Component	Duration
16:05:03.268000000	16:08:52.827000000	1		APPLICATION dataverse.war	null		229559
16:05:03.268000000	16:05:03.269000000	2		APPLICATION dataverse.war	OPENING_ARCHIVE		1
16:05:03.269000000	16:05:03.269000000	2		APPLICATION dataverse.war	VALIDATE_TARGET	command	0
16:05:03.269000000	16:05:03.270000000	2		APPLICATION dataverse.war	OPENING_ARCHIVE	ArchiveHandler	1
16:05:03.270000000	16:05:03.270000000	2		APPLICATION dataverse.war	CREATE_DEPLOYMENT_CONTEXT	Initial	0
16:05:03.270000000	16:05:03.270000000	2		APPLICATION dataverse.war …
```
=> Improve data collection of structured deployment tracing

nucleus/pom.xml
- maven plugin should prioritize maven environment over
the user's environment
- honor ~/.mavenrc settings when executing asadmin via Ant exec.
=> PAYARA-4064 Fixed dependency on operating system's java

appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jaxrs/RolesAllowedRequestFilter.java
=> PAYARA-4073 using the correct constructor of NotAuthorizedException

nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/remote/RemoteCommand.java, nucleus/admin/util/src/main/java/com/sun/enterprise/admin/remote/RemoteAdminCommand.java, nucleus/admin/util/src/main/java/com/sun/enterprise/admin/remote/ServerRemoteAdminCommand.java, nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/InstanceCommandExecutor.java, nucleus/osgi-platforms/osgi-cli-remote/src/main/java/org/glassfish/osgi/cli/remote/OSGiShellCommand.java
Reverts https://github.com/payara/Payara/pull/4161 and https://github.com/payara/Payara/pull/4123
=> Revert RemoteCommand refactor

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/DescriptorConstants.java, appserver/ejb/ejb-full-container/src/main/java/org/glassfish/ejb/mdb/deployment/annotation/handlers/MessageDrivenHandler.java
https://github.com/payara/Payara/pull/4084 was merged despite review comments.
=> PAYARA-3964 Review comments

nucleus/core/bootstrap/src/main/java/fish/payara/boot/runtime/BootCommand.java
Try starting a domain with the following post boot command file to test:
~~~
start-local-instance --node localhost-domain1 instance1
~~~
Make sure you've created the instance first, although it shouldn't matter in principle
=> PAYARA-4113 Log Boot Command Exceptions

appserver/admingui/cluster/osgi.bundle, appserver/admingui/cluster/pom.xml, appserver/admingui/cluster/src/main/java/fish/payara/cluster/admingui/PayaraClusterHandlers.java, appserver/admingui/cluster/src/main/resources/org/glassfish/cluster/admingui/Strings.properties, appserver/admingui/cluster/src/main/resources/shared/instanceNew.inc
Title.
I've had to remove the _required_ label, so the prompt has changed a little from a text box to a full error message. From my testing this hasn't changed the functionality of the page at all, it's merely aesthetic.
=> PAYARA-4096 Allow generating instance names from the Admin Console

Jenkinsfile-Nightly
Title.
The Arquillian extension was moved at some point.
=> Fix path in Jenkinsfile-Nightly

appserver/tests/payara-samples/classpath/embedded-vs-jersey/pom.xml, appserver/tests/payara-samples/classpath/pom.xml, appserver/tests/payara-samples/pom.xml, appserver/tests/payara-samples/samples-programmatic/pom.xml, appserver/tests/payara-samples/samples/asadmin/pom.xml, appserver/tests/payara-samples/samples/clustered-singleton/clustered-singleton-ejb/pom.xml, appserver/tests/payara-samples/samples/clustered-singleton/pom.xml, appserver/tests/payara-samples/samples/custom-loginmodule-realm/loginmodule-realm-impl/pom.xml, appserver/tests/payara-samples/samples/custom-loginmodule-realm/loginmodule-realm-test/pom.xml, appserver/tests/payara-samples/samples/custom-loginmodule-realm/pom.xml, appserver/tests/payara-samples/samples/dynamic-roles/pom.xml, appserver/tests/payara-samples/samples/ejb-http-remoting/api/pom.xml, appserver/tests/payara-samples/samples/ejb-http-remoting/client/pom.xml, appserver/tests/payara-samples/samples/ejb-http-remoting/pom.xml, appserver/tests/payara-samples/samples/ejb-http-remoting/server-app/pom.xml, appserver/tests/payara-samples/samples/formauth/pom.xml, appserver/tests/payara-samples/samples/jacc-per-app/pom.xml, appserver/tests/payara-samples/samples/jaxrs-rolesallowed-servlet/pom.xml, appserver/tests/payara-samples/samples/jaxrs-rolesallowed/pom.xml, appserver/tests/payara-samples/samples/jaxws-tracing/pom.xml, appserver/tests/payara-samples/samples/microprofile-endpoints/insecure/pom.xml, appserver/tests/payara-samples/samples/microprofile-endpoints/pom.xml, appserver/tests/payara-samples/samples/microprofile-endpoints/secure/pom.xml, appserver/tests/payara-samples/samples/oauth2/pom.xml, appserver/tests/payara-samples/samples/openid/pom.xml, appserver/tests/payara-samples/samples/pom.xml, appserver/tests/payara-samples/samples/rolesPermitted/pom.xml, appserver/tests/payara-samples/test-utils/pom.xml
=> PAYARA-4129 Fixed version number of payara-samples

appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/policy/FallbackPolicy.java
fixes #4174. Manually tested fix of NPE as described in the bug description.
=> NPE with FT annotations on classes in default package

appserver/admin/gf_template/src/main/resources/config/default-web.xml, appserver/admin/gf_template_web/src/main/resources/config/default-web.xml, appserver/admin/production_domain_template/src/main/resources/config/default-web.xml, appserver/admin/production_domain_template_web/src/main/resources/config/default-web.xml
=> PAYARA-4061 Reflect jar name change

nucleus/pom.xml
Fix for osgi global lock to resolve payara-micro-service
payara/patched-src-hk2#8
payara/Payara_PatchedProjects#271
=> PAYARA-4122 Set HK2 version to 2.6.1.payara-p1

nucleus/pom.xml
Depends on https://github.com/payara/Payara_PatchedProjects/pull/273
=> PAYARA-4146 Update JavaMail to 1.6.4.payara-p1.

.github/PULL_REQUEST_TEMPLATE.md
Adds a default template for Pull Requests
Aim is to encourage better quality PRs
No dependencies, blockers or deadlines
N/A
Created in own repo. Created new PR to see template in action.
N/A
GitHub
Payara Internal wiki page on creating PRs
Should cover everything we need out of a PR. This PR description has also followed template
=> TEST-384 Add PR Template

appserver/deployment/client/src/main/java/org/glassfish/deployment/client/AbstractDeploymentFacility.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/remote/RemoteCommand.java, nucleus/admin/template/src/main/resources/config/server.policy, nucleus/admin/util/src/main/java/com/sun/enterprise/admin/remote/RemoteAdminCommand.java, nucleus/admin/util/src/main/java/com/sun/enterprise/admin/remote/ServerRemoteAdminCommand.java, nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/InstanceCommandExecutor.java, nucleus/osgi-platforms/osgi-cli-remote/src/main/java/org/glassfish/osgi/cli/remote/OSGiShellCommand.java, nucleus/security/core/src/main/resources/config/server.policy
Fixes TCK tests for j2eetools on master branch
Integrates work in 5.193.1 maintenance branch with the revert of commit 027afbb40cff086acfec99ebe77eddc4c81df13a
There will be one more commit with cleanup in deployment-client, which passes TCK too, but it is more radical.
=> J2eetools fixes for master

appserver/pom.xml
Zulu JDK 1.8_212 on Ubuntu 18.04 with Maven 3.6.0
=> PAYARA-4198 Upgrade Tyrus to 1.15

Jenkinsfile
This is a CI improvement
Convention is to put agent at top
local sandbox
=> Minor syntax tweak

Jenkinsfile-Nightly
This is a CI improvement
Shows status of nightly as unstable rather than failure. Which is more correct.
Tested in local Jenkins sandbox
Internal Jenkins
n/a
none
=> CI-93 Fix Nightly Tests.

nucleus/pom.xml
A new final release of jackson has been released
None
Build + start
Zulu JDK 1.8_212 on Ubuntu 18.04 with Maven 3.6.0
=> PAYARA-4213 Upgrade jackson to 2.10.0

Jenkinsfile-Nightly
This is a CI pipeline correction
Fixes syntax error of a superfluous closing parenthesis .
=> CI-93 Fix syntax error

appserver/common/annotation-framework/src/main/java/org/glassfish/apf/impl/ComponentDefinition.java, appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/ASURLClassLoader.java, nucleus/deployment/common/src/main/java/com/sun/enterprise/deployment/deploy/shared/InputJarArchive.java
Contains some small improvements to deployment, reducing deployment times by ~9%.
Tested by using netinium's test domain + app and see how long deployment takes
Before: 77 seconds
After:    70 seconds
Zulu JDK 1.8_181 on Windows 10 with Maven 3.6.0
=> PAYARA-3811 improve deployment times

nucleus/common/common-util/src/test/java/com/sun/enterprise/loader/DirWatcherTest.java
It takes a little while for filesystem changes to become available to FileWatcher service. The PR adds retries to the assertions in order to wait for the changes to propagate to client.
`DirWatcherTest` in `common-util` should consistently pass on Linux. So far tested on Windows, where is wasn't causing any issues, though.
- ` mvn clean test -pl :common-util`
JDK 1.8.0_221, Windows 10, Maven 3.6.2
=> PAYARA-3811: Stabilize test

appserver/packager/appserver-base/src/main/docs/README.txt
Updated README.txt co contain also tested JDK11 versions.
Do not merge yet - may be updated, but give me feedback ;)
=> PAYARA-4095 Updated README.txt - supported JDK distributions

appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/JCDIServiceImpl.java
Cherrypick of the commit from 5.193.1
- Jakarta TCKs
- `./tck.sh ejb32/mdb/modernconnector` - failed before this commit, passed after it
- original commit was only in BitBucket, that is why I could not find it here :-)
=> PAYARA-4048: Inject MDBs as non-contextual

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/EjbInvocation.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/BaseContainer.java
Fixed NPE, caused in #4325 
- Jakarta TCKs
`   ./tck.sh ejb/ee/bb/entity/bmp`
=> PAYARA-4197 Fixed NPE introduced in refactoring

pom.xml
This isn't a bug fix / feature. 
none
Full build on travis.
All included in `mvn clean install`
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10)
Maven 3.6.1
Ubuntu 16.04.6 LTS/xenial
=> Cleanup maven warnings

appserver/security/realm-stores/pom.xml
This is a bug fix . 
`javax` was replaced with `jakarta` while #4298 was waiting to be merged
`mvn validate`
Maven 3.6.2
=> Fix replaced dependency

api/payara-bom/pom.xml, pom.xml
Updates Arquillian containers in BOM to version 2.0, and adds AppClient package coordinates.
https://github.com/payara/Payara-Examples/pull/115 Builds ok and pulls new connectors
Zulu JDK 1.8_222 on Windows 10 with Maven 3.6.2
=> PAYARA-3924: Update public artifacts for 5.194 in BOM

appserver/admingui/common/src/main/help/en/help/ref-ldaprealmprop.html
No Jira made for this
Small online documentation fox
fixes https://github.com/payara/Payara/issues/352
=> Fix small doc issue. Fixes #352

appserver/admin/production_domain_template_web/pom.xml, appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml, pom.xml
#4366
Validation of specified xmls done in the build process.
Full build (`mvn clean install`) on travis.
Ubuntu 16.04.6 LTS
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10)
Maven 3.6.1
=> CUSTCOM-56 Fix production domain.xml

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/DynamicInterceptor.java
Minor internal code reformat to the `com.sun.enterprise.v3.admin.DynamicInterceptor` class. Removed un-needed `System.out.println` that was polluting the logs.
No tests needed.
Run the default test suite in the repository.
Windows 10, Zulu 11.35
=> [CUSTCOM-88] Minor changes to DynamicInterceptor

appserver/admin/gf_template/pom.xml, appserver/admin/gf_template_web/pom.xml, appserver/admin/production_domain_template/pom.xml, appserver/admin/production_domain_template_web/pom.xml, appserver/distributions/payara-ml/pom.xml, appserver/distributions/payara-web-ml/pom.xml, appserver/distributions/payara-web/pom.xml, appserver/distributions/payara/pom.xml, appserver/distributions/pom.xml, appserver/extras/embedded/all/pom.xml, appserver/extras/embedded/web/pom.xml, appserver/extras/payara-micro/payara-micro-boot/pom.xml, nucleus/admin/template/pom.xml, pom.xml
- validate resources from own modules to fail fast
- validate distributed resources to fail before install
This is a build enhancement
Tested manually on each module by braking some XML syntax, running the build of a module and watching when the check is done and if it fails the build.
See comments in diff
=> CUSTCOM-153 Validate XML resources

nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/Domain.java
When redeploying applications for deployment groups, a HK2 bean locking exception would be thrown as the server attempts to deploy the application to the deployment group as well as each of the instances within that deployment group. This change means that only the deployment group is targeted so the application can deploy normally.
The broken functionality was caused by 81f87239ac175e26affc4fc2fbe0c5338a618696, but the included fix does seem appropriate for the original issue. This change aims to complement
that commit.
N/A
Redeploying to deployment groups spread across multiple notes, as well as redeploying to individual instances within that deployment group.
N/A
=> CUSTCOM-78 Fix Redeployment For Deployment Groups

pom.xml
Based on 
https://github.com/payara/patched-src-jersey/pull/50
https://github.com/payara/Payara_PatchedProjects/pull/290
Build of payara including tests.
- Quicklook
- Payara Private Tests
- Jakarta TCKs
- Mojarra
=> CUSTCOM-160 Jersey upgrade from 2.29.1.payara-p1 to 2.30.payara-p1

nucleus/common/internal-api/pom.xml, nucleus/common/internal-api/src/test/java/org/glassfish/internal/deployment/GetApplicationNameTest.java
This PR adds unit tests for this PR: https://github.com/payara/Payara/pull/4384
Zulu JDK 1.8_222 on Elementary OS 0.4.1 Loki with Maven 3.5.4>
=> APPSERV-18 Test for testing get application name

README.md, appserver/packager/appserver-base/src/main/docs/README.txt
Documentation update to provide the correct JDK versions.
No testing as this is a documentation update.
=> Correct supported JDK in readme files (related to PAYARA-4095)

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java, appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/micro/services/PayaraInstanceImpl.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java
When stopping and starting a Payara Micro instance with a static name (`--name`) and an EJB timer running, the timer will be stored to be resumed, but won't actually run. This is caused by an inconsistent EJB container ID, which in turn is caused by an inconsistent application unique ID. This re-implements old functionality to remove the CDI event that fires to reconfigure the application unique ID from the clustered store.
Fixes https://github.com/payara/Payara/issues/4103
Reproducer in linked issue (just the application outside of docker).
To repeat: run two Payara Micro instances with:
~~~
java -jar payara-micro-5.201-SNAPSHOT.jar --name micro1 --autobindhttp --deploy sample-service.war
~~~
~~~
java -jar payara-micro-5.201-SNAPSHOT.jar --name micro2 --autobindhttp …
=> CUSTCOM-24 Restore Persistent EJB Timers on Payara Micro Restart

appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/fish/payara/jdbc/SQLTraceStoreAdapter.java, appserver/monitoring-console/core/src/main/java/fish/payara/monitoring/admin/SetMonitoringConsoleConfigurationCommand.java, appserver/monitoring-console/core/src/main/java/fish/payara/monitoring/alert/Condition.java, appserver/monitoring-console/core/src/main/java/fish/payara/monitoring/alert/Watch.java, appserver/monitoring-console/core/src/main/java/fish/payara/monitoring/model/SeriesAnnotation.java, appserver/monitoring-console/core/src/main/java/fish/payara/monitoring/store/InMemoryAlarmService.java, appserver/monitoring-console/core/src/main/java/fish/payara/monitoring/store/InMemoryMonitoringDataRepository.java, appserver/monitoring-console/core/src/test/java/fish/payara/monitoring/model/SeriesAnnotationTest.java, appserver/monitoring-console/webapp/src/main/java/fish/payara/monitoring/web/ApiRequests.java, appserver/monitoring-console/webapp/src/main/java/fish/payara/monitoring/web/ApiResponses.java, appserver/monitoring-console/webapp/src/main/webapp/js/mc-controller.js, appserver/monitoring-console/webapp/src/main/webapp/js/mc-view-components.js, appserver/monitoring-console/webapp/src/main/webapp/js/mc-view.js, appserver/payara-appserver-modules/healthcheck-checker/src/main/java/fish/payara/healthcheck/mphealth/MicroProfileHealthChecker.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/GarbageCollectorHealthCheck.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/HoggingThreadsHealthCheck.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/MachineMemoryUsageHealthCheck.java, nucleus/payara-modules/healthcheck-cpool/src/main/java/fish/payara/nucleus/healthcheck/cpool/ConnectionPoolHealthCheck.java, nucleus/payara-modules/healthcheck-stuck/src/main/java/fish/payara/nucleus/healthcheck/stuck/StuckThreadsHealthCheck.java, nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/RequestTracingService.java
Had a look at new sonar warning I recently caused by code changes and addressed them (hopefully).
Mostly this is 
* using constants, 
* extracting methods to reduce complexit
* use a more appropriate method for a test (`indexOf` vs. `includes`, etcetera)
* use lambdas with _expression body_ syntax where possible
Manually tested that (since there where non-automatic changes applied)
* monitoring data collection from non-DAS instances still works.
* SQL tracing in MC still works
* the MC JS generally does not complain about some error
=> Addresses sonar warnings of recent code changes

appserver/admin/gf_template/src/main/resources/config/domain.xml, appserver/admin/gf_template_web/src/main/resources/config/domain.xml, appserver/admin/production_domain_template/src/main/resources/config/domain.xml, appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml, appserver/extras/embedded/all/src/main/resources/config/domain.xml, appserver/extras/embedded/web/src/main/resources/config/domain.xml, appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/domain.xml, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/CreateInstanceCommand.java, nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/CreateLocalInstanceCommand.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastConfigSpecificConfiguration.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/admin/SetHazelcastConfiguration.java
https://github.com/payara/Payara/pull/4341/files added a config specific data grid start port, to allow the domain wide option to be overriden. This PR configures that property with a system property, which allows this config specific option to be overriden on a per-instance basis.
Manual testing of overriding this property for each instance.
Tested using domain1 and production domain on full server.
In progress...
I added a formatting commit, so for reviewing the actual changes see https://github.com/payara/Payara/pull/4482/files/c7ea657c9d473a8bb04bdb7448447915f7ec88f5
=> CUSTCOM-79 Add Config Specific Data Grid System Property

appserver/tests/payara-samples/classpath/pom.xml, appserver/tests/payara-samples/pom.xml, appserver/tests/payara-samples/samples/ejb-http-remoting/pom.xml, appserver/tests/payara-samples/samples/pom.xml, appserver/tests/payara-samples/test-utils/src/main/java/fish/payara/samples/ServerOperations.java
Removed problematic modules, with the intention of adding them back in later once problems have been addressed. Tracked internally with QACI-95
=> QACI-95 Samples fixes

appserver/pom.xml
This is a component upgrade of the Glassfish Fighterfish.
=> APPSERV-62 Upgrade Glassfish Fighterfish

appserver/pom.xml
This is a component upgrade of boss Classfilewriter to 1.2.4.Final
=> APPSERV-64 Upgrade Jboss Classfilewriter to 1.2.4.Final

pom.xml
This is a component upgrade of Jackson to 2.10.2
=> APPSERV-65 Upgrade Jackson to 2.10.2

pom.xml
This is a component upgrade of Istack Common Utility to 3.0.10
=> APPSERV-67 Upgrade Istack Common Utility to 3.0.10

pom.xml
This is a component upgrade of Hazelcast to 3.12.6
=> APPSERV-68 Upgrade Hazelcast to 3.12.6

api/payara-bom/pom.xml
This is a component upgrade of the Imqjmx to 4.4.2
=> APPSERV-69 Upgrade Imqjmx to 4.4.2

pom.xml
This is a component upgrade of the SnakeYAML to 1.25
=> APPSERV-85 Upgrade SnakeYAML to 1.25

pom.xml
This is a component upgrade of the ASM to 7.3.1
=> APPSERV-84 Upgrade ASM to 7.3.1

nucleus/pom.xml
This is a component upgrade of the Logging Annotation Processor to 1.9
=> APPSERV-75 Upgrade Logging Annotation Processor to 1.9

nucleus/pom.xml
This is a component upgrade of the  Bouncy Castle to 1.64
=> APPSERV-73 Upgrade Bouncy Castle to 1.64

pom.xml
This is a component upgrade of the Cache API to 1.1.1
=> APPSERV-72 Upgrade Cache API to 1.1.1

pom.xml
This is a component upgrade of the Jakarta dependencies
=> APPSERV-71 Upgrade Jakarta dependencies

appserver/pom.xml
This is a component upgrade of the JSFTemplating to 2.1.4
=> APPSERV-63 Upgrade JSFTemplating to 2.1.4

api/payara-bom/pom.xml
This is a component upgrade of the OSGi DTO to 1.1.0
=> APPSERV-83 Upgrade OSGi DTO to 1.1.0

nucleus/pom.xml
This is a component upgrade of the MIME Streaming Extension to 1.9.12
=> APPSERV-82 Upgrade MIME Streaming Extension to 1.9.12

appserver/packager/glassfish-common-web/pom.xml, appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastTimerStore.java, appserver/pom.xml, nucleus/admin/util/pom.xml, nucleus/common/common-util/pom.xml, nucleus/pom.xml, pom.xml
This is a component upgrade of the JLine to 3.13.3
=> APPSERV-81 Upgrade JLine to 3.13.3

nucleus/pom.xml
This is a component upgrade of the Javassist to 3.26.0-GA
=> APPSERV-79 Upgrade Javassist to 3.26.0-GA

nucleus/pom.xml
This is a component upgrade of the Hamcrest to 2.2
=> APPSERV-76 Upgrade Hamcrest to 2.2

appserver/pom.xml, nucleus/pom.xml, pom.xml
This is a component upgrade of the OSGi Resource Locator to 1.0.3
=> APPSERV-76 Upgrade OSGi Resource Locator to 1.0.3

pom.xml
This is a component upgrade of the JSON Processing to 1.1.6
=> APPSERV-74 Upgrade JSON Processing to 1.1.6

appserver/tests/payara-samples/samples/rest-management/src/test/java/fish/payara/samples/rest/management/HttpSemanticsTest.java
This test makes sure that the parameters in the request are parsed correctly to the parameters of the admin command invoked by checking the command log returned in the response.
This test validates https://github.com/payara/Payara/pull/4504.
=> CUSTCOM-199 Test For Admin Command JSON Invocation

pom.xml
This is a component upgrade of the Hibernate Validator to 6.1.2.Final
=> APPSERV-78 Upgrade Hibernate Validator to 6.1.2.Final

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/CommonClassLoaderServiceImpl.java
=> APPSERV-22 Remove System.out.println

pom.xml
Updates Weld to 3.1.2
There appears to be issues with 3.1.3: https://github.com/payara/Payara/pull/4519
=> APPSERV-113 Weld 3.1.2

appserver/tests/payara-samples/samples/rest-management/src/test/java/fish/payara/samples/rest/management/JvmOptionsTest.java
Added a test for the JVM options REST management endpoint, to make sure
that the endpoint continues to work as intended.
=> CUSTCOM-234 JVM options REST management test

appserver/payara-appserver-modules/cdi-auth-roles/src/main/java/fish/payara/appserver/cdi/auth/roles/NonSerializableProperties.java, appserver/payara-appserver-modules/cdi-auth-roles/src/main/java/fish/payara/appserver/cdi/auth/roles/RolesPermittedInterceptor.java, appserver/tests/payara-samples/samples/rolesPermitted/pom.xml, appserver/tests/payara-samples/samples/rolesPermitted/src/main/java/fish/payara/samples/rolespermitted/IdentityStoreTest.java, appserver/tests/payara-samples/samples/rolesPermitted/src/main/java/fish/payara/samples/rolespermitted/TestRolesPermitted.java, appserver/tests/payara-samples/samples/rolesPermitted/src/main/java/fish/payara/samples/rolespermitted/TestServlet.java, appserver/tests/payara-samples/samples/rolesPermitted/src/main/webapp/WEB-INF/web.xml, appserver/tests/payara-samples/samples/rolesPermitted/src/test/java/fish/payara/samples/rolespermitted/RolesPermittedTest.java
Beans with @RolesPermitted could not hold scopes like @ViewScoped or @SessionScoped as the interceptor wasn't serialisable.
Updated the existing test to use a serializable scope and to make some serial tests to test this
=> CUSTCOM-166 Make Beans With @RolesPermitted Serializable

pom.xml
This is a component upgrade of the Yasson to 1.0.6
- Quicklook
- Build test
=> CUSTCOM-40 Upgrade to Yasson 1.0.6

appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/rest/MetricsResource.java
- by default jersey client sends valid header which was causing Internal Server Error:
`text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2`
- now spaces and missing leading zeroes are tolerated
- reduced copy and paste
- behavior of the regular expression was tested locally modifying this simple test (q=0.1 or q= 0.1 vs expected 0.1 AND q=.1 or q = .1 vs expected .1):
```
@Test
public void test() {
Pattern pattern = Pattern.compile("[q\\s]+=\\s*(.+)");
assertTrue(pattern.matcher("q=0.1").matches());
final Matcher matcher = pattern.matcher("q = .1");
matcher.find();
assertEquals(".1", matcher.group(1));
}
```
- then I verified that Payara with fixed MetricsResource works in tests under PAYARA-4176 + CUSTCOM-133 (this was a blocker for these tests).
=> CUSTCOM-254 Fixed parsing of Accept header in metrics

appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/startup/EjbApplication.java, appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/SecurityDeployer.java, appserver/security/core-ee/src/main/java/com/sun/enterprise/security/jacc/JaccWebAuthorizationManager.java, appserver/security/core-ee/src/main/java/com/sun/enterprise/security/jacc/context/PolicyContextRegistration.java, appserver/security/core-ee/src/main/java/com/sun/enterprise/security/web/integration/WebSecurityManagerFactory.java, appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java, appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java, appserver/web/web-core/src/main/java/org/apache/catalina/startup/Embedded.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/VirtualServer.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebContainer.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModule.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModuleConfig.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/security/integration/RealmInitializer.java, nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/WebAndEjbToJaasBridge.java
This PR is based on https://github.com/payara/Payara/pull/4621 and was created to separate testing of both change steps.
* First must be merged the fix https://github.com/payara/Payara/pull/4621 (done)
First follow instructions in https://github.com/payara/Payara/pull/4621 , then you can test this in similar way:
This should still pass:
```
git checkout dmatej/CUSTCOM-133-code-cleanup
mvn clean install -PQuickBuild,fastest -TC8
git checkout dmatej/PAYARA-4176-TestContainers-prototype
mvn clean install -Ptest-containers  -pl :test-containers -Dit.test=MetricsSecurityITest,JaspicSamAuthenticationITest # should pass again
```
=> CUSTCOM-133 Code cleanup in security

.github/PULL_REQUEST_TEMPLATE.md
The template was quite noisy with inconsistent formatting. Now each
section is separated by 2 lines, and only one comment is displayed per
section. Sections that seemed to be covering topics that were too
similar have been merged. No sections are pre-filled anymore.
=> Template Readability Modifications

pom.xml
This is a bug fix to fix a PrimeFaces issue where AutoSelect Event is Null within Custom Component.
This issue is caused by PrimeFaces when it calls `processAjaxBehavior` method in the [AjaxBehaviorListenerImpl ](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/behavior/ajax/AjaxBehaviorListenerImpl.java):
```
public void processAjaxBehavior(AjaxBehaviorEvent event) throws AbortProcessingException {
FacesContext context = FacesContext.getCurrentInstance();
final ELContext elContext = context.getELContext();
.....
try {
listener.invoke(elContext, new Object[]{});
}
catch (MethodNotFoundException | IllegalArgumentException | ArrayIndexOutOfBoundsException mnfe) {
processArgListener(context, elContext, event);
}
private void processArgListener(FacesContext …
```
=> CUSTCOM-179 PrimeFaces AutoSelect Event is Null within Custom Component

pom.xml
Payara/Payara_PatchedProjects#307
- JavaEE7Samples
Zulu JDK 1.8_212 on Ubuntu 18.04 with Maven 3.6.3
=> APPSERV-110 Update grizzly to version 2.4.4

pom.xml
This is a bug fix. It is related to this PR https://github.com/payara/Payara/pull/4592. It covers more use cases compared to the related PR
Patched artifact: https://github.com/payara/Payara_PatchedProjects/pull/309
Code changes: https://github.com/payara/patched-src-el-ri/pull/2#pullrequestreview-413402879
**Ran the following test from Jakarta TCK:**
- EL
- JSF
- Servlet
=> CUSTCOM-273 PrimeFaces Events are Null within Custom Component

Jenkinsfile-Nightly
Merge the duplicate env sections which makes it fail.
=> Fix Jenkinsfile-Nightly

appserver/web/weld-integration/osgi.bundle, pom.xml
#4069 Description
- JavaEE8Samples
-JavaEE7Samples
Zulu JDK 1.8_212 on Ubuntu 20.04 with Maven 3.6.0
=> APPSERV-80 Update weld to version 3.1.4

nucleus/pom.xml, pom.xml
Title.
Where they are they get missed from the api and bom poms.
=> FISH-224 Move license and url to top-level pom (Release)

appserver/admingui/payara-theme/src/main/resources/branding/masthead.inc, appserver/admingui/pom.xml
https://github.com/payara/patched-src-woodstock-suntheme/pull/20
=> CUSTCOM-291 Update Woodstock and Fix Masthead Image Dimensions

nucleus/pom.xml, pom.xml
Title.
Where they are they get missed from the api and bom poms.
=> FISH-224 Move license and url to top-level pom

.github/PULL_REQUEST_TEMPLATE.md
Title.
Fed up of issue prompt needing escaping 😂
=> FISH-226 Use ## rather than # in PR template

appserver/extras/certificate-management/src/main/java/fish/payara/certificate/management/CertificateManagementDomainConfigUtils.java, appserver/extras/certificate-management/src/main/java/fish/payara/certificate/management/CertificateManagementKeytoolCommands.java, appserver/extras/certificate-management/src/main/java/fish/payara/certificate/management/admin/AbstractCertManagementCommand.java, appserver/extras/certificate-management/src/main/java/fish/payara/certificate/management/admin/AddToKeyStoreCommand.java, appserver/extras/certificate-management/src/main/java/fish/payara/certificate/management/admin/AddToTrustStoreCommand.java, appserver/extras/certificate-management/src/main/java/fish/payara/certificate/management/admin/GenerateCsrCommand.java, appserver/extras/certificate-management/src/main/java/fish/payara/certificate/management/admin/GenerateSelfSignedCertificateCommand.java, appserver/extras/certificate-management/src/main/java/fish/payara/certificate/management/admin/RemoveExpiredCertsCommand.java, appserver/extras/certificate-management/src/main/java/fish/payara/certificate/management/admin/RemoveFromKeyStoreCommand.java, appserver/extras/certificate-management/src/main/java/fish/payara/certificate/management/admin/RemoveFromTrustStoreCommand.java, appserver/extras/certificate-management/src/main/manpages/fish/payara/certificate/management/admin/generate-csr.1, appserver/extras/certificate-management/src/main/manpages/fish/payara/certificate/management/admin/generate-self-signed-certificate.1
Remake of #4711 AND https://github.com/payara/Payara/pull/4742 after git had a complete meltdown during a rebase and AGAIN after cherry-picking commit by commit.
Sync from Enterprise:
payara/Payara-Enterprise#52
payara/Payara-Enterprise#56
payara/Payara-Enterprise#69
=> APPSERV-150 APPSERV-153 FISH-195 Commands to Remove expired certificates and add/remove from key/trust stores, and add node & nodedir parameters 

pom.xml
This a feature to support for multi HTTPAuthenticationMechanism within each WAR of an EAR deployment (WAR A uses JWT, WAR B uses Certificate for example).
Patched artifact: payara/Payara_PatchedProjects#315
Code changes: payara/patched-src-security-soteria/pull/1
- Build test
Reproduce is available in the related JIRA issue.
=> FISH-171 Support for multi HTTPAuthenticationMechanism

pom.xml
This upgrades MicroProfile JWT to 1.1.1.payara-p1.
- Build test
- MicroProfile TCK
MircroProfile 1.1.1 release only includes fixes to the TCK tests. There are no changes to the API
=> FISH-151 Implement MicroProfile JWT-Auth 1.1.1

appserver/tests/payara-samples/samples/rest-management/src/test/java/fish/payara/samples/rest/management/ServerLogTest.java
Ignored while a fix is in progress
=> QACI-289 Exclude ServerLogTest

Jenkinsfile
=> Revert "QACI-262 Skip Quicklook"

appserver/extras/certificate-management/src/main/java/fish/payara/certificate/management/admin/GenerateSelfSignedCertificateCommand.java, appserver/extras/certificate-management/src/main/java/fish/payara/certificate/management/admin/RemoveExpiredCertsCommand.java, appserver/extras/certificate-management/src/main/manpages/fish/payara/certificate/management/admin/generate-self-signed-certificate.1
Sync PR for Jonathan.
Zulu JDK 1.8_212 on Ubuntu 20.04 with Maven 3.6.03
This PR updates the internal documentation
=> FISH-191 Extended text to state to add/remove certs manually

Jenkinsfile
A small tweak to give developers a heads up of any expired certificates coming within the current and next month
Validated with Jenkins connector plugin for visual studio and tested locally on local keystore. Tested on jenkins
=> QACI-286 Check for expired certs before running Jenkins script

appserver/tests/payara-samples/samples/rest-management/src/test/java/fish/payara/samples/rest/management/SystemPropertyTest.java
Ignores bad test until rectified
=> FiSH-156 Ignore bad test

nucleus/common/common-util/src/main/java/com/sun/appserv/server/util/VersionInfoImpl.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/VersionInfo.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/ODLLogFormatter.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/UniformLogFormatter.java, nucleus/core/logging/src/main/java/fish/payara/enterprise/server/logging/JSONLogFormatter.java
Include "update" version on the logging message
=> FISH-215 Include update version on the logging message

appserver/tests/payara-samples/samples/rest-management/src/test/java/fish/payara/samples/rest/management/SystemPropertyTest.java
Removes a redundant line making an incorrect assertion.
=> FISH-156 fix test

appserver/extras/embedded/all/pom.xml, appserver/extras/embedded/web/pom.xml, appserver/featuresets/payara-web/pom.xml, appserver/packager/glassfish-gui-l10n/pom.xml, appserver/packager/glassfish-gui/pom.xml
Removed Slack Notifier from the build.
- Build Test
=> FISH-269 Remove Slack Notifier

appserver/extras/docker-images/pom.xml
https://github.com/payara/Payara/pull/4790
=> FISH-278 [Community] Update Docker Java Versions to 8u252

appserver/extras/embedded/all/pom.xml, appserver/extras/embedded/web/pom.xml, appserver/featuresets/payara-web/pom.xml, appserver/packager/glassfish-gui-l10n/pom.xml, appserver/packager/glassfish-gui/pom.xml
Removed Datadog Notifier from the build.
- Build Test
=> FISH-272 Remove Datadog Notifier

appserver/extras/embedded/all/pom.xml, appserver/extras/embedded/web/pom.xml, appserver/featuresets/payara-web/pom.xml, appserver/packager/glassfish-gui-l10n/pom.xml, appserver/packager/glassfish-gui/pom.xml
Removed XMPP Notifier from the build.
- Build Test
=> FISH-267 Remove XMPP Notifier

appserver/extras/embedded/all/pom.xml, appserver/extras/embedded/web/pom.xml, appserver/featuresets/payara-web/pom.xml, appserver/packager/glassfish-gui-l10n/pom.xml, appserver/packager/glassfish-gui/pom.xml
Removed NewRelic Notifier from the build.
- Build Test
=> FISH-266 Remove NewRelic Notifier

appserver/extras/embedded/all/pom.xml, appserver/extras/embedded/web/pom.xml, appserver/featuresets/payara-web/pom.xml, appserver/packager/glassfish-gui-l10n/pom.xml, appserver/packager/glassfish-gui/pom.xml
Removed SNMP Notifier from the build.
- Build Test
=> FISH-268 Remove SNMP Notifier

appserver/extras/embedded/all/pom.xml, appserver/extras/embedded/web/pom.xml, appserver/featuresets/payara-web/pom.xml, appserver/packager/glassfish-gui-l10n/pom.xml, appserver/packager/glassfish-gui/pom.xml
Removed Email Notifier from the build.
- Build Test
=> FISH-271 Remove Email Notifier

appserver/extras/embedded/all/pom.xml, appserver/extras/embedded/web/pom.xml, appserver/featuresets/payara-web/pom.xml
Removed Yubikey Authentication Mechanism from the build.
- Build Test
=> FISH-273 Remove Yubikey Authentication Mechanism

appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/MetricsService.java
Small addition of more metadata in connection with https://github.com/payara/monitoring-console/pull/19
=> FISH-8 Adds App context to MC Annotation for MicroProfile Metrics 

appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/common/DataSourceSpec.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java
fixes #4487
Tested using reproducer at https://github.com/haraldatbmw/payara-micro-mpconfig
=> FISH-68 Support MP Config properties in DataSourceDefinitions

pom.xml
Needs https://github.com/payara/monitoring-console/pull/21 merged and released first!
=> FISH-287 Increment MC implementation version to 1.3

nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/store/strategy/ReservoirTraceStorageStrategy.java, nucleus/payara-modules/requesttracing-core/src/test/java/fish/payara/nucleus/requesttracing/store/strategy/ReservoirTraceStorageStrategyTest.java
The new test won't fail randomly as the random is seeded.
=> FISH-241 Fix Reservoir Sampling Test

Jenkinsfile
Caused enterprise to fail, missing change in community. Managed doesn't save the domain after testing
=> QACI-195 Add MP TCKs to PR tests - Managed doesn't save logs

appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java, appserver/web/war-util/src/test/java/org/glassfish/web/loader/WebappClassLoaderTest.java
=> FISH-66 Prevent zip file closure on EJB initalisation

appserver/tests/payara-samples/samples/rest-management/src/test/java/fish/payara/samples/rest/management/ServerLogTest.java
Will otherwise fail until Grizzly is upgraded
=> Disable ServerLogTest until Grizzly upgrade

appserver/pom.xml, appserver/tests/payara-samples/pom.xml
This is a component upgrade, fixing a security vulnerability.
Ran payara-samples and the MicroProfile TCKs using managed profile.
Linux, JDK 8u252
=> FISH-381 Update nimbus-jose-jwt to 8.20

Jenkinsfile, Jenkinsfile-Nightly
This is an additional test.
payara/Payara_PatchedProjects#331
This adds testing to ensure that maven artefacts have the correct checksum.
Ran locally `mvn clean install --strict-checksums`
Zulu JDK 1.8_262 on Ubuntu 18.04 with Maven 3.6.3
=> QACI-459 Test the checksums for maven artifacts

appserver/admin/gf_template/src/main/resources/config/domain.xml, appserver/admin/production_domain_template/src/main/resources/config/domain.xml, appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/schemagen, appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/schemagen.bat, appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wscompile, appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wscompile.bat, appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsdeploy, appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsdeploy.bat, appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsgen, appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsgen.bat, appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsimport, appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsimport.bat, appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/xjc, appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/xjc.bat
=> FISH-25 FISH-93 Revert

appserver/tests/payara-samples/samples/remote-ejb-tracing/remote-ejb-tracing-client/pom.xml
Title.
Post not pre-integration.
=> FISH-369 Fix remote EJB tracing test

pom.xml
payara/Payara_PatchedProjects#338
Eclipselink PR payara/patched-src-eclipselink#7
=> FISH-604 Upgrade eclipselink without FISH-405

appserver/admingui/microprofile-console-plugin/src/main/resources/microprofile/specs/configAPI/gcpConfigSourceConfiguration.jsf, appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/gcp/GetGCPSecretsConfigSourceConfigurationCommand.java, appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/gcp/SetGCPSecretsConfigSourceConfigurationCommand.java
Admin Console bugfix for [FISH-341](https://github.com/payara/Payara/pull/4944)
=> Fixed issue where you could not configure GCP secrets using the Admin Console

appserver/admingui/microprofile-console-plugin/src/main/resources/fish/payara/admingui/microprofile/Strings.properties, appserver/admingui/microprofile-console-plugin/src/main/resources/microprofile/microprofileConfigAPITabs.inc, appserver/admingui/microprofile-console-plugin/src/main/resources/microprofile/specs/configAPI/awsConfigSourceConfiguration.jsf, appserver/admingui/microprofile-console-plugin/src/main/resources/microprofile/specs/configAPI/gcpConfigSourceConfiguration.jsf, appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/aws/AWSSecretsConfigSource.java, appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/aws/AWSSecretsConfigSourceConfiguration.java, appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/aws/GetAWSSecretsConfigSourceConfigurationCommand.java, appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/aws/SetAWSSecretsConfigSourceConfigurationCommand.java, appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/aws/client/AuthUtils.java, appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/aws/client/AwsAuthFeature.java, appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/aws/client/AwsRequestBuilder.java, appserver/payara-appserver-modules/microprofile/config-extensions/src/test/java/fish/payara/microprofile/config/extensions/aws/client/AuthUtilsTest.java
Allows fetching and modifying AWS Secrets.
TBD
=> FISH-340 Create AWS Secrets Config Source

appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/azure/admin/SetAzureSecretsConfigSourceConfigurationCommand.java
=> Corrected a typo in the parameters of set-azure-config-source-configuration command

pom.xml
Depends on: https://github.com/payara/Payara_PatchedProjects/pull/342
Update of https://github.com/payara/Payara/pull/4915 with FISH-406 also thrown in.
=> FISH-405 FISH-406 Left Join Fetch on Embeddable ElementColection fails & NamedQuery with QueryHints.REFRESH fails to execute

nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/JDBCConfigSource.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/JDBCConfigSourceHelper.java
Fixes errors found in JDBC config source testing where errors were being swallowed and resources were leaking.
=> FISH-676 JDBC Config Source Fixes

appserver/packager/appserver-base/src/main/docs/README.txt
=> Fix Release Notes URL

appserver/distributions/payara-ml/pom.xml, appserver/distributions/payara-web-ml/pom.xml, appserver/distributions/payara-web/pom.xml, appserver/distributions/payara/pom.xml, appserver/distributions/pom.xml, appserver/extras/docker-images/pom.xml, appserver/extras/docker-images/server-full/src/main/docker/assembly.xml, appserver/extras/docker-images/server-web/src/main/docker/assembly.xml
This is an improvement. The domain still exists in production-template.jar, but no longer features in any build stages.
Starting the server-full docker image and payara final artifact.
=> FISH-375 Remove Production Domain From Build

appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/SignedJWTIdentityStore.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jaxrs/RolesAllowedDynamicFeature.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jaxrs/RolesAllowedRequestFilter.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jwt/JWTInjectableType.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jwt/JwtTokenParser.java, pom.xml
This is a feature. Will need upgrading to the final release version when it's release, but for now the release candidate is good enough.
TCK updated: https://github.com/payara/MicroProfile-TCK-Runners/pull/123
Ran the new TCK against our current implementation
=> FISH-661 MicroProfile JWT Auth 2.1 Upgrade

appserver/extras/certificate-management/certificate-management-cli/src/main/java/fish/payara/certificate/management/cli/AbstractCertManagementCommand.java
Fixes incompability created in https://github.com/payara/Payara/pull/4970
Required to merge ASAP, fixes build :-)
=> FISH-330 Fixed getAlias calls in AbstractCertManagementCommand

appserver/common/amx-javaee/src/main/java/org/glassfish/admin/amx/impl/j2ee/loader/AMXJ2EEStartupService.java, nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/config/AMXConfigImpl.java
Fixed yet another AMX NPE, improved logging
Improved QuickLook instability
QuickLook
=> QACI-549 FISH-762 fix NPE in AMX

Jenkinsfile, Jenkinsfile-Nightly, appserver/persistence/cmp/support-sqlstore/src/main/java/com/sun/jdo/spi/persistence/support/sqlstore/database/H2.properties, appserver/tests/quicklook/amx/src/test/amx/AMXProxyTests.java, appserver/tests/quicklook/build.xml, appserver/tests/quicklook/cluster/clustersetup/src/test/clustersetup/ClusterSetupTest.java, appserver/tests/quicklook/gfproject/db-targets.xml, appserver/tests/quicklook/gfproject/h2.properties, appserver/tests/quicklook/gfproject/v3-targets.xml
Fixes numerous errors in QickLook
Added back previously disabled tests
QuickLook test
JDK 8 / mac
This includes other PRs and I still need to remove those other commits
=> QACI-530 QuickLook test fixes

nucleus/core/kernel/src/main/java/org/glassfish/kernel/embedded/EmbeddedDomainXml.java
This is a bug fix for #4861
Test in reproducer passed.
=> FISH-763 #4861 fixed path to domain xml

appserver/persistence/jpa-container/pom.xml, appserver/persistence/jpa-container/src/main/java/org/glassfish/persistence/jpa/JPADeployer.java, nucleus/admin/config-api/src/main/java/fish/payara/enterprise/config/GetTranslatedConfigValue.java, nucleus/cluster/admin/src/main/java/fish/payara/admin/cluster/GetTranslatedConfigValue.java
Create an instance, then add a system property the the key of APP_DS_NAME pointing and the key of the name of a custom data source. Deploy the application on the Jira with the target of just the instance.
Zulu JDK 1.8_272 on Ubuntu 18.04 with Maven 3.6.3
Community version of payara/payara-enterprise#234
=> FISH-275 Don't create EMF on DAS if no schema generation needed

pom.xml
This is a fix, addressing the Github issue https://github.com/payara/Payara/issues/4952
https://github.com/payara/patched-src-hk2/pull/17
https://github.com/payara/patched-src-hk2/pull/18
https://github.com/payara/Payara_PatchedProjects/pull/345
OpenAPI TCK and Unit tests
=> FISH-743 Upgrade to HK2 2.6.1.payara-p4

appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/SignedJWTIdentityStore.java
Fixes: https://github.com/payara/Payara/issues/5017
When an application that is configured to use MP JWT authentication defines a remote public key location using the `mp.jwt.verify.publickey.location` MP configuration property, a parsing error of a public key in `JWKS` format will happen. 
This fix properly gathers the contents of the remote key file. 
No tests performed as there is no testing infrastructure for the MP JWT Authentication module
No documentation needed
=> FISH- 652 Fixed Error in MP JWT validation when retrieving JWKS key from remote location

appserver/tests/payara-samples/samples/ejb-invoker-secure-endpoint/src/test/java/fish/payara/samples/ejb/invoker/security/AbstractRemoteBeanSecurityTest.java, appserver/tests/payara-samples/samples/microprofile-endpoints/secure/src/test/java/fish/payara/samples/microprofile/endpoint/secure/MicroprofileSecureEndpointTest.java, appserver/tests/payara-samples/test-utils/src/main/java/fish/payara/samples/ServerOperations.java
=> Payara samples cert fixes

appserver/tests/payara-samples/samples/remote-ejb-tracing/remote-ejb-tracing-client/src/test/java/fish/payara/samples/remote/ejb/tracing/RemoteEjbClientIT.java
Refactors Payara Samples Remote EJB tracing test case to OpenTracing API 0.33.
Payara samples
=> FISH-664 OpenTracing API refactoring

nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigProviderResolverImpl.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/PayaraConfig.java
Used reproducer in original Jira 
=> FISH-892 Clear MP config cache after startup so extesions can be picked up

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebContainer.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModule.java
This a bug fix to fix the issue described in #4653
Manual verification of result and "mvn clean verify -pl :web-glue"
=> FISH-765 #4653 Propagate VirtualServer config to WebModule

appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/DB2PersistenceManager.java, appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/JBatchJDBCPersistenceManager.java, appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/JDBCQueryConstants.java, appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/MySqlPersistenceManager.java, appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/OraclePersistenceManager.java, appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/PostgresPersistenceManager.java, appserver/batch/glassfish-batch-connector/src/main/java/fish/payara/jbatch/persistence/rdbms/SQLServerPersistenceManager.java, appserver/batch/glassfish-batch-connector/src/main/java/org/glassfish/batch/spi/impl/BatchRuntimeConfiguration.java, appserver/batch/glassfish-batch-connector/src/main/java/org/glassfish/batch/spi/impl/BatchRuntimeHelper.java, appserver/batch/glassfish-batch-connector/src/main/java/org/glassfish/batch/spi/impl/GlassFishBatchSecurityHelper.java
This is a code cleanup
*JavaEE7Samples
=> FISH-1006 Cleanup of glassfish-batch-connector module

appserver/distributions/payara-web-ml/src/main/assembly/payara-web-ml.xml, appserver/distributions/payara-web/src/main/assembly/payara-web.xml
https://github.com/payara/Payara/pull/5099
=> FISH-753 Missed web distribution assemblies

pom.xml
Includes FISH-631 fix to infinite loop in Grizzly Tls 1.3 handshake.
Also includes fixes to various race conditions in Grizzly HTTP/2 implementation. This makes the h2spec testing much more stable.
=> [FISH-631] [FISH-464] Grizzly 2.4.4.payara-p5 integration

nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/PayaraConfig.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/test/java/fish/payara/nucleus/microprofile/config/spi/PayaraConfigTest.java
Currently just a test - to run against jenkins and make sure it fails.
Should fix the error seen at http://192.168.1.120:8080/job/TestMPTCKs/2588/consoleFull
=> QACI-625 MP Config Cache Concurrency Issues

nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/PayaraConfig.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/test/java/fish/payara/nucleus/microprofile/config/spi/PayaraConfigTest.java
https://github.com/payara/Payara/pull/5120 should have been to the release branch :(
This is a cherry-pick, so shouldn't cause issues merging back into master
=> QACI-625 MP Config Concurrency Issues [Release Branch]

nucleus/pom.xml
Sync up repository names with CI and deployment scripts
=> [QACI-575] renamed ossrh generic name to Payra-specific maven central

appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/ConnectionPool.java
This is a bug fix to cancel the connection pool manager retry task on completion max wait timeout.
Add the following configuration to domain.xml:
````
<jdbc-connection-pool connection-creation-retry-interval-in-seconds="20" max-wait-time-in-millis="10000" datasource-classname="org.apache.derby.jdbc.ClientDataSource" connection-creation-retry-attempts="3" name="SamplePool" res-type="javax.sql.DataSource">
<property name="User" value="app"></property>
<property name="DatabaseName" value="sample"></property>
<property name="serverName" value="mylocalhost"></property>
<property name="PortNumber" value="1527"></property>
<property name="URL" value="jdbc:derby://mylocalhost:1527/sample"></property>
<property name="Password" value="app"></property>
</jdbc-connection-pool>
<jdbc-resource …
```
=> FISH-984 Max Wait Time isn't respected when the JDBC pool is locked for a long time 

appserver/web/weld-integration/src/main/java/org/glassfish/weld/DeploymentImpl.java, nucleus/common/internal-api/src/main/java/fish/payara/nucleus/hotdeploy/ApplicationState.java
This is a feature PR to support java file path from the source root of project for Hot Reload(Incremental Deploy).
https://github.com/payara/ecosystem-vscode-plugin/pull/70
=> FISH-975 Convert source path to package name

SUPPORT.adoc
Exactly what it says on the title.
=> Minor title rename on support policy

appserver/packager/appserver-base/src/main/docs/README.txt
=> Correct readme url

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ApplicationProcessor.java
Update License Header, missed in original FISH-1158 PR
=> FISH-1158 Update License Header

nucleus/common/common-util/src/test/java/org/glassfish/common/util/InstanceCounterTest.java
Instance Counter test was failing under certain circumstances
It was depending on GC doing it's think within a certain timeframe, which was unreasonable.
Fixed it so the timing issues should not be a factor
=> [FISH-1176] Test Failure - Instance Counter test stability

appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardWrapper.java
Race condition NPE during parallel undeployment
MP-TCK parallel test uncovers this issue
Regular test suite
=> [FISH-1177] Fixed servlet undeployment race condition NPE

pom.xml
This is a Payara transformer version upgrade PR which fixes the Jakarta Faces transformer action in deployment descriptor.
=> FISH-625 Upgrade Payara Transformer to v0.2.2

Jenkinsfile
=> Allow parallel testing

appserver/tests/payara-samples/micro-programmatic/pom.xml, appserver/tests/payara-samples/micro-programmatic/src/test/java/fish/payara/samples/programatic/DeployApplicationTest.java, appserver/tests/payara-samples/micro-programmatic/src/test/java/fish/payara/samples/programatic/TestServlet.java
This is a test case to deploy sample web application to Payara Micro instance locally(similar to David's docker container tests).
=> Payara Micro application deployment testcase

nucleus/payara-modules/nucleus-microprofile/config-service/src/test/java/fish/payara/nucleus/microprofile/config/source/DirConfigSourceTest.java
The tests in `nucleus/payara-modules/nucleus-microprofile/config-service` fail because:
* Use of File.separator in regex, "\\" isn't valid - changed so on Windows it replaces "\\\\\\\\"
* Symbolic Links aren't enabled by default on Windows - changed so that the test gets skipped if the permissions aren't granted
=> FISH-1208 Fix Failing Tests on Windows

appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/util/ClusteredSingletonLookupImplBase.java, appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/ContextImpl.java, appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/JavaEEContextUtilImpl.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/InvocationManagerImpl.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/PayaraHazelcastTenant.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/PayaraHazelcastTenantFactory.java
Continuation of #5188 
Added system property fish.payara.tenantcontrol.blocking.disable to disable tenant control blocking
=> [FISH-1293] Empty context should not block due to absent tenant

appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/branding/glassfish-version.properties, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ApplicationProcessor.java, appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/test/app/application/ExceptionMapperTest.java, appserver/pom.xml
This PR enables OpenAPI unit testcase which is fixed by upgrading to HK2 patch and also upgrade the Payara major version.
=> FISH-1282 Enable OpenAPI#testMappedException test case

pom.xml
Update to https://github.com/payara/Payara/pull/5198
=> FISH-1274 Remove unnecessary validation

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java
=> [FISH-1328] Fixed Request Tracing NPE in Concurrent

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/util/DOLUtils.java, appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/JavaEEContextUtilImpl.java
Tenant control uncovered a bug that prevents Hazelcast objects from working properly in EAR files
Fixes #5221 
https://github.com/payara/Payara/issues/5221#issuecomment-832800257
Use "ignore whitespace changes" to review
=> [FISH-1346] Hazelcast Cache now works for EAR files

appserver/common/glassfish-naming/pom.xml, appserver/common/glassfish-naming/src/main/java/com/sun/enterprise/naming/impl/GlassfishNamingManagerImpl.java, appserver/common/glassfish-naming/src/main/java/com/sun/enterprise/naming/util/IIOPObjectFactory.java, appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/GlassFishORBManager.java, appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/RoundRobinPolicy.java, nucleus/core/extra-jre-packages/pom.xml
This is a fix to refactor `java.naming.factory.initial` class property value from `com.sun.jndi.cosnaming.CNCtxFactory` to `org.glassfish.jndi.cosnaming.CNCtxFactory`.
=> FISH-1358 JakartaEE9: ClassNotFoundException org.glassfish.jndi.cosnaming.CNCtxFactory on executing the JavaEE7Samples/EJB/Remote test

api/payara-bom/pom.xml, appserver/tests/payara-samples/pom.xml, appserver/tests/payara-samples/test-utils/src/main/resources/arquillian.xml, pom.xml
This is a PR to upgrade the Payara Arquillian Connector version to `3.0.alpha1` and Arquillian Core API to `1.7.0.Alpha9`.
=> FISH-1313 JakartaEE9: Upgrade Payara Arquillian Connector to 3.0.alpha1

pom.xml
=> [FISH-1374] Update snakeyaml to 1.28

appserver/extras/docker-images/pom.xml, nucleus/admin/server-mgmt/src/test/java/fish/payara/admin/servermgmt/cli/PrintCertificateCommandTest.java
Reverts https://github.com/payara/Payara/pull/5215
Issues with the HTTP changes and JMX
=> Revert FISH-1323

appserver/tests/payara-samples/samples/clustered-singleton/clustered-singleton-test/src/main/java/fish/payara/samples/clustered/singleton/ClusteredSingletonInterceptedEJB.java
=> [QACI-664] Clustered Singleton test race condition fixed

nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/certificate/CertificateRealm.java
=> [FISH-387] Don't check client certificates by default

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/util/DOLUtils.java, appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/JavaEEContextUtilImpl.java, nucleus/common/internal-api/src/main/java/org/glassfish/internal/api/ContextProducer.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/PayaraHazelcastTenant.java
Follow on to #5223 
Fixes #5221
=> [FISH-1346] Hazelcast Cache now works for EAR files - Part 2

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/BaseProcessor.java
Fixes #5218
Signed-off-by: smillidge <steve.millidge@payara.fish>
Fixes Concurrent Modification Exception with empty paths
Tested with test case provided on GitHub issue
Ubuntu 20.04 JDK 8
none
Simple Fix
=> Fix Concurrent Modification Exception FISH-1341

pom.xml
This is a bug fix. Updates HK2 to the new patch level
Fixes #5119 
Depends on https://github.com/payara/patched-src-hk2/pull/23
=> [FISH-1083] Update HK2 to -p6 patch level

pom.xml
=> FISH-786 Upgrade security connectors to a final version

nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/CLICommand.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/MultimodeCommand.java
Pull request to copy code for FISH-1423 from my fork into a branch.
=> Copy code from my fork to a branch

appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/FormAuthenticator.java
=> Remove illegal javadoc character

appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/FormAuthenticator.java
=> Payara 6.2021.1.alpha1 release into Payara6 Master

nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/admin/GetConfigOrdinal.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/admin/SetConfigOrdinal.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/JNDIConfigSource.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/MicroprofileConfigConfiguration.java
Internal Bug
Executed command to configure ordinal value
ubunutu 20.04
maven 3.6.3
=> FISH-1510 Allow configuration of MicroProfile Config Ordinal for JNDI

pom.xml
Split off from https://github.com/payara/Payara/pull/5303
=> FISH-1504 Use JWT-Auth 1.2.1

pom.xml
There are new tests in Payara Enterprise repository but I didn't have time to copy them here. If I have time today, I'll add them but don't expect it.
To be done
=> FISH-786 FISH-1521 Upgrade security connectors to 2.1.0

appserver/tests/payara-samples/samples/openid/pom.xml, appserver/tests/payara-samples/samples/openid/src/main/java/fish/payara/security/oidc/client/GetUserName.java, appserver/tests/payara-samples/samples/openid/src/main/java/fish/payara/security/oidc/client/defaulttests/SecuredPage.java, appserver/tests/payara-samples/samples/openid/src/main/java/fish/payara/security/oidc/client/ear/SomeEJB.java, appserver/tests/payara-samples/samples/openid/src/main/java/fish/payara/security/oidc/client/elpersessiontests/OpenidConfigBeanEL.java, appserver/tests/payara-samples/samples/openid/src/main/java/fish/payara/security/oidc/client/elpersessiontests/SecuredPageEL.java, appserver/tests/payara-samples/samples/openid/src/main/java/fish/payara/security/oidc/server/OidcProvider.java, appserver/tests/payara-samples/samples/openid/src/main/resources/elpersessiontests/META-INF/microprofile-config.properties, appserver/tests/payara-samples/samples/openid/src/main/resources/openid-configuration.json, appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/test/InvalidRedirectURITest.java, appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/test/OpenIdDefaultMultipleRolesInUserInfoTest.java, appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/test/OpenIdDefaultRoleInUserInfoTest.java, appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/test/OpenIdDefaultRolesInUserInfoTest.java, appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/test/OpenIdDefaultTest.java, appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/test/OpenIdDefaultTestMultipleRoles.java, appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/test/OpenIdELInEarTest.java, appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/test/OpenIdELPerSessionInEarTest.java, appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/test/OpenIdELPerSessionTest.java, appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/test/OpenIdELTest.java, appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/test/OpenIdTestUtil.java, appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/test/UseCookiesTest.java, pom.xml
Tests to cover FISH-1521, which was fixed in the connectors repository.
Builds on top of https://github.com/payara/Payara/pull/5337.
=> FISH-1521 Tests for fix of mapping of groups from an OIDC provider

appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/policy/Policy.java
Workaround fix for the TCK, which currently mandates and checks that specifically this error gets thrown (and not any other kind of Deployment/Definition exception). The "proper" fix for this is liable to be a pain and have ramifications since it entails changing the way the deploy command works and checking for serialisation issues when using the DeploymentException class (as well as then reflecting these changes in Arquillian). 
This workaround fix simply adds the exception name to the message so that it can be read and rethrown as it later in Arquillian. This is done because Weld wraps the FaultToleranceException in a generic CDI definition exception, which is then rethrown as a DeploymentException which strips away all throwables/exceptions to avoid serialisation issues (so the …
=> FISH-1518 Add Exception Name to FaultTolerance Message.

.github/ISSUE_TEMPLATE/config.yml
Added a new contact link to the repository's Issue template that will allow users to understand how to report security flaws and vulnerabilities
=> Added new contact link for reporting security issues

pom.xml
This is a component upgrade PR of Payara Transformer to v0.2.5.
=> FISH-1345/FISH-1278 Upgrade Payara Transformer to v0.2.5

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/enhancement-request.md
Add open label to new issues automatically, currently we do this manually.
=> Add open label to new issues

nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/adapter/AdminJerseyServiceIteratorProvider.java, pom.xml
Upgrade Jersey version
Rest Client TCK passes
openjdk version "1.8.0_282" Apache Maven 3.6.3 Ubuntu 20.04.2 LTS
=> FISH-5655 Update Jersey Version to 2.34.payara-p1

appserver/packager/appserver-base/src/main/docs/README.txt
README versions were missed in the update versions section of the scripts, this PR resolves them manually
=> Update README versions

nucleus/pom.xml
Upgraded commons-io to version 2.11.0
Built Payara to see if it builds
Ubuntu 20.04 maven version 3.6.3 openjdk version "1.8.0_292"
=> FISH-5698 Upgraded commons-io to version v2.11.0

appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/service/FaultToleranceServiceImpl.java
NamingException was thrown on the PostConstruct method.
N/A
N/A
Built Payara
ubuntu 20.04 openjdk version "1.8.0_292" maven 3.6.3
N/A
N/A
=> FISH-5724 Stopped throwing NamingException on PostConstruct method

appserver/registration/glassfish-registration/src/main/java/com/sun/enterprise/registration/glassfish/ModuleMap.java, pom.xml
Upgrade ASM to version 9.1
Dependent on https://github.com/payara/patched-src-hk2/pull/24 
Will release new hk2 version once approved
N/A
Built Payara
ubuntu 20.04 Maven 3.6.3 openjdk version "1.8.0_292"
N/A
N/A
=> FISH-5751 Upgrade ASM to version 9.1

nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/PayaraConfig.java
Occasionally, application crashes with exception from ConcurrentHashMap during microprofile configuration processing:
java.lang.IllegalStateException: Recursive update
Deploy reproducer (attached to the JIRA ticket) to root, restart server, try to access http://localhost:8080/ShowConfigValues
Linux, OpenJDK 8
=> FISH-5734 fix recursive call to map.compute

nucleus/pom.xml
Title.
None
None
Built the server, loaded the admin console.
Windows 10, Zulu JDK 8u312, 11.0.13, and 17.0.1
N/A
None
=> FISH-5822 Maven WAR Plugin 3.3.2

pom.xml
Title.
Waiting on approval (✔) and release (✔) of patched EclipseLink
https://github.com/payara/patched-src-eclipselink/pull/14
None
Server starts
OpenSUSE WSL 15.3, JDK 8
N/A
None
=> FISH-5804 Use patched EclipseLink 2.7.9

SUPPORT.adoc
This is a simple update on the role of product management in handling new enhancement requests in the support document.
Approve and merge as quickly as possible.
=> Community Support Update

nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/PayaraConfig.java
Fix the method getOptionalValues that it throws NoSuchElementException if the result is empty.
=> FISH-5746 #5419 Fix the getOptionalValues NoSuchElementException

pom.xml
Release bunch of OpenId improvements, each of them already approved.
=> FISH-5852 release security connector 2.2.0

pom.xml
Brings in better handling of MicroProfile Rest Client proxy URIs.
Jersey PR: https://github.com/payara/patched-src-jersey/pull/111
MicroProfile TCK Runners: https://github.com/payara/MicroProfile-TCK-Runners/pull/156
None
Tested MicroProfile Rest Client against Payara Server remote and managed.
WSL OpenSUSE 15.3, JDK 8.
N/A
None
=> FISH-1519 Jersey 2.34.payara-p2

pom.xml
This is a component upgrade PR of MicroProfile Config to v3.0
MicroProfile Config TCK 3.0
https://github.com/payara/MicroProfile-TCK-Runners/pull/160
=> FISH-5862 Upgrade MicroProfile Config to 3.0

pom.xml
This is a component upgrade PR of MicroProfile Metrics to v4.0
MicroProfile Metrics TCK 4.0
https://github.com/payara/MicroProfile-TCK-Runners/pull/160
=> FISH-5865 Upgrade MicroProfile Metrics to 4.0

appserver/packager/microprofile-package/pom.xml, appserver/payara-appserver-modules/microprofile/healthcheck/src/main/java/fish/payara/microprofile/healthcheck/HealthCheckService.java, appserver/payara-appserver-modules/microprofile/healthcheck/src/main/java/fish/payara/microprofile/healthcheck/HealthCheckType.java, appserver/payara-appserver-modules/microprofile/healthcheck/src/main/java/fish/payara/microprofile/healthcheck/activation/HealthSniffer.java, appserver/payara-appserver-modules/microprofile/healthcheck/src/main/java/fish/payara/microprofile/healthcheck/cdi/extension/HealthCDIExtension.java, appserver/payara-appserver-modules/microprofile/pom.xml, appserver/payara-appserver-modules/pom.xml, pom.xml
This is a component upgrade PR of MicroProfile HealthCheck  to v4.0
MicroProfile HealthCheck  TCK 4.0
https://github.com/payara/MicroProfile-TCK-Runners/pull/160
=> FISH-5863 MicroProfile HealthCheck version upgrade to 4.0

appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/cdi/CdiInitEventHandler.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/cdi/JwtAuthCdiExtension.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/CacheableString.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/JWTAuthenticationMechanism.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/JWTProcessingException.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/JwtKeyStoreUtils.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/JwtPrivateKeyStore.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/JwtPublicKeyStore.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/KeyLoadingCache.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/SignedJWTIdentityStore.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jwt/ClaimValueImpl.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jwt/JsonWebTokenImpl.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jwt/JwtTokenParser.java, pom.xml
This is a PR to support MicroProfile JWT Auth v2.0
MicroProfile JWT Auth TCK 2.0
`Tests run: 190, Failures: 0, Errors: 0, Skipped: 0`
https://github.com/payara/MicroProfile-TCK-Runners/pull/167
=> FISH-5869 MicroProfile JWT Auth v2.0 support

pom.xml
Upgrading fault tolerance to 4
this is a feature to update payara and support MicroProfile Fault Tolerance 4
the following are related PR's:
https://github.com/payara/patched-src-microprofile-fault-tolerance/pull/6
https://github.com/payara/MicroProfile-TCK-Runners/pull/165
this was tested on local environment by executing the MicroProfile Fault Tolerance TCK Runner  with remote option:
command:  mvn clean verify -Ppayara-server-remote
result of tests:
`[INFO] Tests run: 442, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 290.295 s - in TestSuite
[INFO]
[INFO]
[INFO] Tests run: 442, Failures: 0, Errors: 0, Skipped: 0`
Ubuntu 20.04, openJDK 1.8.0_292
It is needed create the new tag version for the Fault Tolerance patched project at nexus, then this can be merged
=> FISH-5864: upgrading fault tolerance to 4

pom.xml
Title.
Note that this means this branch no longer builds until all other fixes are brought in.
Technically none, though this will mean the branch no longer builds.
None
N/A
Windows 11, JDK 11
N/A
None
=> FISH-5915 Update Compile Target

nucleus/pom.xml
Title.
Required for compiling on JDK 11.
None.
None.
Built module utilising plugin on JDK 11.
N/A
None
=> FISH-5921 Update Command Security Plugin

appserver/deployment/client/src/test/java/org/glassfish/deployment/client/DFDeploymentPropertiesTest.java
This test was written under the assumption Properties are ordered - they are not
None
None
Compiled module on JDK 11
Windows 11, JDK 11
N/A
None
=> FISH-5919 Fix DFDeploymentPropertiesTest

appserver/extras/grpc/pom.xml, appserver/extras/grpc/src/main/java/io/grpc/servlet/InternalServerImpl.java, appserver/extras/grpc/src/main/java/io/grpc/servlet/ServletAdapter.java, appserver/extras/grpc/src/main/java/io/grpc/servlet/ServletAdapterBuilder.java, appserver/extras/grpc/src/main/java/io/grpc/servlet/ServletServerStream.java, appserver/tests/payara-samples/samples/grpc/pom.xml
Upgrading gRPC to version 1.43.1
This is a feature to upgrade the Payara gRPC implementation
Manual test from local environment
Windows 11 , zulu jdk 1.8.0_312
=> FISH-5880: upgrading gRPC to version 1.43.1

appserver/distributions/distributions.xml, appserver/distributions/payara-ml/pom.xml, appserver/distributions/payara-web-ml/pom.xml, appserver/distributions/payara-web/pom.xml, appserver/distributions/payara/pom.xml, appserver/packager/appserver-base/src/main/resources/config/branding/glassfish-version.properties, nucleus/common/common-util/src/main/java/com/sun/appserv/server/util/Version.java
Missed sync from Enterprise. Allows easier determination of distribution type.
None
None
Built server (non-quickbuild) - each distribution has the correct type in glassfish-version.properties.
WSL,  JDK 8.
N/A
Port from Enterprise.
=> FISH-981 Add Distribution Type to glassfish-version.properties

appserver/payara-appserver-modules/microprofile/healthcheck/src/main/java/fish/payara/microprofile/healthcheck/HealthCheckService.java
Every webapp with healthcheck is periodically called every 12 seconds. This call may come when the application is not ready such as mid-deployment. This stops HealthCheck calls on apps which aren't ready.
None.
None
Manually tested the warnings outputted to the server logs no longer appear with the reproducer attached.
None
FISH-5937 ticket mentions other errors, these are caused by stopping and starting the server as the reproducer says. These are not HealthCheck related and are not related to this ticket and fix.
=> FISH-5937 Crashes during deploy of app with HealthCheck

appserver/web/gf-weld-connector/src/main/java/org/glassfish/weld/connector/WeldUtils.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/InjectionServicesImpl.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/JCDIServiceImpl.java
Improve cdi scan to solve reported issue: [5530](https://github.com/payara/Payara/issues/5530)
This is a fix of the reported issue when deploying an application with payara community
This was tested by using the following test case code: [code test case](https://github.com/sgflt/payara-test-case/commit/0cdedfb651a247a43ccea63842f05e93d392dd16) 
Link of the results of the tests from jira comment:  [jira comment](https://payara.atlassian.net/browse/FISH-5938?focusedCommentId=59865)
Ubuntu 20.04, Open JDK 11
=> FISH-5530: improve-cdi-scan

appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/util/ClusteredSingletonLookupImplBase.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/util/DOLUtils.java, appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/ContextImpl.java, appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/JavaEEContextUtilImpl.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/InvocationManagerImpl.java, nucleus/common/internal-api/src/main/java/org/glassfish/internal/api/ContextProducer.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/PayaraHazelcastTenant.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/PayaraHazelcastTenantFactory.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/store/ClusteredStore.java
Missed ports from master related to Hazelcast 4.2 upgrade.
Fixes failing TCK `ejb30/lite/packaging/embed/classloader`.
None
None
Ran ejb30/lite/packaging/embed/classloader locally - passed
Server started and allows app deployment
WSL, Zulu JDK 11
N/A
None
=> FISH-5982 Missed Master Ports

pom.xml
Updates Security Connectors to use MicroProfile 5.
Merge and release of https://github.com/payara/ecosystem-security-connectors/pull/175
None
WSL, Zulu 11
N/A
None
=> FISH-6016 Security connectors 3.0.alpha3

appserver/tests/payara-samples/samples/openid/src/main/java/fish/payara/security/oidc/client/GetUserName.java, appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/client/ear/SomeEJB.java, appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/client/elpersessiontests/OpenidConfigBeanEL.java, appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/client/elpersessiontests/SecuredPageEL.java, appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/client/eltests/OpenidConfigBeanEL.java, appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/client/eltests/SecuredPageEL.java, pom.xml
Version updated to 3.0.alpha4
none
Payara tests compilation errors removed
=> FISH-5941 new security-connector version for Payara6

pom.xml
Upgrade to JBatch 2.1.0-M1 as a part of JakartaEE 10
=> FISH-6011: upgrade-jbatch to 2.1.0-M1

appserver/web/web-core/src/main/java/org/apache/catalina/connector/InputBuffer.java, appserver/web/web-core/src/main/java/org/apache/catalina/connector/OutputBuffer.java
Callbacks, especially dataAvailable and allDataRead are delivered in quick succession. Before, passing of these callbacks to application was scheduled as two independent tasks, which resulted in ordering of the callbacks to be undefined, driven by OS scheduling.
Now we always deliver `onDataAvailable` before` onAllDataRead` and that before `onError`.
Similar ordering is imposed for `WriteListener`
This resolved problems with gRPC adapter, where out-of-order processing of async events would result in abrupt closes of connections.
```
Java version: 1.8.0_302, vendor: Azul Systems, Inc., runtime: C:\Program Files\Zulu\zulu-8\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
=> FISH-6025: Impose strict ordering of asynchronous callbacks

pom.xml
After patching hazelcast-kubernetes dependency we need to update its version
None
None
=> FISH-6009 hazelcast-kubernetes dependency now patched

appserver/connectors/descriptors/src/main/resources/glassfish/lib/schemas/connector_2_0.xsd, appserver/jdbc/jdbc-ra/jdbc-ra-distribution/xml/ra-cp.xml, appserver/jdbc/jdbc-ra/jdbc-ra-distribution/xml/ra-dm.xml, appserver/jdbc/jdbc-ra/jdbc-ra-distribution/xml/ra-ds.xml, appserver/jdbc/jdbc-ra/jdbc-ra-distribution/xml/ra-xa.xml, pom.xml
Using new patched version 
None
None
=> FISH-6009 hazelcast-kubernetes now patched 

appserver/connectors/descriptors/src/main/resources/glassfish/lib/schemas/connector_2_0.xsd, appserver/jdbc/jdbc-ra/jdbc-ra-distribution/xml/ra-cp.xml, appserver/jdbc/jdbc-ra/jdbc-ra-distribution/xml/ra-dm.xml, appserver/jdbc/jdbc-ra/jdbc-ra-distribution/xml/ra-ds.xml, appserver/jdbc/jdbc-ra/jdbc-ra-distribution/xml/ra-xa.xml, pom.xml
mq.version updated and connector_2_0.xsd added
None
None
Step by step defined here:
https://payara.atlassian.net/jira/software/c/projects/FISH/boards/163?modal=detail&selectedIssue=FISH-6019)
Zulu JDK 11 on Windows 10 with Maven 3.6.0"-->
=> FISH-6019 using new mq.version

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployment/annotation/handlers/ManagedExecutorDefinitionHandler.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/ConcurrentDefinitionDescriptor.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/node/DeploymentDescriptorNode.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/node/ManagedExecutorDefinitionNode.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/xml/TagNames.java, appserver/deployment/schemas/src/main/resources/glassfish/lib/schemas/application_10.xsd, appserver/deployment/schemas/src/main/resources/glassfish/lib/schemas/jakartaee_10.xsd, appserver/deployment/schemas/src/main/resources/glassfish/lib/schemas/web-app_6_0.xsd, appserver/tests/payara-samples/samples/concurrency/src/main/java/fish/payara/sample/concurrency/annotations/managedexecutor/ManagedExecutorDefinitionRest.java, appserver/tests/payara-samples/samples/concurrency/src/test/java/fish/payara/sample/concurrency/annotations/managedexecutor/ManagedExecutorRestIT.java, appserver/tests/payara-samples/samples/concurrency/src/test/resources/web.xml, appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/node/WebCommonNode.java
This is to add support for the new xml tag managed-executor described on the Concurrency 3.0 api specification
added samples to test implementation
Windows 11, azul JDK 11
=> Fish-6037: support managedexecutor xml tag

appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/ComponentEnvManagerImpl.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/cdi/ConcurrentCDIExtension.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ConcurrentRuntime.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ContextServiceConfig.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ContextServiceDefinitionDescriptorDeployer.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/deployment/annotation/handlers/ContextServiceDefinitionHandler.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/deployment/annotation/handlers/ContextServiceDefinitionListHandler.java, appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/api/ConnectorConstants.java, appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/api/ConnectorsUtil.java, appserver/connectors/connectors-runtime/pom.xml, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/ContextServiceDefinitionDescriptor.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/ResourceDescriptorRegistry.java, appserver/tests/payara-samples/samples/concurrency/pom.xml, nucleus/resources/src/main/java/org/glassfish/resourcebase/resources/api/ResourceConstants.java
Add support for ContextServiceDefinition annotation, creates the context service, allows injection into Resource.
Work in progress, parameters are not yet working.
WIP
=> FISH-6039 Concurrency - ContextServiceDefinition

pom.xml
Upgrade jakarta-annnotation to 2.1.0 as a path to Jakarta EE 10 compatibility
=> FISH-6013 upgrade jakarta-annnotation to 2.1.0

appserver/concurrent/concurrent-connector/src/main/java/org/glassfish/concurrent/config/ManagedExecutorService.java, appserver/concurrent/concurrent-connector/src/main/java/org/glassfish/concurrent/config/ManagedExecutorServiceBase.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ConcurrentRuntime.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/InvocationContext.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/BaseConfig.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ConcurrentObjectFactory.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ContextServiceConfig.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ContextServiceDefinitionDescriptorDeployer.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ManagedExecutorDescriptorDeployer.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ManagedExecutorServiceConfig.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ManagedScheduledExecutorServiceConfig.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/deployment/annotation/handlers/ContextServiceDefinitionHandler.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployment/annotation/handlers/ManagedExecutorDefinitionHandler.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/ContextServiceDefinitionDescriptor.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/ManagedExecutorDefinitionDescriptor.java
First implementation of ContextServiceDefinition.
ContextServiceDefinition allows to specify context behavior of a Managed(Scheduled)ExecutorService.
We continue to fix/implement missing parts of TCK tests, WIP.
Sample webapp with such code:
```
@ContextServiceDefinition(name = "java:app/concurrent/ContextA",
propagated = {ContextServiceDefinition.APPLICATION},
unchanged = ContextServiceDefinition.TRANSACTION)
@ManagedExecutorDefinition(name = "java:app/concurrent/MES1",
maxAsync = 3,
context = "java:app/concurrent/ContextA")
@WebServlet("/asynch")
public class AsynchServlet extends HttpServlet {
@Resource(lookup = "java:app/concurrent/MES1")
ManagedExecutorService mes;
@Override
public void doGet(HttpServletRequest req, HttpServletResponse resp)
throws ServletException {
try ( …
```
=> Fish 6039 contextservicedefinition

pom.xml
This is a dependency update
relates to #5641
=> FISH-6067 Upgrade Jackson 2.12.4 -> 2.12.6

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ConcurrentRuntime.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java
Correct passing context to threads. Custom Context Providers are now working
TCK tests report about 20 failures less
Linux, OpenJDK
=> Fish 5968 custom context providers

pom.xml
This a feature to upgrade the Jakarta Messaging to the latest version to support Jakarta EE 10
N/A
N/A
Test one of the new enhancement of Jakarta messaging 3.1.0 which is "Support repeatable annotations where applicable"
by running the [JMS samples](https://github.com/payara/patched-src-javaee7-samples/tree/master/jms).
Here is the PR for the performed test [JMS Upgrade test PR](https://github.com/payara/patched-src-javaee7-samples/pull/71)
N/A
None
=> FISH-6077 Update Jakarta Messaging to 3.1.0

appserver/concurrent/concurrent-connector/src/main/java/org/glassfish/concurrent/config/ManagedThreadFactory.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ConcurrentRuntime.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ContextServiceDefinitionDescriptorDeployer.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ManagedExecutorDescriptorDeployer.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ManagedThreadFactoryConfig.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ManagedThreadFactoryDescriptorDeployer.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/ContextServiceDefinitionDescriptor.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/node/ApplicationNode.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/node/ContextServiceDefinitionNode.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/xml/TagNames.java, appserver/deployment/schemas/src/main/resources/glassfish/lib/schemas/ejb-jar_4_1.xsd, appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/node/EjbNode.java, appserver/tests/payara-samples/samples/concurrency/src/main/java/fish/payara/sample/concurrency/annotations/contextservice/ContextServiceApplication.java, appserver/tests/payara-samples/samples/concurrency/src/main/java/fish/payara/sample/concurrency/annotations/contextservice/ContextServiceConfigEJBRest.java, appserver/tests/payara-samples/samples/concurrency/src/main/java/fish/payara/sample/concurrency/annotations/contextservice/ContextServiceEJB.java, appserver/tests/payara-samples/samples/concurrency/src/main/java/fish/payara/sample/concurrency/annotations/contextservice/ContextServiceEJBFromConfig.java, appserver/tests/payara-samples/samples/concurrency/src/main/java/fish/payara/sample/concurrency/annotations/contextservice/ContextServiceRest.java, appserver/tests/payara-samples/samples/concurrency/src/main/java/fish/payara/sample/concurrency/annotations/contextservice/util/IntContextProvider.java, appserver/tests/payara-samples/samples/concurrency/src/main/java/fish/payara/sample/concurrency/annotations/contextservice/util/IntContextRestorer.java, appserver/tests/payara-samples/samples/concurrency/src/main/java/fish/payara/sample/concurrency/annotations/contextservice/util/IntContextSnapshot.java, appserver/tests/payara-samples/samples/concurrency/src/test/java/fish/payara/sample/concurrency/annotations/contextservice/ContextServiceApplicationIT.java, appserver/tests/payara-samples/samples/concurrency/src/test/java/fish/payara/sample/concurrency/annotations/contextservice/ContextServiceWebRestIT.java, appserver/tests/payara-samples/samples/concurrency/src/test/resources/ejb-jar4.xml, appserver/tests/payara-samples/samples/concurrency/src/test/resources/web.xml, appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/node/WebCommonNode.java
Add support for context service tag
Adding support  to use ContextService from xml tag configuration
Samples added and TCK executed 
Windows 11, Azul JDK 11
Samples need to be improved because the result to execute the IntContextProvider is some cases return 0
=> Fish-6136: add support for context service tag

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ConcurrentRuntime.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/TransactionSetupProviderImpl.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/deployment/annotation/handlers/ContextServiceDefinitionHandler.java
TCK tests testing unchanged transaction start working and implementation of ALL_REMAINING in the context lists is implemented.
TCK, few more tests work
Linux, OpenJDK
=> Fish 6204 implementation of ALL_REMAINING and unchanged transaction

pom.xml
Makes Payara compatible with JDK 18
=> Updated asm to 9.2 for JDK 18 compatibility

Jenkinsfile, Jenkinsfile-Nightly, appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/ProviderContainerContractInfoImpl.java, appserver/persistence/jpa-container/src/main/java/org/glassfish/persistence/jpa/ServerProviderContainerContractInfo.java, appserver/tests/payara-samples/test-utils/src/main/resources/arquillian.xml, pom.xml
Upgrade EclipseLink to [3.1.0-M1](https://github.com/eclipse-ee4j/eclipselink/releases/tag/3.1.0-M1)
=> FISH-6018 Upgrade EclipseLink to 3.1.0-M1

pom.xml
Upgrade Jackson to 2.12.6.20220326
=> FISH-6215 Upgrade Jackson to version 2.12.6.20220326

nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/remote/RemoteCLICommand.java, nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/LocalServerCommand.java, nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/TimeoutParamDefaultCalculator.java, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ClusterCommandHelper.java, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/LocalStrings.properties, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/RestartClusterCommand.java, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/RestartInstanceCommand.java, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/StartClusterCommand.java, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/StopClusterCommand.java, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/StopInstanceCommand.java, nucleus/cluster/admin/src/main/java/fish/payara/admin/cluster/RestartDeploymentGroupCommand.java, nucleus/cluster/admin/src/main/java/fish/payara/admin/cluster/StartDeploymentGroupCommand.java, nucleus/cluster/admin/src/main/java/fish/payara/admin/cluster/StopDeploymentGroupCommand.java, nucleus/cluster/admin/src/main/manpages/com/sun/enterprise/v3/admin/cluster/restart-instance.1, nucleus/cluster/admin/src/main/manpages/com/sun/enterprise/v3/admin/cluster/start-cluster.1, nucleus/cluster/admin/src/main/manpages/com/sun/enterprise/v3/admin/cluster/start-instance.1, nucleus/cluster/admin/src/main/manpages/com/sun/enterprise/v3/admin/cluster/stop-cluster.1, nucleus/cluster/admin/src/main/manpages/com/sun/enterprise/v3/admin/cluster/stop-instance.1, nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/RestartLocalInstanceCommand.java, nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/StartLocalInstanceCommand.java, nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/StopLocalInstanceCommand.java, nucleus/cluster/cli/src/main/manpages/com/sun/enterprise/admin/cli/cluster/restart-local-instance.1, nucleus/cluster/cli/src/main/manpages/com/sun/enterprise/admin/cli/cluster/start-local-instance.1, nucleus/cluster/cli/src/main/manpages/com/sun/enterprise/admin/cli/cluster/stop-local-instance.1
Added `--timeout` option
N/A
N/A
Built Payara and tested timeout
ubuntu 20.04 maven 3.6.3 openjdk version "11.0.12" 2021-07-20
https://github.com/payara/Payara-Community-Documentation/pull/296
=> FISH-898 Added timeout option to instance commands P6

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/VirtualServerFacade.java
Title.
Resolves the compilation errors for the `VirtualServerFacade` class brought about by the Tomcat changes.
None
None
None
N/A
N/A
None
=> FISH-6176 Adjust imports for VirtualServerFacade

appserver/admingui/cluster/src/main/resources/cluster/clusterInstances.jsf, appserver/admingui/cluster/src/main/resources/cluster/clusters.jsf, appserver/admingui/cluster/src/main/resources/dg/dgInstances.jsf, appserver/admingui/cluster/src/main/resources/dg/dgs.jsf, appserver/admingui/cluster/src/main/resources/shared/instancesExtraButtons.inc, appserver/admingui/cluster/src/main/resources/standalone/standaloneInstances.jsf, appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/ClusterHandler.java, appserver/admingui/common/src/main/resources/shared/listTableButtons.inc, appserver/admingui/core/src/main/resources/org/glassfish/admingui/core/Strings.properties
Option for timeout has been introduced, this will add it to the admin console.
n/a
n/a
Built and tested timeout in admin console
maven 3.6.3, ubuntu 20.04 openjdk version "1.8.0_302"
n/a
n/a
=> FISH-5893 Add Timeout Option to Admin Console

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ConcurrentRuntime.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/TransactionSetupProviderImpl.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ContextServiceDefinitionDescriptorDeployer.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ManagedExecutorDescriptorDeployer.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/deployment/annotation/handlers/ContextServiceDefinitionHandler.java, appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/api/ConnectorsUtil.java, nucleus/resources/src/main/java/org/glassfish/resourcebase/resources/naming/ResourceNamingService.java
Implementation of majority of the context-related stuff in Concurrency, mainly fixing JNDI storing/lookup.
TCK, only 1 failure remains in the context package
Linux, OpenJDK
New default-web.xml needed to copy to domain1/config to overcome temporal issue (tag 18) with old Tomcat/Jasper.
=> Fish 6204 implement context behaviour

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/VirtualServer.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/VirtualServerValve.java
Reimplement the `VirtualServerPipeline` class as a Valve, due to changes in Tomcat APIs.
Also includes the associated changes in the `VirtualServer` class.
None
None
N/A
N/A
N/A
The call to `setIsActive` I've left alone for now to maintain the behaviour, despite on the surface looking wrong: if you pass `false` to that method it does nothing.
The `addValve` method was removed, since it now does nothing but call super. The `removeValve` method was removed since the method it overrides no longer exists, and the calls to it have been prepended to `getPipeline()` which is where the method now lives. `addValve(String valveName)` has been left alone as it wasn't an overriding method.
Also includes some formatting changes because this was written 12+ years ago when 1080p monitors were a thing of …
=> FISH-6193 FISH-6252 Reimplement VirtualServerPipeline as a Valve

appserver/pom.xml
=> FISH-6262 Upgrade Json-smart to version 2.4.8 P6

pom.xml
=> FISH-6275 Upgrade Hazelcast to version 4.2.4

appserver/concurrent/concurrent-impl/src/test/java/org/glassfish/concurrent/runtime/ConcurrentRuntimeTest.java
Fix test in Payara build. Follow the new simplified constructor syntax.
Remove already ignored tests.
Running Payara tests.
=> FISH-6287 fix concurrent implementation tests

nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/APIClassLoaderServiceImpl.java, nucleus/osgi-platforms/felix/src/main/resources/config/osgi.properties
This is a porting ext/lib support [FISH-5955](https://payara.atlassian.net/browse/FISH-5955)
N/A
None
Build and run Payara server
WIndows 11, OpenJDK11, Maven 3.8.4
N/A
None
=> FISH-6272 Port ext/lib support to Payara6

appserver/packager/external/jakarta-ee9-shim/pom.xml, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java, pom.xml
Merge with current state of Payara 6.
TCK tests work properly.
=> Fish 6287 merge concurrency3 to payara6

pom.xml
https://github.com/payara/Payara/pull/5796
=> FISH-6343 Change Parsson to Patched Version (Release Branch)

pom.xml
Compatibility enhancement. Will run on JDK 19
See #5659 and #5716
=> update to asm 9.3 for java 19 compatibility

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/admin/ManagedExecutorServiceBaseManager.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/admin/ManagedExecutorServiceManager.java, appserver/concurrent/concurrent-impl/src/main/resources/org/glassfish/concurrent/admin/LocalStrings.properties, appserver/connectors/descriptors/src/main/resources/glassfish/lib/dtds/payara-resources_1_6.dtd, appserver/connectors/descriptors/src/main/resources/glassfish/lib/dtds/payara-resources_1_7.dtd, appserver/resources/resources-connector/src/main/java/org/glassfish/resources/admin/cli/ResourceConstants.java, appserver/resources/resources-connector/src/main/java/org/glassfish/resources/admin/cli/ResourcesXMLParser.java, appserver/resources/resources-connector/src/main/java/org/glassfish/resources/api/Resource.java, appserver/resources/resources-runtime/src/main/java/org/glassfish/resources/module/ResourcesDeployer.java, appserver/tests/payara-samples/samples/pom.xml, appserver/tests/payara-samples/samples/resources/mes-in-payara-resources-example/pom.xml, appserver/tests/payara-samples/samples/resources/mes-in-payara-resources-example/src/main/java/fish/payara/examples/ApplicationConfig.java, appserver/tests/payara-samples/samples/resources/mes-in-payara-resources-example/src/main/java/fish/payara/examples/MSESResource.java, appserver/tests/payara-samples/samples/resources/mes-in-payara-resources-example/src/main/java/fish/payara/examples/Person.java, appserver/tests/payara-samples/samples/resources/mes-in-payara-resources-example/src/main/java/fish/payara/examples/PersonDao.java, appserver/tests/payara-samples/samples/resources/mes-in-payara-resources-example/src/main/java/fish/payara/examples/PersonResource.java, appserver/tests/payara-samples/samples/resources/mes-in-payara-resources-example/src/main/resources/META-INF/persistence.xml, appserver/tests/payara-samples/samples/resources/mes-in-payara-resources-example/src/main/webapp/WEB-INF/payara-resources.xml, appserver/tests/payara-samples/samples/resources/mes-in-payara-resources-example/src/main/webapp/WEB-INF/web.xml, appserver/tests/payara-samples/samples/resources/mes-in-payara-resources-example/src/main/webapp/index.xhtml, appserver/tests/payara-samples/samples/resources/mes-in-payara-resources-example/src/test/java/fish/payara/examples/ConcurrencyResourcesIT.java, appserver/tests/payara-samples/samples/resources/mes-in-payara-resources-example/src/test/java/fish/payara/examples/ManagedExecutorServiceIT.java, appserver/tests/payara-samples/samples/resources/pom.xml
Allow definition of concurrency resources to be defined in payara-resources.xml
Added test in appserver/tests/payara-samples/samples/resources/mes-in-payara-resources-example
OpenJDK, Linux
TBD
=> Fish 5722 mes in payara resources xml

appserver/connectors/descriptors/src/main/resources/glassfish/lib/dtds/payara-resources_1_7.dtd
Just popped into my head a couple of hours after reviewing that I didn't check this.
=> FISH-5722 Correct DTD

appserver/extras/docker-images/pom.xml
Title.
None
None
Built images and ran unit tests
Windows 10
N/A
None
=> FISH-6398 Update Docker images to 11.0.15, and 17.0.3 (Payara6)

pom.xml
With Faces API 4.0.1 and Faces runner in https://github.com/payara/jakartaee-10-tck-runners it passes TCK.
```
build Payara from this PR and run the runner it: `cd faces-tck && ./run-tck.sh`
Be prepared - it takes 3-3.5 hour to complete!
```
...
[INFO] Faces TCK Signature Test 4.0.0 ..................... SUCCESS [ 17.275 s]
[INFO] Jakarta Faces Parent 4.0.0-SNAPSHOT ................ SUCCESS [  0.005 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:05 h
[INFO] Finished at: 2022-07-13T14:41:29+02:00
```
=> FISH-6085 Upgrade Faces API and Tyrus

Jenkinsfile
Part of pipeline modularisation - will allow us to specify the branch that we want to run against on different Payara distributions
=> Branch config support

pom.xml
Component upgrade, in order to fix jaxrs-tck issue as mentioned on https://github.com/eclipse-ee4j/jakartaee-tck/issues/1052 
it needs jersey upgrade as a solution
None
None
Performed:
+ [rest-tck](https://github.com/payara/jakartaee-10-tck-runners/tree/main/rest-tck)
+ jaxrs-tck, result: [test result](https://jenkins.payara.fish/view/Jakarta%20TCK%20Testing/job/TCK-Suite/458/testReport/), [report](https://jenkins.payara.fish/blue/organizations/jenkins/TCK-Suite/detail/TCK-Suite/458/pipeline/8)
+ quicklook
+ payara-samples
Ubuntu 20.04.4 LTS, OpenJDK11, Maven 3.8.4
None
None
=> FISH-6439 Upgrade jersey to 3.1.0-M7

nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/HoggingThreadsHealthCheck.java
Unsure how to test this since I couldn't reproduce the issue in the first place.
=> FISH-6276 Stop ArithmeticException being thrown

appserver/web/web-core/src/main/java/org/apache/catalina/connector/CoyoteAdapter.java, nucleus/pom.xml
Improve memory for alpn negotiator maps
This PR is to test the jenkins pipeline and verify the whole tests are passing after changing the grizzly npn dependency
Manual testing
Windows 11, Azul JDK 8, Maven 3.8.3
=> Fish-6392: improve memory for alpn negotiator maps

nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/HoggingThreadsHealthCheck.java
Unsure how to test this since I couldn't reproduce the issue in the first place.
=> FISH-6276  Stop ArithmeticException being thrown P6

pom.xml
https://github.com/payara/patched-src-tyrus/pull/3
=> FISH-6072 Use tyrus version 2.1.0.payara-p1

pom.xml
Staging repo:  https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/fishpayara-2092/fish/payara/security/connectors/security-connectors-api/3.0.alpha5/security-connectors-api-3.0.alpha5.pom
=> FISH-6431 Upgrade Payara Security Connectors to version 3.0.alpha5

nucleus/pom.xml
Improve memory for alpn negotiator maps
This PR is to test the jenkins pipeline and verify the whole tests are passing after changing the grizzly npn dependency
Manual testing
Windows 11, Azul JDK 11, Maven 3.8.3
=> FISH-6392: upgrading npn grizzly dependency to test payara server 6

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/GuiUtil.java, appserver/admingui/payara-theme/src/main/resources/branding/masthead.inc
This PR adds Payara Major version to the top tool bar in the Web Admin console.
=> FISH-6399 Implement New Payara 6 Version Text in Header of Payara Server 6

appserver/extras/embedded/shell/glassfish-embedded-static-shell/pom.xml
Port of https://github.com/payara/Payara/pull/5923
=> FISH-6507: Exclude admingui from embedded static shell

nucleus/pom.xml
Upgrading corba version to fix duplicate socket connections
this is a bug fix
This is an upgrade of the corba dependency with the fix to solve issue causing duplicate connections when solving hostname on the cloud environment
This was tested on AWS cloud environment with two instances created. One for the DAS and the second one to execute client application added on the ticket as an attachment here: [FISH-6481](https://payara.atlassian.net/browse/FISH-6481)
AWS cloud with two windows server 2019 instances, azul jdk 8
=> FISH-6481: upgrading corba version to fix duplicate socket connections

appserver/admingui/pom.xml
Enhancement, upgrading commons-fileupload to 1.4
None
None
Build and run Payara server
Windows 11, OpenJDK1.8, Maven 3.8.4
None
None
=> FISH-6391 Fix sonatype-2014-0173 commons-fileupload : commons-fileupload : 1.3.3

appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/domain.xml, nucleus/pom.xml
https://github.com/payara/Payara/pull/5958
=> Merge Payara6-tck into Payara6

pom.xml
https://jenkins.payara.fish/blue/organizations/jenkins/TCK-Suite/detail/TCK-Suite/561/pipeline/8
=> FISH-6543 Upgrade JAXB Impl to 4.0.1

appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContextValve.java, appserver/web/web-core/src/test/java/org/apache/catalina/core/StandardContextValveTest.java
New 0-day vulnerability exploit using ROOT context root deployments
Steps in https://payara.atlassian.net/browse/FISH-6603
using Payara\appserver\extras\payara-micro\payara-micro-distribution\target\payara-micro.jar
=> Fish 6603 payara6

appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContextValve.java, appserver/web/web-core/src/test/java/org/apache/catalina/core/StandardContextValveTest.java
New 0-day vulnerability exploit using ROOT context root deployments
Steps in https://payara.atlassian.net/browse/FISH-6603
using Payara\appserver\extras\payara-micro\payara-micro-distribution\target\payara-micro.jar
=> FISH-6603 : using regex

appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContextValve.java, appserver/web/web-core/src/test/java/org/apache/catalina/core/StandardContextValveTest.java
New 0-day vulnerability exploit using ROOT context root deployments
Steps in https://payara.atlassian.net/browse/FISH-6603
using Payara\appserver\extras\payara-micro\payara-micro-distribution\target\payara-micro.jar
=> Fish-6603 New 0-day vulnerability exploit using ROOT context root deployments

appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/PayaraMicro.java, appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/PayaraMicroBoot.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/RUNTIME_OPTION.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java, appserver/extras/payara-micro/payara-micro-core/src/main/resources/commandoptions.properties, appserver/pom.xml, appserver/tests/fish372-tests/README.md, appserver/tests/fish372-tests/datagrid-tests/pom.xml, appserver/tests/fish372-tests/datagrid-tests/run-tests.sh, appserver/tests/fish372-tests/datagrid-tests/src/main/java/fish/payara/datagrid/DataGrid.java, appserver/tests/fish372-tests/datagrid-tests/src/main/java/fish/payara/datagrid/DataGridApplication.java, appserver/tests/fish372-tests/datagrid-tests/src/main/java/fish/payara/datagrid/DataGridResource.java, appserver/tests/fish372-tests/datagrid-tests/src/main/resources/log4j.properties, appserver/tests/fish372-tests/datagrid-tests/src/test/java/fish/payara/datagrid/tests/PayaraMicroWithNoClusterIT.java, appserver/tests/fish372-tests/datagrid-tests/src/test/resources/log4j.properties, appserver/tests/fish372-tests/datagrid-tests/stop-payara-instances.sh, appserver/tests/fish372-tests/pom.xml, appserver/tests/payara-samples/micro-programmatic/pom.xml, appserver/tests/payara-samples/micro-programmatic/src/test/java/fish/payara/samples/programatic/DataGridTest.java, appserver/tests/payara-samples/micro-programmatic/src/test/java/fish/payara/samples/programatic/DeployApplicationTest.java, appserver/tests/payara-samples/micro-programmatic/src/test/java/fish/payara/samples/programatic/PayaraMicroCommandsTest.java, appserver/tests/payara-samples/micro-programmatic/src/test/java/fish/payara/samples/programatic/PayaraMicroServer.java, appserver/tests/payara-samples/micro-programmatic/src/test/java/fish/payara/samples/programatic/StartPayaraMicroWithNoClusterTest.java, appserver/tests/pom.xml, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/LocalStrings.properties, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastConfigSpecificConfiguration.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java
Port of https://github.com/payara/Payara/pull/5904
None
See main PR.
Started two micro instances with `--nocluster` - they didn't cluster, and hazelcast was still started
Started two micro instances without `--nocluster` - they clustered
Started two micro instances with `--nohazelcast` - they didn't cluster, and hazelcast wasn't started.
Windows 10, JDK 11.
https://github.com/payara/Payara-Documentation/pull/115
None
=> FISH-372 Provide option to disable clustering functionality of Hazelcast on Payara Micro (Payara 6)

appserver/tests/fish372-tests/README.md, appserver/tests/fish372-tests/pom.xml
Title.
Comments raised in review of https://github.com/payara/Payara/pull/5995
=> Fix Typos and Remove Commented Dependency (Payara6)

appserver/tests/fish372-tests/README.md, appserver/tests/fish372-tests/pom.xml
Title.
Comments raised in review of https://github.com/payara/Payara/pull/5995
=> Fix Typos and Remove Commented Dependency

pom.xml
Title.
None
None
Built and started admin console.
Windows 10, JDK 8.
N/A
None
=> FISH-6672 Hibernate Validator 6.2.5.Final

pom.xml
Components upgrade:
+ Upgrade Servlet-API to 4.0.4
+ Upgrade Jackson to 2.13.4
+ Upgrade Snakeyaml to 1.33
+ Upgrade JAXB-API to 2.3.3
+ Upgrade JAXB-OSGi to 2.3.7
+ Upgrade Yasson to 1.0.11
+ Upgrade Weld to 3.1.9.Final
+ Upgrade JAX-WS to 2.3.3
None
None
+ Run Payara Server
+ Run quicklook test
+ Run payara-sample test
Windows 11, WSL, OpenJDK8, Maven 3.8.4
=> FISH-6671, FISH-6675, FISH-6676, FISH-6678, FISH-6679, FISH-6682, FISH-6685, FISH-6690 Components upgrade

pom.xml
Upgrades the Eclipse Transformer to 0.2.9.
Review, build, and publication of https://github.com/payara/transformer/pull/30
None
* Built Transformers.
* Built Payara Server.
* Ran EE7 sample test jaxrs/simple-get using `payara-server-remote` profile using the Payara6 branch (so it's jakarta namespace).
WSL, Zulu 11.0.17
N/A
None
=> FISH-6726 Eclipse Transformer 0.2.9

pom.xml
Title.
None
None
Built server, started and loaded admin console.
WSL, JDK 8.
N/A
None
=> FISH-6684 Jakarta Inject 1.0.5

pom.xml
Upgrade patched Jersey from `2.3.14.payara-p3` to `2.3.18.payara-p1`
https://github.com/payara/patched-src-mojarra/pull/15
None
Build and run payara server
Run payara samples and quicklook test
Windows 11, WSL, OpenJDK8, Maven 3.8.4
None
None
=> FISH-6680 Upgrade mojarra to 2.3.18.payara-p1

pom.xml
Updates Woodstox
Performed manual testing instructions for full server boot
N/A
=> FISH-6698 Update Woodstox to 5.4.0

nucleus/pom.xml
Update multiple Felix components
None
None
Ran domain manual testing steps, started server, instances deployed and tested applications
JDK 8, Maven 3.6.3, Windows 10
=> FISH-6704 FISH-6705 FISH-6706 FISH-6707 FISH-6708 FISH-6709 FISH-6710 Update Felix Components

nucleus/pom.xml, pom.xml
Components upgrade:
+ Upgrade HA API to 3.1.13
+ Upgrade JLine to 3.21.0
+ Upgrade Javaassist to 3.29.2-GA
+ Upgrade metainf-services to 1.9
+ Upgrade mimepull to 1.9.15
N/A
N/A
Build and run payara server,  run payara samples and quicklook
Windows 11, WSL, OpenJDK8, Maven 3.8.4
None
None
=> FISH-6699 FISH-6700 FISH-6701 FISH-6702 FISH-6703 Components upgrade

nucleus/pom.xml, pom.xml
Components upgrade:
+ Upgrade JLine to 3.21.0
+ Upgrade Javaassist to 3.29.2-GA
+ Upgrade metainf-services to 1.9
+ Upgrade snakeyaml to 1.33
+ Upgrade jackson to 2.13.4
None
N/A
Build and run payara server, run payara samples and quicklook
Windows 11, WSL, OpenJDK11, Maven 3.8.4
None
None
=> FISH-6700 FISH-6701 FISH-6702 FISH-6675 FISH-6676 Components upgrade (p6)

nucleus/pom.xml
Title.
None
None
None
Built domain, started domain, loaded admin console.
WSL, JDK 8.
N/A
None
=> FISH-6717 JBoss Logging 3.4.3.Final

nucleus/osgi-platforms/felix/src/main/resources/config/osgi.properties, nucleus/pom.xml
OSGI Util Promise and Function upgrade to 1.2.0
new osgi.ee properties added to support java multiples profile
None
None
Build and run Payara server
Windows 11, Ubuntu WSL, OpenJDK8, Maven 3.8.4
None
None
=> FISH-6711 FISH-6712 Upgrade OSGi Util Promise and Funtion to 1.2.0

appserver/packager/legal/src/main/resources/glassfish/legal/3RD-PARTY-LICENSE.txt, appserver/security/webservices.security/src/main/java/com/sun/enterprise/security/webservices/ClientPipeCreator.java, appserver/security/webservices.security/src/main/java/com/sun/enterprise/security/webservices/SecurityServiceImpl.java, appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/SecurityService.java, appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/ServerPipeCreator.java, appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/WSClientContainer.java, pom.xml
Metro upgrade to 2.4.8.payara-p1
Woodstox upgrade to 6.4.0
woodstox upgrade is required to resolve OSGi issue because metro-jax-ws is using 6.x.x version 
https://github.com/payara/patched-src-metro-wsit/pull/17 - metro re-apply patches
https://github.com/payara/patched-src-metro-jax-ws/pull/7 - metro-jax-ws re-apply patches
None
Build and run payara server
Run payara samples and quicklook test
Windows 11, WSL, OpenJDK8, Maven 3.8.6
None
None
=> FISH-6697 Update Metro to 2.4.8 and Woodstox 6.4.0

nucleus/osgi-platforms/felix/src/main/resources/config/osgi.properties, nucleus/pom.xml
Port of https://github.com/payara/Payara/pull/6078
=> FISH-6711 FISH-6712 Upgrade OSGi Util Promise and Function

nucleus/pom.xml, pom.xml
Updates various components to newer versions.
None
None
Compiled and started the server, created an instance and deployed application.
Windows 10, Maven 3.6.3, JDK 11
None
None
=> FISH-6718 (P6) Upgrade Build and Test Plugins

appserver/tests/payara-samples/pom.xml, nucleus/pom.xml, pom.xml
Updates various components to newer versions.
None
None
Compiled and started the server, created an instance and deployed application.
Windows 10, Maven 3.6.3, JDK 8
None
None
=> FISH-6718 Upgrade Build and Test Plugins

nucleus/osgi-platforms/felix/src/main/resources/config/osgi.properties
Cherry-pick of 58adbed8d7a136c926d65191017981c9fb2d921c
=> FISH-6711 FISH-6712 Upgrade OSGi Util Promise and Function (Cherry-pick)

pom.xml
Upgrade Woodstox to 6.4.0
N/A
N/A
Build and run Payara server
Windows 11, WSL Ubuntu, OpenJDK11, Maven 3.8.4
None
None
=> FISH-6820 Upgrade woodstox to 6.4.0

Jenkinsfile
Integrates SonarQube analysis into the test pipeline
=> [DEVOPS-792] - SonarQube Static Code Analysis

appserver/packager/legal/src/main/resources/glassfish/legal/3RD-PARTY-LICENSE.txt, appserver/security/webservices.security/src/main/java/com/sun/enterprise/security/webservices/ClientPipeCreator.java, appserver/security/webservices.security/src/main/java/com/sun/enterprise/security/webservices/SecurityServiceImpl.java, appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/SecurityService.java, appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/ServerPipeCreator.java, appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/WSClientContainer.java, pom.xml
Appears to break numerous TCKs with a NPE:
```
Caused by: java.lang.NullPointerException
at com.sun.xml.rpc.processor.modeler.j2ee.xml.BaseType.sizeOfElement(BaseType.java:424)
at com.sun.xml.rpc.processor.modeler.j2ee.xml.javaWsdlMappingType.getPackageMappingCount(javaWsdlMappingType.java:41)
at com.sun.xml.rpc.processor.modeler.j2ee.JaxRpcMappingXml.getNSToPkgMapping(JaxRpcMappingXml.java:68)
at com.sun.xml.rpc.processor.config.J2EEModelInfo.setJaxRcpMappingXml(J2EEModelInfo.java:85)
at com.sun.xml.rpc.processor.config.J2EEModelInfo.<init>(J2EEModelInfo.java:77)
at com.sun.xml.rpc.tools.wscompile.J2EEToolPlugin.createModelInfo(J2EEToolPlugin.java:75)
at com.sun.xml.rpc.util.JaxRpcObjectFactoryImpl.createJ2EEModelInfo(JaxRpcObjectFactoryImpl.java:75)
at …
```
=> FISH-6818 FISH-6697 Revert "Merge pull request #6072 from arieki/FISH-6697"

appserver/pom.xml, nucleus/pom.xml, pom.xml
Upgrades all components which also needed upgrading in Enterprise.
Started the server, deployed an application, opened admin console. Ran Payara Samples
Ubuntu 20 (WSL), Zulu JDK 11, Maven 3.6.3
N/A
N/A
=> (P6) FISH-6848 FISH-6849 FISH-6850 FISH-6854 Upgrade Components

pom.xml
Port of #6042 by applying the patch to Soteria 3.0.1 in payara/patched-src-security-soteria@c05d2ba9 and configuring its maven project to run integration tests against Payara 6 remote and setting up maven release plugin.
integration tests in soteria passed
I'll yet look at reported JWT TCK failures and fix them within this PR.
=> FISH-6764: Upgrade Soteria to bring back AuthMechanism-per-webapp functionality

pom.xml
Use Fault Tolerance 4.0.2.payara-p1 (4.0.2 patched to use EE 9.1 & 10 OSGi imports)
https://github.com/payara/patched-src-microprofile-fault-tolerance/pull/9
None
Ran Fault Tolerance TCK.
Windows 11, Zulu JDK 11.
Pending...
None
=> FISH-6762 Fault Tolerance 4.0.2.payara-p1

pom.xml
Upgrade Microprofile Config to version 3.0.2
This is a feature to upgrade Microprofile Config version
None
Ran MicroProfile-Config TCK
`
[INFO] Tests run: 368, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 91.399 s - in TestSuite
[INFO]
[INFO]
[INFO] Tests run: 368, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (verify) @ config-tck ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
`
and full
`
[INFO] Reactor Summary for MicroProfile TCK Suite Parent 1.1-SNAPSHOT:
[INFO]
[INFO] MicroProfile TCK Suite Parent ...................... SUCCESS [  0.374 s]
[INFO] MicroProfile Fault Tolerance TCK Runner ............ SUCCESS [04:22 min]
[INFO] MicroProfile JWT-Auth TCK …
=> Fish 6761 upgrade mp config

pom.xml
Upgrade Microprofile Health  to version 4.0.1
This is a feature to upgrade Microprofile Health
None
Ran MP Health TCK
`
[INFO] Tests run: 28, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.663 s - in TestSuite
[INFO]
[INFO]
[INFO] Tests run: 28, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (verify) @ health-tck ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
`
Ubuntu 20.04, Azul JDK 11, Maven 3.8
=> FISH-6763:upgrade mp health version

nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/utils/DetachedCommandHelper.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/utils/SseCommandHelper.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/AdminCommandInstanceImpl.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/CommandRunnerImpl.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/JobAuthorizationAttributeProcessor.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/JobCleanUpService.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/JobCreatorService.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/JobManagerService.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/JobPersistenceService.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/commands/AttachCommand.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/commands/ListJobsCommand.java, nucleus/tests/admin/pom.xml, nucleus/tests/admin/src/test/java/org/glassfish/nucleus/admin/progress/DetachAttachTest.java, nucleus/tests/admin/src/test/java/org/glassfish/nucleus/admin/progress/JobManagerTest.java
Reverting JobManager removal because of the reported cases here: https://payara.atlassian.net/browse/FISH-6815 and https://payara.atlassian.net/browse/FISH-6947
Creating deployment groups with an instance and start payara-micro same port of the instance then start the deployment group and finally restart the server with success
Ubuntu 20.04, Azul jdk 11, maven 3.8
=> FISH-6983: Reverting JobManager removal

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/deploy/ContextEjbDecorator.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/deploy/ContextEnvironmentDecorator.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/deploy/ContextLocalEjbDecorator.java
Compilation error fixed
None
None
None
None
None
=> FISH-6150-6148-6149 : packages updated

nucleus/security/ssl-impl/src/main/java/com/sun/enterprise/security/ssl/impl/SecuritySupportImpl.java
Similar to
- eclipse-ee4j/glassfish#24218
=> FISH-6963 Make it easier to locate expired certificate

appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/TomcatDeploymentConfig.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/VirtualServer.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/deploy/SecurityCollectionDecorator.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/deploy/SecurityConstraintDecorator.java
Fixing issues for SecurityCollectionDecorator, SecurityConstraintDecorator and CatalinaListener
=> FISH-6156-6157-6146

appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jwt/JwtTokenParser.java, pom.xml
The changes include upgrading MP JWT to 2.1
mp jwt tck 2.1 - https://github.com/payara/MicroProfile-TCK-Runners/pull/204
Build server and run MP JWT TCK
N/A
N/A
=> FISH-6979 Add support for RSA-OAEP-256 for MP JWT 2.1

Jenkinsfile
Run the full/extended JWT Auth TCK rather than just the base.
https://github.com/payara/Payara/pull/6167
See MicroProfile JWT Auth TCK.
Ran full TCK locally.
WSL, Zulu 11.0.17
N/A
None
=> Enable MP JWT-Auth Full TCK

appserver/security/webintegration/src/main/java/com/sun/web/security/realmadapter/JaspicRealm.java
This is a fix that broke MP JWT TCK test
N/A
N/A
+ Build and run MP JWT TCK on local machine
+ [EE10 authentication, authorization, security TCK](https://jenkins.payara.fish/blue/organizations/jenkins/JakartaEE-10-TCK/detail/JakartaEE-10-TCK/282/pipeline/)
N/A
N/A
=> FISH-6906 FISH-6299 FISH-6022 Unify Principals Returned from SecurityContext and HttpServletRequest

appserver/packager/legal/src/main/resources/glassfish/legal/3RD-PARTY-LICENSE.txt
Follow on from https://github.com/payara/Payara/pull/6161
=> FISH-7025 Update Third Party

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/config/OpenApiConfiguration.java
scan lib renamed to follow specs
None
None
=> FISH-6927 : SCAN_LIB_KEY renamed

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/deploy/MessageDestinationDecorator.java
Resolves Compilation Errors in MessageDestinationDecorator. MessageDestination moved package but was completely unchanged
=> FISH-6154 Resolve Compilation Errors in MessageDestinationDecorator

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/deploy/FilterDefDecorator.java
=> FISH-6153 : compile errors fixed

nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/utils/DetachedCommandHelper.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/utils/SseCommandHelper.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/AdminCommandInstanceImpl.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/CommandRunnerImpl.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/JobAuthorizationAttributeProcessor.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/JobCleanUpService.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/JobCreatorService.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/JobManagerService.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/JobPersistenceService.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/commands/AttachCommand.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/commands/ListJobsCommand.java, nucleus/tests/admin/pom.xml, nucleus/tests/admin/src/test/java/org/glassfish/nucleus/admin/progress/DetachAttachTest.java, nucleus/tests/admin/src/test/java/org/glassfish/nucleus/admin/progress/JobManagerTest.java
Port of https://github.com/payara/Payara/pull/6197 (which is a port of https://github.com/payara/Payara/pull/6157)
=> FISH-6815-6947-6983 Revert Job Manager Removal (Release)

nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/utils/DetachedCommandHelper.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/utils/SseCommandHelper.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/AdminCommandInstanceImpl.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/CommandRunnerImpl.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/JobAuthorizationAttributeProcessor.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/JobCleanUpService.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/JobCreatorService.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/JobManagerService.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/JobPersistenceService.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/commands/AttachCommand.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/commands/ListJobsCommand.java, nucleus/tests/admin/pom.xml, nucleus/tests/admin/src/test/java/org/glassfish/nucleus/admin/progress/DetachAttachTest.java, nucleus/tests/admin/src/test/java/org/glassfish/nucleus/admin/progress/JobManagerTest.java
Port of https://github.com/payara/Payara/pull/6157
=> FISH-6815-6947-6983 Revert Job Manager Removal

api/payara-bom/pom.xml
Title.
None
N/A
None
N/A
N/A
None
=> Remove Duplicate BOM Dependency

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/ContextFacade.java
Resolves all compilation errors in ContextFacade replacing all now removed methods with their new counterparts.
=> FISH-6168 Resolve Compilation Errors in ContextFacade

Jenkinsfile
=> Remove Sonarqube Analysis

pom.xml
Just upgrading microprofile dependency to 6.0.
Waiting for Jenkins for complete tests
OpenJDK, Linux
=> FISH-6958 upgrade microprofile to 6

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/GlassfishNetworkListener.java
Fixes the NPE encountered by the Docker images.
None
None
Ran the Docker unit tests
WSL
N/A
None
=> FISH-6907 Fix NPE

appserver/extras/certificate-management/certificate-management-admin/pom.xml, appserver/extras/certificate-management/certificate-management-admin/src/main/java/fish/payara/certificate/management/admin/AbstractRemoteCertificateManagementCommand.java, appserver/extras/certificate-management/certificate-management-admin/src/main/java/fish/payara/certificate/management/admin/AddKeystoreEntryCommand.java, appserver/extras/certificate-management/certificate-management-admin/src/main/java/fish/payara/certificate/management/admin/AddTruststoreEntryCommand.java, appserver/extras/certificate-management/certificate-management-cli/pom.xml, appserver/extras/certificate-management/certificate-management-cli/src/main/java/fish/payara/certificate/management/cli/AbstractCertManagementCommand.java, appserver/extras/certificate-management/certificate-management-cli/src/main/java/fish/payara/certificate/management/cli/AddToKeyStoreCommand.java, appserver/extras/certificate-management/certificate-management-cli/src/main/java/fish/payara/certificate/management/cli/AddToTrustStoreCommand.java, appserver/extras/certificate-management/certificate-management-cli/src/main/java/fish/payara/certificate/management/cli/GenerateSelfSignedCertificateCommand.java, appserver/extras/certificate-management/certificate-management-cli/src/main/java/fish/payara/certificate/management/cli/RemoveExpiredCertsCommand.java, appserver/extras/certificate-management/certificate-management-cli/src/main/java/fish/payara/certificate/management/cli/RemoveFromKeyStoreCommand.java, appserver/extras/certificate-management/certificate-management-cli/src/main/java/fish/payara/certificate/management/cli/RemoveFromTrustStoreCommand.java, appserver/extras/certificate-management/certificate-management-cli/src/main/java/fish/payara/certificate/management/cli/RenewSelfSignedCertificateCommand.java, appserver/extras/certificate-management/certificate-management-cli/src/main/manpages/fish/payara/certificate/management/cli/generate-self-signed-certificate.1, appserver/extras/certificate-management/certificate-management-cli/src/main/manpages/fish/payara/certificate/management/cli/renew-self-signed-certificates.1, appserver/extras/certificate-management/certificate-management-common/pom.xml, appserver/extras/certificate-management/certificate-management-console-plugin/pom.xml, appserver/extras/certificate-management/pom.xml
Syncs the missing certificate management commits from Enterprise.
=> FISH-7101 Sync Missing Certificate Management Commits

appserver/appclient/client/acc/pom.xml, appserver/packager/external/metro-xmlsec/pom.xml
Prospective fix for the ejb30/webservice, webservices12, webservices13, and xml-ws TCKs.
None
None
None
Ran the first 20 tests of webservices12 locally.
WSL OpenSUSE, Zulu 11.0.18
N/A
None
=> FISH-6479 Fix for Webservice Clients (Release)

pom.xml
Components upgrade
N/A
N/A
Build and run Payara server,  run clusterjsp application on multiples instance to verify the web session data
WSL, Windows 11, OpenJDK 11, Maven 3.8.4
N/A
N/A
=> FISH-6864 Upgrade Hazelcast to 5.2.2

pom.xml
Title - it was wrong and I fixed it :)
None
None
None
N/A
None - it's already correct in the docs.
None
=> FISH-7245 Upgrade MicroProfile BOM to 6.0

appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/util/ClusteredSingletonLookupImplBase.java
Workaround for https://github.com/hazelcast/hazelcast/issues/17901
=> FISH-7639 Hazelcast Monitoring Warning: workaround

appserver/tests/payara-samples/samples/microprofile-config/src/test/java/fish/payara/samples/microprofile/config/MicroProfileConfigIT.java, core/pom.xml, nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigExpressionResolver.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/test/java/fish/payara/nucleus/microprofile/config/spi/ConfigExpressionResolverTest.java
This is to upgrade MP Config 3.1 and pass TCK
execution of payara-samples and MP TCK 3.1
unit tests for config from payara-samples:
`
Aug 25, 2023 10:23:43 AM org.jboss.arquillian.container.impl.MapObject populate
WARNING: Configuration contain properties not supported by the backing object fish.payara.arquillian.container.payara.CommonPayaraConfiguration
Unused property entries: {allowConnectingToRunningServer=true}
Supported property names: [adminHttps, debug, ignoreCertificates, libraries, type, target, adminUser, authorisation, domain, adminPort, properties, adminHost, adminPassword]
[INFO] Running fish.payara.samples.microprofile.config.MicroProfileConfigIT
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.55 s - in …
=> Fish 7689 upgrading config 3.1 for mp 6.1

core/pom.xml
Upgrades the Weld API to 5.0.SP3
None
None
Started Server and loaded the admin console - no errors.
OpenSUSE Leap 15.5 WSL, Zulu 11.0.20
N/A
None
=> FISH-6867 Weld API 5.0.SP3

pom.xml
Upgrade istack commons to 4.2.0
complete build
=> FISH-6865 Upgrade istack commons to 4.2.0

api/payara-bom/pom.xml, appserver/tests/payara-samples/samples/opentelemetry/src/main/java/fish/payara/samples/otel/manual/ManualTracing.java, core/pom.xml, nucleus/payara-modules/opentracing-adapter/src/main/java/fish/payara/opentracing/OpenTelemetryService.java
Upgrading opentelemetry to 1.29.0
Execution of payara samples on local environment and jenkins pipeline
Ubuntu 20.04, Azul JDK 11, maven 3.8.6
=> Fish 7226 upgrading opentelemetry to 1.29.0 mp 6.1

appserver/packager/legal/src/main/resources/glassfish/legal/3RD-PARTY-LICENSE.txt
Title. Missed the update in https://github.com/payara/Payara/pull/6373
=> FISH-6863 Update 3RD-PARTY-LICENSE.txt

appserver/packager/legal/src/main/resources/glassfish/legal/3RD-PARTY-LICENSE.txt
Adding missed upgrade for opentelemetry license
=> FISH-7226: upgrading license opentelemetry version

appserver/packager/legal/src/main/resources/glassfish/legal/3RD-PARTY-LICENSE.txt
Update santuario in 3RD-PARTY-LICENSE.txt
=> FISH-6866 Update 3RD-PARTY-LICENSE.txt

core/pom.xml
Cherry-picks our additional null check to latest Tyrus and updates Payara to use it.
https://github.com/payara/patched-src-tyrus/pull/5
None
Built Tyrus, built server, started server, loaded admin console.
Windows 11, Zulu 11.0.20
N/A
None
=> FISH-6885 Tyrus 2.1.3.payara-p1

nucleus/admin/template/src/main/resources/docroot/index.html
Updates links and copyright on the welcome page.
None
None
Started server, loaded localhost:8080 - tried all links.
WSL, Zulu 11.0.20
N/A
None
=> FISH-7753 Update Welcome Page

.github/workflows/assign-community-prs.yaml
Quick pull request to add a missing fix to GA workflow for community contributions.
=> Minor fix to GA workflow

Jenkinsfile
Title. Do the thing.
None
None
Jenkins
N/A
None
=> FISH-7278 Use New MicroProfile TCK branch

core/pom.xml
Title.
This breaks the TCK for us - reverting for now pending investigation.
None
N/A
None
N/A
N/A
None
=> Revert "FISH-6876 FISH-7757 Parsson 1.1.4 & JSON-P API 2.1.2"

appserver/tests/payara-samples/samples/use-bundled-jsf-primefaces/src/test/java/fish/payara/samples/usebundledjsf/primefaces/DontUseBundledJsfTest.java, appserver/tests/payara-samples/samples/use-bundled-jsf-primefaces/src/test/java/fish/payara/samples/usebundledjsf/primefaces/ParallelUseBundledJsfTest.java, appserver/tests/payara-samples/samples/use-bundled-jsf-primefaces/src/test/java/fish/payara/samples/usebundledjsf/primefaces/UseBundledJsfEarTest.java, appserver/tests/payara-samples/samples/use-bundled-jsf-primefaces/src/test/java/fish/payara/samples/usebundledjsf/primefaces/UseBundledJsfTest.java
Improves the maven resolver format.
=> FISH-6519 Test Improvement

core/pom.xml
This is to add last version of specs for MP 6.1
=> Fish-7776: adding last version of mp specs 6.1

core/pom.xml
Update to latest Catalina 10.1.12.
=> Update Feature Branch to Latest Catalina

pom.xml
Updates the titular property.
None
None
Built server, started admin console.
Windows 11, Zulu 11.0.20.1
Pending...
None
=> FISH-7836 Update MicroProfile Release Version Property

pom.xml
https://github.com/payara/patched-src-eclipselink/pull/27
=> FISH-7531 FISH-7808 Use eclipselink 4.0.1.payara-p2

appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/FormAuthenticator.java
Ports fix from Tomcat for CVE-2023-41080
https://github.com/apache/tomcat/commit/e3703c9abb8fe0d5602f6ba8a8f11d4b6940815a
None
None
https://github.com/payara/Payara-Documentation/pull/336
None
=> FISH-7947 Avoid Protocol Relative Redirects

nucleus/admin/server-mgmt/src/main/java/fish/payara/admin/servermgmt/cli/RestartDomainsCommand.java, nucleus/admin/server-mgmt/src/main/java/fish/payara/admin/servermgmt/cli/StartDomainsCommand.java, nucleus/admin/server-mgmt/src/main/java/fish/payara/admin/servermgmt/cli/StopAllDomainsCommand.java, nucleus/admin/server-mgmt/src/main/java/fish/payara/admin/servermgmt/cli/StopDomainsCommand.java
Added domainTimeout parameter.
n/a
n/a
manual testing
ubuntu 22.04..02lts, maven 3.8.6, jdk 11
pending
=> FISH-7869 Add additional timeout for domains commands

appserver/jms/admin/src/main/java/org/glassfish/jms/admin/cli/JMSDestination.java, appserver/jms/jms-core/src/main/java/com/sun/enterprise/connectors/jms/system/MQAddressList.java, appserver/jms/jms-core/src/main/java/com/sun/enterprise/connectors/jms/util/JmsRaUtil.java, nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/Domain.java, nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/Server.java, nucleus/admin/config-api/src/main/java/fish/payara/enterprise/config/serverbeans/DeploymentGroup.java, nucleus/admin/config-api/src/main/java/org/glassfish/config/support/Constants.java, nucleus/admin/config-api/src/main/java/org/glassfish/config/support/DomainXmlPreParser.java, nucleus/admin/config-api/src/main/java/org/glassfish/config/support/InstanceReaderFilter.java, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/InstanceRegisterInstanceCommand.java, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ListInstancesCommand.java, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/PostRegisterInstanceCommand.java
=> Revert "FISH-7132 : handling deployment groups  in the same way done by clusters"

api/payara-bom/pom.xml, appserver/appclient/client/acc/pom.xml, appserver/packager/external/metro-xmlsec/pom.xml, appserver/packager/legal/src/main/resources/glassfish/legal/3RD-PARTY-LICENSE.txt, pom.xml
Patched Metro release https://github.com/payara/patched-src-metro-wsit/pull/23
Had to upgrade woodstox due to osgi issues
=> FISH-7964 FISH-7239 FISH-7222 Upgrade Metro, Santuario and Woodstox

appserver/jms/admin/src/main/java/org/glassfish/jms/admin/cli/JMSDestination.java, appserver/jms/jms-core/src/main/java/com/sun/enterprise/connectors/jms/system/MQAddressList.java, appserver/jms/jms-core/src/main/java/com/sun/enterprise/connectors/jms/util/JmsRaUtil.java, nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/Domain.java, nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/Server.java, nucleus/admin/config-api/src/main/java/fish/payara/enterprise/config/serverbeans/DeploymentGroup.java, nucleus/admin/config-api/src/main/java/org/glassfish/config/support/Constants.java, nucleus/admin/config-api/src/main/java/org/glassfish/config/support/DomainXmlPreParser.java, nucleus/admin/config-api/src/main/java/org/glassfish/config/support/InstanceReaderFilter.java, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/InstanceRegisterInstanceCommand.java, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ListInstancesCommand.java, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/PostRegisterInstanceCommand.java
=> Revert "Revert "FISH-7132 : handling deployment groups  in the same way done by clusters""

appserver/tests/payara-samples/samples/payara-expression-config-properties/pom.xml, appserver/tests/payara-samples/test-domain-setup/src/test/java/fish/payara/samples/setuptests/ViewLogWarningErrorTest.java
Various fixes and changes to allow running the tests on Windows.
Also requires https://github.com/payara/Payara/pull/6461
None
None
Ran the tests on Windows, duh.
Windows!
N/A
None
=> Run Samples on Windows

appserver/extras/docker-images/pom.xml
=> FISH-7997 FISH-7998 update docker jdk

appserver/tests/payara-samples/repackaged/jacc-provider-repackaged/pom.xml, core/pom.xml, nucleus/pom.xml, pom.xml
Switch to using the new Nexus URL.
None
None
Cleaned local maven repo, set up new passwords in maven config, built server.
Windows 11
N/A
None
=> ITOPS-2508 Use New Nexus URL

appserver/packager/legal/src/main/resources/glassfish/legal/3RD-PARTY-LICENSE.txt, core/pom.xml
Updates Hazelcast to 5.3.6
None
None
Started DAS and along with two local instances - clustered and no obvious errors.
WSL
N/A
None
=> FISH-8051 Hazelcast 5.3.6

appserver/packager/legal/src/main/resources/glassfish/legal/3RD-PARTY-LICENSE.txt
Title.
None
N/A
N/A
N/A
N/A
None
=> Update MicroProfile 3rd-party

appserver/packager/glassfish-web/pom.xml
Title, noticed some duplicate dependencies in a pom during other work.
None
None
None
My eyes.
N/A
Duplicated from line 212 of the same pom.
=> Remove Duplicate Dependencies

appserver/admingui/healthcheck-service-console-plugin-l10n/src/main/resources/fish/payara/admingui/healthcheck/Strings_ja.properties, appserver/admingui/healthcheck-service-console-plugin/src/main/resources/fish/payara/admingui/healthcheck/Strings.properties, appserver/admingui/healthcheck-service-console-plugin/src/main/resources/healthcheck/checkers/stuckThreadsConfiguration.jsf, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HealthCheckStuckThreadExecutionOptions.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/GetHealthCheckConfiguration.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/SetHealthCheckServiceConfiguration.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/configuration/StuckThreadsChecker.java, nucleus/payara-modules/healthcheck-stuck/src/main/java/fish/payara/nucleus/healthcheck/stuck/StuckThreadsHealthCheck.java
=> FISH-6466 : port from Payara-Enterprise 5

api/payara-bom/pom.xml, core/pom.xml
https://github.com/payara/patched-src-jaxb-api/pull/1
=> FISH-7223 FISH-8085 Upgrade IMQJMQ and JAXB-API

appserver/extras/docker-images/pom.xml, appserver/extras/docker-images/tests/pom.xml
Merge of https://github.com/payara/Payara/pull/6505 and https://github.com/payara/Payara/pull/6508 to the release branch
None
None
Pending...
Windows 11
https://github.com/payara/Payara-Documentation/pull/347
None
=> FISH-8129 Add JDK 21 Docker Images (Release Branch)

core/core-parent/pom.xml, core/pom.xml, pom.xml
=> FISH-8063 Generate javadoc and sources for Core

pom.xml
Update to H2 2.2.224 ([changes](https://github.com/h2database/h2database/compare/version-2.2.220...version-2.2.224)).
=> FISH-8048 Update to H2 2.2.224

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/ApplicationHandlers.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLoaderService.java
When the application is deployed to an instance and the server is restarted, all Module and Component data is lost.
None
None
* Started domain
* Created an instance and started it
* Deployed clusterjsp to the instance
* Loaded the admin console and checked under Applications -> clusterjsp and check that the modules and components are present
* Restart the DAS instance and check again - should still be there
* Restart the instance and check again - should still be there
Windows 11, Zulu JDK 11.0.21
N/A
Port of https://github.com/payara/Payara-Enterprise/pull/1061
=> FISH-6659 Modules and Components Lost After Restart

appserver/admingui/common/src/main/resources/commonTask.jsf, appserver/admingui/core/src/main/resources/org/glassfish/admingui/core/Strings.properties
Link to marketing, feedback page.
Link opens the feedback page in a new tab.
=> FISH-8035 Add Feedback Link to Admin UI

Jenkinsfile
Work to make the "PR testing" job to run the tests in parallel
=> FISH-8205 - run the tests in the pipeline in parallel

Jenkinsfile
https://github.com/payara/Payara/pull/6565
https://github.com/payara/cargotracker/pull/34
None
Ran locally using payara-server-remote, payara-server-managed, and payara-server-embedded profiles.
Windows 11, Zulu 21.0.2
N/A
None
=> Test CargoTracker using Payara7 branch

core/pom.xml
Testing updating OSGi & Felix in HK2
https://github.com/payara/patched-src-hk2/pull/31
None
Built locally and ran MicroProfile OpenAPI TCK - seemed to work.
Windows 11, JDK 11.0.22
N/A
None
=> FISH-8320 Update OSGi & Felix in HK2

nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/RestartInstanceCommand.java, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/StartInstanceCommand.java
Making instance restart sync with status icon
This is a fix to set the correct status when restarting and instance from Admin UI
Manual testing from UI on the section of instances and cluster:
instances:
clicking restart
wait until new instances is restarted with correct status
process on the background working correctly:
cluster section:
click restart:
wait until instances are ready
last status reported correctly
windows 11, maven 3.9.5
=> FISH-7364: making status sync when restarting instance

Jenkinsfile
Should speed up the build of the server a bit.
None
None
Built server with and without labelled options - speeds up build of Core by a few minutes.
Windows 11, Zulu JDK 11.0.22
N/A
None
=> Skip Generating Javadoc and Sources in Jenkins

.github/dependabot.yml
=> FISH-8337 enable dependabot payara6

nucleus/pom.xml
Removes the unused plugin declaration.
None
None
Built the server - everything was bon.
Windows 11
N/A
None
=> Remove Unused Remote Resources Plugin

appserver/pom.xml
Ports https://github.com/payara/Payara-Enterprise/pull/1236
=> FISH-8560 Bump net.minidev:accessors-smart from 2.4.11 to 2.5.1

appserver/extras/embedded/build.xml
Researched how multirelease jars work  - figured out that the different java version files are stored in `META-INF/versions` folder and are only picked up if the Multi-Release option is present in the Manifest.
I Ran Embedded before this and after, the exception is no longer thrown and Embedded starts successfully and I can access deployed application
=> FISH-8481 Fix Embedded

nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/HSTSFilter.java
=> FISH-8543 Check if HSTS Header is already present

appserver/admingui/cluster/src/main/resources/cluster/clusterSystemPropertiesButtons.jsf, appserver/admingui/common/src/main/resources/configuration/configSystemPropertiesButtons.jsf, appserver/appclient/client/acc-config/pom.xml, appserver/extras/docker-images/pom.xml, appserver/extras/docker-images/tests/pom.xml, appserver/payara-appserver-modules/microprofile/metrics/pom.xml, appserver/pom.xml, appserver/tests/fish372-tests/datagrid-tests/pom.xml, appserver/tests/payara-samples/pom.xml, appserver/tests/payara-samples/repackaged/smallrye-config-repackaged/pom.xml, appserver/tests/payara-samples/samples/cleanboot/pom.xml, appserver/tests/payara-samples/samples/concurrency/pom.xml, appserver/tests/payara-samples/samples/reproducers/pom.xml, appserver/tests/payara-samples/samples/use-bundled-jsf-primefaces/pom.xml, appserver/tests/quicklook/pom.xml, core/core-parent/pom.xml, core/pom.xml, nucleus/admin/server-mgmt/pom.xml, nucleus/deployment/common/src/main/java/org/glassfish/loader/util/ASClassLoaderUtil.java, nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/GenericGrizzlyListener.java, nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/HSTSFilter.java, nucleus/grizzly/nucleus-grizzly-all/pom.xml, nucleus/packager/external/opentelemetry-repackaged/pom.xml, nucleus/packager/external/vboxjws/pom.xml, nucleus/pom.xml, pom.xml
Syncs applicable changes from the master branch.
Hopefully didn't miss anything.
None
None
Built the server and loaded the admin console.
Windows 11, Zulu 21.0.2
N/A
None
=> Master Sync 10/05/2024

core/pom.xml
Reverts payara/Payara#6705
Causes build to fail
=> Revert "Bump org.apache.maven.plugins:maven-source-plugin from 3.2.1 to 3.3.1"

nucleus/pom.xml
Port of https://github.com/payara/Payara-Enterprise/pull/1319
=> FISH-8686 Bump commons-io:commons-io from 2.11.0 to 2.16.1

core/pom.xml
=> Revert maven source upgrade

.github/workflows/generate-metrics-report.yml
Continuation of #6727, with added fixes to report the correct data.
=> Final fixes to metrics report action

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/BundleDescriptor.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/archivist/Archivist.java, appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/descriptor/EjbBundleDescriptorImpl.java, appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/descriptor/EjbDescriptor.java
This reverts commit 1e0a33e209dbe380f3f4e11555bcfaa6de93fb7f, reversing changes made to 3afdc5bdf30b5c2b8ade455f81ab60937b42607d.
=> FISH-8775 Revert "Merge pull request #6664 from jGauravGupta/FISH-8309"

nucleus/pom.xml
Restores missing manpages for the asadmin command as well as the commands from several other sub-modules.  
Fixes #6592   
Built Payara and deployed a simple application.
=> FISH-8437 FISH-8820 Restore missing manpages.

appserver/web/web-naming/src/main/java/org/apache/naming/resources/FileDirContext.java
Built Payara and deployed a basic application.
A symbolic link was created in the application root and `allowLinking=true` was set.
JDK 11 on Ubuntu 22.04
=> FISH-8399 Make allowLinking follow symbolic links.

core/pom.xml
Only API changed, not implementation
Did local build
Waiting for Jenkins tests if anything breaks
OpenJDK 21, Linux
=> FISH-8885 Upgrade Validation to 3.1

pom.xml
Title.
Replaces https://github.com/payara/Payara/pull/6723 as still awaiting CLA
None
None
Jenkins
N/A
None
=> FISH-8872 Upgrade Payara Arquillian containers to 3.0

appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/EntityManagerFactoryWrapper.java, appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/EntityManagerWrapper.java, appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/QueryWrapper.java, appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/StoreProcedureQueryWrapper.java, appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/TypedQueryWrapper.java, appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/spi/util/EntityManagerMethod.java, appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/spi/util/EntityManagerQueryMethod.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/PersistenceUnitDescriptor.java, appserver/packager/external/jakarta-ee11-shim/pom.xml, appserver/persistence/jpa-container/src/main/java/org/glassfish/persistence/jpa/PersistenceUnitInfoImpl.java, core/pom.xml, pom.xml
=> FISH-8882 FISH-8883 Upgrade Jakarta Persistence

nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/admin/ClearCache.java
FISH 8887 typo in ClearCache
Added new REST endpoint with correct spelling. Could not change just the typo because Enterprise 6 calls this class from Community.
ran build
=> FISH-8887 new REST endpoint with correct spelling.

appserver/web/weld-integration/src/main/java/org/glassfish/weld/DeploymentImpl.java
This is a fix for CDI 4.1 execution to pass TCK's that expect to inject some bean references from available archives not included on a new one created during the deployment process.
Latest execution of TCK with upgraded versions for CDI 4.1:
`
[INFO]  [mvn.test] [INFO] Tests run: 1334, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 504.0 s -- in TestSuite
[INFO]  [mvn.test] [INFO]
[INFO]  [mvn.test] [INFO] Results:
[INFO]  [mvn.test] [INFO]
[INFO]  [mvn.test] [INFO] Tests run: 1334, Failures: 0, Errors: 0, Skipped: 0
[INFO]  [mvn.test] [INFO]
[INFO]  [mvn.test] [INFO]
[INFO]  [mvn.test] [INFO] --- maven-jar-plugin:3.4.2:test-jar (default) @ weld-payara-runner-tck ---
[INFO]  [mvn.test] [INFO]
[INFO]  [mvn.test] [INFO] --- maven-surefire-report-plugin:3.2.5:report-only …
=> Fish 9109 fixing remaining issue cdi tck

core/pom.xml
https://github.com/payara/patched-src-tyrus/pull/6
=> FISH-8933 Upgrade tyrus to 2.1.5.payara-p1

appserver/web/jsf-connector/src/main/java/org/glassfish/faces/integration/GlassFishInjectionProvider.java, pom.xml
Upgrades Mojarra to 4.0.7 with patches reapplied.
Merge of patched project PR, and release of patched artefact.
https://github.com/payara/patched-src-mojarra/pull/22
None
Started the admin console and clicked around - nothing obviously broken.
Windows 11, Java 11.
N/A
None
=> FISH-8142 Upgrade Mojarra to 4.0.7 with Patches Reapplied

appserver/web/jsf-connector/src/main/java/org/glassfish/faces/integration/GlassFishInjectionProvider.java, pom.xml
The Mojarra upgrade breaks the Faces TCK.
Reverting for now until we fix.
None
None
Ran the Faces TCK
Jenkins
N/A
None
=> FISH-9184 Revert "FISH-8142 Upgrade Mojarra to 4.0.7 with patches reapplied"

appserver/tests/payara-samples/pom.xml, appserver/tests/payara-samples/samples/concurrency/pom.xml
Also adds the extra BOMs and dependencies which were removed in the newer BOM.
None
None
Jenkins
N/A
None
=> Update Arquillian to 1.9.1.Final

appserver/admin/cli-optional/src/main/java/com/sun/enterprise/admin/cli/optional/DBControl.java, nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java, nucleus/admin/util/src/main/java/com/sun/enterprise/admin/remote/RemoteAdminCommand.java
FISH-9196 spot bugs default encoding
SpotBugs issues relating the code using default encoding. Specified to use UTF_8
Ran spotbugs against changes
=> FISH-9196 spot bugs default encoding

appserver/admin/cli-optional/src/main/java/com/sun/enterprise/admin/cli/optional/DBControl.java, appserver/concurrent/concurrent-impl/pom.xml, appserver/extras/docker-images/pom.xml, appserver/extras/docker-images/tests/pom.xml, appserver/jdbc/jdbc-config/pom.xml, appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/GlassFishORBManager.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/impl/MetricsServiceImpl.java, appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/micro/services/PayaraInstanceImpl.java, appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/micro/services/asadmin/SendAsadminCommand.java, appserver/payara-appserver-modules/rest-monitoring/rest-monitoring-war/pom.xml, appserver/pom.xml, appserver/tests/fish372-tests/datagrid-tests/pom.xml, appserver/tests/fish372-tests/pom.xml, appserver/tests/payara-samples/pom.xml, appserver/tests/payara-samples/repackaged/smallrye-config-repackaged/pom.xml, appserver/tests/payara-samples/samples/concurrency/pom.xml, appserver/tests/payara-samples/test-utils/pom.xml, appserver/web/jsf-connector/src/main/java/org/glassfish/faces/integration/GlassFishInjectionProvider.java, appserver/web/weld-integration/pom.xml, core/core-parent/pom.xml, core/pom.xml, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/CLICommand.java, nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java, nucleus/admin/util/src/main/java/com/sun/enterprise/admin/remote/RemoteAdminCommand.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/SnifferManagerImpl.java, nucleus/packager/external/opentelemetry-repackaged/pom.xml, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/admin/ClearCache.java, nucleus/resources/src/main/java/org/glassfish/resourcebase/resources/util/BindableResourcesHelper.java, pom.xml
Syncs Payara7 with main
None
None
Built the server and started the admin console.
Windows 11, Zulu 21.0.4, Maven 3.9.8
N/A
None
=> Master Sync 13/08/2024

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/RestUtil.java
- Resolves FISH-9197
Built and started the server, changed the admin password via the admin gui, checked the logs to see if the new password appeared.
Maven home: 3.9.6
=> FISH-9197 Masking

api/payara-bom/pom.xml, appserver/packager/external/jakarta-ee11-shim/pom.xml, appserver/packager/glassfish-web/pom.xml, appserver/pom.xml, appserver/web/jstl-connector/pom.xml, appserver/web/jstl-connector/src/main/java/org/glassfish/jstl/integration/GlassFishTldProvider.java, core/pom.xml, pom.xml
WASP has replaced the impl which is why references are replaced
Shim is not needed anymore due to this upgrade.
=> FISH-9571 FISH-9572 Upgrade JSTL API

Jenkinsfile
=> FISH-9332: use a new branch for Cargotracker

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/AdminAdapter.java, nucleus/osgi-platforms/osgi-cli-remote/src/main/java/org/glassfish/osgi/cli/remote/OSGiShellCommand.java
FISH-9770 spotbug issues relating to default encoding.
I have changed from the code using its default encoding, to using UTF_8 as suggested by spotbugs.
built and have also ran spotbugs against the changes to make suer they had been fixed.
=> FISH-9770 spot bugs default encoding

pom.xml
Include Eclipselink patch: https://github.com/payara/patched-src-eclipselink/pull/32
Patch comes from a customer, I rewrote it to follow Eclipselink way of coding
Luis' https://github.com/payara/patched-src-eclipselink/pull/35
https://github.com/payara/patched-src-eclipselink/pull/32
Tested by customer
https://github.com/payara/patched-src-eclipselink/pull/35
This is only reproducible on Linux environment
You can use a Linux Distribution or a VM on Windows
=> FISH-9063 FISH-9551 Upgrade Eclipselink to 4.0.1.payara-p3

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/WebBundleDescriptor.java, appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/SecurityDeployer.java, appserver/security/core-ee/src/main/java/com/sun/enterprise/security/jacc/JaccWebAuthorizationManager.java, nucleus/security/core/src/main/java/com/sun/enterprise/security/PolicyLoader.java
This is to fix failing test from the authorization TCK that requires a pre processing of custom factories for the PolicyConfigurationFactory provider and PolicyFactory provider
Execution of authorization TCK with the following results:
`
[INFO] Reactor Summary for Jakarta Authorization TCK - main 3.0.0:
[INFO]
[INFO] Jakarta Authorization TCK - main ................... SUCCESS [ 19.194 s]
[INFO] common ............................................. SUCCESS [  4.471 s]
[INFO] Authorization TCK Signature Test ................... SUCCESS [  6.343 s]
[INFO] app-custom-policy .................................. SUCCESS [ 16.106 s]
[INFO] app-custom-policy2 ................................. FAILURE [ 15.753 s]
[INFO] app-custom-policyfactory ........................... SUCCESS [ 15.726 s]
[INFO] …
=> Fish 9730 fixing authorization tck tests for custom policy

appserver/admingui/cdieventbus-notifier-console-plugin/src/main/resources/cdieventbus/cdiEventbusNotifierConfiguration.jsf, appserver/admingui/eventbus-notifier-console-plugin/src/main/resources/eventbus/eventbusNotifierConfiguration.jsf, appserver/admingui/jms-notifier-console-plugin/src/main/resources/jms/jmsNotifierConfiguration.jsf, appserver/admingui/payara-console-extras/src/main/resources/fish/payara/admingui/extras/Strings.properties, appserver/admingui/payara-console-extras/src/main/resources/notification/notification.jsf, nucleus/common/internal-api/src/main/java/fish/payara/internal/notification/admin/BaseSetNotifierConfigurationCommand.java, nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/admin/GetNotificationConfigurationCommand.java, nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/admin/SetNotificationConfiguration.java
- Resolves FISH-9693
- Adds a dropdown in the Admin Console to set the event filtering level for notifiers.
- Built the server.
- Opened the Admin Console
- Navigated to Notifications
- Changed the filter via the dropdown.
- Checked this worked via the `asadmin get-___-notifier-configuration` commands.
- Used the `asadmin get-___-notifier-configuration` commands to edit the notifiers.
- Checked the Admin Console to verify this change was visible.
=> FISH-9693 Event Filtering Admin Console

appserver/web/web-core/src/main/java/org/apache/catalina/connector/Request.java
Fix Failing `JSTLClient#positiveXPathVariableBindingsTest` TCK Test
None
No
1. build Payara
2. run "mvn clean verify -pl . -pl tags-tck -Ppayara-server-managed -Dpayara.version=7.2024.1.Alpha2-SNAPSHOT > result.log"
3. Should see in the log file:
Finished Test:  PASSED........com/sun/ts/tests/jstl/spec/xml/xmlcore/bindings/JSTLClient.java#positiveXPathVariableBindingsTest
Zulu JDK 21 on Ubuntu 22 with Maven 3.6.3
=> Fish 9628 fix tags tck

nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/LocalServerCommand.java, nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/StartServerHelper.java, nucleus/common/common-util/src/main/java/com/sun/appserv/management/client/prefs/MemoryHashLoginInfoStore.java, nucleus/common/common-util/src/main/java/com/sun/appserv/server/util/Version.java, nucleus/common/common-util/src/main/java/com/sun/common/util/logging/GFLogRecord.java, nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingOutputStream.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/security/store/PasswordAdapter.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/glassfish/ASenvPropertyReader.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/process/ProcessManager.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/process/ProcessState.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/process/ProcessStreamDrainerWorker.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/process/ProcessUtils.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/xml/MiniXmlParser.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/xml/XmlParserHelper.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/util/ProcessExecutor.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/util/io/FileUtils.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/util/io/ServerDirs.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/util/net/NetUtils.java, nucleus/common/common-util/src/main/java/fish/payara/logging/PayaraLogManager.java, nucleus/common/common-util/src/main/java/org/glassfish/admin/payload/PayloadImpl.java, nucleus/common/common-util/src/main/java/org/glassfish/common/util/admin/AsadminInput.java, nucleus/common/common-util/src/main/java/org/glassfish/common/util/admin/ManPageFinder.java, nucleus/common/common-util/src/main/java/org/glassfish/security/common/FileRealmStorageManager.java, nucleus/common/common-util/src/main/java/org/glassfish/security/common/SharedSecureRandomImpl.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java
Various spotbugs fixes
Mainly setting default charset and adding ProcessState instead of boolean.
Also deprecated methods to keep semantic versioning happy 
n/a
Started server
n/a
Ran spotbugs in common-util no more high priority warnings
=> FISH-9854 Fix high priority spotbugs errors in common-util

appserver/tests/payara-samples/repackaged/smallrye-config-repackaged/pom.xml
Replaces https://github.com/payara/Payara/pull/6993 and all similar PRs as I'm tired of seeing them done one by one.
None
None
None
N/A
N/A
None
=> Add smallrye common property

core/pom.xml
Updates the Jakarta EE Concurrency API to 3.1.1
None
None
None
My brain
N/A
None
=> Update Concurrency API to 3.1.1

.github/dependabot.yml
=> FISH-9672 update dependabot filters

core/pom.xml, pom.xml
Upgrades Faces API and Mojarra to 4.1
None
None
Built the server, loaded the admin console - no errors.
[Ran all currently passing TCKs](https://jenkins.payara.fish/view/TCKs/job/JakartaEE-11-TCK/52/) - no new failures.
Windows 11, Maven 3.9.9, Zulu JDK 21.0.4
N/A
None
=> FISH-9606 FISH-9607 Faces and Mojarra 4.1

core/pom.xml
Upgrade Security API and Upgrade Soteria
none
none
Build and Run Payara 7
Zulu JDK 21 on Windows 11 with Maven 3.9.0
none->
none
=> FISH-9141 FISH-9142 Upgrade Security API and Upgrade Soteria

pom.xml
Don't attempt to set response buffer size on a committed response
https://github.com/payara/patched-src-mojarra/pull/26
None
Ran through the full Platform TCK, no failures
Jenkins
N/A
None
=> FISH-10056 Mojarra 4.0.7.payara-p2

pom.xml
Reapplies our patches on top of Mojarra 4.0.9
Builds on top of https://github.com/payara/Payara/pull/7046 so as to hopefully not cause conflicts
Fixes https://github.com/payara/Payara/issues/7025
https://github.com/payara/patched-src-mojarra/pull/25
None
Jenkins
N/A
None
=> FISH-9992 FISH-10056 FISH-10072 Mojarra 4.0.9

appserver/packager/external/jakarta-ee11-shim/pom.xml
Removes dependencies no longer needed, and updates the comments for those that remain.
https://github.com/payara/Payara/pull/7107
https://github.com/payara/Payara/pull/7108
None
Built the server, loaded the admin console, clicked around - no OSGi explosions
Windows 11 , Zulu JDK 21.0.5, Maven 3.9.9
N/A
None
=> FISH-10139 Update EE11 shim

appserver/concurrent/concurrent-impl/pom.xml, appserver/extras/docker-images/tests/pom.xml, appserver/jdbc/jdbc-config/pom.xml, appserver/pom.xml, appserver/tests/fish372-tests/datagrid-tests/pom.xml, appserver/tests/payara-samples/pom.xml, appserver/tests/payara-samples/repackaged/http-matchers-repackaged/pom.xml, appserver/tests/payara-samples/repackaged/jacc-provider-repackaged/pom.xml, appserver/tests/payara-samples/repackaged/pom.xml, appserver/tests/payara-samples/repackaged/smallrye-config-repackaged/pom.xml, appserver/tests/payara-samples/samples/cleanboot/pom.xml, appserver/tests/payara-samples/samples/concurrency/pom.xml, appserver/tests/payara-samples/samples/dynamic-roles/pom.xml, appserver/tests/payara-samples/samples/jacc-per-app/pom.xml, appserver/tests/payara-samples/samples/jacc-per-app/src/test/java/fish/payara/samples/jaccperapp/InstallJaccProviderTest.java, appserver/tests/payara-samples/samples/jakartaee-namespace-transformer/pom.xml, appserver/tests/payara-samples/samples/realm-identity-stores/pom.xml, appserver/tests/payara-samples/samples/use-bundled-jsf-primefaces/pom.xml, appserver/web/weld-integration/pom.xml, core/pom.xml, nucleus/admin/config-api/src/main/java/org/glassfish/config/support/DomainXmlPreParser.java, nucleus/admin/config-api/src/main/java/org/glassfish/config/support/InstanceReaderFilter.java, nucleus/pom.xml, pom.xml
Resyncs with the main branch since https://github.com/payara/Payara/pull/7053
None
¯\\_(ツ)\_/¯
Build the server, loaded the admin console, clicked around a bit.
Windows 11, Zulu JDK 21.0.5, Maven 3.9.9
N/A
None
=> Resync with Main 04/12/2024

core/pom.xml
Upgrade JSON-P API to 2.1.3
None
None
Samples, quickook etc
Zulu JDK 11 on Windows 11 with Maven 3.9.0
=> FISH-6876 : json-p version upgraded

core/pom.xml
Downgrades the core compare version to the previous version - we haven't released a major version yet so we can make breaking changes.
None
None
None
None
None
None
=> Downgrade Core Compare Version to 6.20.0

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/annotation/handlers/ResourceHandler.java
Fixing issue to inject Resources to MDB when configuring using the activation-config-property
This is a fix
To test this you need to create a jms resource and then deploy the application included here on the PR:
Create the following resource on the server:
`
asadmin create-jms-resource --restype jakarta.jms.Queue --property Name=PhysicalQueue jms/TESTQ
`
deploy the following applications:
- MDB application:
[TestEnvvEntries-ejb-payara6.zip](https://github.com/user-attachments/files/18277535/TestEnvvEntries-ejb-payara6.zip)
- Producer application:
[SimpleApp-payara6.zip](https://github.com/user-attachments/files/18277544/SimpleApp-payara6.zip)
after deploying call the following endpoint to produce a message to the queue and activate the MDB to receive the message: …
=> FISH-10228: fixing issue to inject resource added from activation-config-property

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/annotation/handlers/ResourceHandler.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java, core/pom.xml
This is a PR to fix cdi-tck failures
Manual testing with the execution of the cdi-tck using patched weld version recently created to maintain weld probe packages and not affect functionality
linux ubuntu 20.04, JDK 11, maven 3.8.6
=> FISH-10295: adding cdi-tck fixes

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/annotation/handlers/ResourceHandler.java
Ports https://github.com/payara/Payara/pull/7159
=> FISH-10435 Add Null Check (Release Branch)

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/annotation/handlers/ResourceHandler.java
Add a null check on top of https://github.com/payara/Payara/pull/7145 and https://github.com/payara/Payara/pull/7147 to fix a NPE in the EJB TCK.
None
None
Ran through the CDI and ejb30/bb TCK - all green.
Jenkins
N/A
None
=> FISH-10435 Add Null Check

appserver/security/webservices.security/src/main/java/com/sun/enterprise/security/jauth/jaspic/provider/config/SoapAuthenticationService.java
This caused a ClassCastException during the Authentication TCK
Ran authentication tck
=> FISH-10225 Fix Failures in Authentication TCK: SPI SOAP

appserver/extras/docker-images/pom.xml
- Resolves FISH-10467 for Community6
- Resolves FISH-10468 for Community6
- Resolves FISH-10469 for Community6
Built the server and allowed tests to run.
=> FISH-10467 FISH-10468 FISH-10469 Update Docker JDKs

nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/ChangeNodeMasterPasswordCommand.java, nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/CreateLocalInstanceCommand.java, nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/InstallNodeBaseCommand.java, nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/InstallNodeSshCommand.java, nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/LocalInstanceCommand.java, nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/NativeRemoteCommandsBase.java, nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/SynchronizeInstanceCommand.java
fixing code smells for cluster-cli
This is to fix code smells from the following report:  https://jenkins.payara.fish/view/All/job/Spotbugs-Payara6-Build/30/spotbugs/moduleName.-1142719795/
I ran locally the spotbugs validations resulting in no errors from the cluster-cli module:
command used:
`
mvn clean install com.github.spotbugs:spotbugs-maven-plugin:spotbugs -PQuickBuild -DskipTests -Dfindbugs.skip=false -Djavadoc.skip=true -Dsource.skip=true -Dspotbugs.effort=max -Dspotbugs.htmlOutput=true
`
Ubuntu 20.04, zulu 11, maven 3.8.6
=> FISH-10458: fixing code smells for cluster-cli

appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/payara-boot.properties, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java, appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/authorization/PolicyProvider.java, appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/authorization/WebAuthorizationManagerService.java, appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/authorization/cache/PermissionCache.java
How to Define DefaultPolicyFactory for Payara Micro
None
None
Steps:
1. build Payara 7 from [FISH-10156-design-set-of-default-policy-factory](https://github.com/luiseufrasio/Payara/tree/FISH-10156-design-set-of-default-policy-factory]
2. cd .\appserver\extras\payara-micro\payara-micro-distribution
3. Download WAR attached at https://payara.atlassian.net/browse/FISH-10156
4. java -jar payara-micro.jar <PATH_TO_HELLO_PROJECT>hello-micro-7-jdk21-0.1-SNAPSHOT.war
Should start and deploy without issues.
Zulu JDK 21 on Windows 11 with Maven 3.9.0
=> FISH-10138 FISH-10156 design set of default policy factory

pom.xml
Updates the arquillian container to 4.0.alpha2
None
None
None
None
None
None
=> Update Arquillian Container to 4.0.alpha2

pom.xml
- Resolves FISH-7248
Maven version: 3.9.9
Java version: 11.0.25, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.15.153.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"
OpenMQ PR is found [here](https://github.com/payara/patched-src-openmq/pull/29).
=> FISH-7248 Update OpenMQ to 6.5.1

core/pom.xml, nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/SSLConfigurator.java
- Resolves FISH-8459
- Depends on [patched Grizzly 4.0.2](https://github.com/payara/patched-src-grizzly/pull/43)
Built the server, running all tests.
Maven version: 3.9.9
Java version: 11.0.25, vendor: Ubuntu
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.15.153.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"
=> FISH-8459 Update Grizzly to patched 4.0.2

core/pom.xml
=> FISH-10140 Update Security Connectors

core/pom.xml
This PR just bumps the Jakarta EE11 Api version to 11.0.0-M5
=> FISH-10578 FISH-10597 update Payara 7 samples

core/pom.xml
Title
None
None
None
None
N/A
None
=> Remove Duplicate Hibernate Validator Version Property

appserver/appclient/client/acc-standalone/src/main/java/org/glassfish/appclient/client/acc/agent/ACCAgentClassLoader.java, appserver/appclient/client/acc-standalone/src/main/java/org/glassfish/appclient/client/acc/agent/ClassLoaderWrapper.java, appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/CLIBootstrap.java, appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/ACCClassLoader.java, appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/common/ClassPathUtils.java, appserver/tests/quicklook/ejb/mdb/src/test/mdb/MDBTests.java, core/pom.xml, pom.xml
Appclient was incorrectly picking up the classpath and the patched PFL version was causing the "prvdr is null" error when looking up via JNDI.
n/a
Ran Messaging tck
=> FISH-10460 Resolve Appclient Messaging TCK issues

nucleus/admin/template/pom.xml, nucleus/admin/template/src/main/resources/docroot/index.html
Added nofollow and tracking for links. Updated copyright year
=> FISH-10527 added nofollow to index page

appserver/payara-appserver-modules/jmx-monitoring-service/pom.xml, core/pom.xml, nucleus/grizzly/nucleus-grizzly-all/pom.xml, nucleus/security/core/osgi.bundle, pom.xml
Upgraded various dependencies 
https://github.com/payara/patched-src-hk2/pull/35
https://github.com/payara/patched-src-jersey/pull/233
https://github.com/payara/patched-src-gmbal-commons/pull/4
started das
SNAPSHOTS are available for patches (will need to change version)
=> FISH-10575 Upgrade dependencies

core/pom.xml
Updates the security connectors to 3.1.2, pulling in JSON Smart 2.5.2
https://github.com/payara/ecosystem-security-connectors/pull/383
None
Jenkins
Pending...
None
=> FISH-10576 Update Security Connectors to 3.1.2

nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HealthCheckConstants.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HealthCheckHoggingThreadsExecutionOptions.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HealthCheckService.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HealthCheckTask.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HealthCheckWithThresholdExecutionOptions.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HistoricHealthCheckEvent.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HistoricHealthCheckEventStore.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/GetHealthCheckConfiguration.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HealthCheckConfigurer.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HealthCheckServiceLister.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/HealthCheckServiceThresholdConfigurer.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/ListHistoricHealthChecks.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/SetHealthCheckConfiguration.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/SetHealthCheckServiceConfiguration.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/events/PayaraHealthCheckServiceEvents.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/BaseHealthCheck.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/BaseThresholdHealthCheck.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/preliminary/HoggingThreadsHealthCheck.java
- Resolves FISH-10712 for Payara 6.
- Fixes Spotbugs errors for the Healthcheck Core module where appropriate.
- Fixes most non-Spotbugs related warnings in Healthcheck Core.
Built the server and ran all tests.
=> FISH-10712 Spotbugs: Healthcheck Core

core/pom.xml
https://github.com/payara/patched-src-tyrus/pull/8
=> FISH-8933 Upgrade tyrus to 2.1.5.payara-p2

appserver/pom.xml, core/pom.xml
Had to upgrade nimbus in soteria due to osgi errors
https://github.com/payara/patched-src-security-soteria/pull/11
n/a
ran security tck: 
Parsing Failsafe Summary
Completed running 117 tests
Number of tests failed 0
Number of tests with errors 0
Number of tests skipped 0
Parsing summary.txt
Completed running 84 tests
Number of tests failed 0
Number of tests with errors 0
Number of tests skipped 0
=> FISH-10640 Upgrade nimbus-jose-jwt

core/pom.xml, pom.xml
Bump asm.version from 9.7.1 to 9.8
None
None
Quicklook, samples etc
Zulu JDK 21 on Windows 11 with Maven 3.9.9
None
=> FISH-10894 : ASM upgraded to 9.8 in dependencies

appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/cdi/extension/RepositoryImpl.java
Adding multiple entities processing for Jakarta Data interface methods
This is a feature to introduce the multiprocessing of entities for Jakarta Data Repository methods. The following list of methos is considered for this PR:
From CrudRepository
`
@Insert
<S extends T> List<S> insertAll(List<S> entities);
`
`
@Update
<S extends T> List<S> updateAll(List<S> entities);
`
From BasicRepository
`
@Save
<S extends T> List<S> saveAll(List<S> entities);
`
`
@Delete
void deleteAll(List<? extends T> entities);
`
Manual testing using the following reproducer:
[JakartaDataReproducer.zip](https://github.com/user-attachments/files/19900988/JakartaDataReproducer.zip)
To test deploy d eapplication and execute the following endpoints:
to insert a list of entities use:
- …
=> FISH-10953: adding multiple entities processing for crud operations

appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/cdi/extension/RepositoryImpl.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/util/DeleteOperationUtility.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/util/FindOperationUtility.java
Add support for @By annotation on methods deleteById and findById from Repository Interfaces
This is a feature to include more functionality for Jakarta Data implementation. In this case we are including the support of the @By annotation for two methods from the Repository interfaces, the list of methods are the following:
From BasicRepository
`
@Find
Optional<T> findById(@By("id(this)") K id);
`
`
@Delete
void deleteById(@By("id(this)") K id);
`
Manual testing using the following reproducer:
[JakartaDataReproducer.zip](https://github.com/user-attachments/files/19971058/JakartaDataReproducer.zip)
From the reproducer use the following endpoint to create 3 new entities:
- http://localhost:8080/JakartaDataReproducer-1.0-SNAPSHOT/api/hello-world/insertList
then you can use the new endpoint to …
=> FISH-10506: adding By annotation processing for methods deleteById and findById

api/payara-bom/pom.xml, appserver/tests/payara-samples/samples/ejb-http-remoting/pom.xml
Title.
Also fixes them in the bom
None
None
Jenkins
N/A
None
=> FISH-11029 Align `imq` Version with `mq.version`

appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/cdi/extension/DynamicInterfaceDataProducer.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/cdi/extension/JakartaDataExtension.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/cdi/extension/RepositoryImpl.java
Adding implementation for @Insert annotation on custom methods and fix issues to use multiple @Repository annotation on interfaces for an application
This is a feature to improve implementation to support the @Insert annotation on custom methods and also fix issues to use @Repository annotation on multiple interfaces for an application
Manual testing using the following reproducer attached here:
[JakartaDataReproducer.zip](https://github.com/user-attachments/files/20091842/JakartaDataReproducer.zip)
To test the usage of the @Insert annotation on custom method it was needed to add a new repository interface on the project. From the Reproducer you will see the following two repository interfaces:
On the last we are not extending any other interface and we are providing custom methods …
=> FISH-10502: processing insert annotation for custom methods

appserver/pom.xml
A number of properties were missing or were hard coded to old versions - I have tried to fix them.
Not sure we even need this anymore or what this achieves. Also not sure if impl versions are meant to align with the implementation project, or just the exact version of the spec api (e.g. 5.0 vs. 5.0.3)
None
None
None
N/A
N/A
None
=> Fix Missing and Incorrect Spec Versions

appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/cdi/extension/RepositoryImpl.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/util/DataCommonOperationUtility.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/util/InsertAndSaveOperationUtility.java
Adding implementation for @Save and @Update annotations on custom methods 
This is a feature to improve implementation to support the @Save ans @Update annotations on custom methods. This also fix the ticket FISH-10503
Manual testing using the following reproducer attached here:
[JakartaDataReproducer.zip](https://github.com/user-attachments/files/20127805/JakartaDataReproducer.zip)
To test you need to use the PersonRepository class with custom methods to execute the save operation:
also you can test the update operation:
to test use the following endpoints:
fort save
- http://localhost:8080/JakartaDataReproducer-1.0-SNAPSHOT/api/personas/savePersona
- http://localhost:8080/JakartaDataReproducer-1.0-SNAPSHOT/api/personas/savePersonas
- …
=> FISH-10500: resolving @Save annotation on custom methods

appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/cdi/extension/DynamicInterfaceDataProducer.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/cdi/extension/JakartaDataExtension.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/cdi/extension/RepositoryImpl.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/util/DataCommonOperationUtility.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/util/DeleteOperationUtility.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/util/FindOperationUtility.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/util/InsertAndSaveOperationUtility.java, appserver/packager/external/libpam4j/pom.xml, appserver/tests/payara-samples/classloader-data-api/pom.xml, appserver/tests/payara-samples/samples/cleanboot/pom.xml, nucleus/tests/quicklook/pom.xml, pom.xml
Resyncs the feature branch with changes made to `Payara7` to resolve conflicts.
I have scanned through the commits and I believe nothing has been "undone" by the removal of Core.
Also includes a couple of extra bits of cleanup - removing some redundant versions and group ids.
None
¯\\_(ツ)\_/¯
Wiped local maven repo
Rebuilt the server - everything resolved.
Windows 11, Maven 3.9.9, Zulu JDK 21.0.6
N/A
None
=> FISH-11007 Resync Feature Branch with `Payara7`

appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/cdi/extension/DynamicInterfaceDataProducer.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/cdi/extension/EntityMetadata.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/cdi/extension/RepositoryImpl.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/util/DataCommonOperationUtility.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/util/FindOperationUtility.java
Adding Implementation for @Find and @By on custom methods
This is a feature to improve implementation to support @Find and @By annotations on custom methods.
Manual testing using the following reproducer attached here:
[JakartaDataReproducer.zip](https://github.com/user-attachments/files/20234283/JakartaDataReproducer.zip)
To test you need to use PersonRepository using custom methods with Find and By annotations:
the number of parameters represent a valid parameter available on the Entity class
now the following endpoint are available:
http://localhost:8080/JakartaDataReproducer-1.0-SNAPSHOT/api/personas/findAll
http://localhost:8080/JakartaDataReproducer-1.0-SNAPSHOT/api/personas/findById/{id}
http://localhost:8080/JakartaDataReproducer-1.0-SNAPSHOT/api/personas/findByName/{name} …
=> FISH-10505: resolving @Find and @By annotation on custom methods

pom.xml
Upgrades Expressly to 6.0.0
None
None
Jenkins
N/A
None
=> FISH-8815 Expressly 6.0.0

appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/cdi/extension/RepositoryImpl.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/util/FindOperationUtility.java
@OrderBy implementation
None
None
1. http://localhost:8080/JakartaDataReproducer-1.0-SNAPSHOT/api/personas/insertPersonasList
2. http://localhost:8080/JakartaDataReproducer-1.0-SNAPSHOT/api/personas/findAllOrderedByAge
3. http://localhost:8080/JakartaDataReproducer-1.0-SNAPSHOT/api/personas/findAllOrderedByAgeAndLastName
4. http://localhost:8080/JakartaDataReproducer-1.0-SNAPSHOT/api/personas/findAllOrderedByWrongField
Zulu JDK 21 on Windows 11 with Maven 3.9.9
=> Fish 10504 parse order by annotation

.github/ISSUE_TEMPLATE/config.yml
- Fixes #7383
https://payara.org/ references PCF
The forum however
is not named so.
Thus I propose to update not only url but name as well.
=> Update Payara Forum info

appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/cdi/extension/RepositoryImpl.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/util/DeleteOperationUtility.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/util/FindOperationUtility.java
Include usage of @By annotation on delete custom methods with multiple parameters
None
None
1. http://localhost:8080/JakartaDataReproducer-1.0-SNAPSHOT/api/personas/insertPersonasList
2. http://localhost:8080/JakartaDataReproducer-1.0-SNAPSHOT/api/personas/deleteByFirstNameAndLastName/Luis/Neto
3. http://localhost:8080/JakartaDataReproducer-1.0-SNAPSHOT/api/personas/deleteByFirstNameAndLastNameAndReturn/Marcia/Garcia
4. http://localhost:8080/JakartaDataReproducer-1.0-SNAPSHOT/api/personas/findAll
5. Expected Result:
```
[
{
"age": 40,
"firstName": "Alfonso",
"id": 1,
"lastName": "Valdez"
},
{
"age": 20,
"firstName": "Juan",
"id": 2,
"lastName": "Perez"
}
]
```
Zulu JDK 21 on Windows 11 with Maven 3.9.9
=> Fish 11134 at by annotation on delete with multiple params

appserver/connectors/work-management/src/main/java/com/sun/enterprise/connectors/work/context/ConnectorCallbackHandler.java, appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/security/application/EJBSecurityManager.java
This is to fix the last failing tests in the connector-platform-tck
The main change is 
```
s.getPrincipals().add(glassFishCallerPrincipal);
for (String group : caller.getGroups()) {
s.getPrincipals().add(new Group(group));
}
```
n/a
n/a
Ran the connector-platform-tck
Java version: 21.0.5, vendor: Azul Systems, Inc., runtime: /Users/kalinchan/.sdkman/candidates/java/21.0.5-zulu/zulu-21.jdk/Contents/Home
OS name: "mac os x", version: "15.1.1", arch: "aarch64", family: "mac"
n/a
https://jenkins.payara.fish/job/JakartaEE-11-TCK/222/
=> FISH-11200 Add groups to principals

appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/cdi/extension/RepositoryImpl.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/util/DeleteOperationUtility.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/util/QueryOperationUtility.java
Adding Delete operation for @Query annotation
This is a feature to include the Delete operation using @query annotation  
Manual testing using the following reproducer:
[JakartaDataReproducer.zip](https://github.com/user-attachments/files/20765753/JakartaDataReproducer.zip)
to test, first insert some data using the following endpoint:
http://localhost:8080/JakartaDataReproducer-1.0-SNAPSHOT/api/personas/insertPersonasStream
then use any of the following endpoint to delete:
The following will delete all the rows from table person
http://localhost:8080/JakartaDataReproducer-1.0-SNAPSHOT/api/personas/deleteAllFromPerson
http://localhost:8080/JakartaDataReproducer-1.0-SNAPSHOT/api/personas/deleteAllFromPersonVoid
for the following you need to indicate specific attribute to delete the row from …
=> FISH-11217: adding delete operation for @Query annotation

appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/cdi/extension/RepositoryImpl.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/util/QueryOperationUtility.java
This PR will enable sorting when using the `@Query` annotated methods in a Jakarta Data application.
For example:
```
@Query("FROM Person")
Stream<Person> findAllWithSingleSort(Sort<?> sort);
```
or
```
@Query("FROM Person")
Stream<Person> findAllWithSorts(Sort<?>... sorts);
```
n/a
n/a
Firstly, download [JakartaDataReproducer.zip](https://github.com/user-attachments/files/20817680/JakartaDataReproducer.zip)
and build and deploy in Payara
Secondly, insert the people into the repository:
http://localhost:8080/api/personas/insertPersonasStream
Finally sort the data by visiting:
* Single Sort
http://localhost:8080/api/personas/findPersonWithQuerySorted/age?direction=ASC&ignoreCase=FALSE
* Double Sort
http://localhost:8080/api/personas/findPersonWithQuerySorted/age/firstName?direction=ASC&igno …
=> FISH-11234 Add Jakarta Data Sorting for @Query annotated methods

appserver/persistence/jpa-container/src/main/java/org/glassfish/persistence/jpa/JPADeployer.java
Syncing with glassfish
n/a
n/a
mvn clean verify -Ppayara-server-managed -Pjakarta-staging -pl . -pl persistence-platform-tck "-Dit.test=ee.jakarta.tck.persistence.ee.cdi.ServletEMLookupTest"
=> FISH-11462 Fix EMF lookup

pom.xml
See  payara/Payara-Enterprise/pull/2111
=> FISH-11415: testing snapshot version

pom.xml
=> FISH-11415: testing snapshot version to validate headers

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/annotation/impl/AppClientScanner.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/annotation/impl/ModuleScanner.java
Add more scanning for appclient
Resolves the remaining persistence platform tck issues and ejb platform tck issues.
n/a
n/a
https://jenkins.payara.fish/job/JakartaEE-11-TCK/266/
https://jenkins.payara.fish/job/JakartaEE-11-TCK/267/
=> FISH-11446 FISH-10780 Add more scanning for appclient

appserver/extras/docker-images/pom.xml
- Implements FISH-11630
- Updates docker jdk11 version.
- Implements FISH-11632
- Updates docker jdk17 version.
- Implements FISH-11633
- Updates docker jdk21 version.
Built the server and docker images, allowing all tests to run.
Maven home: 3.9.9
Java version: 11.0.27, vendor: Ubuntu
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.15.153.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"
=> FISH-11630 FISH-11632 FISH-11633 Community6

appserver/tests/payara-samples/samples/corba-read-timeout/pom.xml, appserver/tests/payara-samples/samples/corba-read-timeout/src/main/java/fish/payara/samples/corba/read/timeout/TimeoutTestService.java, appserver/tests/payara-samples/samples/corba-read-timeout/src/main/java/fish/payara/samples/corba/read/timeout/TimeoutTestServiceBean.java
Updates the dependencies for Jakarta, and adds required add-opens.
The test remains disabled for now as it takes a long time to execute.
None
None
https://jenkins.payara.fish/blue/organizations/jenkins/Payara%20Community%20PR%20Testing/detail/PR-7539/1/pipeline/78
Jenkins
N/A
None
=> FISH-11517 Fix Corba Test (Payara7)

appserver/tests/payara-samples/samples/pom.xml
Title
None
None
Ran test locally against payara-server-managed profile
Windows 11, Zulu JDK 21.0.7, Maven 3.9.10
N/A
None
=> FISH-11681 Re-enable MicroProfile Rest Client test

pom.xml
Resolves failing sample test regarding jaxrs rolesallowed.
https://github.com/payara/patched-src-security-soteria/pull/12
Ran appserver/tests/payara-samples/samples/jaxrs-rolesallowed-servlet
Java version: 21.0.5, vendor: Azul Systems, Inc., runtime: /Users/kalinchan/.sdkman/candidates/java/21.0.5-zulu/zulu-21.jdk/Contents/Home
OS name: "mac os x", version: "15.5", arch: "aarch64", family: "mac"
=> FISH-10592 Use patched soteria version

appserver/tests/payara-samples/samples/ejb-http-remoting/pom.xml, appserver/tests/payara-samples/samples/ejb-http-remoting/src/test/java/fish/payara/samples/ejbhttp/CustomizedTypesIT.java, appserver/tests/payara-samples/samples/pom.xml
Reenables ejb-http-remoting sample test
n/a
n/a
sample
=> FISH-11513 Reenable ejb-http-remoting sample

appserver/admingui/common/src/main/resources/security/realms/realmAttrs.inc, appserver/extras/docker-images/tests/pom.xml, appserver/pom.xml, appserver/tests/payara-samples/samples/cleanboot/pom.xml, appserver/tests/payara-samples/samples/concurrency/pom.xml, appserver/tests/payara-samples/samples/use-bundled-jsf-primefaces/pom.xml, appserver/tests/quicklook/pom.xml, appserver/web/weld-integration/src/main/java/org/glassfish/weld/GlassFishWeldProvider.java, nucleus/pom.xml, pom.xml
Syncs applicable changes from the main branch since https://github.com/payara/Payara/pull/7454
N/A
None
Built and started the server, poked the admin console - no explosions
Windows 11, Maven 3.9.10, Zulu JDK 21.0.7
N/A
None
=> FISH-11689 Main Sync 2025/07/28

appserver/tests/payara-samples/samples/ejb-http-remoting/src/test/java/fish/payara/samples/ejbhttp/CustomizedTypesIT.java
=> FISH-11513 Reenable ignored tests

appserver/web/web-core/src/main/java/org/apache/catalina/loader/WebappLoader.java, appserver/web/web-naming/src/main/java/org/apache/naming/resources/WebDirContext.java
- Fixes FISH-10821
- Created the docker image as described in the reproducer, inspected the logs for errors, viewed the URLs.
- Ran this build of Payara against the Servlet TCK.
Payara 6 Micro docker environment
Maven home: 3.9.9
Java version: 11.0.28, vendor: Ubuntu
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.15.153.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"
=> FISH-10821 Alternate Document Root

appserver/data/data-core/src/main/java/fish/payara/data/core/cdi/extension/PageImpl.java, appserver/data/data-core/src/main/java/fish/payara/data/core/cdi/extension/RepositoryImpl.java, appserver/data/data-core/src/main/java/fish/payara/data/core/util/QueryByNameOperationUtility.java
Fix NullPointerExceptions from Jakarta Data TCK 
This is a fix for all the NullPointerException references from the results from Jakarta Data TCK
Manual testing executing the Jakarta Data TCK:
Current results don't show any NullPointerException reference
Ubunto 20.04, azul jdk 21, maven 3.9.9
=> Fish 11807 fixing nullpointerexception from tck

appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/ClusteredCDIEventBusImpl.java, appserver/pom.xml, appserver/tests/payara-samples/pom.xml, appserver/transaction/jts/src/main/java/com/sun/enterprise/transaction/jts/JavaEETransactionManagerJTSDelegate.java, appserver/transaction/jts/src/main/java/com/sun/jts/jta/TransactionManagerImpl.java, appserver/transaction/jts/src/main/java/com/sun/jts/jta/TransactionServiceProperties.java, appserver/web/web-core/src/main/java/org/apache/catalina/loader/WebappLoader.java, appserver/web/web-naming/src/main/java/org/apache/naming/resources/WebDirContext.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/event/EventTypes.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/AppServerStartup.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/CollectLogFiles.java, nucleus/pom.xml, pom.xml
Syncs applicable changes from the main branch since https://github.com/payara/Payara/pull/7563
N/A
None
Built and started the server, poked the admin console - no explosions
Windows 11, Maven 3.9.11, Zulu JDK 21.0.8
N/A
None
=> FISH-11928 Main Sync 2025/08/15

appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/security/application/EJBSecurityManager.java, appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/authorization/WebAuthorizationManagerService.java
The current request is not available in the servlet context
n/a
n/a
https://jenkins.payara.fish/view/TCKs/job/JakartaEE-11-TCK/308/
Java EE 7 Samples
=> FISH-11672 Add HttpServletRequest to EJB context

appserver/batch/glassfish-batch-connector/src/main/java/org/glassfish/batch/spi/impl/BatchRuntimeConfiguration.java, appserver/batch/glassfish-batch-connector/src/main/java/org/glassfish/batch/spi/impl/BatchRuntimeHelper.java
Fixes instances without batch runtime configuration when at least 1 instance has a batch runtime configuration saved.
None
None
Run these asadmin commands, with the defect `inst2` will fail to start after the `set-batch-runtime-configuration` command:
```
start-domain
create-instance --node=localhost-domain1 inst1
create-instance --node=localhost-domain1 inst2
create-instance --node=localhost-domain1 inst3
create-instance --node=localhost-domain1 inst4
create-deployment-group dp1
add-instance-to-deployment-group --instance=inst1 --deploymentGroup=dp1 
add-instance-to-deployment-group --instance=inst2 --deploymentGroup=dp1 
add-instance-to-deployment-group --instance=inst3 --deploymentGroup=dp1 
add-instance-to-deployment-group --instance=inst4 --deploymentGroup=dp1 
start-deployment-group …
```
=> FISH-9654 Make Batch Runtime Configuration optional
