payara/Payara

appserver/web/gf-web-connector/osgi.bundle, appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionScopedCDIUtil.java
Now checking for no-invocation context run during testing
Not sure if this affects real-world applications, but I think it may
Fixes test issue with #5010 
None
Was caused by the following throwing WARNINGS, but not errors, thus not failing the build
```
testcase name="testafterBeanDiscovery" classname="org.glassfish.cdi.transaction.TransactionScopedContextExtensionTest" time="0.538">
<error message="No Current Invocation present" type="java.lang.IllegalStateException">java.lang.IllegalStateException: No Current Invocation present at org.glassfish.cdi.transaction.TransactionScopedContextExtensionTest.testafterBeanDiscovery(TransactionScopedContextExtensionTest.java:76) </error>
<system-err>
```
tests now pass without warning
jdk 8, mac
None
Relates to FISH-790
=> FISH-873 TransactionScopedCDIUtil Context Util - can now be run without a context

appserver/extras/docker-images/pom.xml, appserver/extras/docker-images/tests/pom.xml
Delete Payara artifacts.
```
rm -rf ~/.m2/repository/fish
docker image rm payara/server-web:5.2020.8-SNAPSHOT-jdk11
docker image rm payara/server-web:5.2020.8-SNAPSHOT
```
Build all artifacts (but don't run Payara Samples)
- to my surprise it passed even with TC8
```
mvn clean install -PQuickBuild,BuildExtras,BuildDockerImages -amd -TC8; # time: 5:53
```
Without "Extras" and payara-web
```
rm -rf ~/.m2/repository/fish/payara/distributions/payara-web* # to be sure that it compiles even without it
mvn clean install -PQuickBuild,BuildDockerImages -amd -TC8; # time: 4:21
```
Build zip files and docker images
-  TC8 - :eyes: Wow!
```
mvn clean install -pl :extras,:docker-images -PQuickBuild,BuildExtras,BuildDockerImages -amd # time: 6:37
mvn clean install -pl :extras,:docker-images …
```
=> QACI-592 Fixed build consistency when using QuickBuild

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLoaderService.java
Applications are loaded to instances they are not assigned to. See Jira for reproducer. The effect of this can be seen in the node logs
Links to https://github.com/payara/Payara-Enterprise/pull/258
No new tests
+ Quicklook
+ Payara Samples
+ Java EE7 Samples
+ Java EE8 Samples
+ Payara Microprofile TCKs Runner
+ Cargo Tracker
Internal Jenkins http://192.168.1.120:8080/job/BuildAndTestInParallel/1606/ (results ephemeral, kept 14 days)
n/a
=> FISH-505 prevent loading apps to instance app not assigned to

api/payara-api/src/main/java/fish/payara/notification/requesttracing/RequestTraceSpan.java, api/payara-api/src/main/java/fish/payara/notification/requesttracing/RequestTraceSpanContext.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java, appserver/ejb/ejb-opentracing/src/main/java/fish/payara/ejb/opentracing/OpenTracingIiopServerInterceptor.java, appserver/monitoring-console/core/src/main/java/fish/payara/monitoring/runtime/MonitoringConsoleRuntimeImpl.java, appserver/payara-appserver-modules/jaxrs-client-tracing/src/main/java/fish/payara/requesttracing/jaxrs/client/JaxrsClientRequestTracingFilter.java, appserver/payara-appserver-modules/microprofile/opentracing-jaxws/src/main/java/fish/payara/opentracing/jaxws/JaxwsContainerRequestTracingFilter.java, appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/cdi/TracedInterceptor.java, appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/jaxrs/OpenTracingRequestEventListener.java, nucleus/payara-modules/opentracing-adapter/src/main/java/fish/payara/opentracing/OpenTracingScope.java, nucleus/payara-modules/opentracing-adapter/src/main/java/fish/payara/opentracing/ScopeManager.java, nucleus/payara-modules/opentracing-adapter/src/main/java/fish/payara/opentracing/span/Span.java, nucleus/payara-modules/opentracing-adapter/src/main/java/fish/payara/opentracing/tracer/Tracer.java, nucleus/payara-modules/requesttracing-core/pom.xml, nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/RequestTracingService.java, pom.xml
This is a feature PR to upgrade the MicroProfile OpenTracing 2.0 and OpenTraing API 0.33.
OpenTraing API 0.33 includes breaking changes and deprecated methods are removed:
- `ScopeManager.active()`
- `ScopeManager.activate(Span, boolean)`
- `Scope.span()`
- `SpanBuilder.startActive()`
- `Tracer.startManual()`
OpenTracing TCK 2.0-RC2
https://github.com/payara/patched-src-microprofile-opentracing/pull/1
https://github.com/payara/MicroProfile-TCK-Runners/pull/128
https://github.com/payara/Payara_PatchedProjects/pull/347
=> FISH-664 MP OpenTracing 2.0-RC2 Upgrade

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/logger/FileLoggerHandler.java, nucleus/common/common-util/src/main/java/com/sun/common/util/logging/GFLogRecord.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/GFFileHandler.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/SyslogHandler.java
force toString() during the same thread as the logging happens so objects
don't get passed around different threads in logging and have a chance to get
out of sync and be inconsistent
Pragmatic & minimalist fix to remove race conditions in log records causing stale state to be printed in log message
None
Existing tests
Jenkins
This is a simplest fix for the issue, not touching anything that doesn't directly relate
Choose "hide whitespace changes" from GitHub setup to make the review easier
=> CUSTOM-55 possibly stale log records are propagated

nucleus/deployment/common/src/main/java/fish/payara/deployment/util/GAVConvertor.java
Added ability to deploy GAV from local repository.
***Example:***
`java -jar payara-micro.jar --deployFromGAV org.example:someapp:1.0 --additionalRepository file:///c:/Users/alex/.m2/repository`
Zulu JDK 8, Windows 10 Pro
=> FISH-886 Deploy GAV from local repository + some code cleanup

appserver/extras/embedded/all/pom.xml
- JaxwsContainerRequestTracing is now discovered by ServiceLocator
Fixes packaging of embedded Payara. Any deployed webservice could not handle requests, because at least one implementation of opentracing is required.
Manual run of integration tests with embedded Payara.
=> #4953 package jaxws opentracing to embedded Payara

appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jwt/JwtTokenParser.java
This PR addresses a bug I found while working on a MP JWT feature. The JWT claims `iat` and `exp` are stored as `int` for verification. Both claims hold a timestamp as the number of seconds since epoch. The code is susceptible to the year 2038 integer overflow problem; aka, the epochalypse. Values after January 19, 2038 3:14:07 GMT will cause an integer overflow. This can cause valid tokens to be treated as expired.
This will eventually cause a security problem once we reach 2038/01/19. Any tokens that expired before 2038/01/19 can be accepted once again. This happens because the current time overflows and becomes negative but all `exp` claims before this day will not overflow and will remain positive. It will appear as though the old tokens have not expired yet.
This PR changes the …
=> MP JWT uses long datatype for exp and iat verification to prevent overflow in 2038

appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/FaultToleranceServiceConfiguration.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/cdi/FaultToleranceInterceptor.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/policy/FaultTolerancePolicy.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/service/FaultToleranceMethodContextImpl.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/service/FaultToleranceServiceImpl.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/service/MethodKey.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/test/java/fish/payara/microprofile/faulttolerance/policy/AbstractBulkheadTest.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/test/java/fish/payara/microprofile/faulttolerance/policy/AbstractMetricTest.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/test/java/fish/payara/microprofile/faulttolerance/policy/BulkheadLifecycleTckTest.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/test/java/fish/payara/microprofile/faulttolerance/policy/CircuitBreakerBasicTest.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/test/java/fish/payara/microprofile/faulttolerance/policy/FaultToleranceStressTest.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/test/java/fish/payara/microprofile/faulttolerance/service/FaultToleranceMethodContextStub.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/test/java/fish/payara/microprofile/faulttolerance/service/FaultToleranceServiceStub.java
Small refactorings in Fault Tolerance implementation to make all TCK test pass.
The core change was to return back to standard managed thread pools. These pools propagate application context correctly so the issue with having incorrect application name on invocation stack no longer applies.
However the need for application name was greatly reduced in next optimization, where actual class and method reference are used as keys into state map, further stabilizing the tests.
Also discovered and fixed is memory leak in `FaultTolerancePolicy`'s cache where entires were not deleted upon undeployment, which was troublesome especially for run of TCK. With these two changes together in became apparent that cleanup of method data can be removed, as data has relatively small footprint and keeping …
=> FISH-659: Fault Tolerance 3.0 full pass

appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/service/FaultToleranceServiceImpl.java
Custom thread pools were swapped back to managed executors in the FT
implementation, so the shutdown methods would fail as the executors are
managed so don't require shutdown.
For reproducing the current error, shutdown the server and check the logs.
=> FISH-659 Fix MP FT executor shutdown

appserver/admingui/jca/src/main/java/org/glassfish/jca/admingui/handlers/ConnectorsHandlers.java, appserver/admingui/jca/src/main/resources/resourceAdapterConfigAttr.inc, appserver/orb/orb-connector/src/main/java/org/glassfish/enterprise/iiop/util/S1ASThreadPoolManager.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/commands/ListThreadpools.java, nucleus/core/kernel/src/main/manpages/com/sun/enterprise/v3/admin/commands/list-threadpools.1
Community PR of Jonathan's https://github.com/payara/Payara-Enterprise/pull/264
Created a new instance with a new config, then created a thread pool in that instance's config. Create a resource adapter config and check that the name of the new thread pool is in the drop down menu for Thread Pool IDs.
Zulu JDK 1.8_272 on Ubuntu 20.04 with Maven 3.6.3
Updated man page in this PR for list-threadpools command
=> FISH-744 Resource Adapter Config lists thread pools from all instances in the admin console

pom.xml
Title.
The scripts in OpenMQ were running into issues on Linux due to Windows line endings.
PatchedProjects PR: https://github.com/payara/Payara_PatchedProjects/pull/355
=> FISH-642 Rebuild OpenMQ on Linux to fix line endings

appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/hashicorp/HashiCorpSecretsConfigSource.java
(No access to or installation of Vault needed to reproduce problem)
```
./asadmin start-domain
./asadmin create-password-alias HASHICORP_VAULT_TOKEN
(you can enter 12345 as password)
./asadmin set-hashicorp-config-source-configuration --enabled true --dynamic true --api-version 2 --vault-address http://127.0.0.1:8200 --secrets-engine-path secret --secrets-path hello
./asadmin deploy clusterjsp.war
```
Before PR deployment fails, afterwards deployment succeeds.
=> FISH-876 Failure to connect to hashicorp vault no longer blocks deployment

appserver/tests/payara-samples/samples/http/pom.xml, appserver/tests/payara-samples/samples/http/src/test/java/fish/payara/samples/TLSSupportTest.java, appserver/tests/payara-samples/samples/pom.xml
A simple test to confirm TLS support by checking available protocols for newly created sockets, for TLS versions 1 to 1.3.
This test fails, as TLSv1.3 is not listed as a  'supported' protocol for sockets, this has been confirmed as a genuine failure. Spawned FISH-462.
~~Couldn't test on JDK11 due to QACI-451.~~
Samples remote and managed on JDK8
JDK zulu 1.8.0_265 Remote & Managed, 5.2020.5-SNAPSHOT
JDK zulu 1.8.0_262 Remote & Managed, 5.2020.5-SNAPSHOT
JDK zulu 1.8.0_152 (Skipped test, as expected), 5.2020.5-SNAPSHOT
The test will be skipped if TLSv1.3 is not supported for the JDK version it is being run on.
I timeboxed this test to push it out with this test case, but I was writing another test case which can be seen in AlanRoth/QACI-377-extra branch, however encountered a problem with …
=> QACI-377 Added TLS 1 to 1.3 support test

nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/JarFileUtils.java
Changes the closeCachedJarFiles behavior to only close JarFile instances associated with a "file:" URL.  All others are removed from the cache so they can be closed when no longer in use.  The assumption is that others might be owned by a URLClassLoader, but "file:" is most likely owned by the process requesting the close.  This should allow redeployment of the vast majority of applications on Windows without having to worry about file locks, while letting applications which need unusual Jar file URLs to work.
fixes: https://github.com/payara/Payara/issues/4414
None provided
Tested that it fixes the issue using the application which showed it.
None
OS: RedHat Linux 7
JDK: OpenJDK 8.0.201
Maven: 3.6.2
N/A
N/A
=> [FISH-1017] Payara can close JarFile instances used by current URLClassLoaders

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/UberJarCreator.java
Remote artifact deployed with a temporary name app...tmp. But, e.g., for MDBs we need to specify resource adapter name activation property and we get an deployment error. This fix changes deploy name to `artifactId-version`.
When creating an uber jar a GAV artifacts are added with a context name, not a filename. When executes this uber jar an exception throws if context name length less than or equal 4. In other case we have an incomplete application name (context - last four chars). This fix writes GAV artifacts with their filenames and adds their contexts to the contexts.properties during uber jar creation.
=> Add appropriate application name to GAV deployments / FISH-1015

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/ClusterHandler.java, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ListInstancesCommand.java
=> [FISH-759] sort instances in admin console

appserver/payara-appserver-modules/microprofile/config/src/main/java/fish/payara/microprofile/config/activation/ConfigDeployer.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/activation/MetricsSniffer.java
Fixes #5080
Obviously javadoc says there may be null returned.
```
/**
* Returns the meta data for the given key
*
* @param metaDataKey key of the meta date.
* @param metadataType type of the meta date.
* @return instance of T or null
*/
<T> T getTransientAppMetaData(String metaDataKey, Class<T> metadataType);
```
=> 5080 Payara logback libs produce NPE / FISH-1007

nucleus/payara-modules/opentracing-adapter/src/main/java/fish/payara/opentracing/OpenTracingService.java, nucleus/payara-modules/opentracing-adapter/src/main/java/fish/payara/opentracing/tracer/Tracer.java
There were certain scenarios where it was possible for the span propagated from a remote EJB client to not get picked up by the server-side Tracer. This was traced back to the getTracer method - the server-side tracer wasn't using the scope manager of the RMI tracer. There was essentially a race condition present in the creation of Tracers - everything worked _as long as_ the RMI tracer was initialised first _and_ had an active span.
I've changed it so that we now use a shared scope manager across all tracers. The scope manager is focussed on maintaining the thread local active scope, so I don't _think_ this will cause any issues with span scopes bleeding across the different tracers when they shouldn't be.
None
None.
Turned on Request Tracing, and configured it to …
=> FISH-990 OpenTracing Active Span is NULL when retrieved in EJB tracer on remote execution

appserver/batch/glassfish-batch-commands/src/main/java/fish/payara/batch/CleanJbatchRepository.java, appserver/batch/glassfish-batch-commands/src/main/manpages/fish/payara/batch/clean-jbatch-repository.1, appserver/batch/glassfish-batch-commands/src/main/manpages/fish/payara/batch/purge-jbatch-repository.1
This is a feature.
Using example app which performs an execution, ran command then went to the admin console server -> batch -> executions and checked that they were deleted.
Added man pages to PR.
See also `purge-jbatch-repository` command which already exists to delete all executions.
This is the community PR for payara/payara-enterprise#272
=> FISH-108 Add command to clean Jbatch repository

appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/util/ConnectorTimerProxy.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EjbContainerUtilImpl.java, appserver/tests/payara-samples/classloader-data-api/src/main/java/fish/payara/samples/classloaderdata/InstanceResource.java, pom.xml
Continuation of #5081 
Better ClassLoader leak test
=> [FISH-1018] found more leaks and more reliable leak test

appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/aws/AWSSecretsConfigSource.java, appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/azure/AzureSecretsConfigSource.java, appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/dynamodb/DynamoDBConfigSource.java, appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/gcp/GCPSecretsConfigSource.java, appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/hashicorp/HashiCorpSecretsConfigSource.java, appserver/payara-appserver-modules/microprofile/config-extensions/src/test/java/fish/payara/microprofile/config/extensions/hashicorp/HashiCorpSecretsConfigSourceTest.java
New test add at https://github.com/payara/Payara/compare/master...Cousjava:FISH-877-mp-config-ordinals-cloud?expand=1#diff-04fc586ba2c85eee6bd5376c25be567f24a810aba8d3b61b686ddb8064cfe54fR122
Using the reproducer from FISH-892, also added a config property with the same key but a different value to the domain config properties. Used curl on the endpoint to get the cloud value. Changed the ordinal of cloud config source to be less then that of domain and ran curl again, this time got the value from the domain config.
=> FISH-877 Add config ordinal to cloud config sources

appserver/extras/payara-micro/payara-micro-distribution/build.xml, appserver/packager/glassfish-nucleus/pom.xml
Removes the _production_ domain template from the Community distributions.
None
Nope
Built the server and checked that the template is no longer present.
Started Micro with https enabled and an app deployed, poking on HTTPS port worked and no **_new_** expired certs in log (though there are some)
Windows 10, JDK 8
Nada
Zilch
=> FISH-753 Remove production domain template from Payara Server Community distributions

appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/admin/cli/MigrateTimers.java, appserver/ejb/ejb-container/src/main/resources/org/glassfish/ejb/admin/cli/LocalStrings.properties, appserver/ejb/ejb-full-container/src/main/java/org/glassfish/ejb/persistent/timer/PersistentEJBTimerService.java, appserver/payara-appserver-modules/hazelcast-ejb-timer/pom.xml, appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/EjbTimerEvent.java, appserver/payara-appserver-modules/hazelcast-ejb-timer/src/main/java/fish/payara/ejb/timer/hazelcast/HazelcastTimerStore.java
This is a new feature or improvement.
This change allows you to migrate EJB timers from live instances, rather than only down ones. This is done using the `migrate-timers` command.
None
None
**Database**
From a clean domain:
* Configure __TimerPool JDBC Connection Pool to point to a non-relative location by editing the sole existing property to something like _C:\Users\pandr\Downloads\Test_ rather than _${com.sun.aas.instanceRoot}/lib/databases/ejb-timer_
* Create a Deployment Group with two instances and start them
* Deploy test app to the deployment group: https://github.com/payara/patched-src-javaee7-samples/tree/master/ejb/timer
* Check the instance logs to ensure the EJB Timer service started and that timers are executing
* Run the following command to migrate timers, using your own …
=> FISH-105 Migrate EJB Timers from Live Instances

appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/JwtPublicKeyStore.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/SignedJWTIdentityStore.java
This is a PR for feature request https://github.com/payara/Payara/issues/5027. With this change, the loaded JWT public key is cached for subsequent requests to use. While the PR is aimed at helping with remote public keys, it handles key caching from any source the same.
I original wrote the feature request with HTTP cache headers in mind but since it is much simpler to have a default cache TTL configurable by `payara-mp-jwt.properties`, I thought that would be a better place to start. A new configuration `publicKey.cache.ttl` sets the TTL in seconds and defaults to 5 minutes (probably want to discuss what the default could be). If set to 0 or less, the cache is disabled and public key loads are no longer synchronized.
Last, I omitted a feature I entertained in …
=> FISH-868 JWT public key is cached for a configurable amount of time.

nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/DirConfigSource.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/MicroprofileConfigConfiguration.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/test/java/fish/payara/nucleus/microprofile/config/source/DirConfigSourceTest.java
During QA after merging #5007, @lprimak stumbled over a SEVERE
log message during deploys, triggered by the non-existing directory
of DirConfigSource. The directory config value has had a default
before, also the docs say otherwise.
The level issue has been fixed by checking only default config value
being used, resulting in an INFO level message. The logic has been
refactored not to use an exception, but Optional API.
None.
Batteries included.
Usual unit tests.
- AdoptOpenJDK (build 11.0.9+11)
- Linux, Fedora 33
- Maven 3.6.3
- Docs will be fixed to include the formerly hidden default value, see https://github.com/payara/Payara-Community-Documentation/pull/126
=> FISH-788: DirConfigSource should not log severe messages if unused.

pom.xml
Appears to cause the JAXR TCK to fail
Depends on https://github.com/payara/Payara_PatchedProjects/pull/364 and https://github.com/payara/patched-src-grizzly/pull/29
=> FISH-464 Revert.

pom.xml
This reverts commit 7bae1622848056794003d0531cdd6b78b9b971c6, reversing
changes made to a28054a955e6ac6facfdb31b5cc5bd996acf41bb.
Initially thought to cause TCK failures but discovered to have been a false positive (literally)
=> [FISH-464] - Revert "Merge pull request #5121 from Pandrex247/FISH-464-Revert"

nucleus/common/internal-api/src/main/java/fish/payara/internal/notification/admin/BaseSetNotifierConfigurationCommand.java
You would get an NPE when configuring notifiers for anything other than the server-config, due to the default config tags not being present in the default domain.xml. This change makes it so default config tags will be created if not already present.
None
Nope
Start a fresh domain:
* Attempt to configure a notifier against the server config: .\appserver\distributions\payara\target\stage\payara5\bin\asadmin set-cdieventbus-notifier-configuration --enabled false --target default-config
* Attempt to configure a notifier against the default config: .\appserver\distributions\payara\target\stage\payara5\bin\asadmin set-cdieventbus-notifier-configuration --enabled false --target default-config
* Attempt to configure a notifier against a standalone instance using Admin Console
User should receive …
=> FISH-1061 Fix NullPointer when Configuring a Notifier against a non-DAS Instance or Config

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/activation/OpenApiSniffer.java
OpenAPI applications without @Path annotations weren't being picked up.
For example, apps with an @OpenAPIDefinition and no actual endpoints.
This commit adds extra sniffer searches to expand this selection.
=> FISH-760 Expand OpenAPI sniffer criteria

appserver/admingui/microprofile-console-plugin/src/main/resources/fish/payara/admingui/microprofile/Strings.properties, appserver/admingui/microprofile-console-plugin/src/main/resources/microprofile/specs/faultToleranceConfiguration.jsf, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/FaultToleranceServiceConfiguration.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/admin/GetFaultToleranceConfigurationCommand.java, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/admin/SetFaultToleranceConfigurationCommand.java
The Fault Tolerance configuration was a bit of a mess, with the correct
configuration parameters not being used, and the incorrect ones being
reported.
This commit makes the managed executor names the configurable options,
and removes the dead configuration options.
As an added bonus, the set command now validates the executor names.
This should work as expected in the admin console and from the command
line.
Docs: https://github.com/payara/Payara-Community-Documentation/pull/135
=> FISH-1069 Rationalise Fault Tolerance Configuration

nucleus/admin/config-api/src/main/java/org/glassfish/config/support/TranslatedConfigView.java
Closes #5126
Microprofile Config based variable substitution in TranslatedConfigView:
1. When no value can be found and no default has been given, a warning
should be printed, so we have a useful error message. Important e. g.
to track causes when DB connections fail, etc.
2. When a value has been found, it might be the wrong one due to wrong
ordinal config, human mistake, etc etc. Enabling debugging
with the TranslatedConfigView will reveal the origin of a value.
(Thx, MicroProfile Config API 2.0!!!)
This is a demo to outline how this could be done. Might need polishing.
None yet.
None yet, except for the test cases already present.
AdoptJDK 11.0.9, Maven 3.6, Linux (Fedora 33)
None yet.
None so far.
=> feature(config-api): Make MPCONFIG in TranslatedConfigView debugable / FISH-1079

appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/monitoring/JdbcStatsProvider.java
This is a bug fix to fix NullPointerException when trying to get slow SQL queries for monitoring.
=> FISH-1084 NullPointerException when getting monitoring data for JDBC

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/DeploymentFileValidator.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/DeploymentGAVValidator.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/RUNTIME_OPTION.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/RuntimeOptions.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/DeploymentComparator.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/UberJarCreator.java, nucleus/deployment/common/src/main/java/fish/payara/deployment/util/GAVConvertor.java
Now Payara Micro  boot-time deployment has some limitations:
* it is impossible to deploy RAR remotely from maven and application using it locally with --deploy option - we get an deployment error
* context root option, when present, is assigned to a first deploy archive, not to a first appropriate
In this patch I tried fix this:
* deploy, deployFromGAV and deploymentdir options proceed in order as they encountered
* contextroot is assigned to a first *appropriate* archive (WAR)
* when a particular deploy archive defined more than once, then archive deployed at the first occurrence but with the last defined value
Windows 10 Pro, Azul Zulu OpenJDK 1.8.0_282
=> Make Micro boot-time deployment more reliable / FISH-1094

appserver/web/war-util/src/main/java/org/glassfish/web/loader/NonCachedJarStreamHandler.java, appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java, appserver/web/web-core/src/main/java/org/apache/catalina/loader/StandardClassLoader.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/BeanDeploymentArchiveImpl.java
Resource Loading - URL()s no longer produce cached JAR files,
thus fixing race conditions when JAR files are closed from outside the thread
During parallel resource loading from multiple apps, JARs are closed due to improper cachine.
Fixes a bug reported for GlassFish: https://github.com/eclipse-ee4j/glassfish/issues/22552
Parallel-tested MP-TCK
=> [FISH-1178] Resource Loading - new URLs no longer produce cached JAR files

appserver/tests/payara-samples/asadmin/src/test/java/fish/payara/samples/asadmin/SetHealthCheckConfigurationTest.java, appserver/tests/payara-samples/asadmin/src/test/java/fish/payara/samples/asadmin/SetHealthCheckNotifierConfigurationTest.java, nucleus/payara-modules/asadmin-audit/src/main/java/fish/payara/audit/admin/SetAdminAuditConfiguration.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/admin/SetHealthCheckConfiguration.java
They don't need to be mandatory. If mandatory it means you always need to have them present, even if not configuring the enabled status.
It also makes chaining to this command from another command a pain, since you'd have to pass it the current config setting.
Also adds a null check for `auditLevel`, since it didn't have one and needed it. 
None
None.
Ran the commands:
* `asadmin set-healthcheck-configuration` - `SUCCESS`
*  `asadmin get-healthcheck-configuration` - default settings
* `asadmin set-healthcheck-configuration --enabled true --dynamic true` - `SUCCESS`
*  `asadmin get-healthcheck-configuration` - changed settings
* `asadmin set-admin-audit-configuration` - `SUCCESS`
*  `asadmin get-admin-audit-configuration` - default settings
* `asadmin set-admin-audit-configuration …
=> FISH-1171 FISH-1172 Make Enabled Parameter of set-admin-audit-configuration and set-healthcheck-configuration Commands Optional

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/RUNTIME_OPTION.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/DynamicReloadService.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/DynamicReloader.java
This is a feature PR to pass `hotDeploy` runtime option on Payara Micro startup to save deployment state and read `.reload` file to fetch modified files and metadata details.
Manually Tested with VSCode hotDeploy integration feature
VSCode 1.53.2, Windows 10, JDK 8
=> FISH-1076 hotDeploy runtime option support in Payara Micro

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
This is bug fix.
Payara Micro failed to start with NPE when --hotDeploy option is absent.
Manual testing
Win 10 Pro, Payara Micro current, Zulu 1.8.0_282
=> Fix NPE when hotDeploy option is absent in Payara Micro

appserver/extras/docker-images/server-node/src/main/docker/bin/entrypoint.sh
Fix value for DOCKER_CONTAINER_ID within entrypoint.sh of server-node image so it has meaningful value within k8s.
Tested on Docker Desktop on Mac with k8s  1.19
=> FISH-1186: Support server-node on k8s

appserver/admin/backup/src/main/java/com/sun/enterprise/backup/BackupManager.java
If an error was encountered creating a domain backup (e.g. insufficient permissions on a file), the backup would not stop, and you'd end up with a corrupt backup zip.
This fixes this by cancelling out the backup and deleting the backup.
None
None
None
* Attempt backup: `asadmin backup-domain`
* Command should succeed with a backup created: `ls payara5/glassfish/domains/domain1/backups`
* Change owner of login.conf file to root: `sudo chown root payara5/glassfish/domains/domain1/config/login.conf`
* Attempt backup: `asadmin backup-domain`
* Command should fail, useful error message, and no corrupt backup created: `ls payara5/glassfish/domains/domain1/backups`
WSL OpenSUSE JDK 8
N/A
None
=> FISH-514 Fix Inconsistent behaviour when a domain backup is created

appserver/batch/glassfish-batch-commands/src/main/java/fish/payara/batch/CleanJbatchRepository.java
- Make --days parameter optional for easier usage
- Show nice message when database is not accessible.
Testing on supported databases.
Zulu 8.52.0.23-CA-macosx (build 1.8.0_282-b08) on Mac 11.2.2 with Maven 3.6.3
Continuation of https://github.com/payara/Payara/pull/5158
=> FISH-1064 : Asadmin to clear out old job executions of JBatch in all supported databases (cont)

nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigProviderResolverImpl.java
`asadmin start-domain --debug --verbose production`
Before PR: NPE appears in log (does not prevent domain starting)
After: No errors or warning appear in log at startup.
- Quicklook
This is the community PR for https://github.com/payara/Payara-Enterprise/pull/338
=> FISH-1173 NPE starting prod domain in ConfigProviderResolver

pom.xml
This is a version upgrade PR for Payara Eclipse Transformer v0.2.3 which includes following fix:
[[FISH-1193](https://github.com/payara/transformer/pull/7)] Jakarta EE 9: jakarta.servlet.http.* imports ignored by Payara transformer in JSP files
[[FISH-1192](https://github.com/payara/transformer/pull/9)] Jakarta EE 9: Duplicate entry ZipException is thrown on transforming web application servlet_plu_singlethreadmodel_web.war 
[[FISH-1194](https://github.com/payara/transformer/pull/10)] Jakarta EE 9: IllegalArgumentException jakarta.mail.Session is not an allowed property value type
[[FISH-1196](https://github.com/payara/transformer/pull/11)] Jakarta EE 9: Servlet Constant value namespace transformation ignored e.g jakarta.servlet.context.tempdir …
=> Upgrade Payara Eclipse Transformer to v0.2.3

pom.xml
Feature.
Port from Payara 4.
> Payara Server 4 introduces a breaking change in EL (at least when it's used in a JSP). An EL expression in JSP which is evaluated correctly on GF 3 might confuse Payara Server 4 and 5 to thing that the expression contains a reference to an imported class and attempts to load that class. This ends in ClassNotFoundException. This happens every time the expression is evaluated. If there's a higher load on the server and the EL needs to be evaluated very often, the Classloader spends a significant amount of time searching for the class. Classloader puts a lock on the class and all the other threads that are evaluating the same expression have to wait for the lock. This can lead to too many threads blocked for a long time.
> 
> To fix this, we need to introduce a …
=> FISH-987 Extra Logging and Option to Disable Evaluating Class References

appserver/web/war-util/src/main/java/org/glassfish/web/loader/NonCachedJarStreamHandler.java
Resource URL instantiation needs to be privileged action because otherwise it fails the TCK
Jakarta TCK fails due to insuficient permissions
Using `doPrivileged()` block for security manager
```
[runcts] OUT => [javatest.batch] ************************************************************
[runcts] OUT => [javatest.batch] * props file set to "/tmp/jenkins-cts-props.txt"
[runcts] OUT => [javatest.batch] ************************************************************
[runcts] OUT => [javatest.batch] 03-30-2021 03:48:30:  Opened connection to http://localhost:8001/jsonprovidertests_jsp_vehicle_web/jsp_vehicle.jsp
[runcts] OUT => [javatest.batch] 03-30-2021 03:48:30:  Test status from a jsp:  1:Test case throws exception: jsonProviderTest11 Failed:
[runcts] OUT => [javatest.batch] 03-30-2021 …
```
=> [FISH-1178 FISH-1283] fixes resource loading Jakarta TCK failures

appserver/admingui/common/src/main/resources/shared/sslAttrs.inc, appserver/admingui/core/src/main/resources/org/glassfish/admingui/core/Strings.properties, nucleus/common/mbeanserver/src/main/java/org/glassfish/admin/mbeanserver/RMIConnectorStarter.java, nucleus/common/mbeanserver/src/main/java/org/glassfish/admin/mbeanserver/ssl/SSLParams.java, nucleus/grizzly/config/pom.xml, nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/GenericGrizzlyListener.java, nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/HSTSFilter.java, nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/dom/Ssl.java, nucleus/grizzly/config/src/test/java/org/glassfish/grizzly/config/HSTSFilterTest.java
This is a feature
New test included in PR
Go to admin console and enable HSTS from SSL page of http-listner-2, `asadmin restart-http-listeners` then curl localhost:8181 with curl and check the headers.
=> FISH-1021 Add support for HSTS header

appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/micro/services/PayaraInstanceImpl.java, appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/micro/services/data/InstanceDescriptorImpl.java, appserver/tests/payara-samples/pom.xml, appserver/tests/payara-samples/samples/jaxrs-rolesallowed-servlet/src/test/java/fish/payara/samples/jaxrs/rolesallowed/servlet/JAXRSRolesAllowedEETest.java, appserver/tests/payara-samples/samples/realm-identity-stores/pom.xml, appserver/tests/payara-samples/samples/realm-identity-stores/src/test/java/fish/payara/samples/realm/identity/store/MultipleRealmIdentityStoreDefinitionTest.java, pom.xml
Bug fix. Removes duplicate HTTP ports from Payara Micro. Fixes race condition on startup that causes duplicate ports.
Fixes Payara Micro Arquillian tests suites along with the release of Connectors 2.4.1
MP TCK
As usual, use "ignore white space changes"
=> [FISH-1289 QACI-579] fix race condition with duplicate initialization of Micro ports

nucleus/osgi-platforms/felix/src/main/resources/config/osgi.properties
Update of the JDK 11 packages for OSGI.
I left out packages marked as `internal` and related to javadoc and jshell.
Smoke test and using the FlightRecorder packages in a custom OSGI module.
Zulu 8.52.0.23-CA-macosx (build 1.8.0_282-b08) on Mac 11.2.2 with Maven 3.6.3
=> FISH-1286: Update JDK 11 packages for OSGI.

nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/DomainDiscoveryService.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/MemberAddressPicker.java
Certain network configurations lead to chosenAddress variable to be null and prevent Payara to start
Fixes #5192
Existing test suites
=> [FISH-1297] Certain network configurations lead to NPE on startup

nucleus/hk2/hk2-config/src/main/java/org/jvnet/hk2/config/ConfigParser.java, nucleus/hk2/hk2-config/src/test/java/org/jvnet/hk2/config/test/GenericConfig.java, nucleus/hk2/hk2-config/src/test/resources/domain.xml
Update to test included in PR
After the first commit to revert the work-around in, run the upgrade-server command which throws a ParseException. After the new commit it doesn't.
This is the community version of payara/payara-enterprise#363
=> FISH-1214 ConfigParser now accepts XML with content outside elements

nucleus/common/common-util/src/main/java/com/sun/enterprise/security/store/PasswordAdapter.java
ISSUE 5167 - asadmin create-password-alias is very slow when there are many aliases created 
Fixes #5167
This is a fix for the issue #5167 
asadmin create-password-alias is very slow when there are many aliases created.
The call to duplicateKeyStore in the writeKeyStoreSafe method of the PasswordAdapter class is what makes create-password-alias slow in this case.
Running duplicateKeyStore  only with masterPassword is changed resolve the problem.
=> FISH-1311 Password alias optimization

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/UberJarCreator.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/embeddable/DeployerImpl.java, nucleus/deployment/common/src/main/java/fish/payara/deployment/util/URIUtils.java
Now Payara Micro does not support Basic authorization for remote repositories when creates uber jar.
Did some manual tests
Win 10 Pro, Zulu 1.8.0_282
=> Basic Auth support for the remote GAV retrieval during uber jar creation in Payara Micro / FISH-1304

appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/monitoring/WebServiceTesterServlet.java, appserver/webservices/jsr109-impl/src/test/java/org/glassfish/webservices/monitoring/WebServiceTesterServletTest.java, nucleus/pom.xml, pom.xml
The Webservice Tester servlet had a possible Host Header attack vector, allowing for a malicious WSDL to potentially be imported. Combined with a code injection vulnerability in Metro, this allowed an attacker to potentially run their own code on a machine. This PR adds extra validation to the tester servlet to ensure the host header is a valid one, and also adds extra validation to Metro itself to help ensure that any replacement being done is a valid variable to help prevent code injection.
I'm not entirely sure if checking if the variable replacement is a valid _java_ variable is in accordance with the spec (I can't find anything saying one way or the other), but I inferred it to be true given that Metro is already validating that the variable being replaced isn't a …
=> FISH-1274 Vulnerability in Metro's WSDL Code Importing/Parsing - Remote Code Execution

appserver/admingui/payara-console-extras/src/main/resources/cdiDevMode/cdiDevModeApplication.jsf, appserver/payara-appserver-modules/security-openid/src/main/java/fish/payara/security/openid/OpenIdUtil.java, appserver/tests/payara-samples/samples/openid/src/main/java/fish/payara/security/oidc/client/ear/SomeEJB.java, appserver/tests/payara-samples/samples/openid/src/main/java/fish/payara/security/oidc/client/eltests/OpenidConfigBeanEL.java, appserver/tests/payara-samples/samples/openid/src/main/java/fish/payara/security/oidc/client/eltests/SecuredPageEL.java, appserver/tests/payara-samples/samples/openid/src/main/resources/ear/META-INF/application.xml, appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/test/OpenIdELInEarTest.java, appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/test/OpenIdELTest.java, appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/test/OpenIdTestUtil.java
This fixes https://github.com/payara/Payara/issues/4469.
Sometimes `CDI.current().getBeanManager()` returns a bean manager for another module in the EAR (in this case for the EJB JAR instead of for the WAR). As suggested in https://lists.jboss.org/pipermail/cdi-dev/2016-April/008185.html, looking up the bean manager using InitialContext returns the correct bean manager for the current module (WAR in this case).
Also fixes an issue in Admin Console: https://github.com/sharpedavid/el-bug-example has app to deploy to Payara. Go to admin console and click on the application name. At the bottom of the page there should be a component table with entries.
Tests in this PR, in tests/payara-samples/samples/openid:
* `OpenIdELInEarTest` - test for using EL to configure OpenID connector in EAR
* …
=> FISH-84 Fix for using EL to configure OpenId in EAR

appserver/admingui/cluster/src/main/resources/standalone/standaloneInstanceGeneral.jsf, appserver/admingui/cluster/src/main/resources/standalone/standaloneTreeNode.jsf, appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/TargetUtil.java, nucleus/admin/util/src/main/java/com/sun/enterprise/admin/remote/RemoteRestAdminCommand.java, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ListInstancesCommand.java, nucleus/cluster/common/src/main/java/com/sun/enterprise/util/cluster/InstanceInfo.java
Port of PR @OndroMih made to Enterprise repo: https://github.com/payara/Payara-Enterprise/pull/354
Admin Console no longer hangs on every page if a remote instance responds slowly. Admin Console hangs for a much shorter time when displaying details about a remote instance. The `list-instances` command has shorter default timeout and therefore also doesn't hang for too long by default.
After the first commit, Admin Console doesn't ask for status of instances (which requires a REST call) when it only needs the name of the instance. This is also to display the instance names in the sidebar tree which is on every page. This was slowing down loading Admin Console pages significantly if remote instances were slow to respond.
After the second commit:
- The list-instances command has shorter …
=> FISH-1287 Admin console retrieves info about remote instances much faster

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/OpenApiService.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/source/PasswordAliasConfigSource.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/PayaraConfig.java
ISSUE 5177 - Load of REST application is very slow (120 seconds) when there are many password aliases created
This is a fix for the issue #5177
Load of REST application is very slow (120 seconds) when there are many password aliases created.
In this situation (800 password aliases), the cause of this slowness is that Microprofile OpenAPI reads the Microprofile Config when register an application in OpenAPI. PasswordAlias is a config source and it's necessary to read the keystore that is a taxing process if there are many password aliases.
One possible solution to resolve this issue is disable OpenAPI, but disabling OpenAPI seems that only affect to publish /openapi url. OpenAPI service is started even if OpenAPI is disabled and always register the application causing the slowness.
In this …
=> FISH-1315 Improve loading time for REST application when there are many password aliases #5177

appserver/extras/docker-images/pom.xml, nucleus/admin/server-mgmt/src/test/java/fish/payara/admin/servermgmt/cli/PrintCertificateCommandTest.java
See https://docs.azul.com/zulu/release-notes/april-2021.html
* Changes broke some tests after the JDK update, so before it would affect anyone else or Jenkins, I fixed tests already in master branch here.
* most important changes: the TLS 1.0 and TLS 1.1 are disabled by default, quite large set of ciphers is out too.
PrintCertificateCommandTest
CertificateRealmITest (in #5019) also reproduced the issue.
Payara default keystores seems not affected.
We should discuss possible consequences before the upgrade. This is not just about docker images, users will upgrade their JDK distributions soon too.
=> FISH-1323 Zulu JDK Update

appserver/common/container-common/osgi.bundle
This is a PR fixes the `GlassFish Common Util` OSGI issue reproduced by Java EE 7 Samples - EJB Timer test case.
=> FISH-1313 Fixes Java EE 7 Samples - EJB Timer test case

appserver/tests/payara-samples/samples/logging/src/test/java/fish/payara/samples/logging/JsonLogFormatIT.java, nucleus/common/common-util/src/main/java/com/sun/common/util/logging/GFLogRecord.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/ODLLogFormatter.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/UniformLogFormatter.java, nucleus/core/logging/src/main/java/fish/payara/enterprise/server/logging/JSONLogFormatter.java
Fixes #5228 
The fix catches the `IllegalArgumentException` in the log formatter, and falls back to the previous way of processing
arguments, because at this point there is no choice.
Sid-effect of this is that logs may lie when formatted this way, but there is nothing that can be done about it
without total brain-surgery of the logging system
Added new test to payara samples
Payara samples
Mac
=> [FISH-1362] Logging parameter conversion fix

nucleus/common/common-util/src/main/java/fish/payara/logging/PayaraLogManager.java, nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/GlassFishMain.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java
Fix for reflective access introduced here https://github.com/payara/Payara/pull/3310
used ENV variables in logging.properties and verified if they are replaced.
Zulu 8.52.0.23-CA-macosx (build 1.8.0_282-b08) on Mac 11.2.3 with Maven 3.6.3
TODO: Check existing documentation for feature
=> Remove reflective access for processing ENV variables in logging.properties file

appserver/jdbc/admin/src/main/java/org/glassfish/jdbc/admin/cli/JDBCConnectionPoolManager.java, appserver/jdbc/jdbc-config/src/main/java/org/glassfish/jdbc/config/validators/JdbcConnectionPoolValidator.java, appserver/jdbc/jdbc-config/src/test/java/org/glassfish/main/jdbc/config/validators/JdbcConnectionPoolValidatorTest.java
Fixed Wrapping JDBC Objects unable to be disabled if a SQL Trace Listener was present but it was impossible to have no listener. The validation preventing wrapping being disabled while a SQL Trace Listener was present has been removed along with the assertion testing this.
Manually testing the expected behaviour on the ticket with the updated changes. Confirmed the Unit Tests in the module still all pass. Ran the EE7 Samples and confirmed all tests still pass with wrapping on and off.
Zulu JDK 1.8_212 on Ubuntu 20.04.2 with Maven 3.6.3
=> FISH-1327 Fix unable to disable Wrapping of JDBC Objects

api/payara-api/pom.xml, api/payara-api/src/main/java/fish/payara/security/api/ClientCertificateValidator.java, appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java, appserver/tests/payara-samples/samples/client-certificate-validator/pom.xml, appserver/tests/payara-samples/samples/client-certificate-validator/src/test/java/fish/payara/security/client/CdiBean.java, appserver/tests/payara-samples/samples/client-certificate-validator/src/test/java/fish/payara/security/client/CertificateValidator.java, appserver/tests/payara-samples/samples/client-certificate-validator/src/test/java/fish/payara/security/client/EjbBean.java, appserver/tests/payara-samples/samples/client-certificate-validator/src/test/java/fish/payara/security/client/HelloServlet.java, appserver/tests/payara-samples/samples/client-certificate-validator/src/test/java/fish/payara/security/client/ValidatorTest.java, appserver/tests/payara-samples/samples/client-certificate-validator/src/test/resources/META-INF/services/fish.payara.security.api.ClientCertificateValidator, appserver/tests/payara-samples/samples/client-certificate-validator/src/test/resources/glassfish-web.xml, appserver/tests/payara-samples/samples/client-certificate-validator/src/test/resources/web.xml, appserver/tests/payara-samples/samples/pom.xml, appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/ContextImpl.java, appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/JavaEEContextUtilImpl.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebContainer.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/security/integration/RealmInitializer.java, nucleus/common/internal-api/src/main/java/org/glassfish/internal/api/ContextProducer.java, nucleus/security/core/pom.xml, nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/JaspicToJaasBridge.java, nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/WebAndEjbToJaasBridge.java, nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/certificate/CertificateRealm.java
- added API for checking client certificates
- checking validity of the certificate (expiration) when authenticating
Added an API to `CertificateRealm` to be able to plug in additional checks via service loader
add `META-INF/services/fish.payara.security.api.ClientCertificateValidator` with class name to activate
Able to `@Inject` other beans and use EE services
New Payara Sample to test this
With @rdebusscher veto.zip
New "Additional Property" for Certificate Realm: `validation-check`
Default is true. If set to false, time validity (e.g. expiration) will not be checked
Able to inject EJB and CDI beans into the validator, however, lifecycle `@PostConstruct/@PreDestroy`
will not work because validators are not true EE objects and not managed by the container
New Service Loader …
=> [FISH-387] client certificate enhancements

nucleus/packager/external/trilead-ssh2/pom.xml
This artifact causes Payara clean build to fail using maven 3.8.1 due to banning of http dependency collection - this blocks updates to CI
Built successfully and manual tested
Maven 3.8.1
Zulu JDK 8.50.0.21
Mac OSX Catalina 10.15.7
=> [QACI-657] - Use jbcrypt 1.0.2 from central

appserver/extras/docker-images/pom.xml
- Downgrade to 8.282 due to TLS 1.0 being disabled
- Upgrade to 11.10 (11.11 not compatible due to TLS 1.0 being disabled)
=> [FISH-1323] Downgrade JDK 8, upgrade JDK 11 (TLS 1.0,1 being disabled)

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/LoggingHandlers.java
When using the Web console to update the logging properties of the server, they are sent one by one to the REST endpoints. This means that the file is updated multiple times and that the file contents is checked multiple times for changes.
verified all changed data onsc reen is written to the file.
Zulu 8.52.0.23-CA-macosx (build 1.8.0_282-b08) on Mac 11.2.3 with Maven 3.6.3
None, fix issue within codebase
=> FISH-1415: Write updated log information all at once to logging.properties file.

appserver/admingui/common/src/main/resources/appServer/pswdAliasAttr.inc, nucleus/security/core/src/main/java/com/sun/enterprise/security/cli/CreatePasswordAlias.java
Reverted the changed made in ZDEP-1987, fixing the inconsistent behaviour described in FISH-1167 as the alias is now made everywhere. The bug which ZDEP-1987 fixed has been replaced by changing the aliasNameNew text property from the Admin Console UI to 'id'. This means the aliasname isn't lost later on due to it having a variable name that wasn't expected as the REST interface expects 'id'.
All steps to reproduce in both FISH-1167 and ZDEP-1987 have been tested and work correctly. All unit tests within the modules passed.
Zulu JDK 1.8_212 on Ubuntu 20.04.2 with Maven 3.6.3
=> FISH-1167 - Fix Inconsistent Synchronization in Password Alias Alterations for Remote Instances

appserver/packager/appserver-base/src/main/docs/README.txt
This brings it upto date of what it should have been incremented to.
The script should now pick up and increment in future releases once the changes to the script here https://github.com/payara/release-scripts/pull/22 have been merged also.
=> Increment link to release notes in docs

nucleus/common/mbeanserver/src/main/java/org/glassfish/admin/mbeanserver/RMIConnectorStarter.java, nucleus/common/mbeanserver/src/main/java/org/glassfish/admin/mbeanserver/ssl/SSLClientConfigurator.java, nucleus/common/mbeanserver/src/main/java/org/glassfish/admin/mbeanserver/ssl/SSLParams.java
JMXService only tried with TLS 1.0 to connect the MBean server. Since TLS 1.0 and 1.1 are disabled in the latest versions of JDK 8 and 11, the JMXService didn't start anymore.
Tested on JDK 8u282, JDK 8u292, JDK 11.0.9, JDK 11.0.11.
Zulu 8.52.0.23-CA-macosx (build 1.8.0_282-b08) on Mac 11.2.3 with Maven 3.6.3
=> FISH-1418: JMXService can use all TLS 1.x versions

nucleus/packager/external/trilead-ssh2/pom.xml
A port PR for Payara 6 to resolve the http block build failure on maven 3.8.0+
=> [QACI-666] - Use jbcrypt 1.0.2 from central

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/DeploymentFileValidator.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/cmd/options/RuntimeOptions.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/UberJarCreator.java, appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/micro/services/data/InstanceDescriptorImpl.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/embeddable/DeployerImpl.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/util/io/FileUtils.java, nucleus/common/internal-api/src/main/java/org/glassfish/internal/data/ApplicationRegistry.java, nucleus/deployment/admin/src/main/java/fish/payara/deployment/admin/DeployRemoteArchiveCommand.java, nucleus/deployment/common/src/main/java/fish/payara/deployment/util/GAVConvertor.java, nucleus/deployment/common/src/main/java/fish/payara/deployment/util/JavaArchiveUtils.java, nucleus/deployment/common/src/main/java/fish/payara/deployment/util/URIUtils.java
Improve remote archive deployment
***Bug fixes***
* `deploy-remote-archive` command: NPE when `additionalRepositories` option is missing for GAV archive
* `deploy-remote-archive` command: Maven Central is not defined as default repository when deploy GAV archive
* `deploy-remote-archive` command: Application name and context is not set from URI when RAR archive deploy from HTTP(S)
* `deploy-remote-archive` command: Add appropriate name to GAV archive
***Enhancements***
* `deploy-remote-archive` command: Add Basic Auth support
* `deploy-remote-archive` command: Make HTTP(S) scheme check case insensitive
***Improvements***
* Switch GAV converter to use URI instead of URL thus eliminate unnecessary conversion
* Check each additional repository only once
* Check Maven Central in last order
* …
=> FISH-1375 Improve remote archive deployment

appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/WebServicesApplication.java, appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/deployment/WebServiceGrizzlyListenerAdapter.java, appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/deployment/WebServiceGrizzlyRestartListener.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/container/GrizzlyNetworkListenerRestartAdapter.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/GrizzlyService.java
EJB Web Services survive network listener restart / reconfigure
This is a bug fix. When doing rolling upgrades and disabling / enabling HTTP interfaces,
EJB web services no longer work without re-loading the application.
Current test suite
Manual testing was done, as no integration tests for this currently exist, and
it would be very difficult to set those up.
Please use "ignore whitespace changes" when reviewing
=> [FISH-995] EJB Web Services survive network listener restart

nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/CLICommand.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/MultimodeCommand.java
Allows the ability to enable/disable escape event 
Tested by seeing if this the expected outcome is expected, and then setting the env variable AS_ADMIN_DISABLE_EVENT_EXPANSION to false and seeing if it is different
ubunutu 20.04
maven 3.6.3
https://github.com/payara/Payara-Community-Documentation/pull/169
Started by @OndroMih
=> FISH-1423 disable escaping asadmin

appserver/admin/gf_template/src/main/resources/config/domain.xml, appserver/admin/gf_template_web/src/main/resources/config/domain.xml, appserver/admin/production_domain_template/src/main/resources/config/domain.xml, appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml, appserver/extras/embedded/all/src/main/resources/config/domain.xml, appserver/extras/embedded/web/src/main/resources/config/domain.xml
add -Djdk.attach.allowAttachSelf=true to domain.xml templates; JDK 9+ requires this settings to allow to attach to its own virtual machine
Compile, run appserver/distributions/payara/target/stage/payara5/glassfish/bin/asadmin
```
asadmin> start-domain
asadmin> enable-monitoring --modules jvm
```
output as expected:
`Command enable-monitoring executed successfully.`
Linux, OpenJDK 11.0.11
=> FISH-229 change domain.xml to allow enable-monitoring in JDK 9+

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/LoggingHandlers.java
Log levels are now sorted alphabetical on Web Console screen.
Manual verification within Browser
Zulu 8.52.0.23-CA-macosx (build 1.8.0_282-b08) on Mac 11.2.3 with Maven 3.6.3
No document required as this is expected behaviour.
=> FISH-1296: Show Logger levels in Web Console alphabetical.

appserver/jdbc/jdbc-runtime/src/main/java/org/glassfish/jdbc/deployer/DataSourceDefinitionDeployer.java
Customer Feature Request
Created test application with min pool size of 0
ubunutu 20.04
maven 3.6.3
=> FISH-380 Allow JDBC Connection Pools to set min-size to zero

appserver/admingui/microprofile-console-plugin/src/main/resources/fish/payara/admingui/microprofile/Strings.properties, appserver/admingui/microprofile-console-plugin/src/main/resources/microprofile/specs/openAPIConfiguration.jsf, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/admin/GetOpenApiConfigurationCommand.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/admin/OpenApiServiceConfiguration.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/admin/SetOpenApiConfigurationCommand.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/rest/app/provider/QueryFormatFilter.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/rest/app/provider/writer/YamlWriter.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/rest/app/service/OpenApiResource.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/rest/init/OpenApiServletContainerInitializer.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/rest/app/OpenApiApplication.java
This is a feature to provide an option to customize the URL for MicroProfile OpenAPI endpoint.
Manually tested
https://github.com/payara/Payara-Community-Documentation/pull/181
=> FISH-123 Add an option to configure the URL for MP OpenAPI endpoint

nucleus/deployment/common/src/main/java/fish/payara/deployment/util/GAVConvertor.java
If version ends with SNAPSHOT, get maven-metadata.xml from maven repo. Get value which is latest SNAPSHOT version 
Manual testing with local repo and payara nexus repo. 
Asadmin command for nexus repo 
<h5>asadmin deploy-remote-archive --additionalRepositories https://nexus.payara.fish/repository/payara-snapshots fish.payara.extras,ejb-http-client,5.2021.5-SNAPSHOT<h5>
ubunutu 20.04
maven 3.6.3
=> FISH-1497 Improve deploying an application from a Maven repository feature to support snapshot version

appserver/extras/docker-images/basic/pom.xml, appserver/extras/docker-images/server-full/src/main/docker/Dockerfile, appserver/extras/docker-images/server-full/src/main/docker/bin/init_1_generate_deploy_commands.sh, appserver/extras/docker-images/server-full/src/main/docker/bin/startInForeground.sh, appserver/extras/docker-images/server-web/src/main/docker/Dockerfile, appserver/extras/docker-images/server-web/src/main/docker/bin/init_1_generate_deploy_commands.sh, appserver/extras/docker-images/server-web/src/main/docker/bin/startInForeground.sh
resolves https://github.com/payara/Payara/issues/4825
Added new env variable POSTBOOT_COMMANDS_FINAL and PREBOOT_COMMANDS_FINAL as suggested
Changed keyserver as previous one wasn't working 
Manual testing
ubunutu 20.04
maven 3.6.3
=> FISH-371 Improve handling of custom POSTBOOT and PREBOOT file in Docker container

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ApplicationProcessor.java
Fix for https://github.com/payara/Payara/issues/5111
The solution is simple -- don't fill style parameter as the value "simple" is incorrect for some usages (e.g. query of header parameters). The standard has meaningful defaults, so it is not necessary to calculate the value based on usage.
manually - in the generated openapi is missing "style: simple" in the parameter
I also tried openapi-generator-cli and there is no problem without style.
=> FISH-1068 in generated openapi omit default style for parameter

pom.xml
Updates Jakarta EL version to one, that fixes CVE-2021-28170.
This incorporates new version of EL based on payara/patched-src-el-ri#4
Present in upstream
JSP and JSF related samples run
```
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.1\bin\..
Java version: 1.8.0_292, vendor: Azul Systems, Inc., runtime: C:\Program Files\Zulu\zulu-8\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
=> FISH-1421: Update version of Jakarta EL 3

appserver/pom.xml
Upgrade json-smart library to the latest version 2.4.7 as it solves https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-31684
I tested MP TCKs.
=> FISH-5544 upgrade json-smart to the latest version, 2.4.7

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/OpenAPIImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/tags/TagImpl.java
Modify comparison of servers and tags in OpenApi to allow multiple entities without data (url or name). Without it, TCK fails.
GH issue: https://github.com/eclipse/microprofile-open-api/issues/453
This change is required by TCK, discussion is here:
https://github.com/eclipse/microprofile-open-api/issues/453
I added also a note how to improve the TCK.
Tested manually, unit tests, TCK without modification
Checkout TCK runner from a branch: https://github.com/payara/MicroProfile-TCK-Runners/tree/FISH-1530
=> FISH-1530 allow multiple servers and tags with empty url and name

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/headers/HeaderImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/media/ContentImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/parameters/ParameterImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ApplicationProcessor.java, appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/test/app/application/HiddenTest.java
This is a bug fix PR to remove hidden Parameters, Schema, and properties from the OpenAPI document.
`HiddenTest#hiddenSchemaPropertyDoesNotCauseErrors`
`HiddenTest#hiddenSchemaDoesNotCauseErrors`
`HiddenTest#hiddenParamDoesNotCauseErrors`
MP OpenAPI Impl Unit Tests
MP OpenAPI TCK
=> FISH-1312 MP OpenAPI hidden attribute is ignored

pom.xml
The original requirement was to upgrade jackson-databind, which is a part of the jackson package (jackson-databind is a transitive dependency). Updated to the latest stable version: 2.12.4.
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.12.4
All TCKs
=> FISH-5545 upgrade jackson to the latest version, 2.12.4

appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/test/OpenIdELPerSessionInEarTest.java, appserver/tests/payara-samples/samples/openid/src/test/java/fish/payara/security/oidc/test/OpenIdELPerSessionTest.java
This is a bug fix which resolves tests with an Enterprise @SincePayara annotation version always running on Community, even if the payara.version set was released before the version in the annotation. As there is no way to compare past and future Enterprise versions to Community versions reliably the version used within the annotation should reflect the edition it's present in.
Manually tested each change to ensure the test is skipped when a Community payara version is specified that was released before the version in the annotation.
Windows 10 Pro, Maven 3.6.3, JDK8
No documentation as this is internal info. 'Tests and Payara Versions' updated with a small comment on Confluence
The title of this PR is slightly different from the QACI-672 ticket as that ticket only specifies the issue …
=> QACI-672 Tests that specify @SincePayara with an Enterprise version always run in Community

nucleus/common/common-util/src/main/java/com/sun/common/util/logging/SortedLoggingProperties.java
This is a bug fix that causes the intended behaviour on JDK11 when setting the server log properties to JSON which also fixes the failing tests.
Ensured SortedLoggingPropertiesTest and JSONLogFormatIT now pass on JDK11. Manually tested once JSON formatting is selected the logs can be seen from the admin console and the logging.properties file is in the order set out in FISH-1509.
Windows 10 Pro, Maven 3.6.3. Tested with both JDK8 and Zulu JDK11.
No documentation required.
=> FISH-5654 - Fixed JSON Logging not working with JDK11

appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/cdi/CdiInitEventHandler.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/cdi/JwtAuthCdiExtension.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/CacheableString.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/JWTAuthenticationMechanism.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/JWTProcessingException.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/JwtKeyStoreUtils.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/JwtPrivateKeyStore.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/JwtPublicKeyStore.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/KeyLoadingCache.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/SignedJWTIdentityStore.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jwt/ClaimValueImpl.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jwt/JsonWebTokenImpl.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jwt/JwtTokenParser.java
Recreated from https://github.com/payara/Payara/pull/5371
Improvements of MP 4 support in JWT Authorization
Changes were done in branches in mine and Petr's forks.
Tests are fixed in PR:
https://github.com/payara/MicroProfile-TCK-Runners/pull/152
New tests enabled in MP TCK Runner
All JWT-Auth TCK tests pass, using full and base profiles
Run MP Auth TCK Runner using https://github.com/payara/MicroProfile-TCK-Runners/pull/152
=> FISH-1520 Fix MicroProfile JWT-Auth TCK Failures

appserver/web/weld-integration/pom.xml, appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/ExecutorServicesImpl.java
This is a bug fix that causes the incorrect error message in the log on firing the async CDI events.
Manually
Not required
=> FISH-81 Fix Incorrect error "No valid EE environment for injection" for CDI reported for events

nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/ChangeMasterPasswordCommand.java, nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/ChangeMasterPasswordCommandDAS.java, nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/LocalServerCommand.java, nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/ChangeNodeMasterPasswordCommand.java
Added warning message to change-master-password command to warn about additional trust and key stores not being re-encrypted 
Ran command to see if warning message appeared.
openjdk version "1.8.0_292" 
ubuntu 20.04 
maven 3.6.3
=> FISH-5639 Added warning message to change-master-password command

appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/jws/ExtensionFileManager.java, appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/boot/loader/jar/JarFile.java
This pull request fixes two SonarQube violations of rule [2093](https://rules.sonarsource.com/java/RSPEC-2093).
Motivation:
Closing autocloseable resources by manually invoking `.close()` is error-prone, can lead to resource leaks and makes the code harder to follow. This pull request refactors the code to instead close the resources automatically using `try-with-resource` statements.
The SonarQube violations are listed here:
* https://sonarcloud.io/project/issues?id=fish.payara.server%3Apayara-aggregator&issues=AW-B1Nbfql1jQuQn6HOw&open=AW-B1Nbfql1jQuQn6HOw
* https://sonarcloud.io/project/issues?id=fish.payara.server%3Apayara-aggregator&issues=AW-B1PeXql1jQuQn6HPD&open=AW-B1PeXql1jQuQn6HPD
This patch was generated automatically using the static analyzer …
=> FISH-5694 Fix Sonar warnings for autoclosable resources

nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigExpressionResolver.java
fixed an error when the ConfigProperty value ended in dollar sign.  
(Payara Micro 5.2021.1～)  
～～～  
when i create microprofile-config.properties like below.  
```properties
test=testest$
```
and inject with annotation like,  
```java
@ConfigProperty(name="test") Optional<String> test
```
the error below occurs.  
```
java.lang.ArrayIndexOutOfBoundsException: Index 9 out of bounds for length 9
at fish.payara.nucleus.microprofile.config.spi.ConfigExpressionResolver.isExpressionStart(ConfigExpressionResolver.java:231)
at fish.payara.nucleus.microprofile.config.spi.ConfigExpressionResolver.resolveExpression(ConfigExpressionResolver.java:178)
at fish.payara.nucleus.microprofile.config.spi.ConfigExpressionResolver.getValue(ConfigExpressionResolver.java:122)
at …
```
=> FISH-5695 ArrayIndexOutOfBoundsException when the ConfigProperty value ends in a dollar sign

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroRuntimeImpl.java, appserver/web/web-glue/src/main/java/com/sun/web/server/J2EEInstanceListener.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/InvocationManagerImpl.java
When `PayaraMicroRuntime.deploy` is used to deploy an application in a service call (like JAX-RS call in `payara-micro-deployer`) the call retained Component Invocation context of deploying application.
With changes to MP Config earlier this year this caused MP Config properties from classpath not being properly discovered.
At the core the PR "pauses" invocation context by putting it aside and restoring it after deployment.
In my testing this uncovered other problems:
Two component invocations were taken from invocation stack when exception was thrown in `postInvoke` (FISH-5690)
The invocation in this case was EntityManager incorrectly propagated to managed thread executor resulting in duplicate closes of it.
It would be great to run Concurrency, Servlet, JPA and EJB TCKs on this one as …
=> FISH-1058 FISH-5690 FISH-5691 Deploy applications via Micro API outside Application Invocation and fix surrounding trouble

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/rest/init/OpenApiServletContainerInitializer.java
This PR fixes the dynamic registration of the Open API endpoint via prioritizing initialization of OpenApiApplication's `org.glassfish.jersey.servlet.ServletContainer` on application deployment.
A bug fix addressing community bug report: #5363.
OpenAPI document processing is done on the first call to `/openapi` endpoint.
=> FISH-5660 Micro fails to deploy WAR with "ServletConfig has not been initialized"

nucleus/admin/server-mgmt/src/main/manpages/com/sun/enterprise/admin/servermgmt/cli/stop-domain.1
Currently the help text from running _asadmin stop-domain --help_  does not accurately reflect the behaviour of the subcommand. This updates it to be accurate.
Manually tested running _asadmin stop-domain --help_ to ensure the updated text is displayed and keeps to the original formatting.
Windows 10 Pro, Maven 3.6.3, JDK8
=> FISH-966 Updated asadmin stop-domain help to be accurate with behaviour

appserver/tests/payara-samples/test-domain-setup/src/test/java/fish/payara/samples/setuptests/MultipleKeystoresConfigurationTest.java, nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/LocalServerCommand.java, nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/ssl/JSSESocketFactory.java, nucleus/security/ssl-impl/src/main/java/com/sun/enterprise/security/ssl/impl/SecuritySupportImpl.java
This is a bugfix for [FISH-1342](https://github.com/payara/Payara/pull/5324) which introduced the ability to specify multiple keystores, however this didn't work on Windows due to the delimiter being ':'. 
This has been changed to use File.pathSeparator which is OS dependent meaning the delimiter is still ':' for Linux but ';' for Windows, allowing this feature to work. Changes have also been made to the keystore path for MultipleKeystoresConfigurationTest meaning SecureCustomHttpListenerTest now passes on Windows.
The same delimiter changes have been made to [FISH-5639](https://github.com/payara/Payara/pull/5370) so this displays the keystores correctly on Windows.
Manually tested the feature works on windows. Tested the Multiple Keystores test in Payara Samples ensuring it passes and …
=> FISH-5693 Updated multiple keystore delimiter to be OS dependent

appserver/extras/docker-images/server-full/src/main/docker/bin/init_1_generate_deploy_commands.sh
Fix for https://github.com/payara/Payara/issues/5391, application added to $DEPLOY_DIR in docker image is not deployed. 
Actually, the fixed file is exactly the same as the related file Payara/appserver/extras/docker-images/server-web/src/main/docker/bin/init_1_generate_deploy_commands.sh, which was OK.
In Payara/appserver/extras/docker-images, build docker image:
mvn -pl :server-full-docker-image -am -PBuildExtras -PBuildDockerImages install
Then create directory with clusterjsp.war (or any war), Dockerfile:
FROM payara/server-full
COPY clusterjsp.war $DEPLOY_DIR
Run the docker:
docker run -i --rm --name bwbportal -p 54848:4848 -p 58080:8080 -p 58181:8181 bwbportal
Correct output:
In log:
clusterjsp was successfully deployed in ...
Accessible app:
http://localhost:58080/clusterjsp/
=> FISH-5701 fix automated deployment, put command to the right file

nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/AnsiColorFormatter.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/CommonFormatter.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/ODLLogFormatter.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/UniformLogFormatter.java, nucleus/core/logging/src/main/java/fish/payara/enterprise/server/logging/JSONLogFormatter.java
Title. Bug fix.
When starting Payara Micro an error would get thrown due to the no-arg constructor no longer existing.
None
None
Started Payara Micro - no error
Windows, JDK 8
None
None
=> FISH-5711 Fix Method not Found Error on boot of Payara Micro

appserver/web/web-core/pom.xml, appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContextValve.java, appserver/web/web-core/src/test/java/org/apache/catalina/core/StandardContextValveTest.java
Adding fix to solve problem to access Restricted Directory when using context root as /
Added new test: StandardContextValveTest.java
I already tested this on local environment. Check the following comment from jira to verify results:
https://payara.atlassian.net/browse/FISH-5702?focusedCommentId=57244
=> Fish 5702 improper limitation pathname restricted directory

api/payara-api/src/main/java/fish/payara/security/client/ClientCertificateValidator.java, nucleus/security/core/pom.xml, nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/certificate/CertificateRealm.java
New Feature, limited functionality of https://github.com/payara/Payara/pull/5241 as it requires other PRs that can't be moved to Enterprise yet.
Used reproducer application for feature to check if it works as intended.
Interop EJB runs successfully (was issue with previous attempt)
Zulu 8.52.0.23-CA-macosx (build 1.8.0_282-b08) on Mac 11.5 with Maven 3.6.3
TODO
=> FISH-5646: Client Certificate Validator API

pom.xml
Jakarta named properties in a Jakarta EE9 application persistence.xml were not recognised. I added the changes to the payara transformer and upgraded the version. PR [here ](https://github.com/payara/transformer/pull/21)
I believe this PR will also solve the issue #5404 
Deployed an Jakarta EE9 application and checked if the persistence.xml properties were working as intended.
Ubuntu 20.04 maven version 3.6.3  openjdk version "1.8.0_292"
=> FISH-5678 Fixed Jakarta named properties in persistence.xml 

nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/ExcludeFieldsSupport.java
Title.
Handle the empty string which is default so that the log message doesn't get thrown on startup.
None
None
Started server - no error.
Added an exclude field - no error and field excluded.
Windows 10, JDK8
N/A
None
=> FISH-5736 Fix Unknown Exclude Field Provided Warning on Startup

appserver/admingui/web/src/main/resources/grizzly/httpAttr.inc, appserver/admingui/web/src/main/resources/org/glassfish/web/admingui/Strings.properties, appserver/tests/payara-samples/samples/http/src/test/java/fish/payara/samples/http/CompressionTest.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/connector/coyote/PECoyoteConnector.java, nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/GenericGrizzlyListener.java, nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/dom/Http.java, pom.xml
An improvement allowing finer configuration of HTTP GZip Compression. It allows the user to configure between three compression strategies: Default, Filtered and Huffman Only.
It also allows for setting the compression level, -1 is the default level, 0 is no compression, 1 is fastest speed and 9 is fastest compression.
Changes have also been made in patched-src-grizzly: https://github.com/payara/patched-src-grizzly/pull/31
Requires PR in patched-src-grizzly to be merged.
CompressionTest in Payara samples. Tests compression in all strategies and levels works.
Manually tested compression works with: 
_curl http://localhost:8080 --silent -H "Accept-Encoding: gzip,deflate" --write-out "%{size_download}\n" --output /dev/null_
Tested using the new test in Payara Samples.
Windows 10 Pro, Maven …
=> FISH-376 Allow finer configuration details of HTTP GZIP compression

appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/impl/MetricsServiceImpl.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/jmx/MBeanExpression.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/jmx/MBeanMetadata.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/jmx/MBeanMetadataHelper.java
Improvement of templating (https://docs.payara.fish/community/docs/documentation/microprofile/metrics/vendor-metrics.html#advanced-templating), adding `${instance}` to `metrics.xml`, which is replaced with the name of the current instance.
- copy `metrics.xml` from `Payara/appserver/payara-appserver-modules/microprofile/metrics/src/main/resources` to `payara5/glassfish/domains/domain1/config`
- add this part before `</vendor>`:
```
<metadata>
<name>requestcount.${instance}</name>
<mbean>amx:type=web-request-mon,pp=/mon/server-mon[${instance}],name=clusterjsp/server/requestcount#count</mbean>
<type>gauge</type>
<unit>none</unit>
<displayName>XXXFINDMEXXX</displayName>
<description>XXXFINDMEXXX</description>
</metadata>
```
- setup monitoring on server
```
set-monitoring-level …
```
=> FISH-5658 instance in custom metrics

appserver/jms/jms-core/src/main/java/com/sun/enterprise/connectors/jms/system/ActiveJmsResourceAdapter.java
Fix for the issue when starting the local jms broker using jdk 11
I didn't add new unit test because of the complexity to deal with statics when starting the ActiveJmsResourceAdapter class
please verify the following comment on jira ticket with the result of manual test that I did on my local environment:
https://payara.atlassian.net/browse/FISH-28?focusedCommentId=57690
Windows 10 with JDK 11(zulu), JDK 10(openjdk) and JDK 9(openjdk)
=> Fish 28 fixing issue when starting openmq with invalid jre path

appserver/ejb/ejb-opentracing/src/main/java/fish/payara/ejb/opentracing/OpenTracingIiopClientInterceptor.java, appserver/ejb/ejb-opentracing/src/main/java/fish/payara/ejb/opentracing/OpenTracingIiopInterceptorFactory.java, appserver/ejb/ejb-opentracing/src/main/java/fish/payara/ejb/opentracing/OpenTracingIiopServerInterceptor.java, appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardWrapper.java, nucleus/packager/external/opentracing-repackaged/pom.xml, nucleus/payara-modules/opentracing-adapter/pom.xml, nucleus/payara-modules/opentracing-adapter/src/main/java/fish/payara/opentracing/OpenTracingService.java, nucleus/payara-modules/opentracing-adapter/src/main/java/fish/payara/opentracing/tracer/Tracer.java, nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/RequestTracingService.java, nucleus/payara-modules/requesttracing-core/src/main/java/fish/payara/nucleus/requesttracing/store/RequestTraceStoreFactory.java
An attempt to improve the throughput of the OpenTracing service, particularly with regards to remote EJBs.
The main change is the un-synchronising of the `getTracer` method - creation of tracers is still synchronised but is now split off into another method and utilises double-checked locking to prevent conflicts. While double-checked locking can be naughty, in this case it's being done on a map itself, so the issue of partially constructed references not returning null Shouldn't™ occur.
My results from performance testing were largely inconclusive since the realm of variance is pretty large - this is working at the micro and millisecond timeframe, any slight deviation outside of my control (e.g. OS runs a background process) will affect the result. In any case, I shall list the reasoning …
=> FISH-5636 Remote EJB Tracing Improvements

appserver/extras/docker-images/basic/src/main/docker/Dockerfile, appserver/extras/docker-images/tests/pom.xml
Upgrade tini to version 0.19.0
Also upgraded testcontainers to version 1.15.1 as docker tests were not running when building the docker images with the command `mvn clean install -PBuildDockerImages -pl :docker-images -amd` you would get the error `No such image: quay.io/testcontainers/ryuk:0.2.3`
N/A
N/A
Built docker images and started server-full
ubuntu 20.04 maven 3.6.3 openjdk version "1.8.0_292"
N/A
N/A
=> FISH-261 Upgrade tini to version 0.19.0

appserver/extras/docker-images/pom.xml
Update to https://github.com/payara/Payara/pull/5460 to use the just released images.
None
None
Built and ran the docker tests.
Windows 10, JDK 8.
N/A
None extra on top of https://github.com/payara/Payara/pull/5460 - TLS 1.0 and 1.1 removed.
=> FISH-1323 Upgrade Docker Images

nucleus/pom.xml
Missed in the original upgrade of all the Felix gubbins.
Applies our pre-existing patch to Felix FileInstall 3.7.0.
Our pre-existing patch makes Payara a bit better at cleaning up after itself in /tmp.
None
None
Started the server and loaded the admin console without issue on JDK 8 and 11.
WSL OpenSUSE 15.3.
Zulu JDK 8u312 and 11.0.13
N/A
None
=> FISH-5750 Felix FileInstall 3.7.0.payara-p1

api/payara-bom/pom.xml, appserver/extras/embedded/common/bootstrap/pom.xml, appserver/extras/embedded/common/installroot-builder/pom.xml, appserver/extras/embedded/common/instanceroot-builder/pom.xml, appserver/extras/embedded/common/osgi-main/pom.xml, appserver/extras/embedded/common/osgi-modules-uninstaller/pom.xml, appserver/osgi-platforms/felix-webconsole-extension/pom.xml, appserver/web/web-core/pom.xml, appserver/web/web-naming/pom.xml, appserver/web/web-naming/src/main/java/org/apache/naming/resources/DirContextURLStreamHandlerService.java, appserver/web/weld-integration/pom.xml, nucleus/admin/rest/rest-service/pom.xml, nucleus/common/common-util/pom.xml, nucleus/core/bootstrap/pom.xml, nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/osgi/BundleProvisioner.java, nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/osgi/EmbeddedOSGiGlassFishRuntimeBuilder.java, nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/osgi/OSGiFrameworkLauncher.java, nucleus/flashlight/framework/pom.xml, nucleus/osgi-platforms/felix/src/main/resources/config/osgi.properties, nucleus/osgi-platforms/osgi-cli-remote/osgi.bundle, nucleus/osgi-platforms/osgi-cli-remote/pom.xml, nucleus/osgi-platforms/osgi-container/pom.xml, pom.xml
OSGi changes to allow HK2 to resolve OSGi and for the server to boot.
Note that this does not constitute Payara supporting JDK 17 - it simply fixes this particular issue of the Felix and HK2 not even able to boot.
None
None
Started the domain and loaded admin console successfully on JDK 8 and 11 without error
Started the domain successfully in JDK 17 without error (loading the admin console is a separate can of worms)
Windows 10.
Zulu JDK 8u312, 11.0.13, and 17.0.1
N/A
If you've started the admin console on JDK 8 and/or 11, you may need to clean the domain before attempting to start on JDK 17 since it may try to load the admin console automatically.
=> FISH-5812 HK2 Cannot Resolve OSGi on JDK 17

appserver/admin/gf_template/src/main/resources/config/domain.xml, appserver/admin/gf_template_web/src/main/resources/config/domain.xml, appserver/admin/production_domain_template/src/main/resources/config/domain.xml, appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml, appserver/orb/orb-iiop/pom.xml, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/composite/CompositeUtil.java, nucleus/packager/nucleus-corba-base/pom.xml, nucleus/pom.xml
Required component upgrades for JDK 17.
**Also adds new System Property to default domain config.**
> For ORB compatibility with JDK11+ JDKs see https://github.com/eclipse-ee4j/orb-gmbal/issues/22
In short, the ORB references com.sun.corba.ee.spi.orb.ORB, which references com.sun.corba.ee.impl.corba.TypeCodeFactory which eventually references com.sun.corba.ee.spi.legacy.connection.Connection.getSocket and java.net.Socket.checkPermission(java.net.SocketImpl).
Now SocketImpl contains a method "<S extends SocketImpl & PlatformSocketImpl> S createPlatformSocketImpl", which causes the ORB to crash completely. Setting a system property with this string ignores the fact GMBAL doesn't support multiple upper bounds.
None.
None.
Ran the Payara - ejb-invoker Secure Endpoint test against JDK 8 - …
=> FISH-5829 FISH-5830 GMBAL 4.0.3 and PFL 4.1.2

pom.xml
Please consider updating Yasson 1.0.6 to 1.0.9 in next release of Payara Community 5.x
Yasson 1.0.6 contains several serialization failures which are fixed in 1.0.9 and it took me days to work around them, so to prevent others to run in the same troubles, this update should get adopted. As it is a pure bug fix it should not imply any new bugs.
=> Yasson 1.0.9

pom.xml
Updates OpenMQ to 5.1.4, reapplies our pre-existing patches, and backports https://github.com/eclipse-ee4j/openmq/commit/18fdf26b1a28fcd036132aa82d7d011f6f551dce to make JDK 17 happy.
Deployment of OpenMQ 5.1.4.payara-p2
https://github.com/payara/patched-src-openmq/commits/openmq-5.1.4.payara-maintenance
None
Ran against JDK 8, 11, and 17.
Started server, ran JMS tests from JavaEE7-Samples - no failures
These tests were run with https://github.com/payara/Payara/pull/5484 and https://github.com/payara/Payara/pull/5485 merged locally.
WSL OpenSUSE 15.3
Zulu JDK 8u312, 11.0.13, 17.0.1
N/A
None
=> FISH-5838 FISH-5839 OpenMQ 5.1.4.payara-p2

appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/ProxyServicesImpl.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/WeldProxyException.java, pom.xml
Title.
Updates Weld to a version that works with JDK 17.
PR does not constitute support for CDI under JDK 17 - there are failures in Payara Samples that indicate an issue in Weld with the resolution of the `RolesPermitted` annotation. Java reflect can't parse the signature of the `semantics` enum, specifically when it's the Weld Proxy being parsed (it's using JDK 1.5 type signatures which support for was removed in JDK 17):
`fish.payara.cdi.auth.roles.LogicalOperator -- Signature Parse error: Expected Field Type Signature`
This does however only occur when the server is running under JDK 17 since it's a change in the JDK itself that breaks things.
None.
None
Started the server and ran Payara Samples without issue - JDK 8
Started the server and ran Payara Samples without issue - JDK 11
WSL …
=> FISH-5832 FISH-5833 Weld 3.1.8 and Weld SPI 3.1.SP4

appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/CSIV2TaggedComponentInfo.java, appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/GSSUPToken.java, appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/GSSUtils.java, appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/GSSUtilsService.java, appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/SecClientRequestInterceptor.java, appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/SecServerRequestInterceptor.java, nucleus/security/core/src/main/java/com/sun/enterprise/common/iiop/security/GSSUtilsContract.java
Cherry-pick from upstream of required changes for EJB security on JDK 17.
None.
None.
Ran the Payara - ejb-invoker Secure Endpoint test against JDK 8 - worked
Ran the Payara - ejb-invoker Secure Endpoint test against JDK 11 - worked
Ran the Payara - ejb-invoker Secure Endpoint test against JDK 17 - worked
WSL OpenSUSE 15.3, Zulu JDK 8u312, 11.0.13, 17.0.1
N/A
None
=> FISH-5836 FISH-5837 Refactor EJB Security to Use Public APIs and Fix Improper Formatting in GSSUtils

appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/jmx/MBeanMetadata.java, appserver/payara-appserver-modules/microprofile/metrics/src/test/java/fish/payara/microprofile/metrics/jmx/MBeanMetadataTest.java
Fixes Exception when not using tags in custom Vendor metrics having a Placeholder.
new Unit test MBeanMetadataTest
Zulu 8.52.0.23-CA-macosx (build 1.8.0_282-b08) on Mac 11.8 with Maven 3.8.2
Not needed, Bugfix
=> FISH-5801: Custom Vendor MP Metrics Using Placeholders Require 'tags'

appserver/admin/gf_template/src/main/resources/config/domain.xml, appserver/admin/gf_template_web/src/main/resources/config/domain.xml, appserver/admin/production_domain_template/src/main/resources/config/domain.xml, appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml
MicroProfile Rest Client TCK would fail complaining that java.lang.invoke wasn't opened.
None
None
Ran MicroProfile Rest Client TCK against Payara Server running on JDK 17.
Windows 10, Zulu JDK 17.0.1
N/A
None
=> FISH-5840 Open java.lang.invoke for MP Rest Client

appserver/extras/payara-micro/payara-micro-distribution/build.xml
Take two of https://github.com/payara/Payara/pull/5456
The file `.gitkeep` is not required in the unpacked runtime directory of the Payara Micro instance and its presence prevents using the CDS capabilities fully on JDK17.
None
None
Built and checked manually - no .gitkeep present in any folder within Payara Micro
On JDK 17:
* java -jar payara-micro.jar --rootdir micro-root --outputlauncher
* java -XX:ArchiveClassesAtExit=payara.jsa -jar micro-root/launch-micro.jar --warmup --deploymentDir deployment --nocluster
* java -jar -XX:SharedArchiveFile=payara.jsa  micro-root/launch-micro.jar
* Should start with no errors
Windows 10, JDK 17.0.1
N/A
I let IntelliJ do a formatting sweep because the indentation of the file made me cringe.
If you want to see the actual functionality change, just look …
=> FISH-5802 Exclude .gitkeep File From Payara Micro

appserver/pom.xml
Fixes the issue with Weld creating proxies with Java 5 style signatures, which lead to `Signature Parse error: Expected Field Type Signature` when parsing annotations with enum parameters with non-default values.
None
None
Ran Payara Samples on JDK 8, 11, and 17 - no issues.
Ran Java EE 7 Samples on JDK 8, 11, and 17 - no issues.
WSL OpenSUSE 15.3, Zulu JDK 8u312, 11.0.13, 17.0.1
N/A
None.
=> FISH-5835 ClassFileWriter 1.2.5

pom.xml
Subresource Integrity (SRI) is a security feature that enables browsers to verify that resources they fetch (for example, from a CDN) are delivered without unexpected manipulation. It works by allowing you to provide a cryptographic hash that a fetched resource must match.
Dependent on https://github.com/payara/monitoring-console/pull/37
Will release version 1.8 of monitoring-console-webapp once approved.
N/A
Loaded the monitoring console and verified everything works.
Ubuntu 20.04 openjdk version "1.8.0_302" maven 3.6.3
N/A
=> FISH-5824 Added Subresource Integrity for monitoring console

appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/datastructure/DataStructureFactory.java, appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/datastructure/RWLockDataStructure.java
This fixes a lost read lock in RWLockDataStructure in case removeAll() is called while other threads call getResource().
fixes #5496
No new tests created
Testing could be done by simulation heavy db access load.
There were notes about some coarse lock handling in method addResource(...) which as been adapted according to lock handling in getResource() method
=> PAYARA-5496  fixing RwLockDatastructure locking bug (also FISH-985)

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/LoggingHandlers.java, appserver/admingui/common/src/main/resources/configuration/loggerGeneral.jsf, appserver/admingui/common/src/main/resources/org/glassfish/common/admingui/Strings.properties, nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/LogService.java, nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/logging/UpgradeLogging.java, nucleus/admin/template/src/main/resources/config/logging.properties, nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/mbean/LoggingImpl.java, nucleus/common/common-util/src/main/java/com/sun/common/util/logging/GFLogRecord.java, nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java, nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingPropertyNames.java, nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingXMLNames.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/SetLogAttributes.java
A new feature allowing users to skip the forced .toString() on all parameters when logging. The command to set this property has been added to set-log-attributes and the admin console. This property is updated dynamically and doesn't need a server restart for the logging changes to take affect.
None
None
Manually tested the toString is skipped appropriately and without the need for a server restart. Ran the logging tests already in place.
Community Documentation PR: https://github.com/payara/Payara-Community-Documentation/pull/276
If you test this manually, fastLoggingEnabled() will return the old value while logging a logging property has been changed. Any logs after this will be using the new value. This doesn't impact the functionality but please keep it …
=> FISH-5703 Option to Improve Logging Speed

appserver/security/core-ee/pom.xml, appserver/security/core-ee/src/main/java/com/sun/enterprise/security/jacc/JaccWebAuthorizationManager.java, appserver/security/realm-stores/src/main/java/fish/payara/security/realm/CertificateCredentialImpl.java
The problem: When authenticated using @CertificateAuthenticationMechanismDefinition and IdentityStore @CertificateIdentityStoreDefinition, and when a role is mapped to a particular certificate principal in payara-web.xml, the role isn't assigned to the authenticated user. The role is applied if CLIENT_CERT login config mechanism is defined in web.xml.
Proposed solution in this PR:
* in `JaccWebAuthorizationManager`, if the role isn’t granted (potentially because of the mismatch between `PrincipalImpl` and `CallerPrincipal`), check if the current principal class is `CallerPrincipal`. If that's true, convert it to `PrincipalImpl` and check for the role again
* In `CertificateCredentialImpl`, change how the `CallerPrincipal` is created so that it contains the name in the …
=> FISH-5769 RFC2253 format with Certificate HAM, fix role verification

pom.xml
[CVE-2021-40690 ](https://nvd.nist.gov/vuln/detail/CVE-2021-40690#vulnCurrentDescriptionTitle) identified a security issue with Santuario versions prior to 2.2.3 and 2.1.7. This PR updates our patched repo to 2.2.3 which also can run on JDK14+
Requires PR in patched-src-metro-wsit to be merged: https://github.com/payara/patched-src-metro-wsit/pull/11
None
All unit tests. Tested server starts and admin console loads
Windows 10, Maven 3.6.3, JDK 8 and JDK 17
Community Documentation PR: https://github.com/payara/Payara-Community-Documentation/pull/277
Webservices 2.4.3.payara-p6 hasn't been built and uploaded to nexus yet. This will be done when the blocking PR is approved.
=> FISH-5811 Upgrade Apache Santuario to 2.2.3

appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/SecClientRequestInterceptor.java, appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/SecurityMechanismSelector.java
Bug Fix.
Payara expects to be able to propagate a CSIV2 IdentityToken to the remote EJB, and so needs to map the `CallerPrincipal` (wrapped within a `DistinguishedPrincipalCredential`) it has gained from the OIDC provider to a Distinguished Name, Principal Name, or Certificate Chain (or simply pass an anoynmous token).
This PR makes the server now map `DistinguishedPrincipalCredential`s as a GSSAPI principal name (Generic Security Service Application Program Interface).
None
None - this is a tricky test to automate (multiple instances, applications deployed to one and not the other etc.).
Executed the reproducer attached to the issue.
Windows 11, JDK 11.0.13
N/A
Slight variation on this solution available here, which tries to avoid the creation of a GSSUPName class …
=> FISH-5883 Security Exception When a Remote EJB Is Called While Authenticated Using The OIDC Security Connector

appserver/packager/microprofile-package/pom.xml, appserver/payara-appserver-modules/microprofile/pom.xml, appserver/payara-appserver-modules/microprofile/rest-client/pom.xml, appserver/payara-appserver-modules/microprofile/rest-client/src/main/java/fish/payara/microprofile/restclient/RestClientServletContainerInitializerBlacklist.java, appserver/payara-appserver-modules/microprofile/rest-client/src/main/resources/META-INF/services/fish.payara.web.loader.ServletContainerInitializerBlacklist, appserver/tests/payara-samples/samples/microprofile-rest-client/pom.xml, appserver/tests/payara-samples/samples/microprofile-rest-client/src/main/java/fish/payara/sample/microprofile/restclient/JAXRSConfiguration.java, appserver/tests/payara-samples/samples/microprofile-rest-client/src/main/java/fish/payara/sample/microprofile/restclient/JavaEE8Resource.java, appserver/tests/payara-samples/samples/microprofile-rest-client/src/main/java/fish/payara/sample/microprofile/restclient/JavaEE8ResourceClient.java, appserver/tests/payara-samples/samples/microprofile-rest-client/src/main/resources/META-INF/beans.xml, appserver/tests/payara-samples/samples/microprofile-rest-client/src/test/java/fish/payara/samples/microprofile/restclient/MicroProfileRestClientIT.java, appserver/tests/payara-samples/samples/pom.xml, appserver/web/war-util/osgi.bundle, appserver/web/war-util/src/main/java/fish/payara/web/loader/ServletContainerInitializerBlacklist.java, appserver/web/war-util/src/main/java/org/glassfish/web/loader/ServletContainerInitializerUtil.java, appserver/web/web-core/pom.xml, appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java
Bug fix.
If we don't skip trying to initialise Rest Client "servlets" a knock-on effect will occur during validation where a clash will be detected with the implementation endpoint (as in the endpoint that the Rest Client interface actually maps to).
Retry of https://github.com/payara/Payara/pull/5514 following on from comments made on that (can't reopen original since I rebased onto latest master). I've now added a "blacklist" extension point using _ServiceLoader_ pattern to the usual flow of gathering the initializers from an "interest" list, allowing us to remove the dependency on MicroProfile from web-core.
None
New sample added that checks that an app with both actual endpoint and Rest Client interface bundled within it can deploy successfully.
Ran new sample.
Ran MicroProfile Rest …
=> FISH-26 Skip Init on Servlets Annotated with '@RegisterRestClient'

appserver/packager/microprofile-package/pom.xml, appserver/tests/payara-samples/pom.xml, pom.xml
This is a component upgrade PR of MicroProfile RestClient to v3.0
MicroProfile RestClient TCK 3.0
https://github.com/payara/patched-src-jersey/pull/112
https://github.com/payara/MicroProfile-TCK-Runners/pull/162
=> FISH-5868 Upgrade MicroProfile RestClient to 3.0

appserver/payara-appserver-modules/microprofile/healthcheck/src/main/java/fish/payara/microprofile/healthcheck/HealthCheckService.java
Web application with a class annotated by combination of MP Health and EJB:
```
@Readiness
@ApplicationScoped
```
Such application reports "No valid EE environment for injection of JdbcHealthCheck".
This PR adds WebComponentInvocation around the HealthCheck, so the EE environment is working. Annotation like Inject and EJB work reliably.
Periodically deploy testing app and try localhost:8080/health.
Tried on Linux, OpenJDK 8 and 11
Reproducer app attached to the JIRA ticket, including testing scripts.
=> FISH-5780 FISH-5779 create web component invocation around mp health check call

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/OpenAPIImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/tags/TagImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ApplicationProcessor.java, pom.xml
This is a component upgrade PR of MicroProfile OpenAPI to v3.0
MicroProfile OpenAPI TCK 3.0
`Tests run: 244, Failures: 0, Errors: 0, Skipped: 0`
MicroProfile OpenAPI Unit tests
`Tests run: 118, Failures: 0, Errors: 0, Skipped: 0`
https://github.com/payara/MicroProfile-TCK-Runners/pull/164
=> FISH-5866 MicroProfile OpenAPI version upgrade to 3.0 

nucleus/payara-modules/healthcheck-cpool/src/main/java/fish/payara/nucleus/healthcheck/cpool/ConnectionPoolHealthCheck.java
Title.
JDK 11 has a class named `Module`, so the wildcard import needs being made explicit. 
None.
None.
Compiled module on JDK 11.
N/A
None.
=> FISH-5914 Resolve Ambiguous Reference

nucleus/pom.xml
Title.
Make Enforcer plugin require JDK 11
None
None
Attempted to build with JDK 8 -> got warning and build exits.
Attempted to build with JDK 11 -> build starts.
Windows 11, Zulu JDK 8 & 11
N/A
None
=> FISH-5916 Update Enforcer Plugin

nucleus/payara-modules/nucleus-microprofile/config-service/src/test/java/fish/payara/nucleus/microprofile/config/source/DirConfigSourceTest.java
Test fix.
Windows by default doesn't allow symbolic links unless you're running as an admin user.
None
None
Compiled and ran test.
N/A
None
=> FISH-5918 FISH-1208 Fix DirConfigSourceTest on Windows (Payara6)

nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/StopInstanceCommand.java
A bug fix where using a custom node directory would result in `Node directory ... does not exist or is not a valid node directory` as it would always look at the default directory when executing `asadmin stop-local-instance` as part of the `asadmin stop-deployment-group` command.
Manually tested with reproducer on the ticket using: New node in custom directory, default node and New node in default directory.
None.
None.
=> FISH-5879 The 'stop-deployment-group --kill=true' command does not work with custom Node Directory

appserver/web/weld-integration/src/main/java/org/glassfish/weld/DeploymentImpl.java
Bug fix.
In certain situations applications would _sometimes_ fail to deploy due to a failure to validate the injection points of CDI Extensions (e.g. the RolesPermittedInterceptor).
This was eventually tracked down to whether certain bean managers were accessible to the extension, which was determined by the order in which they were resolved/loaded. This eventually led (all credit to @pdudits) to a discovery that the bean deployment archive graph was being created incorrectly.
None
None - tricky to reproduce and the reproducer we have is a customer app
Deployed and undeployed customer app > 20 times without error.
Windows 11, JDK 8
N/A
None.
=> FISH-5854 Error Related to the RolesPermittedInterceptor During Deployment

nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/schemadoc/AttributeMethodVisitor.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/schemadoc/DocClassVisitor.java, nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/AnnotationScanner.java, nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/NodeInfo.java, nucleus/flashlight/framework/src/main/java/org/glassfish/flashlight/impl/client/ProbeProviderClassFileTransformer.java, nucleus/flashlight/framework/src/main/java/org/glassfish/flashlight/impl/core/ProviderSubClassImplGenerator.java
When running an embedded EJB container via a testing framework, the EJBContainer.createEJBContainer method will fail with the following stack trace:
`java.lang.UnsupportedOperationException: Module requires ASM6
at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:145)
at org.objectweb.asm.ClassReader.readModuleAttributes(ClassReader.java:758)
at org.objectweb.asm.ClassReader.accept(ClassReader.java:557)
at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
at org.glassfish.deployment.common.GenericAnnotationDetector.scanArchive(GenericAnnotationDetector.java:146)
at org.glassfish.deployment.common.GenericAnnotationDetector.hasAnnotationInArchive(GenericAnnotationDetector.java:96)
at org.glassfish.ejb.embedded.EJBContainerProviderImpl.getRequestedEJBModuleOrLibrary(EJBCo …
=> FISH-394 Upgrade ASM Opcodes

appserver/extras/docker-images/pom.xml
Removes JDK 8 build of Docker images.
Building of Docker images seems to be broken on the Payara6 branch - not broken by this change.
The build of Docker images is fixed by the master merge PR: https://github.com/payara/Payara/pull/5475
None
Built Docker image.
Windows 11
N/A
None
=> FISH-5935 Remove JDK 8 Docker build

appserver/ejb/ejb-container/osgi.bundle, appserver/ejb/ejb-container/pom.xml, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/StaticRmiStubGenerator.java, appserver/packager/glassfish-corba-base/pom.xml, appserver/packager/glassfish-corba/pom.xml, nucleus/packager/nucleus-corba-base/pom.xml, nucleus/pom.xml
Removes more sun packages which JDK 11 doesn't like.
None
None
Compiled server on JDK 11 - no complaints.
N/A
None
=> FISH-5956 Replace 'sun.rmi.rmic' with 'org.glassfish.rmic'

appserver/payara-appserver-modules/microprofile/metrics/pom.xml
microprofile-metrics uses jaxb2-maven-plugin - only version 2.5.0 is JDK11 compatible.
None
None
Compiled module on JDK 11. Ran microprofile-metrics module unit tests.
Windows 10, JDK 11, Maven 3.6.3
None.
None.
=> FISH-5920 Update MicroProfile Metrics Schemagen for JDK 11

nucleus/common/common-util/src/main/java/com/sun/enterprise/security/store/AsadminSecurityUtil.java
Recreating truststore file when corrupted
this is a fix of a reported issue when reading a corrupted truststore for secure administration
Local testing by using a blank truststore file to simulate corrupted file
Windows 11,  zulu JDK 8U312
=> FISH-5892: recreating truststore file when corrupted

appserver/security/jacc.provider.file/src/main/java/com/sun/enterprise/security/provider/PolicyConfigurationImpl.java
TCK tests occasionally have problems with accessing granted.policy file. This change fixes it.
TCK ejb30/lite/packaging executed many times without the issue reoccurring.
Linux, JDK 8 and 11
=> Fish 5672 tck policy files doprivileged

.github/CONTRIBUTING.md, appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/UtilHandlers.java, appserver/admingui/common/src/main/resources/shared/sslAttrs.inc, appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/AppClientFacade.java, appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/CLIBootstrap.java, appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/jws/JavaWebStartInfo.java, appserver/common/glassfish-ee-api/src/main/java/com/sun/appserv/ClassLoaderUtil.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/StaticRmiStubGenerator.java, appserver/packager/appserver-base/src/main/docs/README.txt, appserver/packager/glassfish-web/pom.xml, appserver/persistence/cmp/enhancer/src/main/java/com/sun/jdo/api/persistence/enhancer/URLClassPath.java, appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java, appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/monitoring/WebServiceTesterServlet.java, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/AdminMain.java, nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/JavaConfig.java, nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/JavaConfig.java, nucleus/admin/launcher/src/test/java/com/sun/enterprise/admin/launcher/JavaConfigTest.java, nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/HttpConnectorAddress.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/util/JDK.java, nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/MainHelper.java, nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/Util.java, nucleus/packager/nucleus-grizzly/pom.xml
Removes the various checks of JDK 8 vs. 9, along with other references to support for JDK 8
None - but related to https://github.com/payara/Payara/pull/5567
None
Compiled server on JDK 11.
Attempted to start on JDK 8 - expected error.
Server starts on JDK 11.
TLS 1.3 shown as an available option in admin console.
Windows 11, Zulu JDK 11 (and 8)
N/A - no Payara6 branch yet
You'll need to pull in the Payara 6 branch (and optionally PR 5567) for the server to compile.
=> FISH-5923 Remove JDK 8 vs. 9 checks

appserver/admin/gf_template/src/main/resources/config/domain.xml, appserver/admin/gf_template_web/src/main/resources/config/domain.xml, appserver/admin/production_domain_template/src/main/resources/config/domain.xml, appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml, appserver/extras/embedded/all/src/main/resources/config/domain.xml, appserver/extras/embedded/web/src/main/resources/config/domain.xml, nucleus/admin/template/src/main/resources/config/domain.xml
Removes redundant JVM options around JDK versions that are not supported. Removed the JDK 9+ requirement from others as base JDK is now 11.
None
Built Payara module.
Maven 3.6.3 JDK 11 Windows 10
None
None
=> FISH-5924 Remove Redundant JVM Options from Domain Config

appserver/distributions/distributions.xml, appserver/distributions/payara-ml/pom.xml, appserver/distributions/payara-web-ml/pom.xml, appserver/distributions/payara-web/pom.xml, appserver/distributions/payara/pom.xml, appserver/packager/appserver-base/src/main/resources/config/branding/glassfish-version.properties, nucleus/common/common-util/src/main/java/com/sun/appserv/server/util/Version.java
Missed sync from Enterprise. Allows easier determination of distribution type.
None
None
Built server (non-quickbuild) - each distribution has the correct type in glassfish-version.properties.
WSL,  JDK 8.
N/A
Port from Enterprise.
=>  FISH-981 Add Distribution Type to glassfish-version.properties (Payara6)

appserver/payara-appserver-modules/microprofile/healthcheck/src/main/java/fish/payara/microprofile/healthcheck/HealthCheckService.java
Every webapp with healthcheck is periodically called every 12 seconds. This call may come when the application is not ready such as mid-deployment. This stops HealthCheck calls on apps which aren't ready.
None.
None
Manually tested the warnings outputted to the server logs no longer appear with the reproducer attached.
Windows 10, JDK 11, Maven 3.6.3
None
FISH-5937 ticket mentions other errors, these are caused by stopping and starting the server as the reproducer says. These are not HealthCheck related and are not related to this ticket and fix.
=> FISH-5937 Crashes during deploy of app with HealthCheck

appserver/web/gf-weld-connector/src/main/java/org/glassfish/weld/connector/WeldUtils.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/InjectionServicesImpl.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/JCDIServiceImpl.java
Fixes https://github.com/payara/Payara/issues/5530
Deployment of testcase finished in 5 seconds.
=> 5530 improve cdi scan

appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/embedded/DomainXmlTransformer.java
TCK tests reveal a recent file change has broken the Embedded EJB Container, specifically in DomainXmlTransformer when it tries to find its logger.
```
jakarta.ejb.EJBException: Caught unexpected exception trying to create a temporary domain.xml file.
...
Caused by: java.util.MissingResourceException: Can't find com.sun.logging.enterprise.system.container.ejb.LogStrings bundle from
```
The log file name was changed in a recent PR to fix another error, and so this fixes the new error by having it point to the moved file.
None
None
Ran ejb30/lite/packaging/ TCK
WSL, JDK 8
N/A
PR which changed file name here: https://github.com/payara/Payara/pull/5579
=> FISH-5857 Fix Error Starting Embedded EJB Container

appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/embedded/DomainXmlTransformer.java
TCK tests reveal a recent file change has broken the Embedded EJB Container, specifically in DomainXmlTransformer when it tries to find its logger.
```
jakarta.ejb.EJBException: Caught unexpected exception trying to create a temporary domain.xml file.
...
Caused by: java.util.MissingResourceException: Can't find com.sun.logging.enterprise.system.container.ejb.LogStrings bundle from
```
The log file name was changed in a recent PR to fix another error, and so this fixes the new error by having it point to the moved file.
None
None
Ran ejb30/lite/packaging TCK locally
WSL, JDK 11
N/A
PR which changed file name here: https://github.com/payara/Payara/pull/5580
=> FISH-5857 FISH-5982 Fix Error Starting Embedded EJB Container (Payara6)

nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/Parser.java, nucleus/admin/cli/src/test/java/com/sun/enterprise/admin/cli/ParserTest.java, nucleus/core/bootstrap/src/main/java/fish/payara/boot/runtime/BootCommands.java, nucleus/core/bootstrap/src/test/java/fish/payara/boot/runtime/BootCommandsTest.java
A bug fix where putting double quotes in a command stored in a preboot-command file would result in `UnacceptableValueException: Invalid parameter: name_value.  This parameter may not have more than one value.` 
None
No new tests. Added this scenario to existing tests
Manually tested against the reproducer and values from unit test in regex101.
Documentation PR: https://github.com/payara/Payara-Community-Documentation/pull/288
The new regex works by using a positive lookahead to check the current character is not a double or single quote preceded by a backslash, which checked by using a nested negative lookbehind.
This regex can be seen and tested in regex101 here: https://regex101.com/r/2aVRtd/1
=> FISH-5974 Specify system-property with Double Quotes in preboot-command File

nucleus/admin/config-api/src/main/java/org/glassfish/config/support/TranslatedConfigView.java, nucleus/admin/config-api/src/test/java/org/glassfish/config/support/TranslatedValueTest.java
Strings with multiple default values in the DataSourceDefinition URL would change the entire string to the first default found if no value was found via env properties or mp-config properties.
resolves https://github.com/payara/Payara/issues/5322
N/A
Created test that uses multiple env properties with defaults
Tested reproducer
openjdk version "11.0.11" 2021-04-20 LTS
Apache Maven 3.6.3
ubuntu 20.04
N/A
=> FISH-5676 Apply Default Values in @DataSourceDefinition URL via Variable Expansion

nucleus/admin/config-api/src/main/java/org/glassfish/config/support/TranslatedConfigView.java, nucleus/admin/config-api/src/test/java/org/glassfish/config/support/TranslatedValueTest.java
Strings with multiple default values in the DataSourceDefinition URL would change the entire string to the first default found if no value was found via env properties or mp-config properties.
resolves https://github.com/payara/Payara/issues/5322
N/A
Created test that uses multiple env properties with defaults
Tested reproducer
openjdk version "11.0.11" 2021-04-20 LTS
Apache Maven 3.6.3
ubuntu 20.04
N/A
=> FISH-5676 Apply Default Values in @DataSourceDefinition URL via Variable Expansion - P6

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/GenerateBashAutoCompletionCommand.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/LocalStrings.properties
Added option to generate-bash-autocomplete command to include local commands
This option is disabled by default
N/A
N/A
Built Payara, Started server and executed command with localCommands option set to true
Apache Maven 3.6.3
Ubuntu 20.04
openjdk version "1.8.0_302"
https://github.com/payara/Payara-Community-Documentation/pull/293
I got inspiration from https://github.com/payara/Payara/blob/cf883d86b7583761e6dd35f9aa7ee4317a412f9c/nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/AdminMain.java#L262 in order to get the Local Commands. I was unable to Inject the CLIContainer to use the CLIUtil.getLocalCommands Method.
=> FISH-5803 Added local commands option to generate-bash-autocomplete

appserver/concurrent/concurrent-impl/pom.xml, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/cdi/ConcurrentCDIExtension.java, appserver/concurrent/concurrent-impl/src/main/resources/META-INF/services/jakarta.enterprise.inject.spi.Extension, pom.xml
Add implementation of Asynchronous annotation, runs method in the provided (or default) ManagedExecutionService, checks required return type, Transactional values and the result returned from JNDI.
Unimplemented ContextServiceDefinition annotation and thread context switching causes the TCK tests fail. Once implemented, the related tests should succeed. 
As all of these PRs, we use our implementation of RI 3.0 - https://github.com/aubi/concurrency-ri/tree/jakartaee10 
They can be tested via tck-suite.xml:
`<package name="ee.jakarta.tck.concurrent.spec.ManagedExecutorService.resourcedef.*"/>`
I'll attach a simple app to try.
=> Fish 5963 concurrency add @Asynchronous

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebContainer.java, appserver/web/web-naming/src/main/java/org/apache/naming/resources/FileDirContext.java, nucleus/common/internal-api/src/main/java/org/glassfish/internal/deployment/Deployment.java, nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/DeployCommand.java
Whenever an application that is being used as the default web module of a virtual server gets redeployed, the virtual server will stop working and not correctly process requests sent to it.
N/A
N/A
The server must be tested remotely as the error will only trigger when accessing the virtual server through its hostname. A suggested environment to test this is AWS.
It can be tested locally by changing the domain URL from "localhost" to your local hostname.
Built Payara, Start server, deploy apps, setup default web module on a virtual server, redeploy the application
Windows 11, RHEL8.4.0, JDK8, Maven 3.8.4
None
=> FISH-5939 Application Redeployment Breaks virtual server When Using it as Default Module

appserver/admingui/cluster/src/main/resources/org/glassfish/cluster/admingui/Strings.properties
An improvement to the DockerInstallDirHelp label, changing the label so this is clear the Installation Directory should be left as the default unless using a custom Docker image.
None
None
Built the server, updated label is shown in the admin console for DOCKER Node Types.
Windows 10, JDK 11, Maven 3.6.3
The documentation surrounding this is already correct
None
=> FISH-5927 Document --installdir Command and Installation Directory for Docker Nodes

nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/custom/NotificationLogViewer.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java, nucleus/core/logging/src/main/java/fish/payara/enterprise/server/logging/PayaraNotificationFileHandler.java
Bug fixed the Payara notification logging service configuration 
N/A
N/A
Start the server and configure the Notification Service to use a separate log file and update any of the Payara Notification Logging Service logger settings
Windows 11, JDK 8
N/A
N/A
=> FISH-6043 Configuring Payara Notification Logging Service causes NullPointerException

nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/custom/NotificationLogViewer.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java, nucleus/core/logging/src/main/java/fish/payara/enterprise/server/logging/PayaraNotificationFileHandler.java
Bug fixed the Payara notification logging service configuration by fixing incorrect logger name of LoggerNotifier
N/A
N/A
Start the server and configure the Notification Service to use a separate log file and update any of the Payara Notification Logging Service logger settings
N/A
N/A
=> FISH-6043 Configuring Payara Notification Logging Service causes NullPointerException (P6)

appserver/extras/docker-images/pom.xml
Update the Docker image JDK versions from 11.0.13 to 11.0.14.1.
None
None
None
WSL
N/A
None
=> FISH-6046 Update Docker JDK version

appserver/extras/docker-images/pom.xml
Update the Docker image JDK versions from 11.0.13 & 8u312 to 11.0.14.1 & 8u322 respectively.
None
None
Built images - tests passed
Started payara/server-full image - no errors
Started payara/micro - no errors
WSL
N/A
None
=> FISH-6046 Update Docker Image JDK versions

appserver/deployment/schemas/src/main/resources/glassfish/lib/schemas/application-client_10.xsd, appserver/deployment/schemas/src/main/resources/glassfish/lib/schemas/application_10.xsd, appserver/deployment/schemas/src/main/resources/glassfish/lib/schemas/beans_4_0.xsd, appserver/deployment/schemas/src/main/resources/glassfish/lib/schemas/jakartaee_10.xsd, appserver/deployment/schemas/src/main/resources/glassfish/lib/schemas/orm_3_1.xsd, appserver/deployment/schemas/src/main/resources/glassfish/lib/schemas/permissions_10.xsd, appserver/deployment/schemas/src/main/resources/glassfish/lib/schemas/wsdl_customizationschema_3_0.xsd
Added Jakarta EE 10 deployment descriptor's schemas including the dependant namespace from [Jakarta EE page](https://jakarta.ee/xml/ns/jakartaee/#10)
N/A
Build and run Payara Platform
N/A
N/A
=> FISH-6086 Add Jakarta EE 10 schemas (P6)

appserver/admin/gf_template/src/main/resources/config/domain.xml, appserver/admin/gf_template_web/src/main/resources/config/domain.xml, appserver/admin/production_domain_template/src/main/resources/config/domain.xml, appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml, appserver/extras/payara-micro/payara-micro-distribution/build.xml
Bug fix where creating a new DnsContextFactory would result in IllegalAccessException on JDK17
None
None
Manually tested the changes with creating a new DnsContextFactory in sample application and deploying it to Payara - Checked the logs for no IllegalAccessException
Also tested on Payara Cloud DeploymentReplayIT with JDK 17 and this now passed.
JDK 17, Maven 3.6.3, Windows 10
None
If testing on Payara Cloud, you need to increment the Payara Community version to 5.2022.2-SNAPSHOT and when running mvn clean install and mvn clean verify add the profile -Pcommunity as there is no JDK 17 support on Payara Enterprise yet.
=> FISH-5990 Make DnsContextFactory JNDI DirContext instantiable on JDK 17

appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/GlassFishORBManager.java, appserver/tests/payara-samples/pom.xml, appserver/tests/payara-samples/samples/remote-ejb-tracing/pom.xml, pom.xml
These changes do not fix remote EJBs on JDK 17 directly, the suggested fix for this is to specify `--add-opens=java.base/java.lang=ALL-UNNAMED` to the invoking command as short of refactoring the IllegalReflectiveAccess there is no fix to this (See JIRA for more information)
These changes instead specify this --add-opens to the remote-ejb-tracing sample which I identified is also broken due to this error.
These changes also add the parameter `-Dorg.glassfish.gmbal.no.multipleUpperBoundsException=true` to the GlassFishORBManager meaning it doesn't need to be specified by the client. This issue is explained here: https://github.com/eclipse-ee4j/orb-gmbal/issues/22
None
None
Manually tested the fix against the reproducer in the community bug, my own reproducer and the remote-ejb-tracing …
=> FISH 6027 - Remote EJB + JDK 17 does not work

appserver/payara-appserver-modules/rest-monitoring/rest-monitoring-war/pom.xml, appserver/tests/payara-samples/samples/concurrency/pom.xml, pom.xml
Upgrading concurrency dependencies
this is to upgrade concurrency dependencies for 3.0 and be included on the web-profile
The 10.0.0-SNAPSHOT version is temporal and should be upgraded when the release of the jakarta 10 is done. For now this can be tested by building the last version of the jakarta api project here: https://github.com/eclipse-ee4j/jakartaee-api
Tested with a sample Web application with the jakarta.jakartaee-web-api dependency with provided scope into the payara-web distribution
Windows 11, Azul JDK 11
=> FISH-5964: upgrading jakartaee-web-api for server

appserver/extras/docker-images/pom.xml
Adds JDK 17 build of Docker images
None
None
Built JDK 17 docker image
Windows 10, JDK 17, Maven 3.6.3
N/A
None
=> FISH-5942 Create JDK17 based Docker Image

pom.xml
Increment Jackson to 2.13.1 because of CVE: https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2326698
Addresses Community Issue: https://github.com/payara/Payara/issues/5641
None
Started the server on JDK 11 and 17 - No warnings, failures or compilation failures.
Windows 10, Maven 3.6.3, Zulu JDK 11 & 17
None
None
=> FISH-6092 Upgrade Jackson to 2.13.1

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployment/annotation/handlers/ManagedThreadFactoryDefinitionHandler.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/ManagedThreadFactoryDefinitionDescriptor.java, nucleus/common/common-util/src/main/java/org/glassfish/common/util/OSGiObjectInputOutputStreamFactoryImpl.java
Adding change to set classloader and fix IllegalArgumentException when classloader is null
this is a fix of some issues when the classloader is null
execution of the concurrency tck
Windows 11, Azul jdk 11
=> FISH-6102: fixing null classloader and returning normal thread priority

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ConcurrentRuntime.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ContextServiceConfig.java, pom.xml
```
@ContextServiceDefinition(name = "java:app/concurrent/ContextA",
propagated = { APPLICATION, IntContext.NAME },
cleared = StringContext.NAME,
unchanged = TRANSACTION)
```
Note the `unchanged = TRANSACTION` -- the transaction is now unchanged.
Failing tests in package `ee.jakarta.tck.concurrent.spec.ContextService.contextPropagate.*` decreased from 9 to 6.
Linux, OpenJDK
Requires current version of concurrencty-ri, branch jakarta10: https://github.com/aubi/concurrency-ri/commit/7ce79fde06a97cdd6f788b6309cae5585b577930
I accidentally moved the payara6-concurrency-3.0-upgrade branch, so this diff doesn't include the main commit of this PR:
https://github.com/aubi/Payara/commit/65f0fd6e9e20f8fa9edab12d050ef5a96297ba26
=> FISH-5968 leave transaction intact if mentioned in unchanged parameter

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ConcurrentRuntime.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/TransactionSetupProviderImpl.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/deployment/annotation/handlers/ContextServiceDefinitionHandler.java
Fix transaction suspend in contextual call - if ContextServiceDefinition.cleared contains TRANSACTION, suspend the current transaction on a contextual call.
Keep ALL_REMAINING in the lists of contexts and then add there the custom providers.
TCK: from 9 passed and 6 failing we have got  to 12 passed and 4 failing.
It is necessary to update to up-to-date our RI.
=> Fish 6204 Improve Implementation of Context Switching

appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
FISH-6208 Deprecate and change WebAppClassLoader#getResources to return null for CVE-2022-22965 (Enterprise)
Credit to https://github.com/apache/tomcat/commit/530108cb568ba7bb51594d0ecfc2421db2e4bf53
Unsure how to attribute Re: copyright
None
None
None
To Do
To Do
To Do
To Do
None
=> FISH-6208 Deprecate and change WebAppClassLoader#getResources to return null for CVE-2022-22965

appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
FISH-6208 Deprecate and change WebAppClassLoader#getResources to return null for CVE-2022-22965 (Enterprise)
Credit to https://github.com/apache/tomcat/commit/530108cb568ba7bb51594d0ecfc2421db2e4bf53
Unsure how to attribute Re: copyright
None
None
None
To Do
To Do
To Do
To Do
None
=> FISH-6208 Deprecate and change WebAppClassLoader#getResources to return null for CVE-2022-22965 (Payara6)

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ManagedScheduledExecutorDefinitionDeployer.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ManagedThreadFactoryDescriptorDeployer.java
Adding deploy methods and reordering
This is a fix to add missed deploy methods and reordering the calls between them
the tck execution
Windows 10, Azul JDK 11
=> FISH-6216: adding missed deploy methods and reordering

nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/APIClassLoaderServiceImpl.java, nucleus/osgi-platforms/felix/src/main/resources/config/osgi.properties
This puts `${domainDir{/lib/ext/*` onto system classpath (argument `-cp` to launched server process). System classloader is then used as base for both Felix OSGi runtime, as well as application's API Classloader.
It was verified that this change doesn't alter the set of classes accessible to applications, anything on system classpath (glassfish.jar and its dependencies resolved via `Class-Path` manifest attribute) are already available over API Classloader, because it allows loading much more than just API classes.
Alternative solution to #5694, includes #5649.
Classpath is only extended when system property `java.ext.dirs` is not defined, which is true on any JDK >= 9 as that would cause fatal JVM error.
* Reproducer for FISH-5946 against Oracle 12.
* Verified that cp is not altered for …
=> FISH-5955 FISH-5948 Support for lib/ext for Java 9+

appserver/tests/payara-samples/samples/grpc-ejb/pom.xml, appserver/tests/payara-samples/samples/grpc/pom.xml, appserver/tests/payara-samples/samples/grpc/src/main/java/fish/payara/samples/grpc/CdiBean.java, appserver/tests/payara-samples/samples/grpc/src/main/java/fish/payara/samples/grpc/ClashingServlet.java, appserver/tests/payara-samples/samples/grpc/src/main/java/fish/payara/samples/grpc/PayaraService.java, appserver/tests/payara-samples/samples/grpc/src/main/proto/payara.proto, appserver/tests/payara-samples/samples/grpc/src/test/java/fish/payara/samples/grpc/GrpcClient.java, appserver/tests/payara-samples/samples/grpc/src/test/java/fish/payara/samples/grpc/GrpcTest.java, appserver/tests/payara-samples/samples/grpc/src/test/resources/glassfish-web.xml, appserver/tests/payara-samples/samples/pom.xml, appserver/tests/pom.xml
Sample added to the master branch of Payara, and updated to run as an automatic sample.
None
None
1. Start local Payara
.\appserver\distributions\payara\target\stage\payara5\bin\asadmin start-domain --verbose
2. Build Payara Samples
../Payara/appserver/tests/payara-samples$ mvn clean install -DskipTests
3. Install Test Domain Setup
../Payara/appserver/tests/payara-samples/test-domain-setup$ mvn clean install -Ppayara-server-remote
4. Verify grpc
../Payara/appserver/tests/payara-samples/samples/grpc$ mvn verify -Ppayara-server-remote
Zulu JDK 1.8_212 on Ubuntu 20.04 with Maven 3.8.4
=> FISH-6068 Add gRPC Sample to the Payara 'master' Branch

pom.xml
Upgrading `jakarta.validation:jakarta.validation-api` to 3.0.1 to support Jakartaee 10
N/A
build and run Payara server
Windows 11, OpenJDK11, Maven 3.6.3
None
None
=> FISH-6200 Update jakarta validation to 3.0.1

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ManagedExecutorDescriptorDeployer.java
The pool doesn't start any task with default core pool size = 0
Setting core to max makes the MES behaving correctly.
Fixes 3 Concurrency TCK failures.
Linux, OpenJDK
=> FISH-6216 set core pool size in managedexecutorservice to same value as max

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ConcurrentRuntime.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ManagedScheduledExecutorDefinitionDeployer.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ManagedThreadFactoryDescriptorDeployer.java
Correct storage in JDNI for managed thread factory and scheduled executor, which missed the correct behavior
Current tests (with fixes in RI and TCK) results:
Tests run: 172, Failures: 23, Errors: 0, Skipped: 14
Linux, OpenJDK
=> FISH-6216 implement jndi storage for managed thread factory and scheduled executor

appserver/common/container-common/src/main/java/org/glassfish/javaee/services/CommonResourceProxy.java, appserver/common/container-common/src/main/java/org/glassfish/javaee/services/JndiLookupNotifier.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ConcurrentRuntime.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployment/annotation/handlers/ContextServiceDefinitionHandler.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployment/annotation/handlers/ContextServiceDefinitionListHandler.java
Implement thread context saving on jndi lookup for ManagedThreadFactory as required by  TCK test.
We also open discussion to interpret spec, that context saving should happen on process thread -- if succeeded, it will be necessary to revert this commit.
All TCKs tests in ee.jakarta.tck.concurrent.spec.ManagedThreadFactory.resourcedef.* now pass.
Linux, OpenJDK
Other part of the changes is in our Concurrency RI fork, branch jakartaee10.
=> Fish 6216 managedthreadfactory jndi lookup

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/EJBUtils.java
Fix for linkagerror when getting interface classloader
this is a fix of the linkageerror getting when executing Concurrency TCK
This changes were tested by executing the Concurrency TCK. After executing now we have the following issues:
[ERROR] Tests run: 160, Failures: 16, Errors: 0, Skipped: 0
Windows 10, Azul JDK 11
=> FISH-6216: fix for linkagerror when getting interface classloader

.github/ISSUE_TEMPLATE/bug-report.md, .github/PULL_REQUEST_TEMPLATE.md, appserver/tests/payara-samples/README.md
Updates some files for JDK 11 being the minimum version.
None
Documentation is on this branch: [FISH-5926 Payara 6 documentation for JDK 11 · JamesHillyard/Payara-Community-Documentation@94b08b2](https://github.com/JamesHillyard/Payara-Community-Documentation/commit/94b08b2ac60dfda3fad0df6e832025e880b2d2f1) which when approved will be a new `Payara6` branch on the Community documentation repo.
None
=> FISH-5926 Update Documentation Around Java 11

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/InvocationManagerImpl.java
Fixes handling of standard contexts (Security, Application) when not specified (e.g. when loading from xml file). They are configured to the context given by Remaining. If Remaining is not specified, they go to propagated.
Edit: REVERTED - This change stops inheriting JNDI contexts from calling thread when creating new thread from ManagedExecutorService.
Currently it decreased number of failing tests from 16 to 11.
Linux, OpenJDK
Requires current version of wip-payara Referential implementation.
=> Fish 6216 Fix unspecified standard contexts, move the to Remaining

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/ContextServiceDefinitionDescriptor.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/node/ContextServiceDefinitionNode.java
Adds methods to load properly context sets from application.xml.
Last change in Payara sources, all TCK tests run (except broken ones, properly excluded in runner).
Linux, OpenJDK
Needs update all RI (another changes), API/RI (includes fixes before we properly do the TCK test challenges and exclude them from runner), Runner (few excluded tests).
=> FISH-6216 support context service definition context sets in xml

appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/ACCClassLoader.java
Ran Quicklook on JDK 8, 11 and 17
Stacktrace is now the following
[testng] ERROR>OpenJDK 64-Bit Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "org.glassfish.appclient.client.acc.agent.ACCAgentClassLoader"). To use archived non-system classes, this property must not be set
[testng] ERROR>May 04, 2022 4:07:48 PM org.glassfish.enterprise.iiop.api.GlassFishORBHelper postConstruct
[testng] ERROR>INFO: GlassFishORBFactory service initialized.
[testng] ERROR>com.sun.enterprise.container.common.spi.util.InjectionException: Exception attempting to inject Unresolved Message-Destination-Ref MsgBeanQueue@java.lang.String@null into class com.sun.mdb.client.Client: Lookup failed for 'java:comp/env/MsgBeanQueue' in …
=> FISH-6260 Fix NoSuchField exception

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ConcurrentRuntime.java, appserver/packager/external/jakarta-ee9-shim/pom.xml, pom.xml
Mainly reverted the behavior with storing thread context in ManagedThreadFactory during jndi lookup, it is stored at the beginning of newThread() as it always did. The TCK test will be challenged.
Other changes just fix running in current Payara6 branch.
TCKs, failing tests:
**ee.jakarta.tck.concurrent.spec.ManagedThreadFactory.resourcedef.ManagedThreadFactoryDefinitionTests**
* testManagedThreadFactoryDefinitionAllAttributes
* testManagedThreadFactoryDefinitionAllAttributesEJB
* testParallelStreamBackedByManagedThreadFactory
* testParallelStreamBackedByManagedThreadFactoryEJB
**ee.jakarta.tck.concurrent.spec.Platform.dd.DeploymentDescriptorTests**
* testDeploymentDescriptorDefinesManagedThreadFactory
=> Fish 6287 fix ManagedThreadFactory's saving context, around newThread()

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModule.java, appserver/web/web-glue/src/main/java/fish/payara/web/WebModuleValve.java, appserver/web/web-glue/src/main/java/org/glassfish/web/LogFacade.java
Reimplements most of the functionality the `J2EEInstanceListener` class used to, namely:
* Creating a `WebComponentInvocation` for the request
* Creating a transaction around the request in the `JavaEETransactionManager` and clearing up after it has been serviced
* Setting the `AppServSecurityContext` with the `Principal` obtained from the `Request` and clearing up after it has been serviced
Potentially important reimplementation details:
* As a `Valve` instead of an `InstanceListener`, we're no longer doing all of the above for each "sub-invocation" of the request (before & after each `Filter#doFilter`, before & after each `Servlet#service`, etc.).
* I've dropped the check for the `getUnwrappedCoyoteRequest` if the `Request` is a subclass of `RequestFacade`. I didn't find any case where …
=> FISH-6310 Reimplement J2EEInstanceListener as a Valve

appserver/packager/external/h2db/pom.xml, pom.xml
Upgrade the H2 to 2.1.212 version. Repackage module in Payara requires a patched binary with zip file of H2, so I also have uploaded h2db 2.1.212 to [payara-artifact](https://nexus.payara.fish/#browse/browse:payara-artifacts)
N/A
None
Build and run Payara Server
N/A
None
=> FISH-6110 Upgrade to latest H2 version (P6)

pom.xml
Feature, upgrading the `jakarta-transaction`.
None
None
Build and Run Payara
N/A
`jakarta-interceptor 2.1` is already included on the shim that was already merged by @aubi, to avoid OSGi issue since `jakarta-transaction 2.0.1` requires `jakarta-interceptor 2.1`
=> FISH-6199 Upgrade Transaction to 2.0.1 (Wave 4)

pom.xml
This PR upgrades Exousia to 2.1.0-M2 and depends on the following PRs:
[WASP version upgrade to 3.1.0-M4](https://github.com/payara/Payara/pull/5748)
[Jakarta Standard Tag Library version upgrade to 3.0](https://github.com/payara/Payara/pull/5756)
[Jakarta Authorization 2.1 TCK Runner](https://github.com/aubi/jakartaee-10-tck-runners/pull/3)
````
Completed running 34 tests.
Number of Tests Passed      = 34
Number of Tests Failed      = 0
Number of Tests with Errors = 0
````
=> FISH-6007 Upgrade Exousia to 2.1.0-M2

pom.xml
JBatch implementation upgrade to the latest version, API remains on the latest 2.1.0.
JBatch TCK 2.1.0 is testing only JBatch 2.1.0, so we will have to wait until platform TCK, which will test everything.
QuickLook tests are OK.
=> FISH 6082: upgrade jbatch to 2.1.1

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebContainer.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModule.java, appserver/web/web-glue/src/main/java/fish/payara/web/WebModuleGlueUtil.java, appserver/web/web-glue/src/main/java/fish/payara/web/WebModuleInstanceManager.java, appserver/web/web-glue/src/main/java/fish/payara/web/WebModuleValve.java
Adds an implementation of the Tomcat Catalina `InstanceManager` to use instead of the `DefaultInstanceManager`, the intent being that we want to retain integration with the Payara `InjectionManager` and `InvocationManager`.
None.
None
Branch doesn't compile so none.
N/A
N/A
Without the ability to debug it I'm a bit unsure of the behaviour to take with the `newInstance(Object object)` method - when the object has already been instantiated outside of the instance manager. I took inspiration from how the `InjectionManagerimpl#createManagedObject(Object object)` method works when it's not creating a managed bean via `ManagedBeanManagerImpl` and instead creating one via simple `clazz.getConstructor().newInstance()`.
=> FISH-6309 InstanceManager Implementation

nucleus/packager/nucleus-osgi/pom.xml, nucleus/pom.xml
Upgrades Felix to 7.0.4 and its subprojects to the latest versions too.
Needs release of fileinstall 3.7.4.payara-p1 - done: https://nexus.payara.fish/#browse/browse:payara-artifacts:org%2Fapache%2Ffelix%2Forg.apache.felix.fileinstall%2F3.7.4.payara-p1
None
Compiled server, started server, loaded admin console - no explosions.
Windows 10, Zulu JDK 11
N/A
None
=> FISH-5750 FISH-6283 Upgrade Felix

api/payara-bom/pom.xml, appserver/packager/external/jakarta-ee9-shim/pom.xml, appserver/packager/metro/pom.xml, appserver/tests/quicklook/wsit/JaxwsFromWsdl/build.xml, appserver/tests/quicklook/wsit/jsr109tester/build.xml, appserver/webservices/jsr109-impl/src/test/java/org/glassfish/webservices/JAXWSAdapterRegistryTest.java, appserver/webservices/soap-tcp/src/main/java/org/glassfish/webservices/transport/tcp/ServletFakeArtifactSet.java, pom.xml
Metro upgraded to 4.0.0-M4.
It was necessary to add apache santuario as well.
JAXB TCK passed, "SAAJ Compatibility Test Suite Version 1.4"
Also a simple WS application was tested.
=> FISH-6064 FISH-6321 Upgrade Metro to 4.0.0-M4 & EclipseLink to 4.0.0-M3.payara-p1

api/payara-bom/pom.xml
Remove testng dependency from concurrent-api in Payara. It was obviously let in compile scope by mistake.
=> add exclusion of testng from concurrent-api

appserver/payara-appserver-modules/microprofile/fault-tolerance/pom.xml, appserver/payara-appserver-modules/microprofile/fault-tolerance/src/test/java/fish/payara/microprofile/faulttolerance/policy/BulkheadMetricTckTest.java, appserver/tests/payara-samples/samples/concurrency/src/test/java/fish/payara/sample/concurrency/annotations/managedscheduledexecutor/ManagedScheduledExecutorRestIT.java
Microprofile Fault Tolerance tests rely on exact time measuring, which occasionally fail during build on cloud machines. These changes
* calculate preparation time and add this time to tolerated time error
* repeat the time-sensitive tests 3 times, so they can pass without repeating whole huge build+testing.
Tested with artificial delays, runs very reliably
OpenJDK, Linux
=> Stabilize MP FT tests

appserver/admingui/core/src/main/resources/org/glassfish/admingui/core/Strings.properties, appserver/admingui/payara-theme/src/main/resources/branding/masthead.inc
The "Enable Asadmin Recorder" button is not visible in the header of the Admin Console
None
None
1. mvn clean install -DskipTests
2. ./appserver/distributions/payara/target/stage/payara6/bin/asadmin start-domain
3. Open localhost:4848 in a web browser
4. Check if the button appears
Zulu JDK 11 on Ubuntu 18.04 with Maven 3.8.4
=> Fish 6301 "Enable Asadmin Recorder" button is not visible

pom.xml
this is a temporary until parsson next release
This is a fix, to be able to pass JSONP signature test TCK, it needs to use final release of `jakarta.json-api:2.1.0` at the other hand `org.eclipse.parrson:jakarta.json:1.1.0` has not use it yet. So that, this is as midterm solution to use patched version of `org.eclipse.parrson` till [parsson](https://github.com/eclipse-ee4j/parsson) next release to fix and use final release on `jakarta.json-api:2.1.0`
I've uploaded parsson patched version to [payara-artifacts](https://nexus.payara.fish/#browse/browse:payara-artifacts:org%2Feclipse%2Fparsson) as well
N/A
none
Build and run payara server
Ubuntu 20.04.4 LTS, OpenJDK11, Maven 3.6.3
None
None
=> FISH-6343 Change Parsson to Patched Version

appserver/extras/docker-images/tests/src/test/java/fish/payara/distributions/docker/PayaraServerNodeTest.java
This image frequently times out due to it having to do more on boot than other images, and this isn't intended to be a performance test
None
None
Ran the tests - they didn't time out
Windows 10
N/A
None
=> Loosen Docker payara/server-node Image Test Timing.

appserver/admingui/common/src/main/resources/js/adminjsf.js
When the Collect Logs button is clicked, it redirects to a page that doesn’t have the general admin console branding. Even if the Collect Logs button is clicked on the redirected page, nothing happens, and the domain logs are not collected. 
None
None
1. mvn clean install -DskipTests
2. ./appserver/distributions/payara/target/stage/payara6/bin/asadmin start-domain
3. Open: localhost:4848
4. Click on Domain in the tree on the left
5. Choose Tab: Domain Logs
6. Click on "Collect Logs" button
7. The download should happens
8. Check if the zip file is correct.
Zulu JDK 11 on Ubuntu 18.04 with Maven 3.8.4
None
Please clear your browser cache before executing the tests.
=> FISH-6307 Can't collect domain logs from the Admin Console

appserver/extras/docker-images/pom.xml
Adds a JDK 17 Docker image to the build
None
None
Ran the tests under `appserver/extra/docker-images/docker-tests` with the pom edited to run test against JDK 17 images - passed.
Built images, started JDK 17 image, deployed an application - no explosions.
WSL OpenSUSE 15.3
https://github.com/payara/Payara-Community-Documentation/pull/312
None
=> FISH-6353 JDK 17 Docker Image

appserver/admingui/reference-manual/src/main/help/en/help/reference/create-jdbc-connection-pool.html, appserver/jdbc/admin/src/main/manpages/org/glassfish/jdbc/admin/cli/create-jdbc-connection-pool.1
The documentation within the admin console (reference docs) and on the admin command currently states that this property defaults to true - it does not, it defaults to false.
N/A
N/A
Tested the help info shows correctly
N/A - This property isn't written in the documentation
None
=> SERV-714 Update Documentation Around `prefer-validate-over-recreate` Property

appserver/web/web-core/src/main/java/org/apache/catalina/valves/ErrorReportValve.java, pom.xml
Fix for Core Profile TCK test `CustomJsonbSerializationIT.testMissingClientSerializationWithCDIProvider`.
This test throws a `WebApplicationException` with a response status code of 400 (Bad Request) if it fails to deserialize, and the test expects to receive said status code.
There's likely some underlying bugs happening within Jersey / Yasson itself as there are numerous calls to `ResponseWriter#getResponseContext` that fail and throw container exceptions as it tries to map the error (doesn't happen on Jersey 3.0.x), but given that Jersey is deferring the processing of it to the container (Payara) I believe this is the actual fix. There's a couple of other places where the error code is explicitly set to HTTP 500 (e.g. `StandardWrapperValve#exception`) which was done in GlassFish a …
=> FISH-6360 Payara Does Not Status Code Set In 'WebApplicationException'

appserver/common/glassfish-naming/pom.xml, appserver/common/glassfish-naming/src/main/java/com/sun/enterprise/naming/impl/GlassfishNamingManagerImpl.java, appserver/common/glassfish-naming/src/main/java/com/sun/enterprise/naming/util/IIOPObjectFactory.java, appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/GlassFishORBManager.java, appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/RoundRobinPolicy.java, nucleus/core/extra-jre-packages/pom.xml, nucleus/pom.xml
https://github.com/payara/patched-src-glassfish-corba/pull/15
N/A
Ran Quicklook tests on JDK17
=> FISH-5747 Upgrade Corba to version 4.2.4.payara-p1

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
Improvement by invoking `gf.stop()` on payara micro shutdown rather than only `gf.dispose()`
N/A
None
+ Run integrations test on [arquillian-connectors](https://github.com/Payara/ecosystem-arquillian-connectors/tree/master)
+ Deploy and run simple servlet application that has servlet destroy method on it to Payara-micro
Windows11, Ubuntu 20.04.4 LTS, OpenJDK8, Maven 3.8.4
None
None
=> FISH-1336 Properly Shutdown Payara Micro on Ctrl+C

appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
Undeployment of an application takes a long time on Payara6 on Windows.
This issue is caused by the NPE exception thrown in the stop operation of WebappClassloader which results in an uncleaned classloader and locking in Windows.
NPE exception is caused during cleaning the cache of BeanELResolver.properties field via Reflection API which is now changed from static to non-static, and that already fixes the cache issue as per the following ticket details.
[BeanELResolver needs cleanup method · Issue #171 · jakartaee/expression-language](https://github.com/jakartaee/expression-language/issues/171) 
[Fix #171. Make cache per instance rather than per class · jakartaee/expression-language@3ec9258](https://github.com/jakartaee/expression-language/commit/3ec9258dd20ebedb76e1a72a63c69bf71b14775b) …
=> FISH-6352 File locks prevent undeployment on Windows

appserver/admingui/pom.xml, appserver/admingui/war/src/main/webapp/WEB-INF/sun-web.xml, pom.xml
This PR fixes the Payara Admin Console Branding layout in Payara6
https://github.com/payara/patched-src-glassfish-woodstock/pull/2
=> FISH-5983 Upgrade woodstock-webui-jsf-suntheme to v5.0.0.payara-p1

appserver/extras/docker-images/pom.xml
Title.
Payara-web distribution does not currently start, and thus fails the test.
None
Built images and ran unit tests
Windows 10
N/A
Payara-web distribution does not currently start, and thus fails the test.
=> FISH-6398 Update Docker Images to 8u332, 11.0.15, and 17.0.3

appserver/common/glassfish-naming/pom.xml, appserver/common/glassfish-naming/src/main/java/com/sun/enterprise/naming/impl/GlassfishNamingManagerImpl.java, appserver/common/glassfish-naming/src/main/java/com/sun/enterprise/naming/util/IIOPObjectFactory.java, appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/GlassFishORBManager.java, appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/RoundRobinPolicy.java, nucleus/core/extra-jre-packages/pom.xml, nucleus/pom.xml
Reverts payara/Payara#5818
Breaks web profile - we need to look at the dependency structure, since it seems the fix adopted elsewhere is to pull full Corba into the web distribution which shouldn't strictly require it.
=> Revert "FISH-5747 Upgrade Corba to version 4.2.4.payara-p1"

appserver/extras/docker-images/pom.xml
When updating Docker images for older releases of Payara the build will attempt to create a JDK17 image - this won't work for releases older than 5.2021.10.
This splits off the JDK17 image generation into a separate profile and execution, so that it can be disabled via explicitly turning the profile off e.g. `mvn clean install -pl ./appserver/extras/docker-images -amd -PBuildDockerImages,QuickBuild,!generate-jdk17-docker-image -Dpayara.version=5.2021.3`
None
None
* `mvn clean install -pl ./appserver/extras/docker-images -amd -PBuildDockerImages,QuickBuild,!generate-jdk17-docker-image -Dpayara.version=5.2021.3` - build succeeded and jdk8 & 11 images created
* `mvn clean install -pl ./appserver/extras/docker-images -amd -PBuildDockerImages,QuickBuild -Dpayara.version=5.2021.3` - build …
=> FISH-6429 Move JDK17 Docker Image Generation into a Separate Profile

pom.xml
Connection Closes Prematurely On HTTP/2 HTTPS Connections When Request Takes Long To Complete
None
None
1. "git checkout FISH-1515-Payara6" in Payara6
2. mvn clean install -T 3 -DskipTests
3. .\appserver\distributions\payara\target\stage\payara6\bin\asadmin start-domain --verbose
4. Deploy app message-board.war (attached in https://payara.atlassian.net/browse/FISH-1515)
5. Poke https://localhost:8181/message-board-war/app/wait?seconds=31
6. Response: HTTP_200_OK and the message: "OK, waited 31 seconds"
Zulu JDK 11.0.10 on Windows 10 with Maven 3.8.4
=> FISH-1515 new grizzly version p1 patched from version 4.0.0

nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/ssl/JSSE14SocketFactory.java
Port of https://github.com/payara/Payara/pull/5769 to Payara6 branch.
=> FISH-6336 Bouncy Castle FIPS Integration for HTTPS Connection (Payara6 Port)

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/OpenAPISupplier.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/OpenApiService.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/OpenAPIImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/util/ModelUtils.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/rest/app/service/OpenApiResource.java
When we have 2 applications deployed in one Payara Server instance, we are getting only one API Documentation
None
None
Steps:
1. mvn clean install -DskipTests
2. ./appserver/distributions/payara/target/stage/payara5/bin/asadmin start-domain -v
3. Deploy two simple applications to the Payara server: https://payara.atlassian.net/browse/FISH-6298
4. http://localhost:8080/openapi/ shows the API documentation for the 2 apps.
JDK 1.8_212 on Windows 10 with Maven 3.8.4
=> FISH-6298 OpenAPI document doesn't take into account multiple applications deployment

api/payara-bom/pom.xml, appserver/extras/docker-images/pom.xml, appserver/packager/rest-monitoring/pom.xml, appserver/pom.xml, appserver/tests/payara-samples/pom.xml
This PR updates the POMs to make use of the Maven Release Plugin for version management so we can move away from using scripts to create tags/branches
Performed release:prepare and release:perform with -DdryRun to ensure proper versioning
WSL2 Ubuntu 20.04 zulu JDK 1.8.0_342
This will only automate the updating of version numbers for the time being as profiles also need configuring for deployment, the specifics of which are still in discussion
=> [QACI-723] - Use Maven Release Plugin for Releases

Jenkinsfile
Disable the known failing suites temporarily.
These will be re-enabled as we fix them and all must run before the Payara6-tck branch can be merged back in.
=> Temporarily disable known failing test suites

appserver/packager/external/jakarta-ee9-shim/pom.xml, pom.xml
This removes all of packages and bundles that are no longer necessary after all APIs have been updated.
Only few CDI packages are retained for microprofile APIs, and JAXB for jackson JAXB annotations. 
I also attempted to make `jsftemplating` happy with older EL, but it also needs faces classes that no longer exist.
=> FISH-6373: Shrink shim to minimum required by legacy components

pom.xml
Updates OpenMQ to 6.3.0.payara-p1, required for Jakarta EE 10.
https://github.com/payara/patched-src-openmq/pull/19
None
Built and started server.
Currently running JMS TCK
WSL, JDK 11
N/A
None
=> FISH-6077 FISH-6450 OpenMQ 6.3.0.payara-p1 (Release Branch)

pom.xml
Updates OpenMQ to 6.3.0.payara-p1, required for Jakarta EE 10.
https://github.com/payara/patched-src-openmq/pull/19
None
Built and started server.
Currently running JMS TCK
WSL, JDK 11
N/A
None
=> FISH-6077 FISH-6450 OpenMQ 6.3.0.payara-p1

appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContextValve.java, appserver/web/web-core/src/test/java/org/apache/catalina/core/StandardContextValveTest.java
Cherry-pick of https://github.com/payara/Payara-Enterprise/pull/630 (by @luiseufrasio) 
FISH-6459
Steps in https://payara.atlassian.net/browse/FISH-6459
using Payara Server Enterprise instead of microprofile.
- Quicklook
- Jakarta TCKs
- Mojarra
JDK 1.8_212 on Windows 10  with Maven 3.8.0
=> FISH-6459 replacing ./ to /

appserver/extras/docker-images/pom.xml
Updates the Docker image JDK versions to 11.0.16, and 17.0.4.
None
None
Ran the Docker tests.
Windows 10.
N/A
None
=> FISH-6471 Upgrade Docker image JDK (Payara 6 Release)

appserver/extras/docker-images/pom.xml
Updates the Docker image JDK versions to 8u345, 11.0.16, and 17.0.4.
None
None
Ran the Docker tests.
Windows 10.
N/A
None
=> FISH-6471 Upgrade Docker image JDK

appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContextValve.java, appserver/web/web-core/src/test/java/org/apache/catalina/core/StandardContextValveTest.java
Cherry-pick of https://github.com/payara/Payara-Enterprise/pull/630 (by @luiseufrasio) 
FISH-6459
Steps in https://payara.atlassian.net/browse/FISH-6459
using Payara Server Enterprise instead of microprofile.
- Quicklook
- Jakarta TCKs
- Mojarra
JDK 1.8_212 on Windows 10  with Maven 3.8.0
=> FISH-6459 replacing ./ to / (Payara 6 Release)

appserver/extras/docker-images/pom.xml
Updates the Docker image JDK versions to 11.0.16, and 17.0.4.
None
None
Ran the Docker tests.
Windows 10.
N/A
None
=> FISH-6471 Upgrade Docker image JDK (Payara6)

appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContextValve.java, appserver/web/web-core/src/test/java/org/apache/catalina/core/StandardContextValveTest.java
FISH-6459
Steps in https://payara.atlassian.net/browse/FISH-6459
using Payara Server 6 instead of microprofile.
- Quicklook
- Jakarta TCKs
- Mojarra
JDK 11 on Windows 10  with Maven 3.8.0
=> FISH-6459 replacing ./ with /

nucleus/cluster/ssh/src/main/java/org/glassfish/cluster/ssh/launcher/SSHLauncher.java, nucleus/cluster/ssh/src/test/java/org/glassfish/cluster/ssh/launcher/SSHLauncherTest.java
Recreation of https://github.com/payara/Payara/pull/5896
An instance hosted on a remote SSH node in a Windows environment would quickly return saying that the command had failed, but when refreshing the instance page the instance would show as running.
This seems to come about due to a hard-coded 3 second wait, at which point the SSH connection is terminated. This PR ups the wait to the default of 120 seconds, which can be overidden using a new system property `fish.payara.node.ssh.timeout`. This means:
* Commands which take less than 120 (or user-defined x) seconds to complete should still return within that time - the SSH connection won't just sit there for 120  (or user-defined x) seconds
* Commands which take longer than 120 (or user-defined x) seconds will show as failed, though if …
=> FISH-6415 Unexpected Error When Starting Instance Hosted On Remote SSH Node on Windows OS Via Cygwin (Payara6)

nucleus/cluster/ssh/src/main/java/org/glassfish/cluster/ssh/launcher/SSHLauncher.java, nucleus/cluster/ssh/src/test/java/org/glassfish/cluster/ssh/launcher/SSHLauncherTest.java
Recreation of https://github.com/payara/Payara/pull/5895
An instance hosted on a remote SSH node in a Windows environment would quickly return saying that the command had failed, but when refreshing the instance page the instance would show as running.
This seems to come about due to a hard-coded 3 second wait, at which point the SSH connection is terminated. This PR ups the wait to the default of 120 seconds, which can be overidden using a new system property `fish.payara.node.ssh.timeout`. This means:
* Commands which take less than 120 (or user-defined x) seconds to complete should still return within that time - the SSH connection won't just sit there for 120  (or user-defined x) seconds
* Commands which take longer than 120 (or user-defined x) seconds will show as failed, though if …
=> FISH-6415 Unexpected Error When Starting Instance Hosted On Remote SSH Node on Windows OS Via Cygwin

appserver/admingui/cluster/pom.xml, appserver/admingui/common/pom.xml, appserver/admingui/common/src/main/resources/js/adminjsf.js, appserver/admingui/core/pom.xml, appserver/admingui/faces-compat/pom.xml, appserver/admingui/faces-compat/src/main/java/com/sun/faces/config/FacesInitializer2.java, appserver/admingui/faces-compat/src/main/java/fish/payara/server/internal/admingui/GlassFishInjectionProvider.java, appserver/admingui/full/pom.xml, appserver/admingui/jca/pom.xml, appserver/admingui/jms-plugin/pom.xml, appserver/admingui/payara-console-extras/pom.xml, appserver/admingui/payara-console-extras/src/main/java/fish/payara/admingui/extras/rest/PayaraRestApiHandlers.java, appserver/admingui/pom.xml, appserver/admingui/war/pom.xml, appserver/admingui/war/src/main/webapp/WEB-INF/sun-web.xml, appserver/admingui/war/src/main/webapp/WEB-INF/web.xml, appserver/admingui/web/pom.xml, appserver/extras/certificate-management/certificate-management-console-plugin/pom.xml, appserver/osgi-platforms/glassfish-osgi-console-plugin/pom.xml, appserver/packager/glassfish-gui/pom.xml, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ClassLoaderHierarchyImpl.java, pom.xml
This builds on top of classloading features of admingui that allow importing additional OSGi bundles into its application classloader. These bundles now take precedence over delegation to common application classloader and that allows us to override Faces 4 API and implementation with Faces 3.0.2.
This then also requires bit of manual initialization and injection provider from `jsf-connector` need to be copied as well.
I base this on top of TCK branch, which possibly doesn't have any fixed for admin console integrated yet, I didn't check.
This covers classloading and start up aspects of it, few other things need to be covered in followup tasks:
* There is still ocassional JS error like `table.getAllSelectedRowsCount is not a function`, for which we already know a fix and we must either …
=> FISH-6483: Package Faces 3.0 for use by Admin GUI

pom.xml
Upgrades OpenMQ to p2 which fixes the LICENSE.md and NOTICE.md files from being extracted in the top-level dir of Payara.
https://github.com/payara/patched-src-openmq/pull/21
Approval, build, and publication of OpenMQ PR.
None
Built MQ, built server using new MQ - no license or notice file under payara5 dir.
WSL
N/A
For a guide on building OpenMQ: https://payara.atlassian.net/wiki/spaces/PAYAR/pages/3135012872/OpenMQ
=> FISH-6477 Do not include LICENSE.md or NOTICE.md (Payara6-tck) (Community Contribution)

appserver/security/jacc.provider.inmemory/osgi.bundle, appserver/security/jacc.provider.inmemory/src/main/java/fish/payara/security/jacc/provider/PolicyProviderImpl.java, appserver/web/weld-integration-fragment/pom.xml, nucleus/core/javassist-packages/pom.xml, nucleus/core/pom.xml, nucleus/packager/nucleus/pom.xml, nucleus/security/core/pom.xml, nucleus/security/core/src/main/java/com/sun/enterprise/security/AuthenticationProxyHandler.java, nucleus/security/core/src/main/java/com/sun/enterprise/security/PolicyLoader.java, nucleus/security/core/src/main/java/com/sun/enterprise/security/SecurityLifecycle.java, pom.xml
This PR adds Javassist proxy class for policy provider to delegate Java SE policy check. (Only needed for `TCKPolicy` as it does not support delegation, but Exousia impl (and `PolicyProviderImpl` from inmemory module) already do delegation so proxy is not needed).
Weld OSGI exports `javassist.util.proxy` which is having issue in Nucleus security module so exported Javassist from Nucleus.
=> FISH-6419 Proxy for TCK PolicyProvider

pom.xml
Upgrades OpenMQ to p3 which fixes the LICENSE.md and NOTICE.md files from being extracted in the top-level dir of Payara.
https://github.com/payara/patched-src-openmq/pull/20
Approval, build, and publication of OpenMQ PR.
None
Built MQ, built server using new MQ - no license or notice file under payara5 dir.
WSL
N/A
For a guide on building OpenMQ: https://payara.atlassian.net/wiki/spaces/PAYAR/pages/3135012872/OpenMQ
=> FISH-6477 Do not include LICENSE.md or NOTICE.md (Community Contribution)

pom.xml
Upgrades OpenMQ to p2 which fixes the LICENSE.md and NOTICE.md files from being extracted in the top-level dir of Payara.
https://github.com/payara/patched-src-openmq/pull/21
Approval, build, and publication of OpenMQ PR.
None
Built MQ, built server using new MQ - no license or notice file under payara5 dir.
WSL
N/A
For a guide on building OpenMQ: https://payara.atlassian.net/wiki/spaces/PAYAR/pages/3135012872/OpenMQ
=> FISH-6477 Do not include LICENSE.md or NOTICE.md (Payara6) (Community Contribution)

pom.xml
Upgrading jersey version to solve proxy creation issues for injection context fields
this is a bug fix to solve issues when injecting context fields for Singleton EJB's
manual testing on local environment after building the patched jersey project with the version  3.1.0-M7.payara-p1
windows 11, maven 3.8, azul jdk 11
=> FISH-6435: upgrading jersey version to solve proxy issues

appserver/tests/payara-samples/test-domain-setup/src/test/java/fish/payara/samples/setuptests/ViewLogWarningErrorTest.java, pom.xml
Security connectors 2.4.0 add support for `accessTokenIssuer` - a different issuer URL to id token issuer. This is required to support Microsoft ADFS, which behaves exactly like that.
Release of payara/ecosystem-security-connectors#221 to Maven central (in few hours, I suspect).
Payara Samples openid tests against staged version of release artifacts.
Small fix added to `ViewLogWarningErrorTest` so it behaves correctly in non-unicode locales.
```
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.6
Java version: 1.8.0_302, vendor: Azul Systems, Inc., runtime: C:\Program Files\Zulu\zulu-8\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
=> FISH-6434: Upgrade security connectors to version with ADFS issuer support

Jenkinsfile
Samples were updated to be compatible with EE10 mostly by dropping implicit archives with empty `beans.xml`.
payara/patched-src-javaee7-samples#77 updates tests so they pass
=> FISH-6411: Re-enable EE7 samples

pom.xml
Just the Jakarta annotations 2.1.1 update to fix the Jakarta EE TCK Signature tests - packaging jakarta.json-api seems to cause Jenkins to explode despite all the tests being proven to work on multiple local machines.
None
None
Ran the Signature TCK - passed.
WSL OpenSUSE Leap 15.4, Zulu JDK 11.0.16
N/A
The signature TCK also seemingly requires the `--add-opens=java.base/jdk.internal.vm.annotation=ALL-UNNAMED` JVM option to be enabled server-side. I'm looking at adding this to the runner rather than enabling it by default in the domain since it **seems** very specific.
=> FISH-6512 Jakarta Annotations 2.1.1 (Release Branch)

Jenkinsfile
This is a PR to enable the EE 8 samples
This is a fix to enable the EE 8 samples
This depends of the following PR: https://github.com/payara/patched-src-javaee8-samples/pull/24
=> FISH-6410: enabling java ee 8 sample tests

appserver/admingui/common/src/main/resources/js/adminjsf.js
Added require for function calls on table, so they succeed.
Currently, there is no (known) JS warning in the log while working with admin gui.
There is only 404 for a js file (will be consecutive PR).
Going through admin gui (e.g. select list of JDBC resources, go to detail, ping, deploy application, etc.)
Open JS debugger while going through admin gui and watch uncatched exceptions.
=> FISH-6483 add several other js require in admingui

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/bootstrap/BootCommandService.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLoaderService.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/store/ClusteredStore.java
Fixes the issue with using DEPLOY command in postbootcommand file.
Set the BootCommandService to 10. Return HazelcastCore and ClusteredStore back to level 10 as they don't need to be started earlier. And add an explicit dependency from ApplicationLoaderService for cases, that postbootcommanfile contains setup for already deployed apps.
Add check during application loading service, if it was already loaded via postbootcommandfile.
You need some JakartaEE 9 app.
Create file postboot.asadmin with content:
`deploy /path/to/yourapp.war`
Run this command from Payara:
`/asadmin start-domain --postbootcommandfile /path/to/postboot.asadmin`
Expected output: deployed app (it asks for password when opened).
OpenJDK, Linux
=> FISH-6501 Fix BootCommandService Runlevel

appserver/payara-appserver-modules/microprofile/fault-tolerance/src/main/java/fish/payara/microprofile/faulttolerance/cdi/FaultToleranceInterceptor.java, appserver/tests/payara-samples/samples/pom.xml, appserver/tests/payara-samples/samples/reproducers/pom.xml, appserver/tests/payara-samples/samples/reproducers/src/main/java/fish/payara/samples/resource/fish6238/SingletonBean.java, appserver/tests/payara-samples/samples/reproducers/src/main/java/fish/payara/samples/resource/fish6238/StatelessBean.java, appserver/tests/payara-samples/samples/reproducers/src/test/java/fish/payara/samples/resource/fish6238/FaultToleranceTest.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/EjbServicesImpl.java
This is a fix for https://github.com/payara/Payara/issues/5679 issue.
EJB life-cycle failed to recognize programmatic interceptor regarding fault-tolerance interceptor that is using around invoke interception type
N/A
None
+ Build payara server with build extras profile `-PBuildExtras`
+ Checkout this reproducer https://github.com/ismailsalloo/payara-sample
+ Change `fish.payara.extras:payara-embedded-all` payara-sample's dependency version to fixed payara which is `5.2022.4-SNAPSHOT`
example:
```
<dependency>
<groupId>fish.payara.extras</groupId>
<artifactId>payara-embedded-all</artifactId>
<version>5.2022.4-SNAPSHOT</version>
<scope>test</scope>
</dependency>
```
+ Run `mvn clean test` 
Windows 11, OpenJDK1.8, Maven 3.8.4
None
None
=> FISH-6238 Microprofile Interceptors [@Fallback@/CircuitBreaker] are not getting invoked if the EJB is a @Stateless Bean

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLoaderService.java
The previous changes FISH-6501 introduced a problem with app loading during restart. This fix corrects the way, how is already loaded app checked.
An application can be loaded via postbootcommand file, e.g. ApplicationLoaderService will try to load this application later again. The former test was using isLoaded flag, but it is set for the application during server reboot. This new fix uses isRunning.
Download the jolokia war file from the ticket. The test can be done with clusterjsp.war as well.
Create file postboot.asadmin with content:
`deploy /path/to/jolokia-war-1.7.1.war`
Run this command from Payara:
`/asadmin start-domain --postbootcommandfile /path/to/postboot.asadmin`
Expected output: deployed app (it asks for password when opened).
Stop the server and start again without …
=> FISH-6501 Fix App Loading After Reboot

appserver/tests/payara-samples/samples/legacy-mode-empty-beans-xml/pom.xml, appserver/tests/payara-samples/samples/legacy-mode-empty-beans-xml/src/main/java/fish/payara/samples/cdi/legacymode/beans/AnnotatedBean.java, appserver/tests/payara-samples/samples/legacy-mode-empty-beans-xml/src/main/java/fish/payara/samples/cdi/legacymode/beans/NotAnnotatedBean.java, appserver/tests/payara-samples/samples/legacy-mode-empty-beans-xml/src/main/resources/arquillian.xml, appserver/tests/payara-samples/samples/legacy-mode-empty-beans-xml/src/test/java/fish/payara/samples/cdi/legacymode/beans/EnableLegacyModeTest.java, appserver/tests/payara-samples/samples/pom.xml, appserver/web/gf-weld-connector/src/main/java/org/glassfish/weld/connector/WeldUtils.java, appserver/web/weld-integration/pom.xml, appserver/web/weld-integration/src/main/java/org/glassfish/weld/BeanDeploymentArchiveImpl.java, appserver/web/weld-integration/src/main/resources/beans-all.xml, appserver/web/weld-integration/src/test/java/org/glassfish/weld/RootBeanDeploymentArchiveTest.java, nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/ServerTags.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationConfigListener.java, nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/DeployCommand.java
Starting with CDI 4.0, bean archives with empty beans.xml have discovery mode `annotated`. This PR adds a compatibility configuration option that users can leverage to switch this back to `all` discovery mode. 
Application level configuration: `asadmin deploy  --properties=emptyBeansXmlModeALL=true my_app.war`
Global configuration: `asadmin create-system-properties fish.payara.deployment.emptyBeansXmlModeALL=true `
[https://github.com/payara/Payara-Documentation/pull/90](https://github.com/payara/Payara-Documentation/pull/90)
=> FISH-6486 Support legacy handling of empty beans.xml

appserver/pom.xml
Nimbus-JOSE-JWT version 9.8.1 uses json-smart version 1.3.2 (affected component) and thus it is needed to be updated. 
None
payara-samples
quicklook
=> FISH-6522 Nimbus-jose upgrade to 9.25

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
Improvement by invoking gf.stop() on payara micro shutdown rather than only gf.dispose()
N/A
+ Run integrations test on [arquillian-connectors](https://github.com/payara/ecosystem-arquillian-connectors/tree/Payara6)
+ Deploy and run simple servlet application that has servlet destroy method on it to Payara-micro
Windows11, Ubuntu 20.04.4 LTS, OpenJDK11, Maven 3.8.4
None
=> FISH-1336 Properly Shutdown Payara Micro on Ctrl+C (P6)

appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/domain.xml
This is a fix,
`jacc-provider` with `name=simple` is unavailable thus it causes the policy provider lookup failed to collect the defined policy provider from domain.xml.
By removing the jacc identification on tag `security-service` on payara micro's domain.xml it help policy provider to get correct `jacc-provider` config
None
+ `cd appserver/extras/docker-images`
+ Run `mvn clean install` 
None
None
=> FISH-6442 Payara Micro Docker Image Test Fails

appserver/extras/docker-images/micro/pom.xml, appserver/extras/docker-images/server-full/pom.xml, appserver/extras/docker-images/server-node/pom.xml, appserver/extras/docker-images/server-web/pom.xml
The recent change to make the bom use `project.version` meant the docker images were ignoring `payara.version` when determining which version of Payara to bundle.
None
None
Built images and ran tests using `payara.version=5.2022.3`, checking logs to make sure it actually used 5.2022.3
WSL
N/A
None
=> Bundle payara.version not project.version

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java
Enabling preprocessing for ENV placeholder on micro logging properties
This is a bug fix for an issue to map system properties to placeholders added on a logging.properties file for payara micro
Manual testing using the following command line for payara micro:
java -Dloglevel=FINE -jar payara-micro.jar --logProperties logging.properties
and using the attached logging.properties file attached on the ticket: [FISH-6506](https://payara.atlassian.net/browse/FISH-6506)
`~/projects/Payara/appserver/extras/payara-micro/payara-micro-distribution/target$ java -Dloglevel=FINE -jar payara-micro.jar --logProperties logging.properties
Sep 20, 2022 8:04:59 PM fish.payara.micro.impl.RuntimeDirectory processDirectoryInformation
WARNING: Payara Micro Runtime directory is located in a temporary file …
=> FISH-6506: enable preprocessing for ENV placeholder on micro logging properties

appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/InjectionServicesImpl.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/NonModuleInjectionServices.java
This is an improvement to reduce the log level severity when no valid EE environment for injection is found.
None
Manual testing
Windows 10, Zulu JDK 11.0.10
N/A
None
=> FISH-5780 Reduce the log level severity when no valid EE environment for injection is found

appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/healthcheck/HealthCheckCounter.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/healthcheck/HealthCheckGauge.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/healthcheck/ServiceExpression.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/impl/MetricsServiceImpl.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/jmx/MBeanExpression.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/jmx/MetricsMetadata.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/jmx/MetricsMetadataConfig.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/jmx/MetricsMetadataHelper.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/writer/MetricsWriterImpl.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/resources/metrics.xml, appserver/payara-appserver-modules/microprofile/metrics/src/test/java/fish/payara/microprofile/metrics/jmx/MetricsMetadataTest.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HealthCheckStatsProvider.java, nucleus/payara-modules/healthcheck-stuck/src/main/java/fish/payara/nucleus/healthcheck/stuck/StuckThreadsHealthCheck.java
This PR adds HealthCheck stats (Stuck thread count) to MicroProfile Metrics.
`StuckThreadsHealthCheck` required by `MetricsServiceImpl`.
`MetricsServiceImpl` required by `FaultToleranceServiceImpl` and `MicroProfileMetricsChecker`.
All of these services started at `@RunLevel(StartupRunLevel.VAL)`.
The enable status of HealthCheck can not be checked during registration of Metrics metadata which is by default registered and during response writer operation, health check status is checked.
````
asadmin start-domain
asadmin set-healthcheck-service-configuration --serviceName=stuck-thread --enabled=true
asadmin restart-domain
````
Open `http://localhost:8080/metrics/vendor` URL which so=houl contains the following result:
````
vendor_system_cpu_load 0.2421606522975489
vendor_thread_stuck_count …
```
=> FISH-5827 Stuck Thread count as MicroProfile Metric Gauge

appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/InjectionServicesImpl.java
Preventing error logs related to inject TransactionalScopedCDIEventHelperImpl for TransactionScoped CDI Beans
this is a bug fix to not add unnecesary error logs for TransactionScoped CDI Beans
local testing using the attached reproducer from the ticket [FISH-6430](https://payara.atlassian.net/browse/FISH-6430)
logs looks more cleaned:
`  [#|2022-09-27T13:18:04.654-0500|INFO|Payara 5.2022.4-SNAPSHOT||_ThreadID=129;_ThreadName=http-thread-pool::http-listener-1(2);_TimeMillis=1664302684654;_LevelValue=800;|
TestTransactionalScopeBean initialized. Value is 1664302684654|#]
[#|2022-09-27T13:19:02.527-0500|INFO|Payara 5.2022.4-SNAPSHOT||_ThreadID=129;_ThreadName=http-thread-pool::http-listener-1(2);_TimeMillis=1664302742527;_LevelValue=800;|
ServiceBean:: testTransactionalScope value is …
=> Fish-6430: skipping BdId TransactionalExtension type to not generate error logs

nucleus/pom.xml, pom.xml
Enhancement to upgrade milestone components 
None
+ Performed Payara sample and Quicklook
+ JakartaEE-10-tck -> [test-result](https://jenkins.payara.fish/blue/organizations/jenkins/JakartaEE-10-TCK/detail/JakartaEE-10-TCK/222/pipeline/)
+ TCK Suite -> [test-result](https://jenkins.payara.fish/blue/organizations/jenkins/TCK-Suite/detail/TCK-Suite/569/pipeline); `activation` and `java-mail-standalone` got failure due to configuration which fails to read test result however all test cases is passed for both
Windows 11, WSL, OpenJDK11, Maven 3.8.4
None
None
=> FISH-6357 Ensure No Longer Using Jakarta Milestone Components

appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/healthcheck/HealthCheckCounter.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/healthcheck/HealthCheckGauge.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/healthcheck/ServiceExpression.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/jmx/MetricsMetadata.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/jmx/MetricsMetadataHelper.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/resources/metrics.xml, appserver/payara-appserver-modules/microprofile/metrics/src/test/java/fish/payara/microprofile/metrics/jmx/MetricsMetadataTest.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HealthCheckStatsProvider.java, nucleus/payara-modules/healthcheck-cpool/src/main/java/fish/payara/nucleus/healthcheck/cpool/ConnectionPoolHealthCheck.java, nucleus/payara-modules/healthcheck-stuck/src/main/java/fish/payara/nucleus/healthcheck/stuck/StuckThreadsHealthCheck.java
This PR integrates Connection Pool Helthcheck with Microprofile Metrics.
New config added to `metrics.xml`
````
<metadata>
<name>${attribute}.${subattribute}</name>
<service>healthcheck-cpool/${attribute}#${subattribute}</service>
<type>gauge</type>
<unit>none</unit>
<displayName>${attribute} ${subattribute}</displayName>
<description>Displays the number of ${subattribute} of ${attribute}.</description>
</metadata>
````
Unit test
To verify the feature enable HealthCheck and Connection Pool HealthCheck from the Admin console.
[https://github.com/payara/Payara-Documentation/pull/107](https://github.com/payara/Payara-Documentation/pull/107)
=> FISH-5828 Connection Pool HealthCheck exposed to MicroProfile Metrics

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ContextServiceConfig.java, pom.xml
Payara failed the Concurrency TCK 3.0.2. It is fixed now:
* properly handle context lists during context switch (fix in ContextSetupProviderImpl.java)
* cancel scheduled Future (upgrade of patched Concurrency RI)
This patch depends on new version of patched Concurrency RI: https://github.com/payara/patched-src-concurrency-ri/pull/2 
The version 3.0.0.payara-p2 is uploaded to Payara's nexus.
Run latest Concurrency TCK, version 3.0.2. Updated runner: https://github.com/payara/jakartaee-10-tck-runners/pull/44
=> FISH-6556 Concurrency Fix Web Profile

appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContextValve.java, appserver/web/web-core/src/test/java/org/apache/catalina/core/StandardContextValveTest.java
META-INF folder is necessary to be available for some requests.
None
None
Steps in https://payara.atlassian.net/browse/FISH-6603
using Payara\appserver\extras\payara-micro\payara-micro-distribution\target\payara-micro.jar
=> FISH-6603 : META-INF must not be always denied

appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/healthcheck/HealthCheckCounter.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/healthcheck/HealthCheckGauge.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/healthcheck/ServiceExpression.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/jmx/MetricsMetadata.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/jmx/MetricsMetadataHelper.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/resources/metrics.xml, appserver/payara-appserver-modules/microprofile/metrics/src/test/java/fish/payara/microprofile/metrics/jmx/MetricsMetadataTest.java, nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/HealthCheckStatsProvider.java, nucleus/payara-modules/healthcheck-cpool/src/main/java/fish/payara/nucleus/healthcheck/cpool/ConnectionPoolHealthCheck.java, nucleus/payara-modules/healthcheck-stuck/src/main/java/fish/payara/nucleus/healthcheck/stuck/StuckThreadsHealthCheck.java
This PR integrates Connection Pool Helthcheck with Microprofile Metrics.
New config added to `metrics.xml`
````
<metadata>
<name>${attribute}.${subattribute}</name>
<service>healthcheck-cpool/${attribute}#${subattribute}</service>
<type>gauge</type>
<unit>none</unit>
<displayName>${attribute} ${subattribute}</displayName>
<description>Displays the number of ${subattribute} of ${attribute}.</description>
</metadata>
````
Unit test
To verify the feature enable HealthCheck and Connection Pool HealthCheck from the Admin console.
[https://github.com/payara/Payara-Documentation/pull/107](https://github.com/payara/Payara-Documentation/pull/107)
https://github.com/payara/Payara/pull/5974
=> FISH-5828 Connection Pool Metrics Exposed as MicroProfile Metrics

nucleus/admin/util/src/main/java/com/sun/enterprise/admin/remote/reader/MultipartProprietaryReader.java
On JDK 11.0.16 if a WAR contained a .json file, Payara would create an ActionReport when it is not needed, this change ensures that for only ActionReport files an ActionReport is created.
=> FISH-6566 Only create an action report for action report files

nucleus/admin/util/src/main/java/com/sun/enterprise/admin/remote/reader/MultipartProprietaryReader.java
On JDK 11.0.16 if a WAR contained a .json file, Payara would create an ActionReport when it is not needed, this change ensures that for only ActionReport files an ActionReport is created.
=> FISH-6566 Only create an action report for action report files [Payara6]

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java, nucleus/admin/config-api/src/main/java/fish/payara/boot/runtime/BootCommands.java, nucleus/admin/config-api/src/test/java/fish/payara/boot/runtime/BootCommandsTest.java, nucleus/common/internal-api/src/main/java/fish/payara/internal/api/DeployPreviousApplicationsRunLevel.java, nucleus/common/internal-api/src/main/java/fish/payara/internal/api/PostBootRunLevel.java, nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/GlassFishMain.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/bootstrap/BootCommandService.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLoaderService.java
Port of https://github.com/payara/Payara/pull/5991
This PR attempts to sanitise the boot sequence for services, post-boot commands, and application deployments.
In our previous attempts to allow variable substitution in post-boot command files and make post-boot commands consistent, we ended up frequently causing unintentional side effects typically to do with deployment or command timings.
This PR introduces two new run levels, which are used to hopefully make everything consistent and better space out the server boot lifecycle timings.
Before:
* Run level 10 (in no particular order - all run at the same run level):
* Previously deployed applications
* Post-boot commands
* Startup services (e.g. MicroProfile Config)
* Run level 20:
* Autodeploy applications (not previously deployed ones) …
=> FISH-6588 Add Extra Run Levels for Post-Boot and Deployment and Resolve Payara Micro Variable Expansion Error (Payara6)

appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroImpl.java, nucleus/admin/config-api/src/main/java/fish/payara/boot/runtime/BootCommands.java, nucleus/admin/config-api/src/test/java/fish/payara/boot/runtime/BootCommandsTest.java, nucleus/common/internal-api/src/main/java/fish/payara/internal/api/DeployPreviousApplicationsRunLevel.java, nucleus/common/internal-api/src/main/java/fish/payara/internal/api/PostBootRunLevel.java, nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/GlassFishMain.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/bootstrap/BootCommandService.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLoaderService.java
This PR attempts to sanitise the boot sequence for services, post-boot commands, and application deployments.
In our previous attempts to allow variable substitution in post-boot command files and make post-boot commands consistent, we ended up frequently causing unintentional side effects typically to do with deployment or command timings.
This PR introduces two new run levels, which are used to hopefully make everything consistent and better space out the server boot lifecycle timings.
Before:
* Run level 10 (in no particular order - all run at the same run level):
* Previously deployed applications
* Post-boot commands
* Startup services (e.g. MicroProfile Config)
* Run level 20:
* Autodeploy applications (not previously deployed ones)
* Applications in the autodeploy folder
* Admin …
=> FISH-6588 Add Extra Run Levels for Post-Boot and Deployment and Resolve Payara Micro Variable Expansion Error

nucleus/common/glassfish-api/src/main/java/org/glassfish/api/event/EventTypes.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/AppServerStartup.java, nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/PayaraExecutorService.java
Bug fix for the `PayaraExecutorService` encountering NPEs during use in an Embedded EJB Container.
With `ApplicationLoaderService` now starting at run level 15 rather tha 10, this meant the `ALL_APPLICATIONS_LOADED` event was firing later than before, leading to the thread pools in the `PayaraExecutorService` still being _null_ during the "half-restarts" that occur when using the Embedded EJB Container.
These "half-restarts" only re-initialise **some** services, not all, which was leading to the thread pools in `PayaraExecutorService` being nulled from receiving the `SERVER_SHUTDOWN` event, but never being reinitialised.
Since the `SERVER_START` event doesn't get fired until _after_ run-level 10 (our NPE happens _at_ run-level 10), I've created a new event to get fired after run-level 1. …
=> FISH-6588 Embedded EJB Container NPE Fix

nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/ldap/CustomSocketFactory.java
Override createSocket method without arguments to fix ldap connection issue
This is a fix for an invalid behaviour when trying to create LDAPs connections
manual testing with different versions of JDK, please check comments on the following ticket: https://payara.atlassian.net/browse/FISH-6567?focusedCommentId=64300
Windows 11 and ubuntu 20.04, JDK's used: Azul JDK 8, Oracle JDK 8,Azul jdk 11.0.13, Azul jdk 11.0.17, Oracle jdk 11.0.15, Azul jdk 17.30.15,  Azul jdk 17.0.4,  OpenJDK 11.0.12, Azul jdk 11.0.15, maven 3.8.6
=> FISH-6567: override createSocket method without arguments to fix ldap connection issue

nucleus/common/simple-glassfish-api/src/main/java/org/glassfish/embeddable/GlassFishRuntime.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java
A customer would like to provide a path to a hazelcast configuration file when using Payara Embedded with Arquillian.
None
1. Download the attached reproducer application & hazelcast-config.xml
2. Modify the embedded arquillian configuration in arquillian.xml to specify a path to the hazelcast-text.xml file:
<?xml version="1.0"?>
<arquillian xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="http://jboss.org/schema/arquillian"
xsi:schemaLocation="http://jboss.org/schema/arquillian
http://jboss.org/schema/arquillian/arquillian_1_0.xsd">
<container qualifier="payara-embedded" default="true">
<configuration>
<property name="bindHttpPort">9990</property>
<property name="hazelcastConfigurationFile">C:/Users/luise/Downloads/hazelcast-test.xml</property>
</configuration>
</container> …
=> FISH-6495 : setting hazelcast property when passed

nucleus/common/simple-glassfish-api/src/main/java/org/glassfish/embeddable/GlassFishRuntime.java
A customer would like to provide a path to a hazelcast configuration file when using Payara Embedded with Arquillian.
None
1. Download the attached reproducer application & hazelcast-config.xml
2. Modify the embedded arquillian configuration in arquillian.xml to specify a path to the hazelcast-text.xml file:
<?xml version="1.0"?>
<arquillian xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="http://jboss.org/schema/arquillian"
xsi:schemaLocation="http://jboss.org/schema/arquillian
http://jboss.org/schema/arquillian/arquillian_1_0.xsd">
<container qualifier="payara-embedded" default="true">
<configuration>
<property name="bindHttpPort">9990</property>
<property name="hazelcastConfigurationFile">C:/Users/luise/Downloads/hazelcast-test.xml</property>
</configuration>
</container> …
=> FISH-6495 : verifying if property was passed

pom.xml
Upgrades the components from 0.2.7 to 0.2.9 and 1.0 to 1.1.1 respectively.
Please note that the Payara Deployment Transformer implementation is not pulled into the distribution - only the API is. To test you must drop it into the modules directly manually.
Merge, build ,and release of: https://github.com/payara/transformer/pull/30
None
* Built Transformers.
* Built Payara Server.
* Dropped Payara Deployment Transformer impl into modules.
* Ran EE7 sample test jaxrs/simple-get using the _master_ branch (so it's `javax` namespace).
Windows 10
WSL
N/A - nothing to update
See notes in description of having to drop in transformer impl.
=> FISH-6724 FISH-6726 Eclipse Transformer 0.2.9 and Payara Deployment Transformer 1.1.1

pom.xml
Upgrade patched Jersey from `2.36.payara-p1` to `2.37.payara-p1`
None
None
Run Payara server, quicklook test and payara-samples
Windows 11, WSL, OpenJDK8, Maven 3.8.4
N/A
N/A
=> FISH-6670 Upgrade Jersey to 2.37

appserver/extras/docker-images/pom.xml
Update docker images to latest JDK versions
None
None
Build docker images
Maven 3.6.3, JDK 11, Windows 10
None
None
=> FISH-6669 (P6) Update Docker JDK Versions

appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/cdi/CdiInitEventHandler.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/cdi/JsonWebTokenProducer.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/cdi/JwtAuthCdiExtension.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/JWTAuthenticationMechanism.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jwt/JsonWebTokenImpl.java, appserver/tests/payara-samples/samples/microprofile-endpoints/secure/src/test/resources/post-boot-commands.txt, appserver/tests/payara-samples/samples/reproducers/src/main/java/fish/payara/samples/mpjwt/fish6022/JaxrsApplication.java, appserver/tests/payara-samples/samples/reproducers/src/main/java/fish/payara/samples/mpjwt/fish6022/PublicServlet.java, appserver/tests/payara-samples/samples/reproducers/src/main/java/fish/payara/samples/mpjwt/fish6022/RootResource.java, appserver/tests/payara-samples/samples/reproducers/src/test/java/fish/payara/samples/mpjwt/fish6022/InvalidTokenOnPublicEndpointTest.java
MP JWT Auth says that it is possible to access unprotected endpoints with invalid JWT token in the header unless application tries to access injected `JsonWebToken`. At the same time, unprotected endpoints should have access to JWT token if it is valid and has been passed in the request.
Therefore there are three possible behaviors upon accessing `JsonWebToken`:
* If token is valid, the class can be injected to access properties of the token. Principal identity is also estabilished
* If token is not present, empty token is injected, all methods return null.
* If token is invalid, any access to the class will result in `NotAuthorizedException`, causing JAX-RS processing to end with status 401.
Spec doesn't specify behavior in servlet container, therefore it was not considered. That results …
=> FISH-6022 FISH-6299: Allow access to unprotected endpoints with invalid JWT

api/payara-api/src/main/java/fish/payara/cluster/Clustered.java, appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/annotation/handlers/SingletonHandler.java, appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/cluster/ClusterScopedInterceptor.java
Fixes a typo in the '@Clustered' API.
None
None
Built the server, ran the clustered-singleton test in payara-samples
WSL, Zulu JDK 11
PR to Documentation: https://github.com/payara/Payara-Documentation/pull/152
Added to our itnernal documentation of breaking changes: https://payara.atlassian.net/wiki/spaces/PAYAR/pages/3418685483/Breaking+Changes
None
=> FISH-1175 Fix Typo in '@Clustered' API

pom.xml
Updates ASM to 9.4 and HK2 to 2.6.1.payara-p8 which had ASM incremented to 9.4
~Blocked by https://github.com/payara/patched-src-hk2/pull/25 being approved and published to Nexus~
None
Started the server, created and instance and deployed an application
JDK 8, Maven 3.6.3, Windows 10
None
None
=> FISH-6686 Update ASM to 9.4

appserver/pom.xml
Update BCEL to 6.6.1. This also fixes CVE-2022-42920
None
None
Started the server, created an instance and deployed an application
Windows 10, Maven 3.6.3, JDK 11
None
None
=> FISH-6715 (P6) Update BCEL to 6.6.1

pom.xml
Improvements for JakartaEE 8 applications running on Payara 6, original idea is https://github.com/payara/Payara/issues/5842
This PR is the opposite part to https://github.com/payara/Payara/pull/6031, which improved support of Java EE 9 apps on Payara 5.
The only change happens in jsf-uncompressed.js
All `jakarta.faces.*` post data is duplicated with `javax.faces` copies.
E.g. the reproducer application produced this output:
```
form: form
form:input: Message
jakarta.faces.behavior.event: action
jakarta.faces.partial.ajax: true
jakarta.faces.partial.event: click
jakarta.faces.partial.execute: form:jsfButton form:input
jakarta.faces.partial.render: form:output
jakarta.faces.source: form:jsfButton
jakarta.faces.ViewState: 3768650063610317665:-4574714117490412382
```
The new version produces …
=> FISH-6596 Jakarta Form Data

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ApplicationProcessor.java, appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/test/app/application/SchemaExampleTest.java, appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/test/util/JsonUtils.java
When using OpenAPI annotation @Schema on the Class attribute, it does not rename it instead it appears twice (initial attribute name and the renamed one)
None
new test **fieldSchemaExampleIsRenamed** in `fish.payara.microprofile.openapi.test.app.application.SchemaExampleTest`
1. mvn clean install -T 3C -DskipTests
2. .\appserver\distributions\payara\target\stage\payara5\bin\asadmin start-domain
3. Download and unzip: https://github.com/payara/Payara/files/7254999/payara-openapi-schema-name-error.zip
4. cd C:\Dev\reproducers\payara-openapi-schema-name-error
5. C:\Dev\reproducers\payara-openapi-schema-name-error\mvn clean package
6. C:\Users\luise\git\Payara\appserver\distributions\payara\target\stage\payara5\bin\asadmin deploy .\payara-openapi-schema-name-error.war
7. Poke …
=> FISH-5778 : handling duplicated field when annotated with @Schema

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/visitor/OpenApiContext.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/visitor/OpenApiWalker.java, appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/test/app/application/DependantClassesTest.java, appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/test/app/application/schema/Child.java
JAX-RS Subresources don't Appear in OpenAPI Document
None
new test **dependantClassSinglePathAnnotation** in `fish.payara.microprofile.openapi.test.app.application.DependantClassesTest`
1. mvn clean install -T 3C -DskipTests
2. .\appserver\distributions\payara\target\stage\payara5\bin\asadmin start-domain
3. cd C:\Dev\reproducers\FISH-5808
4. C:\Dev\reproducers\FISH-5808\mvn clean install
5. C:\Users\luise\git\Payara\appserver\distributions\payara\target\stage\payara5\bin\asadmin deploy .\openapi-test.war
6. Poke http://localhost:8080/openapi
7. It should show: /resources/foo/bar into **paths** & **endpoints**
Zulu JDK 1.8_212 on Windows 10 with Maven 3.8.4
=> FISH-5808 : handling single @Path on methods

appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/AuthenticatorBase.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/security/web/GlassFishSingleSignOn.java
Fixes #5551. The session that estabilishes SSO ID is now added into SSO tracking object.
Upon logout, the session is now explicitly invalidated before new SSO ID is generated. 
Empty realm is now handled the same as `null` realm. Therefore to enable SSO between Jaspic, or Jakarta EE Security, following must be present in `web.xml`:
```
<login-config>
<realm-name>anything</realm-name>
</login-config>
```
This doesn't need to refer to any existing realm name, it's a mean to enable applications to opt-in to SSO feature. Otherwise any two applications would be treated as SSO ones, regardless of their identity store or even authentication mechanism.
Test project per our internal JIRA now behaves as expected (after making the change to `web.xml`).
```
Apache Maven 3.8.6 …
```
=> FISH-6047: Fix Single Sing On handling for Jaspic applications, Single Sign Off for all SSO-enabled apps

nucleus/osgi-platforms/felix/src/main/resources/config/osgi.properties
The inflation threshold is set to 15, deploying more than 15 applications will have a delegation through the OSGi boot classloader attempt but ultimately fail since it doesn't have explicit access to the class as it belongs in the jdk.internal.reflect package. Adding the `jdk.internal.reflect` packages to OSGi BootDelegation allows for this to work as expected.
Addresses this Felix bug: [Apache Felix bug](https://issues.apache.org/jira/browse/FELIX-6184)
None
None
Unable to test the fix as discussed & mentioned on internal ticket.
Tested the property shows in the final packaged distribution as expected.
JDK 11.0.3, Windows 10, Maven 3.6.3
None
None
=> FISH-5809 (P6) Add `jdk.internal.reflect` packages to OSGi BootDelegation

pom.xml
Upgrades soteria implementation to one from payara/patched-src-security-soteria#4, which is already deployed to payara-artifacts.
What was described as "spurious warning" was in fact manifesting, that OpenID security connectors changed and they no longer ship Authentication Mechanism per OpenId provider, rather there is single mechanisms that can be activated by one of definition annotations.
All integrations tests in soteria pass against updated Payara. They weren't run before.
```
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.6
Java version: 11.0.12, vendor: Azul Systems, Inc., runtime: C:\Program Files\Zulu\zulu-11
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", …
```
=> FISH-6598: Upgrade soteria to fix broken Multiple Auth Mechanisms in EAR

appserver/pom.xml
Update BCEL to 6.6.1. This also fixes CVE-2022-42920
None
None
Started the server, created an instance and deployed an application
Windows 10, Maven 3.6.3, JDK 8
https://github.com/payara/Payara-Documentation/pull/157
None
=> FISH-6715 Update BCEL to 6.6.1

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/parameters/ParameterImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/test/app/application/QueryParamTest.java
When using OpenAPI annotation @Parameter(... explode = Explode.TRUE) (see code snippet), it is resulting in an exception in the 5.2021.7 version whereas for the 5.31.0 version OpenAPI document is not getting generated.
None
`fish.payara.microprofile.openapi.test.app.application.QueryParamTest`
1. **mvn clean install -T 3C -DskipTests**
2. .\appserver\distributions\payara\target\stage\payara5\bin\asadmin start-domain
3. **download** war file **payara-openapi-explode-issue-1.0-Payara6.war** from https://payara.atlassian.net/browse/FISH-5798
5. \asadmin deploy .\payara-openapi-explode-issue-1.0-SNAPSHOT.war
6. Poke http://localhost:8080/openapi
It should show: 
```
...
paths:
/rest/ping:
get:
operationId: ping
parameters:
- name: name
in: query
description: The name(s)
required: false …
```
=> FISH-5798 : casting explode parameter to EnumModel

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/parameters/ParameterImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/test/app/application/QueryParamTest.java
When using OpenAPI annotation @Parameter(... explode = Explode.TRUE) (see code snippet), it is resulting in an exception in the 5.2021.7 version whereas for the 5.31.0 version OpenAPI document is not getting generated.
None
`fish.payara.microprofile.openapi.test.app.application.QueryParamTest`
1. **mvn clean install -T 3C -DskipTests**
2. .\appserver\distributions\payara\target\stage\payara5\bin\asadmin start-domain
3. **download** war file **payara-openapi-explode-issue-1.0-SNAPSHOT.war** from https://payara.atlassian.net/browse/FISH-5798
5. \asadmin deploy .\payara-openapi-explode-issue-1.0-SNAPSHOT.war
6. Poke http://localhost:8080/openapi
It should show: 
```
...
paths:
/rest/ping:
get:
operationId: ping
parameters:
- name: name
in: query
description: The name(s)
required: false …
```
=> FISH-5798 : casting explode property to EnumModel

appserver/packager/legal/src/main/resources/glassfish/legal/3RD-PARTY-LICENSE.txt
Updates the third-party license:
* Remove references to dependencies that are no longer included
* Update existing dependency versions
* Reorganise file so that we don't have duplicate license blocks
* The duplicates that remain are for dependencies which are dual-licensed.
None, but should be kept in-line with all of the other component upgrades going on right now.
None
N/A
N/A
N/A
N/A
Dependencies and licenses viewed via performing the following command on the payara distribution: `mvn org.codehaus.mojo:license-maven-plugin:2.0.0:third-party-report "-Dlicense.excludedScopes=test"`
=> FISH-6746 Update 3RD-PARTY-LICENSE.txt (Payara6)

appserver/packager/legal/src/main/resources/glassfish/legal/3RD-PARTY-LICENSE.txt
Updates the third-party license:
* Remove references to dependencies that are no longer included
* Update existing dependency versions
* Reorganise file so that we don't have duplicate license blocks
* The duplicates that remain are for dependencies which are dual-licensed.
https://github.com/payara/Payara/pull/6066
None
N/A
N/A
N/A
N/A
Dependencies and licenses viewed via performing the following command on the payara distribution: `mvn org.codehaus.mojo:license-maven-plugin:2.0.0:third-party-report "-Dlicense.excludedScopes=test"`
=> FISH-6746 Update 3RD-PARTY-LICENSE.txt

appserver/packager/appserver-base/src/main/docs/README.txt
Adds mention of JDK 17 support to README file in Payara distribution, taken from https://docs.payara.fish/community/docs/General%20Info/Supported%20Platforms.html
Addresses https://github.com/payara/Payara/issues/6059
None
None
Compiled Payara, checked README is correct in distributions
Zulu JDK 8, Maven 3.6.3, Windows 10
N/A
=> FISH-6748 Add JDK 17 support to README

appserver/packager/appserver-base/src/main/docs/README.txt
Adds mention of JDK 17 support to README file in Payara distribution, taken from https://docs.payara.fish/community/docs/6.2022.1/General%20Info/Supported%20Platforms.html
Addresses https://github.com/payara/Payara/issues/6059
None
None
Compiled Payara, checked README is correct in distributions
Zulu JDK 11, Maven 3.6.3, Windows 10
N/A
=> FISH-6748 (P6) Add JDK 17 support to README

appserver/web/web-core/src/main/java/org/apache/catalina/connector/CoyoteAdapter.java
Security fix.
It was possible to circumvent JACC authentication using a `./` traversal, since the request normalisation which normally stops these attacks actually happens _after_ the JACC check has occurred. So while the path is normalised as expected, the actual JACC check has already occurred and passed when it would fail against the normalised path.
This PR reactivates the old normalisation in the CoyoteAdapater which was commented out many many moons ago without explanation when integrating Grizzly with the forked Tomcat in the days of GlassFish 2 & 3.
What happens now is that if a request which would fail its normalisation checks occur, a HTTP 400 request is returned. This is, from a quick scan of their code, in line with how Tomcat / Catalina functions today.
The criteria for …
=> FISH-6775 Authorization Constraints Ignored When Using Path Traversal Penetration Using Default Virtual Module

appserver/web/web-core/src/main/java/org/apache/catalina/connector/CoyoteAdapter.java
Security fix.
It was possible to circumvent JACC authentication using a `./` traversal, since the request normalisation which normally stops these attacks actually happens _after_ the JACC check has occurred. So while the path is normalised as expected, the actual JACC check has already occurred and passed when it would fail against the normalised path.
This PR reactivates the old normalisation in the CoyoteAdapater which was commented out many many moons ago without explanation when integrating Grizzly with the forked Tomcat in the days of GlassFish 2 & 3.
What happens now is that if a request which would fail its normalisation checks occur, a HTTP 400 request is returned. This is, from a quick scan of their code, in line with how Tomcat / Catalina functions today.
The criteria for …
=> FISH-6775 Authorization Constraints Ignored When Using Path Traversal Penetration Using Default Virtual Module (Payara6)

appserver/distributions/payara-ml/pom.xml, appserver/distributions/payara-web-ml/pom.xml, appserver/distributions/payara-web/pom.xml, appserver/distributions/payara/pom.xml, appserver/extras/docker-images/pom.xml, appserver/packager/appserver-base/pom.xml, appserver/packager/external/libpam4j/pom.xml, appserver/pom.xml, nucleus/pom.xml
Pam4j is missing the required JNA dependency in the packager 
Latest JNA so it runs on apple silicon.
Only other possibility is to put JNA in modules/ putting it in lib/ doesn’t work 
fixes #5581 
Mac, Linux
=> FISH-6578 added jna required dependency to packager and upgraded it to latest

appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/cdi/CdiInitEventHandler.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/cdi/JsonWebTokenProducer.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/cdi/JwtAuthCdiExtension.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/JWTAuthenticationMechanism.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jwt/JsonWebTokenImpl.java, appserver/tests/payara-samples/samples/microprofile-endpoints/secure/src/test/resources/post-boot-commands.txt, appserver/tests/payara-samples/samples/reproducers/src/main/java/fish/payara/samples/mpjwt/fish6022/JaxrsApplication.java, appserver/tests/payara-samples/samples/reproducers/src/main/java/fish/payara/samples/mpjwt/fish6022/PublicServlet.java, appserver/tests/payara-samples/samples/reproducers/src/main/java/fish/payara/samples/mpjwt/fish6022/RootResource.java, appserver/tests/payara-samples/samples/reproducers/src/test/java/fish/payara/samples/mpjwt/fish6022/InvalidTokenOnPublicEndpointTest.java, appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/AuthenticatorBase.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/security/web/GlassFishSingleSignOn.java
Port of #6021 and #6053 for Payara6
=> FISH-6022 FISH-6299 FISH-6047: Payara 6 port for JWT and SSO issues

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModule.java
When starting a new instance, the following warning is logged: 
`Ignoring invalid property default-web-xml = /home/james/workspace/payara5/glassfish/nodes/localhost-domain1/Dull-Piranha/config/default-web.xml`
This fix prevents this from happening and sets the default-web.xml property. This changes nothing functionally, as this property is already correctly configured by the time it reaches `vs.setDefaultWebXmlLocation(value);`. This also explains why it was observed this warning doesn't impact any functionality on the server.
N/A
N/A
Started the server, created a new instance and observed the logs.
Windows 10, Maven 3.6.3, JDK 8
N/A
=> FISH-6066 Invalid property 'default-web-xml' on instance start-up

appserver/extras/embedded/build.xml
As found in FISH-6578, the jar limit is 65535 entries. Payara 6 and Payara Enterprise both exceeded this limit and so required this property for https://github.com/payara/Payara-Enterprise/pull/719 and https://github.com/payara/Payara/pull/6082 respectively to compile. This same error was not observed in Payara 5 Community, but this PR keeps the distributions aligned.
None
None
Unable to test this as the error doesn't yet occur on Community
Maven 3.6.3, Windows 10, JDK 8
N/A
N/A
=> Embedded Use Zip64 Format

nucleus/pom.xml
Upgrades GlassFish management to 3.2.3 porting existing payara patches.
Requires https://github.com/payara/patched-src-gmbal-commons/pull/2 to be merged and released
None
Started the server, created an instance and deployed an application
Maven 3.6.3, Windows 10, JDK 8
N/A
N/A
=> FISH-6717 Upgrade GlassFish Management to 3.2.3.payara-p1

appserver/distributions/payara-ml/pom.xml, appserver/distributions/payara-web-ml/pom.xml, appserver/distributions/payara-web/pom.xml, appserver/distributions/payara/pom.xml, appserver/extras/docker-images/pom.xml, appserver/extras/embedded/build.xml, appserver/packager/external/libpam4j/pom.xml, appserver/pom.xml, nucleus/pom.xml
Pam4j is missing the required JNA dependency in the packager
Latest JNA so it runs on apple silicon.
Only other possibility is to put JNA in modules/ putting it in lib/ doesn’t work
Needs additional commit 6f1b7b1 which community did not need to prevent `error creating jar archive contains more than 65535 entries`
Payara 6 port of community contribution: https://github.com/payara/Payara/pull/5961
Fixes: https://github.com/payara/Payara/issues/5581
None
Tested server starts as expected, created new instance and deployed application
Maven 3.6.3, JDK 11, Windows 10
N/A
N/A
=> FISH-6578 (P6) added jna required dependency to packager and upgraded it to latest

nucleus/pom.xml
Upgrades GlassFish management to 3.2.3 porting existing payara patches.
Requires https://github.com/payara/patched-src-gmbal-commons/pull/2 to be merged and released
None
Started the server, created an instance and deployed an application
Maven 3.6.3, Windows 10, JDK 11
N/A
N/A
=> FISH-6714 (P6) Upgrade GlassFish Management to 3.2.3.payara-p1

pom.xml
Title.
Reverting Mojarra seems to cause CDI to have issues. Removing Weld seems to fix this.
=> Revert "FISH-6685 Upgrade weld"

appserver/load-balancer/admin/pom.xml, appserver/packager/glassfish-common-web/pom.xml, appserver/persistence/cmp/ejb-mapping/pom.xml, appserver/persistence/cmp/support-ejb/pom.xml, appserver/pom.xml
Upgrade Schema2Beans to 6.7. Note that the package name has changed.
None
None
Payara Samples and quicklook tests
Zulu JDK 11 on Ubuntu 18.04 with Maven 3.8.4
This upgrade was based on this glassfish commit:
https://github.com/javaee/glassfish/commit/cc77df384d17bee7f573f475ac3d4952307a3126
=> FISH-6722 : schema2beans upgraded to version 6.7

appserver/packager/glassfish-cmp/pom.xml, appserver/persistence/cmp/generator-database/pom.xml, appserver/persistence/cmp/model/pom.xml, appserver/pom.xml
Upgrade DBSchema from 3.1.1 to 6.7. Note that the package name has changed.
None
None
Payara Samples and quicklook tests
Zulu JDK 11 on Ubuntu 18.04 with Maven 3.8.4
This upgrade was based on this glassfish commit:
https://github.com/javaee/glassfish/commit/cc77df384d17bee7f573f475ac3d4952307a3126
=> FISH-6721 : dbschema version upgraded to 6.7

appserver/web/web-core/src/main/java/com/sun/enterprise/web/connector/grizzly/CoyoteConnectorLauncher.java, appserver/web/web-core/src/main/java/fish/payara/appserver/web/core/CatalinaRequest.java, appserver/web/web-core/src/main/java/fish/payara/appserver/web/core/CatalinaResponse.java, appserver/web/web-core/src/main/java/fish/payara/appserver/web/core/GrizzlyCatalinaBridge.java, pom.xml
Updates Catalina to 10.1.1, fixing new compilation errors in `web-core`, `web-glue` and `websecurity`. Unable to test this further as the branch doesn't compile.
Can't upgrade to Catalina 10.1.2 as this bug is present https://bz-he-de.apache.org/bugzilla/show_bug.cgi?id=66353 causing test failures. 10.1.3 will fix this when it's released
=> FISH-5971 Upgrade Catalina to 10.1.1

appserver/extras/embedded/build.xml
Payara Enterprise Embedded All exceeded the 65,535 file limit for a zip/jar so Zip64 was required. This however caused an invalid cen header / class not found exception for all other embedded distributions. This specifically only impacted Payara 5 on JDK 8. It appears to be related to this JDK bug which was fixed in JDK 10 https://bugs.openjdk.org/browse/JDK-8186464 hence only affecting JDK 8.
Use the 'as-needed' option instead so there is no issue with jars containing fewer than 65,535 files but will use Zip64 for distributions with more files, allowing both to compile and run as expected.
Tested Embedded Web & Embedded All manual test.
Ubuntu 20 (WSL), Zulu JDK 11, Maven 3.6.3
N/A
=> FISH-6578 Use Zip64 as-needed

pom.xml
This change of Mojarra uses regex for jakarta/javax copy of POST headers.
Using startsWith failed in Faces TCK, when some option was in fact an event.
Faces TCK
OpenJDK, Linux
=> FISH-6596 Upgrade Mojarra to Patched Source 4.0.0-p2

appserver/connectors/admin/src/main/java/org/glassfish/connectors/admin/cli/ConnectorConnectionPoolManager.java
When the `create-connector-connection-pool` command is executed currently it fails when environment variables are used as there is no substitution in place. With this change before the properties are set a full variable replacement check is performed.
Started the server, set the NUM environment variable to 20, ran the relevant command below:
**Windows (cmd)**
`asadmin create-connector-connection-pool --connectiondefinition=jakarta.jms.ConnectionFactory --transactionSupport=NoTransaction --resourceAdapterName=jmsra --maxpoolsize=${ENV=NUM}`
**Windows (Windows Terminal / Poweshell)**
_Remove the spaces in ${ENV=NUM} - These were necessary to keep the backticks_ 
``asadmin create-connector-connection-pool --connectiondefinition=jakarta.jms.ConnectionFactory --transactionSupport=NoTransaction …
=> FISH-1413 (P6) Perform variable substitution for create-connector-connection-pool

appserver/web/web-core/src/main/java/org/apache/catalina/connector/CoyoteAdapter.java
Update to https://github.com/payara/Payara/pull/6079 based on feedback from GlassFish.
Reworks the solution so that exceptions aren't used.
Also fixes the detail message so that it actually gets set.
None
None
_Pending_
* Ran the reproducer for FISH-6775
WSL, JDK 8
N/A - internal
None
=> FISH-6775 Update

pom.xml
Sets the Jakarta version to 10.0.0 for the platform and web APIs in the BOM/API.
None
None
Built the server, maven didn't complain.
Windows 11, Zulu JDK 11.
N/A
None
=> Set Jakarta Version to 10.0.0

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/deploy/ContextResourceDecorator.java
Resolves compilation error in ContextResourceDecorator where ContextResource appears to have been moved to https://github.com/apache/tomcat/blob/main/java/org/apache/tomcat/util/descriptor/web/ContextResource.java. The very core of this appears to be identical with a few new fields with the respective getter and setter methods
=> FISH-6151 Resolve ContextResourceDecorator Compilation Errors

appserver/pom.xml
Title.
None
None
Built server, started DAS.
Windows 11, Zulu JDK 11.0.17 and 17.0.5
N/A
Whomever previously patched accessors-smart forgot to make a maintenance branch and tag, so I have no way of knowing what was actually changed - my best guess is increasing the version of ASM used (which should no longer be required, 2.4.8 uses 9.1)
=> FISH-7025 accessors-smart 2.4.8

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/deploy/ErrorPageDecorator.java
Resolves compilation errors in ErrorPageDecorator. 
ErrorPage has moved to https://github.com/apache/tomcat/blob/10.1.x/java/org/apache/tomcat/util/descriptor/web/ErrorPage.java
RequestUtil.urlDecode has been replaced with UDecoder.URLDecode. This always requires a charset so to maintain previous behaviour I have set this to null as was previously happening https://github.com/apache/tomcat/blob/7.0.x/java/org/apache/catalina/util/RequestUtil.java#L178 
The same null charset behaviour was maintained https://github.com/apache/tomcat/blob/10.1.x/java/org/apache/tomcat/util/buf/UDecoder.java#L186
=> FISH-6152 Resolve Compilation Errors in ErrorPageDecorator

appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/SignedJWTIdentityStore.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jwt/JwtTokenParser.java
New feature on JWT 2.1 to read token age and clock skew properties. I also remove major code smells on method `JwtTokenParser.verifyAndParseSignedJWT` by introducing a new method `JwtTokenParser.verifySignedJWT` to reduce the complexity
MP JWT TCK runner - https://github.com/payara/MicroProfile-TCK-Runners/pull/209
TokenAgeTest - https://github.com/payara/MicroProfile-TCK-Runners/pull/209
Build and run Payara server and execute MP JWT TCK on local machine
N/A
None
=> FISH-6978 Add support for restricting token age and clock skew for MP JWT 2.1

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/CacheModule.java
Resolves the compilation errors in CacheModule. FilterDef and FilterMap were part of `web-core` which was removed, I believe these changes will maintain the original behaviour although they are different.
FilterDef `setFilterClassName` was replaced with `setFilterClass` however these both take strings and appear to be doing the same function. A null check is lost, however `CACHING_FILTER_CLASSNAME` is a static final string so could never be null hence I didn't feel the need to re-implement this.
Rather than a FilterMap having one servlet name and URL pattern, it instead has two lists which I have modified by adding rather than setting these properties. `setDispatcherTypes` with an EnumSet of DispatcherType is completely removed, being replaced with `setDispatcher` requiring a string. This …
=> FISH-6167 Resolve Compilation Errors in CacheModule

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/OASFactoryResolverImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/media/SchemaImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/util/ModelUtils.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/BaseProcessor.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/FilterProcessor.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ModelReaderProcessor.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/visitor/OpenApiContext.java, appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/impl/model/OpenApiBuilderTest.java, appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/resource/rule/ApplicationProcessedDocument.java, appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/spec/NodeType.java, appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/test/app/application/SchemaExampleTest.java, pom.xml
Adding support of additionalProperties to the generated OpenApi documentation.
If additionalProperties is not specified in the `@Schema` annotation, it is supposed to be True, but it is not mentioned in the displayed documentation (it's the default value).
If explicitly specified, it is always displayed, either true or false.
Deploy the reproducer attached to the Jira ticket to Payara and open `http://localhost:4848/openapi` in browser.
The key parts of the source:
```
@Schema(description = "no additionalProperties defined, shouldn't appear in OpenApi description")
public static class WithoutAdditionalProperties {
@Schema(additionalProperties = Schema.True.class, description = "additionalProperties defined as true, should appear as 'additionalProperties: true'")
public static class …
```
=> FISH-6768 display additionalProperties if specified

appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/eesecurity/SignedJWTIdentityStore.java, appserver/payara-appserver-modules/microprofile/jwt-auth/src/main/java/fish/payara/microprofile/jwtauth/jwt/JwtTokenParser.java
Fix MP JWT TCK `RolesAllowedSignEncryptRsaOaepTest` test by read optional `mp.jwt.decrypt.key.algorithm` config property and validate the key algorithm
MP JWT TCK Runner - https://github.com/payara/MicroProfile-TCK-Runners/pull/211
New test class added to MP JWT TCK - https://github.com/payara/MicroProfile-TCK-Runners/pull/211
Build, run and execute MP JWT TCK
N/A
None
=> FISH-6979 Add support for RSA-OAEP-256 for MP JWT 2.1

api/payara-bom/pom.xml, api/payara-core-bom/pom.xml, appserver/ejb/ejb-full-container/pom.xml, appserver/monitoring-console/core/pom.xml, appserver/payara-appserver-modules/yubikey-authentication/pom.xml, appserver/tests/payara-samples/samples/clustered-singleton/clustered-singleton-test/pom.xml, appserver/tests/payara-samples/samples/ejb-http-remoting/pom.xml, appserver/tests/payara-samples/samples/multiple-keystores/pom.xml, appserver/tests/payara-samples/samples/opentelemetry/pom.xml, appserver/tests/payara-samples/samples/opentelemetry/src/main/java/fish/payara/samples/otel/manual/InitializeOtel.java, appserver/tests/payara-samples/samples/opentelemetry/src/main/java/fish/payara/samples/otel/manual/ManualTracing.java, appserver/tests/payara-samples/samples/opentelemetry/src/main/java/fish/payara/samples/otel/manual/ManuallyTracingServlet.java, appserver/tests/payara-samples/samples/opentelemetry/src/main/resources/META-INF/microprofile-config.properties, appserver/tests/payara-samples/samples/pom.xml, appserver/tests/payara-samples/samples/remote-ejb-tracing/pom.xml, appserver/tests/payara-samples/samples/reproducers/pom.xml, appserver/tests/payara-samples/samples/rolesallowed-unprotected-methods/pom.xml, nucleus/packager/external/opentelemetry-repackaged/pom.xml, nucleus/packager/external/pom.xml, nucleus/packager/requesttracing-package/pom.xml, nucleus/payara-modules/opentracing-adapter/pom.xml, nucleus/payara-modules/opentracing-adapter/src/main/java/fish/payara/opentracing/OpenTelemetryService.java, pom.xml
This brings OpenTelemetry APIs and default implementations into server as basis for implementing MP Telemetry and redoing opentracing support via shim.
Applications can now manually bootstrap OTEL SDK and use the tracer. OTLP export via GRPC and HTTP works. It is possible to add additional components into `domaindir/lib` and have autoconfiguration bootstrap them properly.
New samples module will be basis for adding arquillian tests. So far the test has been only manual using this exact application.
* Deploy the sample application, observe OTLP traces appearing in Jaeger (via its native OTLP collection endpoint)
* Configure tracing via API
* Configure tracing via autoconfiguration, providing properties from MP config (one of MP Tracing requriements)
* Add jar for logging exporter into …
=> FISH-6966: Package Opentelemetry into distribution

pom.xml
In this PR, a few performance optimizations have been done.
- File canonicalization cache is disabled by default in JDK 12 which helps in performance optimizations for file name canonicalization. In HK2, TypeImpl#addDefiningURI duplicate uri is added so canonicalization is not required.
Manually with reproducer
Windows 11, and WSL
JDK 11, 12, and 17
https://github.com/payara/patched-src-hk2/pull/29
=> FISH-6432 Applications Take Longer To Deploy on JDK 11 and 17 (Payara 5.x)

appserver/persistence/cmp/support-sqlstore/src/main/java/com/sun/jdo/spi/persistence/support/sqlstore/connection/ConnectionImpl.java, appserver/persistence/cmp/support-sqlstore/src/main/java/com/sun/jdo/spi/persistence/support/sqlstore/connection/ConnectionManager.java, appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/LogFileHandle.java, appserver/web/web-core/src/main/java/org/apache/catalina/fileupload/PartItem.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/ASURLClassLoader.java, nucleus/common/common-util/src/main/java/org/glassfish/admin/payload/PayloadFilesManager.java, nucleus/deployment/common/src/main/java/com/sun/enterprise/deployment/deploy/shared/InputJarArchive.java, nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/ClientArtifactsManager.java, nucleus/payara-modules/healthcheck-cpool/src/main/java/fish/payara/nucleus/healthcheck/cpool/ConnectionPoolHealthCheck.java, pom.xml
In this PR, a few performance optimizations have been done.
- The finalize methods of FileInputStream, FileOutputStream, Zip Inflator, and Deflator were deprecated for removal in JDK 9. They have been removed in JDK12 release, which may cause resources are not cleaned and leaked.
- File canonicalization cache is disabled by default in JDK 12 which helps in performance optimizations for file name canonicalization. In HK2, TypeImpl#addDefiningURI duplicate uri is added so canonicalization is not required.
Manually with reproducer
Windows 11, and WSL
JDK 11, 12, and 17
https://github.com/payara/patched-src-hk2/pull/28
=> FISH-6432 Applications Take Longer To Deploy on JDK 11 and 17

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/api/visitor/ApiVisitor.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/OpenAPIImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/security/SecurityRequirementImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ApplicationProcessor.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/visitor/OpenApiWalker.java
Handling annotation @SecurityRequirementSet and property securitySet
None
1. Deploy the reproducer-6766.zip attached on https://payara.atlassian.net/browse/FISH-6766
2. Poke localhost:8080/openapi
3. Check the yaml result... It should contain:
security:
- airlinesRatingApp_auth: []
**- testScheme1: []
- testScheme2: []**
into openapi and also into /user/login -> get
it also should have:
security:
- httpSchemeForTest: []
**- userApiKey: []
- userBearerHttp: []**
inside /user/{username} -> patch
The tests where based in TCK: 
https://github.com/eclipse/microprofile-open-api/pull/519/files#diff-0b001a0b97f0f3eecd10d2d39d7de2a15716bd7b95885244e0f3802f36d7cb3d
=> Fish 6766 : Support new security requirement constructs for MP OpenAPI 3.1

appserver/ejb/ejb-opentracing/src/main/java/fish/payara/ejb/opentracing/OpenTracingIiopServerInterceptor.java, appserver/payara-appserver-modules/microprofile/opentracing/src/main/java/fish/payara/microprofile/opentracing/cdi/TracedInterceptor.java, appserver/tests/payara-samples/samples/opentelemetry/README.adoc, appserver/tests/payara-samples/samples/opentelemetry/pom.xml, appserver/tests/payara-samples/samples/opentelemetry/src/main/java/fish/payara/samples/otel/manual/ManualTracing.java, appserver/tests/payara-samples/samples/remote-ejb-tracing/src/test/java/fish/payara/samples/remote/ejb/tracing/RemoteEjbClientIT.java, nucleus/packager/external/opentracing-repackaged/pom.xml, nucleus/payara-modules/opentracing-adapter/pom.xml, nucleus/payara-modules/opentracing-adapter/src/main/java/fish/payara/opentracing/OpenTelemetryService.java, nucleus/payara-modules/opentracing-adapter/src/main/java/fish/payara/opentracing/OpenTracingService.java, nucleus/payara-modules/opentracing-adapter/src/main/java/fish/payara/opentracing/PayaraRequestTracingExporter.java, nucleus/payara-modules/opentracing-adapter/src/test/java/fish/payara/opentracing/OpenTelemetryTraceConversionTest.java
As transitional step, we use OpenTracing shim to bridge all use of opentracing in the server with OpenTelemetry.
Whenever OpenTracing is used, OpenTelemetry SDK is auto-configured on per-application basis respecting system properties and environment variables.
So far there is no application API beyond using OpenTracing to get to OTEL, so they will arrive later
Payara Samples and OpenTracing TCKs should still pass without problems, let's see what Jenkins thinks about it.
=> FISH-6969: Use OpenTelemetry as basis for OpenTracing Support

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ApplicationProcessor.java, appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/test/app/application/EnumTest.java
Check conformance with @Schema(hide=true) for MP OpenAPI 3.1
None
None
1.  C:\Users\luise\git\Payara> git remote set-url origin https://github.com/luiseufrasio/Payara/ 
2. git fetch
3. git checkout -b FISH-6767-schema-hide-true origin/FISH-6767-schema-hide-true
4. mvn clean install -DskipTests
5. ./appserver/distributions/payara/target/stage/payara6/bin/asadmin start-domain -v
6. poke localhost:4848
7. deploy the reproducer attached here: https://payara.atlassian.net/browse/FISH-6767 
8. open another terminal
9. curl http://localhost:8080/openapi?format=json | jq '.paths."/user/special".post.requestBody.content."application/json".schema'
10. curl http://localhost:8080/openapi?format=json | jq '.paths."/user/special".post.requestBody.content."application/json"'
11. curl …
=> Fish 6767 schema hide true

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/config/OpenApiConfiguration.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/media/SchemaImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/util/ModelUtils.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/FilterProcessor.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ModelReaderProcessor.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/visitor/OpenApiContext.java
OpenAPI refined the rules for usage of lists, specifying scanning or excluding classes for OpenAPI.
OpenAPI TCK, all tests (which deploy) for the scanning rules pass, total number of failing issues decreased from 18 to 4.
Linux, OpenJDK
The first commit is functional, the other just code formatting, removing majority of compiler warnings.
Getters and setters were removed as they are not used and the data is only internal.
=> FISH-6975 OpenAPI Scanning Rules

api/payara-bom/pom.xml, appserver/admingui/common/pom.xml, appserver/packager/microprofile-package/pom.xml, appserver/payara-appserver-modules/rest-monitoring/rest-monitoring-war/pom.xml, appserver/security/core-ee/pom.xml, pom.xml
Payara BOM declared `jakarta-web-api` version of 9.1.0, as well as for Platform BOM. This was an oversight where we in fact had two properties for platform version.
It also address eclipse-ee4j/jakartaee-api#133, where we exclude the transitional dependencies by default.
=> FISH-7063: Use only single property for Jakarta API version

appserver/security/core-ee/src/main/java/com/sun/enterprise/security/auth/realm/jdbc/JDBCRealm.java
Setting JDBC Realm is a bit frustrating, because only successful login verifies the settings. In case of problems, setting  logger `javax.enterprise.system.core.security` to the `FINEST` level helps. But if the user is not logged in, only debugging server help to find why.
Therefor I added logging if user wasn't found of if password didn't match. Username is logged, password is not.
All these logs are done on the `FINEST` level.
Switch logger  `javax.enterprise.system.core.security` to the `FINEST` level
Setup JDBC Realm, take app using it, try to login with 
1) non-existing user, logs: `User 'abc' not found in the database!`
2) wrong password, logs: `User 'abc' password mismatch!`
It's necessary to search the log entry, running admin gui fills it quickly at this level.
Linux, OpenJDK
=> Log JDBC Realm Login Failures, User Not Found or Password Mismatch

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/ComponentsImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/ExtensibleImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/ExtensibleTreeMap.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/ExternalDocumentationImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/OpenAPIImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/OperationImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/PathItemImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/examples/ExampleImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/headers/HeaderImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/info/ContactImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/info/InfoImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/info/LicenseImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/links/LinkImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/media/ContentImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/media/EncodingImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/media/SchemaImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/parameters/ParameterImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/parameters/RequestBodyImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/responses/APIResponseImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/responses/APIResponsesImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/security/OAuthFlowImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/security/OAuthFlowsImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/security/SecuritySchemeImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/servers/ServerImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/servers/ServerVariableImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/tags/TagImpl.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/util/ModelUtils.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ApplicationProcessor.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/visitor/OpenApiWalker.java, appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/impl/model/ModelInvariantsTest.java
Adding support
Going through MP OpenApi TCK -- test, which deploy (yes, the TCK is broken) pass!
There is a setup required -- disable https (Configurations, server-config, Network Config, edit http-listener-2, set disabled; this is registered as second server, tests expectat only one server, specifically `testStaticDocument`).
Linux, OpenJDK
It was necessary to distinguish between "no extensions defined" and "empty extensions defined". The TCK requires, that annotation `@Extension` is propagated to `@APIResponses/@APIResponse`, but only if not defined. In the next code:
```
@APIResponses(extensions = @Extension(name = "x-responses-ext", value = "test-responses-ext"), value = {
@APIResponse(responseCode = "200", description = "successful operation",
extensions = @Extension(name = …
```
=> FISH-6769 OpenApi Support for 'extensions'

pom.xml
No functional changes for Payara Community, however this keeps the version used in-line with Payara 6 Enterprise
Requires https://github.com/payara/transformer/pull/33 approving, merging and Transformer 1.2 releasing
N/A
Compiled Transformer Impl 1.2, added it to `payara6/glassfish/modules`, started the server, deployed a Java EE 8 application (clusterjsp.war) and confirmed successful transformation and deployment.
Windows 10, Zulu JDK 11, Maven 3.6.3
N/A
This PR has accidentally been pushed to the main repository rather than a fork and I don't have permissions to delete this branch, after merging please delete this branch
=> FISH-6627 Use Transformer 1.2

appserver/extras/docker-images/pom.xml
Updates the JDK image used for the Payara Docker images to the latest.
None
None
Ran the unit tests against 6.2023.2
Windows 11
N/A
None
=> FISH-7153 FISH-7155 Docker JDK 11.0.18 & 17.0.6

pom.xml
This is a bug fix / feature. Eclipse link patched version updated
https://github.com/payara/patched-src-eclipselink/pull/24
The steps defined in https://payara.atlassian.net/browse/FISH-7076
But at the end it should return NOT_FOUND instead of an Exception
- Quicklook
- Jakarta TCKs
- Mojarra
Zulu JDK 11.0.17 on Windows 10 with Maven 3.8.4
=> FISH-7076 : eclipselink version upgraded

appserver/packager/appserver-base/src/main/docs/README.txt
With the merging of [FISH-1366: Upgrade cacerts.jks and keystore.jks to pkcs12IN COMMUNITY REVIEW](https://payara.atlassian.net/browse/FISH-1366) the minimum requirement within the bundled README and in the docs should be changed to JDK 11.0.12+
=> FISH-7115 : jdk 11 min version upgraded

nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java, nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/StartServerHelper.java
Fix for zombie instance when ports are used from another instance
This is a fix for a bug reported when trying to start an instance from a deployment group trying to use ports used for another available running instance like payara micro
Manual testing, now the error is showed on the logs when trying to start the instance:
https://user-images.githubusercontent.com/279375/223603704-657331b5-e86e-4c8c-a0db-033184b336be.mp4
On logs now we can see the following message:
`
Command start-local-instance failed.
Port 28080 is in use
To complete this operation run the following command locally on host localhost from the Payara Server install location C:\java\projects\Payara\appserver\distributions\payara\target\stage\payara6:
lib/nadmin  start-local-instance --node localhost-domain1 --sync normal …
=> FISH-7016: adding fix when ports are used from another instance

appserver/admingui/common/src/main/resources/js/adminjsf.js
Fixes the bug that when selecting a locally available file for deployment the file path gets left blank, causing an error when you then try to proceed the deployment.
None
None
* Deploy a locally available file
* Applications -> Deploy -> Local Packaged File or Directory -> Browse Files -> _select file_ -> Choose File
* File path should be populated
* Click deploy
* Should succeed
* Redeploy a locally available file
* Applications -> Click on application -> Redeploy -> Local Packaged File or Directory -> Browse Files -> _select file_ -> Choose File
* File path should be populated
* Click deploy
* Should succeed
* Deploy an uploaded file (the "default" way to deploy)
* Applications -> Deploy -> Upload -> _select file_
* Click deploy
* Should succeed
N/A
Make sure …
=> FISH-7077 Fix Blank File Path on Deployment

pom.xml
To test the upgrade:
- Download the project below [demo-payara-spring6 (1).zip](https://github.com/payara/Payara/files/11015235/demo-payara-spring6.1.zip)
- Extract and compile with Maven
- Run the project using Payara Micro 6.2023.3-SNAPSHOT
- Check the log details and make sure the exception is not shown `java.lang.UnsupportedOperationException: PermittedSubclasses require ASM9`
Related PR: https://github.com/payara/patched-src-hk2/pull/30
=> FISH-6931 Upgrade ASM to v9.4

pom.xml
Upgrade Eclipselink to Use Final Release Version
None
None
Payara Samples
Quicklook
Zulu JDK 11.0.11 on Ubuntu 18.04 with Maven 3.8.4
None
=> FISH-6583 : using new eclipselink version

nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/CollectionLeafResource.java
Unable to create JVM option using Web UI
Getting Exception “JVM option${ } already exists in the configuration” upon creating JVM option using WEB UI.
1. mvn clean install -T 14 -DskipTests
2. .\appserver\distributions\payara\target\stage\payara6\bin\asadmin start-domain -v
3. Navigate to Payara -> Server config-> JVM Settings -> Jvm Options Tab
4. Click on "Add Jvm Option" button
5. Type: -Dhttps.nonProxyHosts="localhost|127.0.0.1|10.*.*.*|*.fmp-fbz.fgov.be|*.fedris.be|*.faofat.fgov.be"
6. Click on Save button
7. Click on "Add Jvm Option" button
8. Type: -Dhttp.nonProxyHosts="localhost|127.0.0.1|10.*.*.*|*.fmp-fbz.fgov.be|*.fedris.be|*.faofat.fgov.be"
9. Click on Save button
- Quicklook
- Samples
Zulu JDK 11.0.11 on Windows 11 with Maven 3.8.4
=> Fish 7127 unable to create jvm option

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/api/visitor/ApiContext.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/OpenAPISupplier.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/config/OpenApiConfiguration.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ApplicationProcessor.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/visitor/OpenApiContext.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/visitor/OpenApiWalker.java, appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/impl/visitor/OpenApiWalkerTest.java, appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/resource/rule/ApplicationProcessedDocument.java
If mp.openapi.extensions.scan.lib is set to true, include libraries from EAR (lib/*.jar) to schema scanning. Resources are processed only from the WAR file.
Also old error when for `mp.openapi.extensions.scan.lib=false` it wrongly generated reference to a library class (e.g. dangling reference).
Reproducer app
OpenAPI TCK for `mp.openapi.extensions.scan.lib` both `true` and `false`.
[Doc update](https://github.com/payara/Payara-Documentation/pull/238)
Deploy the reproducer app in the Jira ticket.
```
mvn clean install && /path-to-payara/payara6/bin/asadmin deploy --force MultiWarEar-ear/target/MultiWarEar-ear-1.0-SNAPSHOT.ear
```
Set config value (Configurations/server-config/Microprofile/Property) `mp.openapi.extensions.scan.lib` to `true`. Open …
=> FISH-6980 scan ear's lib/*.jar for openapi

appserver/packager/external/pom.xml, nucleus/packager/external/pom.xml
Some extensions seem to transitively depend on them.
This may be a case of dependency leaking which we should fix at some point - but we'd need to do a big review before we determine that. This is simply a workaround for now.
None
N/A
Made a local "deploy" directory: `mkdir /home/andrew/Downloads/Deploy`
Tested a deployment: `mvn clean deploy -Dmaven.test.skip=true -Pdeploy-internals,BuildExtras -DaltDeploymentRepository=local::file:///home/andrew/Downloads/Deploy -T 1C`
Checked that the deploy directory contained the nucleus/packager/external and appserver/packager/external packages.
WSL
N/A
None
=> Deploy Repackaged Modules

nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/LocalServerCommand.java, nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/domain/DomainConstants.java, nucleus/admin/server-mgmt/src/main/java/fish/payara/admin/servermgmt/cli/AddKeypairCommand.java
During verification of master password, load `cacerts.jks` if `cacerts.p12` is not found
After the transition to key/truststores to P12 format, server doesn't start if the stores are in JKS.
This change allows to start the server and serve HTTPS.
After building this PR, replace both *.p12 files in `appserver/distributions/payara/target/stage/payara6/glassfish/domains/domain1/config` (`cacerts` and `keystore`) with their jks version (e.g. from Payara 5 build).
Also change the names in `domain.xml`:
```
<jvm-options>-Djavax.net.ssl.keyStore=${com.sun.aas.instanceRoot}/config/keystore.jks</jvm-options>
```
Start the server normally and try all ports: 8080, 8181, 4848
=> FISH-6504 Load cacerts.jks if p12 is not Found

nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/PayaraHazelcastTenantFactory.java
Picks [this commit](https://github.com/payara/Payara/commit/284d69375fb02b100b5cf275b730f0ce59b431b2) back into master, since it was unintentionally reverted.
Fixes #6259 
None
None
Created a deployment group with two instances, deployed clusterjsp with availability enabled, checked that session data is persisted across Hazelcast.
Windows 11, Zulu 11.
https://github.com/payara/Payara-Documentation/pull/255
None
=> FISH-7337 Don't Block Hazelcast by Default

nucleus/hk2/hk2-config/src/main/java/org/jvnet/hk2/config/ConfigParser.java
Cherry-picks across some changes from Payara 5 which never made it to Payara 6, related to preventing the config parser from spamming warnings.
None
None
See Enterprise PR: https://github.com/payara/Payara-Enterprise/pull/828
See Enterprise PR: https://github.com/payara/Payara-Enterprise/pull/828
N/A
None
=> FISH-7291 Cherry-pick Missed Commits from Payara 5

nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/KeystoreManager.java, nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/ChangeMasterPasswordCommandDAS.java, nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/LocalServerCommand.java, nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/pe/PEFileLayout.java, nucleus/admin/util/src/main/java/com/sun/enterprise/admin/remote/RemoteRestAdminCommand.java
After Payara upgrade from P5 to P6, keystore and cacerts remain in the JKS format.
This PR fixes change-master-password command, so it accepts JKS keystores.
I tried to use old domain with jks keystores (e.g. no p12 files in domain/config) and copied it to Payara from this PR.
Then try
```
./asadmin change-master-password
```
Verification can be done with second run or with `keytool` in the domain/config directory:
```
keytool -list --keystore cacerts.jks
keytool -list --keystore keystore.jks
```
The new password is required.
Linux, OpenJDK 8 and 11
=> FISH-7359 Fix change-master-password for JKS Keystores

appserver/security/jacc.provider.inmemory/src/main/java/fish/payara/security/jacc/provider/compatibility/JaccProviderCompatibilityStartup.java
Upgrade Service for JACC
Startup that checks if any domain.xml configuration has jacc provider values incompatibles with Payara since version 6. It replaces the default jacc provider and removes the old 'simple' one.
None
1. mvn clean install -T 14 -DskipTests
2. replace domain.xml file at C:\Users\luise\git\Payara\appserver\distributions\payara\target\stage\payara6\glassfish\domains\domain1\config by its Payara5 version attached in JIRA: https://payara.atlassian.net/browse/FISH-7096
3. .\appserver\distributions\payara\target\stage\payara6\bin\asadmin start-domain -v
4. poke localhost:4848
5. It should open correctly without "CNFE" on logs
- Quicklook
- Jakarta TCKs
- Mojarra
Zulu JDK …
=> FISH-7096 : old jacc providers renamed on startup

appserver/pom.xml
Upgrades JSON Smart to 2.4.10 to fix CVE-2023-1370
None
None
None
N/A
https://github.com/payara/Payara-Documentation/pull/260
None
=> FISH-7292 FISH-7374 JSON Smart 2.4.10

appserver/extras/docker-images/pom.xml
Upgrades the Docker image JDKs to 11.0.19 and 17.0.7
None
None
Built and started Docker images
Windows
N/A
None
=> FISH-7404 Upgrade Docker Image JDKs

nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/ASURLClassLoader.java
Fixes potential ClassLoader leaks that might be kept in the StackTrace reference of the internal `Throwable` in [ASURLClassLoader](https://github.com/payara/Payara/blob/master/nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/ASURLClassLoader.java#L1105).
Here is what we have in visualvm:
One can also note there is a lot of cleaner for `SentinelInputStream` pending.
Probably due to #6179.
- payara-embedded-all 6.2023.2
- JDK17
- Linux Debian Bullseye
=> FISH-7204 Removes internal ASURLClassLoader throwable reference to avoid ClassLoader leaks

appserver/web/web-glue/osgi.bundle, nucleus/hk2/hk2-config/osgi.bundle
While trying to [build](https://docs.payara.fish/community/docs/General%20Info/Build%20Instructions.html) Payara from source, after fixing the bundle plugin (#6262), I hit the following error:
```
[ERROR] Manifest fish.payara.server.core.hk2:hk2-config:glassfish-jar:6.2023.5-SNAPSHOT : package info for org.jvnet.hk2.config attribute [version~='6.2023.5 org.jvnet.hk2.config.provider.annotations'], key must be an EXTENDED (CORE1.3.2 [-.\w]+). From null
[ERROR] Manifest fish.payara.server.core.hk2:hk2-config:glassfish-jar:6.2023.5-SNAPSHOT : package info for org.jvnet.hk2.config attribute [version~~='6.2023.5'], key must be an EXTENDED (CORE1.3.2 [-.\w]+). From null
[ERROR] Error(s) found in manifest configuration
```
Some commas were missing but I tried to align the same declaration as in …
=> FISH-7331 [JDK17] Fixes HK2 config for compilation

appserver/admingui/common-l10n/osgi.bundle, appserver/admingui/core-l10n/osgi.bundle, appserver/admingui/war/pom.xml, appserver/admingui/webui-jsf-plugin-l10n/osgi.bundle, appserver/admingui/webui-jsf-suntheme-plugin-l10n/osgi.bundle
Fixes loading of the admin console following on from the name changes in https://github.com/payara/Payara/pull/6246
Without this, loading the admin console fails with the following error:
```
com.sun.enterprise.module.ResolveError: Not able to locate a unique module by name fish.payara.server.internal.admingui.console-common
```
None
None
Loaded the admin console
Windows, Zulu 11.0.19
N/A
I'm unsure ATM if we need to define the bundle version as something other than `${project.osgi.version}` - I guess we'll find out when we attempt to diverge the versions in the future.
=> FISH-6607 Fix Admin Console OSGi imports and Fragments

api/payara-api/pom.xml
The Maven module changes had the unintended side-effect of stopping this generation from happening - this fixes it.
None
None
Built payara-api - javadoc was generated.
WSL, Zulu 11
N/A
None
=> FISH-6607 Don't Skip Javadoc Generation of payara-api

appserver/ejb/ejb-http-remoting/client/pom.xml
With the changes from https://github.com/payara/Payara/pull/6246 we're skipping javadoc generation on EJB HTTP Client, breaking the release scripts. This fixes that.
None
None
Build the server using `mvn clean install` and checked up `appserver/ejb/ejb-http-remoting/client` and the javadoc was present
WSL
N/A
None
=> FISH-6607 Don't skip javadoc on EJB HTTP Client

appserver/ejb/ejb-http-remoting/client/pom.xml
With the changes from https://github.com/payara/Payara/pull/6246 we're skipping javadoc generation on EJB HTTP Client, breaking the release scripts. This fixes that.
None
None
Build the server using `mvn clean install` and checked up `appserver/ejb/ejb-http-remoting/client` and the javadoc was present
WSL
N/A
None
=> FISH-6607 Don't skip javadoc on EJB HTTP Client (Release)

nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigProviderResolverImpl.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/PayaraConfig.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/test/java/fish/payara/nucleus/microprofile/config/spi/PayaraConfigTest.java
Renaming variables according to their content and fix code accordingly. Also do synchronization only when setting data, otherwise use the fast path.
The problem was, that the config didn't cache at all and always did search for the DurationSeconds.
I use the reproducer from Jira ticket, using only the simple request (basically simple REST):
```
wrk -c 400 -t 400 -d 120 http://localhost:8080/jee-mongo/api/hello-world/
```
Comparison:
* Glassfish: `Requests/sec:   3543.07`
* Current Payara 6: `Requests/sec:   1400.88`
* This version: `Requests/sec:  35984.01`
Feel free to correct this result as it seems really to fast.
Linux, OpenJDK 11 (compile) 17 (run)
=> Fish 7426 fix payara config cache timing comm

pom.xml
Upgrading to the latest version of ASM allows Payara 5 to run on the latest Java 21.
Tested by replacing `asm-*` jars with their respective 9.5 versions downloaded from Maven Central. Ran Payara 5 with an internal build of Java 21 and verified that the server starts and can deploy applications.
macOS 12.6.3
I noticed the statement that no further community releases will be made from Payara 5, but considered this useful anyway in case someone wants to build from source. Also, this could be applied to any Enterprise offerings.
=> FISH-7341 Upgrade ASM from 9.4 to 9.5 to allow running on Java 21

appserver/tests/payara-samples/samples/rolesallowed-unprotected-methods/pom.xml, appserver/tests/payara-samples/samples/rolesallowed-unprotected-methods/src/test/java/fish/payara/samples/rolesallowed/unprotected/methods/RemoteEjbClientIT.java, core/pom.xml, pom.xml
Upgrade libs, fix RemoteEjbClientIT test by passing module-related arguments to tests, enhance the test by printing stacktrace in case of failure.
I compiled the server by Java 11.
I started the server by Java 21.
I ran Concurrency TCK - there is one failure due to changes in JDK (reported https://github.com/jakartaee/concurrency/issues/282), otherwise it runs well.
I ran Payara Samples:
* in `nucleus/pom.xml` and `core/core-parent/pom.xml` in tag `maven-enforcer-plugin` remove the upper JDK limit:
```
<version>[${jdk.version},)</version>
```
In directory `appserver/tests/payara-samples` run tests:
```
JAVA_HOME=/usr/lib/jvm/java21-openjdk-amd64 mvn clean install -Ppayara-server-remote
```
All tests pass well.
Linux, OpenJDK 11 and 21
=> FISH-7341 FISH-7381 upgrade asm and eclipselink.asm to 9.5

appserver/payara-appserver-modules/microprofile/telemetry/src/main/java/fish/payara/microprofile/telemetry/tracing/OpenTracingHelper.java, appserver/payara-appserver-modules/microprofile/telemetry/src/main/java/fish/payara/microprofile/telemetry/tracing/PayaraTracingServices.java, appserver/payara-appserver-modules/microprofile/telemetry/src/main/java/fish/payara/microprofile/telemetry/tracing/jaxrs/JerseyOpenTelemetryAutoDiscoverable.java, appserver/payara-appserver-modules/microprofile/telemetry/src/main/java/fish/payara/microprofile/telemetry/tracing/jaxrs/OpenTelemetryApplicationEventListener.java, appserver/payara-appserver-modules/microprofile/telemetry/src/main/java/fish/payara/microprofile/telemetry/tracing/jaxrs/OpenTelemetryRequestEventListener.java, appserver/payara-appserver-modules/microprofile/telemetry/src/main/java/fish/payara/microprofile/telemetry/tracing/jaxrs/OpenTracingCdiUtils.java, appserver/payara-appserver-modules/microprofile/telemetry/src/main/java/fish/payara/microprofile/telemetry/tracing/jaxrs/OpenTracingHelper.java, appserver/payara-appserver-modules/microprofile/telemetry/src/main/java/fish/payara/microprofile/telemetry/tracing/jaxrs/ResourceCache.java, appserver/payara-appserver-modules/microprofile/telemetry/src/main/java/fish/payara/microprofile/telemetry/tracing/jaxrs/client/JaxrsClientRequestTelemetryFilter.java, appserver/payara-appserver-modules/microprofile/telemetry/src/main/java/fish/payara/microprofile/telemetry/tracing/jaxrs/client/RestClientTelemetryListener.java
This PR adds new span attributes that will be required by Microprofile OpenTelemetry Tracing TCK 1.1 (a388a3f).
Then it tries to minimize number of MP Config lookups and reflection done on every request by introducing REST application-scoped `ResourceCache`, where information is cached for every invoked resource (Jakarta Rest method).
And finally rearranges helper classes, makes them package private where possible  and removes dead code from them.
Also adds new alias for span strategy of Microprofile Telemetry 1.0 -- `opentelemetry-1.13`, as that is more fair designation of where that strategy comes from.
Depends on payara/MicroProfile-TCK-Runners#226, as in-server workaround for OpenTracing TCK has been removed.
OpenTracing TCK (with patch above), MP Telemetry Tracing 1.1-SNAPSHOT
``` …
```
=> FISH-7339: Update span attributes for MP OpenTelemetry Tracing 1.1

nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/cluster/PayaraCluster.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/eventbus/EventBus.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/exec/ClusterExecutionService.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/DomainDiscoveryStrategy.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/MemberAddressPicker.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/PayaraHazelcastDiscoveryFactory.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/admin/ClearCache.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/admin/ListCaches.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/store/ClusteredStore.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/resources/META-INF/services/com.hazelcast.spi.discovery.DiscoveryStrategyFactory
prevents partitions to be placed on instances where the application is not deployed
Also cleaned up deprecation and lint warnings for Java 11
---
Basically, this resurrects the same PR from a couple of years ago. This was very well tested, and just was waiting for Hazelcast to release version 5, which took way too long, so this PR was closed at the time "due to inactivity"
=> [FISH-1419] use separate Hz partition groups for Payara domain instance groups

api/payara-bom/pom.xml, core/core-bom/pom.xml, core/pom.xml, nucleus/pom.xml, pom.xml
Payara BOM should not depend on Payara Core BOM, as that one contains lots of internal information. The public dependencies from Core BOM has been copied to Payara BOM (most of them were already there).
Core BOM import moved into nucleus parent, which is next in inheritance hierarchy.
Identified few of the properties that core BOM used, but didn't actually define, they well still in root.
=> FISH-6607: Remove dependency on core-bom from payara-bom

api/payara-bom/pom.xml, core/pom.xml
MicroProfile Open Telemetry upgrade necessary for 7.0
None
None
Zulu JDK 11.0.11 on Windows 11 with Maven 3.6.0
=> FISH-7483 : Open telemetry APIs upgraded to 1.26.0

core/pom.xml, nucleus/osgi-platforms/felix/src/main/resources/config/osgi.properties
Upgrades Hazelcast to 5.3.0
None
None
Started the DAS.
Clustered two Micro instances
WSL, Zulu 11
N/A
We may want to look into the new warnings on starting the DAS about not supporting the `TCP_KEEPCOUNT`, `TCP_KEEPIDLE`, and `TCP_KEEPINTERVAL` options...
=> FISH-7377 Hazelcast 5.3.1

api/payara-api/pom.xml, api/payara-bom/pom.xml, appserver/distributions/payara-ml/pom.xml, appserver/distributions/payara-web-ml/pom.xml, appserver/distributions/payara-web/pom.xml, appserver/distributions/payara/pom.xml, appserver/ejb/ejb-http-remoting/client/pom.xml, appserver/extras/embedded/all/pom.xml, appserver/extras/embedded/web/pom.xml, appserver/extras/payara-micro/payara-micro-distribution/pom.xml, core/core-bom/pom.xml, core/core-parent/pom.xml, core/pom.xml, pom.xml
Some flattened poms were missing the URL tag (e.g. payara-api) which meant they could not be used to upload to Maven Central. This fixes that, and also corrects the incorrect tags that the flatten plugin was creating. The flatten plugin was appending the artifact IDs to the "base" URL and leading to entries such as `https://github.com/payara/Payara/payara-nucleus-parent/payara-parent/ejb/ejb-http-remoting/ejb-http-client` which don't resolve.
Also updates the flatten plugin to 1.5.0 because I hoped they might have fixed the URL issue themselves (but haven't). When doing so I noticed a number of duplications of the flatten plugin configuration which I've removed.
None
None
Built with BuildExtras - checked all POMs had correct URL tag in flattened POM.
Windows 11, Zulu 11
N/A
None
=> FISH-7499 Fix Missing and Incorrect URLs Tags

core/pom.xml
Using new new PFL patched version
Remote EJB calls/communication done from a remote Java client application are not working properly on Payara Enterprise 5 and 6 when run in JDK 11 (on both ends).
- Quicklook
- Jakarta TCKs
- Mojarra
Zulu JDK 11 on Windows 11 with Maven 3.6.0
=> FISH-7462 : new PFL patched version for JDK 11 Support

nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/SecureAdminBootstrapHelper.java, nucleus/cluster/admin/src/main/resources/META-INF/config-files, nucleus/cluster/common/src/main/java/com/sun/enterprise/util/cluster/SyncRequest.java
We add support to run with jks keystores, not only p12.
When an instance is created, there is a list of files to copy. The jks variants were added to this list (they are ignored if they don't exist).
Instances synchronize files with DAS, therefor it was necessary to add jks there as well. They are required, so a simple list was changed to a list of alternatives -- the first existing file is copied.
* Check out and build Payara/Payara6
* Replace cacerts.p12 with cacerts.jks, keystore.p12 with keystore.jks (e.g. from Payara 5 build)
* Change settings in config.xml in domain1, replace `.p12` with `.jks` for both keystores
* Start the domain: `payara/bin/asadmin start-domain -v --debug`
* Load the admin console
* **Create a new instance** (FISH-7453) from admin gui - it is now normally …
=> FISH-7452 FISH-7453 Start/Create Instance When Using JKS Keystores

appserver/extras/payara-micro/payara-micro-boot/src/main/java/fish/payara/micro/PayaraMicroRuntime.java, appserver/extras/payara-micro/payara-micro-core/src/main/java/fish/payara/micro/impl/PayaraMicroRuntimeImpl.java
[FISH-1335](https://payara.atlassian.net/browse/FISH-1335) Removed deprecated run methods from PayaraMicroBootRuntime
Breaking changes
Have to monitor PR build
Java version: 11.0.18, vendor: Oracle Corporation
Default locale: en_IN, platform encoding: UTF-8
OS name: "mac os x", version: "13.4", arch: "aarch64", family: "mac"
[FISH-1335]: https://payara.atlassian.net/browse/FISH-1335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FISH-1335 Removed deprecated run methods

appserver/web/weld-integration/src/main/java/org/glassfish/cdi/transaction/TransactionalInterceptorRequiresNew.java
This PR fixes issue [6274](https://github.com/payara/Payara/issues/6274).
When using @Transactional(Transactional.TxType.REQUIRES_NEW) the interceptor suspends and resumes the transaction but also the transaction in the current invocation. But when resuming it sets the tx in the invocation also when there was none when the interceptor started. This causes issues when using an observer method with @Observes(during = TransactionPhase.AFTER_SUCCESS) because when this method is executed the tx is already committed and when calling datasource.getConnection() this causes an exception because it is checking the tx status in the current invocation.
No new tests because the current code do not allow for setting or mocking the invocationmanager/current invocation.
Reran the reproducer, no more …
=> FISH-7451 Fixes for Issue 6274

appserver/admin/gf_template/src/main/resources/config/domain.xml, appserver/admin/gf_template_web/src/main/resources/config/domain.xml, appserver/admin/production_domain_template/src/main/resources/config/domain.xml, appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml, appserver/extras/payara-micro/payara-micro-distribution/build.xml
Adding fix to include com.sun.jndi.ldap classes when using jdk 17
This is a fix of a reported bug when trying to use jndi.ldap classes
Manual testing:
Now the call of the endpoint is responding with 200 from micro, server a web:
No issues from logs using JDK 17
Ubuntu 20.04, maven 3.8.6, azul jdk 17
=> FISH-7409: adding property to load com.sun.jndi.ldap classes for jdk 17

nucleus/common/common-util/src/test/java/com/sun/enterprise/loader/DirWatcherTest.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/test/java/fish/payara/nucleus/microprofile/config/source/DirConfigSourceTest.java
FISH-7620 Fix timeout issue for Mac OS build
JIRA: https://payara.atlassian.net/browse/FISH-7620 - Fixing Mac OS build
At present, WatchService API takes around 10 seconds to update file system on Mac OS, so added delay of 10 seconds in case of assertion failure which fix Mac OS build. Have to ignore the assertion In a case where WatchService is failing to read the path pattern `watcher-files.example`
Fixed existing tests with appropriate delays in case of Mac OS
Maven built succesfully
Maven: 3.9.2
Java version: 11.0.18, vendor: Oracle Corporation
Default locale: en_IN, platform encoding: UTF-8
OS name: "mac os x", version: "13.4", arch: "aarch64", family: "mac"
=> FISH-7620 Fixed Test cases for MacOS build

appserver/packager/external/libpam4j/pom.xml
Fixing issue to start server caused by the libpam4j-repackaged.jar dependency
This is fix for a bug when creating the jar bundle for the libpam4j, older version of the maven-bundle-plugin 
is generating a jar file with error in zip headers. To fix, it is needed to use last version of
the plugin 5.1.9
Manual testing with most recent versions of JDK 11 and 17. Now the server can start with both JDK's
windows 11, Azul JDK 11.0.20 and Azul JDK  17.0.8
=> FISH-7665: fixing issue creating osgi bundle for libpam4j

pom.xml
This PR depends on: https://github.com/payara/patched-src-openmq/pull/23
Fix Incorrect 'imqcmd' calculations for the number of consumers after cluster restart
The imqcmd utility shipped with Open MQ software in Payara Server has a list destinations command that shows basic statistics of the number of producers, consumers and messages for each destination configured. After a cluster restart, the numbers shown by the command’s output are incorrect on a variable frequency, but close to the actual number to be shown. For example, where the number of consumers is 8 for a specific cluster instance, the number displayed might be 6, 7, 9, 10
https://github.com/payara/patched-src-openmq/pull/23
No
1. .\asadmin create-domain --portbase 9000 domain-9000
2. .\asadmin start-domain domain-9000
3. …
=> FISH-7273 : new openmq version to avoid duplicate consumers

appserver/extras/docker-images/pom.xml
Updates the Docker image JDKs to 11.0.20 and 17.0.8.
None
None
Built Docker images and let the automated tests run - they passed
Windows 11, Zulu JDK 11.0.20
N/A
None
=> FISH-7662 Update Docker images to 11.0.20 & 17.0.8

api/payara-bom/pom.xml
Adds the `opentracing.version` property to the Payara BOM, as the flatten doesn't appear to be expanding out the version from the inherited `core-parent` pom. 
None
None
Built `payara-bom` - `opentracing-api` now has a version.
Windows 11, Zulu 11.0.19
N/A
None
=> FISH-7641 Add Version to opentracing-api in Payara BOM

nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/DeleteApplicationRefCommand.java
So far, deleting application reference was reliably working on instances, but not on a deployment group. When delete-application-ref was used with a deployment group as a target, it removed the reference from DAS, but it didn't undeploy the application from the instance. Consequent `create-application-ref` failed (because the app was installed, but DAS wasn't aware of it).
This PR fixes behavior of `delete-application-ref` with target to deployment group, which undeploys the application also from all instances in the deployment group
Basically, the idea is to deploy an application, leave it deployed on DAS and make it available/removed from a deployment group. It is possible to call `create-application-ref` and `delete-application-ref` repeatedly. Customer wanted to make accessible a new …
=> FISH-6773 Delete Application Reference on a Deployment Group

appserver/payara-appserver-modules/microprofile/healthcheck/src/main/java/fish/payara/microprofile/healthcheck/cdi/extension/HealthCDIExtension.java
The user reported an issue in which, at runtime, the synthetic HealthCheck bean can be injected but is not included in the health check APIs. 
None
None
1. build Payara Server
2. git clone https://github.com/ghunteranderson/payara-issue-5594.git
3. edit the pom.xml file to change payara version: **<payara.version>6.2023.9-SNAPSHOT</payara.version>**
4. http://localhost:8080/health
5. In Payara 6, the API GET /health now includes health checks defined as synthetic beans
=> FISH-7597 : adding health checks for the qualifiers

appserver/admin/gf_template/src/main/resources/config/domain.xml, appserver/admin/gf_template_web/src/main/resources/config/domain.xml, appserver/admin/production_domain_template/src/main/resources/config/domain.xml, appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml
Add Opens on java.base/java.io & on java.base/jdk.internal.misc
From JDK 21 testing, we need to add this to our default JVM options.
None
None
Compile the "Payara6" branch of the patched-src-javaee7-samples repository against JDK 21, and run them against Payara Server running on JDK 21.
Zulu JDK 21 on Windows 11 with Maven 3.8.6
None
=> FISH-7716 : opening java.io & jdk.internal.misc since JDK 21

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBContextImpl.java
The `EJBContext` methods `getEnvironment`, `getCallerIdentity` and `isCallerInRole(Identity)` were removed in Jakarta EE 9.
This PR removes these methods from `EJBContextImpl`.
Since this was probably caused by missing `@Override` annotations, I went ahead and added that for all overriding methods such that future removals may be detected.
This is an enhancement which removes dead code and also allows Payara to compile on future JDKs where the deprecated `Identity` class has been removed.
Ran `mvn clean install` successfully.
```
% mvn -v 
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /Users/eirbjo/Development/apache-maven-3.8.6
Java version: 11.0.18, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home
OS name: "mac …
```
=> FISH-7340 Remove obsolete EJBContext methods 

nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/HSTSFilter.java
Adding fix to prevent multiple security headers of Strict-Transport-Security on the response
This is a fix for the following reported bug: https://github.com/payara/Payara/issues/6178
Manual testing with the reproducer included on the ticket:  https://payara.atlassian.net/browse/FISH-7044
Now the request is working fine adding just one occurrence of the security header on the response:
`
8m2pcqb77qu6lh5pl7v35pgyhauot2ntazall9f4idjs5lypnu5u83k6tf165ijyl64r0nf8mm1kexkclstpr13xgtmidw25pjv6yx6w2qyvm6jxu2vduxtj1mxsfralqbs4hss1ka6cpxdejq1nxly97p81zcqhpg22952l4rt6pk30qkm6f96ob7h33iines80f2bj6ziwwlimewj2az7rsoiae1nwskyyde4uh9l1xebng8e0vyr68pg3kc8l8067cjqy6lblvuk2xc5oiw01lasqnzi9vmrokal7scnik13x8xyuv1r54btm7mdxt97pu0xydhj2ahrrsnqgqx1ydsm41wyyh7de01zy0ktufu6okdouzkk2hnz94ywbjywsb7smwz2dffirm4nn36ah3 …
=> FISH-7044: preventing the addition of multiple HSTS header for response

appserver/admin/gf_template/src/main/resources/config/domain.xml, appserver/admin/gf_template_web/src/main/resources/config/domain.xml, appserver/admin/production_domain_template/src/main/resources/config/domain.xml, appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml
Cargotracker didn't run on JDK 17. The required --add-opens is used from JDK 21. This PR lowers the required JDK to 17.
* Compile Payara
* checkout Cargotracker: `git clone git@github.com:eclipse-ee4j/cargotracker.git`
* change version of Payara to use in `pom.xml`: `<payara.version>6.2023.9-SNAPSHOT</payara.version>`
* run cargotracker in JDK 17: `JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 mvn clean package -DskipTests cargo:run`
Linux, OpenJDK 11 (to compile Payara), OpenJDK 17 to run
=> FISH-7716 openjava.base/java.io on jdk 17

appserver/tests/functional/cleanboot/README.md, appserver/tests/functional/cleanboot/admingrouplib.py, appserver/tests/functional/cleanboot/admininstancelib.py, appserver/tests/functional/cleanboot/asadminlib.py, appserver/tests/functional/cleanboot/testcleanbootcommand.py
Automated test using Python 3 and Playwright.
The goal is to automate the Clean Boot test performed with each release candidate:
- start the domain
- create an instance, start the instance, check the logs for any warning/error, stop the instance, delete the instance
- create a deployment group with 2 instances, start the group, check the logs for any warning/error, stop the group, delete the group and the instance
- stop the domain
Instructions to run it are in the README.md
Tested with Payara 5 and 6
=> Fish 7356 automate cleanboot test

appserver/extras/pom.xml, pom.xml
Some changes to accomodate releasing Core separately.
This renames the old "embedded" profile to be better aligned with the other "BuildX" profiles we use.
This also moves Certificate Management into its own profile to separate it out in prep for it being moved into its own repo like other extensions.
BuildExtras still builds both Embedded and Certificate Management, but now also builds the Docker images - the rational is that BuildExtras is now a "build all optional modules", and that there are separate "BuildX" profiles for the individual optional modules.
This also introduces a profile to skip building Core: `BuildCore`.
This is a profile that is active by default (so Core continues to be built by default). It doesn't use the maligned `activeByDefault` option, and is instead active as …
=> FISH-7238 FISH-7721 FISH-7723 Changes to Accommodate Releasing Core Separately

core/core-parent/pom.xml
In the path to split core modules, we add semantic versioning check for core modules. This PR adds the check to the parent, e.g. all core modules must pass this check: no incompatible changes in patch releases.
The check is currently added as a profile `force-semver`. If it will cause no problems for some longer time, let's activate it by default.
Build works normally:
```
mvn clean install -T 16 -PQuickBuild,force-semver -DskipTests
```
Let's to some incompatible change, e.g. delete file `nucleus/common/glassfish-api/src/main/java/org/glassfish/api/Startup.java`, which doesn't cause build error otherwise. The same build fails with this message:
```
[ERROR] Failed to execute goal com.github.siom79.japicmp:japicmp-maven-plugin:0.17.2:cmp (default) on
project glassfish-api: Versions of …
```
=> FISH-7268 Add Semantic Versioning Check in Core Module

core/pom.xml
Fix CVE-2023-1370, json-smart Uncontrolled Recursion vulnerability
None
None
1. mvn clean install -T 14 -DskipTests
2. .\appserver\distributions\payara\target\stage\payara6\bin\asadmin start-domain -v
3. Payara Samples
4. Quicklook
Zulu JDK 11.0.11 on Windows 11 with Maven 3.8.4
None
None
=> FISH-7648 : upgraded shaded json-smart version

pom.xml
Upgrades H2DB to 2.2.220
None - already uploaded H2DB to payara-artifacts
None
Started database using `asadmin start-database`
Payara was able to ping it using `asadmin ping-connection-pool H2Pool`
OpenSUSE Leap 15.5 WSL, Zulu 11
N/A
None
=> FISH-6863 H2DB 2.2.220

pom.xml
Upgrade Santuario to the latest version 3.0.2
=> FISH-6866 Upgrade Santuario to 3.0.2

appserver/extras/docker-images/basic/pom.xml, appserver/extras/docker-images/basic/src/main/docker/Dockerfile, appserver/extras/docker-images/micro/pom.xml, appserver/extras/docker-images/micro/src/main/docker/Dockerfile, appserver/extras/docker-images/micro/src/main/docker/bin/entrypoint.sh, appserver/extras/docker-images/server-full/pom.xml, appserver/extras/docker-images/server-full/src/main/docker/Dockerfile, appserver/extras/docker-images/server-full/src/main/docker/bin/entrypoint.sh, appserver/extras/docker-images/server-full/src/main/docker/bin/init_1_generate_deploy_commands.sh, appserver/extras/docker-images/server-full/src/main/docker/bin/startInForeground.sh, appserver/extras/docker-images/server-node/pom.xml, appserver/extras/docker-images/server-node/src/main/docker/Dockerfile, appserver/extras/docker-images/server-node/src/main/docker/bin/entrypoint.sh, appserver/extras/docker-images/server-web/pom.xml, appserver/extras/docker-images/server-web/src/main/docker/Dockerfile, appserver/extras/docker-images/server-web/src/main/docker/bin/entrypoint.sh, appserver/extras/docker-images/server-web/src/main/docker/bin/init_1_generate_deploy_commands.sh, appserver/extras/docker-images/server-web/src/main/docker/bin/startInForeground.sh, appserver/extras/docker-images/tests/pom.xml
Disables the extra zip validation added in JDK 11.0.20 & 17.0.8 which breaks the libpam4j package we bundle in Payara Server & Micro. While no longer an issue on the **most recent** releases due to fix introduced in https://github.com/payara/Payara-Enterprise/pull/899, if we ever decide to rebuild an older Community image utlising the newest JDKs we either need to add this option or backport the fix to all previous releases!
Since the `create-jvm-options` command requires the domain be running (and it cannot start due to the missing JVM option!) I've had to resort to inserting the option via sed (because I can't think of a better way). I have attempted to preserve the indentation because it pleases me.
None
None
Built latest Payara Server & Micro and their respective Docker images and let …
=> FISH-7740 Disable Extra Zip Validation in Docker Images

appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/util/ClusteredSingletonLookupImplBase.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/CMCSingletonContainer.java, appserver/payara-appserver-modules/payara-micro-cdi/src/main/java/fish/payara/micro/cdi/extension/cluster/ClusterScopeContext.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java
Probably more of a bug fix than enhancement
- Auto-promotes a new cluster member into CP subsystem if necessary
- Auto-resets CP subsystem when it gets into unusable state (not enough members leave and join)
- handles distributed lock exceptions well when CP subsystem is enabled
See https://github.com/hazelcast/hazelcast/issues/24897 for context
* New system property `hazelcast.cp-subsystem.auto-promote` (boolean, defaults to true) - Enable / Disable auto-promote functionality
* New system property `hazelcast.auto-partition-group` (boolean, temporarily defaults to false) - Enable / Disable auto-partition-group functionality
* Document existing system property `hazelcast.cp-subsystem.cp-member-count` (int, defaults to zero) to enable CP subsystem without additional Hazelcast configuration …
=> FISH-7640 Improved Hazelcast functionality as it relates to CP subsystem

core/core-parent/pom.xml
Follow on to https://github.com/payara/Payara/pull/6379
Enables semantic versioning in Core by default.
To disable, you must define the `core.force.semver` property to _false_.
None
None
* Attempted to build core with no property - it fails on semver (because opentelemetry introduced breaking API changes): `mvn clean install -f core`
* Attempt to build core with property set to _true_ - it fails on semver: `mvn clean install -f .\core\ "-Dcore.force.semver=true"`
* Attempt to build core with property set to _false_ - build succeeds: `mvn clean install -f .\core\ "-Dcore.force.semver=false"`
Windows 11, Zulu JDK 11.0.20
Pending...
Name of property obviously up for discussion.
=> FISH-7760 Enable Semantic Versioning of Core by Default

core/pom.xml
Updates the JSON-P implementation (Parsson) to 1.1.4.
This is a patched version of Parsson, since the published 1.1.4 has a malformed OSGi manifest and doesn't work.
Also updates the JSON-P API to 2.1.2.
https://github.com/payara/patched-src-parsson/pull/1
None
* Created a temp maven repo: `mkdir D:\Downloads\FISH-7757`
* Built patched parsson and let unit tests run: `mvn clean install -Dmaven.repo.local=D:\Downloads\FISH-7757`
* Build Payara server, overriding version of parsson in pom: `mvn clean install -Dmaven.repo.local=D:\Downloads\FISH-7757 -Dparsson.version=1.1.4.payara-p2-SNAPSHOT`
* Started server
Windows 11, Zulu JDK 11.0.20
N/A
None
=> FISH-6876 FISH-7757 Parsson 1.1.4 & JSON-P API 2.1.2

.github/workflows/assign-community-prs.yaml
This pull request introduces a new GA workflow to assign new PRs made by contributors not belonging to Payara so that they are processed by a member of the Service team.
Testing of the workflow was done on a separate repository: https://github.com/fturizo/GHActionsTester/
=> GA Workflow to handle Community PRs Assignment

appserver/packager/legal/src/main/resources/glassfish/legal/3RD-PARTY-LICENSE.txt, appserver/pom.xml
Updates the JBoss Class File Writer to 1.3.0.Final with amendments.
The vanilla 1.3.0.Final release has malformed OSGi, with the osgi.ee filter being set to UNKNOWN. This is fixed by using a more recent version of the Maven Bundle plugin.
This however also starts importing java.* packages by default (the ones from the JDK), which we don't currently support, so there's also an additional change to make it so that these packages are excluded.
https://github.com/payara/patched-src-jboss-classfilewriter/pull/1
None
* Make a temporary maven repo to ensure no "cheating" going on via cache: `mkdir D:\Downloads\FISH-6858`
* Build patched JBoss ClassFileWriter: `mvn clean install "-Dmaven.repo.local=D:\Downloads\FISH-6858"`
* Build Payara, overriding jboss classfilewriter version to the SNAPSHOT …
=> FISH-6858 JBoss Class File Writer 1.3.0

.github/workflows/assign-community-prs.yaml
GitHub Action Workflow to Manage Assignment of Community Contributions
This is a copy of #6408 as the workflow broked on the GitHub repository
=> Re-added assign community contributions workflow

appserver/packager/legal/src/main/resources/glassfish/legal/3RD-PARTY-LICENSE.txt, appserver/pom.xml, core/pom.xml
Updates these components to get away from a CVE in JSON Smart.
Also updates the security connector in the same way.
https://github.com/payara/ecosystem-security-connectors/pull/273
None
Built server, ran EE7 samples against it.
Windows 11, Zulu 11.0.20
https://github.com/payara/Payara-Documentation/pull/321
None
=> FISH-7820 FISH-7827 FISH-7828 FISH-7829 Update Nimbus-Jose-JWT, Accessors Smart, and JSON Smart

api/payara-bom/pom.xml, core/pom.xml
Removes a redundant dependency.
This dependency was rolled into the main api artefact.
https://github.com/open-telemetry/opentelemetry-java/blob/main/CHANGELOG.md?plain=1#L208
None
None
Built server, started server, ran against OpenTelemetry-Tracing TCK
Windows 11, Zulu 11.0.20.1
N/A
None
=> FISH-7278 Remove Redundant Dependency

appserver/extras/payara-micro/payara-micro-distribution/build.xml
Added add-opens `java.base/java.io` to the MANIFEST.MF for Payara Micro
Fixes #6406 
Ran Cargotracker tests using Payara Micro 6.2023.10-SNAPSHOT on JDK17
Ubuntu 22.04.2 LTS, Zulu JDK 17, Maven 3.8.6
=> FISH-7817 add-opens java.base/java.io for payara micro

appserver/admin/gf_template/src/main/resources/config/domain.xml, appserver/admin/gf_template_web/src/main/resources/config/domain.xml, appserver/admin/production_domain_template/src/main/resources/config/domain.xml, appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml, appserver/extras/payara-micro/payara-micro-distribution/build.xml, appserver/tests/payara-samples/samples/remote-ejb-tracing/pom.xml
Title.
Also adds extra required JVM options for Remote EJB Tracing test
None
None
Ran Remote EJB Tracing test on JDK 17 AND 21 - no errors.
Windows 11, Zulu 17.0.8.1 & 21.0.0
N/A
None
=> FISH-7847 Fix InaccessibleObjectException for `javax.management` and `javax.management.openmbean` on JDK 17 & 21

appserver/payara-appserver-modules/microprofile/telemetry/src/main/java/fish/payara/microprofile/telemetry/tracing/WithSpanMethodInterceptor.java, appserver/tests/payara-samples/samples/opentelemetry/src/test/java/fish/payara/samples/otel/spanname/OpenTelemetryWithSpanIT.java
Fixing naming of span to fix TCK issues
This is a fix for the TCK issues reported from the last version of opentelemetry
now the TCK tests are passing:
`
[INFO] Tests run: 56, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 220.243 s - in TestSuite
[INFO]
[INFO]
[INFO] Tests run: 56, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (verify) @ MicroProfile-OpenTelemetry-Tracing ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
`
and full TCK
`
[INFO] Reactor Summary for MicroProfile TCK Suite Parent 1.1-SNAPSHOT:
[INFO]
[INFO] MicroProfile TCK Suite Parent ...................... SUCCESS [  0.375 s]
[INFO] MicroProfile Fault Tolerance TCK Runner ............ SUCCESS …
=> FISH-7776: fixing naming for span to pass tck issues

core/pom.xml
Hi,
I'm trying to deploy my application in payara-embedded-all 6.2023.9 with the JDK21 and hit a ClassReader issue.
It seems that simply updating the ASM version to 9.6 solves the problem.
=> FISH-7865 Update to ASM 9.6

nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/RestartDomainCommand.java, nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/StartDomainCommand.java, nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/StopDomainCommand.java, nucleus/admin/server-mgmt/src/main/java/fish/payara/admin/servermgmt/cli/RestartDomainsCommand.java, nucleus/admin/server-mgmt/src/main/java/fish/payara/admin/servermgmt/cli/StartDomainsCommand.java, nucleus/admin/server-mgmt/src/main/java/fish/payara/admin/servermgmt/cli/StopAllDomainsCommand.java, nucleus/admin/server-mgmt/src/main/java/fish/payara/admin/servermgmt/cli/StopDomainsCommand.java, nucleus/admin/server-mgmt/src/main/manpages/com/sun/enterprise/admin/servermgmt/cli/restart-domain.1, nucleus/admin/server-mgmt/src/main/manpages/com/sun/enterprise/admin/servermgmt/cli/start-domain.1, nucleus/admin/server-mgmt/src/main/manpages/com/sun/enterprise/admin/servermgmt/cli/stop-domain.1
* start-domain
* restart-domain
* stop-domain
* stop-domains
* stop-all-domains
* start-domains
* restart-domains
Manual testing
Ubuntu 22.04.2 LTS, maven 3.8.6 zulu jdk 11
https://github.com/payara/Payara-Documentation/pull/325
=> FISH-7454 Add timeout option for domain commands

core/core-parent/pom.xml, core/pom.xml, nucleus/pom.xml
Updates the enforcer settings to allow compiling and running tests on JDK 21.
Also removes redundant enforcer settings.
None
None
Tried to compile on JDK 21 - enforcer didn't trip.
Windows 11, Zulu 21.0.0
N/A
None
=> Update Enforcer to Allow Running Tests on JDK 21

appserver/jms/admin/src/main/java/org/glassfish/jms/admin/cli/JMSDestination.java, appserver/jms/jms-core/src/main/java/com/sun/enterprise/connectors/jms/system/MQAddressList.java, appserver/jms/jms-core/src/main/java/com/sun/enterprise/connectors/jms/util/JmsRaUtil.java, nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/Domain.java, nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/Server.java, nucleus/admin/config-api/src/main/java/fish/payara/enterprise/config/serverbeans/DeploymentGroup.java, nucleus/admin/config-api/src/main/java/org/glassfish/config/support/Constants.java, nucleus/admin/config-api/src/main/java/org/glassfish/config/support/DomainXmlPreParser.java, nucleus/admin/config-api/src/main/java/org/glassfish/config/support/InstanceReaderFilter.java, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/InstanceRegisterInstanceCommand.java, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ListInstancesCommand.java, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/PostRegisterInstanceCommand.java
In general, JMS Service availability doesn’t work when setting up a JMS cluster in LOCAL mode when using deployment groups unlike traditional clusters (generally known as Shoal clusters).
None
None
Steps:
1. build Payara Community
2. run it
3. Run the next commands using asadmin:
```
copy-config default-config mqc-config
set configs.config.mqc-config.availability-service.jms-availability.availability-enabled=true
set configs.config.mqc-config.jms-service.type=LOCAL
create-node-ssh --sshport=22 --nodehost=localhost --installdir=${com.sun.aas.productRoot} --sshuser=${user.name} remote-node-1
create-node-ssh --sshport=22 --nodehost=localhost --installdir=${com.sun.aas.productRoot} --sshuser=${user.name} remote-node-2
create-deployment-group dg1
create-instance --deploymentgroup=dg1 …
```
=> FISH-7132 : handling deployment groups  in the same way done by clusters

nucleus/pom.xml
Upgrades the awaitility test dependency to 4.2.0
None
None
Built server and let unit tests run.
Windows 11, Zulu 11.0.20.1
N/A
None
=> FISH-7240 Update Awaitility to 4.2.0

nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/ASURLClassLoader.java
This PR fixes lookup of classes in MultiRelease JARs for version-specific classes. Fixes #6452.
Tested on my [reproducer](https://github.com/ctabin/gf-test-lucene)
OpenJDK 21, Linux Debian
Azul JDK 21, Ubuntu 20.04
=> FISH-7959: Fixes MultiRelease JAR lookup for specific version classes

nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/Realm.java
Fixes the Custom LoginModule/Realm feature for Windows. 
When running the `create-auth-realm` command to utilise a custom realm it fails because the `realmJarPath` property resolves to an incorrect URL on Windows.
The path `C:\asd\dsa\example.jar` ends up being registered to the class loader as `file://C:/asd/dsa/example.jar` which is an incorrect URL: it should either be `file:/C:/asd/dsa/example.jar` or `file:///C:/asd/dsa/example.jar`
None
None
Ran the custom-loginmodule-realm sample on Windows and WSL.
Windows 11, Zulu JDK 11.0.20.1.
WSL OpenSUSE Leap 15.5
N/A
None
=> FISH-7953 Fix Cannot Load Custom Realm Class Error on Windows

nucleus/admin/config-api/src/main/java/org/glassfish/config/support/DomainXmlPreParser.java, nucleus/admin/config-api/src/main/java/org/glassfish/config/support/InstanceReaderFilter.java
In general, JMS Service availability doesn’t work when setting up a JMS cluster in LOCAL mode when using deployment groups unlike traditional clusters (generally known as Shoal clusters).
None
None
Steps:
1. build Payara 6 Community
2. run it
3. Run the following commands using asadmin:
```
copy-config default-config mqc-config
set configs.config.mqc-config.availability-service.jms-availability.availability-enabled=true
set configs.config.mqc-config.jms-service.type=LOCAL
create-node-ssh --sshport=22 --nodehost=localhost --installdir=${com.sun.aas.productRoot} --sshuser=${user.name} remote-node-1
create-node-ssh --sshport=22 --nodehost=localhost --installdir=${com.sun.aas.productRoot} --sshuser=${user.name} remote-node-2
create-deployment-group dg1
create-instance --deploymentgroup=dg1 …
```
=> FISH-7132 : config refs list being handled

core/pom.xml
Jersey 3.1.3 with our fix for and with JDK packages excluded from OSGi imports
https://github.com/payara/patched-src-jersey/pull/206
None
Built server and started admin console - no OSGi errors and console loads successfully.
Windows 11, Zulu JDK 11.0.21
N/A
Jenkins run against SNAPSHOT: https://engineeringjenkins.payara.fish/blue/organizations/jenkins/Payara%20Community%20PR%20Testing/detail/PR-6491/3/pipeline
=> FISH-7129 Jersey 3.1.3

core/pom.xml, pom.xml
Vulnerability on JQuery 1.2 < 3.5.0
Depends On: 
- https://github.com/payara/monitoring-console/pull/39 being merged
- monitoring-console 2.0.2 deploy on Nexus 
None
Zulu JDK 11.0.11 on Windows 11 with Maven 3.8.4
=> FISH-7262 : monitoring console using jQuery 3.6.1

core/pom.xml, nucleus/grizzly/config/pom.xml, nucleus/grizzly/config/src/test/java/org/glassfish/grizzly/config/GrizzlyConfigTest.java, nucleus/grizzly/config/src/test/java/org/glassfish/grizzly/config/GrizzlyTestUtils.java, nucleus/grizzly/config/src/test/java/org/glassfish/grizzly/config/HttpRedirectTest.java, nucleus/grizzly/config/src/test/java/org/glassfish/grizzly/config/PUGrizzlyConfigTest.java, nucleus/pom.xml
In new Jenkins, the Grizzly tests failed ~ 20% of the time due to `Address already in use` errors. It's fairly well documented that after closing a socket, the port will enter a TIME WAIT state to prevent delayed packets arriving to a different listener. The OS will make the port available again after a period of time that is not deterministic.
This PR introduces a wait period of up to 1 minute to ensure the port is available before beginning the test.
None
Ran the tests locally where it was always observed to pass and they continue to pass 100% of the time with no added delay in running the test suite. 
Ran 15 Jenkins builds and none failed where it's expected ~ 3-5 would fail. Verified some tests took 20+ seconds showing the await functionality was activated to make this test pass.
New …
=> ITOPS-2602 Make Grizzly HTTP Test More Predictable

appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/impl/WeightedSnapshot.java, appserver/payara-appserver-modules/microprofile/metrics/src/main/java/fish/payara/microprofile/metrics/writer/OpenMetricsExporter.java, appserver/payara-appserver-modules/microprofile/metrics/src/test/java/fish/payara/microprofile/metrics/writer/OpenMetricsExporterTest.java, appserver/payara-appserver-modules/microprofile/metrics/src/test/resources/examples/GaugeTags.txt
Fix buckets counting for Prometheus format
This is a fix for an issue to totalize the occurrences of bucket values
Manual testing by executing metrics application with histogram and timer metrics and custom configuration for percentiles and buckets
TCK results for metrics:
result from samples:
steps to reproduce on the ticket:
https://payara.atlassian.net/browse/FISH-8100
windows 11, azul jdk 11, maven 3.9.5 / ubuntu 20.04, azul jdk 11, maven 3.8.6
=> FISH-8100: fixing issue when totalizing buckets for prometheus format

core/pom.xml
jakarta security upgraded to 3.0.3
Depends on:
- https://github.com/payara/patched-src-security-soteria/pull/8
- Deploy of version 3.0.3.payara-p1 on maven central
None
Samples, Quicklook
Zulu JDK 11 on Windows 11 with Maven 3.8.4
None
None
=> FISH-6874 : jakarta security upgraded to 3.0.3

appserver/extras/docker-images/pom.xml
Title.
None
None
Built Docker images and _very carefully_ checked the logs to ensure 11, 17, and 21 images were being created.
Windows
N/A
None
=> Fix build of Docker images - JDKs 11 and 17 were being skipped

nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/StartServerHelper.java
Remote JMS Broker Fails to Start
None
1. payara6/glassfish/bin/asadmin start-domain
2. payara6/glassfish/bin/asadmin set configs.config.server-config.jms-service.type=REMOTE
3. payara6/glassfish/bin/asadmin stop-domain
4. payara6/mq/bin imqbrokerd
5. payara6/glassfish/bin/asadmin start-domain
It should start beautifully
Samples, quicklook etc
Zulu JDK 11 on Windows 11 with Maven 3.8.4
None
None
=> FISH-7993 : ignoring JMS PORT

core/core-parent/pom.xml, core/pom.xml, nucleus/packager/external/opentelemetry-repackaged/pom.xml
Upgrading okhttp to fix CVE's CVE-2023-3635 and CVE-2023-0833
This is a fix to resolve both CVE's reported:
- Okio GzipSource unhandled exception Denial of Service: CVE-2023-3635
- Component version with information disclosure flaw: CVE-2023-0833
Execution of Jenkins pipeline
ubuntu 20.04, azul JDK 11, maven 3.8.6
=> FISH-7835: upgrading okhttp and skipping kotlin dependencies

.github/workflows/monitor-issues-in-voting.yaml
This PR fixes the https://github.com/payara/Payara/actions/workflows/monitor-issues-in-voting.yaml[Monitor Issues in Voting] GitHub action so it doesn't report an error when attempting to notify the MS Teams channels if no issues were selected.
=> Minor fix to monitor issues in voting workflow GitHub action

core/pom.xml
Simple component upgrade
Upgrade required for compilation by JKD 21
=> FISH-7991 upgrade command-security-maven-plugin to 1.0.17

core/pom.xml
Updates Jersey to 3.1.5 with our patches reapplied.
Set to SNAPSHOT for now to let this run through all tests via Jenkins.
https://github.com/payara/patched-src-jersey/pull/208
None
Built locally and ran MicroProfile REST Client TCK
Windows 11, Zulu JDK 11.0.21
N/A
None
=> FISH-8172 Jersey 3.1.5

Jenkinsfile, appserver/tests/payara-samples/samples/cleanboot/README.md, appserver/tests/payara-samples/samples/cleanboot/pom.xml, appserver/tests/payara-samples/samples/cleanboot/src/test/java/fish/payara/functional/cleanboot/AdminGroup.java, appserver/tests/payara-samples/samples/cleanboot/src/test/java/fish/payara/functional/cleanboot/AdminInstance.java, appserver/tests/payara-samples/samples/cleanboot/src/test/java/fish/payara/functional/cleanboot/AdminPage.java, appserver/tests/payara-samples/samples/cleanboot/src/test/java/fish/payara/functional/cleanboot/CleanBootIT.java, appserver/tests/payara-samples/samples/pom.xml
Cleanboot test converted in Java. 
It uses Arquillian to start/stop the server.
Playwright opens a browser (in headless mode by default), loads the admin console, then runs 2 tests
- create an instance, start the instance, check the logs, stop the instance and delete the instance. It fails if the logs contain errors.
- create a deployment group with 2 instances, start the group, check the logs for both instances, stop the group, delete the group and the instances. It fails if the logs contain errors.
Any warning in the logs is printed in the output, for manual verifications when necessary.
=> FISH-8072 - cleanboot test with arquillian

nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/GFFileHandler.java
Removing of duplicated semicolon in import to build on JDK 21
None
None
Samples, quicklook, etc
None
None
=> FISH-8217 : duplicated semicolon removed

nucleus/common/common-util/src/main/java/com/sun/enterprise/util/ProcessExecutor.java
Unqualified call to 'yield' method is not supported in releases since Java 14
None
None
Samples, quicklook, etc
Zulu JDK 11.0.11 on Ubuntu 18.04 with Maven 3.8.6
None
None
=> FISH-8217 : unqualified yield method fixed

pom.xml
Sets the parent version of the release to 6.11.1, which reverts JAXB to 4.0.1 to fix the XML-WS TCK.
~Review, testing, and release of https://github.com/payara/Payara/tree/Payara-Core-6.11.1-Release~
Tag published: https://github.com/payara/Payara/tree/payara-core-6.11.1
None
https://engineeringjenkins.payara.fish/blue/organizations/jenkins/JakartaEE-10-TCK/detail/JakartaEE-10-TCK/52/pipeline/
Jenkins
Pending... 
Release notes will need adjusting...
Pending...
=> FISH-8248 Use Core 6.11.1

appserver/web/web-core/src/main/java/org/apache/catalina/realm/JAASRealm.java, nucleus/security/core/src/main/java/com/sun/enterprise/security/GroupPrincipal.java
package java.security.acl does not exist
None
None
Samples, quicklook etc
None
None
=> FISH-8215 : port solution from Glassfish

nucleus/deployment/common/src/main/java/org/glassfish/loader/util/ASClassLoaderUtil.java
Hi,
We are using payara-embedded-all to deploy our application. This dependency (among) other are (re-)packaged in an überjar for the delivery.
While making some test to migrate from this überjar to spring boot, we hit the exception below while deploying our app with
```java
Deployer earDeployer = glassfish.getDeployer();
earDeployer.deploy("myFile.ear");
```
This is because the URIs returned are pointing to internal jar (and hence starting with `jar:<path>` (for instance `jar:file:/path/to/app-spring-boot.jar!/BOOT-INF/lib/mylib-1.0.0.jar!/`). So, I suggest to simply ignore those in this case.
Here is the stacktrace that this PR intended to fix.
```
SEVERE: Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException
at …
```
=> FISH-8044 Avoid crashing due to FileSystemNotFound while behind a Spring boot

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/DynamicReloadService.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/DynamicReloader.java
This pull request addresses the challenges faced in the Payara Micro Maven Plugin's dev mode, specifically when deployment fails after a successful build. The proposed solution introduces a fail-safe mechanism that involves the addition of a `dev-mode` flag for persistent deployment.
Added a new dev mode flag that can be passed to Payara Micro. This flag instructs Payara Micro to persistently monitor for changes after the failure of application deployment.
For more details and test scenarios:
https://github.com/payara/ecosystem-maven/pull/293
=> FISH-8259 Improve Dev Mode Fail-Safe Mechanism

core/pom.xml
This reverts commit 1fb6650acf4c579d7d88a2eea853470d8eb73bdb, reversing changes made to 625a0f89d6d9caab36f7aaae64ddd08ecdc948d3.
This is due to it breaking the Jakarta EE 10 XML-WS TCK
Original PR: https://github.com/payara/Payara/pull/6502
None
None
None
My eyes
N/A
None
=> Revert: FISH-7224 Upgrade JAXB-OSGI to 4.0.4

appserver/extras/docker-images/pom.xml
Updates the Docker JDK versions to 11.0.22, 17.0.10, and 21.0.2.
None
None
_Waiting for Azul to publish the Docker images..._
Built Payara server using 11.0.22.
Built Docker images and let unit tests run.
Windows 11, Zulu 11.0.22
N/A
None
=> FISH-8262 FISH-8263 FISH-8264 Upgrade Docker JDK Versions

core/pom.xml
The PR upgrades the Security Connector to expand the functionality of the OIDC Connector by enabling proxy configuration. This addition is crucial for scenarios where the application interacts with an OpenID Connect provider through a reverse proxy, offering more flexibility in handling requests.
- **Download NGINX for Windows:** Visit the NGINX website ([nginx news](https://nginx.org/) ) and download the Windows version of NGINX.
- **Install NGINX:** Follow the installation instructions provided with the downloaded package to install NGINX on your Windows machine. During the installation, choose the installation directory. For example, C:\nginx.
- **Edit NGINX configuration file:** Locate the NGINX configuration file (`nginx.conf`) in the NGINX installation directory (typically found …
=> FISH-8054 Upgrade the OpenID Security Connector to 3.2

appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModule.java
Warning Falsely Logged with Custom Error Pages
None
None
1. Replace tag `<virtual-server>` into domain.xml in Payara Server to:
```
<virtual-server network-listeners="http-listener-1,http-listener-2" id="server">
<property name="send-error_1" value="code=404 path=${com.sun.aas.instanceRoot}/docroot/404.html reason=NOT_FOUND"></property>
</virtual-server>
```
2. Create a 404.html file in domain1/docroot/
3. Start server ./asadmin start-domain -v
4. Warning should **NOT** be logged during deployment
Zulu JDK 11 on Windows 11 with Maven 3.8.6
None
=> FISH-7430 : send-error_X property being skipped

nucleus/core/kernel/src/main/java/org/glassfish/kernel/event/EventsImpl.java, nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/config/ClusteredConfig.java
Cleanup unnecessary warning log
None
None
1. Build Payara: 6.2024.3-SNAPSHOT
2. Donwload zipped application reproducer: **PayaraMicroHelloWorld.zip** from https://payara.atlassian.net/browse/FISH-7367
3. Change payara versions in pom.xml: `<version.payara.micro>6.2024.3-SNAPSHOT</version.payara.micro><version.payara>6.2024.3-SNAPSHOT</version.payara>`
4. Build the reproducer: `mvn clean package`
5. Download Hazelcast 5.3.6
6. run bin/hz-start.bat
7. run the reproducer via: `mvn clean package payara-micro:start`
8. Check that the exception is not logged any more
None
=> FISH-7362 : Ignore ReplicatedMapCantBeCreatedOnLiteMemberException dispatched from Hazelcast

nucleus/admin/util/src/main/java/com/sun/enterprise/admin/remote/reader/MultipartProprietaryReader.java
https://payara.atlassian.net/browse/FISH-7212 fix issue when creating MIME*.tmp files on the system
This is a fix of a reported issue when Payara Server is creating MIME*.tmp files on the Temp folder on the system
To test this you need to create a local instance, then add this instance as a member of a deployment group and then try to deploy an application with more than 1 MB of size. That can be: jar file, war file, ear file or rar file
The MIME*.tmp file is not created on the temp folder on the system:
this was tested on Windows 11,  Azul JDK 11 and Maven 3.9.5
=> FISH-7212: avoiding creation of temporal files on local system

appserver/tests/functional/payara-micro/README.md, appserver/tests/functional/payara-micro/pom.xml, appserver/tests/functional/payara-micro/src/test/java/fish/payara/functional/micro/ClusterHAJSPPage.java, appserver/tests/functional/payara-micro/src/test/java/fish/payara/functional/micro/DualSessionsIT.java, appserver/tests/functional/payara-micro/src/test/resources/arquillian.xml, appserver/tests/functional/payara-micro/src/test/resources/clusterjsp/clusterjsp-war/web/ClearSession.jsp, appserver/tests/functional/payara-micro/src/test/resources/clusterjsp/clusterjsp-war/web/HaJsp.jsp, appserver/tests/functional/payara-micro/src/test/resources/clusterjsp/clusterjsp-war/web/MANIFEST.MF, appserver/tests/functional/payara-micro/src/test/resources/clusterjsp/clusterjsp-war/web/WEB-INF/sun-web.xml, appserver/tests/functional/payara-micro/src/test/resources/clusterjsp/clusterjsp-war/web/WEB-INF/web.xml
Adds a functional test with Payara Micro.
It starts 2 instances, deploys ClusterJsp in both and expect them to cluster. Using Playwright, in a browser, the test adds an attribute in the first instance. Then opens the second instance, checks for attribute 1, and adds attribute 2. Then navigates to Instance1, and checks for attribute1 and attribute2.
The test depends on some utilities from payara-samples, and requires to build payara-samples before running the test. Because of that, it requires to specify the profile `payara-micro-managed` when executing the test with maven.
The test uses Playwright. By default, it will use Playwright CLI command to install the dependencies. In Linux, this will use sudo to install the dependencies. To disable that installation, disable the profile …
=> Fish 7358 automate test payara micro

api/payara-bom/pom.xml, appserver/concurrent/concurrent-connector/src/main/java/org/glassfish/concurrent/config/ManagedExecutorService.java, appserver/concurrent/concurrent-impl/pom.xml, appserver/concurrent/concurrent-impl/src/main/java/fish/payara/concurrent/monitoring/ManagedExecutorServiceStatsProvider.java, appserver/concurrent/concurrent-impl/src/main/java/fish/payara/concurrent/monitoring/ManagedScheduledExecutorServiceStatsProvider.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ConcurrentRuntime.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/InvocationContext.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/TransactionHandleImpl.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/TransactionSetupProviderImpl.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ConcurrentObjectFactory.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ContextServiceDefinitionDescriptorDeployer.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ManagedExecutorDescriptorDeployer.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ManagedExecutorServiceConfig.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ManagedScheduledExecutorDefinitionDeployer.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ManagedThreadFactoryDescriptorDeployer.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployment/annotation/handlers/ManagedExecutorDefinitionHandler.java, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployment/annotation/handlers/ManagedScheduledExecutorDefinitionHandler.java, appserver/concurrent/concurrent-impl/src/test/java/org/glassfish/concurrent/runtime/ConcurrentRuntimeTest.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/ManagedExecutorDefinitionDescriptor.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/ManagedScheduledExecutorDefinitionDescriptor.java, appserver/packager/glassfish-common/pom.xml, appserver/pom.xml, appserver/tests/payara-samples/samples/concurrency/pom.xml, appserver/tests/payara-samples/samples/concurrency/src/main/java/fish/payara/sample/concurrency/annotations/managedscheduledexecutor/ManagedScheduledExecutorEJB.java, appserver/tests/payara-samples/samples/concurrency/src/test/java/fish/payara/sample/concurrency/annotations/managedscheduledexecutor/ManagedScheduledExecutorApplicationIT.java, core/pom.xml, pom.xml
We donated Fork&Join Pool to Concurro plus one fix, so we can start using the upstream project again
This PR integrates the latest version and also implements usage of virtual threads
I uploaded a testing application to the Jira ticket. The app defines its own MES:
```
@ManagedExecutorDefinition(name = "java:app/VirtMES", maxAsync = 10, virtual = true)
```
1. Compile Payara 7 and the app, both with Java 21.
2. Deploy the app to Payara
3. Open `http://localhost:8080/ConcurrencyVirtual-1.0-SNAPSHOT/rest/test`
It displays 3 stacktraces of the tasks, all of the ending with
```
java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
```
E.g. the threads are executed in virtual threads!
Linux, OpenJDK 21
I deployed concurro, version `3.1.0-SNAPSHOT` to our snapshot nexus repository. We …
=> FISH-7670 Integerate Latest Concurro with Virtual Threads

nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigExpressionResolver.java, nucleus/payara-modules/nucleus-microprofile/config-service/src/test/java/fish/payara/nucleus/microprofile/config/spi/ConfigExpressionResolverTest.java
- Fixes #6549 
None
Included in PR
I ran `ConfigExpressionResolverTest`, which has been extended in this PR, too.
Fedora 39 with Maven 3.9.6 and Java 17.0.9
-
If you want to see the failing test, simply checkout the PR branch and reset HEAD to one commit before. I compiled Payara using `mvn package -Dmaven.javadoc.skip -DskipTests -pl nucleus/payara-modules/nucleus-microprofile/config-service -am` and ran the tests from my IDE.
=> FISH-8317 - Microprofile Config NPE for profiled setting

core/pom.xml, pom.xml
Adds the snapshot and staging repos to the pom. 
Staging is hidden behind a profile because we shouldn't be relying on it - only added for convenience.
None
None
Built server - no new obvious warnings in logs.
Windows 11, Maven 3.9.6, Zulu JDK 11.0.22
N/A
None
=> Add Additional Repos

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/commands/GenerateHeapDumpCommand.java
Added the generate-heap-dump command
| Params    | Description|
| -------- | ------- |
| target | specifies the name of an instance, cluster or deployment group.    |
| outputDir | Where the heap dump file should be stored     |
| outputFileName | File name for the heap dump    |
If no outputFileName is present, a file name will be generated.
n/a
n/a
Built Payara, started domain and ran command, tested with target being an instance and deployment group with two instances.
openjdk version "1.8.0_372"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_372-b07)
OpenJDK 64-Bit Server VM (Temurin)(build 25.372-b07, mixed mode)
Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)
Maven home: C:\Maven\apache-maven-3.9.0
Java version: 1.8.0_372, vendor: Temurin, runtime: …
=> FISH-8227 Add Heap Dump command

core/core-parent/pom.xml, core/pom.xml
We relied on finding latest version of previously published API, but this fails for a deployment of branch 6.x.y, while there is already published branch 7.
It will be necessary to update value `payara.core.compare-version` every release. Therefor it is next to the version number.
Local build.
=> FISH-8453 Specify Previous Version Directly, No Automation

core/core-parent/pom.xml, core/pom.xml
Fixes a couple of warnings about missing plugin versions.
N/A
None
Built the server - no warnings about missing plugin versions for enforcer and build-helper.
Windows 11.
N/A
None
=> Fix Some Maven Build Warnings

core/pom.xml
Upgrades us to Parsson 1.1.5 with the JSONP-API deprecated to 2.1.0 to grab the fixes for CVE-2023-4043.
Parsson 1.1.5 includes the same upgrades that caught us out when we tried to upgrade to 1.1.4 - JSONP-API has been updated from 2.1.0.
Changes introduced in JSONP-API to the `JsonProvider.provider()` method appear to break our TCK runner.
They reworked how system properties are loaded by this SPI class, and it now (correctly) finds the system property. This however breaks us because this SPI class doesn't fall back to the other methods available for loading the factory class (service loader, OSGi, default) - it simply fails with a (wrapped) ClassNotFoundException.
In our case, we previously passed this TCK test because our Service Loader would end up returning the expected dummy TCK …
=> FISH-7757 FISH-8344 Upgrade to Parsson 1.1.5 with JSONP-API Deprecated to 2.1.0

appserver/admingui/cluster/src/main/resources/cluster/clusterSystemPropertiesButtons.jsf, appserver/admingui/common/src/main/resources/configuration/configSystemPropertiesButtons.jsf
Applies the fix from https://github.com/payara/Payara/pull/4497 to allow deleting system properties via the admin console.
None
None
Added a system proeprty via the admin console.
Deleted system property via the admin console.
Clicked off the page each time to ensure it was reloaded.
Windows 11, Zulu 11
N/A
None
=> CUSTCOM-75 FISH-8273 Allow Deleting System Properties via Admin Console

nucleus/common/common-util/src/main/java/com/sun/appserv/server/util/Version.java
The SNAPSHOT snipping was in the wrong place, and the update version can contain non-integers.
None
None
Built the server, and started the server - nothing amiss about the version in the logs.
Ran the `version` asadmin command - nothing amiss.
Loaded the admin console and clicked on "About" at the top to see the full version number - nothing amiss
Loaded Micro - nothing amiss about the version number printed out in the logs.
Windows 11, Zulu 11.0.22
N/A
None
=> FISH-8482 Adjust parsing of version number.

nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/GenericGrizzlyListener.java
This warning is displayed in the log files even though the http2 is disabled:
```
[2022-06-27T17:32:17.140+0100] [Payara 5.37.0] [WARNING] [] [org.glassfish.grizzly.config.GenericGrizzlyListener] [tid: _ThreadID=45 _ThreadName=RunLevelControllerThread-1656347531709] [timeMillis: 1656347537140] [levelValue: 900] [[
HTTP/2 (enabled by default) is unsupported with port unification and will be disabled for network listener admin-listener.]]
```
None
None
1. Start a Payara server domain
2. Create a local instance.
3. Disable HTTP 2 support:
4. set configs.config.server-config.network-config.protocols.protocol.admin-listener.http.http2-enabled=false
5. Check for the warning in the log files of the local instance.
None
=> FISH-6456: checking if http2 is enabled

nucleus/packager/external/vboxjws/pom.xml
Port of https://github.com/payara/Payara-Enterprise/pull/1231
Bumps org.virtualbox:vboxjws from 4.1.4 to 4.2.8.
---
updated-dependencies:
- dependency-name: org.virtualbox:vboxjws dependency-type: direct:production update-type: version-update:semver-minor ...
=> FISH-8556 Bump org.virtualbox:vboxjws from 4.1.4 to 4.2.8

core/pom.xml
Reverts payara/Payara#6649
Executing any asadmin command prints out:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jline.terminal.impl.exec.ExecTerminalProvider$ReflectionRedirectPipeCreator (file:/D:/Git/Payara2/appserver/distributions/payara/target/stage/payara6/glassfish/modules/jline.jar) to constructor java.lang.ProcessBuilder$RedirectPipeImpl()
WARNING: Please consider reporting this to the maintainers of org.jline.terminal.impl.exec.ExecTerminalProvider$ReflectionRedirectPipeCreator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
=> Revert "FISH-8557 Bump jline.version from 3.21.0 to 3.26.1"

nucleus/deployment/common/src/main/java/org/glassfish/loader/util/ASClassLoaderUtil.java
Avoid crashing due to FileSystemNotFound while behind a Spring boot
None
None
Samples, Quicklook etc
Zulu JDK 11 on Windows 11 with Maven 3.8.6
None
=> FISH-8044 : adding jar: packages into the classpath

Jenkinsfile, core/core-parent/pom.xml, pom.xml
Adds the Jakarta staging repo as a Maven repository (under a profile)
Also cherry-picks https://github.com/payara/Payara/pull/6541 because otherwise the exec ignores the command line defined profile (since it spins up a new maven command).
None
None
Cleaned maven repo, built server with `jakarta.security.enterprise.version` set to 4.0.0-M3
WSL
N/A
None
=> FISH-8634 Add Jakarta Staging Repo

pom.xml
Switches us from using maven exec to spin up a maven command inside our own maven command to more simply binding to a lifecycle phase.
Also updates us to the latest 2.4.0
None
None
Cleared maven repo.
Built server.
Checked that no unstaged changes: `git status`
Checked that a 3rd party license has been bundled in the Payara Server distribution under `payara6/glassfish/legal`
Changed Jackson version to 2.16.1 and rebuilt server.
Checked that a 3rd party license bundled in the Payara Server distribution under `payara6/glassfish/legal` has been updated appropriately.
Windows 11
N/A
None
=> Don't Use Maven Exec for 3rd Party License

appserver/extras/docker-images/pom.xml
Upgrades the base Docker Java images to 11.0.23, 17.0.11, and 21.0.3
None
None
Built the images locally, everything seems bon.
I've checked DockerHub and there appears to be AMD and ARM manifests for all images.
WSL
N/A
None
=> FISH-8627 FISH-8628 FISH-8269 Upgrade Docker Image Java Versions

.github/dependabot.yml
•	Jakarta EE APIs - Ignore major and minor version increases (patch updates only) on "jakarta*"
•	Jakarta EE Implementations - ignore major version increases (minor and patch updates only)
•	MicroProfile APIs - Ignore major and minor version increases (patch updates only). Can probably wildcard on "org.eclipse.microprofile.*"
•	Ignore all submodules
=> FISH-8497 update dependabot conditions

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/BundleDescriptor.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/archivist/Archivist.java, appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/descriptor/EjbBundleDescriptorImpl.java, appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/descriptor/EjbDescriptor.java
This PR addresses an issue where a `PersistenceContext` injected into a CDI bean, subsequently injected into a Message-Driven Bean (MDB) or a Stateless EJB, resolves to null. The problem occurs due to the different contexts in which the `EntityManager` Resource Descriptor instances are added during processing.
The issue arises when the EntityManager Resource Descriptor instance added to the CDI bean's `EjbBundleDescriptor` is not accessed from the MDB bean's `EjbMessageBeanDescriptor`. Although `EjbBundleDescriptor` is the parent descriptor context, it is not the superclass of `EjbMessageBeanDescriptor`. As a result, when accessing the `EntityManager` Resource Descriptor from `EjbMessageBeanDescriptor`, it does not look up in the `EjbBundleDescriptor` context, leading to a null resolution …
=> FISH-8309 Persistence Context is NULL on CDI Injected beans into MDB

appserver/packager/appserver-core/pom.xml, appserver/packager/external/jakarta-ee11-shim/pom.xml, appserver/packager/external/pom.xml, core/pom.xml
Upgrades HK2 to the version aligned with EE11 APIs (4.0.0) with our patches reapplied as we need them for compilation.
Also introduces the EE11 shim to fudge the OSGi bundle version validation, allowing us to avoid having to do a "big bang" update of all the dependencies all at once. 
The shim as introduced here has an upgrade shim for Annotations 2.1 to 3.0, as HK2 now requires Annotations 3.0 but the server is currently providing 2.1 (upgrading annotations would kick off a large dependency chain and will be tackled separately).
The shim also contains a downgrade shim for HK2 itself, as we're not upgrading Jersey at this moment (Jersey 3.1 still uses HK2 3.0) as it also kicks off a chain of dependency updates e.g. Grizzly. This shim also covers the HK2 requirement in InSights, which we …
=> FISH-8635 FISH-8653 Upgrade HK2 and Introduce EE11 Shim

core/pom.xml, pom.xml
Upgrades the monitoring console to one aligned with EE11 and Payara 7.
Version purposefully left as SNAPSHOT for now, as we may want to push additional changes.
https://github.com/payara/monitoring-console/pull/42
https://github.com/payara/patched-src-hk2/pull/34
https://github.com/payara/Payara/pull/6693
https://github.com/payara/Payara/pull/6630
None
Built the server and started the admin console - monitoring console factory resolved and bootstrapped.
Enabled the monitoring console, some metrics, and loaded the console:
* `asadmin set-monitoring-console-configuration --enabled=true`
* Admin Console -> Configurations -> server-config -> Monitoring -> enable everything
* Load localhost:8080/monitoring-console - should load successfully and you should be able to see the graphs collecting …
=> FISH-8664 Payara 7 Monitoring Console

Jenkinsfile, appserver/tests/functional/embeddedtest/README.md, appserver/tests/functional/embeddedtest/pom.xml, appserver/tests/functional/embeddedtest/src/test/java/fish/payara/embedded/EmbeddedDeploymentIT.java, appserver/tests/functional/payara-micro/pom.xml, appserver/tests/functional/payara-micro/src/test/java/fish/payara/functional/micro/ClusterHAJSPPage.java, appserver/tests/functional/payara-micro/src/test/java/fish/payara/functional/micro/DualSessionsIT.java
Add a new stage in the Jenkins pipeline to run the functional test for payara micro and payara embedded.
Note: when running the test for Payara Micro, one step installs the dependencies for Playwright. This may throw an error 
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 3598 (unattended-upgr)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
This has to do with different installations colliding. As of now, I haven't found a simple way to avoid that issue from happening.
=> FISH-8630 - run functional test with payara micro in Jenkins pipeline

appserver/packager/external/jakarta-ee11-shim/pom.xml, core/pom.xml
Upgrade Expression Language API to 6.0
None
None
Payara Samples, Quicklook etc
Zulu JDK 21 on WSL Ubuntu 22.04 with Maven 3.8.4
=> Fish 8722 upgrade expression language api to 6

core/pom.xml
Updates the Payara Security Connectors to 3.1.1.
Release and publication of said security connectors.
N/A
None - security connectors not released yet
Windows 11, Zulu 11.0.23
N/A
None
=> FISH-8760 Update Security Connectors to 3.1.1

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/BundleDescriptor.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/archivist/Archivist.java, appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/descriptor/EjbBundleDescriptorImpl.java, appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/descriptor/EjbDescriptor.java
Fix for Persistence Context injection issue on CDI beans and TCK fix for EJB Remote tests
This PR addresses an issue where a PersistenceContext injected into a CDI bean, subsequently injected into a Message-Driven Bean (MDB) or a Stateless EJB, resolves to null. The problem occurs due to the different contexts in which the EntityManager Resource Descriptor instances are added during processing.
The issue arises when the EntityManager Resource Descriptor instance added to the CDI bean's EjbBundleDescriptor is not accessed from the MDB bean's EjbMessageBeanDescriptor. Although EjbBundleDescriptor is the parent descriptor context, it is not the superclass of EjbMessageBeanDescriptor. As a result, when accessing the EntityManager Resource Descriptor from EjbMessageBeanDescriptor, it does not …
=> FISH-8309: Persistence Context is NULL on CDI Injected beans into MDB and tck fix

nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/ASURLClassLoader.java
Optimize multi-release JAR processing, remove resource leak from MR-JarFile remaining open
Opening MR-Jars correctly by using `RUNTIME_VERSION`
fixes #6554 
Deploy original reproducer for this issue
Any
=> FISH-8688 improvement: optimize MR-jar class loading

appserver/web/web-core/src/main/java/org/apache/catalina/core/ContainerBase.java, appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java
fixes #6747 
Bugfix. #6637 caused a regression that left dangling threads around
Manual testing for memory leaks
=> Properly cleaning up ContainerBackgroundSessionProcessor threads after application is undeployed

nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java
Fixes instances in a deployment group getting the incorrect configuration getting injected.
None
None
* Disable auto increment port: Admin Console > Domain > Data Grid > Auto Increment Port > Disable
* Create an instance: instance1
* Create a second instance: instance2
* Set Hazelcast port for instance1 to 12000
* Set Hazelcast port for instance2 to 13000
* Restart DAS
* Create a deployment group and add instance1 & instance2 to it: group1
* Start deployment group: both instances should start successfully, with instance1 binding Hazelcast to 12000 and instance2 to 13000 (should be no port conflicts, as this would imply both instances are using the same Hazelcast config and trying to bind to the same port)
Windows 11, Zulu 11.0.23
N/A
None
=> FISH-8334 Fix Incorrect Hazelcast Config for Instances in Deployment Groups

.gitignore, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/EjbInvocation.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/EjbInvocationFactory.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/BaseContainer.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EjbAsyncInvocationManager.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EjbAsyncTask.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EjbEndpointFacadeImpl.java, appserver/ejb/ejb-full-container/src/main/java/org/glassfish/ejb/mdb/MessageBeanContainer.java, appserver/payara-appserver-modules/microprofile/telemetry/src/main/java/fish/payara/microprofile/telemetry/tracing/jaxrs/OpenTelemetryApplicationEventListener.java, appserver/payara-appserver-modules/microprofile/telemetry/src/main/java/fish/payara/microprofile/telemetry/tracing/jaxrs/OpenTracingHelper.java, appserver/payara-appserver-modules/microprofile/telemetry/src/main/java/fish/payara/microprofile/telemetry/tracing/jaxrs/ResourceCache.java, appserver/persistence/entitybean-container/src/main/java/org/glassfish/persistence/ejb/entitybean/container/EntityContainer.java, appserver/security/core-ee/src/main/java/com/sun/enterprise/security/jacc/context/PolicyContextHandlerData.java, appserver/tests/payara-samples/classloader-data-api/src/main/java/fish/payara/samples/classloaderdata/InstanceResource.java, appserver/web/gf-web-connector/src/main/java/fish/payara/appserver/context/JavaEEContextUtilImpl.java, appserver/web/war-util/src/main/java/org/glassfish/web/loader/CachingReflectionUtil.java, appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java, appserver/web/web-core/src/main/java/org/apache/catalina/core/ApplicationFilterConfig.java, appserver/web/web-core/src/main/java/org/apache/catalina/core/ContainerBase.java, appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java, appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardEngine.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebComponentInvocation.java, core/core-parent/pom.xml, nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/ASURLClassLoader.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/ComponentInvocation.java, nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/DeployCommandSupplementalInfo.java
Fixes ClassLoader leaks
fixes #6554 (partial fix, performance isn't addressed, just leaks)
fixes #6301 
fixes #4098 
Tested with `appserver/tests/payara-samples/classloader-data-api` leak tester app and VisualVM
Any
=> FISH-8672 bugfix: removed class loader leaks

core/pom.xml
Core compare version didn't get updated by release job.
None
None
Built the server.
Windows 11, Zulu 11.0.23
N/A
None
=> Update Core Compare Version

appserver/admingui/common/src/main/resources/pluginTreeNodeSecurity.jsf
FISH-5740 URL redirects to audit instead of security jsf
Built the server and tested it points to the right direction
=> FISH-5740: changed URL direction and updated copyright date.

appserver/web/web-core/src/main/java/org/apache/catalina/core/ContainerBase.java, appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardEngine.java, core/core-parent/pom.xml, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/ComponentInvocation.java
https://github.com/payara/Payara/pull/6677 introduced breaking changes to Core classes, which in turn broke Enterprise.
This reinstates semantic versioning and "unbreaks" the changes.
None
None
Built this branch and started the domain - everything bon.
Built Payara Enterprise - compiles correctly.
I haven't tested for leaks (yet™), but I don't believe I've reintroduced usage of the non-WeakReference or Atomic variables anywhere.
Windows 11, Zulu 11.0.23
N/A
I am aware these changes are ugly and fragile. It is however the state we end up in when we have a split codebase and enforce semantic versioning. We're in a bit of a pickle because the Core major versions are somewhat tied to Jakarta APIs - 7.0.0.Alpha1 has already been released for usage with Payara 7. 
Naming is also hard - if you …
=> FISH-8672 FISH-8857 Keep Semantic Versioning Happy

nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java, nucleus/admin/launcher/src/test/java/com/sun/enterprise/admin/launcher/GFLauncherExtractPortTest.java
This is a fix.
Related:
- https://github.com/payara/Payara/issues/4386
- https://github.com/payara/Payara/pull/4387 - but it didn't consider alteration made in `JavaConfig.java` (https://github.com/payara/Payara/pull/3905) https://github.com/payara/Payara/blob/26c504bb440432cfaa40e425730650945a23c823/nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/JavaConfig.java#L165
New UT added for host part in address.
```
$ uzip -q -d /tmp/payara appserver/distributions/payara/target/payara.zip
$ /tmp/payara/payara6/glassfish/bin/asadmin start-domain --debug=true
Waiting for domain1 to start .............
Successfully started the domain : domain1
domain  Location: /tmp/payara/payara6/glassfish/domains/domain1
Log File: …
```
=> FISH-8728 Refine RE to allow host in jdwp agent address

appserver/admingui/cluster/src/main/resources/dg/dgNew.jsf, appserver/admingui/cluster/src/main/resources/org/glassfish/cluster/admingui/Strings.properties
FISH-8855 added auto name for deployment group
I have made changes to the strings.properties file so that instead of saying autoname instance, it says autoname instance/deployment group so it saves creating another autoname.help text.
Changed dgNew.jsf to include the checkbox button and changed the commands block for the new button so that the Deployment group label does not show as required (as autoname is an option) and if autoname is selected, it will use the same code as the instance autoname.
Built and ran the server, made sure it was working. Tested auto naming multiple deployment groups and instances to make sure both worked correctly. Tested leaving everything blank to display error messages and tested setting own name + ticking the box to make sure that if the label is populated, …
=> FISH-8855-Added Auto name for deployment group

Jenkinsfile
Add a retry mechanism to retry failing tests in the pipeline, instead of requiring to rerun the whole build and other tests for one failure
the retry mechanism can be witnessed in this run: https://jenkins.payara.fish/blue/organizations/jenkins/Payara%20Community%20PR%20Testing/detail/PR-6746/9/pipeline/82/
=> FISH-8796 - add retry to test suites running in pipeline

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/SnifferManagerImpl.java
Fixes the XML Web Services engine seemingly only starting inconsistently.
In the case that an application bundles its own version of Metro, the annotations that the Web Service Sniffer looks for will be detected by HK2 twice - once as an `AnnotationType` and once as an `InterfaceModel`.
Within HK2, both of these get stored in a Map of Maps with the same name (but in different maps). It’s a Map essentially indexed by the class name, but separated into separate Maps based on the model type (AnnotationType vs. InterfaceModel vs. EnumType etc.).
```
/**
* Storage indexed by TYPE : interface | class | annotation and then by name.
*/
private final ConcurrentMap<Class, ConcurrentMap<String, TypeProxy<Type>>> storage=
new ConcurrentHashMap<Class, ConcurrentMap<String, TypeProxy<Type>>>();
```
The …
=> FISH-8736 Fix for Web Services Engine Inconsistently Starting

appserver/payara-appserver-modules/payara-micro-service/src/main/java/fish/payara/appserver/micro/services/PayaraInstanceImpl.java
Fix `list-hazelcast-cluster-members` command and the associated Data Grid Members page on the Admin Console from showing no instances after configuring (and rebooting) Hazelcast.
None
None
Started admin console and looked at the data grid members page - should be one instance present.
Go back to Data Grid configuration tab and restart the data grid.
Go back to the data grid members - the server instance should still be present.
Also ran the Docker-based reproducer from the Jira issue.
Windows 11
Docker
N/A
None
=> FISH-8794 Fix PayaraInstanceImpl Desync on Restart of Hazelcast 

nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/HazelcastCore.java
Check that the Hazelcast encryption settings have actually changed before displaying "Restart Required".
None
None
Started the admin console and went to the datagrid config page (Domain > Data Grid).
Set 'Restart Data Grid' to true (and change nothing else) and click 'Save' - "Restart Domain" should not be shown.
Enable 'Encrypt Data Grid' and click 'Save' again - "Restart Domain" should be shown (as well as some warnings saying you haven't configured it properly).
Windows 11
N/A
None
=> FISH-8953 Fix Incorrect Unprocessed Change Showing for Hazelcast Encryption Settings

core/pom.xml, nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/CLICommand.java
-  Resolves FISH-8557
- Prevents the illegal reflection warning message from appearing on JDK 11.
Built the server and deployed a simple application.
=> FISH-8557 Upgrade JLine to 3.26.3

core/pom.xml
Upgrades the EL API to 6.0.1 to allow passing the TCK.
None
None
Ran the EL TCK.
Started the admin console and clicked around - no explosions
Windows 11, Java 21.0.3
N/A
None
=> FISH-8987 Upgrade EL API to 6.0.1

nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/admin/ClearCache.java
FISH-8888 clear-cache command endpoint incorrect.
I changed the parameter name to cache-name as the previous key was already being used which resulted in an error.
Tested using ./asadmin start-domain --debug domain1. Got the name of a cache from - localhost:4848/management/domain/list-caches and cleared successfully.
=> FISH-8888 ClearCache command rest endpoint corrected

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLoaderService.java, nucleus/resources/src/main/java/org/glassfish/resourcebase/resources/util/BindableResourcesHelper.java
This is a fix to a reported bug caused by referenced resources used on app's
Manual testing on the server following described steps on the following tickets:
- https://payara.atlassian.net/browse/FISH-6659
- https://payara.atlassian.net/browse/FISH-9098
step 1: create instance and start:
step 2: create jdbc resource without assigned to an specific target
step3: deploy application to the instance created: clusterjsp and SimpleJndiLookup-1.0-SNAPSHOT
Observe components section for both:
step 4: Stop the instance and domain
step 5: Start the domain again, now you can't see any error during startup, this means the issue of the resource is fixed and if we look the Modules and Components for the applications we will see the details for it each application and both should look the same as …
=> FISH-9098: fix for deployments caused by referenced resources from apps

core/core-parent/pom.xml, core/pom.xml
Moves the enforcer to the core-aggregator.
Being under core-parent meant it wasn't being used by the majority of the codebase.
Also updates the minimum Maven version to 3.6.3.
None
None
Built the server.
Ran `mvn versions:display-plugin-updates -pl .` and it didn't scream about the minimum Maven version not being defined.
Windows 11, Zulu 11.0.23, Maven 3.9.8
N/A
None
=> FISH-9082 Move Enforcer to `core-aggregator`

core/pom.xml
This reverts commit 0514ba3aef666330a145155655aa306a7d1fbd16.
Upgrading Tyrus appears to break the TCK, due to an OSGi error
```
org.osgi.framework.BundleException: Unable to resolve org.glassfish.tyrus.container-grizzly-client [47](R 47.0): missing requirement [org.glassfish.tyrus.container-grizzly-client [47](R 47.0)] osgi.wiring.package; (osgi.wiring.package=org.glassfish.tyrus.client.exception) Unresolved requirements: [[org.glassfish.tyrus.container-grizzly-client [47](R 47.0)] osgi.wiring.package; (osgi.wiring.package=org.glassfish.tyrus.client.exception)]
```
None
None
Ran the Websocket TCK
Jenkins and local (WSL)
N/A
None
=> FISH-9185 Revert "FISH-8933 Upgrade tyrus to 2.1.5.payara-p1"

nucleus/packager/nucleus-jersey/pom.xml
- Resolves FISH-9111
Reproducer can be found in [this repository](https://github.com/Viii3/Reproducer-FISH-9111).
Built Payara and tested against the reproducer.
Java version: 21.0.3, vendor: Eclipse Adoptium
=> FISH-9111 stax2-api dependency.

appserver/admingui/payara-console-extras/src/main/java/fish/payara/admingui/extras/rest/PayaraRestApiHandlers.java, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/readers/InputObject.java, nucleus/payara-modules/asadmin-recorder/src/main/java/fish/payara/asadmin/recorder/AsadminRecorderService.java
- Resolves 3 issues from Spotbugs
- Resolves FISH-9176
- FISH-9193
- FISH-9194
- FISH-9195
- Built the server and deployed clusterjsp.
- Ran spotbugs and examined the reports to see the associated issues are no longer present.
=> FISH-9176 FISH-9193 FISH-9194 FISH-9195 Improvements from Spotbugs

appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebContainer.java
Bugfix. Application Deployment failure results Class Loader leak and extra error messages.
The root cause is the message stops undeployment process from proceeding further.
This is now fixed and leaks are removed.
```
[#|2024-07-28T04:01:23.573-0500|SEVERE|Payara 6.2024.7|jakarta.enterprise.web.core|_ThreadID=97;_ThreadName=admin-thread-pool::admin-listener(1);_TimeMillis=1722157283573;_LevelValue=1000;_MessageID=AS-WEB-CORE-00175;|
Exception during cleanup after start failed
org.apache.catalina.LifecycleException: Manager has not yet been started
at org.apache.catalina.session.StandardManager.stop(StandardManager.java:872)
at org.apache.catalina.core.StandardContext.stop(StandardContext.java:5954)
at com.sun.enterprise.web.WebModule.stop(WebModule.java:648)
at …
```
=> FISH-9171 bugfix: prevent deployment failures from causing an undeployment failure and leaks

nucleus/payara-modules/payara-executor-service/src/main/java/fish/payara/nucleus/executorservice/PayaraExecutorService.java
Disable PayaraExecutorService events before server shuts down.
Prevents exceptions on shutdown as described in linked issue
fixes #6879
=> FISH-9222 bugfix: disable PayaraExecutorService events before server shuts down

appserver/admingui/web/src/main/resources/configuration/httpListenerTabs.inc, appserver/admingui/web/src/main/resources/grizzly/listenerTabs.inc, appserver/admingui/web/src/main/resources/grizzly/protocolTabs.inc
In the admin console, the SSL settings tab should be hidden when security is disabled.
This PR gets the securityEnabled attribute and renders the tab if security is enabled.
n/a
n/a
Manual testing, started admin console, visited server-config -> http listeners, network listeners and protocols. 
Verified that the ssl tab was rendered correctly based on Security being enabled.
Java version: 11.0.23, vendor: Azul Systems, Inc., runtime: /Users/kalinchan/.sdkman/candidates/java/11.0.23-zulu/zulu-11.jdk/Contents/Home
OS name: "mac os x", version: "14.6.1", arch: "aarch64", family: "mac"
n/a
n/a
=> FISH-6579 Hide ssl tab when security is disabled

appserver/web/web-naming/src/main/java/org/apache/naming/resources/FileDirContext.java
A customer has reported that their document root bases that point to directories that live on a DFSN server do not work correctly on Payara Server when the server runs on a Windows Server 2019.
None
None
Quicklook, Samples etc
Zulu JDK 11 on Ubuntu 22 with Maven 3.8.4
None
=> FISH-9186 : Use the LinkOption.NOFOLLOW_LINKS option

appserver/web/jsf-connector/src/main/java/org/glassfish/faces/integration/GlassFishInjectionProvider.java, pom.xml
- Resolves FISH-8142
- Depends on [Faces TCK 4.0.3](https://github.com/payara/jakartaee-10-tck-runners/pull/74)
- Depends on [Jenkins using the 4.0.3 folder](https://github.com/payara/EngineeringJenkinsjobs/pull/124)
Built the server and ran it against Faces TCK 4.0.3
Maven version: 3.6.3
OS name: "linux", version: "6.8.0-40-generic", arch: "amd64", family: "unix"
=> FISH-8142 Update Mojarra

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLoaderService.java
Adding validation to skip deploy on target, when not needed
This is to fix a reported issue where an application is deployed on the server instead of only deploy on the instance that was defined from the beginning
Manual testing by deploying multiple applications on different instances and then stop and restart to validate if only the applications are deployed on the instances and not the server:
Follow the steps described on the ticket, here details: https://payara.atlassian.net/browse/FISH-9502
applications attached here:
[Reproducers.zip](https://github.com/user-attachments/files/16681343/Reproducers.zip)
for the steps described on the ticket use the following file: clusterjsp.war
then create other two instances and deploy the following applications:
1. simpleRest.war
2. …
=> FISH-9502: adding validation to skip deploy on target

appserver/extras/docker-images/pom.xml
Upgrades the Docker JDKs to 11.0.24, 17.0.12, and 21.0.4.
None
None
Built the Docker images and let the integration test run.
Windows 11, Zulu JDK 11.0.24, Maven 3.9.8, Docker Desktop 4.33.1
N/A
None
=> FISH-9579 FISH-9580 FISH-9582 Upgrade Docker JDKs

nucleus/pom.xml
Upgrades Apache Ant to 1.10.15, and aligns the ant-launcher dependency to the same version and property.
None
None
Jenkins
N/A
None
=> FISH-9604 Upgrade Ant to 1.10.15

appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/UtilHandlers.java, appserver/admingui/common/src/main/resources/configuration/sysInstanceValues.jsf, appserver/admingui/common/src/main/resources/configuration/systemProperties.jsf, appserver/admingui/corba/src/main/resources/iiopServerPageNode.jsf, appserver/admingui/web/src/main/resources/serverPageNode.jsf
Escapes properties in admin console
Reproducer in JIRA
=> FISH-9553 Sanitise properties in admin console

api/payara-bom/pom.xml, appserver/tests/payara-samples/pom.xml
This dependency was renamed a while ago.
None
None
Checked in IDE that dependency version of `arquillian-payara-micro-remote` is inherited from bom.
IntelliJ IDE
N/A (apparently - no mention of it in https://github.com/payara/Payara-Documentation)
None
=> FISH-9618 Fix Incorrect `payara-micro-remote` Dependency Name

nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/Cluster.java, nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/ImportSyncBundleCommand.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/security/SecurityUtils.java, nucleus/common/common-util/src/main/java/org/glassfish/common/util/RandomUtils.java
Used `SecurityUtils` to generate a random and use it within the respective classes. Spot bugs issue. (check description)
Spotbugs warning:
```
Random object created and used only once in com.sun.enterprise.admin.cli.cluster.ImportSyncBundleCommand.backupInstanceDir()
This code creates a java.util.Random object, uses it to generate one random number, and then discards the Random object. This produces mediocre quality random numbers and is inefficient. If possible, rewrite the code so that the Random object is created once and saved, and each time a new random number is required invoke a method on the existing Random object to obtain it.
If it is important that the generated Random numbers not be guessable, you must not create a new Random for each random number; the values are too easily …
```
=> FISH-9771 FISH-9688 spot bugs random only used once

appserver/security/core-ee/src/main/java/com/sun/enterprise/security/jacc/JaccWebAuthorizationManager.java
Resync with an update from Eclipse GlassFish, updating a very old (and unused) method to have batter handling for accessing secure variants of URLs.
I also removed another unused method while I was at it.
None
None
Ran the Jakarta Servlet TCK locally - all but the client cert tests passed (improvement from before)
Windows 11, Zulu JDK 21.0.4, Maven 3.9.9
N/A
None
=> FISH-9853 Improve Handling for Accessing Secure Variant of URL

appserver/web/web-core/src/main/java/org/apache/catalina/Store.java, appserver/web/web-core/src/main/java/org/apache/catalina/session/PersistentManagerBase.java, appserver/web/web-ha/src/main/java/org/glassfish/web/ha/session/management/HAStoreBase.java
Fixed regression introduced in #6637 
- compare update times to stored session in HA scenarios only
- Use `store.load()` instead of `swapIn()` to load sessions during update time comparison, as `swapIn()` has side effects, such as replacing session object in the session map, and calling users' activation handlers every time a session is retrieved, leading to session loss and performance issues
To further explain this, when the session is replaced in the map by `swapIn()`, other copies of the session hang around in other threads.
Sessions get stored in HA store at the end of each request, and only the session currently in the map gets updated.
Those other copies do not get stored in the HA store when request ends, since they are no longer in the session map.
This leads to the data loss. …
=> FISH-9748 bugfix: fix HA session race condition leading to session attribute loss

appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/monitoring/WebServiceTesterServlet.java
=> FISH-9803 - NPE prevented by update of index in array to prevent null value as input.

appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/annotation/handlers/AbstractAuthAnnotationHandler.java, appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/descriptor/EjbDescriptor.java, appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/security/application/EJBSecurityManager.java, appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/security/application/PayaraToExousiaConverter.java, appserver/security/core-ee/src/main/java/com/sun/enterprise/security/jacc/JaccEJBConstraintsTranslator.java
Fixes the EJB authorization tests in the Authorization TCK.
This is intended as a stop-gap solution for now, as I believe this class (and all surrounding JACC code) needs some heavy rewrites - we're only "half" using Exousia in the current state, duplicating a lot of code and so not always using Exousia itself for authorization.
None
None
Ran the Authorization TCK, didn't spot any new failures (_app-custom-policy2_ tests fails regardless)
Ran all currently passing TCKs, no new failures (jsp runner is currently broken - ignore. #WorksOnMyMachine): https://jenkins.payara.fish/view/Build/job/JakartaEE-11-TCK/48/
OpenSUSE WSL, Maven 3.9.9, Zulu JDK 21.0.4
N/A
None
=> FISH-9802 Fix EJB Failures in Authorization 3.0 TCK

core/pom.xml
This reverts commit 25f915e9cdf419b2eaa709771fb686862626e786, reversing changes made to c358409cddf764b9ebf416e981c38acd4d5c979b in #7015
It breaks the generation of sources and needs addressing separately
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-source-plugin:3.3.1:jar-no-fork (attach-sources) on project opentelemetry-repackaged: Presumably you have configured maven-source-plugin to execute twice in your build. You have to configure a classifier for at least one of them. -> [Help 1]`
None
None
Built the server and let sources get generated
Windows 11, Zulu JDK 11.0.24, Maven 3.9.9
N/A
None
=> FISH-9961 Revert #7015

appserver/security/jaspic-provider-framework/src/main/java/com/sun/jaspic/config/factory/BaseAuthConfigFactory.java, core/pom.xml
Upgrades the Authentication API to 3.1.1, and removes Security Manager code from the `BaseAuthConfigFactory` as the permissions inherited from the Jakarta API had been removed.
None
None
Built the server and let unit tests run, started the admin console and poked around - no explosions
Windows 11, Zulu JDK 21.0.4, Maven 3.9.9
N/A
None
=> FISH-8927 Upgrade Authentication API

appserver/admingui/cdieventbus-notifier-console-plugin/src/main/resources/cdieventbus/cdiEventbusNotifierConfiguration.jsf, appserver/admingui/eventbus-notifier-console-plugin/src/main/resources/eventbus/eventbusNotifierConfiguration.jsf, appserver/admingui/jms-notifier-console-plugin/src/main/resources/jms/jmsNotifierConfiguration.jsf, appserver/admingui/payara-console-extras/src/main/resources/notification/notification.jsf
- Resolves FISH-10034
- Admin Console drop-down now uses descending order for severity levels.
Built the server, opened the admin console, examined the drop-down for filters.  
Used the admin console to change the filter levels and verified this worked in the CLI.
=> FISH-10034 Filter Ordering

appserver/extras/docker-images/pom.xml
Upgrades the Docker JDKs to 21.0.5, 17.0.13, and 11.0.25.
None
None
Build Docker images locally
Windows 11
N/A
None
=> FISH-10086 FISH-10087 FISH-10088 Upgrade Docker JDKs

nucleus/payara-modules/notification-core/src/main/java/fish/payara/nucleus/notification/admin/TestNotifier.java
- Resolves FISH-10107
- The "test" button in the Admin Console now sends the notification at `SEVERE` level. This ensures the test message is always received, regardless of notifier configuration.
Configured the Teams notifier with a webhook, set the Teams notifier to `SEVERE`, pressed the "test" button in the Admin Console, saw the message appear on Teams.
=> FISH-10107 Test Notifier Severity

appserver/packager/external/jakarta-ee11-shim/pom.xml
Add a downgrade shim for security, currently required by the OpenID security connector.
None
None
None
My brain
N/A
None
=> Security API downgrade shim

appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
Adds a fallout clause for if field doesn't exist. The field in question belonged in Mojarra, who have since potentially fixed the issue themselves in https://github.com/eclipse-ee4j/mojarra/pull/5479?
Without this change, the following error is thrown on application deployment/undeployment (most prominently in Micro and Embedded)
```
[2024-11-13T08:49:24.762+0200] [] [WARNING] [] [jakarta.enterprise.web.util] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1731480564762] [levelValue: 900] [[
Error clearing BeanELResolver cache
java.lang.NullPointerException
at org.glassfish.web.loader.WebappClassLoader.clearBeanResolver(WebappClassLoader.java:2677)
at org.glassfish.web.loader.WebappClassLoader.clearBeanELResolverCache(WebappClassLoader.java:2666)
at …
```
=> FISH-10136 Fix NPE in Payara Micro and Embedded

nucleus/admin/config-api/src/main/java/org/glassfish/config/support/DomainXmlPreParser.java, nucleus/admin/config-api/src/main/java/org/glassfish/config/support/InstanceReaderFilter.java
- Resolves FISH-10146
- Instances no longer strip data from the `<deployment-groups>` block of the domain xml.
- Instances have improved checking for deciding whether or not to discard a config from their own domain xml.
- Previously instances would discard any config for instances not in their _first_ deployment group. They now check all of their deployment groups.
- Resolves FISH-9875
- Deployment groups that share instances no longer exhibit inconsistent behaviour.
Tested using a modified reproducer for FISH-10146:
The following batch file was used for testing.
```
@ECHO OFF
CALL asadmin start-domain
echo.
CALL asadmin create-local-instance instance1
echo.
CALL asadmin start-local-instance instance1
echo.
CALL asadmin create-deployment-group group1
echo.
CALL asadmin …
```
=> FISH-10146 FISH-9875 Deployment Group Nullpointer

core/pom.xml
Upgrades Parsson to 1.1.7, for compliance with EE11 artefacts (currently requires the shim to work)
None
None
Loaded the admin console and clicked around - no explosions
Windows 11, Zulu JDK 21.0.5, Maven 3.9.9
N/A
None
=> FISH-10141 Parsson 1.1.7

pom.xml
Upgrades Metro to 4.0.4 and Woodstox 7.1.0, for compliance with EE11 artefacts (currently requires the shim to work).
At some point we will need to review if our existing patches need reapplying to Metro.
None
None
Loaded the admin console and clicked around - no explosions
Windows 11, Zulu JDK 21.0.5, Maven 3.9.9
N/A
None
=> FISH-10142 FISH-10279 Metro 4.0.4 and Woodstox 7.1.0

core/pom.xml, nucleus/hk2/hk2-config/pom.xml
When attempting to serialize and deserialize an instance of the jakarta.validation.ConstraintViolation class on a Jakarta application, the server runtime will trigger a java.lang.ClassCastException mentioning that an instance of org.hibernate.validator.constraints.CompositionType cannot be assigned to a field of the same class. 
None
None
1. Build Payara Community
2. Start Payara Server domain and deploy the WAR artefact (**manual-validator-app-p6.war**) attached at: https://payara.atlassian.net/browse/FISH-10036
3. Test the application’s REST endpoint:
`curl "http://localhost:8080/manual-validator-app/api/vehicle?name=Lewis"`
**The operation should work correctly and print 200 http code with the results**
Zulu JDK 11 on Windows 11 with Maven 3.9.0
None
None
=> Fish 10036 class cast ex deserializing validation instance p6

api/payara-bom/pom.xml, appserver/extras/embedded/all/pom.xml, appserver/extras/embedded/web/pom.xml, appserver/extras/payara-micro/payara-micro-distribution/pom.xml, appserver/featuresets/payara-web/pom.xml, appserver/packager/payara-mvc/pom.xml, appserver/packager/payara-mvc/src/main/assembly/payara-mvc.xml, appserver/packager/payara-mvc/src/main/resources/pkg_proto.py, appserver/packager/pom.xml, appserver/packager/resources/pkg_conf.py, appserver/tests/payara-samples/samples/mvc/pom.xml, appserver/tests/payara-samples/samples/mvc/src/main/java/fish/payara/samples/mvc/AppController.java, appserver/tests/payara-samples/samples/mvc/src/main/java/fish/payara/samples/mvc/RestConfiguration.java, appserver/tests/payara-samples/samples/mvc/src/main/java/fish/payara/samples/mvc/Salutation.java, appserver/tests/payara-samples/samples/mvc/src/main/webapp/WEB-INF/beans.xml, appserver/tests/payara-samples/samples/mvc/src/main/webapp/WEB-INF/faces-config.xml, appserver/tests/payara-samples/samples/mvc/src/main/webapp/WEB-INF/views/greet.xhtml, appserver/tests/payara-samples/samples/mvc/src/main/webapp/WEB-INF/views/salute.xhtml, appserver/tests/payara-samples/samples/mvc/src/main/webapp/WEB-INF/web.xml, appserver/tests/payara-samples/samples/mvc/src/test/java/fish/payara/samples/mvc/PayaraMvcIT.java, appserver/tests/payara-samples/samples/pom.xml, pom.xml
Initial PoC of bundling the MVC 2.1 API and Krazo 3.0 as its implementation.
None
Added a sample
I've built the server and started the admin console and nothing exploded.
Ran Payara through the Krazo TCK and testsuite modules: https://github.com/eclipse-ee4j/krazo/tree/3.0.1
Ran test sample against server-remote and micro-managed profiles
Windows 11, Zulu JDK 11.0.25, Maven 3.9.9
https://github.com/payara/Payara-Documentation/pull/524
None
=> FISH-10211 MVC 2.1 and Krazo 3.0

appserver/web/web-core/src/main/java/org/apache/catalina/connector/Request.java
This will fix the failing `getValueQuotedTest` in the servlet tck.
n/a
Ran the servlet tck
```
mvn clean verify -B -Dpayara.version=7.2024.1.Alpha3-SNAPSHOT -pl . -pl servlet-tck -Ppayara-server-managed,jakarta-staging -Dit.test=servlet.tck.api.jakarta_servlet_http.cookie.CookieTests
```
This will cause tags to possibly fail due to reverting the fix
=> FISH-10042 Dont strip cookie of quotes

core/pom.xml
This reverts commit 18f394ae3f6f014d2d01f9833f4c5a762431a541, reversing changes made to de796c9744ca69aa6c075c35f86e34535088c8b4.
Upgrading to Parsson 1.1.7 breaks the JSON-P TCK.
None
None
Ran the JSON-P TCK - passed
WSL
N/A
None
=> Revert Parsson Upgrade (Release)

core/pom.xml
This reverts commit 18f394ae3f6f014d2d01f9833f4c5a762431a541, reversing changes made to de796c9744ca69aa6c075c35f86e34535088c8b4.
Upgrading to Parsson 1.1.7 breaks the JSON-P TCK.
None
None
Ran the JSON-P TCK - passed
WSL
N/A
None
=> Revert Parsson Upgrade

core/core-parent/pom.xml, core/pom.xml, nucleus/grizzly/config/src/test/java/org/glassfish/grizzly/config/HttpRedirectTest.java
Adding Header validation for RFC-9110
This is a security fix to prevent issues based on CVE reported here:  `[CVE-2024-45687](https://www.cve.org/CVERecord?id=CVE-2024-45687)` and here [glassfish issue](https://github.com/eclipse-ee4j/glassfish/issues/25128)
Manual testing:
To test this set the dependency version on the payara server: 4.0.0.payara-p2 build and run
deploy the following reproducer: 
[ReproducerJDK11.zip](https://github.com/user-attachments/files/17711134/ReproducerJDK11.zip)
By default grizzly is setting two new properties that enable the validation of the headers by default. You can customize this behavior by seeting the following properties from UI or by cli command o directly on the domain.xml file 
- -Dorg.glassfish.grizzly.http.STRICT_HEADER_NAME_VALIDATION_RFC_9110=tru …
=> FISH-9690: adding new version of grizzly to validate headers RFC-9110

nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/CLIUtil.java, nucleus/core/kernel/src/main/java/fish/payara/enterprise/admin/CreateSystemProperty.java, nucleus/core/kernel/src/main/java/fish/payara/enterprise/admin/LocalStrings.properties, nucleus/core/kernel/src/main/manpages/com/sun/enterprise/v3/admin/create-system-properties.1, nucleus/core/kernel/src/main/manpages/com/sun/enterprise/v3/admin/delete-system-property.1, nucleus/core/kernel/src/main/manpages/com/sun/enterprise/v3/admin/list-system-properties.1, nucleus/core/kernel/src/main/manpages/fish/payara/enterprise/admin/create-system-property.1
- Resolves FISH-10318
- Adds a `create-system-property` asadmin command.
- Adds an associated manpage.
- Adjusts existing manpages for relevant commands to refer to the new one.
- Built the server and used the command to create a new system property.  
- Verified the property exists with the `list-system-properties` command.
=> FISH-10318 Add create-system-property command

appserver/web/web-core/src/main/java/org/apache/catalina/connector/Response.java
`java.lang.IllegalStateException: Cannot change buffer size after data has been written` when buffer size needs to be incremented
None
None
1. Start the Payara server and make sure HTTP/2 and HTTP/2 push are enabled.
2. Deploy the war file from [web1-0.0.1-SNAPSHOT-p6.war](https://github.com/luiseufrasio/fish-61/blob/main/web1-0.0.1-SNAPSHOT-p6.war)
3. Quickly hard reload the index page (https) in the browser (CTRL + F5).
4. No more errors in the log
Zulu JDK 11 on Windows 11 with Maven 3.9.0
None
=> FISH-61 : only checking if response was commited

nucleus/core/kernel/pom.xml, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/commands/CLIUtil.java, nucleus/core/kernel/src/main/java/fish/payara/enterprise/admin/CreateSystemProperty.java, nucleus/core/kernel/src/main/java/fish/payara/enterprise/admin/commands/CreateJvmOption.java, nucleus/core/kernel/src/main/java/fish/payara/enterprise/admin/commands/LocalStrings.properties, nucleus/core/kernel/src/main/manpages/fish/payara/enterprise/admin/commands/create-jvm-option.1
- Resolves FISH-10319
- Adds `create-jvm-option` asadmin command.
- Adds relevant manpage.
Used the command to create a new JVM option, verified the existence of the new option via the `list-jvm-options` command.
=> FISH-10319 Add create-jvm-option command

appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/BaseContainer.java, appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/StatelessContainerFactory.java, appserver/tests/quicklook/cluster/clustersetup/src/test/clustersetup/ClusterSetupTest.java, appserver/tests/quicklook/testng/testng_gd.xml, appserver/tests/quicklook/testng/testng_gd_security.xml, appserver/tests/quicklook/web/helloworld/src/test/HelloJSPTestNG.java
Enabling quicklook test
this is to enable the previous quicklook test that were disabled to pass Payara 7 tests 
executing the quicklook tests on local environment:
here the results:
Linux Ubuntu 20.04, Azul JDK 21, Maven 3.9.9
=> Fish-10300: enabling quicklook tests

appserver/extras/docker-images/micro/src/main/docker/Dockerfile, appserver/extras/docker-images/micro/src/main/docker/bin/entrypoint.sh
Implement Docker Images Graceful Shutdown Support
None
None
Run in WSL:
1. export JAVA_HOME=/usr/lib/jvm/zulu11-ca-amd64 && export PATH=${JAVA_HOME}/bin:${PATH}
2. cd Payara
3. mvn clean install -DskipTests
4. cd appserver/extras/docker-images/server-full
5. mvn clean package
6. cd target/docker
7. docker build -t payara/server-full:local -f ./payara/server-full/build/Dockerfile.jdk11 ./payara/server-full/tmp/docker-build/
8. docker run -it -p 8080:8080 -p 4848:4848 --name payara_docker payara/server-full:local
9. open another WSL Tab
10. docker ps -a
11. docker stop <container_id>, it works with only the id's 3 first chars
12. It should show us the logs of stop-domain with a gracefull shutdown at the ORIGINAL WSL tab
Zulu JDK 11.0.11 on Ubuntu 22 with Maven 3.9.0
=> FISH-8859 FISH-10015 : design graceful shutdown of docker images community 6

api/payara-bom/pom.xml, appserver/extras/embedded/all/pom.xml, appserver/extras/embedded/web/pom.xml, appserver/extras/payara-micro/payara-micro-distribution/pom.xml, appserver/featuresets/payara-web/pom.xml, appserver/packager/data/pom.xml, appserver/packager/data/src/main/assembly/data.xml, appserver/packager/data/src/main/resources/pkg_proto.py, appserver/packager/external/jakarta-data-api/pom.xml, appserver/packager/external/pom.xml, appserver/packager/pom.xml, appserver/pom.xml, pom.xml
Adds the Jakarta Data API to Payara Server.
The published API doesn't have an OSGi manifest, so I have added one.
None
None
Ran against https://github.com/payara/jakartaee-10-tck-runners/pull/135 - signature test passes
Windows 11, Zulu JDK 21.0.6, Maven 3.9.9
N/A
None
=> FISH-9145 Add Jakarta Data API

appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java, appserver/deployment/javaee-full/src/main/java/org/glassfish/javaee/full/deployment/EarDeployer.java, appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java, appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/archivist/WebArchivist.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/ACLSingletonProvider.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/BeanDeploymentArchiveImpl.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/BeanManagerNamingProxy.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/DeploymentImpl.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/GlassFishWeldProvider.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/RootBeanDeploymentArchive.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/ValidationNamingProxy.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/JCDIServiceImpl.java, appserver/web/weld-integration/src/test/java/org/glassfish/weld/services/JCDIServiceImplTest.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/ASURLClassLoader.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/CacheCleaner.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/CachingReflectionUtil.java, nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/DirWatcher.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java, nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/DeploymentContextImpl.java
Bugfix. BeanManager isn't properly constructed when multiple CDI WARs exist in an EAR.
Also allows EAR-libraries to be scanned for CDI annotations
fixes #7031 
also fixes #7078 
Appears specifically when multiple WARs use OmniFaces
This is the *head* PR in the CDI-performance and modernization sequence.
PRs #7165 and #7097 depend on this PR
Tested with the failing reproducer
** Needs TCK run
=> FISH-10049 bugfix: Split CDI bean deployment when multiple WARs exist in an EAR

appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/api/ConnectorClassLoaderServiceImpl.java, appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/api/ConnectorsClassLoaderUtil.java, appserver/web/gf-weld-connector/src/main/java/org/glassfish/weld/connector/WeldUtils.java, appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/annotation/impl/WarScanner.java, appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/archivist/WebArchivist.java, appserver/web/web-glue/src/main/java/org/glassfish/web/deployment/descriptor/WebFragmentDescriptor.java, appserver/web/web-naming/src/main/java/org/apache/naming/resources/WebDirContext.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/DeploymentImpl.java, nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/DeploymentContextImpl.java, nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/DeploymentUtils.java, nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/InstalledLibrariesResolver.java
Dependencies can be copied to `<domain_dir>/lib/warlibs/` and use no-dependency skinny-war
for deployments, significantly improving deployment times.
This can be done by layered docker deployment as well.
This will reduce application redeployment times by orders of magnitude 
Able to deploy real applications in half a second on my machine that used to take 15+ seconds
Fixes #6405 
PR #7165 depends on this PR
Applications need to be deployed with the following snippet to `asadmin`: `--properties warlibs=true` to take advantage of shared WAR libraries. This is to prevent unnecessary loading of shared libraries with non-development applications, such as admin console or other applications that will fail if shared WAR libraries are loaded.
Tested skinny WAR deployment
See …
=> FISH-10286 Enhancement: Use <domain_dir>/lib/warlibs to enable fast deployments

appserver/web/war-util/src/main/java/com/sun/enterprise/glassfish/web/WarHandler.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/TomcatDeploymentConfig.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModule.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/pwc/connector/coyote/PwcCoyoteRequest.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/session/SessionCookieConfig.java, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/session/WebSessionCookieConfig.java
- Resolves FISH-8545
- Makes Payara parse the payara-web.xml file correctly.
- Adds SameSite to various cookie configurations.
Tested against the reproducer.
=> FISH-8545 SameSite Cookie

appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/ComponentEnvManagerImpl.java, core/pom.xml
Updates Concurro to 3.1.0-M5, fixing the inherited typo 
None
None
Ran against Concurrency TCK, passed: https://jenkins.payara.fish/view/TCKs/job/JakartaEE-11-TCK/129/
Jenkins
N/A
None
=> FISH-10585 Update Concurro to 3.1.0-M5

api/payara-bom/pom.xml, appserver/common/container-common/pom.xml, appserver/packager/external/jakarta-ee11-shim/pom.xml, appserver/packager/glassfish-web/pom.xml, appserver/payara-appserver-modules/cdi-auth-roles/pom.xml, appserver/payara-appserver-modules/microprofile/jwt-auth/pom.xml, appserver/payara-appserver-modules/payara-micro-cdi/pom.xml, appserver/payara-appserver-modules/yubikey-authentication/pom.xml, appserver/pom.xml, appserver/security/realm-stores/pom.xml, appserver/web/web-core/src/main/java/org/apache/catalina/connector/AsyncContextImpl.java, appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java, core/pom.xml, nucleus/common/common-util/pom.xml
Using pure soteria 4 and upgrading weld to Final version
None
None
1. build server in WSL
2. cd jakartaee-10-tck-runners
3. git checkout FISH-10184-fix-authentication-failures
4. edit payara-profile.xml to comment 2 tests (https://payara.atlassian.net/browse/FISH-10181): 
```
```
5. jakartaee-10-tck-runners/security-tck$ ./run-tck.sh > /mnt/c/code/tck.txt
Zulu JDK 21 on Ubuntu 22.04 with Maven 3.9.0
=> FISH-10184 FISH-10185 FISH-10186 FISH-10187 : Pass Security TCK Tests

appserver/admingui/common/src/main/resources/appServer/serverInstAdminPassword.jsf, appserver/admingui/core/src/main/resources/templates/baseLayout.xhtml, appserver/admingui/payara-enterprise-theme/src/main/resources/branding/masthead.inc, appserver/admingui/payara-theme/src/main/resources/branding/masthead.inc, nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/provider/ActionReportResultHtmlProvider.java
Escapes HTTP characters in the REST interface, to help lock down any XSS attempts someone may try if they have access to the application server's filesystem.
Most config which would be displayed here is protected by validation of the domain.xml, as that prevents you from having the "<" or ">" characters as values. The key files however don't have this validation, and so we must escape them.
None
None
On a clean domain:
* Add the following to the `admin-keyfile` file under domain config: `user3<img src=x onerror=alert('XSS')>;{SSHA256}qXV9vLHbkJRoMaJkGsNUrz5jSHDzMTR0CyFmZjUt8HJQVlIi2X8XaA==;asadmin`
* Add the following to the `keyfile` file under domain config: `wibbles<img src=x onerror=alert('XSS')>;{SSHA256}6v8s3F0zGwF9bi9s1tygCvTz+az/Im55nS6Z3Z1sCIS9ng9aLAykCQ==;`
* Ping the REST …
=> FISH-10521 Escape HTTP Characters in REST Interface

core/pom.xml
Updating corba version to use new concurrency implementation
This is a feature to improve the concurrency functionality of the corba implementation when processing big messages. The process to read big messages cause to split in multiple fragments internally processed by multithread functionality. The reported issue from customer mentioned that in some moment most of the threads are in the wait state causing an startvation because any of those threads can get time to continue processing. This will impact the system using most of the resources available and in some moment restart the system to clear resources
You need to deploy the following EJB on the server:
[remoteview.zip](https://github.com/user-attachments/files/19061160/remoteview.zip)
And use the same as a lib for the following …
=> FISH-10526: update of corba to use new concurrency implementation instead of synchronized blocks

appserver/packager/external/jakarta-ee11-shim/pom.xml
Now that security connectors have been updated, we can remove the downgrade shim for Soteria and the Security API.
None
None
Started the DAS and loaded the admin console - no explosions.
Ran through the Jakarta TCKs - no OSGi issues to do with resolving the security connectors spotted.
Windows 11, Maven 3.9.9, Zulu 21.0.6
N/A
None
=> FISH-10073 Reduce EE11 Shim

core/pom.xml
Updates the security connectors to 4.0.0.alpha3, pulling in JSON Smart 2.5.2
https://github.com/payara/ecosystem-security-connectors/pull/384
None
Jenkins
Pending...
None
=> FISH-10576 Update Security Connectors to 4.0.0.alpha3

appserver/admingui/common/src/main/resources/configuration/loggerGeneral.jsf, appserver/admingui/common/src/main/resources/org/glassfish/common/FieldLengths.properties, appserver/admingui/common/src/main/resources/org/glassfish/common/admingui/Strings.properties, appserver/admingui/reference-manual/src/main/help/en/help/reference/set-log-attributes.html, nucleus/admin/template/src/main/resources/config/logging.properties, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/SyslogHandler.java, nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/SetLogAttributes.java, nucleus/core/logging/src/main/manpages/com/sun/enterprise/server/logging/commands/set-log-attributes.1
Adding ability to set the syslog host and changed the syslog message to include the logger name instead of glassfish and if no logger name is set use payara.
n/a
n/a
Connected to an ec2 instance with syslog enabled accepting udp 514 
https://github.com/payara/Payara-Documentation/pull/571
=> FISH-8950 Implement syslog host parameter

core/pom.xml
Updates Jersey to 3.1.10 with our outstanding patches reapplied
https://github.com/payara/patched-src-jersey/pull/234
None
I started the admin console - no explosions
Windows 11, Maven 3.9.9, Zulu JDK 11.0.26
N/A
None
=> FISH-10899 Update Jersey to 3.1.10.payara-p1

appserver/ejb/ejb-container/src/test/java/com/sun/ejb/containers/BaseContainerTest.java, appserver/jdbc/jdbc-runtime/src/test/java/org/glassfish/jdbcruntime/deployment/annotation/handlers/DataSourceDefinitionTest.java, appserver/payara-appserver-modules/hazelcast-ejb-timer/src/test/java/fish/payara/ejb/timer/hazelcast/HazelcastTimerStoreTest.java, appserver/payara-appserver-modules/microprofile/config-extensions/src/test/java/fish/payara/microprofile/config/extensions/hashicorp/HashiCorpSecretsConfigSourceTest.java, appserver/payara-appserver-modules/microprofile/rest-client-ssl/src/test/java/fish/payara/microprofile/jaxrs/client/ssl/RestClientSslContextAliasListenerTest.java, appserver/payara-appserver-modules/payara-micro-cdi/src/test/java/fish/payara/micro/cdi/extension/cluster/ClusterScopeContextTest.java, appserver/web/web-core/src/test/java/org/apache/catalina/core/StandardContextValveTest.java, appserver/web/web-glue/src/test/java/com/sun/enterprise/web/deploy/FilterDefDecoratorTest.java, appserver/web/weld-integration/src/test/java/org/glassfish/weld/services/JCDIServiceImplTest.java, core/pom.xml, nucleus/common/internal-api/src/test/java/org/glassfish/internal/deployment/GetApplicationNameTest.java, nucleus/core/logging/src/test/java/com/sun/enterprise/server/logging/LoggingExclusionTest.java, nucleus/core/logging/src/test/java/com/sun/enterprise/server/logging/LoggingPropertiesTest.java, nucleus/payara-modules/requesttracing-core/src/test/java/fish/payara/nucleus/requesttracing/RequestTracingServiceMockTest.java
Updated mockito version to 5.16.1 and adapted some tests to the new version
Ran mvn clean install
MacOS, JDK 11, Maven 3.9.9
=> Update Mockito dependency version to 5.16.1

appserver/admingui/jdbc/src/main/resources/advancePool.inc, appserver/admingui/jdbc/src/main/resources/jdbcConnectionPoolAdvance.jsf, appserver/admingui/jdbc/src/main/resources/org/glassfish/jdbc/admingui/Strings.properties, appserver/jdbc/admin/src/main/java/org/glassfish/jdbc/admin/cli/CreateJdbcConnectionPool.java, appserver/jdbc/admin/src/main/java/org/glassfish/jdbc/admin/cli/JDBCConnectionPoolManager.java, appserver/jdbc/admin/src/main/manpages/org/glassfish/jdbc/admin/cli/create-jdbc-connection-pool.1, appserver/jdbc/jdbc-config/src/main/java/org/glassfish/jdbc/config/JdbcConnectionPool.java, appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/common/DataSourceSpec.java, appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/ManagedConnectionFactoryImpl.java, appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/ManagedConnectionImpl.java, appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/base/ConnectionHolder.java, appserver/jdbc/jdbc-ra/jdbc40/src/main/java/com/sun/gjc/spi/jdbc40/ConnectionHolder40.java, appserver/jdbc/jdbc-runtime/src/main/java/org/glassfish/jdbc/deployer/DataSourceDefinitionDeployer.java, appserver/jdbc/jdbc-runtime/src/main/java/org/glassfish/jdbcruntime/service/JdbcServiceConfigListener.java, appserver/resources/resources-connector/src/main/java/org/glassfish/resources/admin/cli/ResourceConstants.java, appserver/resources/resources-connector/src/main/java/org/glassfish/resources/admin/cli/ResourcesXMLParser.java
Add option to admin console to skip client info validation.
Also throw a restart required when changed.
n/a
none
Deployed an simple jpa example from Payara-Examples to verify if client info was skipped when set.
Also verified behaviour isn't changed dynamically
Java version: 21.0.5, vendor: Azul Systems, Inc., runtime: /Users/kalinchan/.sdkman/candidates/java/21.0.5-zulu/zulu-21.jdk/Contents/Home
OS name: "mac os x", version: "15.1.1", arch: "aarch64", family: "mac"
https://github.com/payara/Payara-Documentation/pull/578
=> FISH-9749 Add option to skip jdbc client info validation

nucleus/admin/server-mgmt/src/main/manpages/com/sun/enterprise/admin/servermgmt/cli/create-domain.1, nucleus/cluster/cli/src/main/manpages/com/sun/enterprise/admin/cli/cluster/create-local-instance.1
- Resolves FISH-10914
- Adds the `--masterpasswordlocation` parameter to the help pages for `create-domain` and `create-local-instance`.
Used the `asadmin help` command to view the changed manpages.
=> FISH-10914 Add Missing Help Text

appserver/data/data-core/pom.xml, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/cdi/extension/DynamicInterfaceDataProducer.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/cdi/extension/JakartaDataExtension.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/cdi/extension/QueryData.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/cdi/extension/QueryType.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/cdi/extension/RepositoryImpl.java, appserver/persistence/jpa-container/src/main/java/org/glassfish/persistence/jpa/JPADeployer.java
Adding implementation of simple CRUD operations using jakarta data interfaces
This is a feature to include the execution of CRUD operations using the Jakarta Data interfaces
Manual testing using the following r
[JakartaDataReproducer.zip](https://github.com/user-attachments/files/19769500/JakartaDataReproducer.zip)
eproducer:
The current implementation on the server can resolve the following operation for a simple entity on the default database on Payara Server:
We need a class  on an application that implements the CrudRepository interface and also this interface should need to be annotated by the annotation @Repository, here the example:
where the Author is a valid entity defined on the application that follows Jakarta Persistence rules for its definition
then on the application we can …
=> FISH-10499: Adding simple crud operation using jakarta data interface methods

core/core-parent/pom.xml, core/pom.xml
The experiment is over, we have decided that getting the codebase into a less monolithic state with individually versioning APIs and modules is too much effort, and even when complete adds a lot of mental overhead for all of the different versions of Enterprise we support and adds complexity to any attempt to stagger changes between Community and Enterprise.
This is the first PR of a few which will look to remove the concept of Core vs. Server.
Step 1 (FISH-10805) - removing the semantic versioning enforcement we have.
None
None
* Built the server - no errors.
* Made a breaking API change and compiled the module - no errors
Windows 11, Maven 3.9.9, Zulu Java 11.0.26
_Pending..._
None
=> FISH-10805 Remove Semantic Versioning Check from Payara Core

appserver/tests/payara-samples/micro-programmatic/pom.xml, appserver/tests/payara-samples/micro-programmatic/src/test/java/fish/payara/samples/programatic/CustomErrorPageTest.java, appserver/tests/payara-samples/micro-programmatic/src/test/java/fish/payara/samples/programatic/DataGridTest.java, appserver/tests/payara-samples/micro-programmatic/src/test/java/fish/payara/samples/programatic/StartPayaraMicroWithNoClusterTest.java, appserver/tests/payara-samples/micro-programmatic/src/test/resources/custom-404.html, appserver/web/web-glue/src/main/java/com/sun/enterprise/web/VirtualServer.java
When specifying a custom error page within a preboot file, this wouldn't work due to the property being parsed incorrectly.
This PR will strip the property value of any additional quotation marks.
i.e.
property = "code=500 reason=example path=/wibbles/wobbles.html"
will result in = code=500 reason=example path=/wibbles/wobbles.html
Note the stripped quotation marks.
n/a
Created payara micro programmatic test 
go to payara-samples directory and run `mvn clean verify -Ppayara-micro-managed -Dpayara.version=6.2025.5-SNAPSHOT -Dtest=CustomErrorPageTest` (might have to comment out other modules)
1. Created a 404 html page somewhere on my local device.
2. Created preboot command to specify the property:
`set configs.config.server-config.http-service.virtual-server.server.property.send-error_1="c …
=> FISH-10876 Fix error page property parsing

pom.xml
Moves the definition of this repository to the "default" repository block and has it enabled/disabled via properties. This keeps the repository order intact by having them polled after all of the standard set of repositories - when they are added by profile they get queried first.
None
None
Wiped local maven repo, built server with profile enabled, inspect logs - payara-nexus-staging is not queried first.
Windows 11, Maven 3.9.9, Zulu 11.0.26
N/A
None
=> Move `payara-nexus-staging` Repository

nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/domain/DomainBuilder.java, nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/pe/LocalStrings.properties, nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/pe/PEDomainsManager.java, nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/ChangeNodeMasterPasswordCommand.java, nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/CreateLocalInstanceCommand.java, nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/LocalStrings.properties
- Resolves FISH-10958
- If the user supplies an invalid master password location, the command will fail before changing the master password.
- Additionally applied a similar change to `create-domain` and `create-local-instance`.
-Followed the reproducer: attempt to change password with a non-existent master password path, check the command output, check if the password has still been changed.
- Attempt to create a domain with an invalid master password location, command fails and no domain is created.
- Attempt to create a local instance with an invalid master password location, command fails and no instance is created.
OS name: "windows 11", version: "10.0", arch: …
=> FISH-10958 Invalid Password Location Handling

appserver/packager/rest-monitoring/pom.xml, appserver/payara-appserver-modules/rest-monitoring/rest-monitoring-war/pom.xml, nucleus/pom.xml
This shouldn't be 1.0.0-Beta anymore really - the inherited dependencies and build config has changed over time
None
None
* Started the server
* Set all monitoring levels to _High_ and enabled the monitoring service at _Admin Console > Configurations > server-config > Monitoring_ 
* Set _AMX_ to true under Set all monitoring levels to _High_ and enabled the monitoring service at _Admin Console > Configurations > server-config > Monitoring > JMX_ 
* Enabled REST Monitoring at Set all monitoring levels to _High_ and enabled the monitoring service at _Admin Console > Configurations > server-config > Monitoring > JMX > REST_
* Restarted the domain
* Pinged http://localhost:4848/rest-monitoring/rest/read/java.lang:type=Memory - got data.
Windows 11, Zulu JDK 11.0.26, Maven 3.9.9
Later™
None
=> Align REST Monitoring WAR Version

appserver/admingui/faces-compat/pom.xml, pom.xml
There appears to be an issue with all versions higher than 3.10.0 that causes the aggregate JAR to be empty.
None
None
* Create empty build repo for testing: `mkdir D:\Downloads\Maven2`
* Create empty deployment repo for testing: `mkdir D:\Downloads\Maven3`
* Built and deploy the server using these directories: `mvn clean deploy -PBuildEmbedded "-Dmaven.repo.local=D:\Downloads\Maven2" "-DaltDeploymentRepository=local::file:///D:\Downloads\Maven3" -DskipTests -T 1C` - javadoc for payara-api is correctly generated (not an empty jar) and deployed as expected
* Generate the aggregate Server javadoc: `mvn pre-site -Pjavadoc "-Dmaven.repo.local=D:\Downloads\Maven2"` - javadoc (available under `Payara/target`) is correctly generated (not an empty jar), containing docs for the `com`, `org`, and …
=> FISH-10996 Fix Aggregate Javadoc Generation

appserver/flashlight/btrace/pom.xml, appserver/flashlight/client/pom.xml, nucleus/flashlight/agent/pom.xml, nucleus/flashlight/flashlight-extra-jdk-packages/pom.xml, nucleus/flashlight/framework/pom.xml
They were pointing at nucleus common and appserver common, which provide no extra config on top of their own parents. I assume they were moved out of these directories at some point and erroneously retained the original parent.
None
None
Wiped maven repo.
Built server - everything resolved.
Windows 11, Zulu JDK 11.0.26, Maven 3.9.9
N/A
None
=> FISH-10997 Fix Flashlight Module Parents

nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/AddLibraryCommand.java, nucleus/deployment/admin/src/main/manpages/org/glassfish/deployment/admin/add-library.1
- Resolves FISH-11137
1. Built the [example project](https://github.com/flowlogix/cdi-scanning).
2. Used `asadmin add-library --type=war <filename>` for the example library.
3. Verified the warlib was sent to the correct folder (domain1/lib/warlibs)
4. Restarted the server.
5. Deployed the example application from the example project.
Java version: 21.0.3, vendor: Eclipse Adoptium
=> FISH-11137 Add warlibs support to add-library command.

appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/api/visitor/ApiVisitor.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/config/OpenApiConfiguration.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/model/util/ModelUtils.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/processor/ApplicationProcessor.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/impl/visitor/OpenApiWalker.java, appserver/payara-appserver-modules/microprofile/openapi/src/main/java/fish/payara/microprofile/openapi/util/BeanValidationType.java, appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/impl/visitor/OpenApiWalkerTest.java, appserver/payara-appserver-modules/microprofile/openapi/src/test/java/fish/payara/microprofile/openapi/test/app/application/BeanValidationTest.java
This PR adds support for scanning BeanValidation annotations in Microprofile OpenAPI
n/a
Created BeanValidationTest.java to test additional use cases not verified by the TCK
Ran Payara OpenAPI tests and the Microprofile OpenAPI TCK
[INFO] Tests run: 317, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 31.389 s - in TestSuite
[INFO]
[INFO]
[INFO] Tests run: 317, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] Tests run: 142, Failures: 0, Errors: 0, Skipped: 0
Java version: 11.0.26, vendor: Azul Systems, Inc., runtime: /Users/kalinchan/.sdkman/candidates/java/11.0.26-zulu/zulu-11.jdk/Contents/Home
Default locale: en_GB, platform encoding: …
=> FISH-11054 Add Microprofile OpenAPI Bean Validation support

pom.xml
Fixes broken Admin UI styling in Payara 7
Rebased the patched Payara Admin UI styling on Glassfish Woodstock 6.0.1 for Payara 7
[https://github.com/payara/patched-src-glassfish-woodstock/pull/4]
git clone git@github.com:jtarry-payara/patched-src-glassfish-woodstock.git
cd patched-src-glassfish-woodstock
git checkout 6.0.1.payara-p1
mvn clean install
git clone git@github.com:jtarry-payara/Payara.git
cd Payara
git checkout FISH-11207-adminui-woodstock-patch-6.0.1.payara-p1
mvn clean install -Pjakarta-staging -T 16
Ubuntu 24.04
openjdk 21.0.7
Maven 3.9.9
Also updated copyright year to 2025
=> FISH-11207 Updated woodstock jsf to 6.0.1.payara-p1

pom.xml
Partially revert https://github.com/payara/Payara/pull/7447 by downgrading to 3.30.2.
JLine 3.30.4 and 3.30.3 seem to cause issues with the terminal specifically in Linux (including Git Bash and WSL). Powershell seems OK
There seems to be issues with displaying the prompts and the output of some commands (though it does still accept input). For example:
```
admin change-admin-password
Enter admin user name [default: admin]>
password
password
andrew@Pandrex-PC:~/Git/Payara> 
asadmin list-log-attributes
Authentication failed with password from login store: /home/andrew/.gfclient/pass
Enter admin password for user "admin">
andrew@Pandrex-PC:~/Git/Payara>
```
None
None
Ran the commands listed in the description - log attributes were displayed and the change-admin-password command correctly …
=> FISH-11414 Downgrade JLine to 3.30.2

appserver/admingui/cluster/src/main/java/fish/payara/cluster/admingui/PayaraClusterHandlers.java, appserver/admingui/cluster/src/main/resources/dg/dgNew.jsf, appserver/admingui/cluster/src/main/resources/org/glassfish/cluster/admingui/Strings.properties, appserver/admingui/cluster/src/main/resources/shared/instanceNew.inc
There was same message for missing name of Instance and Deployment Group. This fix makes them separate.
Also i18n was used instead of a hardcoded message.
Steps to Reproduce:
* Go to deployment groups
* Click “New…”
* Do NOT enter Deployment Group Name nor click Auto Name
* Click OK
* A message “No deployment group name provided and Auto Name is not enabled.”
Similarly with Instances, the message will be "No instance name provided and Auto Name is not enabled.".
Linux, OpenJDK 21
=> FISH-11198 Fix Missing Message for Empty Deployment Group Name

appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/ComponentEnvManagerImpl.java, appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/FactoryForEntityManagerFactoryWrapper.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/EntityManagerReferenceDescriptor.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/node/PersistenceUnitNode.java, appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/xml/PersistenceTagNames.java, appserver/web/weld-integration/src/main/java/org/glassfish/cdi/persistence/AnnotationInvocationHandler.java, appserver/web/weld-integration/src/main/java/org/glassfish/cdi/persistence/PersistenceExtension.java, appserver/web/weld-integration/src/main/resources/META-INF/services/jakarta.enterprise.inject.spi.Extension
Initial CDI Persistence Extension.
Not fully passing the TCK yet, but an incremental improvement from not passing at all.
Failures still to resolve:
* ServletEMLookupTest#injectUtilitiesUsingQualifier
None
None
Ran the `ee.jakarta.tck.persistence.ee.cdi.ServletEMLookupTest` Persistence Platform TCK test
```
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0
```
Kicked off TCK runs (pending results):
* "Passing" Platform: [JakartaEE-11-TCK#242](https://jenkins.payara.fish/view/TCKs/job/JakartaEE-11-TCK/242/)
* "Passing" Web Profile: [JakartaEE-11-TCK#243](https://jenkins.payara.fish/view/TCKs/job/JakartaEE-11-TCK/243/)
* Persistence (not currently included in "passing"): [JakartaEE-11-TCK#244](https://jenkins.payara.fish/view/TCKs/job/JakartaEE-11-TCK/244/)
Windows 11, Maven 3.9.10, Zulu …
=> FISH-11296 Initial CDI Persistence Extension

appserver/admingui/common/src/main/resources/security/realms/realmAttrs.inc
FISH-11465 changed realmAttrs so that the extra properties are set to visible if the condition is met (if the realm class name = the specific section)
in `realmAttrs` the extra properties visibility was set to false which resulted in them not showing. I have changed it so that the extra properties are visible if the class matches. It makes sure it displays the correct section relating to the class name.
Run Payara 6, Security > Realms > fileRealm > make sure extra properties is visible > change something & save > reload realm to make sure change is made
=> FISH-11465 Existing Realms Don’t Display Any Properties, Just Name - Fix Missing Properties

appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/util/DataCommonOperationUtility.java
Because Iterable types are considered like entity types themselves, this results in multiple results in DataCommonOperationUtility#processReturnType being rejected by single object return validations in that method.
None
Manually tested http://localhost:8080/JakartaDataReproducer-1.0-SNAPSHOT/api/personas/updatePersonaIterable now works.
Also manually tested all endpoints on payara/Payara/pull/7494 .
Zulu 21.0.7, Windows 11, apache-maven-3.9.9
The 2nd commit is not necessary to fix the issue, but maybe an improvement?
=> FISH-11604 Not extracting entity types from Iterable parameter/return types

appserver/tests/payara-samples/samples/client-certificate-validator/pom.xml, appserver/tests/payara-samples/samples/http/pom.xml, appserver/tests/payara-samples/samples/pom.xml
Re-enable tests which seem to have been disabled since EE10
Ports across fix from https://github.com/payara/Payara/pull/7534
None
None
Ran tests locally against payara-server-managed profile
Windows 11, Maven 3.9.10, Zulu JDK 11.0.27
N/A
None
=> FISH-11682 Re-enable Tests

appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/cdi/extension/DynamicInterfaceDataProducer.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/util/QueryOperationUtility.java
When testing the `@Query` annotation for the following endpoint: `http://localhost:8080/JakartaDataReproducer-1.0-SNAPSHOT/api/personas/findPersonByLastNameWithQueryLimited/Valdez/5`  got the error: `java.lang.ClassCastException: class fish.payara.server.jakartadatareproducer.model.Person cannot be cast to class [Lfish.payara.server.jakartadatareproducer.model.Person; (fish.payara.server.jakartadatareproducer.model.Person and [Lfish.payara.server.jakartadatareproducer.model.Person; are in unnamed module of loader org.glassfish.web.loader.WebappClassLoader @2fa53dd9)`
None
None
1. http://localhost:8080/JakartaDataReproducer-1.0-SNAPSHOT/api/personas/insertPersonasRandom/10
2. Choose 1 surname which repeats
3. Fill SURNAME_CHOSEN_HERE and call …
=> FISH-11605 Query operation failed to return array of data

pom.xml
Updates Hazelcast to 5.3.8, with an additional CP subsystem fix backport.
Review, merge, and publication of Hazelcast 5.3.8-payara-1
https://github.com/payara/patched-src-hazelcast/pull/8
None
Ran through Jakarta TCKs
* https://jenkins.payara.fish/view/TCKs/job/TCK-Suite/1066/
* https://jenkins.payara.fish/view/TCKs/job/TCK-Suite/1067/
* https://jenkins.payara.fish/view/TCKs/job/JakartaEE-10-TCK/583/
* https://jenkins.payara.fish/view/TCKs/job/JakartaEE-10-TCK/584/
Did additional testing noted here: https://payara.atlassian.net/browse/FISH-10878?focusedCommentId=107324
Jenkins
N/A
None
=> FISH-10878 Upgrade Hazelcast to 5.3.8 with Additional CP Fix Backport

appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/util/AmbiguousPersistenceUnitException.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/util/DataCommonOperationUtility.java, appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/util/UnambiguousPersistenceUnitException.java
Introduces a new property "fish.payara.data.usePU" to specify the persistence unit to use when multiple are present.
Only uses the one which is true, if there are multiple, an exception is thrown.
n/a
n/a
Added another persistence unit:
```
<persistence-unit name="pu2" transaction-type="JTA">
<provider>org.eclipse.persistence.jpa.PersistenceProvider</provider>
<jta-data-source>jdbc/__default</jta-data-source>
<properties>
<property name="fish.payara.jakarta.data.usePU" value="true"/>
</properties>
</persistence-unit>
```
=> FISH-11591 Jakarta Data - Add resolution for multiple persistence units

appserver/data/data-core/src/main/java/fish/payara/jakarta/data/core/cdi/extension/JakartaDataExtension.java
Changes to pass CDI TCK tests preventing the usage of different providers and custom entity annotations
This is a fix to pass Jakarta Data TCK with test related to validate CDI test cases
Running the Jakarta Data TCK and passing the failures from the CDITests configuration:
Ubuntu 20.04, Maven 3.9.9, zulu JDK 21
=> Fish-11777: fixing CDI Test for Jakarta Data TCK

nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/CollectLogFiles.java
FISH-11698 collect-log-files does not collect from custom location
Previously, if ${com.sun.aas.instanceRoot} was in the path, it would change it to `env.getInstanceRoot`/logs. This means if the user had a custom path as `${com.sun.aas.instanceRoot}/logs/newlogs/server.log` It would overwrite that path and not use the newlogs directory.
Tested the command with and without ${com.sun.aas.instanceRoot}.
=> FISH-11698 collect-log-files does not collect from custom location

appserver/data/data-core/src/main/java/fish/payara/data/core/cdi/extension/RepositoryImpl.java, appserver/data/data-core/src/main/java/fish/payara/data/core/util/DeleteOperationUtility.java, appserver/data/data-core/src/main/java/fish/payara/data/core/util/FindOperationUtility.java, appserver/data/data-core/src/main/java/fish/payara/data/core/util/QueryOperationUtility.java
Fix IllegalArgumentExceptions from Jakarta Data TCK results
This is a fix to resolve TCK errors reported from Jakarta Data TCK
Manual testing executing the Jakarta Data TCK:
`
[ERROR] Errors:
[ERROR]   EntityTests.testLiteralTrue » Runtime jakarta.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 5.0.0-B08.v202505280949-dfc411d38767f696ce9f2741de051aef050cbeba): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "ID" must be in the GROUP BY list; SQL statement:
SELECT COUNT(ID) FROM NATURALNUMBER WHERE ((ISODD = ?) AND (ID BETWEEN ? AND ?)) ORDER BY ID ASC [90016-224]
Error Code: 90016
Call: SELECT COUNT(ID) FROM NATURALNUMBER WHERE ((ISODD = ?) AND (ID BETWEEN ? AND ?)) …
=> Fish 11806 fix illegalargumentexception from entity tests

appserver/transaction/jts/src/main/java/com/sun/enterprise/transaction/jts/JavaEETransactionManagerJTSDelegate.java, appserver/transaction/jts/src/main/java/com/sun/jts/jta/TransactionManagerImpl.java, appserver/transaction/jts/src/main/java/com/sun/jts/jta/TransactionServiceProperties.java, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/event/EventTypes.java, nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/AppServerStartup.java
Provides two potential opt-out fixes for the resource adaptor deployment vs. transaction recovery race condition. This is a race condition that may occur if you have a resource that utilises a custom resource adaptor (as in, one that must be deployed to the server) - the resource adaptor may not be deployed by the time the transaction recovery thread attempts to utilise it.
Both fixes allow opting-out for now until we're sure everything is fine.
The startup time of the above threads getting kicked off is defined by `TransactionLifecycleService`. This has a service run level of 10 (`StartupRunLevel`), but the actual timing of the threads being kicked off is the `SERVER_READY` event, which gets sent by `AppServerStartup`.
This `SERVER_READY` event is currently sent very shortly after the …
=> FISH-11585 Fix Resource Adapter Transaction Recovery Race Condition

appserver/extras/docker-images/pom.xml
Upgrades the Docker JDKs to 21.0.8
None
None
Ran Docker unit tests - all passed.
Windows 11
N/A
None
=> FISH-11924 Upgrade Docker JDK to 21.0.8

appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/InjectionServicesImpl.java
This is a fix that restores `@Resource` annotation injection functionality that was broken after PR #5883 removed ResourceInjectionServices. The removal of ResourceInjectionServices was intended to fix issues with simple environment entries and EJB interceptor JNDI naming, but inadvertently broke injection of JNDI resources like mail sessions, data sources, and other resources that use `@Resource` annotation in CDI-managed beans.
The fix adds direct processing of `@Resource` annotations within InjectionServicesImpl.aroundInject() method to handle resource injection while maintaining the improvements from PR #5883.
- Related to PR #5883 and #5881 which removed ResourceInjectionServices
- Fixes regression where `@Resource` injection returns null in Payara 6 (worked in Payara 5)
- Tested …
=> [FISH-11590] : handling `@Resource` annotations

pom.xml
This reverts commit e78690e7d2618f3efd03913d665edb74b8060c20 / https://github.com/payara/Payara/pull/7616
Breaks our run of the Jakarta TCK.
Investigation of whether it's our runner causing this pending.
None
None
Ran Jakarta EE TCK Signature test and Mail TCKs - green.
Jenkins
N/A
None
=> FISH-11959 FISH-12071 Revert "Bump jakarta.mail:jakarta.mail-api from 2.1.3 to 2.1.4"

Jenkinsfile
Fixes the maven resolution issues with MicroProfile TCKs.
We need to stop relying on overriding with `-Dpayara.version` - it isn't foolproof. Notably, ShrinkWrap resolver explicitly reads the POM as-is and ignores any command line overrides, which can lead to issues and misaligned versions.
Also includes some small misc. improvements
None
None
Jenkins
N/A
None
=> FISH-12141 Update POMs for Shrinkwrap

appserver/admingui/cluster/src/main/resources/dg/dgGeneral.jsf, appserver/admingui/cluster/src/main/resources/dg/dgs.jsf, appserver/admingui/common/src/main/resources/org/glassfish/common/admingui/Strings.properties, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ClusterCommandHelper.java, nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ListInstancesCommand.java, nucleus/cluster/admin/src/main/java/fish/payara/admin/cluster/ExecutorServiceFactory.java, nucleus/cluster/common/src/main/java/com/sun/enterprise/util/cluster/InstanceInfo.java, nucleus/cluster/common/src/main/java/com/sun/enterprise/util/cluster/LocalStrings.properties, nucleus/common/glassfish-api/src/main/java/org/glassfish/api/admin/InstanceState.java
- Modified `ClusterCommandHelper.java` to use `ExecutorServiceFactory` for thread pool management when executing commands on cluster instances, factoring out thread pool creation
- Introduced `ExecutorServiceFactory.java` to encapsulate the creation of `ExecutorService` instances
- Modified `ListInstancesCommand.java` to retrieve instance information in parallel using an `ExecutorService`
- Modified `InstanceInfo.java` to handle `TimeoutException`, setting the state to `UNKNOWN` 
- Updated `Strings.properties` and `LocalStrings.properties` to add support for new `Unknown` state with corresponding image and text.
See https://payara.atlassian.net/browse/FISH-12070
- Created deployment group with remote instances
- Slowdown network on remote instances so they don't respond within timeout …
=> FISH-11174 Get instance info in parallel & display timeouts as Unknown

nucleus/deployment/admin/src/main/java/fish/payara/deployment/admin/DeployRemoteArchiveCommand.java, nucleus/deployment/admin/src/main/manpages/org/glassfish/deployment/admin/redeploy.1
Allows using the new `--warlibs` parameter with the `deploy-remote-archive` command.
Also adds missing help docs for the redeploy command
N/A
None
```
git clone https://github.com/lprimak/apps/ Lenny-Apps
cd Lenny-Apps/starter-generator
mvn dependency:copy-dependencies
mvn package -Dskinny.war
asadmin start-domain
asadmin add-library --type war target\dependency\*
asadmin restart-domain
asadmin deploy-remote-archive --name sg https://github.com/Pandrex247/Payara/raw/refs/heads/TESTING/starter-generator-1.x-SNAPSHOT.war
asadmin deploy-remote-archive --name sg --warlibs https://github.com/Pandrex247/Payara/raw/refs/heads/TESTING/starter-generator-1.x-SNAPSHOT.war
asadmin undeploy sg
asadmin deploy-remote-archive --name sg --properties "warlibs=true" …
```
=> FISH-12093 FISH-12132 Allow `--warlibs` with the `deploy-remote-archive` Command

appserver/concurrent/concurrent-impl/pom.xml, appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/admin/listener/ResourcesConfigListener.java, appserver/concurrent/concurrent-impl/src/main/resources/org/glassfish/concurrent/admin/LocalStrings.properties, appserver/concurrent/concurrent-impl/src/test/java/org/glassfish/concurrent/admin/VirtualThreadsUnprocessedEventsTest.java, appserver/concurrent/concurrent-impl/src/test/resources/VirtualThreadsUnprocessedEventsTest.xml
https://payara.atlassian.net/browse/FISH-10834
Adds a `ConfigListener` which creates `UnprocessedChangeEvents` when the `use-virtual-threads` setting is changed for `ManagedExecutorService`, `ManagedScheduledExecutorService`, and `ManagedThreadFactory` which are server resources.
N/A
New unit test added in PR. It tests creating a new ManagedExecutorService and asserts if changing the the use-virtual-threads property on it causes the `UnprocessedChangeEvent` to be created.
Manual testing via Admin console and asadmin commands carried out.
After researching the topic I believe the only indicator of when a server restart is required is under: Common Tasks > Server . There you will see "Status: Restart Required".
Similarly when using the asadmin comment, you need to execute the following …
=> FISH-10834 Indicate server restart required for Virtual Threads config change

appserver/extras/docker-images/tests/src/test/java/fish/payara/jcache/JCacheRestTest.java
Adjusts the Docker Jcache test so that it reads in the payara.version property, rather than always relying on "latest"
None
None
Built Docker image and ran test - all passed
Ran tests with "-Dpayara.version=6.2025.8" - logs indicated 6.2025.8 was being used and tests passed.
Windows 11, Maven 3.9.11, Zulu JDK 11.0.28
N/A
None
=> Read in `payara.version` to Docker Jcache Test
